import AccessibleDialog from "../components/AccessibleDialog";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {supabase} from "../supabase";
import {useMemberAuth} from "../lib/memberAuth";
import {useLocalization} from "../lib/localization";
import {useAccessControl} from "../lib/accessControl";
import {notifyActionsBySourceId} from "../lib/operationalNotifications";
import {AttendanceRow,attendanceHours,attendanceKind,attendanceTotals,readAllRows,israelDayStart,israelDayEnd} from "../lib/attendanceReporting";
import "../styles/attendanceReporting.css";
type Member={id:string;display_name:string;subteam:string|null;active?:boolean};
type Meeting={id:string;title:string;starts_at:string;ends_at:string;status:string;calendar_event_id:string|null;opened_by:string|null;closed_by:string|null;opened_at:string|null;closed_at:string|null;opened_automatically:boolean;closed_automatically:boolean};
type CalendarEvent={id:string;title:string;starts_at:string;ends_at:string;mandatory:boolean};
type Absence={id:string;member_id:string;calendar_event_id:string;reason:string;status:string;reviewer_note:string|null;reviewed_by:string|null;reviewed_at:string|null;created_at:string};
const attendanceColumns="id,member_id,meeting_id,checked_in_at,checked_out_at,check_in_method,check_out_method,correction_reason,corrected_by";
export default function AttendanceReportsPage(){
 const {profile}=useMemberAuth(),{pick,language}=useLocalization(),access=useAccessControl(),[params,setParams]=useSearchParams();
 const canReview=Boolean(profile&&(profile.role==="admin"||profile.role==="mentor"||access.can("view_team_reports"))),canApproveAbsence=Boolean(profile&&["admin","mentor"].includes(profile.role)),canRoster=Boolean(profile&&(profile.role==="admin"||profile.role==="mentor"||access.can("correct_attendance")));
 const requestedView=params.get("view"),requestedEvent=params.get("event")??"";
 const [view,setView]=useState<"overview"|"absences"|"roster">(requestedView==="absences"?"absences":requestedView==="roster"&&canRoster?"roster":"overview");
 const [period,setPeriod]=useState("month"),[customFrom,setCustomFrom]=useState(""),[customTo,setCustomTo]=useState(""),[search,setSearch]=useState(""),[team,setTeam]=useState(""),[sort,setSort]=useState("name");
 const [records,setRecords]=useState<AttendanceRow[]>([]),[members,setMembers]=useState<Record<string,Member>>({}),[meetings,setMeetings]=useState<Meeting[]>([]),[events,setEvents]=useState<CalendarEvent[]>([]),[absences,setAbsences]=useState<Absence[]>([]),[selectedMember,setSelectedMember]=useState<string|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false);
 const [showRequest,setShowRequest]=useState(Boolean(requestedEvent)),[eventId,setEventId]=useState(requestedEvent),[reason,setReason]=useState(""),[reviewing,setReviewing]=useState<{request:Absence;decision:"approved"|"rejected"}|null>(null),[reviewNote,setReviewNote]=useState("");
 const [meetingId,setMeetingId]=useState(""),[present,setPresent]=useState<string[]>([]),[rosterNote,setRosterNote]=useState(""),[rosterRows,setRosterRows]=useState<AttendanceRow[]>([]),[editing,setEditing]=useState(false),[rosterLoading,setRosterLoading]=useState(false),[saving,setSaving]=useState(false);
 const generation=useRef(0);
 const range=useMemo(()=>{const end=new Date(),start=new Date();if(period==="week")start.setDate(start.getDate()-7);else if(period==="quarter")start.setMonth(start.getMonth()-3);else if(period==="season"){start.setFullYear(start.getMonth()>=8?start.getFullYear():start.getFullYear()-1,8,1);start.setHours(0,0,0,0);}else start.setMonth(start.getMonth()-1);if(period==="custom"&&customFrom)start.setTime(israelDayStart(customFrom).getTime());if(period==="custom"&&customTo)end.setTime(israelDayEnd(customTo).getTime());return{from:start.toISOString(),to:end.toISOString()};},[period,customFrom,customTo]);
 async function load(){if(!profile)return;const ticket=++generation.current;setLoading(true);setLoadError(false);try{
 if(range.from>range.to)throw Error(pick("Start date must be before end date.","תאריך ההתחלה חייב להיות לפני תאריך הסיום."));
 const [attendance,memberRows,meetingRows,eventRows,absenceRows]=await Promise.all([
 readAllRows<AttendanceRow>((a,b)=>supabase.from("attendance_records").select(attendanceColumns+",team_meetings!inner(starts_at,ends_at)").gte("team_meetings.ends_at",range.from).lte("team_meetings.starts_at",range.to).order("id").range(a,b)),
 canReview?readAllRows<Member>((a,b)=>supabase.from("team_members").select("id,display_name,subteam,active").order("id").range(a,b)):Promise.resolve([{id:profile.id,display_name:profile.display_name,subteam:profile.subteam,active:true}]),
 readAllRows<Meeting>((a,b)=>supabase.from("team_meetings").select("id,title,starts_at,ends_at,status,calendar_event_id,opened_by,closed_by,opened_at,closed_at,opened_automatically,closed_automatically").neq("status","cancelled").order("id").range(a,b)),
 readAllRows<CalendarEvent>((a,b)=>supabase.from("team_calendar_events").select("id,title,starts_at,ends_at,mandatory").eq("cancelled",false).order("id").range(a,b)),
 readAllRows<Absence>((a,b)=>supabase.from("absence_requests").select("*").order("id").range(a,b))]);
 if(ticket!==generation.current)return;setRecords(attendance);setMembers(Object.fromEntries(memberRows.map(m=>[m.id,m])));setMeetings(meetingRows);setEvents(eventRows);setAbsences(absenceRows.sort((a,b)=>b.created_at.localeCompare(a.created_at)));
 }catch(error){if(ticket===generation.current){setLoadError(true);setMessage(error instanceof Error?error.message:"Attendance could not load");}}finally{if(ticket===generation.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{generation.current++};},[profile?.id,range,canReview]);
 useEffect(()=>{let active=true;setEditing(false);setRosterNote("");setRosterRows([]);setPresent([]);if(!meetingId)return;setRosterLoading(true);void readAllRows<AttendanceRow>((a,b)=>supabase.from("attendance_records").select(attendanceColumns).eq("meeting_id",meetingId).order("id").range(a,b)).then(rows=>{if(active){setRosterRows(rows);setPresent(rows.map(r=>r.member_id));setRosterLoading(false);}}).catch(error=>{if(active)setMessage(error.message);});return()=>{active=false};},[meetingId]);
 const format=new Intl.DateTimeFormat(language==="he"?"he-IL":"en-IL",{timeZone:"Asia/Jerusalem",dateStyle:"medium",timeStyle:"short"});
 const eventMap=Object.fromEntries(events.map(e=>[e.id,e])),meetingMap=Object.fromEntries(meetings.map(m=>[m.id,m])),upcomingEvents=events.filter(e=>new Date(e.ends_at)>new Date()).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
 const filteredMembers=Object.values(members).filter(m=>(!team||m.subteam===team)&&(!search||m.display_name.toLowerCase().includes(search.toLowerCase())));
 const summary=filteredMembers.map(member=>({member,...attendanceTotals(records.filter(r=>r.member_id===member.id))})).sort((a,b)=>sort==="hours"?b.hours-a.hours:a.member.display_name.localeCompare(b.member.display_name));
 const visibleIds=new Set(filteredMembers.map(m=>m.id)),visibleRecords=records.filter(r=>visibleIds.has(r.member_id)),totals=attendanceTotals(visibleRecords);
 const periodMeetings=meetings.filter(m=>m.starts_at<=range.to&&m.ends_at>=range.from).sort((a,b)=>b.starts_at.localeCompare(a.starts_at));
 const selected=selectedMember?members[selectedMember]:null,detail=records.filter(r=>r.member_id===selectedMember).sort((a,b)=>b.checked_in_at.localeCompare(a.checked_in_at)),selectedMeeting=meetingMap[meetingId];
 const switchView=(next:typeof view)=>{setView(next);setParams(next==="overview"?{}:{view:next})};
 const kindLabel=(r:AttendanceRow)=>({open:pick("Missing checkout / still in","טרם נרשמה יציאה"),automatic:pick("Automatic checkout","יציאה אוטומטית"),corrected:pick("Manually recorded / corrected","רישום ידני / מתוקן"),recorded:pick("Recorded","נרשם")}[attendanceKind(r)]);
 const who=(id:string|null,automatic:boolean)=>id?(members[id]?.display_name??pick("Recorded member","חבר/ה מתועד/ת")):automatic?pick("System · scheduled","מערכת · מתוזמן"):pick("Not recorded (historical)","לא תועד (היסטורי)");
 function exportCsv(){const rows=selectedMember?detail:visibleRecords;const lines=[["Member","Meeting","Check in (Israel)","Check out (Israel)","Hours","Status","Method","Correction note"],...rows.map(r=>[members[r.member_id]?.display_name??r.member_id,meetingMap[r.meeting_id]?.title??r.meeting_id,format.format(new Date(r.checked_in_at)),r.checked_out_at?format.format(new Date(r.checked_out_at)):"",r.checked_out_at?attendanceHours(r).toFixed(2):"",kindLabel(r),r.check_in_method,r.correction_reason??""])];const csv="\uFEFF"+lines.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(",")).join("\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));link.download="g3-attendance-detail.csv";link.click();URL.revokeObjectURL(link.href);}
 async function saveRoster(){if(!meetingId||saving)return;if(rosterNote.trim().length<3){setMessage(pick("Enter an audit note.","הזינו הערת תיעוד."));return;}setSaving(true);const {error}=await supabase.rpc("save_meeting_attendance_roster",{p_meeting_id:meetingId,p_present_members:present,p_note:rosterNote.trim()});setSaving(false);setMessage(error?.message??pick("Roster saved. Existing check-in and checkout times preserved.","הרשימה נשמרה. זמני נוכחות קיימים נשמרו."));if(!error){setMeetingId("");setEditing(false);await load();}}
 async function submitAbsence(e:FormEvent){e.preventDefault();if(!profile)return;const {data,error}=await supabase.from("absence_requests").insert({member_id:profile.id,calendar_event_id:eventId,reason:reason.trim()}).select("id").single();let pushFailed=false;if(!error&&data?.id){const delivery=await notifyActionsBySourceId(data.id);pushFailed=delivery.failed>0;}setMessage(error?.message??pick(pushFailed?"Absence request submitted. It is visible to reviewers, but phone push delivery was unavailable.":"Absence request submitted. Mentors and administrators were notified.",pushFailed?"בקשת ההיעדרות נשלחה והיא גלויה לבודקים, אך התראת הטלפון לא הייתה זמינה.":"בקשת ההיעדרות נשלחה. המנטורים והמנהלים קיבלו הודעה."));if(!error){setShowRequest(false);setEventId("");setReason("");await load()}}async function decide(e:FormEvent){e.preventDefault();if(!reviewing)return;const requestId=reviewing.request.id,{error}=await supabase.rpc("review_absence_request",{p_request_id:requestId,p_status:reviewing.decision,p_note:reviewNote.trim()});let pushFailed=false;if(!error){const delivery=await notifyActionsBySourceId(requestId);pushFailed=delivery.failed>0;}setMessage(error?.message??pick(pushFailed?"Decision saved. It is visible to the member, but phone push delivery was unavailable.":"Decision saved and the member was notified.",pushFailed?"ההחלטה נשמרה והיא גלויה לחבר/ה, אך התראת הטלפון לא הייתה זמינה.":"ההחלטה נשמרה ונשלחה הודעה לחבר/ה."));if(!error){setReviewing(null);setReviewNote("");await load()}}
 return <main className="hub-page attendance-center attendance-v2"><header className="attendance-command-hero"><div><div className="hub-eyebrow">G3 PEOPLE OPERATIONS</div><h1>{pick("Attendance center","מרכז נוכחות")}</h1><p>{pick("People, meetings and recorded hours. All times are Israel time.","אנשים, מפגשים ושעות נוכחות. כל הזמנים לפי שעון ישראל.")}</p></div><button className="hub-button" onClick={()=>setShowRequest(true)}>+ {pick("Request absence","בקשת היעדרות")}</button></header>
 <nav className="attendance-tabs"><button className={view==="overview"?"is-active":""} onClick={()=>switchView("overview")}>{pick("Attendance overview","סקירת נוכחות")}</button><button className={view==="absences"?"is-active":""} onClick={()=>switchView("absences")}>{pick("Absence requests","בקשות היעדרות")}<b>{absences.filter(a=>a.status==="pending").length}</b></button>{canRoster&&<button className={view==="roster"?"is-active":""} onClick={()=>switchView("roster")}>{pick("By meeting","לפי מפגש")}</button>}</nav>
 {message&&<div className="hub-message" role="status">{message}</div>}
 {view!=="absences"&&<div className="attendance-filters"><label>{pick("Period","תקופה")}<select value={period} onChange={e=>{setPeriod(e.target.value);setMeetingId("")}}>{[["week","Last 7 days","7 ימים"],["month","Last month","חודש"],["quarter","Last quarter","רבעון"],["season","Current season (September–August)","עונה נוכחית (ספטמבר–אוגוסט)"],["custom","Custom dates","טווח תאריכים"]].map(([v,en,he])=><option key={v} value={v}>{pick(en,he)}</option>)}</select></label>{period==="custom"&&<><label>{pick("From","מתאריך")}<input type="date" value={customFrom} onChange={e=>setCustomFrom(e.target.value)}/></label><label>{pick("To","עד תאריך")}<input type="date" value={customTo} onChange={e=>setCustomTo(e.target.value)}/></label></>}<label>{pick("Subteam","תת־צוות")}<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">{pick("All subteams","כל הצוותים")}</option>{Array.from(new Set(Object.values(members).map(m=>m.subteam).filter(Boolean))).map(t=><option key={t!}>{t}</option>)}</select></label><label>{pick("Find a person","חיפוש אדם")}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="button-secondary" onClick={()=>void load()} disabled={loading}>{pick("Refresh","רענון")}</button>{canReview&&<button className="hub-button" disabled={loading||loadError} onClick={exportCsv}>{pick("Export detail CSV","ייצוא פירוט CSV")}</button>}</div>}
 {loading?<section className="hub-card" role="status">{pick("Loading attendance…","טוען נוכחות…")}</section>:loadError?<section className="hub-card">{pick("Report unavailable. Refresh to retry; missing data is not shown as zero.","הדוח אינו זמין. רעננו כדי לנסות שוב.")}</section>:<>
 {view==="overview"&&<><div className="admin-stat-grid"><article><strong>{visibleRecords.length}</strong><span>{pick("Meeting attendances","רישומי נוכחות")}</span></article><article><strong>{totals.hours.toFixed(1)}</strong><span>{pick("Closed-record hours · includes automatic/manual","שעות ברשומות סגורות · כולל ידני ואוטומטי")}</span></article><article><strong>{totals.open}</strong><span>{pick("Still in / missing checkout · excluded from hours","טרם נרשמה יציאה · לא נכלל בשעות")}</span></article></div>
 <section className="hub-card attendance-people"><div className="attendance-section-title"><h2>{pick("People","חברי הקבוצה")}</h2><label>{pick("Sort","מיון")} <select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">{pick("Name","שם")}</option><option value="hours">{pick("Hours","שעות")}</option></select></label></div>
 <div className="attendance-table-scroll"><table><thead><tr><th>{pick("Person","שם")}</th><th>{pick("Meetings","מפגשים")}</th><th>{pick("Hours","שעות")}</th><th>{pick("Missing checkout","ללא יציאה")}</th><th>{pick("Automatic","אוטומטי")}</th></tr></thead><tbody>{summary.map(row=><tr key={row.member.id}><td><button className="attendance-person-link" onClick={()=>setSelectedMember(row.member.id)}>{row.member.display_name}</button><small>{row.member.subteam}{row.member.active===false?pick(" · Inactive"," · לא פעיל"):""}</small></td><td>{row.sessions}</td><td>{row.hours.toFixed(2)}</td><td>{row.open||"—"}</td><td>{row.automatic||"—"}</td></tr>)}</tbody></table>{!summary.length&&<p>{pick("No people match these filters.","אין אנשים התואמים לסינון.")}</p>}</div></section></>}
 {view==="roster"&&canRoster&&<section className="hub-card attendance-meetings"><h2>{pick("Meetings at a glance","מבט על המפגשים")}</h2><p>{pick("Select a meeting for its full roster. Counts follow your person and subteam filters.","בחרו מפגש להצגת הרשימה המלאה. המספרים בהתאם לסינון אנשים וצוותים.")}</p><div className="attendance-table-scroll"><table><thead><tr>{[pick("Meeting / date","מפגש / תאריך"),pick("Status","מצב"),pick("Attended","נכחו"),pick("Still in / missing out","ללא יציאה"),pick("Approved absence","היעדרות מאושרת"),pick("Hours","שעות")].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{periodMeetings.map(m=>{const rows=visibleRecords.filter(r=>r.meeting_id===m.id),t=attendanceTotals(rows);return <tr key={m.id}><td><button className="attendance-person-link" onClick={()=>setMeetingId(m.id)}>{m.title}</button><small>{format.format(new Date(m.starts_at))}</small></td><td>{m.status}</td><td>{rows.length}</td><td>{t.open||"—"}</td><td>{m.calendar_event_id?absences.filter(a=>a.calendar_event_id===m.calendar_event_id&&a.status==="approved"&&visibleIds.has(a.member_id)).length:"—"}</td><td>{t.hours.toFixed(2)}</td></tr>})}</tbody></table>{!periodMeetings.length&&<p>{pick("No meetings in this period.","אין מפגשים בתקופה זו.")}</p>}</div></section>}
  {view==="absences"?<section className="absence-board">{absences.length?absences.map(item=><article className={`hub-card absence-card status-${item.status}`} key={item.id}><header><span>{item.status}</span><time>{new Date(item.created_at).toLocaleDateString()}</time></header><h2>{eventMap[item.calendar_event_id]?.title??pick("Calendar event","אירוע בלוח")}</h2>{canApproveAbsence?<strong>{members[item.member_id]?.display_name}</strong>:null}<p>{item.reason}</p>{item.reviewer_note?<blockquote><b>{pick("Reviewer response","תגובת הבודק/ת")}</b>{item.reviewer_note}</blockquote>:null}{canApproveAbsence&&item.status==="pending"?<footer><button className="absence-approve" onClick={()=>{setReviewing({request:item,decision:"approved"});setReviewNote("")}}>{pick("Approve","אישור")}</button><button className="absence-reject" onClick={()=>{setReviewing({request:item,decision:"rejected"});setReviewNote("")}}>{pick("Reject","דחייה")}</button></footer>:null}</article>):<section className="hub-card attendance-empty">{pick("No absence requests yet.","אין עדיין בקשות היעדרות.")}</section>}</section>:null}

 </>}
 {selected&&<AccessibleDialog className="attendance-record-drawer" title={selected.display_name} onClose={()=>setSelectedMember(null)}><header><div><span className="hub-eyebrow">{pick("PERSON ATTENDANCE","נוכחות אישית")}</span><h2>{selected.display_name}</h2><p>{pick("Selected reporting period · Israel time","תקופת הדוח שנבחרה · שעון ישראל")}</p></div><button autoFocus className="button-secondary" onClick={()=>setSelectedMember(null)}>{pick("Close","סגירה")}</button></header><button className="hub-button" onClick={exportCsv}>{pick("Export this history","ייצוא היסטוריה זו")}</button><div className="attendance-history">{detail.map(r=><article key={r.id}><h3>{meetingMap[r.meeting_id]?.title??r.meeting_id}</h3><span className={`attendance-record-state state-${attendanceKind(r)}`}>{kindLabel(r)}</span><dl><div><dt>{pick("Check in","כניסה")}</dt><dd>{format.format(new Date(r.checked_in_at))}</dd></div><div><dt>{pick("Check out","יציאה")}</dt><dd>{r.checked_out_at?format.format(new Date(r.checked_out_at)):pick("Not recorded","לא נרשמה")}</dd></div><div><dt>{pick("Hours","שעות")}</dt><dd>{r.checked_out_at?attendanceHours(r).toFixed(2):"—"}</dd></div><div><dt>{pick("Method","אופן רישום")}</dt><dd>{r.check_in_method} / {r.check_out_method??"—"}</dd></div></dl>{r.correction_reason&&<p>{pick("Correction","תיקון")}: {r.correction_reason} · {members[r.corrected_by??""]?.display_name??""}</p>}</article>)}{!detail.length&&<p>{pick("No attendance in this period.","אין נוכחות בתקופה זו.")}</p>}</div></AccessibleDialog>}
 {meetingId&&selectedMeeting&&<AccessibleDialog className="attendance-record-drawer" title={selectedMeeting.title} onClose={()=>!saving&&setMeetingId("")}><header><div><span className="hub-eyebrow">{pick("MEETING ROSTER","רשימת מפגש")}</span><h2>{selectedMeeting.title}</h2><p>{format.format(new Date(selectedMeeting.starts_at))}</p></div><button autoFocus className="button-secondary" disabled={saving} onClick={()=>setMeetingId("")}>{pick("Close","סגירה")}</button></header><div className="attendance-session-audit"><p>{pick("Opened by","נפתח על ידי")}: <strong>{who(selectedMeeting.opened_by,selectedMeeting.opened_automatically)}</strong>{selectedMeeting.opened_at&&` · ${format.format(new Date(selectedMeeting.opened_at))}`}</p><p>{pick("Closed by","נסגר על ידי")}: <strong>{selectedMeeting.status==="closed"?who(selectedMeeting.closed_by,selectedMeeting.closed_automatically):pick("Not closed","טרם נסגר")}</strong>{selectedMeeting.closed_at&&` · ${format.format(new Date(selectedMeeting.closed_at))}`}</p></div>
 {rosterLoading?<p role="status">{pick("Loading full roster…","טוען רשימה מלאה…")}</p>:editing?<><p>{pick("Existing recorded times are preserved. Only new manual attendees receive the scheduled times. Location-verified records cannot be removed here.","זמנים קיימים נשמרים. רק נוכחים חדשים ברישום ידני יקבלו את זמני המפגש. לא ניתן להסיר כאן רשומות מאומתות מיקום.")}</p><div className="roster-grid">{Object.values(members).filter(m=>m.active!==false||present.includes(m.id)).map(m=>{const existing=rosterRows.find(r=>r.member_id===m.id),locked=!!existing&&existing.check_in_method!=="admin",approved=!!selectedMeeting.calendar_event_id&&absences.some(a=>a.member_id===m.id&&a.status==="approved"&&a.calendar_event_id===selectedMeeting.calendar_event_id);return <label key={m.id}><input type="checkbox" disabled={locked||saving} checked={present.includes(m.id)} onChange={e=>setPresent(ids=>e.target.checked?[...ids,m.id]:ids.filter(id=>id!==m.id))}/><span><strong>{m.display_name}</strong><small>{locked?pick("Recorded times protected","זמנים קיימים מוגנים"):approved?pick("Approved absence","היעדרות מאושרת"):m.subteam}</small></span></label>})}</div><label className="roster-note">{pick("Reason for roster correction","סיבת תיקון הרשימה")}<textarea rows={3} value={rosterNote} onChange={e=>setRosterNote(e.target.value)}/></label><button className="hub-button" disabled={saving||rosterNote.trim().length<3} onClick={()=>void saveRoster()}>{pick("Save roster","שמירת רשימה")}</button></>:<><div className="attendance-table-scroll"><table><thead><tr><th>{pick("Person","שם")}</th><th>{pick("Check in","כניסה")}</th><th>{pick("Check out","יציאה")}</th><th>{pick("Hours / status","שעות / מצב")}</th></tr></thead><tbody>{rosterRows.map(r=><tr key={r.id}><td>{members[r.member_id]?.display_name??r.member_id}</td><td>{format.format(new Date(r.checked_in_at))}</td><td>{r.checked_out_at?format.format(new Date(r.checked_out_at)):"—"}</td><td>{r.checked_out_at?attendanceHours(r).toFixed(2):"—"}<small>{kindLabel(r)}</small></td></tr>)}</tbody></table>{!rosterRows.length&&<p>{pick("No attendance recorded.","טרם נרשמה נוכחות.")}</p>}</div>{new Date(selectedMeeting.ends_at)<=new Date()&&<button className="hub-button" onClick={()=>setEditing(true)}>{pick("Correct roster","תיקון רשימה")}</button>}</>}
 </AccessibleDialog>}
 {showRequest?<div className="attendance-dialog-backdrop" onClick={()=>setShowRequest(false)}><form className="attendance-dialog" onClick={e=>e.stopPropagation()} onSubmit={submitAbsence}><span>{pick("PLANNED ABSENCE","היעדרות מתוכננת")}</span><h2>{pick("Request absence","בקשת היעדרות")}</h2><label>{pick("Meeting or event","מפגש או אירוע")}<select required value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">{pick("Choose from the calendar","בחירה מלוח השנה")}</option>{upcomingEvents.map(event=><option value={event.id} key={event.id}>{format.format(new Date(event.starts_at))} · {event.title}</option>)}</select></label><label>{pick("Reason (required)","סיבה (חובה)")}<textarea required minLength={3} rows={4} value={reason} onChange={e=>setReason(e.target.value)}/></label><footer><button type="button" onClick={()=>setShowRequest(false)}>{pick("Cancel","ביטול")}</button><button className="hub-button">{pick("Submit request","שליחת בקשה")}</button></footer></form></div>:null}
 {reviewing?<div className="attendance-dialog-backdrop" onClick={()=>setReviewing(null)}><form className="attendance-dialog" onClick={e=>e.stopPropagation()} onSubmit={decide}><span>{reviewing.decision.toUpperCase()}</span><h2>{members[reviewing.request.member_id]?.display_name}</h2><p>{eventMap[reviewing.request.calendar_event_id]?.title}</p><label>{pick("Response to member (required)","תגובה לחבר/ה (חובה)")}<textarea autoFocus required minLength={3} rows={4} value={reviewNote} onChange={e=>setReviewNote(e.target.value)}/></label><footer><button type="button" onClick={()=>setReviewing(null)}>{pick("Cancel","ביטול")}</button><button className={reviewing.decision==="rejected"?"absence-reject":"absence-approve"}>{pick("Confirm decision","אישור החלטה")}</button></footer></form></div>:null}</main>}
