import {useEffect,useMemo,useState} from "react";
import {useLocalization} from "../lib/localization";
import {supabase} from "../supabase";

type Person={id:string;display_name:string;subteam:string|null};
type Attendance={member_id:string;checked_in_at:string;checked_out_at:string|null};
type Task={assignee_id:string|null;status:string;due_at:string|null;archived?:boolean};
type Skill={member_id:string;status:string};
type Issue={resolved_by:string|null;status:string};
type InsightRow={person:Person;hours:number;sessions:number;tasksDone:number;tasksOpen:number;tasksOverdue:number;skills:number;issues:number};
const csvCell=(value:string|number)=>`"${String(value).replace(/"/g,'""')}"`;

export default function ContributionInsightsPage(){
  const {pick}=useLocalization();
  const [people,setPeople]=useState<Person[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[tasks,setTasks]=useState<Task[]>([]),[skills,setSkills]=useState<Skill[]>([]),[issues,setIssues]=useState<Issue[]>([]);
  const [period,setPeriod]=useState(30),[team,setTeam]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{const from=new Date(Date.now()-period*86400000).toISOString();setLoading(true);setError("");void Promise.all([
    supabase.from("team_members").select("id,display_name,subteam").eq("active",true).order("display_name"),
    supabase.from("attendance_records").select("member_id,checked_in_at,checked_out_at").gte("checked_in_at",from),
    supabase.from("project_tasks").select("assignee_id,status,due_at,archived"),
    supabase.from("training_enrollments").select("member_id,status").eq("status","qualified"),
    supabase.from("robot_issues").select("resolved_by,status").eq("status","resolved").gte("resolved_at",from),
  ]).then(results=>{const failure=results.find(result=>result.error)?.error;if(failure)setError(failure.message);setPeople((results[0].data??[]) as Person[]);setAttendance((results[1].data??[]) as Attendance[]);setTasks((results[2].data??[]) as Task[]);setSkills((results[3].data??[]) as Skill[]);setIssues((results[4].data??[]) as Issue[]);setLoading(false);});},[period]);
  const rows=useMemo<InsightRow[]>(()=>people.map(person=>{const records=attendance.filter(item=>item.member_id===person.id),hours=records.reduce((sum,item)=>sum+Math.max(0,((item.checked_out_at?new Date(item.checked_out_at):new Date()).getTime()-new Date(item.checked_in_at).getTime())/3600000),0),owned=tasks.filter(item=>item.assignee_id===person.id&&!item.archived);return{person,hours,sessions:records.length,tasksDone:owned.filter(item=>item.status==="done").length,tasksOpen:owned.filter(item=>item.status!=="done").length,tasksOverdue:owned.filter(item=>item.status!=="done"&&item.due_at&&new Date(item.due_at).getTime()<Date.now()).length,skills:skills.filter(item=>item.member_id===person.id).length,issues:issues.filter(item=>item.resolved_by===person.id).length};}),[people,attendance,tasks,skills,issues]);
  const teams=useMemo(()=>Array.from(new Set(people.map(person=>person.subteam).filter(Boolean) as string[])).sort(),[people]),visible=team==="all"?rows:rows.filter(row=>row.person.subteam===team);
  const totals=useMemo(()=>visible.reduce((sum,row)=>({hours:sum.hours+row.hours,sessions:sum.sessions+row.sessions,done:sum.done+row.tasksDone,open:sum.open+row.tasksOpen,overdue:sum.overdue+row.tasksOverdue,skills:sum.skills+row.skills,issues:sum.issues+row.issues}),{hours:0,sessions:0,done:0,open:0,overdue:0,skills:0,issues:0}),[visible]);
  const teamRows=useMemo(()=>teams.map(name=>{const members=rows.filter(row=>row.person.subteam===name);return{name,members:members.length,hours:members.reduce((sum,row)=>sum+row.hours,0),open:members.reduce((sum,row)=>sum+row.tasksOpen,0),overdue:members.reduce((sum,row)=>sum+row.tasksOverdue,0),skills:members.reduce((sum,row)=>sum+row.skills,0)};}),[teams,rows]);
  function exportCsv(){const headings=["Member","Department","Sessions","Workshop hours","Open tasks","Overdue tasks","Completed tasks","Qualifications","Issues resolved"],content=[headings,...visible.map(row=>[row.person.display_name,row.person.subteam??"",row.sessions,row.hours.toFixed(2),row.tasksOpen,row.tasksOverdue,row.tasksDone,row.skills,row.issues])].map(line=>line.map(csvCell).join(",")).join("\n"),link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\ufeff",content],{type:"text/csv;charset=utf-8"}));link.download=`g3-leadership-insights-${period}d.csv`;link.click();URL.revokeObjectURL(link.href);}
  return <main className="hub-page contribution-page web-admin-page">
    <header className="hub-page-header"><div><div className="hub-eyebrow">FRC 6740 · {pick("Leadership intelligence","תובנות ניהוליות")}</div><h1>{pick("Team pulse","מצב הקבוצה")}</h1><p>{pick("See workload, learning and participation signals together—so leaders know where support is needed.","מציגים יחד עומס, למידה והשתתפות — כדי שההנהלה תדע היכן נדרשת תמיכה.")}</p></div><div className="insight-controls"><label>{pick("Period","תקופה")}<select value={period} onChange={event=>setPeriod(Number(event.target.value))}><option value={7}>{pick("7 days","7 ימים")}</option><option value={30}>{pick("30 days","30 ימים")}</option><option value={90}>{pick("90 days","90 ימים")}</option></select></label><label>{pick("Department","מחלקה")}<select value={team} onChange={event=>setTeam(event.target.value)}><option value="all">{pick("All departments","כל המחלקות")}</option>{teams.map(name=><option key={name}>{name}</option>)}</select></label><button className="hub-button" onClick={exportCsv} disabled={!visible.length}>{pick("Export CSV","ייצוא CSV")}</button></div></header>
    {error?<div className="hub-message is-error" role="alert">{pick("Analytics could not load: ","לא ניתן לטעון את הניתוח: ")}{error}</div>:null}
    <section className="insight-stat-grid" aria-busy={loading}><article><small>{pick("Workshop activity","פעילות בסדנה")}</small><strong>{totals.hours.toFixed(1)}h</strong><span>{totals.sessions} {pick("check-ins","כניסות")}</span></article><article><small>{pick("Delivery","ביצוע")}</small><strong>{totals.done}</strong><span>{pick("tasks completed","משימות הושלמו")}</span></article><article className={totals.overdue?"needs-attention":""}><small>{pick("Needs attention","דורש תשומת לב")}</small><strong>{totals.overdue}</strong><span>{pick("overdue assignments","משימות באיחור")}</span></article><article><small>{pick("Capability growth","צמיחת יכולות")}</small><strong>{totals.skills}</strong><span>{pick("qualifications earned","הסמכות שהושגו")}</span></article></section>
    <section className="insight-layout"><div className="contribution-table"><div className="contribution-row head"><span>{pick("Member","חבר/ה")}</span><span>{pick("Sessions","מפגשים")}</span><span>{pick("Hours","שעות")}</span><span>{pick("Open","פתוחות")}</span><span>{pick("Overdue","באיחור")}</span><span>{pick("Qualified","הסמכות")}</span></div>{loading?<div className="insight-empty">{pick("Loading team signals…","טוען נתוני קבוצה…")}</div>:visible.length?visible.map(row=><article className="contribution-row" key={row.person.id}><span><strong>{row.person.display_name}</strong><small>{row.person.subteam??pick("No department","ללא מחלקה")}</small></span><span>{row.sessions}</span><span>{row.hours.toFixed(1)}</span><span>{row.tasksOpen}</span><span className={row.tasksOverdue?"signal-alert":""}>{row.tasksOverdue}</span><span>{row.skills}</span></article>):<div className="insight-empty">{pick("No members match this view.","אין חברים התואמים לתצוגה זו.")}</div>}</div>
      <aside className="hub-card department-pulse"><header><div><div className="hub-eyebrow">{pick("Department view","תצוגת מחלקות")}</div><h2>{pick("Workload balance","איזון עומסים")}</h2></div></header>{teamRows.map(row=><button type="button" onClick={()=>setTeam(row.name)} key={row.name}><span><strong>{row.name}</strong><small>{row.members} {pick("members","חברים")}</small></span><span><b>{row.open}</b><small>{pick("open","פתוחות")}</small></span><span className={row.overdue?"signal-alert":""}><b>{row.overdue}</b><small>{pick("late","באיחור")}</small></span></button>)}</aside></section>
    <aside className="hub-privacy-note"><strong>{pick("Use for support—not ranking","לשימוש כתמיכה — לא כדירוג")}</strong><span>{pick("Hours and counts never measure creativity, learning, teamwork or personal circumstances. Investigate the context before acting on any signal.","שעות וספירות אינן מודדות יצירתיות, למידה, עבודת צוות או נסיבות אישיות. יש לבדוק את ההקשר לפני פעולה על בסיס מדד כלשהו.")}</span></aside>
  </main>;
}
