import {useEffect,useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {useLocalization} from "../lib/localization";
import {supabase} from "../supabase";

type Person={id:string;display_name:string;subteam:string|null};
type Attendance={member_id:string;checked_in_at:string;checked_out_at:string|null};
type Task={id:string;title:string;assignee_id:string|null;status:string;due_at:string|null;archived?:boolean};
type Skill={member_id:string;status:string};
type Issue={resolved_by:string|null;status:string};
type InsightRow={person:Person;hours:number;sessions:number;tasksDone:number;tasksOpen:number;tasksOverdue:number;skills:number;issues:number};
const csvCell=(value:string|number)=>`"${String(value).replace(/"/g,'""')}"`;

export default function ContributionInsightsPage(){
  const {pick}=useLocalization();
  const [people,setPeople]=useState<Person[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[tasks,setTasks]=useState<Task[]>([]),[skills,setSkills]=useState<Skill[]>([]),[issues,setIssues]=useState<Issue[]>([]);
  const [period,setPeriod]=useState(30),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selectedId,setSelectedId]=useState<string|null>(null),[reload,setReload]=useState(0),[lastUpdated,setLastUpdated]=useState<Date|null>(null);
  useEffect(()=>{const from=new Date(Date.now()-period*86400000).toISOString();setLoading(true);setError("");void Promise.all([
    supabase.from("team_members").select("id,display_name,subteam").eq("active",true).order("display_name"),
    supabase.from("attendance_records").select("member_id,checked_in_at,checked_out_at").gte("checked_in_at",from),
    supabase.from("project_tasks").select("id,title,assignee_id,status,due_at,archived"),
    supabase.from("training_enrollments").select("member_id,status").eq("status","qualified"),
    supabase.from("robot_issues").select("resolved_by,status").eq("status","resolved").gte("resolved_at",from),
  ]).then(results=>{const failure=results.find(result=>result.error)?.error;if(failure)setError(failure.message);setPeople((results[0].data??[]) as Person[]);setAttendance((results[1].data??[]) as Attendance[]);setTasks((results[2].data??[]) as Task[]);setSkills((results[3].data??[]) as Skill[]);setIssues((results[4].data??[]) as Issue[]);setLastUpdated(new Date());setLoading(false);});},[period,reload]);
  const rows=useMemo<InsightRow[]>(()=>people.map(person=>{const records=attendance.filter(item=>item.member_id===person.id),hours=records.reduce((sum,item)=>item.checked_out_at?sum+Math.max(0,(new Date(item.checked_out_at).getTime()-new Date(item.checked_in_at).getTime())/3600000):sum,0),owned=tasks.filter(item=>item.assignee_id===person.id&&!item.archived);return{person,hours,sessions:records.length,tasksDone:owned.filter(item=>item.status==="done").length,tasksOpen:owned.filter(item=>item.status!=="done").length,tasksOverdue:owned.filter(item=>item.status!=="done"&&item.due_at&&new Date(item.due_at).getTime()<Date.now()).length,skills:skills.filter(item=>item.member_id===person.id).length,issues:issues.filter(item=>item.resolved_by===person.id).length};}),[people,attendance,tasks,skills,issues]);
  const visible=rows;
  const totals=useMemo(()=>visible.reduce((sum,row)=>({hours:sum.hours+row.hours,sessions:sum.sessions+row.sessions,done:sum.done+row.tasksDone,open:sum.open+row.tasksOpen,overdue:sum.overdue+row.tasksOverdue,skills:sum.skills+row.skills,issues:sum.issues+row.issues}),{hours:0,sessions:0,done:0,open:0,overdue:0,skills:0,issues:0}),[visible]);
  const selected=rows.find(row=>row.person.id===selectedId),selectedAttendance=attendance.filter(item=>item.member_id===selectedId),selectedTasks=tasks.filter(item=>item.assignee_id===selectedId&&!item.archived);
  function exportCsv(){const headings=["Member","Sessions","Workshop hours","Open tasks","Overdue tasks","Completed tasks","Qualifications","Issues resolved"],content=[headings,...visible.map(row=>[row.person.display_name,row.sessions,row.hours.toFixed(2),row.tasksOpen,row.tasksOverdue,row.tasksDone,row.skills,row.issues])].map(line=>line.map(csvCell).join(",")).join("\n"),link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\ufeff",content],{type:"text/csv;charset=utf-8"}));link.download=`g3-leadership-insights-${period}d.csv`;link.click();URL.revokeObjectURL(link.href);}
  return <main className="hub-page contribution-page web-admin-page">
    <header className="hub-page-header"><div><div className="hub-eyebrow">FRC 6740 · {pick("Leadership intelligence","תובנות ניהוליות")}</div><h1>{pick("Team pulse","מצב הקבוצה")}</h1><p>{pick("See workload, learning and participation signals together—so leaders know where support is needed.","מציגים יחד עומס, למידה והשתתפות — כדי שההנהלה תדע היכן נדרשת תמיכה.")}</p>{lastUpdated?<small className="insight-updated">{pick("Updated","עודכן")} {lastUpdated.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small>:null}</div><div className="insight-controls"><label>{pick("Period","תקופה")}<select value={period} onChange={event=>setPeriod(Number(event.target.value))}><option value={7}>{pick("7 days","7 ימים")}</option><option value={30}>{pick("30 days","30 ימים")}</option><option value={90}>{pick("90 days","90 ימים")}</option></select></label><button type="button" onClick={()=>setReload(value=>value+1)}>{pick("Refresh","רענון")}</button><button className="hub-button" onClick={exportCsv} disabled={!visible.length}>{pick("Export CSV","ייצוא CSV")}</button></div></header>
    {error?<div className="hub-message is-error" role="alert">{pick("Analytics could not load: ","לא ניתן לטעון את הניתוח: ")}{error}</div>:null}
    <section className="insight-stat-grid" aria-busy={loading}><article><small>{pick("Workshop activity","פעילות בסדנה")}</small><strong>{totals.hours.toFixed(1)}h</strong><span>{totals.sessions} {pick("check-ins","כניסות")}</span></article><article><small>{pick("Delivery","ביצוע")}</small><strong>{totals.done}</strong><span>{pick("tasks completed","משימות הושלמו")}</span></article><article className={totals.overdue?"needs-attention":""}><small>{pick("Needs attention","דורש תשומת לב")}</small><strong>{totals.overdue}</strong><span>{pick("overdue assignments","משימות באיחור")}</span></article><article><small>{pick("Capability growth","צמיחת יכולות")}</small><strong>{totals.skills}</strong><span>{pick("qualifications earned","הסמכות שהושגו")}</span></article></section>
    <section className="contribution-table"><div className="contribution-row head"><span>{pick("Member","חבר/ה")}</span><span>{pick("Sessions","מפגשים")}</span><span>{pick("Hours","שעות")}</span><span>{pick("Open","פתוחות")}</span><span>{pick("Overdue","באיחור")}</span><span>{pick("Qualified","הסמכות")}</span></div>{loading?<div className="insight-empty">{pick("Loading team signals…","טוען נתוני קבוצה…")}</div>:visible.length?visible.map(row=><button type="button" className="contribution-row insight-member-row" onClick={()=>setSelectedId(row.person.id)} key={row.person.id}><span><strong>{row.person.display_name}</strong><small>{pick("Open details","פתיחת פרטים")} →</small></span><span>{row.sessions}</span><span>{row.hours.toFixed(1)}</span><span>{row.tasksOpen}</span><span className={row.tasksOverdue?"signal-alert":""}>{row.tasksOverdue}</span><span>{row.skills}</span></button>):<div className="insight-empty">{pick("No active members to display.","אין חברים פעילים להצגה.")}</div>}</section>
    {selected?<section className="hub-card insight-detail">
      <header><div><div className="hub-eyebrow">{pick("Member support view","תצוגת תמיכה בחבר/ה")}</div><h2>{selected.person.display_name}</h2></div><button type="button" aria-label={pick("Close details","סגירת פרטים")} onClick={()=>setSelectedId(null)}>×</button></header>
      <div className="insight-detail-stats"><span><b>{selected.hours.toFixed(1)}</b>{pick("completed hours","שעות שהושלמו")}</span><span><b>{selectedAttendance.filter(item=>!item.checked_out_at).length}</b>{pick("active check-ins","כניסות פעילות")}</span><span><b>{selected.tasksOpen}</b>{pick("open tasks","משימות פתוחות")}</span><span><b>{selected.skills}</b>{pick("qualifications","הסמכות")}</span></div>
      <div className="insight-detail-columns"><div><h3>{pick("Current responsibilities","אחריות נוכחית")}</h3>{selectedTasks.length?selectedTasks.slice(0,6).map(task=><article key={task.id}><span><strong>{task.title}</strong><small>{task.due_at?new Date(task.due_at).toLocaleDateString():pick("No due date","ללא תאריך יעד")}</small></span><b className={task.status!=="done"&&task.due_at&&new Date(task.due_at).getTime()<Date.now()?"signal-alert":""}>{task.status.replace("_"," ")}</b></article>):<p>{pick("No current project tasks.","אין משימות פרויקט נוכחיות.")}</p>}<Link to="/projects">{pick("Open projects","פתיחת פרויקטים")} →</Link></div>
      <div><h3>{pick("Recent attendance","נוכחות אחרונה")}</h3>{selectedAttendance.length?selectedAttendance.slice(0,6).map((record,index)=><article key={`${record.checked_in_at}-${index}`}><span><strong>{new Date(record.checked_in_at).toLocaleDateString()}</strong><small>{new Date(record.checked_in_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></span><b>{record.checked_out_at?pick("Completed","הושלם"):pick("Still open","עדיין פתוח")}</b></article>):<p>{pick("No attendance in this period.","אין נוכחות בתקופה זו.")}</p>}<Link to="/admin/reports">{pick("Open attendance report","פתיחת דוח נוכחות")} →</Link></div></div>
    </section>:null}
    <aside className="hub-privacy-note"><strong>{pick("Use for support—not ranking","לשימוש כתמיכה — לא כדירוג")}</strong><span>{pick("Hours and counts never measure creativity, learning, teamwork or personal circumstances. Investigate the context before acting on any signal.","שעות וספירות אינן מודדות יצירתיות, למידה, עבודת צוות או נסיבות אישיות. יש לבדוק את ההקשר לפני פעולה על בסיס מדד כלשהו.")}</span></aside>
  </main>;
}
