import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {useLocalization} from '../lib/localization';
import {autopilot,Command,Concept,DEFAULT_CONCEPT,DT,ENGINE,FIELD,MAX_TICKS,normalized,OBSTACLES,parseRecording,Pose,Recording,replay,START,step} from '../lib/conceptTwin';
import '../styles/intelligence.css';
import type {ModelMetrics} from '../components/FieldTwinCanvas';
import {FIELD_SEASONS} from '../lib/fieldSeasons';
import {RobotModel,savedRobot,validateGlb} from '../lib/robotModel';
const Canvas=lazy(()=>import('../components/FieldTwinCanvas'));
export default function FieldTwinPage(){
 const [modelMetrics,setModelMetrics]=useState<ModelMetrics|null>(null);const [padName,setPadName]=useState('No controller detected — press a controller button to connect.');
 useEffect(()=>{const id=window.setInterval(()=>{const p=Array.from(navigator.getGamepads?.()??[]).find(Boolean);setPadName(p?`Connected: ${p.id}`:'No controller detected — press a controller button to connect.');},1000);return()=>window.clearInterval(id);},[]);
 const [year,setYear]=useState(2026);const season=FIELD_SEASONS.find(s=>s.year===year)!;const historical=year!==2026;
 const [custom,setCustom]=useState<RobotModel>();
 useEffect(()=>{let active=true;void savedRobot().then(m=>{if(m&&active){validateGlb(m.data);setCustom(m);}}).catch(()=>{});return()=>{active=false;};},[]);
 async function uploadRobot(file?:File){if(!file)return;try{if(file.size>40*1024*1024)throw Error('Maximum model size is 40 MB.');const data=await file.arrayBuffer();validateGlb(data);stop();setModelMetrics(null);setCustom({name:file.name,data,scale:1,rotation:0});setThreeD(true);}catch(e){setStatus(e instanceof Error?e.message:'Model import failed');}}
 const {pick}=useLocalization();const [pose,setPose]=useState<Pose>({...START}),[config,setConfig]=useState<Concept>({...DEFAULT_CONCEPT});
 const [enabled,setEnabled]=useState(false),[mode,setMode]=useState<'manual'|'auto'|'replay'>('manual'),[input,setInput]=useState<'keyboard'|'gamepad'>('keyboard');
 const [threeD,setThreeD]=useState(false),[detailed,setDetailed]=useState(true),[kitbot,setKitbot]=useState(true),[view,setView]=useState<'orbit'|'top'|'follow'>('orbit');
 const [status,setStatus]=useState(''),[fps,setFps]=useState(0),[recording,setRecording]=useState(false),[saved,setSaved]=useState<Recording|null>(null),[path,setPath]=useState<Pose[]>([]);
 const [deadband,setDeadband]=useState(.12),[xAxis,setXAxis]=useState(0),[yAxis,setYAxis]=useState(1),[turnAxis,setTurnAxis]=useState(2),[invertY,setInvertY]=useState(true);
 const keys=useRef(new Set<string>()),touch=useRef<Command>({vx:0,vy:0,omega:0}),physics=useRef<Pose>({...START}),record=useRef<Recording|null>(null),waypoint=useRef(0),playIndex=useRef(0);
 const latest=useRef({enabled,mode,input,config,recording,saved,deadband,xAxis,yAxis,turnAxis,invertY});latest.current={enabled,mode,input,config,recording,saved,deadband,xAxis,yAxis,turnAxis,invertY};
 const page=useRef<HTMLElement>(null);const [expanded,setExpanded]=useState(false);
 async function fullscreen(){if(expanded){if(document.fullscreenElement)await document.exitFullscreen();setExpanded(false);return;}setExpanded(true);try{await page.current?.requestFullscreen();}catch{/* Embedded browsers use the expanded layout. */}}
 useEffect(()=>{const changed=()=>{if(!document.fullscreenElement)setExpanded(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setExpanded(false);};document.addEventListener('fullscreenchange',changed);window.addEventListener('keydown',escape);return()=>{document.removeEventListener('fullscreenchange',changed);window.removeEventListener('keydown',escape);};},[]);
 function reportFps(value:number){setFps(value);}
 const stop=()=>{latest.current.enabled=false;setEnabled(false);keys.current.clear();touch.current={vx:0,vy:0,omega:0};};
 useEffect(()=>{
  const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,textarea,[contenteditable]'))return;if(e.code==='Space'&&latest.current.enabled){e.preventDefault();stop();return;}if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();keys.current.add(e.code);}};
  const up=(e:KeyboardEvent)=>keys.current.delete(e.code),blur=()=>stop(),visibility=()=>{if(document.hidden)stop();},disconnect=()=>{if(latest.current.input==='gamepad'){stop();setStatus('Gamepad disconnected — simulation disabled.');}};
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);window.addEventListener('gamepaddisconnected',disconnect);
  let frame=0,then=performance.now(),acc=0,ui=0;
  const animate=(now:number)=>{
   const settings=latest.current;const elapsed=now-then;then=now;
   if(settings.enabled&&elapsed<2000){acc+=Math.min(elapsed/1000,.1);while(acc>=DT){acc-=DT;let cmd:Command={...touch.current};
    if(settings.mode==='auto'){const a=autopilot(physics.current,waypoint.current);waypoint.current=a.next;cmd=a.command;}
    else if(settings.mode==='replay'){
     if(!settings.saved||playIndex.current>=settings.saved.commands.length){stop();break;}cmd=settings.saved.commands[playIndex.current++];
    }else if(settings.input==='gamepad'){
     const pad=Array.from(navigator.getGamepads?.()??[]).find(Boolean);if(!pad){stop();setStatus('Press a gamepad button to connect, then enable.');break;}
     const axis=(i:number)=>{const v=pad.axes[i]??0;return Math.abs(v)<settings.deadband?0:Math.sign(v)*(Math.abs(v)-settings.deadband)/(1-settings.deadband);};cmd={vx:axis(settings.xAxis),vy:axis(settings.yAxis)*(settings.invertY?-1:1),omega:axis(settings.turnAxis)};
    }else{const k=keys.current;cmd={vx:cmd.vx+Number(k.has('KeyD')||k.has('ArrowRight'))-Number(k.has('KeyA')||k.has('ArrowLeft')),vy:cmd.vy+Number(k.has('KeyW')||k.has('ArrowUp'))-Number(k.has('KeyS')||k.has('ArrowDown')),omega:cmd.omega+Number(k.has('KeyQ'))-Number(k.has('KeyE'))};}
    cmd=normalized(cmd);physics.current=step(physics.current,cmd,settings.mode==='replay'&&settings.saved?settings.saved.config:settings.config);
    if(settings.recording&&record.current){record.current.commands.push(cmd);if(physics.current.tick%60===0)record.current.checkpoints.push({...physics.current});if(record.current.commands.length>=MAX_TICKS){setRecording(false);setSaved({...record.current});stop();setStatus('Two-minute recording limit reached. Recording retained.');break;}}
   }}else{acc=0;if(settings.enabled&&elapsed>=2000){stop();setStatus('Long frame interruption — simulation paused safely.');}}
   if(now-ui>70){ui=now;setPose({...physics.current});}frame=requestAnimationFrame(animate);
  };frame=requestAnimationFrame(animate);
  return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('gamepaddisconnected',disconnect);};
 },[]);
 function reset(){stop();setRecording(false);physics.current={...START};setPose({...START});waypoint.current=0;playIndex.current=0;setPath([]);}
 function toggleRecord(){if(recording){setRecording(false);setSaved(record.current?{...record.current}:null);setStatus('Recording saved in this session. Export to keep a copy.');}else{record.current={engine:ENGINE,asset:'2026-field-v2',config:{...config},initial:{...physics.current},commands:[],checkpoints:[]};setRecording(true);setStatus('Recording commands. Enable driving or Auto Play.');}}
 function play(){if(!saved)return;stop();const result=replay(saved);if(result.failure!==null){setStatus(`REPRODUCIBILITY_FAILURE at tick ${result.failure}`);return;}setConfig({...saved.config});setPath(result.path);physics.current={...saved.initial};playIndex.current=0;setRecording(false);setMode('replay');setEnabled(true);setStatus(`Replay verified against ${saved.checkpoints.length} checkpoints in this runtime.`);}
 function compare(){if(!saved)return;const a=replay(saved),b=replay(saved,config);setPath(b.path);setStatus(`Same-input A/B · recorded ${a.pose.distance.toFixed(2)} m / current concept ${b.pose.distance.toFixed(2)} m. Collision ticks ${a.pose.collisions} / ${b.pose.collisions}. Not a strategy ranking.`);}
 function exportRun(){if(!saved)return;const url=URL.createObjectURL(new Blob([JSON.stringify(saved)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='g3-concept-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importRun(file?:File){if(!file)return;try{if(file.size>1500000)throw Error('Recording exceeds 1.5 MB');const r=parseRecording(await file.text());stop();setSaved(r);setStatus('Recording imported. Replay will verify its checkpoints.');}catch(e){setStatus(e instanceof Error?e.message:'Invalid recording');}}
 const press=(axis:keyof Command,value:number)=>(event:React.PointerEvent<HTMLButtonElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);touch.current={...touch.current,[axis]:value};};
 const release=()=>{touch.current={vx:0,vy:0,omega:0};};
 return <main ref={page} className={`intel-page ${expanded?'twin-expanded':''}`}><header className="intel-heading"><div><span className="intel-kicker">G3 LAB / {season.name.toUpperCase()} {year}</span><h1>{pick('Field & robot studio','סטודיו מגרש ורובוט')}</h1><p>{pick('Explore the field. Drive a concept. Compare the same inputs.','חקרו את המגרש, נהגו ברובוט והשוו את אותן הפקודות.')}</p></div><Link className="intel-link" to="/knowledge">{pick('Knowledge & sources','ידע ומקורות')} ↗</Link></header>
 <div className="twin-season-bar"><label>Field season<select value={year} onChange={e=>{reset();setYear(Number(e.target.value));setThreeD(true);setStatus('');}}>{[...FIELD_SEASONS].reverse().map(s=><option key={s.year} value={s.year}>{s.year} · {s.name}</option>)}</select></label><p>{historical?'Historical field viewing · rotate, zoom and inspect your model. Driving and replay are available on 2026 only.':'2026 · Field viewing and planar concept driving'}<br/><small>2017–2020: reference material is available in Knowledge; verified 3D assets are not installed.</small></p></div><div className="twin-layout"><section className="twin-stage"><div className="twin-toolbar"><span className={`twin-state ${enabled?'enabled':''}`}>{historical?'FIELD VIEW':enabled?pick('ENABLED · SIMULATION','פעיל · סימולציה'):pick('DISABLED','מושבת')}</span><div><button onClick={()=>void fullscreen()}>{expanded?pick('Exit full screen','יציאה ממסך מלא'):pick('Full screen','מסך מלא')}</button><button disabled={historical} aria-pressed={!threeD} onClick={()=>setThreeD(false)}>2D</button><button aria-pressed={threeD} onClick={()=>setThreeD(true)}>3D</button><select aria-label={pick('Camera view','תצוגת מצלמה')} value={view} onChange={e=>setView(e.target.value as typeof view)}><option value="orbit">{pick('Rotate camera','סיבוב מצלמה')}</option><option value="top">{pick('Top','מבט על')}</option><option value="follow">{pick('Follow robot','מעקב רובוט')}</option></select></div></div>
 {threeD?<Suspense fallback={<div className="twin-placeholder">{pick('Opening renderer…','פותח תצוגה…')}</div>}><Canvas onModelMetrics={setModelMetrics} season={season} custom={custom} pose={pose} concept={config} detailed={detailed} kitbot={kitbot} view={view} path={path} onStatus={setStatus} onFps={reportFps}/></Suspense>:<div className="twin-flat"><svg viewBox={`-${FIELD.length/2+.5} -${FIELD.width/2+.5} ${FIELD.length+1} ${FIELD.width+1}`} role="img" aria-label={pick('Simplified field plan and robot position','תרשים מגרש ומיקום הרובוט')}><rect x={-FIELD.length/2} y={-FIELD.width/2} width={FIELD.length} height={FIELD.width} fill="#293b50" stroke="#73879b" strokeWidth=".04"/><path d={`M0,-${FIELD.width/2} V${FIELD.width/2}`} stroke="#8ca0b1" strokeDasharray=".15 .15" strokeWidth=".025"/>{OBSTACLES.map((o,i)=><rect key={i} x={o.x-o.w/2} y={-o.y-o.h/2} width={o.w} height={o.h} fill={o.x<0?'#3e9cff':'#f16572'} rx=".06"/>)}<text x="-7.8" y="-3.5" fill="#70b9ff" fontSize=".35">BLUE</text><text x="6.5" y="-3.5" fill="#ff8591" fontSize=".35">RED</text><polyline points={path.map(p=>`${p.x},${-p.y}`).join(' ')} fill="none" stroke="#5be1cf" strokeWidth=".04"/><g transform={`translate(${pose.x},${-pose.y}) rotate(${-pose.heading*180/Math.PI})`}><rect x={-config.length/2} y={-config.width/2} width={config.length} height={config.width} fill="#ed0097" stroke="white" strokeWidth=".035" rx=".05"/><path d="M.1,0 H.65 M.5,-.12 L.65,0 L.5,.12" stroke="#ffe170" fill="none" strokeWidth=".045"/></g></svg><button className="intel-primary" onClick={()=>setThreeD(true)}>{pick('Open detailed 3D field','פתיחת המגרש בתלת־ממד')} ↗</button><small>{pick('Detailed field: 19.6 MB · optional KitBot: 16.2 MB · downloaded only in 3D','מגרש מפורט: 19.6 MB · KitBot אופציונלי: 16.2 MB · הורדה בתלת־ממד בלבד')}</small></div>}
 <div className="twin-metrics"><div hidden={historical}><span>{pick('Time','זמן')}</span><strong>{(pose.tick*DT).toFixed(1)} s</strong></div><div hidden={historical}><span>{pick('Travel','מרחק')}</span><strong>{pose.distance.toFixed(2)} m</strong></div><div hidden={historical}><span>{pick('Collision ticks','צעדים חסומים')}</span><strong>{pose.collisions}</strong></div><div><span>{pick('Rendering','תצוגה')}</span><strong>{threeD?`${fps} FPS`:'2D'}</strong></div></div>
 <div className="twin-drive" hidden={historical}><button className={enabled?'intel-danger':'intel-primary'} onClick={()=>enabled?stop():setEnabled(true)}>{enabled?pick('Disable · Space','השבתה · רווח'):pick('Start driving','התחלת נהיגה')}</button><button onClick={reset}>{pick('Reset position','איפוס מיקום')}</button><select aria-label={pick('Driving mode','מצב נהיגה')} disabled={enabled} value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="manual">{pick('Manual drive','נהיגה ידנית')}</option><option value="auto">Auto Play · patrol</option>{saved?<option value="replay">Replay</option>:null}</select></div>
 <div hidden={historical} className="twin-touch" aria-label={pick('Touch driving controls','בקרי נהיגה במגע')}>{([['↶','omega',1],['↑','vy',1],['↷','omega',-1],['←','vx',-1],['↓','vy',-1],['→','vx',1]] as const).map(([label,axis,value])=><button key={label} aria-label={`${axis} ${value>0?'positive':'negative'}`} onPointerDown={press(axis,value)} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release}>{label}</button>)}</div>
 <p hidden={historical} className="twin-hint">{pick('Click Start driving, then hold the arrow buttons below or use your keyboard. For automatic movement, choose Auto Play before starting. Drag the 3D view to rotate the camera; scroll to zoom.','לחצו על התחלת נהיגה ואז החזיקו את כפתורי החצים או השתמשו במקלדת. לתנועה אוטומטית בחרו Auto Play לפני ההפעלה. גררו את התצוגה לסיבוב המצלמה וגללו לזום.')}<br/>WASD / {pick('arrows: field-relative movement · Q/E: rotation · Space: disable','חצים: תנועה ביחס למגרש · Q/E: סיבוב · רווח: השבתה')}</p></section>
 <aside className="twin-inspector"><section><h2>Upload robot model</h2><p className="intel-muted">Self-contained GLB, up to 40 MB. SolidWorks / Onshape: convert your exported CAD assembly to GLB first. Saved models stay in this browser, not shared with the team.</p><label className="intel-file">Choose GLB<input type="file" accept=".glb,model/gltf-binary" onChange={e=>void uploadRobot(e.target.files?.[0])}/></label>{custom&&<><p style={{overflowWrap:'anywhere'}}>{custom.name}</p>{modelMetrics&&<p className="intel-muted">Model bounds before heading rotation: {(modelMetrics.length*custom.scale).toFixed(3)} × {(modelMetrics.width*custom.scale).toFixed(3)} × {(modelMetrics.height*custom.scale).toFixed(3)} m · {modelMetrics.triangles.toLocaleString()} triangles. These dimensions do not set collision limits.</p>}<label>Scale (GLB uses metres)<input type="number" min="0.001" max="100" step="0.001" value={custom.scale} onChange={e=>{const v=Number(e.target.value);if(v>=.001&&v<=100)setCustom({...custom,scale:v});}}/></label><label>Forward orientation<select value={custom.rotation} onChange={e=>setCustom({...custom,rotation:Number(e.target.value)})}>{[0,90,180,270].map(v=><option key={v} value={v}>{v}°</option>)}</select></label><div className="intel-button-row"><button className="intel-primary" onClick={()=>void savedRobot(custom).then(()=>setStatus('Robot and adjustments saved on this device.')).catch(()=>setStatus('Unable to save: browser storage unavailable or full.'))}>Save on this device</button><button onClick={()=>{setCustom(undefined);void savedRobot(null).catch(()=>setStatus('Could not clear the saved model.'));}}>Use KitBot</button></div><p className="intel-muted">Visual model only. Set collision dimensions separately below; mechanisms are not simulated.</p></>}</section><section><span className="intel-kicker">01 / {pick('ROBOT CONCEPT','קונספט הרובוט')}</span><h2>{pick('Make room for your idea','מקום לרעיון שלכם')}</h2><label className="intel-toggle"><input type="checkbox" checked={kitbot} onChange={e=>setKitbot(e.target.checked)}/>{pick('Show detailed 2026 KitBot','הצגת KitBot 2026 מפורט')}</label><label className="intel-toggle"><input type="checkbox" checked={detailed} onChange={e=>setDetailed(e.target.checked)}/>{pick('Show detailed field','הצגת מגרש מפורט')}</label><p className="intel-muted">{pick('KitBot is a reference model, not G3’s robot. Dimensions below control the simulated collision envelope.','KitBot הוא דגם ייחוס, לא הרובוט של G3. המידות מגדירות את מעטפת ההתנגשות בסימולציה.')}</p>
 {([['length','Length','אורך',.4,1.4],['width','Width','רוחב',.4,1.4],['height','Height','גובה',.2,1.8],['speed','Speed m/s','מהירות מטר/שנייה',.2,5]] as const).map(([key,en,he,min,max])=><label hidden={historical&&key==='speed'} key={key}>{pick(en,he)}<span className="twin-range"><input disabled={enabled||recording} type="range" min={min} max={max} step=".05" value={config[key]} onChange={e=>setConfig({...config,[key]:Number(e.target.value)})}/><output>{config[key].toFixed(2)}</output></span></label>)}</section>
 <section hidden={historical}><span className="intel-kicker">02 / {pick('INPUT & REPLAY','קלט ושחזור')}</span><label>{pick('Input device','התקן קלט')}<select disabled={enabled} value={input} onChange={e=>setInput(e.target.value as typeof input)}><option value="keyboard">{pick('Keyboard / touch','מקלדת / מגע')}</option><option value="gamepad">Gamepad / Xbox</option></select></label>{input==='gamepad'?<details open><p role="status">{padName}</p><summary>{pick('Gamepad mapping','מיפוי בקר')}</summary>{([[xAxis,setXAxis,'X axis'],[yAxis,setYAxis,'Y axis'],[turnAxis,setTurnAxis,'Rotation axis']] as const).map(([value,setter,label])=><label key={label}>{label}<input type="number" min="0" max="7" value={value} onChange={e=>setter(Math.max(0,Math.min(7,Number(e.target.value))))}/></label>)}<label>Deadband<input type="range" min=".05" max=".35" step=".01" value={deadband} onChange={e=>setDeadband(Number(e.target.value))}/></label><label className="intel-toggle"><input type="checkbox" checked={invertY} onChange={e=>setInvertY(e.target.checked)}/>Invert Y</label></details>:null}
 <div className="intel-button-row"><button disabled={mode==='replay'} onClick={toggleRecord}>{recording?'■ '+pick('Stop recording','עצירת הקלטה'):'● '+pick('Record','הקלטה')}</button><button disabled={!saved||recording||enabled} onClick={play}>{pick('Replay','שחזור')}</button><button disabled={!saved||enabled||recording} onClick={compare}>A/B</button><button disabled={!saved} onClick={exportRun}>{pick('Export','ייצוא')}</button></div><label className="intel-file">{pick('Import recording','ייבוא הקלטה')}<input type="file" accept="application/json,.json" onChange={e=>void importRun(e.target.files?.[0])}/></label><small>{saved?`${saved.commands.length} ticks · ${saved.checkpoints.length} checkpoints`:pick('Recordings stay in this session until exported.','ההקלטות נשמרות בהפעלה זו עד לייצוא.')}</small></section>
 <section><span className="intel-kicker">03 / {pick('MODEL & SOURCES','מודל ומקורות')}</span><p className="intel-muted">{historical?'Historical visualization only. No collision, scoring or robot legality checks for this season.':pick('Planar concept simulation: conservative obstacle boxes; no ramp dynamics, fuel physics, match scoring or engineering approval.','סימולציית קונספט מישורית: מעטפות מכשולים שמרניות; ללא דינמיקת רמפות, פיזיקת כדורים, ניקוד או אישור הנדסי.')}</p><a href="https://www.firstinspires.org/resources/library/frc/playing-field" target="_blank" rel="noreferrer">FIRST · {pick('Official field resources','משאבי מגרש רשמיים')} ↗</a><a href="https://github.com/Mechanical-Advantage/AdvantageScopeAssets/releases/tag/archive-v1" target="_blank" rel="noreferrer">AdvantageScope · {pick('Model distribution','מקור הדגמים')} ↗</a><a href="/twin/2026/LICENSE.txt" target="_blank" rel="noreferrer">{pick('Asset license & credits','רישיון וקרדיט')}</a><button onClick={()=>{void import('../components/FieldTwinCanvas').then(m=>m.clearTwinCache()).then(()=>setStatus('Model cache cleared. Selected models will download on next use.'));}}>{pick('Clear model cache','ניקוי מטמון הדגמים')}</button></section></aside></div>
 {status?<p className="intel-status" role="status">{status}</p>:null}<footer className="intel-footer">{ENGINE} · 60 Hz · {pick('Simulated only. No connection to physical robot controls.','סימולציה בלבד. ללא חיבור לבקרת רובוט פיזי.')}</footer></main>;
}
