import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useAdminStatus } from "../lib/useAdminStatus";
import { useLocalization } from "../lib/localization";
import { useMemberAuth } from "../lib/memberAuth";
import { supabase } from "../supabase";

type Area="readiness"|"purchasing"|"decisions"|"training"|"packing"|"assignments";
type Item={id:string;area:Area;title:string;details:string|null;status:string;owner_id:string|null;due_at:string|null};
const areas:Array<[Area,string,string]>=[["readiness","Robot readiness","מוכנות הרובוט"],["purchasing","Parts & purchasing","חלקים ורכש"],["decisions","Decision log","יומן החלטות"],["training","Training matrix","מטריצת הכשרה"],["packing","Pit & packing","פיט ואריזה"],["assignments","Assignments","שיבוצים"]];

export default function FrcOperationsPage(){const {pick}=useLocalization();const {profile}=useMemberAuth();const isAdmin=useAdminStatus();const [params,setParams]=useSearchParams();const area=(areas.some(item=>item[0]===params.get("area"))?params.get("area"):"readiness") as Area;const [items,setItems]=useState<Item[]>([]);const [members,setMembers]=useState<Array<{id:string;display_name:string}>>([]);const [title,setTitle]=useState("");const [details,setDetails]=useState("");const [owner,setOwner]=useState(profile?.id??"");const [due,setDue]=useState("");const [message,setMessage]=useState("");
async function load(){const [{data},{data:people}]=await Promise.all([supabase.from("frc_operational_items").select("*").eq("area",area).eq("archived",false).order("due_at",{ascending:true,nullsFirst:false}),supabase.from("team_members").select("id,display_name").eq("active",true).order("display_name")]);setItems((data??[]) as Item[]);setMembers(people??[]);}useEffect(()=>{void load();},[area]);
async function add(event:FormEvent){event.preventDefault();if(!profile)return;const {error}=await supabase.from("frc_operational_items").insert({area,title:title.trim(),details:details.trim()||null,owner_id:owner||null,due_at:due||null,created_by:profile.id});setMessage(error?.message??pick("Operations item created.","פריט תפעולי נוצר."));if(!error){setTitle("");setDetails("");setDue("");await load();}}
async function update(item:Item,status:string){const {error}=await supabase.from("frc_operational_items").update({status,updated_at:new Date().toISOString()}).eq("id",item.id);setMessage(error?.message??pick("Status updated.","הסטטוס עודכן."));if(!error)await load();}
async function remove(item:Item){if(!isAdmin||!confirm(pick("Delete this item permanently?","למחוק את הפריט לצמיתות?")))return;const {error}=await supabase.from("frc_operational_items").delete().eq("id",item.id);setMessage(error?.message??pick("Item deleted.","הפריט נמחק."));if(!error)await load();}
const label=areas.find(item=>item[0]===area)!;return <main className="hub-page frc-operations-page"><header className="hub-page-header"><div><div className="hub-eyebrow">FRC 6740 · {pick("Operations system","מערכת תפעול")}</div><h1>{pick(label[1],label[2])}</h1><p>{pick("Actionable records with ownership, status and deadlines.","רשומות לביצוע עם אחריות, סטטוס ומועדי יעד.")}</p></div></header><nav className="operations-area-tabs">{areas.map(([id,en,he])=><button className={area===id?"is-active":""} key={id} onClick={()=>setParams({area:id})}>{pick(en,he)}</button>)}</nav><form className="hub-card frc-operation-form" onSubmit={add}><label>{pick("Title","כותרת")}<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{pick("Details","פרטים")}<input value={details} onChange={e=>setDetails(e.target.value)}/></label><label>{pick("Owner","אחראי")}<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">{pick("Unassigned","ללא שיוך")}</option>{members.map(member=><option value={member.id} key={member.id}>{member.display_name}</option>)}</select></label><label>{pick("Due date","תאריך יעד")}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button className="hub-button">{pick("Add item","הוספת פריט")}</button></form>{message?<div className="auth-message">{message}</div>:null}<div className="operations-board">{items.map(item=><article className="hub-card operation-item" key={item.id}><div><span className={`operation-status status-${item.status}`}>{item.status.replace("_"," ")}</span><h2>{item.title}</h2><p>{item.details}</p><small>{members.find(member=>member.id===item.owner_id)?.display_name??pick("Unassigned","ללא שיוך")}{item.due_at?` · ${new Date(`${item.due_at}T12:00:00`).toLocaleDateString()}`:""}</small></div><select value={item.status} onChange={e=>void update(item,e.target.value)}><option value="open">{pick("Open","פתוח")}</option><option value="in_progress">{pick("In progress","בתהליך")}</option><option value="blocked">{pick("Blocked","חסום")}</option><option value="done">{pick("Done","הושלם")}</option></select>{isAdmin?<button className="danger-link" onClick={()=>void remove(item)}>{pick("Delete","מחיקה")}</button>:null}</article>)}</div></main>}
