import '../styles/operationalClarity.css';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useAccessControl} from '../lib/accessControl';
import {useAdminStatus} from '../lib/useAdminStatus';
import AccessibleDialog from '../components/AccessibleDialog';
import {money} from '../lib/finance';
import {productCost,finishedStock,materialDemand,type Product,type PrintJob,type FundEvent,type Sale,type Filament,type Material} from '../lib/fundraising';
import '../styles/fundraising.css';
const blankProduct=(cost:number)=>({name:'',model_url:'',notes:'',materials:[{part_id:'',grams:0}] as Material[],operating_cost:cost,other_cost:0,sale_price:0});
export default function FundraisingPage(){
 const {pick}=useLocalization(),access=useAccessControl(),admin=useAdminStatus(),can=access.can('manage_fundraising')||access.can('manage_inventory');
 const requestKey=useRef(crypto.randomUUID());
 const [params,setParams]=useSearchParams(),view=params.get('view')||'overview';
 const [products,setProducts]=useState<Product[]>([]),[jobs,setJobs]=useState<PrintJob[]>([]),[events,setEvents]=useState<FundEvent[]>([]),[sales,setSales]=useState<Sale[]>([]),[stock,setStock]=useState<Filament[]>([]),[people,setPeople]=useState<{id:string;display_name:string}[]>([]);
 const [defaultCost,setDefaultCost]=useState(0.5),[costDraft,setCostDraft]=useState('0.5'),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[jobFilter,setJobFilter]=useState('active');
 const [dialog,setDialog]=useState(''),[editing,setEditing]=useState<Product|null>(null),[product,setProduct]=useState(blankProduct(0.5));
 const [job,setJob]=useState({product_id:'',event_id:'',quantity:'1',owner_id:'',due_date:'',printer:'',notes:''});
 const [event,setEvent]=useState({name:'',event_date:new Date().toLocaleDateString('en-CA'),location:'',notes:''});
 const [selectedEvent,setSelectedEvent]=useState(''),[sale,setSale]=useState({id:'',event_id:'',product_id:'',quantity:'1',unit_price:'0',payment_method:'cash'});
 const [resultJob,setResultJob]=useState<PrintJob|null>(null),[good,setGood]=useState('0'),[actual,setActual]=useState<Material[]>([]),[resultNote,setResultNote]=useState(''),[voidId,setVoidId]=useState('');
 async function all<T,>(table:string){const out:T[]=[];for(let offset=0;;offset+=500){const {data,error}=await supabase.from(table).select('*').order('id').range(offset,offset+499);if(error)throw error;out.push(...data as T[]);if(data.length<500)return out;}}
 async function load(){setError('');try{const [p,j,e,s,f,m,c]=await Promise.all([all<Product>('fundraising_products'),all<PrintJob>('fundraising_jobs'),all<FundEvent>('fundraising_events'),all<Sale>('fundraising_sales'),supabase.from('frc_parts_inventory').select('id,name,quantity,unit_cost,filament_details').eq('archived',false).eq('unit','kg').not('filament_details','is',null),supabase.from('team_members').select('id,display_name').eq('active',true),supabase.from('fundraising_settings').select('operating_cost').single()]);for(const r of [f,m,c])if(r.error)throw r.error;setProducts(p);setJobs(j);setEvents(e);setSales(s);setStock(f.data??[]);setPeople(m.data??[]);setDefaultCost(Number(c.data!.operating_cost));setCostDraft(String(c.data!.operating_cost));setReady(true);}catch(e){setReady(false);setError(pick('Could not load workspace. Retry before making changes.','לא ניתן לטעון את המרחב. נסו שוב לפני ביצוע שינויים.')+' '+(e as Error).message);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{requestKey.current=crypto.randomUUID();},[dialog]);
 async function command(action:string,data:object){if(busy||!ready)return;setBusy(true);setError('');try{const r=await supabase.rpc('fundraising_command',{p_action:action,p_data:{...data,request_key:requestKey.current}});if(r.error)throw r.error;requestKey.current=crypto.randomUUID();setDialog('');setResultJob(null);setNotice(pick('Saved. Stock and totals refreshed.','נשמר. המלאי והסכומים עודכנו.'));await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function submit(action:string,data:object){return(e:FormEvent)=>{e.preventDefault();void command(action,data);};}
 const tabs=[['overview','Overview','סקירה'],['products','Products & costing','מוצרים ותמחור'],['jobs','Print queue','תור הדפסה'],['events','Events & sales','אירועים ומכירות'],['materials','Filament & purchasing','פילמנט ורכש'],['results','Results','תוצאות']];
 const status=(s:string)=>({planned:pick('Planned','מתוכנן'),printing:pick('Printing','בהדפסה'),succeeded:pick('Succeeded','הצליח'),partial:pick('Partially succeeded','הצלחה חלקית'),failed:pick('Failed','נכשל'),cancelled:pick('Cancelled','בוטל'),open:pick('Open for sales','פתוח למכירות'),closed:pick('Closed','סגור')}[s]??s);
 const revenue=sales.filter(s=>!s.voided).reduce((n,s)=>n+s.quantity*Number(s.unit_price),0),spent=jobs.reduce((n,j)=>n+Number(j.actual_cost??0),0),produced=jobs.reduce((n,j)=>n+j.good_units,0),failed=jobs.reduce((n,j)=>n+j.failed_units,0);
 const chosen=events.find(e=>e.id===selectedEvent),eventSales=sales.filter(s=>s.event_id===selectedEvent),active=products.filter(p=>!p.archived),estimated=productCost(product,stock);
 function edit(p?:Product){setEditing(p??null);setProduct(p?{...p,model_url:p.model_url??'',notes:p.notes??''}:blankProduct(defaultCost));setDialog('product');setError('');}
 function openSale(){setSale({id:crypto.randomUUID(),event_id:selectedEvent,product_id:'',quantity:'1',unit_price:'0',payment_method:'cash'});setDialog('sale');setError('');}
 function openResult(j:PrintJob){setResultJob(j);setGood(String(j.quantity));setActual(j.snapshot.materials.map(m=>({...m,grams:m.grams*j.quantity})));setResultNote('');setDialog('result');setError('');}
 function csv(){const rows=[['Product','Produced','Failed','Sold','Available','Revenue ILS','Production cost ILS'],...products.map(p=>{const js=jobs.filter(j=>j.product_id===p.id),ss=sales.filter(s=>s.product_id===p.id&&!s.voided);return[p.name,js.reduce((n,j)=>n+j.good_units,0),js.reduce((n,j)=>n+j.failed_units,0),ss.reduce((n,s)=>n+s.quantity,0),finishedStock(p.id,jobs,sales),ss.reduce((n,s)=>n+s.quantity*Number(s.unit_price),0),js.reduce((n,j)=>n+Number(j.actual_cost??0),0)];})];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='g3-fundraising-results.csv';a.click();URL.revokeObjectURL(url);}
 const actions=<div className="fr-actions"><button type="button" disabled={busy} onClick={()=>{setDialog('');setError('');}}>{pick('Cancel','ביטול')}</button><button className="primary" disabled={busy||!ready}>{busy?pick('Saving…','שומר…'):pick('Save','שמירה')}</button></div>;
 return <main className="hub-page fr-page"><header className="fr-header"><div><Link to="/work">← {pick('Team operations','תפעול הקבוצה')}</Link><div className="hub-eyebrow">G3 6740 · {pick('MAKE · SELL · SUPPORT THE TEAM','מייצרים · מוכרים · תומכים בקבוצה')}</div><h1>{pick('Fundraising & Production','גיוס כספים וייצור')}</h1><p>{pick('Turn print ideas into finished stock and recorded event income.','מרעיון להדפסה, למלאי מוצרים ולהכנסות מתועדות מאירועים.')}</p></div><div className="fr-actions"><button onClick={()=>void load()} disabled={busy}>{pick('Refresh','רענון')}</button>{can&&<button onClick={()=>setDialog('settings')} disabled={!ready}>{pick('Cost settings','הגדרות עלות')}</button>}</div></header>
 <nav className="fr-tabs" aria-label={pick('Workspace sections','מדורי המרחב')}>{tabs.map(([id,en,he])=><button key={id} aria-current={view===id?'page':undefined} onClick={()=>setParams({view:id})}>{pick(en,he)}</button>)}</nav>
 {error&&!dialog&&<p className="fr-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!ready?<section className="fr-empty">{pick('Loading workspace… If loading fails, use Refresh.','טוען מרחב… במקרה של כשל לחצו על רענון.')}</section>:<>
 {!can&&<p className="fr-empty" role="status">{pick('View only. An administrator can grant Manage fundraising production in Roles & permissions.','צפייה בלבד. מנהל יכול להעניק הרשאת ניהול ייצור לגיוס כספים בתפקידים והרשאות.')}</p>}{view==='overview'&&<><section className="fr-metrics">{[[pick('Sales recorded','מכירות שנרשמו'),money(revenue)],[pick('Ready to sell','מוכן למכירה'),products.reduce((n,p)=>n+finishedStock(p.id,jobs,sales),0)],[pick('In the print queue','בתור ההדפסה'),jobs.filter(j=>['planned','printing'].includes(j.status)).length],[pick('Filaments short for plan','סוגי פילמנט שחסרים לתכנון'),stock.filter(f=>f.quantity<materialDemand(f.id,jobs,['planned','printing'])).length]].map(([l,v])=><article key={String(l)}><span>{l}</span><strong>{v}</strong></article>)}</section><section className="fr-steps">{[['products','1','Define a product','הגדרת מוצר','Choose filament, grams, costs and selling price.','בחירת פילמנט, גרמים, עלויות ומחיר מכירה.'],['jobs','2','Plan & print','תכנון והדפסה','Assign quantity and record success, failures and actual usage.','הגדרת כמות ותיעוד הצלחה, כישלונות וצריכת חומר בפועל.'],['events','3','Sell at an event','מכירה באירוע','Record sales; close and post income to Finance.','רישום מכירות, סגירה והעברת ההכנסות לכספים.']].map(([v,n,en,he,d,dh])=><button key={v} onClick={()=>setParams({view:v})}><b>{n}</b><strong>{pick(en,he)}</strong><span>{pick(d,dh)}</span></button>)}</section>{!can&&<p>{pick('Read-only access. Inventory managers can manage products, printing and sales.','גישה לצפייה. מנהלי מלאי יכולים לנהל מוצרים, הדפסות ומכירות.')}</p>}</>}
 {view==='products'&&<><div className="fr-section-heading"><h2>{pick('Products & costing','מוצרים ותמחור')}</h2>{can&&<button className="primary" onClick={()=>edit()}>{pick('+ Add product','+ הוספת מוצר')}</button>}</div>{!products.length&&<p className="fr-empty">{pick('Start with one product. Add its filament to Inventory first.','התחילו במוצר אחד. הוסיפו תחילה את הפילמנט למלאי.')} <Link to="/tools">{pick('Open inventory','פתיחת מלאי')}</Link></p>}<div className="fr-grid">{products.map(p=>{const cost=productCost(p,stock);return <article className="fr-card" key={p.id}><span>{p.archived?pick('Archived','בארכיון'):pick('Product','מוצר')}</span><h3>{p.name}</h3><p>{p.notes}</p><dl><div><dt>{pick('Estimated unit cost','עלות משוערת ליחידה')}</dt><dd>{money(cost)}</dd></div><div><dt>{pick('Selling price','מחיר מכירה')}</dt><dd>{money(p.sale_price)}</dd></div><div><dt>{pick('Estimated profit / item','רווח משוער ליחידה')}</dt><dd>{money(p.sale_price-cost)}</dd></div><div><dt>{pick('Ready to sell','מוכן למכירה')}</dt><dd>{finishedStock(p.id,jobs,sales)}</dd></div></dl>{p.model_url&&<a href={p.model_url} target="_blank" rel="noreferrer">{pick('Open model / source','פתיחת מודל / מקור')} ↗</a>}{can&&<div className="fr-actions"><button onClick={()=>edit(p)}>{pick('Edit','עריכה')}</button><button disabled={busy} onClick={()=>void command('archive',{id:p.id})}>{p.archived?pick('Restore','שחזור'):pick('Archive','העברה לארכיון')}</button>{!p.archived&&<button className="primary" onClick={()=>{setJob({...job,product_id:p.id});setDialog('job');}}>{pick('Plan print','תכנון הדפסה')}</button>}</div>}</article>;})}</div></>}
 {view==='jobs'&&<><div className="fr-section-heading"><h2>{pick('Print queue','תור הדפסה')}</h2>{can&&<button className="primary" disabled={!active.length} onClick={()=>setDialog('job')}>{pick('+ Plan print','+ תכנון הדפסה')}</button>}</div><p>{pick('Planned jobs show material demand. Starting a job reserves its filament; recording results deducts actual usage. Include supports, purge and failed prints.','עבודות מתוכננות מציגות ביקוש לחומר. התחלת עבודה שומרת חומר; רישום תוצאות מפחית את הצריכה בפועל. כללו תמיכות, ניקוי וכישלונות.')}</p><label>{pick('Show jobs','הצגת עבודות')}<select value={jobFilter} onChange={e=>setJobFilter(e.target.value)}><option value="active">{pick('Planned & printing','מתוכנן ובהדפסה')}</option><option value="finished">{pick('Finished & cancelled','הסתיים ובוטל')}</option><option value="all">{pick('All jobs','כל העבודות')}</option></select></label>{!jobs.length&&<p className="fr-empty">{pick('No print jobs yet. Create a product, then plan a print.','אין עבודות הדפסה. צרו מוצר ואז תכננו הדפסה.')}</p>}<div className="fr-grid">{jobs.filter(j=>jobFilter==='all'||(jobFilter==='active'?['planned','printing'].includes(j.status):['succeeded','partial','failed','cancelled'].includes(j.status))).sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(j=><article className="fr-card" key={j.id}><span className={'fr-badge '+j.status}>{status(j.status)}</span><h3>{j.snapshot.name} · {j.quantity} {pick('items','יחידות')}</h3><p>{people.find(p=>p.id===j.owner_id)?.display_name||pick('Unassigned','ללא אחראי')} · {j.printer||pick('Printer not specified','ללא מדפסת')}{j.due_date?' · '+j.due_date:''}</p><p>{events.find(e=>e.id===j.event_id)?.name} {j.notes}</p><p>{pick('Estimated batch cost','עלות אצווה משוערת')}: {money(j.snapshot.unit_cost*j.quantity)}</p>{j.actual_cost!==null&&<p>{j.good_units} {pick('good','תקינות')} · {j.failed_units} {pick('failed','נכשלו')} · {money(j.actual_cost)}<br/>{j.result_note}</p>}{can&&<div className="fr-actions">{j.status==='planned'&&<><button className="primary" disabled={busy} onClick={()=>void command('start',{id:j.id})}>{pick('Start printing','התחלת הדפסה')}</button><button disabled={busy} onClick={()=>void command('cancel',{id:j.id})}>{pick('Cancel job','ביטול עבודה')}</button></>}{j.status==='printing'&&<button className="primary" onClick={()=>openResult(j)}>{pick('Record result & usage','רישום תוצאה וצריכה')}</button>}{['failed','partial'].includes(j.status)&&<button onClick={()=>{setJob({...job,product_id:j.product_id,event_id:j.event_id??'',quantity:String(j.failed_units)});setDialog('job');}}>{pick('Plan reprint','תכנון הדפסה חוזרת')}</button>}</div>}</article>)}</div></>}
 {view==='materials'&&<><h2>{pick('Material demand & shortages','ביקוש לחומר וחוסרים')}</h2><p>{pick('Inventory is shared with Tools & inventory. Purchasing and receiving remain in the existing purchasing flow.','המלאי משותף לכלים ומלאי. בקשות רכש וקבלת רכישות נשארות בתהליך הרכש הקיים.')}</p><div className="fr-grid">{stock.map(f=>{const demand=materialDemand(f.id,jobs,['planned','printing']),reserved=materialDemand(f.id,jobs,['printing']),short=Math.max(0,demand-f.quantity);return <article className="fr-card" key={f.id}><h3>{f.name}</h3><dl><div><dt>{pick('In stock','במלאי')}</dt><dd>{(f.quantity*1000).toLocaleString()} g</dd></div><div><dt>{pick('Reserved for printing','שמור להדפסה')}</dt><dd>{(reserved*1000).toLocaleString()} g</dd></div><div><dt>{pick('Total planned demand','סך הביקוש המתוכנן')}</dt><dd>{(demand*1000).toLocaleString()} g</dd></div><div><dt>{pick('Shortage','חוסר')}</dt><dd>{(short*1000).toLocaleString()} g {short>0?`≈ ${Math.ceil(short*1000/Number(f.filament_details.net_weight_g))} ${pick('spools','סלילים')}`:''}</dd></div></dl><Link to={'/tools?part='+f.id}>{pick('Open stock / request purchase','פתיחת מלאי / בקשת רכש')} →</Link></article>;})}</div><Link to="/tools">{pick('Add filament to inventory','הוספת פילמנט למלאי')}</Link></>}
 {view==='events'&&<><div className="fr-section-heading"><h2>{pick('Events & sales','אירועים ומכירות')}</h2>{can&&<button className="primary" onClick={()=>setDialog('event')}>{pick('+ Add event','+ הוספת אירוע')}</button>}</div><label>{pick('Choose event','בחירת אירוע')}<select value={selectedEvent} onChange={e=>setSelectedEvent(e.target.value)}><option value="">{pick('Choose…','בחירה…')}</option>{events.map(e=><option key={e.id} value={e.id}>{e.event_date.slice(0,10)} · {e.name} · {status(e.status)}</option>)}</select></label>{chosen&&<section className="fr-card"><h3>{chosen.name}</h3><p>{chosen.event_date.slice(0,10)} · {chosen.location} · {status(chosen.status)}</p><p>{chosen.notes}</p><strong>{money(eventSales.filter(s=>!s.voided).reduce((n,s)=>n+s.quantity*Number(s.unit_price),0))}</strong><p>{pick('Cash','מזומן')}: {money(eventSales.filter(s=>!s.voided&&s.payment_method==='cash').reduce((n,s)=>n+s.quantity*Number(s.unit_price),0))} · {pick('Digital','דיגיטלי')}: {money(eventSales.filter(s=>!s.voided&&s.payment_method==='digital').reduce((n,s)=>n+s.quantity*Number(s.unit_price),0))}</p><p>{chosen.income_id?pick('Posted to Finance. Sales are locked.','הועבר לכספים. המכירות נעולות.'):pick('Not yet posted to Finance. Close the event after checking sales.','טרם הועבר לכספים. סגרו את האירוע לאחר בדיקת המכירות.')}</p>{can&&!chosen.income_id&&<div className="fr-actions">{chosen.status==='open'&&<button className="primary" onClick={openSale}>{pick('+ Record sale','+ רישום מכירה')}</button>}<button disabled={busy} onClick={()=>void command('event_status',{id:chosen.id,status:chosen.status==='open'?'closed':'open'})}>{chosen.status==='open'?pick('Close event','סגירת אירוע'):pick('Open for sales','פתיחה למכירות')}</button>{admin&&chosen.status==='closed'&&<button disabled={busy} onClick={()=>void command('post_income',{id:chosen.id})}>{pick('Post income to Finance','העברת הכנסה לכספים')}</button>}</div>}<div className="fr-sales">{eventSales.map(s=><article key={s.id}><div><strong>{products.find(p=>p.id===s.product_id)?.name}</strong><p>{s.quantity} × {money(s.unit_price)} · {s.payment_method==='cash'?pick('Cash','מזומן'):pick('Digital','דיגיטלי')} {s.voided?pick('· Voided','· בוטל'):''}</p></div><strong>{money(s.quantity*s.unit_price)}</strong>{can&&!s.voided&&!chosen.income_id&&<button onClick={()=>{setVoidId(s.id);setResultNote('');setDialog('void');}}>{pick('Correct / void','תיקון / ביטול')}</button>}</article>)}</div></section>}</>}
 {view==='results'&&<><div className="fr-section-heading"><h2>{pick('Production & fundraising results','תוצאות ייצור וגיוס כספים')}</h2><button onClick={csv}>{pick('Export CSV','ייצוא CSV')}</button></div><section className="fr-metrics">{[[pick('Revenue','הכנסות'),money(revenue)],[pick('Production cost','עלות ייצור'),money(spent)],[pick('Revenue less all production','הכנסות פחות כל הייצור'),money(revenue-spent)],[pick('Print success rate','שיעור הצלחת הדפסה'),produced+failed?Math.round(produced/(produced+failed)*100)+'%':'—']].map(([l,v])=><article key={l}><span>{l}</span><strong>{v}</strong></article>)}</section><p>{pick('Production cost includes actual filament and the job’s operating/additional cost per attempted item, including failures and unsold stock. This is a production contribution estimate, not cash profit. Filament purchasing is already an expense in Finance; consumption is not charged again. Other event expenses belong in Finance.','עלות הייצור כוללת חומר בפועל ועלויות תפעול ותוספות לכל יחידה שנוסתה, כולל כישלונות ומלאי שלא נמכר. זהו אומדן תרומת הייצור, לא רווח מזומן. רכישת פילמנט כבר נרשמת כהוצאה בכספים; הצריכה אינה מחויבת שוב. הוצאות אירוע נוספות נרשמות בכספים.')}</p>{admin&&<Link to="/admin/finance">{pick('Open Finance & reimbursements','פתיחת כספים והחזרים')} →</Link>}</>}
 </>}
 {dialog&&<AccessibleDialog title={pick('Fundraising workspace','מרחב גיוס כספים')} onClose={()=>{if(!busy)setDialog('');}} className="fr-dialog">{error&&<p role="alert" className="fr-error">{error}</p>}
 {dialog==='settings'&&<form onSubmit={submit('settings',{operating_cost:costDraft})}><h2>{pick('Default operating cost','עלות תפעול ברירת מחדל')}</h2><p>{pick('Used for new products. Existing products and print jobs keep their costs.','משמש למוצרים חדשים. מוצרים ועבודות קיימים שומרים על העלויות שלהם.')}</p><label>{pick('ILS per printed item','ש״ח לכל יחידה מודפסת')}<input type="number" required min="0" step="0.01" value={costDraft} onChange={e=>setCostDraft(e.target.value)}/></label>{actions}</form>}
 {dialog==='product'&&<form onSubmit={submit('product',{...product,id:editing?.id,revision:editing?.revision})}><h2>{pick(editing?'Edit product':'Add product',editing?'עריכת מוצר':'הוספת מוצר')}</h2><div className="fr-form-grid"><label>{pick('Product name','שם מוצר')}<input required value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/></label><label>{pick('Model / source link (optional)','קישור למודל / מקור (רשות)')}<input type="url" value={product.model_url} onChange={e=>setProduct({...product,model_url:e.target.value})}/></label></div><h3>{pick('Filament per item','פילמנט ליחידה')}</h3><p>{pick('Use slicer weight, including supports and purge. Add a row for each material/colour.','השתמשו במשקל מתוכנת החיתוך, כולל תמיכות וניקוי. הוסיפו שורה לכל חומר/צבע.')}</p>{product.materials.map((m,i)=><div className="fr-material" key={i}><label>{pick('Inventory filament','פילמנט מהמלאי')}<select required value={m.part_id} onChange={e=>setProduct({...product,materials:product.materials.map((x,n)=>n===i?{...x,part_id:e.target.value}:x)})}><option value="">{pick('Choose filament','בחירת פילמנט')}</option>{stock.map(f=><option key={f.id} value={f.id}>{f.name} · {f.filament_details.material} · {f.filament_details.colour}</option>)}</select></label><label>{pick('Grams per item','גרם ליחידה')}<input type="number" required min="0.1" step="0.1" value={m.grams||''} onChange={e=>setProduct({...product,materials:product.materials.map((x,n)=>n===i?{...x,grams:Number(e.target.value)}:x)})}/></label><button type="button" disabled={product.materials.length===1} onClick={()=>setProduct({...product,materials:product.materials.filter((_,n)=>n!==i)})}>{pick('Remove','הסרה')}</button></div>)}<button type="button" onClick={()=>setProduct({...product,materials:[...product.materials,{part_id:'',grams:0}]})}>{pick('+ Add filament','+ הוספת פילמנט')}</button><div className="fr-form-grid">{(['operating_cost','other_cost','sale_price'] as const).map((k,i)=><label key={k}>{[pick('Operating cost / item (ILS)','עלות תפעול ליחידה (ש״ח)'),pick('Other cost / item (ILS)','עלות נוספת ליחידה (ש״ח)'),pick('Selling price / item (ILS)','מחיר מכירה ליחידה (ש״ח)')][i]}<input required type="number" min="0" step="0.01" value={product[k]} onChange={e=>setProduct({...product,[k]:Number(e.target.value)})}/></label>)}</div><p className="fr-cost" role="status">{pick('Cost','עלות')}: {money(estimated)} · {pick('Estimated profit','רווח משוער')}: {money(product.sale_price-estimated)}</p><label>{pick('Notes / print instructions','הערות / הוראות הדפסה')}<textarea value={product.notes} onChange={e=>setProduct({...product,notes:e.target.value})}/></label>{actions}</form>}
 {dialog==='job'&&<form onSubmit={submit('job',job)}><h2>{pick('Plan a print batch','תכנון אצוות הדפסה')}</h2><div className="fr-form-grid"><label>{pick('Product','מוצר')}<select required value={job.product_id} onChange={e=>setJob({...job,product_id:e.target.value})}><option value="">{pick('Choose…','בחירה…')}</option>{active.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{pick('Items to produce','כמות לייצור')}<input required type="number" min="1" max="100000" step="1" value={job.quantity} onChange={e=>setJob({...job,quantity:e.target.value})}/></label><label>{pick('Event (optional)','אירוע (רשות)')}<select value={job.event_id} onChange={e=>setJob({...job,event_id:e.target.value})}><option value="">{pick('General stock','מלאי כללי')}</option>{events.filter(e=>e.status!=='closed').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>{pick('Responsible person','אחראי/ת')}<select value={job.owner_id} onChange={e=>setJob({...job,owner_id:e.target.value})}><option value="">{pick('Unassigned','ללא שיוך')}</option>{people.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>{pick('Due date','תאריך יעד')}<input type="date" value={job.due_date} onChange={e=>setJob({...job,due_date:e.target.value})}/></label><label>{pick('Printer','מדפסת')}<input value={job.printer} onChange={e=>setJob({...job,printer:e.target.value})}/></label></div><label>{pick('Notes','הערות')}<textarea value={job.notes} onChange={e=>setJob({...job,notes:e.target.value})}/></label>{actions}</form>}
 {dialog==='result'&&resultJob&&<form onSubmit={submit('finish',{id:resultJob.id,good_units:Number(good),failed_units:resultJob.quantity-Number(good),actual_materials:actual,result_note:resultNote})}><h2>{pick('Record print result','רישום תוצאת הדפסה')} · {resultJob.snapshot.name}</h2><label>{pick('Successful items','יחידות תקינות')}<input type="number" min="0" max={resultJob.quantity} step="1" required value={good} onChange={e=>setGood(e.target.value)}/></label><p>{pick('Failed items','יחידות שנכשלו')}: {resultJob.quantity-Number(good)}</p><p>{pick('Confirm actual grams used, including failures. These amounts will be deducted from inventory once.','אשרו את הגרמים שנצרכו בפועל, כולל כישלונות. הכמויות יופחתו מהמלאי פעם אחת.')}</p>{actual.map((m,i)=><label key={m.part_id}>{m.name} · {pick('Actual grams','גרמים בפועל')}<input required type="number" min="0" step="0.1" value={m.grams} onChange={e=>setActual(actual.map((x,n)=>n===i?{...x,grams:Number(e.target.value)}:x))}/></label>)}<label>{pick('Result / failure notes','הערות תוצאה / כישלון')}<textarea required={Number(good)<(resultJob?.quantity??0)} minLength={Number(good)<(resultJob?.quantity??0)?3:undefined} value={resultNote} onChange={e=>setResultNote(e.target.value)}/></label>{actions}</form>}
 {dialog==='event'&&<form onSubmit={submit('event',event)}><h2>{pick('Add fundraising event','הוספת אירוע גיוס כספים')}</h2><label>{pick('Event name','שם האירוע')}<input required value={event.name} onChange={e=>setEvent({...event,name:e.target.value})}/></label><label>{pick('Date','תאריך')}<input required type="date" value={event.event_date} onChange={e=>setEvent({...event,event_date:e.target.value})}/></label><label>{pick('Location','מיקום')}<input value={event.location} onChange={e=>setEvent({...event,location:e.target.value})}/></label><label>{pick('Notes','הערות')}<textarea value={event.notes} onChange={e=>setEvent({...event,notes:e.target.value})}/></label>{actions}</form>}
 {dialog==='sale'&&<form onSubmit={submit('sale',sale)}><h2>{pick('Record a sale','רישום מכירה')}</h2><label>{pick('Product','מוצר')}<select required value={sale.product_id} onChange={e=>setSale({...sale,product_id:e.target.value,unit_price:String(products.find(p=>p.id===e.target.value)?.sale_price??0)})}><option value="">{pick('Choose…','בחירה…')}</option>{products.filter(p=>finishedStock(p.id,jobs,sales)>0).map(p=><option key={p.id} value={p.id}>{p.name} · {finishedStock(p.id,jobs,sales)} {pick('available','זמינים')}</option>)}</select></label><label>{pick('Quantity sold','כמות שנמכרה')}<input required type="number" min="1" step="1" value={sale.quantity} onChange={e=>setSale({...sale,quantity:e.target.value})}/></label><label>{pick('Actual price per item (ILS)','מחיר בפועל ליחידה (ש״ח)')}<input required type="number" min="0" step="0.01" value={sale.unit_price} onChange={e=>setSale({...sale,unit_price:e.target.value})}/></label><label>{pick('Payment method','אמצעי תשלום')}<select value={sale.payment_method} onChange={e=>setSale({...sale,payment_method:e.target.value})}><option value="cash">{pick('Cash','מזומן')}</option><option value="digital">{pick('Digital','דיגיטלי')}</option></select></label><p className="fr-cost">{pick('Sale total','סכום המכירה')}: {money(Number(sale.quantity)*Number(sale.unit_price))}</p>{actions}</form>}
 {dialog==='void'&&<form onSubmit={submit('void_sale',{id:voidId,reason:resultNote})}><h2>{pick('Void incorrect sale','ביטול מכירה שגויה')}</h2><p>{pick('Restores finished stock and removes this sale from event totals. This does not issue a payment refund.','מחזיר מלאי מוצרים ומסיר את המכירה מסכומי האירוע. פעולה זו אינה מבצעת החזר תשלום.')}</p><label>{pick('Reason','סיבה')}<textarea required minLength={3} value={resultNote} onChange={e=>setResultNote(e.target.value)}/></label>{actions}</form>}
 </AccessibleDialog>}
 </main>;
}
