import {useAccessControl} from '../lib/accessControl';
import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../supabase';
import {useAdminStatus} from '../lib/useAdminStatus';
import {EvidenceClaim,EvidenceSource,findEvidence} from '../lib/knowledgeEvidence';
import {useLocalization} from '../lib/localization';
import {KnowledgeSeason,readAllEvidence} from '../lib/knowledgeSources';
import KnowledgeSourceCenter from '../components/KnowledgeSourceCenter';
import '../styles/intelligence.css';
import RobotResearch from '../components/RobotResearch';
import EvidenceTopicFilter,{EvidenceAssociation} from '../components/EvidenceTopicFilter';
import type {CollectedSourceSearch} from '../lib/collectedSources';
export default function KnowledgeEvidencePage({sourceSearch}:{sourceSearch?:CollectedSourceSearch}){
 const [topicFilter,setTopicFilter]=useState<{ids:string[];mode:'all'|'any';links:EvidenceAssociation[]}>({ids:[],mode:'all',links:[]});
 const [allSeasons,setAllSeasons]=useState(false);
 const [params,setParams]=useSearchParams();const showSources=params.get('view')==='sources';const showRobots=params.get('view')==='robots';
 const {pick}=useLocalization();const [seasons,setSeasons]=useState<Record<number,string>>({});const [refresh,setRefresh]=useState(0);
 const {can}=useAccessControl();
 const [sources,setSources]=useState<EvidenceSource[]>([]),[claims,setClaims]=useState<EvidenceClaim[]>([]),[season,setSeason]=useState(new Date().getFullYear()),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([readAllEvidence<EvidenceSource>('frc_evidence_sources'),readAllEvidence<EvidenceClaim>('frc_evidence_claims'),supabase.from('frc_knowledge_seasons').select('season,name').order('season',{ascending:false})]).then(([s,c,configured])=>{if(!active)return;setSources(s);setClaims(c);const configuredEntries=(configured.data??[]) as KnowledgeSeason[];const entries=[...configuredEntries,...[...new Set(s.map(source=>source.season))].filter(year=>!configuredEntries.some(row=>row.season===year)).map(year=>({season:year,name:String(year)}))];setSeasons(Object.fromEntries(entries.map(row=>[row.season,row.name])));setSeason(current=>entries.some(row=>row.season===current)?current:(entries[0]?.season??current));}).catch(()=>{if(active)setError('The evidence index is unavailable. Your existing knowledge library remains available.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[refresh]);
 const results=findEvidence(claims,sources,allSeasons?'all':season,query).filter(c=>{const matches=(id:string)=>topicFilter.links.some(l=>l.claim_id===c.id&&l.claim_revision===c.revision&&l.topic_id===id);return !topicFilter.ids.length||(topicFilter.mode==='all'?topicFilter.ids.every(matches):topicFilter.ids.some(matches));});const seasonSources=sources.filter(s=>s.current&&(allSeasons||s.season===season));const verifiedCount=findEvidence(claims,sources,allSeasons?'all':season,'').length;
 const admin=useAdminStatus();const [edit,setEdit]=useState<EvidenceClaim|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setMessage('');const {error}=await supabase.rpc('curate_frc_evidence',{p_id:edit?.id??null,p_expected:edit?.revision??0,p_source:data.get('source'),p_title:data.get('title'),p_body:data.get('body'),p_locator:data.get('locator'),p_kind:'fact',p_status:data.get('status'),p_note:data.get('reason')});setBusy(false);if(error){setMessage(error.message);return;}try{setClaims(await readAllEvidence<EvidenceClaim>('frc_evidence_claims'));}catch{setMessage('Saved; reload to refresh the index.');return;}setEdit(null);form.reset();setMessage('Evidence saved.');}
 return <main className="intel-page knowledge-evidence-page"><header className="intel-heading"><div><small className="intel-kicker">{pick('ENGINEERING KNOWLEDGE','ידע הנדסי')}</small><h1>{pick('Evidence search','חיפוש מקורות')}</h1><p>{pick('Find reviewed references, inspect their sources and keep track of official document changes.','מצאו מקורות שנבדקו, עיינו באסמכתאות ועקבו אחר שינויים במסמכים רשמיים.')}</p></div>{can("view_field_twin")&&<Link className="intel-link" to="/field-twin">{pick('Explore the field twin →','פתיחת מודל המגרש ←')}</Link>}</header>
 <nav className="intel-tabs"><Link to="/updates?view=knowledge">{pick("Team knowledge library","ספריית הידע של הקבוצה")}</Link>{!showSources&&<a href="https://www.firstinspires.org/resources/library/frc/season-materials" target="_blank" rel="noreferrer">{pick("Official season materials ↗","חומרי העונה הרשמיים ↗")}</a>}</nav>
 {!showRobots&&<section className="knowledge-controls"><label>{pick('Season','עונה')}<select value={!showSources&&allSeasons?"all":season} onChange={e=>{const all=e.target.value==="all";setAllSeasons(all);if(!all)setSeason(Number(e.target.value));}} disabled={loading}>{!showSources&&<option value="all">{pick("All seasons","כל העונות")}</option>}{Object.keys(seasons).map(Number).sort((a,b)=>b-a).map(y=><option key={y} value={y}>{seasons[y]===String(y)?y:`${y} · ${seasons[y]}`}</option>)}</select></label>{!showSources&&<label>{pick('Search reviewed evidence','חיפוש במקורות שנבדקו')}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={pick('Keywords: elevator, turret or a rule number','מילות מפתח: מעלית, צריח או מספר חוק')} /></label>}</section>}
 <nav className="intel-tabs" aria-label={pick('Evidence views','תצוגות מקורות')}><button aria-pressed={!showSources&&!showRobots} onClick={()=>{const next=new URLSearchParams(params);next.delete("view");setParams(next);}}>{pick('Reviewed evidence','מקורות שנבדקו')}</button><button aria-pressed={showRobots} onClick={()=>{const next=new URLSearchParams(params);next.set("view","robots");setParams(next);}}>{pick("Robots & mechanisms","רובוטים ומנגנונים")}</button><button aria-pressed={showSources} onClick={()=>{const next=new URLSearchParams(params);next.set("view","sources");setParams(next);}}>{pick('Official documents & updates','מסמכים רשמיים ועדכונים')}</button></nav>
 {showSources&&<KnowledgeSourceCenter season={season} admin={admin} onSeasonAdded={row=>{setSeasons(current=>({...current,[row.season]:row.name}));setSeason(row.season);}} onEvidenceChanged={()=>setRefresh(n=>n+1)}/>}
 {showRobots&&<RobotResearch admin={admin} sourceSearch={sourceSearch}/>}
 {!showSources&&!showRobots&&<><EvidenceTopicFilter onFilter={setTopicFilter}/><p className="knowledge-strip">{pick('Search covers reviewed references already in this index. It is not yet a complete catalogue of robots, mechanisms or rulebooks. Newly discovered documents need indexing and review before they appear here.','החיפוש כולל מקורות שנבדקו ונוספו לאינדקס. זה עדיין אינו קטלוג מלא של רובוטים, מנגנונים או ספרי חוקים. מסמכים חדשים דורשים אינדוקס ובדיקה לפני שיופיעו כאן.')}</p>
 <section className="evidence-card"><h2>{allSeasons?pick("All seasons","כל העונות"):seasons[season]===String(season)?season:`${season} · ${seasons[season]??''}`}</h2><a href="https://www.firstinspires.org/resources/library/frc/archived-games" target="_blank" rel="noreferrer">{pick("FIRST historical archive ↗","ארכיון העונות של FIRST ↗")}</a><p>{season===2021?pick('The game manual and At Home challenges have distinct rules. Check which format applies.','למדריך המשחק ולאתגרי At Home חוקים נפרדים. בדקו איזה פורמט חל.'):pick('Every reviewed reference belongs to a specific source revision. Historical rules do not establish current-season legality.','כל מקור שנבדק שייך לגרסה מסוימת. חוקים מעונות קודמות אינם קובעים חוקיות בעונה הנוכחית.')}</p><div className="intel-tabs">{seasonSources.map(source=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>)}</div><p>{verifiedCount} {pick('reviewed references','מקורות שנבדקו')} · {seasonSources.length} {pick('current source snapshots','גרסאות מקור נוכחיות')}</p>{!seasonSources.length&&<p>{pick('No reviewed source revision is available for this season yet. Use Official documents & updates to see what has been discovered.','עדיין אין גרסת מקור שנבדקה לעונה זו. בתצוגת מסמכים רשמיים ועדכונים תוכלו לראות מה אותר.')}</p>}</section>
 {loading?<p role="status">Loading evidence…</p>:error?<p role="alert">{error}</p>:<><p>{results.length} {pick("matching references","מקורות תואמים")}</p><div className="knowledge-evidence-grid">{results.map(c=>{const s=sources.find(x=>x.id===c.source_id)!;return <article className="evidence-card" key={c.id}><small>{s.season} · {s.authority} · {c.claim_kind}</small><h2>{c.title}</h2><p>{c.body}</p><a href={`${s.url}${c.locator.match(/PDF page (\d+)/)?.[1]?'#page='+c.locator.match(/PDF page (\d+)/)![1]:''}`} target="_blank" rel="noreferrer">Read source: {c.locator} ↗</a><p>{s.revision} · checked {new Date(s.checked_at).toLocaleDateString()}</p><details><summary>Source verification</summary><p>{s.title}</p><code style={{overflowWrap:'anywhere'}}>{s.sha256??'No document fingerprint'}</code></details></article>;})}</div>{results.length===0&&<div className="evidence-empty"><h2>{pick("No matching indexed references","לא נמצאו מקורות תואמים באינדקס")}</h2><p>{pick("No reviewed reference matches these keywords in the selected seasons. This does not mean no robot used that mechanism. Try fewer keywords or another season.","לא נמצא מקור שנבדק התואם למילות המפתח בעונות שנבחרו. אין פירוש הדבר שלא היה רובוט שהשתמש במנגנון הזה. נסו פחות מילות מפתח או עונה אחרת.")}</p></div>}</>}
 {admin&&<details className="knowledge-curation"><summary>{pick("Manage references · Admin only","ניהול מקורות · למנהלים בלבד")}</summary><p>{pick("Add a sourced reference or correct an existing one. This editor controls what appears in evidence search; it does not fetch documents.","הוסיפו מקור עם אסמכתא או תקנו מקור קיים. עורך זה קובע מה מופיע בחיפוש; הוא אינו מוריד מסמכים.")}</p><p>Publish only after checking the cited page against its recorded source revision. Use Conflicted to remove disputed evidence from search.</p><label>Edit an existing reference<select value={edit?.id??''} onChange={e=>setEdit(claims.find(c=>c.id===e.target.value)??null)}><option value="">Create a new draft</option>{claims.map(c=><option key={c.id} value={c.id}>{c.title} · {c.status}</option>)}</select></label><form key={edit?.id??'new'} onSubmit={save}><label>Source revision<select required name="source" defaultValue={edit?.source_id??''}><option value="" disabled>Choose a verified source</option>{sources.filter(s=>s.current).map(s=><option value={s.id} key={s.id}>{s.season} · {s.title} · {s.revision}</option>)}</select></label><label>Title<input name="title" required minLength={3} maxLength={180} defaultValue={edit?.title}/></label><label>Short factual summary<textarea name="body" required minLength={3} maxLength={1500} defaultValue={edit?.body}/></label><label>Section and page<input name="locator" required maxLength={200} defaultValue={edit?.locator}/></label><label>Status<select name="status" defaultValue={edit?.status??'draft'}>{['draft','published','conflicted','withdrawn'].map(s=><option key={s}>{s}</option>)}</select></label><label>Reason for this change<input name="reason" required minLength={3}/></label><div className="intel-button-row"><button className="intel-primary" disabled={busy}>{busy?'Saving…':'Save evidence'}</button></div><p role="status">{message}</p></form></details>}
 </>}
 </main>;
}
