import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useAdminStatus} from '../lib/useAdminStatus';
import {EvidenceClaim,EvidenceSource,findEvidence} from '../lib/knowledgeEvidence';
import '../styles/intelligence.css';
const seasons:Record<number,string>={2026:'REBUILT',2025:'REEFSCAPE',2024:'CRESCENDO',2023:'CHARGED UP',2022:'RAPID REACT',2021:'INFINITE RECHARGE / At Home',2020:'INFINITE RECHARGE',2019:'Destination: Deep Space',2018:'FIRST POWER UP',2017:'FIRST STEAMWORKS'};
export default function KnowledgeEvidencePage(){
 const [sources,setSources]=useState<EvidenceSource[]>([]),[claims,setClaims]=useState<EvidenceClaim[]>([]),[season,setSeason]=useState(2026),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;Promise.all([supabase.from('frc_evidence_sources').select('*'),supabase.from('frc_evidence_claims').select('*')]).then(([s,c])=>{if(!active)return;setLoading(false);if(s.error||c.error){setError('The evidence index is unavailable. Your existing knowledge library remains available.');return;}setSources(s.data??[]);setClaims(c.data??[]);});return()=>{active=false;};},[]);
 const results=findEvidence(claims,sources,season,query);
 const admin=useAdminStatus();const [edit,setEdit]=useState<EvidenceClaim|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setMessage('');const {error}=await supabase.rpc('curate_frc_evidence',{p_id:edit?.id??null,p_expected:edit?.revision??0,p_source:data.get('source'),p_title:data.get('title'),p_body:data.get('body'),p_locator:data.get('locator'),p_kind:'fact',p_status:data.get('status'),p_note:data.get('reason')});setBusy(false);if(error){setMessage(error.message);return;}const updated=await supabase.from('frc_evidence_claims').select('*');if(updated.error){setMessage('Saved; reload to refresh the index.');return;}setClaims(updated.data??[]);setEdit(null);form.reset();setMessage('Evidence saved.');}
 return <main className="intel-page"><header className="intel-heading"><div><small className="intel-kicker">ENGINEERING KNOWLEDGE · EVIDENCE PILOT</small><h1>Find the source. Understand the evidence.</h1><p>Verified excerpts with season, revision and source location. Historical material never establishes current-season legality.</p></div><Link className="intel-link" to="/field-twin">Explore the field twin →</Link></header>
 <nav className="intel-tabs"><Link to="/updates?view=knowledge">Team knowledge library</Link><a href="https://www.firstinspires.org/resources/library/frc/season-materials" target="_blank" rel="noreferrer">Official season materials ↗</a></nav>
 <section className="knowledge-controls"><label>Season<select value={season} onChange={e=>setSeason(Number(e.target.value))}>{Object.keys(seasons).map(Number).sort((a,b)=>b-a).map(y=><option key={y} value={y}>{y} · {seasons[y]}</option>)}</select></label><label>Search verified evidence<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try field, auto, fuel or hub" /></label></section>
 <p className="knowledge-strip">The season directory covers 2017–2026. Verified excerpts are counted separately below; a listed season does not mean its rulebook has been fully indexed.</p>
 <section className="evidence-card"><h2>{season} · {seasons[season]}</h2><p>{season===2021?'This archive includes At Home challenges as well as the game manual. Do not treat its formats as interchangeable.':'Use the official archive for the season manual, updates and available field resources.'}</p><a href="https://www.firstinspires.org/resources/library/frc/archived-games" target="_blank" rel="noreferrer">Open FIRST archive and expand {season} ↗</a><p>{season===2026?'3D field available in the studio.':'Historical 3D field not installed. Knowledge season selection does not change the simulation.'}</p></section>
 {loading?<p role="status">Loading evidence…</p>:error?<p role="alert">{error}</p>:<><p>{results.length} matching references · no model calls</p><div className="knowledge-evidence-grid">{results.map(c=>{const s=sources.find(x=>x.id===c.source_id)!;return <article className="evidence-card" key={c.id}><small>{s.season} · {s.authority} · {c.claim_kind}</small><h2>{c.title}</h2><p>{c.body}</p><a href={s.url} target="_blank" rel="noreferrer">Read source: {c.locator} ↗</a><p>{s.revision} · checked {new Date(s.checked_at).toLocaleDateString()}</p><details><summary>Source verification</summary><p>{s.title}</p><code style={{overflowWrap:'anywhere'}}>{s.sha256??'No document fingerprint'}</code></details></article>;})}</div>{results.length===0&&<div className="evidence-empty"><h2>Insufficient indexed evidence</h2><p>No published, current reference matches this search in {season}. Check the official manual and updates; do not infer that a design is permitted.</p></div>}</>}
 {admin&&<section className="knowledge-curation"><h2>Curate evidence</h2><p>Publish only after checking the cited page against its recorded source revision. Use Conflicted to remove disputed evidence from search.</p><label>Edit an existing reference<select value={edit?.id??''} onChange={e=>setEdit(claims.find(c=>c.id===e.target.value)??null)}><option value="">Create a new draft</option>{claims.map(c=><option key={c.id} value={c.id}>{c.title} · {c.status}</option>)}</select></label><form key={edit?.id??'new'} onSubmit={save}><label>Source revision<select required name="source" defaultValue={edit?.source_id??''}><option value="" disabled>Choose a verified source</option>{sources.filter(s=>s.current).map(s=><option value={s.id} key={s.id}>{s.season} · {s.title} · {s.revision}</option>)}</select></label><label>Title<input name="title" required minLength={3} maxLength={180} defaultValue={edit?.title}/></label><label>Short factual summary<textarea name="body" required minLength={3} maxLength={1500} defaultValue={edit?.body}/></label><label>Section and page<input name="locator" required maxLength={200} defaultValue={edit?.locator}/></label><label>Status<select name="status" defaultValue={edit?.status??'draft'}>{['draft','published','conflicted','withdrawn'].map(s=><option key={s}>{s}</option>)}</select></label><label>Reason for this change<input name="reason" required minLength={3}/></label><div className="intel-button-row"><button className="intel-primary" disabled={busy}>{busy?'Saving…':'Save evidence'}</button></div><p role="status">{message}</p></form></section>}
 </main>;
}
