import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../supabase";
import { useMemberAuth } from "../lib/memberAuth";
import { useLocalization } from "../lib/localization";

type Project = { id:string; name:string; description:string|null; status:string; due_at:string|null; owner_id:string|null; subteam:string|null };
type Task = { id:string; project_id:string; title:string; status:string; assignee_id:string|null; due_at:string|null };
type Tool = { id:string; name:string; category:string|null; asset_tag:string|null; status:string; requires_training:boolean };
type Checkout = { id:string; tool_id:string; member_id:string; checked_out_at:string; returned_at:string|null };
type Maintenance = { id:string; tool_id:string; description:string; status:string; created_at:string };

export function ProfilePage() {
  const { profile } = useMemberAuth();
  const { pick } = useLocalization();
  const [members,setMembers]=useState<Array<{id:string;display_name:string;role:string;subteam:string|null}>>([]);
  useEffect(()=>{supabase.from("team_members").select("id,display_name,role,subteam").eq("active",true).order("display_name").then(({data})=>setMembers(data??[]));},[]);
  return <div className="hub-page"><header className="hub-page-header"><div><div className="hub-eyebrow">{pick("Team directory","ספר הקבוצה")}</div><h1>{profile?.display_name}</h1><p>{profile?.role} · {profile?.subteam || pick("No subteam assigned","לא שובץ תת־צוות")}</p></div></header><section className="hub-card"><h2>{pick("Active team","חברי קבוצה פעילים")}</h2><div className="member-directory">{members.map(member=><article className="member-row" key={member.id}><div className="member-avatar">{member.display_name[0]}</div><div className="member-identity"><strong>{member.display_name}</strong><small>{member.subteam||pick("General","כללי")} · {member.role}</small></div></article>)}</div></section></div>;
}

export function ProjectsPage() {
  const { pick }=useLocalization();
  const { profile }=useMemberAuth(); const [projects,setProjects]=useState<Project[]>([]); const [tasks,setTasks]=useState<Task[]>([]); const [name,setName]=useState(""); const [message,setMessage]=useState("");
  const load=async()=>{const [{data:p},{data:t}]=await Promise.all([supabase.from("team_projects").select("*").order("created_at",{ascending:false}),supabase.from("project_tasks").select("*").order("created_at")]);setProjects((p??[]) as Project[]);setTasks((t??[]) as Task[]);};
  useEffect(()=>{void load();},[]);
  async function addProject(e:FormEvent){e.preventDefault();if(!profile)return;const {error}=await supabase.from("team_projects").insert({name:name.trim(),owner_id:profile.id,subteam:profile.subteam,status:"active"});setMessage(error?.message??"Project created.");if(!error){setName("");await load();}}
  async function addTask(projectId:string){const title=window.prompt(pick("Task title","שם המשימה"));if(!title||!profile)return;const due=window.prompt(pick("Due date (YYYY-MM-DD), optional","תאריך יעד (YYYY-MM-DD), לא חובה"));await supabase.from("project_tasks").insert({project_id:projectId,title:title.trim(),due_at:due?new Date(`${due}T18:00:00+03:00`).toISOString():null,assignee_id:profile.id,created_by:profile.id});await load();}
  async function cycleProject(project:Project){const states=["planning","active","blocked","completed"];const next=states[(states.indexOf(project.status)+1)%states.length];await supabase.from("team_projects").update({status:next,updated_at:new Date().toISOString()}).eq("id",project.id);await load();}
  async function toggleTask(task:Task){await supabase.from("project_tasks").update({status:task.status==="done"?"todo":"done",completed_at:task.status==="done"?null:new Date().toISOString()}).eq("id",task.id);await load();}
  return <div className="hub-page"><header className="hub-page-header"><div><div className="hub-eyebrow">{pick("Build season","עונת הבנייה")}</div><h1>{pick("Projects & tasks","פרויקטים ומשימות")}</h1><p>{pick("Track ownership, work and deadlines across every subteam.","מעקב אחר אחריות, עבודה ומועדי יעד בכל תתי־הצוותים.")}</p></div></header><form className="hub-card operations-inline" onSubmit={addProject}><input required value={name} onChange={e=>setName(e.target.value)} placeholder={pick("New project name","שם פרויקט חדש")}/><button className="hub-button">{pick("Create project","יצירת פרויקט")}</button></form>{message?<div className="auth-message">{message}</div>:null}<div className="hub-card-grid">{projects.map(project=><section className="hub-card project-card" key={project.id}><div className="announcement-meta"><button onClick={()=>cycleProject(project)}>{project.status}</button><span>{project.subteam||pick("Team","קבוצה")}</span></div><h2>{project.name}</h2><p>{project.description||pick("No description yet.","אין עדיין תיאור.")}</p><div className="task-list">{tasks.filter(task=>task.project_id===project.id).map(task=><button className={task.status==="done"?"task-row is-done":"task-row"} key={task.id} onClick={()=>toggleTask(task)}><span>{task.status==="done"?"✓":"○"}</span><span>{task.title}{task.due_at?<small> · {new Date(task.due_at).toLocaleDateString()}</small>:null}</span></button>)}</div><button className="announcement-link" onClick={()=>addTask(project.id)}>+ {pick("Add task","הוספת משימה")}</button></section>)}</div></div>;
}

export function ToolsPage() {
  const { pick }=useLocalization(); const {profile}=useMemberAuth(); const [tools,setTools]=useState<Tool[]>([]); const [checkouts,setCheckouts]=useState<Checkout[]>([]); const [maintenance,setMaintenance]=useState<Maintenance[]>([]); const [name,setName]=useState(""); const [category,setCategory]=useState(""); const isAdmin=profile?.role==="admin";
  const load=async()=>{const [{data:t},{data:c},{data:m}]=await Promise.all([supabase.from("workshop_tools").select("*").order("name"),supabase.from("tool_checkouts").select("*").is("returned_at",null),supabase.from("tool_maintenance").select("*").neq("status","resolved").order("created_at",{ascending:false})]);setTools((t??[]) as Tool[]);setCheckouts((c??[]) as Checkout[]);setMaintenance((m??[]) as Maintenance[]);}; useEffect(()=>{void load();},[]);
  async function addTool(e:FormEvent){e.preventDefault();await supabase.from("workshop_tools").insert({name:name.trim(),category:category.trim()||null,created_by:profile?.id});setName("");setCategory("");await load();}
  async function toggle(tool:Tool){if(!profile)return;const checkout=checkouts.find(item=>item.tool_id===tool.id);if(checkout){if(checkout.member_id!==profile.id&&!isAdmin)return;await supabase.from("tool_checkouts").update({returned_at:new Date().toISOString(),returned_to:profile.id}).eq("id",checkout.id);}else{await supabase.from("tool_checkouts").insert({tool_id:tool.id,member_id:profile.id});}await load();}
  async function report(tool:Tool){if(!profile)return;const description=window.prompt(pick("Describe the maintenance or safety issue","תארו את התקלה או בעיית הבטיחות"));if(!description?.trim())return;await supabase.from("tool_maintenance").insert({tool_id:tool.id,description:description.trim(),reported_by:profile.id});await load();}
  async function resolve(item:Maintenance){if(!isAdmin)return;await supabase.from("tool_maintenance").update({status:"resolved",resolved_at:new Date().toISOString()}).eq("id",item.id);await load();}
  return <div className="hub-page"><header className="hub-page-header"><div><div className="hub-eyebrow">{pick("Workshop inventory","מלאי הסדנה")}</div><h1>{pick("Tools","כלים")}</h1><p>{pick("Availability, responsibility, training and maintenance in one place.","זמינות, אחריות, הכשרות ותחזוקה במקום אחד.")}</p></div></header>{isAdmin?<form className="hub-card operations-inline" onSubmit={addTool}><input required value={name} onChange={e=>setName(e.target.value)} placeholder={pick("Tool name","שם הכלי")}/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder={pick("Category","קטגוריה")}/><button className="hub-button">{pick("Add tool","הוספת כלי")}</button></form>:null}<div className="hub-list-card">{tools.map(tool=>{const checkout=checkouts.find(item=>item.tool_id===tool.id);return <div className="hub-list-row" key={tool.id}><span><strong>{tool.name}</strong><small>{tool.category||pick("General","כללי")} · {checkout?pick("Checked out","מושאל"):pick("Available","זמין")}{tool.requires_training?` · ${pick("Training required","נדרשת הכשרה")}`:""}</small></span><div className="member-actions"><button onClick={()=>report(tool)}>{pick("Report issue","דיווח תקלה")}</button><button className="announcement-link" disabled={Boolean(checkout&&checkout.member_id!==profile?.id&&!isAdmin)} onClick={()=>toggle(tool)}>{checkout?pick("Return","החזרה"):pick("Check out","השאלה")}</button></div></div>;})}</div>{maintenance.length?<section className="hub-card"><h2>{pick("Open maintenance","תחזוקה פתוחה")}</h2>{maintenance.map(item=><div className="hub-list-row" key={item.id}><span><strong>{tools.find(t=>t.id===item.tool_id)?.name}</strong><small>{item.description}</small></span>{isAdmin?<button onClick={()=>resolve(item)}>{pick("Resolve","סגירה")}</button>:<span>{item.status}</span>}</div>)}</section>:null}</div>;
}

export function SettingsPage() {
  const {profile,refreshProfile}=useMemberAuth();
  const {language,setLanguage}=useLocalization();
  useEffect(()=>{if(profile?.language)setLanguage(profile.language);},[profile?.language]);
  async function chooseLanguage(next:"en"|"he"){setLanguage(next);const {error}=await supabase.rpc("set_my_language",{next_language:next});if(!error)await refreshProfile();}
  return <div className="hub-page"><header className="hub-page-header"><div><div className="hub-eyebrow">Preferences</div><h1>{language==="he"?"הגדרות":"Settings"}</h1><p>{language==="he"?"שפה, התראות ופרטיות":"Language, notifications and privacy."}</p></div></header><section className="hub-card"><h2>{language==="he"?"שפת האפליקציה":"App language"}</h2><div className="language-picker"><button className={language==="en"?"hub-button":"hub-button secondary"} onClick={()=>chooseLanguage("en")}>English</button><button className={language==="he"?"hub-button":"hub-button secondary"} onClick={()=>chooseLanguage("he")}>עברית</button></div><div className="hub-privacy-note"><strong>{language==="he"?"פרטיות כברירת מחדל":"Privacy by default"}</strong><span>{language==="he"?"אין מעקב מיקום ברקע. המיקום נבדק רק בעת דיווח נוכחות.":"No background location tracking. Location is checked only when recording attendance."}</span></div></section></div>;
}
