import { useEffect, useMemo, useState } from "react";
import { useLocalization } from "../lib/localization";
import type { TeamRole } from "../lib/memberAuth";
import { supabase } from "../supabase";

type Permission={permission_key:string;permission_group:string;label:string;label_he:string;description:string;protected:boolean;sort_order:number};
type RolePermission={role:TeamRole;permission_key:string;allowed:boolean};
const roles:TeamRole[]=["member","team_leader","mentor","admin"];
const roleNames:Record<TeamRole,[string,string]>={member:["Student","תלמיד/ה"],team_leader:["Team leader","מוביל/ת צוות"],mentor:["Mentor","מנטור/ית"],admin:["Administrator","מנהל/ת"]};

export default function PermissionsAdminPage(){
 const {pick}=useLocalization(),[catalog,setCatalog]=useState<Permission[]>([]),[grants,setGrants]=useState<RolePermission[]>([]),[message,setMessage]=useState(""),[saving,setSaving]=useState("");
 async function load(){const [p,r]=await Promise.all([supabase.from("app_permissions").select("*").order("sort_order"),supabase.from("role_permissions").select("role,permission_key,allowed")]);const error=p.error||r.error;if(error)setMessage(error.message);else{setCatalog((p.data??[]) as Permission[]);setGrants((r.data??[]) as RolePermission[]);}}
 useEffect(()=>{void load();},[]);
 const groups=useMemo(()=>Array.from(new Set(catalog.map(item=>item.permission_group))),[catalog]);
 function allowed(role:TeamRole,key:string){return role==="admin"||Boolean(grants.find(item=>item.role===role&&item.permission_key===key)?.allowed);}
 async function toggle(role:TeamRole,permission:Permission){if(role==="admin"||permission.protected)return;const next=!allowed(role,permission.permission_key);setSaving(`${role}:${permission.permission_key}`);setGrants(current=>[...current.filter(item=>!(item.role===role&&item.permission_key===permission.permission_key)),{role,permission_key:permission.permission_key,allowed:next}]);const {error}=await supabase.from("role_permissions").upsert({role,permission_key:permission.permission_key,allowed:next,updated_at:new Date().toISOString()},{onConflict:"role,permission_key"});setSaving("");setMessage(error?.message??pick("Permission updated.","ההרשאה עודכנה."));if(error)await load();}
 return <main className="hub-page permissions-page"><header className="permissions-hero"><div><div className="hub-eyebrow">G3 6740 · {pick("Access control","בקרת גישה")}</div><h1>{pick("Roles & permissions","תפקידים והרשאות")}</h1><p>{pick("Define what each role can do. Team leaders remain limited to the departments they lead.","הגדירו מה כל תפקיד רשאי לעשות. מובילי צוות מוגבלים למחלקות שאותן הם מובילים.")}</p></div><span>{catalog.length}<small>{pick("capabilities","יכולות")}</small></span></header>{message?<div className="hub-message" role="status">{message}</div>:null}<section className="permission-principles"><article><b>01</b><strong>{pick("Role grants capability","התפקיד מעניק יכולת")}</strong><small>{pick("The matrix controls the permitted action.","המטריצה קובעת את הפעולה המותרת.")}</small></article><article><b>02</b><strong>{pick("Team scope limits access","שיוך הצוות מגביל גישה")}</strong><small>{pick("Leaders act only inside their assigned departments.","מובילים פועלים רק במחלקות שהוקצו להם.")}</small></article><article><b>03</b><strong>{pick("Security stays protected","האבטחה נשארת מוגנת")}</strong><small>{pick("Account and permission controls remain administrator-only.","ניהול חשבונות והרשאות נשאר למנהלים בלבד.")}</small></article></section><section className="permission-matrix-wrap"><table className="permission-matrix"><thead><tr><th>{pick("Capability","יכולת")}</th>{roles.map(role=><th key={role}><strong>{pick(...roleNames[role])}</strong><small>{role.replace("_"," ")}</small></th>)}</tr></thead><tbody>{groups.map(group=><>{<tr className="permission-group" key={`${group}-header`}><th colSpan={5}>{group}</th></tr>}{catalog.filter(item=>item.permission_group===group).map(permission=><tr key={permission.permission_key}><th><strong>{pick(permission.label,permission.label_he)}</strong><small>{permission.description}</small>{permission.protected?<em>{pick("Protected","מוגן")}</em>:null}</th>{roles.map(role=>{const checked=allowed(role,permission.permission_key),locked=role==="admin"||permission.protected;return <td key={role}><button type="button" className={checked?"is-allowed":""} disabled={locked||saving===`${role}:${permission.permission_key}`} onClick={()=>void toggle(role,permission)} aria-pressed={checked} aria-label={`${pick(...roleNames[role])}: ${pick(permission.label,permission.label_he)}`}><span>{checked?"✓":"—"}</span><small>{checked?pick("Allowed","מותר"):pick("Blocked","חסום")}</small></button></td>})}</tr>)}</>)}</tbody></table></section><footer className="permission-footnote">{pick("Changes affect both the website and phone app. Critical administrator permissions cannot be delegated from this screen.","השינויים משפיעים על האתר ועל אפליקציית הטלפון. לא ניתן להאציל הרשאות מנהל קריטיות ממסך זה.")}</footer></main>;
}
