import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import ContextBackBar from "../components/ContextBackBar";
import { useLocalization } from "../lib/localization";
import { useMemberAuth } from "../lib/memberAuth";
import { enqueuePitScoutReport, listQueuedPitScoutReports, removeQueuedPitScoutReport, type QueuedPitScoutReport } from "../lib/offlineDb";
import { supabase } from "../supabase";

type EventRow={id:string;name:string};
type ReportRow={id:string;team_number:number;source_kind:string;status:string;confidence:number;updated_at:string;data:Record<string,unknown>;notes:string|null};
const blank={team_number:"",source_kind:"mixed",drivetrain:"",dimensions:"",weight:"",scoring:"",intake:"",autonomous:"",endgame:"",preferred_role:"",reliability:"",confidence:"3",notes:""};

export default function PitScoutingPage(){
 const {pick}=useLocalization(),{profile}=useMemberAuth(),[params]=useSearchParams();
 const [events,setEvents]=useState<EventRow[]>([]),[eventId,setEventId]=useState(params.get("event_id")||localStorage.getItem("g3_event_id")||""),[reports,setReports]=useState<ReportRow[]>([]),[form,setForm]=useState(blank),[message,setMessage]=useState(""),[queued,setQueued]=useState(0),[saving,setSaving]=useState(false);
 const online=navigator.onLine!==false;
 async function refreshQueue(){setQueued((await listQueuedPitScoutReports()).length);}
 async function flush(){if(!navigator.onLine)return;for(const report of await listQueuedPitScoutReports()){const {error}=await supabase.from("pit_scouting_reports").upsert(report,{onConflict:"entry_uuid"});if(!error)await removeQueuedPitScoutReport(report.entry_uuid);}await refreshQueue();}
 async function load(){const e=await supabase.from("events").select("id,name").eq("active",true).order("start_date",{ascending:false});if(!e.error){setEvents((e.data??[]) as EventRow[]);if(!eventId&&e.data?.[0])setEventId(e.data[0].id);}if(eventId&&navigator.onLine){const r=await supabase.from("pit_scouting_reports").select("id,team_number,source_kind,status,confidence,updated_at,data,notes").eq("event_id",eventId).order("updated_at",{ascending:false});if(!r.error)setReports((r.data??[]) as ReportRow[]);}await refreshQueue();}
 useEffect(()=>{void flush().then(load);const onOnline=()=>void flush().then(load);window.addEventListener("online",onOnline);return()=>window.removeEventListener("online",onOnline);},[eventId]);
 const covered=useMemo(()=>new Set(reports.map(x=>x.team_number)).size,[reports]);
 async function submit(e:FormEvent){e.preventDefault();if(!profile||!eventId)return;setSaving(true);const payload:QueuedPitScoutReport={entry_uuid:crypto.randomUUID(),event_id:eventId,team_number:Number(form.team_number),reporter_id:profile.id,source_kind:form.source_kind,confidence:Number(form.confidence),status:"submitted",data:{drivetrain:form.drivetrain,dimensions:form.dimensions,weight:form.weight,scoring:form.scoring,intake:form.intake,autonomous:form.autonomous,endgame:form.endgame,preferred_role:form.preferred_role,reliability:form.reliability},notes:form.notes||null,device_id:localStorage.getItem("g3_competition_device_id")||"browser",created_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(navigator.onLine){const {error}=await supabase.from("pit_scouting_reports").upsert(payload,{onConflict:"entry_uuid"});if(error){await enqueuePitScoutReport(payload);setMessage(pick("Connection failed; report secured on this device.","החיבור נכשל; הדוח נשמר במכשיר."));}else setMessage(pick("Pit report synchronized.","דוח הפיט סונכרן."));}else{await enqueuePitScoutReport(payload);setMessage(pick("Saved offline. It will synchronize automatically.","נשמר באופליין ויסונכרן אוטומטית."));}setForm(blank);setSaving(false);await load();}
 return <main className="hub-page pit-scout-page"><ContextBackBar fallbackTo="/competition" label={pick("Competition center","מרכז התחרות")}/><header className="pit-scout-hero"><div><div className="hub-eyebrow">G3 FIELD INTELLIGENCE</div><h1>{pick("Pit scouting","סקאוטינג פיט")}</h1><p>{pick("Capture what teams tell us and what G3 verifies—without mixing it with match evidence.","תיעוד דברי הקבוצות והממצאים ש-G3 אימתה—בנפרד מנתוני משחקים.")}</p></div><div><strong>{covered}</strong><span>{pick("teams covered","קבוצות נסקרו")}</span><small>{queued?pick(`${queued} waiting to sync`,`${queued} ממתינים לסנכרון`):pick(online?"Synced":"Offline ready",online?"מסונכרן":"מוכן לאופליין")}</small></div></header>
 <label className="pit-event-picker">{pick("Competition","תחרות")}<select value={eventId} onChange={e=>{setEventId(e.target.value);localStorage.setItem("g3_event_id",e.target.value)}}>{events.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>{message?<div className="hub-message">{message}</div>:null}
 <form className="hub-card pit-scout-form" onSubmit={submit}><section><h2>{pick("Robot identity","זהות הרובוט")}</h2><label>{pick("Team number","מספר קבוצה")}<input inputMode="numeric" required value={form.team_number} onChange={e=>setForm({...form,team_number:e.target.value})}/></label><label>{pick("Evidence source","מקור המידע")}<select value={form.source_kind} onChange={e=>setForm({...form,source_kind:e.target.value})}><option value="team_stated">{pick("Team stated","נמסר על ידי הקבוצה")}</option><option value="g3_observed">{pick("G3 observed","נצפה על ידי G3")}</option><option value="mixed">{pick("Mixed / verified","משולב / מאומת")}</option></select></label><label>{pick("Confidence","רמת ביטחון")}<select value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x}/5</option>)}</select></label></section><section><h2>{pick("Robot profile","פרופיל הרובוט")}</h2>{[["drivetrain",pick("Drivetrain","מערכת הנעה")],["dimensions",pick("Dimensions","מידות")],["weight",pick("Weight","משקל")],["preferred_role",pick("Preferred alliance role","תפקיד מועדף בברית")]] .map(([key,label])=><label key={key}>{label}<input value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</section><section className="wide"><h2>{pick("Capabilities & evidence","יכולות וממצאים")}</h2>{[["scoring",pick("Scoring capability","יכולת ניקוד")],["intake",pick("Intake and game-piece handling","איסוף וטיפול באלמנט")],["autonomous",pick("Autonomous routines","מהלכי אוטונומי")],["endgame",pick("Endgame capability","יכולת סוף משחק")],["reliability",pick("Reliability observations","תצפיות אמינות")],["notes",pick("Strategic notes","הערות אסטרטגיות")]].map(([key,label])=><label key={key}>{label}<textarea rows={2} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</section><button className="hub-button wide" disabled={saving||!eventId}>{saving?pick("Saving…","שומר…"):pick(online?"Save pit report":"Save safely offline",online?"שמירת דוח פיט":"שמירה בטוחה באופליין")}</button></form>
 <section className="pit-report-strip"><header><h2>{pick("Recent coverage","סקירות אחרונות")}</h2><span>{reports.length}</span></header>{reports.slice(0,8).map(r=><article key={r.id}><b>{r.team_number}</b><div><strong>{r.source_kind.replaceAll("_"," ")}</strong><small>{new Date(r.updated_at).toLocaleString()} · {r.confidence}/5</small></div><span>{r.status}</span></article>)}</section></main>;
}
