import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useLocalization } from "../lib/localization";
import { useMemberAuth } from "../lib/memberAuth";
import { getUnreadUpdateCounts } from "../lib/unreadUpdates";
import { supabase } from "../supabase";

type Meeting={id:string;title:string;starts_at:string;ends_at:string;status:string};
type Task={id:string;title:string;status:string;due_at:string|null;project_id:string;team_projects?:{name?:string;subteam?:string|null}|null};
const time=new Intl.DateTimeFormat("en-IL",{timeZone:"Asia/Jerusalem",weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});

export default function ProductivityHomePage({isAdmin}:{isAdmin:boolean}){
  const {pick}=useLocalization(); const {profile}=useMemberAuth(); const navigate=useNavigate();
  const [active,setActive]=useState<Meeting|null>(null); const [next,setNext]=useState<Meeting|null>(null); const [tasks,setTasks]=useState<Task[]>([]); const [presence,setPresence]=useState(0); const [unread,setUnread]=useState(0); const [blockers,setBlockers]=useState(0); const [maintenance,setMaintenance]=useState(0);
  async function load(){if(!profile)return;const now=new Date().toISOString();const [activeResult,nextResult,taskResult,presenceResult,blockerProjects,blockerTasks,maintenanceResult,counts]=await Promise.all([supabase.from("team_meetings").select("id,title,starts_at,ends_at,status").eq("status","open").limit(1),supabase.from("team_meetings").select("id,title,starts_at,ends_at,status").eq("status","scheduled").gt("starts_at",now).order("starts_at").limit(1),supabase.from("project_tasks").select("id,title,status,due_at,project_id,team_projects(name,subteam)").eq("assignee_id",profile.id).eq("archived",false).neq("status","done").order("due_at",{ascending:true,nullsFirst:false}).limit(4),supabase.from("attendance_records").select("id",{count:"exact",head:true}).is("checked_out_at",null),supabase.from("team_projects").select("id",{count:"exact",head:true}).eq("status","blocked"),supabase.from("project_tasks").select("id",{count:"exact",head:true}).eq("status","blocked").eq("archived",false),supabase.from("tool_maintenance").select("id",{count:"exact",head:true}).neq("status","resolved"),getUnreadUpdateCounts(profile.id)]);setActive((activeResult.data?.[0]??null) as Meeting|null);setNext((nextResult.data?.[0]??null) as Meeting|null);setTasks((taskResult.data??[]) as unknown as Task[]);setPresence(presenceResult.count??0);setBlockers((blockerProjects.count??0)+(blockerTasks.count??0));setMaintenance(maintenanceResult.count??0);setUnread(counts.announcements+counts.channels);}
  useEffect(()=>{void load();},[profile?.id]);
  return <main className="hub-page productivity-home"><section className="home-command"><div><div className="hub-eyebrow">Glue Gun &amp; Glitter · FRC 6740</div><h1>{pick(`Ready, ${profile?.display_name?.split(" ")[0]??"G3"}?`,`מוכנים, ${profile?.display_name?.split(" ")[0]??"G3"}?`)}</h1><p>{pick("Your live command center for today’s team work.","מרכז השליטה החי שלכם לעבודת הקבוצה היום.")}</p></div><img src="/logoG3.png" alt="G3 6740"/></section>
  <section className="home-now-panel"><span className={`home-live-indicator${active?" is-live":""}`}/><div><strong>{active?pick(`${active.title} is open`,`${active.title} פתוח`):pick("No workshop session is open","אין מפגש סדנה פתוח")}</strong><small>{active?pick(`${presence} people currently checked in`,`${presence} אנשים נמצאים כרגע`):next?`${pick("Next","הבא")}: ${next.title} · ${time.format(new Date(next.starts_at))}`:pick("No upcoming meeting loaded","לא נטען מפגש קרוב")}</small></div><button className="hub-button" onClick={()=>navigate("/check-in")}>{pick("Check in / out","כניסה / יציאה")}</button></section>
  <section className="home-metrics"><button onClick={()=>navigate("/updates?view=inbox")}><strong>{unread}</strong><span>{pick("Unread updates","עדכונים שלא נקראו")}</span></button><button onClick={()=>navigate("/work")}><strong>{tasks.length}</strong><span>{pick("My open tasks","המשימות שלי")}</span></button><button onClick={()=>navigate("/work")}><strong>{blockers}</strong><span>{pick("Team blockers","חסמי קבוצה")}</span></button><button onClick={()=>navigate("/tools")}><strong>{maintenance}</strong><span>{pick("Tool issues","תקלות כלים")}</span></button></section>
  <div className="home-productivity-grid"><section className="hub-card home-my-work"><header><div><div className="hub-eyebrow">{pick("My work","העבודה שלי")}</div><h2>{pick("Next actions","הפעולות הבאות")}</h2></div><button onClick={()=>navigate("/projects")}>{pick("All work","כל העבודה")} →</button></header>{tasks.length?tasks.map(task=><button className="home-task" key={task.id} onClick={()=>navigate(`/projects?subteam=${task.team_projects?.subteam??""}`)}><span className={`work-task-status status-${task.status}`}/><span><strong>{task.title}</strong><small>{task.team_projects?.name??pick("G3 project","פרויקט G3")}{task.due_at?` · ${new Date(task.due_at).toLocaleDateString()}`:""}</small></span></button>):<p>{pick("You have no open assigned tasks.","אין לכם משימות פתוחות שהוקצו.")}</p>}</section>
  <section className="hub-card home-upcoming"><div className="hub-eyebrow">{pick("Upcoming","בקרוב")}</div><h2>{pick("Team timeline","ציר הזמן הקבוצתי")}</h2>{next?<button onClick={()=>navigate("/schedule")}><strong>{next.title}</strong><small>{time.format(new Date(next.starts_at))}</small></button>:<p>{pick("No upcoming event loaded.","לא נטען אירוע קרוב.")}</p>}<button onClick={()=>navigate("/competition")}><strong>{pick("Competition center","מרכז התחרות")}</strong><small>{pick("Scouting, analysis and readiness","סקאוטינג, ניתוח ומוכנות")}</small></button></section></div>
  <section className="home-quick-actions"><header><div className="hub-eyebrow">{pick("Quick actions","פעולות מהירות")}</div><h2>{pick("Do, don’t navigate","לבצע, לא לנווט")}</h2></header><div><button onClick={()=>navigate("/projects")}>＋ {pick("Create task","יצירת משימה")}</button><button onClick={()=>navigate("/tools")}>⚠ {pick("Report tool issue","דיווח תקלה")}</button><button onClick={()=>navigate("/updates?view=channels")}># {pick("Post team update","פרסום עדכון")}</button>{isAdmin?<button onClick={()=>navigate("/updates?view=announcements")}>! {pick("Publish announcement","פרסום הודעה")}</button>:null}</div></section>
  <section className="home-frc-ops"><header><div><div className="hub-eyebrow">{pick("FRC operations","תפעול FRC")}</div><h2>{pick("Build-season systems","מערכות עונת הבנייה")}</h2></div><span>{pick("Growing with the team","גדל עם הקבוצה")}</span></header><div>{[["readiness",pick("Robot readiness","מוכנות הרובוט")],["purchasing",pick("Parts & purchasing","חלקים ורכש")],["decisions",pick("Decision log","יומן החלטות")],["training",pick("Training matrix","מטריצת הכשרה")],["packing",pick("Pit & packing","פיט ואריזה")],["assignments",pick("Assignments","שיבוצים")]].map(([area,label])=><button key={area} onClick={()=>navigate(`/frc-operations?area=${area}`)}><span>G3</span><strong>{label}</strong></button>)}</div></section>
  </main>;
}
