import { FormEvent, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useLocalization } from "../lib/localization";
import { useMemberAuth } from "../lib/memberAuth";
import { supabase } from "../supabase";

type Component={id:string;name:string;category:string;serial_number:string|null;part_number:string|null;manufacturer:string|null;status:string;service_interval_days:number|null;last_serviced_at:string|null;notes:string|null};
type Event={id:string;component_id:string;event_type:string;robot_location:string|null;notes:string|null;issue_id:string|null;performed_at:string};
type Battery={id:string;asset_tag:string;manufacturer:string|null;purchase_date:string|null;status:string;notes:string|null};
type BatteryTest={id:string;battery_id:string;voltage:number;internal_resistance_mohm:number|null;result:string;notes:string|null;tested_at:string};
type Part={id:string;name:string;part_number:string|null;quantity:number;minimum_quantity:number;unit:string};
const categories=["motor","gearbox","controller","sensor","mechanism","pneumatic","electrical","radio","other"];

export default function RobotMaintenancePage(){
  const {pick}=useLocalization();const {profile}=useMemberAuth();const navigate=useNavigate();
  const [tab,setTab]=useState<"components"|"batteries"|"alerts">("alerts"),[components,setComponents]=useState<Component[]>([]),[events,setEvents]=useState<Event[]>([]),[batteries,setBatteries]=useState<Battery[]>([]),[tests,setTests]=useState<BatteryTest[]>([]),[parts,setParts]=useState<Part[]>([]),[message,setMessage]=useState("");
  const [componentForm,setComponentForm]=useState({name:"",category:"motor",serial:"",part:"",manufacturer:"",interval:"90"}),[batteryForm,setBatteryForm]=useState({tag:"",manufacturer:"",purchase:""}),[selected,setSelected]=useState<string|null>(null),[eventType,setEventType]=useState("inspected"),[eventNote,setEventNote]=useState(""),[location,setLocation]=useState(""),[testBattery,setTestBattery]=useState(""),[voltage,setVoltage]=useState(""),[resistance,setResistance]=useState(""),[testResult,setTestResult]=useState("pass");
  async function load(){const [c,e,b,t,p]=await Promise.all([supabase.from("robot_components").select("*").order("name"),supabase.from("robot_component_events").select("*").order("performed_at",{ascending:false}).limit(300),supabase.from("robot_batteries").select("*").order("asset_tag"),supabase.from("robot_battery_tests").select("*").order("tested_at",{ascending:false}).limit(300),supabase.from("frc_parts_inventory").select("id,name,part_number,quantity,minimum_quantity,unit").eq("archived",false)]);const error=c.error||e.error||b.error||t.error||p.error;if(error)setMessage(error.message);setComponents((c.data??[]) as Component[]);setEvents((e.data??[]) as Event[]);setBatteries((b.data??[]) as Battery[]);setTests((t.data??[]) as BatteryTest[]);setParts((p.data??[]) as Part[]);}
  useEffect(()=>{void load();},[]);
  async function addComponent(event:FormEvent){event.preventDefault();const {error}=await supabase.from("robot_components").insert({name:componentForm.name.trim(),category:componentForm.category,serial_number:componentForm.serial.trim()||null,part_number:componentForm.part.trim()||null,manufacturer:componentForm.manufacturer.trim()||null,service_interval_days:Number(componentForm.interval)||null,created_by:profile?.id});setMessage(error?.message??pick("Component added.","הרכיב נוסף."));if(!error){setComponentForm({name:"",category:"motor",serial:"",part:"",manufacturer:"",interval:"90"});await load();}}
  async function addEvent(event:FormEvent){event.preventDefault();if(!selected||!profile)return;const component=components.find(item=>item.id===selected);let issueId:string|null=null;if(eventType==="failed"&&component){const created=await supabase.from("robot_issues").insert({title:`Component failure: ${component.name}`,description:`${eventNote.trim()||"Component marked failed during maintenance."}${component.serial_number?`\nSerial: ${component.serial_number}`:""}${component.part_number?`\nPart: ${component.part_number}`:""}`,subsystem:component.category==="electrical"||component.category==="controller"||component.category==="sensor"?"electrical":component.category==="radio"?"controls":"mechanical",severity:"high",discovered_context:"workshop",reporter_id:profile.id}).select("id").single();if(created.error){setMessage(created.error.message);return;}issueId=created.data.id;}const {error}=await supabase.from("robot_component_events").insert({component_id:selected,event_type:eventType,robot_location:location.trim()||null,notes:eventNote.trim()||null,issue_id:issueId,performed_by:profile.id});if(!error){const changes:Record<string,unknown>=eventType==="serviced"?{last_serviced_at:new Date().toISOString(),status:"installed"}:eventType==="failed"?{status:"failed"}:eventType==="retired"?{status:"retired"}:eventType==="installed"?{status:"installed"}:eventType==="removed"?{status:"spare"}:{};await supabase.from("robot_components").update({...changes,updated_at:new Date().toISOString()}).eq("id",selected);setEventNote("");setLocation("");await load();}setMessage(error?.message??(issueId?pick("Lifecycle event recorded and linked to a robot issue.","אירוע מחזור החיים נשמר וקושר לתקלה ברובוט."):pick("Lifecycle event recorded.","אירוע מחזור החיים נשמר.")));}
  async function addBattery(event:FormEvent){event.preventDefault();const {error}=await supabase.from("robot_batteries").insert({asset_tag:batteryForm.tag.trim(),manufacturer:batteryForm.manufacturer.trim()||null,purchase_date:batteryForm.purchase||null,created_by:profile?.id});setMessage(error?.message??pick("Battery registered.","הסוללה נרשמה."));if(!error){setBatteryForm({tag:"",manufacturer:"",purchase:""});await load();}}
  async function addBatteryTest(event:FormEvent){event.preventDefault();if(!testBattery)return;const {error}=await supabase.from("robot_battery_tests").insert({battery_id:testBattery,voltage:Number(voltage),internal_resistance_mohm:resistance?Number(resistance):null,result:testResult,tested_by:profile?.id});if(!error){await supabase.from("robot_batteries").update({status:testResult==="fail"?"quarantined":testResult==="monitor"?"service_due":"available",updated_at:new Date().toISOString()}).eq("id",testBattery);setVoltage("");setResistance("");await load();}setMessage(error?.message??pick("Battery test recorded.","בדיקת הסוללה נשמרה."));}
  async function requestSpare(){const component=components.find(item=>item.id===selected);if(!component||!profile)return;const part=parts.find(item=>component.part_number&&item.part_number?.toLowerCase()===component.part_number.toLowerCase());const quantity=Math.max(1,part?Number(part.minimum_quantity)-Number(part.quantity):1);const {error}=await supabase.from("frc_purchase_requests").insert({part_id:part?.id??null,item_name:component.name,quantity,urgency:component.status==="failed"?"critical":"high",reason:`Robot maintenance: ${component.status}${component.part_number?` · Part ${component.part_number}`:""}`,requested_by:profile.id});setMessage(error?.message??pick("Purchase request created.","בקשת הרכש נוצרה."));}
  const intelligence=useMemo(()=>{const now=Date.now();const due=components.filter(item=>item.status==="service_due"||(item.status==="installed"&&item.service_interval_days&&item.last_serviced_at&&now-new Date(item.last_serviced_at).getTime()>item.service_interval_days*86400000));const failed=components.filter(item=>item.status==="failed");const batteryAlerts=batteries.filter(item=>["service_due","quarantined"].includes(item.status));return{due,failed,batteryAlerts};},[components,batteries]);
  const lastEvent=(id:string)=>events.find(item=>item.component_id===id),lastTest=(id:string)=>tests.find(item=>item.battery_id===id);
  const selectedComponent=components.find(item=>item.id===selected)??null,matchingPart=selectedComponent?.part_number?parts.find(item=>item.part_number?.toLowerCase()===selectedComponent.part_number?.toLowerCase())??null:null;
  return <main className="hub-page maintenance-page">
  <header className="maintenance-hero"><div><button onClick={()=>navigate("/robot-reliability")}>← {pick("Reliability center","מרכז אמינות")}</button><div className="hub-eyebrow">G3 6740 · {pick("Asset lifecycle","מחזור חיי ציוד")}</div><h1>{pick("Robot maintenance","תחזוקת הרובוט")}</h1><p>{pick("Know what is installed, what was serviced, which batteries are healthy and what needs attention before field failure.","דעו מה מותקן, מה טופל, אילו סוללות תקינות ומה דורש טיפול לפני כשל במגרש.")}</p></div></header>
  <section className={`maintenance-operating-state${intelligence.failed.length||intelligence.batteryAlerts.some(item=>item.status==="quarantined")?" is-stop":intelligence.due.length||intelligence.batteryAlerts.length?" is-review":" is-clear"}`}><span aria-hidden="true">{intelligence.failed.length||intelligence.batteryAlerts.some(item=>item.status==="quarantined")?"!":intelligence.due.length||intelligence.batteryAlerts.length?"△":"✓"}</span><div><strong>{intelligence.failed.length||intelligence.batteryAlerts.some(item=>item.status==="quarantined")?pick("Do not treat the robot as cleared","אין להתייחס לרובוט כמאושר"):intelligence.due.length||intelligence.batteryAlerts.length?pick("Engineering review required","נדרשת בדיקה הנדסית"):pick("No recorded maintenance blockers","אין חסמי תחזוקה מתועדים")}</strong><small>{pick("This is a record-based indicator. The drive team and responsible mentors must still perform the readiness checklist.","זהו מדד המבוסס על רשומות. צוות הנהיגה והמנטורים האחראים עדיין חייבים לבצע את רשימת המוכנות.")}</small></div></section>
  <nav className="maintenance-tabs">{(["alerts","components","batteries"] as const).map(item=><button className={tab===item?"is-active":""} onClick={()=>setTab(item)} key={item}>{item==="alerts"?pick("Service alerts","התראות שירות"):item==="components"?pick("Components","רכיבים"):pick("Batteries","סוללות")}</button>)}</nav>{message?<div className="hub-message">{message}</div>:null}
  {selectedComponent?<aside className="maintenance-spare-panel"><div><span>{pick("Selected component","רכיב נבחר")}</span><strong>{selectedComponent.name}</strong><small>{matchingPart?pick(`${matchingPart.quantity} ${matchingPart.unit} in inventory · minimum ${matchingPart.minimum_quantity}`,`${matchingPart.quantity} ${matchingPart.unit} במלאי · מינימום ${matchingPart.minimum_quantity}`):selectedComponent.part_number?pick("Part number is not matched in inventory","מספר החלק אינו תואם לפריט במלאי"):pick("Add a part number to match inventory","הוסיפו מספר חלק כדי להתאים למלאי")}</small></div><button onClick={()=>void requestSpare()}>{pick("Request spare","בקשת חלק חלופי")}</button></aside>:null}
  {tab==="alerts"?<section className="maintenance-alert-board"><article><strong>{intelligence.due.length}</strong><span>{pick("Service due","נדרש שירות")}</span></article><article className="danger"><strong>{intelligence.failed.length}</strong><span>{pick("Failed components","רכיבים תקולים")}</span></article><article className="warning"><strong>{intelligence.batteryAlerts.length}</strong><span>{pick("Battery alerts","התראות סוללה")}</span></article><div className="hub-card maintenance-alert-list">{[...intelligence.failed,...intelligence.due].map(item=><button onClick={()=>{setSelected(item.id);setTab("components");}} key={item.id}><span>{item.status}</span><strong>{item.name}</strong><small>{item.category} · {item.serial_number??pick("No serial number","ללא מספר סידורי")}</small><b>→</b></button>)}{intelligence.batteryAlerts.map(item=><button onClick={()=>{setTestBattery(item.id);setTab("batteries");}} key={item.id}><span>{item.status}</span><strong>{item.asset_tag}</strong><small>{pick("Battery requires review","הסוללה דורשת בדיקה")}</small><b>→</b></button>)}{!intelligence.due.length&&!intelligence.failed.length&&!intelligence.batteryAlerts.length?<p>{pick("No maintenance alerts. Keep recording inspections and tests.","אין התראות תחזוקה. המשיכו לתעד בדיקות ושירות.")}</p>:null}</div></section>:null}
  {tab==="components"?<section className="maintenance-grid"><form className="hub-card maintenance-form" onSubmit={addComponent}><h2>{pick("Register component","רישום רכיב")}</h2><input required placeholder={pick("Component name","שם הרכיב")} value={componentForm.name} onChange={e=>setComponentForm({...componentForm,name:e.target.value})}/><select value={componentForm.category} onChange={e=>setComponentForm({...componentForm,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select><input placeholder={pick("Serial number","מספר סידורי")} value={componentForm.serial} onChange={e=>setComponentForm({...componentForm,serial:e.target.value})}/><input placeholder={pick("Part number","מספר חלק")} value={componentForm.part} onChange={e=>setComponentForm({...componentForm,part:e.target.value})}/><input placeholder={pick("Manufacturer","יצרן")} value={componentForm.manufacturer} onChange={e=>setComponentForm({...componentForm,manufacturer:e.target.value})}/><label>{pick("Service interval (days)","מרווח שירות (ימים)")}<input type="number" min="1" value={componentForm.interval} onChange={e=>setComponentForm({...componentForm,interval:e.target.value})}/></label><button className="hub-button">{pick("Add component","הוספת רכיב")}</button></form><div className="maintenance-assets">{components.map(item=><button className={selected===item.id?"is-active":""} onClick={()=>setSelected(item.id)} key={item.id}><span className={`status-${item.status}`}>{item.status}</span><strong>{item.name}</strong><small>{item.category} · {item.serial_number??item.part_number??"—"}</small><i>{lastEvent(item.id)?new Date(lastEvent(item.id)!.performed_at).toLocaleDateString():pick("No history","אין היסטוריה")}</i></button>)}</div>{selected?<form className="hub-card maintenance-event-form" onSubmit={addEvent}><h2>{pick("Record lifecycle event","תיעוד אירוע מחזור חיים")}</h2><select value={eventType} onChange={e=>setEventType(e.target.value)}>{["installed","removed","inspected","serviced","repaired","failed","retired"].map(x=><option key={x}>{x}</option>)}</select><input value={location} onChange={e=>setLocation(e.target.value)} placeholder={pick("Robot location / mechanism","מיקום ברובוט / מנגנון")}/><textarea value={eventNote} onChange={e=>setEventNote(e.target.value)} placeholder={pick("Work performed, findings or measurements","עבודה שבוצעה, ממצאים או מדידות")}/><button className="hub-button">{pick("Record event","שמירת אירוע")}</button></form>:null}</section>:null}
  {tab==="batteries"?<section className="maintenance-grid"><form className="hub-card maintenance-form" onSubmit={addBattery}><h2>{pick("Register battery","רישום סוללה")}</h2><input required value={batteryForm.tag} onChange={e=>setBatteryForm({...batteryForm,tag:e.target.value})} placeholder={pick("Asset tag, e.g. G3-B12","תג נכס, לדוגמה G3-B12")}/><input value={batteryForm.manufacturer} onChange={e=>setBatteryForm({...batteryForm,manufacturer:e.target.value})} placeholder={pick("Manufacturer","יצרן")}/><label>{pick("Purchase date","תאריך רכישה")}<input type="date" value={batteryForm.purchase} onChange={e=>setBatteryForm({...batteryForm,purchase:e.target.value})}/></label><button className="hub-button">{pick("Register battery","רישום סוללה")}</button></form><div className="maintenance-assets">{batteries.map(item=>{const test=lastTest(item.id);return <button className={testBattery===item.id?"is-active":""} onClick={()=>setTestBattery(item.id)} key={item.id}><span className={`status-${item.status}`}>{item.status}</span><strong>{item.asset_tag}</strong><small>{test?`${test.voltage}V · ${test.internal_resistance_mohm??"—"}mΩ · ${test.result}`:pick("Never tested","לא נבדקה")}</small><i>{test?new Date(test.tested_at).toLocaleDateString():"—"}</i></button>})}</div>{testBattery?<form className="hub-card maintenance-event-form" onSubmit={addBatteryTest}><h2>{pick("Record battery test","תיעוד בדיקת סוללה")}</h2><input required type="number" min="0" max="20" step="0.01" value={voltage} onChange={e=>setVoltage(e.target.value)} placeholder="Voltage"/><input type="number" min="0" step="0.01" value={resistance} onChange={e=>setResistance(e.target.value)} placeholder="Internal resistance mΩ"/><select value={testResult} onChange={e=>setTestResult(e.target.value)}><option value="pass">pass</option><option value="monitor">monitor</option><option value="fail">fail</option></select><button className="hub-button">{pick("Save battery test","שמירת בדיקה")}</button></form>:null}</section>:null}</main>;
}
