import { FormEvent, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useLocalization } from "../lib/localization";
import { useMemberAuth } from "../lib/memberAuth";
import { supabase } from "../supabase";

type Plan={id:string;title:string;subsystem:string;purpose:string;procedure:string;success_criteria:string;safety_notes:string|null;owner_id:string|null;active:boolean};
type Run={id:string;plan_id:string;performed_by:string;result:"pass"|"fail"|"blocked";notes:string|null;measurements:string|null;issue_id:string|null;performed_at:string};
type Check={id:string;label:string;category:string;required:boolean;sort_order:number};
type Session={id:string;title:string;context:string;status:string;created_at:string};
type Result={session_id:string;check_id:string;status:"pending"|"pass"|"fail"|"na";note:string|null};
const subsystems=["drivetrain","mechanical","electrical","software","controls","vision","pneumatics","battery","bumpers","inspection","other"];

export default function RobotReliabilityPage(){
  const {pick}=useLocalization(); const {profile}=useMemberAuth(); const navigate=useNavigate();
  const [plans,setPlans]=useState<Plan[]>([]); const [runs,setRuns]=useState<Run[]>([]); const [checks,setChecks]=useState<Check[]>([]); const [sessions,setSessions]=useState<Session[]>([]); const [results,setResults]=useState<Result[]>([]);
  const [tab,setTab]=useState<"readiness"|"tests"|"history">("readiness"); const [message,setMessage]=useState(""); const [showPlan,setShowPlan]=useState(false); const [selectedPlan,setSelectedPlan]=useState<Plan|null>(null);
  const [planForm,setPlanForm]=useState({title:"",subsystem:"mechanical",purpose:"",procedure:"",success:"",safety:""});
  const [runResult,setRunResult]=useState<"pass"|"fail"|"blocked">("pass"); const [runNotes,setRunNotes]=useState(""); const [measurements,setMeasurements]=useState("");
  const activeSession=sessions.find(item=>item.status==="open")??null;

  async function load(){const [p,r,c,s]=await Promise.all([
    supabase.from("robot_test_plans").select("*").eq("active",true).order("updated_at",{ascending:false}),
    supabase.from("robot_test_runs").select("*").order("performed_at",{ascending:false}).limit(100),
    supabase.from("robot_readiness_checks").select("*").eq("active",true).order("sort_order"),
    supabase.from("robot_readiness_sessions").select("*").order("created_at",{ascending:false}).limit(20)
  ]); setPlans((p.data??[]) as Plan[]);setRuns((r.data??[]) as Run[]);setChecks((c.data??[]) as Check[]);setSessions((s.data??[]) as Session[]);const open=(s.data??[]).find(item=>item.status==="open");if(open){const rr=await supabase.from("robot_readiness_results").select("*").eq("session_id",open.id);setResults((rr.data??[]) as Result[]);}else setResults([]);}
  useEffect(()=>{void load();},[]);

  async function createPlan(event:FormEvent){event.preventDefault();if(!profile)return;const {error}=await supabase.from("robot_test_plans").insert({title:planForm.title.trim(),subsystem:planForm.subsystem,purpose:planForm.purpose.trim(),procedure:planForm.procedure.trim(),success_criteria:planForm.success.trim(),safety_notes:planForm.safety.trim()||null,owner_id:profile.id,created_by:profile.id});setMessage(error?.message??pick("Test plan created.","תוכנית הבדיקה נוצרה."));if(!error){setPlanForm({title:"",subsystem:"mechanical",purpose:"",procedure:"",success:"",safety:""});setShowPlan(false);await load();}}
  async function startReadiness(){if(!profile)return;const created=await supabase.from("robot_readiness_sessions").insert({title:pick("Robot readiness check","בדיקת מוכנות הרובוט"),context:"workshop",opened_by:profile.id}).select("id").single();if(created.error||!created.data){setMessage(created.error?.message??pick("Could not start readiness check.","לא ניתן להתחיל בדיקת מוכנות."));return;}if(checks.length){await supabase.from("robot_readiness_results").insert(checks.map(check=>({session_id:created.data.id,check_id:check.id,status:"pending"})));}await load();}
  async function setCheck(check:Check,status:Result["status"]){if(!activeSession||!profile)return;const {error}=await supabase.from("robot_readiness_results").upsert({session_id:activeSession.id,check_id:check.id,status,checked_by:profile.id,checked_at:new Date().toISOString()},{onConflict:"session_id,check_id"});if(error)setMessage(error.message);else await load();}
  async function completeReadiness(){if(!activeSession)return;const required=checks.filter(item=>item.required);const incomplete=required.some(item=>!results.find(row=>row.check_id===item.id)||results.find(row=>row.check_id===item.id)?.status==="pending");if(incomplete){setMessage(pick("Complete every required check before closing readiness.","יש להשלים כל בדיקה נדרשת לפני סגירת המוכנות."));return;}await supabase.from("robot_readiness_sessions").update({status:"completed",completed_at:new Date().toISOString()}).eq("id",activeSession.id);await load();}
  async function recordRun(event:FormEvent){event.preventDefault();if(!selectedPlan||!profile)return;const {data,error}=await supabase.from("robot_test_runs").insert({plan_id:selectedPlan.id,performed_by:profile.id,result:runResult,notes:runNotes.trim()||null,measurements:measurements.trim()||null}).select("id").single();if(error){setMessage(error.message);return;}setMessage(pick("Test result recorded.","תוצאת הבדיקה נשמרה."));setRunNotes("");setMeasurements("");if(runResult==="fail"&&data&&confirm(pick("This test failed. Create a Robot Issue now?","הבדיקה נכשלה. ליצור תקלה ברובוט כעת?"))){sessionStorage.setItem("g3-reliability-issue-draft",JSON.stringify({title:`Failed test: ${selectedPlan.title}`,description:`Test purpose: ${selectedPlan.purpose}\n\nResult: ${runNotes||"Failed success criteria"}\nMeasurements: ${measurements||"Not recorded"}`,subsystem:selectedPlan.subsystem,testRunId:data.id}));navigate("/robot-issues?new=1");return;}await load();}

  const checkStatus=(id:string)=>results.find(row=>row.check_id===id)?.status??"pending";
  const required=checks.filter(item=>item.required); const passed=required.filter(item=>checkStatus(item.id)==="pass").length; const failed=required.filter(item=>checkStatus(item.id)==="fail").length;
  const readinessScore=required.length?Math.round(passed/required.length*100):0;
  const lastRuns=useMemo(()=>plans.map(plan=>({plan,run:runs.find(row=>row.plan_id===plan.id)})),[plans,runs]);
  const reliability=runs.length?Math.round(runs.filter(run=>run.result==="pass").length/runs.length*100):null;

  return <main className="hub-page reliability-page">
    <header className="reliability-hero"><div><div className="hub-eyebrow">FRC 6740 · {pick("Engineering confidence","ביטחון הנדסי")}</div><h1>{pick("Reliability center","מרכז אמינות")}</h1><p>{pick("Prove the robot is ready with repeatable tests, visible evidence and a shared pre-flight check.","מוכיחים שהרובוט מוכן באמצעות בדיקות חוזרות, ראיות גלויות ובדיקת מוכנות משותפת.")}</p></div><div className="reliability-score"><strong>{activeSession?`${readinessScore}%`:reliability===null?"—":`${reliability}%`}</strong><span>{activeSession?pick("Current readiness","מוכנות נוכחית"):pick("Test pass rate","שיעור הצלחה")}</span></div></header>
    <nav className="reliability-tabs" aria-label={pick("Reliability sections","אזורי אמינות")}>{(["readiness","tests","history"] as const).map(item=><button className={tab===item?"is-active":""} onClick={()=>setTab(item)} key={item}>{item==="readiness"?pick("Readiness","מוכנות"):item==="tests"?pick("Test plans","תוכניות בדיקה"):pick("Test history","היסטוריית בדיקות")}</button>)}</nav>
    {message?<div className="hub-message" role="status">{message}</div>:null}
    {tab==="readiness"?<section className="reliability-panel">{!activeSession?<div className="readiness-start hub-card"><span>READY</span><h2>{pick("Start a robot pre-flight","התחלת בדיקת מוכנות")}</h2><p>{pick("Open one shared checklist for the team. Every required item must be verified before the robot is declared ready.","פתיחת רשימה משותפת לצוות. יש לאמת כל פריט נדרש לפני הכרזה שהרובוט מוכן.")}</p><button className="hub-button" onClick={()=>void startReadiness()}>{pick("Start readiness check","התחלת בדיקת מוכנות")}</button></div>:<><div className="readiness-command"><div><div className="hub-eyebrow">{activeSession.title}</div><h2>{failed?pick(`${failed} blocker(s) found`,`${failed} חסמים נמצאו`):pick("Pre-flight in progress","בדיקת מוכנות בתהליך")}</h2></div><div className="readiness-meter"><i style={{width:`${readinessScore}%`}}/><span>{passed}/{required.length} {pick("required passed","נדרשות עברו")}</span></div></div><div className="readiness-checklist">{checks.map(check=>{const status=checkStatus(check.id);return <article className={`readiness-check status-${status}`} key={check.id}><div><small>{check.category.toUpperCase()}{check.required?` · ${pick("REQUIRED","נדרש")}`:""}</small><strong>{check.label}</strong></div><div className="check-actions"><button aria-label={pick("Pass","עבר")} className={status==="pass"?"selected":""} onClick={()=>void setCheck(check,"pass")}>✓</button><button aria-label={pick("Fail","נכשל")} className={status==="fail"?"selected":""} onClick={()=>void setCheck(check,"fail")}>!</button>{!check.required?<button aria-label={pick("Not applicable","לא רלוונטי")} className={status==="na"?"selected":""} onClick={()=>void setCheck(check,"na")}>N/A</button>:null}</div></article>})}</div><button className="hub-button readiness-complete" onClick={()=>void completeReadiness()}>{pick("Complete and lock result","השלמה ונעילת התוצאה")}</button></>}</section>:null}
    {tab==="tests"?<section className="reliability-panel"><header className="reliability-section-head"><div><div className="hub-eyebrow">{pick("Repeatable engineering","הנדסה חוזרת")}</div><h2>{pick("Test library","ספריית בדיקות")}</h2></div><button className="hub-button" onClick={()=>setShowPlan(v=>!v)}>+ {pick("New test plan","תוכנית חדשה")}</button></header>{showPlan?<form className="hub-card test-plan-form" onSubmit={createPlan}><label>{pick("Test name","שם הבדיקה")}<input required minLength={3} value={planForm.title} onChange={e=>setPlanForm({...planForm,title:e.target.value})}/></label><label>{pick("Subsystem","מערכת")}<select value={planForm.subsystem} onChange={e=>setPlanForm({...planForm,subsystem:e.target.value})}>{subsystems.map(item=><option key={item}>{item}</option>)}</select></label><label>{pick("Purpose","מטרה")}<textarea required rows={2} value={planForm.purpose} onChange={e=>setPlanForm({...planForm,purpose:e.target.value})}/></label><label>{pick("Procedure — one step per line","נוהל — שלב בכל שורה")}<textarea required rows={5} value={planForm.procedure} onChange={e=>setPlanForm({...planForm,procedure:e.target.value})}/></label><label>{pick("Measurable success criteria","קריטריוני הצלחה מדידים")}<textarea required rows={3} value={planForm.success} onChange={e=>setPlanForm({...planForm,success:e.target.value})}/></label><label>{pick("Safety notes","הערות בטיחות")}<textarea rows={2} value={planForm.safety} onChange={e=>setPlanForm({...planForm,safety:e.target.value})}/></label><button className="hub-button">{pick("Save test plan","שמירת תוכנית")}</button></form>:null}<div className="test-plan-grid">{lastRuns.map(({plan,run})=><button className="test-plan-card hub-card" key={plan.id} onClick={()=>setSelectedPlan(plan)}><header><span>{plan.subsystem}</span><b className={run?`result-${run.result}`:""}>{run?run.result:pick("Not run","טרם בוצעה")}</b></header><h3>{plan.title}</h3><p>{plan.purpose}</p><footer>{run?<time>{new Date(run.performed_at).toLocaleDateString()}</time>:<span>{pick("Ready for first run","מוכנה להרצה ראשונה")}</span>}<strong>{pick("Run test","הרצת בדיקה")} →</strong></footer></button>)}</div>{plans.length===0&&!showPlan?<div className="issue-empty"><span>TEST</span><h2>{pick("No test plans yet","אין עדיין תוכניות בדיקה")}</h2><p>{pick("Create the first repeatable test for a critical robot subsystem.","צרו בדיקה חוזרת ראשונה למערכת רובוט קריטית.")}</p></div>:null}</section>:null}
    {tab==="history"?<section className="reliability-panel"><header className="reliability-section-head"><div><div className="hub-eyebrow">{pick("Evidence trail","נתיב ראיות")}</div><h2>{pick("Recorded test runs","הרצות בדיקה מתועדות")}</h2></div></header><div className="test-history">{runs.map(run=>{const plan=plans.find(item=>item.id===run.plan_id);return <article className={`hub-card result-${run.result}`} key={run.id}><span>{run.result.toUpperCase()}</span><div><h3>{plan?.title??pick("Archived test plan","תוכנית בדיקה בארכיון")}</h3><p>{run.notes||pick("No run notes.","אין הערות להרצה.")}</p><small>{new Date(run.performed_at).toLocaleString()}{run.measurements?` · ${run.measurements}`:""}</small></div>{run.issue_id?<button onClick={()=>navigate(`/robot-issues?issue=${run.issue_id}`)}>{pick("Open issue","פתיחת תקלה")} →</button>:null}</article>})}{runs.length===0?<div className="issue-empty"><h2>{pick("No test evidence yet","אין עדיין ראיות בדיקה")}</h2></div>:null}</div></section>:null}
    {selectedPlan?<div className="issue-detail-backdrop" onClick={()=>setSelectedPlan(null)}><aside className="issue-detail test-run-sheet" onClick={e=>e.stopPropagation()}><header><div><div className="hub-eyebrow">{selectedPlan.subsystem}</div><h2>{selectedPlan.title}</h2></div><button onClick={()=>setSelectedPlan(null)}>×</button></header><section><h3>{pick("Purpose","מטרה")}</h3><p>{selectedPlan.purpose}</p></section>{selectedPlan.safety_notes?<div className="test-safety"><strong>{pick("Safety first","בטיחות תחילה")}</strong><p>{selectedPlan.safety_notes}</p></div>:null}<section><h3>{pick("Procedure","נוהל")}</h3><ol>{selectedPlan.procedure.split("\n").filter(Boolean).map((step,index)=><li key={index}>{step.replace(/^\s*\d+[.)-]?\s*/,"")}</li>)}</ol></section><section className="test-success"><h3>{pick("Success criteria","קריטריוני הצלחה")}</h3><p>{selectedPlan.success_criteria}</p></section><form className="test-run-form" onSubmit={recordRun}><h3>{pick("Record this run","תיעוד הרצה זו")}</h3><div className="run-result-picker">{(["pass","fail","blocked"] as const).map(item=><button type="button" className={runResult===item?`selected result-${item}`:""} onClick={()=>setRunResult(item)} key={item}>{item}</button>)}</div><label>{pick("Observations","תצפיות")}<textarea rows={3} value={runNotes} onChange={e=>setRunNotes(e.target.value)} placeholder={pick("What happened during the test?","מה קרה במהלך הבדיקה?")}/></label><label>{pick("Measurements","מדידות")}<input value={measurements} onChange={e=>setMeasurements(e.target.value)} placeholder={pick("Example: 3.2 s, 42 A, ±1 cm","לדוגמה: 3.2 שנ׳, 42A, ±1 ס״מ")}/></label><button className="hub-button">{pick("Save test result","שמירת תוצאה")}</button></form></aside></div>:null}
  </main>;
}
