import { useEffect, useMemo, useState } from "react";
import ContextBackBar from "../components/ContextBackBar";
import { useLocalization } from "../lib/localization";
import { useMemberAuth } from "../lib/memberAuth";
import { supabase } from "../supabase";
type Entry={id:string;event_id:string;match_id:string;team_number:number;scout_user_id:string|null;created_at:string;data:Record<string,unknown>;notes:string|null;is_duplicate:boolean|null};
type Match={id:string;match_type:string|null;match_number:number|null};
const label=(m?:Match)=>m?`${m.match_type?.toUpperCase()==="QUAL"?"QM":m.match_type?.toUpperCase()||"M"}${m.match_number??"?"}`:"Match";
export default function ScoutingQualityPage(){const {pick}=useLocalization(),{profile}=useMemberAuth(),[entries,setEntries]=useState<Entry[]>([]),[matches,setMatches]=useState<Match[]>([]),[names,setNames]=useState<Record<string,string>>({}),[eventId]=useState(localStorage.getItem("g3_event_id")||""),[message,setMessage]=useState("");const canReview=profile?.role==="admin"||profile?.role==="mentor"||profile?.role==="team_leader";
 async function load(){if(!eventId)return;const [e,m,p]=await Promise.all([supabase.from("scout_entries").select("id,event_id,match_id,team_number,scout_user_id,created_at,data,notes,is_duplicate").eq("event_id",eventId).order("created_at"),supabase.from("matches").select("id,match_type,match_number").eq("event_id",eventId),supabase.from("team_members").select("id,display_name")]);if(e.error)setMessage(e.error.message);else setEntries((e.data??[]) as Entry[]);setMatches((m.data??[]) as Match[]);setNames(Object.fromEntries((p.data??[]).map(x=>[x.id,x.display_name])));}useEffect(()=>{void load()},[eventId]);
 const groups=useMemo(()=>{const map=new Map<string,Entry[]>();for(const row of entries){const key=`${row.match_id}:${row.team_number}`;map.set(key,[...(map.get(key)||[]),row]);}return [...map.values()].filter(rows=>rows.filter(row=>!row.is_duplicate).length>1);},[entries]);
 async function resolve(rows:Entry[],acceptedId:string){const reason=window.prompt(pick("Briefly explain why this report is authoritative.","נא להסביר בקצרה מדוע הדוח הזה מוסמך."));if(!reason?.trim())return;const {error}=await supabase.rpc("resolve_scouting_conflict",{target_event:rows[0].event_id,target_match:rows[0].match_id,target_team:rows[0].team_number,accepted_entry:acceptedId,resolution_reason:reason.trim()});setMessage(error?.message??pick("Conflict resolved; original reports remain in the audit trail.","הסתירה נפתרה; הדוחות המקוריים נשמרו ביומן הביקורת."));if(!error)await load();}
 return <main className="hub-page scouting-quality-page"><ContextBackBar fallbackTo="/competition" label={pick("Competition center","מרכז התחרות")}/><header className="quality-hero"><div className="hub-eyebrow">SCOUTING QUALITY CONTROL</div><h1>{pick("Conflict review","בדיקת סתירות")}</h1><p>{pick("Compare duplicate reports, choose the trusted evidence, and preserve every original submission.","השוואת דוחות כפולים, בחירת המידע המהימן ושמירת כל הדיווחים המקוריים.")}</p><strong>{groups.length} {pick("conflicts open","סתירות פתוחות")}</strong></header>{message?<div className="hub-message">{message}</div>:null}{!canReview?<div className="hub-card quality-empty"><h2>{pick("Review access is restricted","הגישה לבדיקה מוגבלת")}</h2><p>{pick("Team leaders, mentors and admins can resolve scouting evidence.","ראשי צוותים, מנטורים ומנהלים יכולים לפתור סתירות בסקאוטינג.")}</p></div>:groups.length===0?<div className="hub-card quality-empty"><h2>{pick("No conflicts to review","אין סתירות לבדיקה")}</h2><p>{pick("Reports with multiple submissions for one robot and match will appear here.","דיווחים כפולים לאותו רובוט ומשחק יופיעו כאן.")}</p></div>:groups.map(rows=>{const match=matches.find(m=>m.id===rows[0].match_id);const keys=[...new Set(rows.flatMap(r=>Object.keys(r.data||{})))];return <section className="hub-card quality-case" key={`${rows[0].match_id}-${rows[0].team_number}`}><header><div><span>{label(match)}</span><h2>{pick("Team","קבוצה")} {rows[0].team_number}</h2></div><b>{rows.length} {pick("reports","דוחות")}</b></header><div className="quality-table"><div className="quality-row heading"><strong>{pick("Signal","מדד")}</strong>{rows.map((r,i)=><strong key={r.id}>{names[r.scout_user_id||""]||`${pick("Scout","סקאוטר")} ${i+1}`}</strong>)}</div>{keys.map(key=><div className="quality-row" key={key}><span>{key.replaceAll("_"," ")}</span>{rows.map(r=><span key={r.id}>{String(r.data?.[key]??"—")}</span>)}</div>)}<div className="quality-row"><span>{pick("Notes","הערות")}</span>{rows.map(r=><span key={r.id}>{r.notes||"—"}</span>)}</div></div><footer>{rows.map(r=><button className={r.is_duplicate?"":"is-current"} key={r.id} onClick={()=>void resolve(rows,r.id)}>{pick("Trust","בחר בדוח של")} {names[r.scout_user_id||""]||new Date(r.created_at).toLocaleTimeString()}</button>)}</footer></section>})}</main>}
