import { useEffect, useState } from "react";
import { supabase } from "../supabase";
import { useLocalization } from "../lib/localization";

type AuditRow={id:number;actor_id:string|null;action:string;entity_type:string;entity_id:string|null;created_at:string};
type AutomationRow={run_key:string;kind:string;created_at:string};

export default function SecurityAdminPage(){
  const {pick}=useLocalization(); const [audit,setAudit]=useState<AuditRow[]>([]); const [runs,setRuns]=useState<AutomationRow[]>([]); const [summary,setSummary]=useState<Record<string,number>>({});
  async function load(){const [{data:a},{data:r},{data:s}]=await Promise.all([supabase.from("audit_log").select("id,actor_id,action,entity_type,entity_id,created_at").order("created_at",{ascending:false}).limit(100),supabase.from("automation_runs").select("run_key,kind,created_at").order("created_at",{ascending:false}).limit(50),supabase.from("team_operations_summary").select("*").single()]);setAudit((a??[]) as AuditRow[]);setRuns((r??[]) as AutomationRow[]);setSummary((s??{}) as Record<string,number>);}
  useEffect(()=>{void load();},[]);
  async function exportBackup(){const tables=["team_members","team_meetings","attendance_records","announcements","team_projects","project_tasks","workshop_tools","tool_checkouts","tool_maintenance","automation_runs"];const entries=await Promise.all(tables.map(async table=>{const {data,error}=await supabase.from(table).select("*");return [table,error?{error:error.message}:data] as const;}));const payload={exported_at:new Date().toISOString(),schema_version:1,data:Object.fromEntries(entries)};const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));link.download=`g3-team-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href);}
  return <div className="hub-page"><header className="hub-page-header"><div><div className="hub-eyebrow">{pick("Security & operations","אבטחה ותפעול")}</div><h1>{pick("System oversight","בקרת מערכת")}</h1><p>{pick("Audit activity, automation health and operational totals.","פעילות ביקורת, תקינות אוטומציות ונתונים תפעוליים.")}</p></div><div className="report-actions"><button onClick={exportBackup}>{pick("Export backup","ייצוא גיבוי")}</button><button className="hub-button" onClick={load}>{pick("Refresh","רענון")}</button></div></header><div className="admin-stat-grid">{Object.entries(summary).map(([key,value])=><article key={key}><strong>{value}</strong><span>{key.replace(/_/g," ")}</span></article>)}</div><section className="hub-card report-table"><h2>{pick("Recent audit activity","פעילות ביקורת אחרונה")}</h2><div className="report-row report-heading"><span>{pick("Entity","ישות")}</span><span>{pick("Action","פעולה")}</span><span>{pick("Time","זמן")}</span></div>{audit.map(row=><div className="report-row" key={row.id}><span><strong>{row.entity_type}</strong><small>{row.entity_id}</small></span><span>{row.action}</span><span>{new Date(row.created_at).toLocaleString()}</span></div>)}</section><section className="hub-card report-table"><h2>{pick("Automation history","היסטוריית אוטומציות")}</h2>{runs.length===0?<p>{pick("No reminders or reports have been due yet.","עדיין לא הגיע מועד לתזכורת או דוח.")}</p>:runs.map(row=><div className="report-row" key={row.run_key}><span>{row.kind}</span><span>{row.run_key}</span><span>{new Date(row.created_at).toLocaleString()}</span></div>)}</section></div>;
}
