import{FormEvent,useEffect,useMemo,useState}from"react";
import{useLocalization}from"../lib/localization";
import{useMemberAuth}from"../lib/memberAuth";
import{MAX_MEDIA_BYTES,prepareImage,safeStorageName,signedFileUrl}from"../lib/mediaFiles";
import{supabase}from"../supabase";

type Category="all"|"robot"|"cad"|"workshop"|"event"|"team";
type Media={id:string;title:string;caption:string|null;category:Exclude<Category,"all">;media_kind:"image"|"drawing"|"document";storage_path:string;mime_type:string;file_name:string;event_date:string|null;tags:string[];uploaded_by:string;created_at:string};
const categories:[Category,string,string][]=[["all","All media","הכול"],["robot","Robot","רובוט"],["cad","CAD & drawings","CAD ושרטוטים"],["workshop","Workshop progress","התקדמות בסדנה"],["event","Events","אירועים"],["team","Team stories","סיפורי קבוצה"]];

export default function TeamMediaPage(){const{pick}=useLocalization(),{profile}=useMemberAuth();const[items,setItems]=useState<Media[]>([]),[urls,setUrls]=useState<Record<string,string>>({}),[category,setCategory]=useState<Category>("all"),[query,setQuery]=useState(""),[showUpload,setShowUpload]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const[form,setForm]=useState({title:"",caption:"",category:"robot" as Exclude<Category,"all">,event_date:"",tags:""}),[file,setFile]=useState<File|null>(null);
 async function load(){const{data,error}=await supabase.from("team_media").select("*").order("event_date",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false});if(error){setMessage(error.message);return}const rows=(data??[])as Media[];setItems(rows);const pairs=await Promise.all(rows.map(async row=>[row.id,await signedFileUrl("team-media",row.storage_path)] as const));setUrls(Object.fromEntries(pairs));}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>items.filter(item=>(category==="all"||item.category===category)&&(!query||`${item.title} ${item.caption??""} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[items,category,query]);
 async function upload(event:FormEvent){event.preventDefault();if(!profile||!file)return;setBusy(true);setMessage("");try{const prepared=await prepareImage(file);if(prepared.size>MAX_MEDIA_BYTES)throw new Error(pick("File is larger than 15 MB.","הקובץ גדול מ־15MB."));const path=`${profile.id}/${safeStorageName(prepared.name)}`;const uploaded=await supabase.storage.from("team-media").upload(path,prepared,{contentType:prepared.type,upsert:false});if(uploaded.error)throw uploaded.error;const kind=prepared.type==="application/pdf"?"document":form.category==="cad"?"drawing":"image";const saved=await supabase.from("team_media").insert({title:form.title.trim(),caption:form.caption.trim()||null,category:form.category,media_kind:kind,storage_path:path,mime_type:prepared.type,file_name:prepared.name,event_date:form.event_date||null,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean),uploaded_by:profile.id});if(saved.error){await supabase.storage.from("team-media").remove([path]);throw saved.error}setForm({title:"",caption:"",category:"robot",event_date:"",tags:""});setFile(null);setShowUpload(false);setMessage(pick("Media added to the team library.","המדיה נוספה לספריית הקבוצה."));await load()}catch(error:any){setMessage(error?.message??pick("Upload failed.","ההעלאה נכשלה."))}finally{setBusy(false)}}
 async function remove(item:Media){if(!profile||!confirm(pick("Delete this media item permanently?","למחוק את פריט המדיה לצמיתות?")))return;const result=await supabase.from("team_media").delete().eq("id",item.id);if(result.error){setMessage(result.error.message);return}await supabase.storage.from("team-media").remove([item.storage_path]);await load()}
 return <main className="hub-page media-page"><header className="media-hero"><div><span>G3 6740 · {pick("TEAM ARCHIVE","ארכיון הקבוצה")}</span><h1>{pick("Team Media","מדיה קבוצתית")}</h1><p>{pick("The visual record of our robot, engineering work, workshop progress and team moments.","התיעוד החזותי של הרובוט, העבודה ההנדסית, ההתקדמות בסדנה ורגעי הקבוצה.")}</p></div><button onClick={()=>setShowUpload(value=>!value)}>{showUpload?pick("Close","סגירה"):pick("+ Add media","+ הוספת מדיה")}</button></header>
 {showUpload?<form className="hub-card media-upload-form" onSubmit={upload}><header><div><strong>{pick("Add to the team story","הוספה לסיפור הקבוצה")}</strong><small>{pick("Images are compressed before upload. PDFs are supported for CAD drawings.","תמונות נדחסות לפני ההעלאה. קובצי PDF נתמכים עבור שרטוטי CAD.")}</small></div></header><label>{pick("Title","כותרת")}<input required maxLength={140} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>{pick("Collection","אוסף")}<select value={form.category} onChange={e=>setForm({...form,category:e.target.value as Exclude<Category,"all">})}>{categories.slice(1).map(([value,en,he])=><option value={value} key={value}>{pick(en,he)}</option>)}</select></label><label className="wide">{pick("Caption","תיאור")}<textarea rows={3} value={form.caption} onChange={e=>setForm({...form,caption:e.target.value})}/></label><label>{pick("Date (optional)","תאריך (אופציונלי)")}<input type="date" value={form.event_date} onChange={e=>setForm({...form,event_date:e.target.value})}/></label><label>{pick("Tags — comma separated","תגיות — מופרדות בפסיקים")}<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label><label className="wide media-file-drop"><input required type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/><span>{file?file.name:pick("Choose a photo, render or drawing","בחירת תמונה, הדמיה או שרטוט")}</span><small>{pick("Maximum 15 MB · no student names or private information","עד 15MB · ללא שמות תלמידים או מידע פרטי")}</small></label><button disabled={busy}>{busy?pick("Preparing upload…","מכין העלאה…"):pick("Publish to Team Media","פרסום במדיה הקבוצתית")}</button></form>:null}
 {message?<div className="hub-message" role="status">{message}</div>:null}<section className="media-toolbar"><div role="tablist" aria-label={pick("Media collections","אוספי מדיה")}>{categories.map(([value,en,he])=><button role="tab" aria-selected={category===value} className={category===value?"is-active":""} onClick={()=>setCategory(value)} key={value}>{pick(en,he)}<b>{value==="all"?items.length:items.filter(x=>x.category===value).length}</b></button>)}</div><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={pick("Search media","חיפוש במדיה")}/></label></section>
 <section className="media-gallery">{visible.map((item,index)=><article className={index%7===0?"is-featured":""} key={item.id}><a href={urls[item.id]} target="_blank" rel="noreferrer" className="media-preview">{item.mime_type.startsWith("image/")?<img src={urls[item.id]} alt={item.title}/>:<span><b>PDF</b>{pick("Open drawing","פתיחת שרטוט")}</span>}<i>{pick(categories.find(x=>x[0]===item.category)?.[1]??item.category,categories.find(x=>x[0]===item.category)?.[2]??item.category)}</i></a><div><small>{item.event_date?new Date(`${item.event_date}T12:00:00`).toLocaleDateString():new Date(item.created_at).toLocaleDateString()}</small><h2>{item.title}</h2>{item.caption?<p>{item.caption}</p>:null}{item.tags.length?<footer>{item.tags.map(tag=><span key={tag}>#{tag}</span>)}</footer>:null}{profile&&(profile.id===item.uploaded_by||["admin","mentor"].includes(profile.role))?<button className="danger-link" onClick={()=>void remove(item)}>{pick("Delete","מחיקה")}</button>:null}</div></article>)}{!visible.length?<div className="media-empty"><span>▧</span><h2>{pick("This collection is ready for its first story","האוסף מוכן לסיפור הראשון שלו")}</h2><p>{pick("Add a photo, CAD render, workshop update or event moment.","הוסיפו תמונה, הדמיית CAD, עדכון מהסדנה או רגע מאירוע.")}</p></div>:null}</section></main>}
