import { FormEvent, useEffect, useMemo, useState } from "react";
import { useAdminStatus } from "../lib/useAdminStatus";
import { useLocalization } from "../lib/localization";
import { useMemberAuth } from "../lib/memberAuth";
import { supabase } from "../supabase";

type Tool={id:string;name:string;category:string|null;asset_tag:string|null;status:string;requires_training:boolean};
type Checkout={id:string;tool_id:string;member_id:string;expected_return_at:string|null;returned_at:string|null};
type Maintenance={id:string;tool_id:string;description:string;status:string};
const categories=["Hand tools","Power tools","Machining","Electrical & electronics","Measurement & inspection","Batteries & chargers","Safety & PPE","Pit equipment","Consumables","Other"];

function csvCell(value:unknown){return `"${String(value??"").replace(/"/g,'""')}"`;}

export default function ToolsInventoryPage(){
  const {pick}=useLocalization(); const {profile}=useMemberAuth(); const isAdmin=useAdminStatus();
  const [tools,setTools]=useState<Tool[]>([]); const [checkouts,setCheckouts]=useState<Checkout[]>([]); const [maintenance,setMaintenance]=useState<Maintenance[]>([]); const [members,setMembers]=useState<Record<string,string>>({});
  const [name,setName]=useState(""); const [assetTag,setAssetTag]=useState(""); const [category,setCategory]=useState(""); const [customCategory,setCustomCategory]=useState(""); const [training,setTraining]=useState(false); const [query,setQuery]=useState(""); const [statusFilter,setStatusFilter]=useState("all"); const [categoryFilter,setCategoryFilter]=useState("all"); const [message,setMessage]=useState("");
  async function load(){const [{data:t},{data:c},{data:m},{data:people}]=await Promise.all([supabase.from("workshop_tools").select("*").order("name"),supabase.from("tool_checkouts").select("*").is("returned_at",null),supabase.from("tool_maintenance").select("*").neq("status","resolved"),supabase.from("team_members").select("id,display_name")]);setTools((t??[]) as Tool[]);setCheckouts((c??[]) as Checkout[]);setMaintenance((m??[]) as Maintenance[]);setMembers(Object.fromEntries((people??[]).map(person=>[person.id,person.display_name])));}
  useEffect(()=>{void load();},[]);
  async function addTool(event:FormEvent){event.preventDefault();const finalCategory=category==="Other"?customCategory.trim()||"Other":category;const {error}=await supabase.from("workshop_tools").insert({name:name.trim(),asset_tag:assetTag.trim()||null,category:finalCategory,requires_training:training,created_by:profile?.id});setMessage(error?.message??pick("Equipment added.","הציוד נוסף."));if(!error){setName("");setAssetTag("");setCategory("");setCustomCategory("");setTraining(false);await load();}}
  async function checkout(tool:Tool){if(!profile)return;const due=prompt(pick("Expected return date (YYYY-MM-DD), or leave blank","תאריך החזרה צפוי YYYY-MM-DD, או להשאיר ריק"));const {error}=await supabase.rpc("checkout_tool",{target_tool:tool.id,expected_return:due?new Date(`${due}T18:00:00+03:00`).toISOString():null});setMessage(error?.message??pick("Equipment checked out.","הציוד הושאל."));if(!error)await load();}
  async function returnTool(item:Checkout){const {error}=await supabase.from("tool_checkouts").update({returned_at:new Date().toISOString(),returned_to:profile?.id}).eq("id",item.id);setMessage(error?.message??pick("Equipment returned.","הציוד הוחזר."));if(!error)await load();}
  async function report(tool:Tool){const description=prompt(pick("Describe the issue","תיאור התקלה"));if(!description?.trim())return;await supabase.from("tool_maintenance").insert({tool_id:tool.id,description:description.trim(),reported_by:profile?.id});await load();}
  const rows=useMemo(()=>tools.map(tool=>{const loan=checkouts.find(item=>item.tool_id===tool.id);const issue=maintenance.find(item=>item.tool_id===tool.id);const status=issue?"maintenance":loan?"borrowed":"available";return{tool,loan,issue,status};}).filter(row=>(!query||`${row.tool.name} ${row.tool.asset_tag??""} ${row.tool.category??""}`.toLowerCase().includes(query.toLowerCase()))&&(statusFilter==="all"||row.status===statusFilter)&&(categoryFilter==="all"||row.tool.category===categoryFilter)),[tools,checkouts,maintenance,query,statusFilter,categoryFilter]);
  function exportCsv(){const header=["Asset tag","Tool","Category","Status","Holder","Return date","Training required","Maintenance"];const body=rows.map(({tool,loan,issue,status})=>[tool.asset_tag,tool.name,tool.category,status,loan?members[loan.member_id]:"",loan?.expected_return_at?new Date(loan.expected_return_at).toLocaleDateString():"",tool.requires_training?"Yes":"No",issue?.description??""]);const blob=new Blob(["\uFEFF"+[header,...body].map(row=>row.map(csvCell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`g3-tools-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);}
  return <main className="hub-page tools-page"><header className="hub-page-header"><div><div className="hub-eyebrow">{pick("Work / Workshop operations","עבודה / תפעול הסדנה")}</div><h1>{pick("Tools & equipment","כלים וציוד")}</h1><p>{pick("A live, searchable inventory for the G3 workshop.","מלאי חי וניתן לחיפוש עבור סדנת G3.")}</p></div><button className="hub-button secondary" onClick={exportCsv}>{pick("Export for Excel","ייצוא לאקסל")}</button></header>
  <section className="tool-summary"><article><strong>{tools.length}</strong><span>{pick("Assets","פריטים")}</span></article><article><strong>{checkouts.length}</strong><span>{pick("Borrowed","מושאלים")}</span></article><article><strong>{maintenance.length}</strong><span>{pick("Maintenance","תחזוקה")}</span></article></section>
  {isAdmin?<form className="hub-card tool-create-grid" onSubmit={addTool}><label>{pick("Equipment name","שם הציוד")}<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>{pick("Asset tag","מספר נכס")}<input value={assetTag} onChange={e=>setAssetTag(e.target.value)}/></label><label>{pick("Category","קטגוריה")}<select required value={category} onChange={e=>setCategory(e.target.value)}><option value="">{pick("Choose category","בחירת קטגוריה")}</option>{categories.map(item=><option key={item}>{item}</option>)}</select></label>{category==="Other"?<label>{pick("Custom category","קטגוריה אחרת")}<input required value={customCategory} onChange={e=>setCustomCategory(e.target.value)}/></label>:null}<label className="checkbox-label"><input type="checkbox" checked={training} onChange={e=>setTraining(e.target.checked)}/>{pick("Training required","נדרשת הכשרה")}</label><button className="hub-button">{pick("Add equipment","הוספת ציוד")}</button></form>:null}
  <section className="inventory-toolbar"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={pick("Search tool or asset tag…","חיפוש כלי או מספר נכס…")}/><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="all">{pick("All categories","כל הקטגוריות")}</option>{categories.map(item=><option key={item}>{item}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">{pick("All statuses","כל הסטטוסים")}</option><option value="available">{pick("Available","זמין")}</option><option value="borrowed">{pick("Borrowed","מושאל")}</option><option value="maintenance">{pick("Maintenance","תחזוקה")}</option></select></section>{message?<div className="auth-message" role="status">{message}</div>:null}
  <div className="inventory-table"><div className="inventory-row inventory-head"><span>{pick("Asset / Tool","נכס / כלי")}</span><span>{pick("Category","קטגוריה")}</span><span>{pick("Status","סטטוס")}</span><span>{pick("Holder / Return","מחזיק / החזרה")}</span><span>{pick("Actions","פעולות")}</span></div>{rows.map(({tool,loan,issue,status})=><article className="inventory-row" key={tool.id}><span><strong>{tool.name}</strong><small>{tool.asset_tag||pick("No asset tag","ללא מספר נכס")}{tool.requires_training?` · ${pick("Training required","נדרשת הכשרה")}`:""}</small></span><span data-label={pick("Category","קטגוריה")}>{tool.category||pick("Other","אחר")}</span><span data-label={pick("Status","סטטוס")}><i className={`inventory-status status-${status}`}>{pick(status,status==="available"?"זמין":status==="borrowed"?"מושאל":"תחזוקה")}</i>{issue?<small>{issue.description}</small>:null}</span><span data-label={pick("Holder / Return","מחזיק / החזרה")}>{loan?<><strong>{members[loan.member_id]??pick("Team member","חבר קבוצה")}</strong><small>{loan.expected_return_at?new Date(loan.expected_return_at).toLocaleDateString():pick("No return date","ללא תאריך החזרה")}</small></>:"—"}</span><span className="inventory-actions">{loan?<button disabled={loan.member_id!==profile?.id&&!isAdmin} onClick={()=>void returnTool(loan)}>{pick("Return","החזרה")}</button>:<button disabled={status==="maintenance"} onClick={()=>void checkout(tool)}>{pick("Check out","השאלה")}</button>}<button onClick={()=>void report(tool)}>{pick("Report issue","דיווח תקלה")}</button></span></article>)}</div>
  </main>;
}
