import {FormEvent,useEffect,useState} from "react";
import {useLocalization} from "../lib/localization";
import {useMemberAuth} from "../lib/memberAuth";
import {supabase} from "../supabase";
import {memberTeams,normalizedTeamMatch,useAccessControl} from "../lib/accessControl";

type E={id:string;title:string;description:string|null;event_type:string;starts_at:string;ends_at:string;all_day:boolean;location:string|null;target_type:string;target_value:string|null;mandatory:boolean};
type EventForm={title:string;description:string;event_type:string;start:string;end:string;location:string;target_type:string;target_value:string;mandatory:boolean};
const dayMs=86400000,emptyForm:EventForm={title:"",description:"",event_type:"team_event",start:"",end:"",location:"",target_type:"all",target_value:"",mandatory:true};
function occursOnDay(event:E,day:Date){const start=new Date(event.starts_at),end=new Date(event.ends_at),dayStart=new Date(day.getFullYear(),day.getMonth(),day.getDate()),dayEnd=new Date(day.getFullYear(),day.getMonth(),day.getDate(),23,59,59,999);return start<=dayEnd&&end>=dayStart;}
function occursInMonth(event:E,cursor:Date){const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),last=new Date(cursor.getFullYear(),cursor.getMonth()+1,0,23,59,59,999);return new Date(event.starts_at)<=last&&new Date(event.ends_at)>=first;}
function localValue(value:string){const date=new Date(value),offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}

export default function UnifiedCalendarPage(){
 const {pick}=useLocalization(),{profile}=useMemberAuth(),access=useAccessControl();
 const [events,setEvents]=useState<E[]>([]),[cursor,setCursor]=useState(new Date()),[view,setView]=useState<"month"|"agenda">("month"),[show,setShow]=useState(false),[message,setMessage]=useState(""),[selected,setSelected]=useState<E|null>(null),[editingId,setEditingId]=useState<string|null>(null),[f,setF]=useState<EventForm>(emptyForm);
 async function load(){const {data,error}=await supabase.from("team_calendar_events").select("*").eq("cancelled",false).order("starts_at");if(error)setMessage(error.message);else setEvents(((data??[]) as E[]).filter(x=>x.target_type==="all"||x.target_type==="member"&&x.target_value===profile?.id||x.target_type==="subteam"&&memberTeams(profile).some(team=>normalizedTeamMatch(team,x.target_value))));}
 useEffect(()=>{void load();},[profile?.id]);
 function openCreate(){setEditingId(null);setF(emptyForm);setSelected(null);setShow(true);}
 function openEdit(event:E){setEditingId(event.id);setF({title:event.title,description:event.description??"",event_type:event.event_type,start:localValue(event.starts_at),end:localValue(event.ends_at),location:event.location??"",target_type:event.target_type,target_value:event.target_value??"",mandatory:event.mandatory});setSelected(null);setShow(true);}
 async function save(e:FormEvent){e.preventDefault();const startsAt=new Date(f.start),endsAt=new Date(f.end||f.start);if(endsAt<startsAt){setMessage(pick("The end date must be after the start date.","תאריך הסיום חייב להיות אחרי תאריך ההתחלה."));return;}const payload={title:f.title,description:f.description||null,event_type:f.event_type,starts_at:startsAt.toISOString(),ends_at:endsAt.toISOString(),location:f.location||null,target_type:f.target_type,target_value:f.target_type==="all"?null:f.target_value||null,mandatory:f.mandatory};const result=editingId?await supabase.from("team_calendar_events").update(payload).eq("id",editingId):await supabase.from("team_calendar_events").insert({...payload,created_by:profile?.id});setMessage(result.error?.message??pick(editingId?"Calendar event updated.":"Calendar event published.",editingId?"האירוע עודכן.":"אירוע פורסם בלוח השנה."));if(!result.error){setShow(false);setEditingId(null);setF(emptyForm);await load();}}
 async function remove(event:E){if(!window.confirm(pick(`Delete “${event.title}” from the team calendar?`,`למחוק את „${event.title}” מלוח הקבוצה?`)))return;const {error}=await supabase.from("team_calendar_events").update({cancelled:true}).eq("id",event.id);setMessage(error?.message??pick("Calendar event deleted.","האירוע נמחק."));if(!error){setSelected(null);await load();}}
 const start=new Date(cursor.getFullYear(),cursor.getMonth(),1),gridStart=new Date(start);gridStart.setDate(start.getDate()-start.getDay());const days=Array.from({length:42},(_,i)=>new Date(gridStart.getTime()+i*dayMs)),monthEvents=events.filter(x=>occursInMonth(x,cursor)),upcoming=events.filter(x=>new Date(x.ends_at).getTime()>=Date.now()).slice(0,30);
 return <main className="hub-page calendar-page"><header className="calendar-hero"><div><div className="hub-eyebrow">FRC 6740 · {pick("One team calendar","לוח שנה קבוצתי אחד")}</div><h1>{pick("Team schedule","לוח הקבוצה")}</h1><p>{pick("Meetings, fundraising, competitions, training, deadlines and personal assignments in one place.","מפגשים, גיוס כספים, תחרויות, הכשרות, מועדים ושיבוצים אישיים במקום אחד.")}</p></div>{access.can("manage_team_calendar")?<button onClick={()=>show?(setShow(false),setEditingId(null)):openCreate()}>{show?pick("Close editor","סגירת העורך"):`+ ${pick("Add event","הוספת אירוע")}`}</button>:null}</header>
 <nav className="calendar-controls"><div><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}>←</button><strong>{cursor.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</strong><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}>→</button></div><div><button className={view==="month"?"is-active":""} onClick={()=>setView("month")}>{pick("Month","חודש")}</button><button className={view==="agenda"?"is-active":""} onClick={()=>setView("agenda")}>{pick("Agenda","סדר יום")}</button></div></nav>
 {message?<div className="hub-message" role="status" aria-live="polite">{message}</div>:null}
 {show?<form className="hub-card calendar-form" onSubmit={save}><div className="wide calendar-form-heading"><span>{pick(editingId?"EDIT EVENT":"NEW EVENT",editingId?"עריכת אירוע":"אירוע חדש")}</span><h2>{pick(editingId?"Update the team schedule":"Add to the team schedule",editingId?"עדכון לוח הקבוצה":"הוספה ללוח הקבוצה")}</h2></div><label>{pick("Event title","כותרת אירוע")}<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>{pick("Type","סוג")}<select value={f.event_type} onChange={e=>setF({...f,event_type:e.target.value})}>{["team_event","fundraising","competition","training","deadline","meeting","other"].map(x=><option key={x}>{x}</option>)}</select></label><label>{pick("Starts","מתחיל")}<input required type="datetime-local" value={f.start} onChange={e=>setF({...f,start:e.target.value,end:e.target.value>f.end?e.target.value:f.end})}/></label><label>{pick("Ends","מסתיים")}<input required type="datetime-local" min={f.start||undefined} value={f.end} onChange={e=>setF({...f,end:e.target.value})}/></label><label>{pick("Audience","קהל יעד")}<select value={f.target_type} onChange={e=>setF({...f,target_type:e.target.value})}><option value="all">{pick("Whole team","כל הקבוצה")}</option><option value="subteam">{pick("Subteam","תת־צוות")}</option><option value="member">{pick("Individual member ID","חבר/ה יחיד/ה")}</option></select></label>{f.target_type!=="all"?<label>{pick("Subteam or member ID","תת־צוות או מזהה חבר/ה")}<input required value={f.target_value} onChange={e=>setF({...f,target_value:e.target.value})}/></label>:null}<label>{pick("Location","מיקום")}<input value={f.location} onChange={e=>setF({...f,location:e.target.value})}/></label><label className="wide">{pick("Details","פרטים")}<textarea rows={3} value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={f.mandatory} onChange={e=>setF({...f,mandatory:e.target.checked})}/>{pick("Mandatory attendance","נוכחות חובה")}</label><button className="hub-button">{pick(editingId?"Save event changes":"Publish to calendar",editingId?"שמירת השינויים":"פרסום בלוח")}</button></form>:null}
 {view==="month"?<section className="month-calendar"><header>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><span key={x}>{x}</span>)}</header><div>{days.map(d=>{const rows=events.filter(x=>occursOnDay(x,d));return <article className={d.getMonth()===cursor.getMonth()?"":"outside"} key={d.toISOString()}><b>{d.getDate()}</b>{rows.slice(0,3).map(x=><button type="button" className={`calendar-event-chip event-${x.event_type}`} key={x.id} onClick={()=>setSelected(x)}>{x.mandatory?"! ":""}{x.title}</button>)}{rows.length>3?<small>+{rows.length-3}</small>:null}</article>})}</div></section>:<section className="calendar-agenda">{upcoming.map(x=><button type="button" className="hub-card calendar-agenda-event" key={x.id} onClick={()=>setSelected(x)}><time><strong>{new Date(x.starts_at).getDate()}</strong><span>{new Date(x.starts_at).toLocaleDateString(undefined,{month:"short"})}</span></time><div><span>{x.event_type}{x.mandatory?` · ${pick("MANDATORY","חובה")}`:""}</span><h2>{x.title}</h2><p>{x.description}</p><small>{new Date(x.starts_at).toLocaleString()} – {new Date(x.ends_at).toLocaleString()} · {x.location}</small></div><b>›</b></button>)}</section>}
 {selected?<div className="calendar-detail-backdrop" role="presentation" onClick={()=>setSelected(null)}><article className="calendar-detail-dialog" role="dialog" aria-modal="true" aria-labelledby="calendar-detail-title" onClick={event=>event.stopPropagation()}><header><div><span>{selected.event_type}{selected.mandatory?` · ${pick("Mandatory","חובה")}`:""}</span><h2 id="calendar-detail-title">{selected.title}</h2></div><button type="button" onClick={()=>setSelected(null)} aria-label={pick("Close event details","סגירת פרטי האירוע")}>×</button></header>{selected.description?<p>{selected.description}</p>:<p className="calendar-no-details">{pick("No additional details were provided.","לא נוספו פרטים נוספים.")}</p>}<dl><div><dt>{pick("Starts","מתחיל")}</dt><dd>{new Date(selected.starts_at).toLocaleString()}</dd></div><div><dt>{pick("Ends","מסתיים")}</dt><dd>{new Date(selected.ends_at).toLocaleString()}</dd></div>{selected.location?<div><dt>{pick("Location","מיקום")}</dt><dd>{selected.location}</dd></div>:null}<div><dt>{pick("Audience","קהל יעד")}</dt><dd>{selected.target_type==="all"?pick("Whole team","כל הקבוצה"):selected.target_value}</dd></div></dl>{access.can("manage_team_calendar")?<footer><button type="button" className="danger" onClick={()=>void remove(selected)}>{pick("Delete event","מחיקת אירוע")}</button><button type="button" className="hub-button" onClick={()=>openEdit(selected)}>{pick("Edit event","עריכת אירוע")}</button></footer>:null}</article></div>:null}
 <footer className="calendar-footnote">{pick(`${monthEvents.length} scheduled items overlap this month. Long-range mandatory dates remain visible months in advance.`,`${monthEvents.length} פריטים מתוכננים חופפים לחודש זה. מועדי חובה ארוכי טווח נשארים גלויים חודשים מראש.`)}</footer></main>;
}
