import {useBuildStringDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
import {useState} from 'react';import {supabase} from '../supabase';import {useLocalization} from '../lib/localization';
export default function BuildExistingStock({projectId,tasks,saved}:{projectId:string;tasks:{id:string;title:string}[];saved:()=>Promise<void>}){
 const initial=()=>({part:'',task:'',quantity:'1',note:'',request:crypto.randomUUID()});
 const draft=useBuildStringDraft(`existing-stock:${projectId}`,initial);const {part,task,quantity,note,request}=draft.value;
 const setPart=(value:string)=>draft.change({part:value,request:crypto.randomUUID()});const setTask=(value:string)=>draft.change({task:value,request:crypto.randomUUID()});const setQuantity=(value:string)=>draft.change({quantity:value,request:crypto.randomUUID()});const setNote=(value:string)=>draft.change({note:value,request:crypto.randomUUID()});const setRequest=(value:ReturnType<typeof crypto.randomUUID>)=>draft.change({request:value});

 const {pick}=useLocalization();const [parts,setParts]=useState<{id:string;name:string;quantity:number}[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <details onToggle={async e=>{if(!e.currentTarget.open)return;const r=await supabase.from('frc_parts_inventory').select('id,name,quantity').eq('archived',false).eq('unit','pcs').order('name');if(r.error)setMessage(pick('Could not load inventory.','לא ניתן לטעון מלאי.'));else setParts(r.data??[]);}}><summary>{pick('Verify parts already in the workshop','אימות חלקים שכבר נמצאים בסדנה')}</summary><p>{pick('Use a separate physical QC task for existing parts. This records an inspected batch without adding stock or inventing manufacturing history. Count the parts in Inventory first if its quantity is wrong.','השתמשו במשימת בדיקת איכות נפרדת לחלקים קיימים. הרישום יוצר אצווה שנבדקה בלי להוסיף מלאי או להמציא היסטוריית ייצור. אם הכמות שגויה, בצעו קודם ספירת מלאי.')}</p><form data-build-form={draft.id} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const r=await supabase.rpc('reconcile_robot_build_existing_stock',{p_task:task,p_part:part,p_quantity:Number(quantity),p_note:note,p_request:request});if(r.error)throw Error(r.error.message);draft.saved(initial());await saved();setMessage(pick('Existing inspected stock recorded. Inventory quantity is unchanged.','מלאי קיים שנבדק נרשם. כמות המלאי לא השתנתה.'));}catch(e){setMessage(e instanceof Error?e.message:pick('Save not confirmed.','השמירה לא אושרה.'));}finally{setBusy(false);}}}><fieldset disabled={busy}><BuildDraftNotice {...draft}/>
 <label>{pick('Existing-stock QC task','משימת בדיקת מלאי קיים')}<select required value={task} onChange={e=>{setTask(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose inspection task','בחרו משימת בדיקה')}</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>
 <label>{pick('Existing inventory part','חלק קיים במלאי')}<select required value={part} onChange={e=>{setPart(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose confirmed component','בחרו רכיב מאומת')}</option>{parts.map(p=><option key={p.id} value={p.id}>{p.name} · {p.quantity}</option>)}</select></label>
 <label>{pick('Physically inspected pieces','יחידות שנבדקו פיזית')}<input required type="number" min={1} max={100000} step={1} value={quantity} onChange={e=>{setQuantity(e.target.value);setRequest(crypto.randomUUID());}}/></label>
 <label>{pick('Known source, batch identity and location','מקור ידוע, זיהוי אצווה ומיקום')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);setRequest(crypto.randomUUID());}}/></label><button>{pick('Record verified existing stock','רישום מלאי קיים מאומת')}</button></fieldset></form><p role="status">{message}</p></details>;
}
