import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {readBuildPages} from '../lib/robotBuildWorkspace';
import BuildAssemblyLots from './BuildAssemblyLots';
import {useBuildStringDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
export default function BuildStockAssembly({projectId,tasks,kits,saved}:{projectId:string;tasks:{id:string;title:string;status:string}[];kits:{id:string;task_id:string;name:string;stock_output_part_id?:string|null;stock_received_at?:string|null;stock_output_quantity?:number|null}[];saved:()=>Promise<void>}){
 const {pick}=useLocalization();const [parts,setParts]=useState<{id:string;name:string}[]>([]),[configs,setConfigs]=useState<{id:string;name:string;revision:string}[]>([]),[eligible,setEligible]=useState<string[]>([]);
 const planInitial=()=>({task:'',name:'',part:'',quantity:'1',request:crypto.randomUUID()});
 const receiptInitial=()=>({kit:'',configuration:'',note:'',request:crypto.randomUUID()});
 const plan=useBuildStringDraft(`stock-assembly-plan:${projectId}`,planInitial),receipt=useBuildStringDraft(`stock-assembly-receive:${projectId}`,receiptInitial);
 const {task,name,part,quantity}=plan.value,{kit,configuration,note}=receipt.value;
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false),[lotKits,setLotKits]=useState<string[]|null>(null);
 useEffect(()=>{let live=true;setLoaded(false);void Promise.all([
  readBuildPages<{id:string;name:string}>((a,z)=>supabase.from('frc_parts_inventory').select('id,name').eq('archived',false).eq('unit','pcs').order('id').range(a,z)),
  readBuildPages<{id:string;name:string;revision:string}>((a,z)=>supabase.from('project_robot_configurations').select('id,name,revision').eq('project_id',projectId).eq('configuration_kind','as_built').order('id').range(a,z)),
  readBuildPages<{task_id:string}>((a,z)=>supabase.from('project_review_gates').select('task_id,project_tasks!inner(project_id)').eq('project_tasks.project_id',projectId).eq('enabled',true).eq('decision_type','qc_accepted').order('task_id').range(a,z)),
  readBuildPages<{task_id:string}>((a,z)=>supabase.from('robot_build_jobs').select('task_id,project_tasks!robot_build_jobs_task_id_fkey!inner(project_id)').eq('project_tasks.project_id',projectId).order('id').range(a,z)),
 ]).then(([p,c,g,j])=>{if(live){setParts(p);setConfigs(c);setEligible(g.filter(x=>!j.some(job=>job.task_id===x.task_id)).map(x=>x.task_id));setLoaded(true);}}).catch(()=>{if(live)setMessage(pick('Could not load stock assembly options. Reload to retry.','לא ניתן לטעון אפשרויות הרכבה למלאי. טענו מחדש לניסיון חוזר.'));});return()=>{live=false;};},[projectId]);
 async function run(fn:()=>PromiseLike<{error:{message:string}|null}>,done:()=>void){if(busy)return;setBusy(true);setMessage('');try{const r=await fn();if(r.error)throw Error(r.error.message);done();await saved();setMessage(pick('Stock assembly record saved.','רשומת הרכבה למלאי נשמרה.'));}catch(e){setMessage(e instanceof Error?e.message:pick('Save not confirmed.','השמירה לא אושרה.'));}finally{setBusy(false);}}

 return <details><summary>{pick('Build an assembly for stock','הרכבת מכלול למלאי')}</summary><p>{pick('Create a bench assembly, plan its required components, then issue them using the kit actions below. After independent physical QC, receive the finished assemblies into inventory. This does not record a robot installation.','צרו מכלול, הגדירו את רכיביו ומסרו אותם באמצעות פעולות הערכה להלן. לאחר בדיקת איכות פיזית בלתי תלויה, קבלו את המכלולים המוגמרים למלאי. פעולה זו אינה רישום התקנה ברובוט.')}</p>
 <form data-build-form={plan.id} onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('create_robot_stock_assembly',{p_task:task,p_name:name,p_part:part,p_quantity:Number(quantity),p_request:plan.value.request}),()=>plan.saved(planInitial()));}}><fieldset disabled={busy||!loaded}><legend>{pick('1. Plan the stock assembly','1. תכנון מכלול למלאי')}</legend><BuildDraftNotice {...plan}/>
 <label>{pick('Existing assembly QC task','משימת בדיקת איכות קיימת')}<select required value={task} onChange={e=>{plan.change({task:e.target.value,request:crypto.randomUUID()});}}><option value="">{pick('Choose an open inspection task','בחירת משימת בדיקה פתוחה')}</option>{tasks.filter(t=>eligible.includes(t.id)&&t.status!=='done'&&!kits.some(k=>k.task_id===t.id)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>
 <label>{pick('Assembly name','שם המכלול')}<input required minLength={3} maxLength={180} value={name} onChange={e=>{plan.change({name:e.target.value,request:crypto.randomUUID()});}}/></label>
 <label>{pick('Finished assembly inventory item','פריט מלאי של המכלול המוגמר')}<select required value={part} onChange={e=>{plan.change({part:e.target.value,request:crypto.randomUUID()});}}><option value="">{pick('Choose finished item','בחירת פריט מוגמר')}</option>{parts.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label>{pick('Finished assemblies to produce','כמות מכלולים לייצור')}<input required type="number" min={1} max={100000} step={1} value={quantity} onChange={e=>{plan.change({quantity:e.target.value,request:crypto.randomUUID()});}}/></label><button>{pick('Create stock assembly kit','יצירת ערכת הרכבה למלאי')}</button></fieldset></form>
 {lotKits!==null&&kits.some(k=>k.stock_output_part_id&&!k.stock_received_at&&!lotKits.includes(k.id))&&<form data-build-form={receipt.id} onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('receive_robot_stock_assembly',{p_kit:kit,p_configuration:configuration,p_note:note,p_request:receipt.value.request}),()=>receipt.saved(receiptInitial()));}}><fieldset disabled={busy||!loaded}><legend>{pick('2. Receive inspected assemblies','2. קבלת מכלולים שנבדקו')}</legend><BuildDraftNotice {...receipt}/><label>{pick('Assembly kit','ערכת הרכבה')}<select required value={kit} onChange={e=>{receipt.change({kit:e.target.value,request:crypto.randomUUID()});}}><option value="">{pick('Choose assembly','בחירת מכלול')}</option>{kits.filter(k=>k.stock_output_part_id&&!k.stock_received_at&&!lotKits.includes(k.id)).map(k=><option key={k.id} value={k.id}>{k.name} · {k.stock_output_quantity}</option>)}</select></label><label>{pick('Exact inspected as-built configuration','תצורת ייצור מדויקת שנבדקה')}<select required value={configuration} onChange={e=>{receipt.change({configuration:e.target.value,request:crypto.randomUUID()});}}><option value="">{pick('Choose reviewed configuration','בחירת תצורה שנבדקה')}</option>{configs.map(c=><option key={c.id} value={c.id}>{c.name} · {c.revision}</option>)}</select></label><label>{pick('Output identity and storage location','זהות התוצר ומיקום האחסון')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>{receipt.change({note:e.target.value,request:crypto.randomUUID()});}}/></label><p>{pick('Issued components remain consumed. Disassembly is separate work and never returns components automatically.','הרכיבים שנמסרו נשארים מנוצלים. פירוק הוא עבודה נפרדת ואינו מחזיר רכיבים אוטומטית.')}</p><button>{pick('Receive accepted assemblies','קבלת מכלולים מאושרים')}</button></fieldset></form>}{loaded&&<BuildAssemblyLots projectId={projectId} kits={kits} tasks={tasks.filter(t=>eligible.includes(t.id)&&t.status!=='done')} configs={configs} saved={saved} onLots={setLotKits}/>}<p role="status">{message}</p></details>;
}
