import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useAccessControl} from '../lib/accessControl';
import {readBuildPages} from '../lib/robotBuildWorkspace';
type Component={id:string;name:string;serial_number:string|null;status:string};
type Mapping={id:string;kit_id:string;component_id:string;note:string;identity_snapshot:{component:{name:string;serial_number:string|null}}};
type Issue={id:string;title:string;status:string};
type Repair={issue_id:string;component_link_id:string;repair_task_id:string|null;retest_task_id:string|null;target_kit_id:string|null;revision:number;note:string;verified_at:string|null};
type Kit={id:string;name:string;installed_at:string|null;retired_at:string|null};
export default function BuildMaintenanceLinks({projectId,kits,tasks,canManage}:{projectId:string;kits:Kit[];tasks:{id:string;title:string;status:string}[];canManage:boolean}){
 const {pick}=useLocalization(),access=useAccessControl(),generation=useRef(0);
 const [data,setData]=useState<{components:Component[];links:Mapping[];issues:Issue[];repairs:Repair[];retests:string[];subteam:string|null}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [kit,setKit]=useState(''),[component,setComponent]=useState(''),[note,setNote]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID());
 async function load(){const token=++generation.current;setError('');try{
  const [components,links,issues,repairs,gates,project]=await Promise.all([
   readBuildPages<Component>((a,z)=>supabase.from('robot_components').select('id,name,serial_number,status').order('id').range(a,z)),
   readBuildPages<Mapping>((a,z)=>supabase.from('robot_build_component_links').select('*,robot_build_kits!inner(project_tasks!inner(project_id))').eq('robot_build_kits.project_tasks.project_id',projectId).order('id').range(a,z)),
   readBuildPages<Issue>((a,z)=>supabase.from('robot_issues').select('id,title,status').eq('project_id',projectId).eq('archived',false).order('id').range(a,z)),
   readBuildPages<Repair>((a,z)=>supabase.from('robot_build_issue_links').select('*,robot_issues!inner(project_id)').eq('robot_issues.project_id',projectId).order('issue_id').range(a,z)),
   readBuildPages<{task_id:string;decision_type:string}>((a,z)=>supabase.from('project_review_gates').select('task_id,decision_type,project_tasks!inner(project_id)').eq('project_tasks.project_id',projectId).eq('enabled',true).order('task_id').range(a,z)),
   supabase.from('team_projects').select('subteam').eq('id',projectId).single()]);
  if(project.error)throw project.error;if(token===generation.current)setData({components,links,issues,repairs,retests:gates.filter(g=>['verified_on_robot','competition_ready'].includes(g.decision_type)).map(g=>g.task_id),subteam:project.data.subteam});
 }catch{if(token===generation.current){setData(null);setError(pick('Maintenance links could not be loaded.','לא ניתן לטעון קישורי תחזוקה.'));}}}
 useEffect(()=>{setData(null);setKit('');setComponent('');void load();return()=>{generation.current++;};},[projectId]);
 const manage=canManage&&!!data&&access.can('manage_robot_reliability',data.subteam);
 return <section className="build-maintenance-links"><h3>{pick('Physical components, faults & retests','רכיבים פיזיים, תקלות ובדיקות חוזרות')}</h3><p>{pick('Link an installed assembly to its existing maintenance record after checking the physical identity. This does not create inventory or claim a new inspection.','קשרו הרכבה מותקנת לרשומת התחזוקה הקיימת לאחר בדיקת הזהות הפיזית. הקישור אינו יוצר מלאי או מעיד על בדיקה חדשה.')}</p>
 {error&&<p role="alert">{error} <button onClick={()=>void load()}>{pick('Retry','ניסיון חוזר')}</button></p>}{!data&&!error&&<p role="status">{pick('Loading maintenance links…','טוען קישורי תחזוקה…')}</p>}
 {data&&<>{data.links.map(l=><article className="build-job" key={l.id}><strong>{l.identity_snapshot.component.name} · {l.identity_snapshot.component.serial_number||pick('No serial recorded','לא נרשם מספר סידורי')}</strong><p>{kits.find(k=>k.id===l.kit_id)?.name} · {kits.find(k=>k.id===l.kit_id)?.retired_at?pick('Historical installation','התקנה היסטורית'):pick('Recorded installation','התקנה שנרשמה')}</p><Link to={`/robot-maintenance?component=${l.component_id}`}>{pick('Open component maintenance','פתיחת תחזוקת הרכיב')}</Link><p>{l.note}</p>
 {data.repairs.filter(r=>r.component_link_id===l.id).map(r=><p key={r.issue_id}><Link to={`/robot-issues?issue=${r.issue_id}`}>{data.issues.find(i=>i.id===r.issue_id)?.title||pick('Linked issue','תקלה מקושרת')}</Link> · {r.verified_at&&data.issues.find(i=>i.id===r.issue_id)?.status==='resolved'?pick('Verified closure recorded','נרשמה סגירה מאומתת'):pick('Repair and physical retest required','נדרשים תיקון ובדיקה פיזית חוזרת')}{r.retest_task_id&&<> · <Link to={`/robot-build?project=${projectId}&view=work&queue=team&task=${r.retest_task_id}`}>{pick('Open retest','פתיחת הבדיקה החוזרת')}</Link></>}</p>)}
 {manage&&<RepairPlan key={`${l.id}:${data.repairs.map(r=>r.revision).join(',')}`} mapping={l.id} projectId={projectId} issues={data.issues.filter(i=>i.status!=='resolved'&&(!data.repairs.some(r=>r.issue_id===i.id)||data.repairs.some(r=>r.issue_id===i.id&&r.component_link_id===l.id)))} plans={data.repairs} kits={kits} tasks={tasks} retests={data.retests} saved={load}/>}</article>)}
 {!data.links.length&&<p>{pick('No physical component links recorded for this build.','לא נרשמו קישורים לרכיבים פיזיים בבנייה זו.')}</p>}
 {manage&&<details><summary>{pick('Link an installed component','קישור רכיב מותקן')}</summary><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await supabase.rpc('link_robot_build_component',{p_kit:kit,p_component:component,p_note:note,p_request:request});if(r.error)throw r.error;await load();setNote('');setRequest(crypto.randomUUID());}catch(e){setError((e as {message:string}).message);}finally{setBusy(false);}}}><fieldset disabled={busy}><label>{pick('Recorded installation','התקנה שנרשמה')}<select required value={kit} onChange={e=>{setKit(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose installation','בחירת התקנה')}</option>{kits.filter(k=>k.installed_at&&!k.retired_at).map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select></label><label>{pick('Existing maintenance component','רכיב תחזוקה קיים')}<select required value={component} onChange={e=>{setComponent(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose the exact physical component','בחירת הרכיב הפיזי המדויק')}</option>{data.components.filter(c=>c.status==='installed').map(c=><option key={c.id} value={c.id}>{c.name} · {c.serial_number||c.id.slice(0,8)}</option>)}</select></label><label>{pick('How was the identity checked?','כיצד נבדקה הזהות?')}<textarea required minLength={5} maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);setRequest(crypto.randomUUID());}}/></label><button>{pick('Save physical identity link','שמירת קישור הזהות הפיזית')}</button></fieldset></form></details>}</>}
 </section>;
}
function RepairPlan({mapping,projectId,issues,plans,kits,tasks,retests,saved}:{mapping:string;projectId:string;issues:Issue[];plans:Repair[];kits:Kit[];tasks:{id:string;title:string;status:string}[];retests:string[];saved:()=>Promise<void>}){
 const {pick}=useLocalization(),[issue,setIssue]=useState(''),[repair,setRepair]=useState(''),[retest,setRetest]=useState(''),[target,setTarget]=useState(''),[note,setNote]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const reset=()=>setRequest(crypto.randomUUID());
 return <details><summary>{pick('Plan repair & required retest','תכנון תיקון ובדיקה חוזרת נדרשת')}</summary><p>{pick('Use the existing issue and tasks. The issue cannot be resolved until the repair is complete and a new approved physical retest identifies the target installation.','השתמשו בתקלה ובמשימות הקיימות. לא ניתן לסגור את התקלה עד השלמת התיקון ואישור בדיקה פיזית חדשה המזהה את ההתקנה המיועדת.')}</p><Link to="/robot-issues">{pick('Open issues to report or assign a fault to this project','פתיחת תקלות לדיווח או לשיוך תקלה לפרויקט זה')}</Link><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const r=await supabase.rpc('plan_robot_build_repair',{p_link:mapping,p_issue:issue,p_repair:repair||null,p_retest:retest||null,p_target:target||null,p_expected:plans.find(p=>p.issue_id===issue)?.revision??0,p_note:note,p_request:request});if(r.error)throw r.error;await saved();}catch(e){setMessage((e as {message:string}).message);}finally{setBusy(false);}}}><fieldset disabled={busy}><label>{pick('Existing project issue','תקלה קיימת בפרויקט')}<select required value={issue} onChange={e=>{setIssue(e.target.value);const p=plans.find(p=>p.issue_id===e.target.value);setRepair(p?.repair_task_id??'');setRetest(p?.retest_task_id??'');setTarget(p?.target_kit_id??'');setNote(p?.note??'');reset();}}><option value="">{pick('Choose an open issue','בחירת תקלה פתוחה')}</option>{issues.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label>
 <label>{pick('Repair task','משימת תיקון')}<select value={repair} onChange={e=>{setRepair(e.target.value);reset();}}><option value="">{pick('Not assigned yet — closure stays blocked','טרם שויך — הסגירה תישאר חסומה')}</option>{tasks.filter(t=>t.id!==retest).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label>
 <label>{pick('Physical retest checkpoint','נקודת בדיקה פיזית חוזרת')}<select value={retest} onChange={e=>{setRetest(e.target.value);reset();}}><option value="">{pick('Not assigned yet — closure stays blocked','טרם שויך — הסגירה תישאר חסומה')}</option>{tasks.filter(t=>retests.includes(t.id)&&t.id!==repair).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label>
 <label>{pick('Installation to verify after repair','התקנה לאימות לאחר התיקון')}<select value={target} onChange={e=>{setTarget(e.target.value);reset();}}><option value="">{pick('Not installed yet — closure stays blocked','טרם הותקן — הסגירה תישאר חסומה')}</option>{kits.filter(k=>k.installed_at&&!k.retired_at).map(k=><option value={k.id} key={k.id}>{k.name}</option>)}</select></label><label>{pick('Repair and verification plan','תוכנית תיקון ואימות')}<textarea required minLength={5} maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);reset();}}/></label><button disabled={!issue}>{pick('Save repair plan','שמירת תוכנית התיקון')}</button></fieldset></form><p role="status">{message}</p><Link to={`/projects?project=${projectId}`}>{pick('Open project tasks to configure repair or verification','פתיחת משימות הפרויקט להגדרת תיקון או אימות')}</Link></details>;
}
