import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {readBuildPages} from '../lib/robotBuildWorkspace';
import {useBuildStringDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
type Handoff={id:string;project_id:string;event_id:string;configuration_id:string;packing_item_id:string|null;kit_id:string|null;note:string;created_at:string};
type Event={id:string;name:string;start_date:string|null;active:boolean};
type Configuration={id:string;name:string;revision:string;configuration_kind:string;identity_snapshot:{asset?:{serial?:string;id?:string}}|null};
type Packing={id:string;title:string;status:string;archived:boolean};
type Kit={id:string;name:string;retired_at:string|null};
export default function BuildEventHandoff({projectId,eventId,editable=false}:{projectId?:string;eventId?:string;editable?:boolean}){
 const {pick}=useLocalization(),initial=()=>({event:'',configuration:'',packing:'',kit:'',note:'',request:crypto.randomUUID()}),draft=useBuildStringDraft(`build-event:${projectId??eventId}`,initial);
 const [rows,setRows]=useState<Handoff[]>([]),[events,setEvents]=useState<Event[]>([]),[configs,setConfigs]=useState<Configuration[]>([]),[packing,setPacking]=useState<Packing[]>([]),[kits,setKits]=useState<Kit[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let live=true;setLoading(true);setError('');void(async()=>{
  const r=await readBuildPages<Handoff>((a,z)=>{let q=supabase.from('robot_build_event_handoffs').select('*');q=projectId?q.eq('project_id',projectId):q.eq('event_id',eventId??'');return q.order('created_at',{ascending:false}).order('id').range(a,z);});
  const es=await readBuildPages<Event>((a,z)=>supabase.from('events').select('id,name,start_date,active').order('id').range(a,z));
  const cs=await readBuildPages<Configuration>((a,z)=>{let q=supabase.from('project_robot_configurations').select('id,name,revision,configuration_kind,identity_snapshot');if(projectId)q=q.eq('project_id',projectId);return q.order('id').range(a,z);});
  const ps=await readBuildPages<Packing>((a,z)=>supabase.from('frc_operational_items').select('id,title,status,archived').eq('area','packing').order('id').range(a,z));
  const ks=await readBuildPages<Kit>((a,z)=>{let q=supabase.from('robot_build_kits').select('id,name,retired_at,project_tasks!inner(project_id)');if(projectId)q=q.eq('project_tasks.project_id',projectId);return q.order('id').range(a,z);});
  if(live){setRows(r);setEvents(es);setConfigs(cs);setPacking(ps);setKits(ks);}
 })().catch(()=>{if(live)setError(pick('Build handoff unavailable. Do not treat missing records as readiness.','העברת הבנייה אינה זמינה. אין לפרש היעדר רשומות כמוכנות.'));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[projectId,eventId,reload]);
 return <section className="build-operation-learning"><h3>{pick('Robot & spares handoff','העברת רובוט וחלפים')}</h3><p>{pick('Event, exact physical configuration and existing packing record. This is preparation context, not a readiness approval. Packing never consumes inventory; repairs and retests stay in the build workflow.','אירוע, תצורה פיזית מדויקת ורשומת אריזה קיימת. זה הקשר להכנות, לא אישור מוכנות. אריזה אינה צורכת מלאי; תיקונים ובדיקות חוזרות נשארים בתהליך הבנייה.')}</p><button disabled={loading||busy} onClick={()=>setReload(n=>n+1)}>{pick('Refresh handoff','רענון ההעברה')}</button>{loading?<p role="status">{pick('Loading…','טוען…')}</p>:error?<p role="alert">{error}</p>:<ul>{rows.map((r,i)=>{const c=configs.find(c=>c.id===r.configuration_id),p=packing.find(p=>p.id===r.packing_item_id),k=kits.find(k=>k.id===r.kit_id),e=events.find(e=>e.id===r.event_id),earlier=rows.slice(0,i).some(x=>x.project_id===r.project_id&&x.event_id===r.event_id);return <li key={r.id}><strong>{e?.name??pick('Event unavailable','האירוע אינו זמין')} · {earlier?pick('Earlier handoff','העברה קודמת'):pick('Latest recorded handoff','ההעברה האחרונה שתועדה')}</strong><p>{c?`${c.name} · ${c.revision} · ${c.identity_snapshot?.asset?.serial??'—'}`:pick('Physical configuration unavailable','התצורה הפיזית אינה זמינה')}</p>{r.kit_id&&<p>{pick('Kit / spares','ערכה / חלפים')}: {k?.name??pick('Unavailable','לא זמין')}{k?.retired_at?' · '+pick('Retired — review replacement','הוצאה משימוש — בדקו החלפה'):''}</p>}{r.packing_item_id&&<p>{pick('Packing','אריזה')}: {p?`${p.title} · ${pick(({open:'Open',in_progress:'In progress',blocked:'Blocked',done:'Done'} as Record<string,string>)[p.status]??p.status,({open:'פתוח',in_progress:'בתהליך',blocked:'חסום',done:'הושלם'} as Record<string,string>)[p.status]??p.status)}${p.archived?' · '+pick('Archived','בארכיון'):''}`:pick('Record unavailable','הרשומה אינה זמינה')}</p>}<p>{r.note}</p><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleString(pick('en-GB','he-IL'))}</time><p><Link to={`/robot-build?project=${r.project_id}&view=assembly`}>{pick('Open build, replacement & retest','פתיחת הבנייה, החלפה ובדיקה חוזרת')}</Link>{r.packing_item_id&&<> · <Link to={`/frc-operations?area=packing&item=${r.packing_item_id}`}>{pick('Open packing record','פתיחת רשומת האריזה')}</Link></>}</p></li>;})}{!rows.length&&<li>{pick('No visible handoff recorded.','לא תועדה העברה גלויה.')}</li>}</ul>}
 {projectId&&editable&&!error&&<details><summary>{pick('Record event handoff','תיעוד העברה לאירוע')}</summary><form data-build-form={draft.id} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const r=await supabase.rpc('record_robot_build_handoff',{p_project:projectId,p_event:draft.value.event,p_configuration:draft.value.configuration,p_packing:draft.value.packing||null,p_kit:draft.value.kit||null,p_note:draft.value.note,p_request:draft.value.request});if(r.error)throw r.error;draft.saved(initial());setReload(n=>n+1);setMessage(pick('Handoff recorded. Packing, stock and readiness approvals were not changed.','ההעברה תועדה. אריזה, מלאי ואישורי מוכנות לא שונו.'));}catch(e){setMessage((e as {message?:string}).message??'Save failed');}finally{setBusy(false);}}}><fieldset disabled={busy||loading}><BuildDraftNotice {...draft}/>{(['event','configuration','packing','kit'] as const).map(key=><label key={key}>{pick(({event:'Competition event',configuration:'Physical configuration',packing:'Existing packing item (optional)',kit:'Kit / spares (optional)'})[key],({event:'אירוע תחרות',configuration:'תצורה פיזית',packing:'פריט אריזה קיים (רשות)',kit:'ערכה / חלפים (רשות)'})[key])}<select required={key==='event'||key==='configuration'} value={draft.value[key]} onChange={e=>draft.change({[key]:e.target.value,request:crypto.randomUUID()})}><option value="">{pick('Choose','בחירה')}</option>{(key==='event'?events.filter(e=>e.active).map(e=>({id:e.id,label:e.name+(e.start_date?' · '+e.start_date:'')})):key==='configuration'?configs.filter(c=>['as_built','as_installed'].includes(c.configuration_kind)&&c.identity_snapshot?.asset?.id).map(c=>({id:c.id,label:`${c.name} · ${c.revision} · ${c.identity_snapshot?.asset?.serial}`})):key==='packing'?packing.filter(p=>!p.archived).map(p=>({id:p.id,label:p.title})):kits.filter(k=>!k.retired_at).map(k=>({id:k.id,label:k.name}))).map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>)}<label>{pick('Handoff scope, packing location and outstanding checks','היקף ההעברה, מקום אריזה ובדיקות שנותרו')}<textarea required minLength={3} maxLength={2000} value={draft.value.note} onChange={e=>draft.change({note:e.target.value,request:crypto.randomUUID()})}/></label><button>{pick('Record handoff','תיעוד ההעברה')}</button></fieldset></form></details>}<p role="status">{message}</p></section>;
}
