import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {readBuildPages} from '../lib/robotBuildWorkspace';
type Requirement={id:string;name:string;revision:number;required_quantity:number;disposition:string;job_id:string|null;inventory_id:string|null};
export default function BuildKitRequirements({projectId,kitId,requirements,saved}:{projectId:string;kitId:string;requirements:{line_id:string;quantity:number}[];saved:()=>Promise<void>}){
 const {pick}=useLocalization();
 const [rows,setRows]=useState<Requirement[]>([]),[line,setLine]=useState(''),[quantity,setQuantity]=useState('1'),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[request,setRequest]=useState(()=>crypto.randomUUID());
 useEffect(()=>{let active=true;void readBuildPages<Requirement>((a,z)=>supabase.from('robot_build_bom_lines').select('id,name,revision,required_quantity,disposition,job_id,inventory_id,robot_build_boms!inner(project_id,shared_at)').eq('robot_build_boms.project_id',projectId).not('robot_build_boms.shared_at','is',null).in('disposition',['make','buy','reuse']).order('id').range(a,z)).then(data=>{if(active)setRows(data);}).catch(()=>{if(active)setError(pick('Could not load requirements. Reopen this build to retry.','לא ניתן לטעון דרישות. פתחו את הבנייה מחדש לניסיון נוסף.'));});return()=>{active=false;};},[projectId]);
 return <details><summary>{pick('Plan required parts for this kit','תכנון החלקים הנדרשים לערכה')}</summary><p>{pick('Choose a reviewed part and the quantity for this assembly. The total across all kits cannot exceed the build requirement. Set zero to remove a plan before parts are issued.','בחרו חלק שנבדק וכמות להרכבה זו. הסכום בכל הערכות לא יכול לחרוג מדרישת הבנייה. הזינו אפס להסרת תכנון לפני מסירת חלקים.')}</p>{error&&<p role="alert">{error}</p>}<form onChange={()=>setRequest(crypto.randomUUID())} onSubmit={async e=>{e.preventDefault();const selected=rows.find(r=>r.id===line);if(!selected||busy)return;setBusy(true);setError('');try{const r=await supabase.rpc('set_robot_build_kit_requirement',{p_kit:kitId,p_line:line,p_quantity:Number(quantity),p_expected:selected.revision,p_note:note,p_request:request,p_previous_quantity:requirements.find(r=>r.line_id===line)?.quantity??0});if(r.error)throw r.error;await saved();setRequest(crypto.randomUUID());}catch(e){setError((e as {message?:string}).message??pick('Save not confirmed. Retry unchanged values.','השמירה לא אושרה. נסו שוב ללא שינוי.'));}finally{setBusy(false);}}}><fieldset disabled={busy}><label>{pick('Reviewed requirement','דרישה שנבדקה')}<select required value={line} onChange={e=>setLine(e.target.value)}><option value="">{pick('Choose required part','בחרו חלק נדרש')}</option>{rows.filter(r=>r.disposition==='make'?r.job_id:r.inventory_id).map(r=><option key={r.id} value={r.id}>{r.name} · {r.required_quantity}</option>)}</select></label><label>{pick('Pieces for this assembly','יחידות להרכבה זו')}<input type="number" required min={0} max={100000} step={1} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>{pick('Location / drawing reference','מיקום / הפניה לשרטוט')}<input required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button>{busy?pick('Saving…','שומר…'):pick('Save assembly requirement','שמירת דרישת הרכבה')}</button></fieldset></form></details>;
}
