import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
type Spec={material:string;condition:string;shape:string;profile:string;length_mm:number;width_mm:number;thickness_mm:number};
type Plan={id:string;part_id:string;revision:number;required_spec?:Spec|null;consumed:number;reserved?:number};
const empty:Spec={material:'',condition:'',shape:'sheet',profile:'',length_mm:0,width_mm:0,thickness_mm:0};
export default function BuildMaterialSpecs({plan,stockItemId,name,canStock,canManage=false,saved}:{plan?:Plan;stockItemId?:string;name:string;canStock:boolean;canManage?:boolean;saved:()=>Promise<void>}){
 const partId=plan?.part_id??stockItemId;
 const {pick}=useLocalization();const [stock,setStock]=useState<{specification:Spec;revision:number}|null>(null),[spec,setSpec]=useState<Spec>(empty),[required,setRequired]=useState<Spec>(plan?.required_spec??empty),[loaded,setLoaded]=useState(false),[failed,setFailed]=useState(false),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[message,setMessage]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID());
 useEffect(()=>{let live=true;setLoaded(false);setFailed(false);void supabase.from('robot_build_stock_specs').select('specification,revision').eq('part_id',partId).maybeSingle().then(r=>{if(!live)return;if(r.error){setFailed(true);return;}const s=r.data as {specification:Spec;revision:number}|null;setStock(s);setSpec(s?.specification??empty);setRequired(plan?.required_spec??s?.specification??empty);setLoaded(true);});return()=>{live=false;};},[plan?.id,plan?.revision,partId]);
 function fields(value:Spec,set:(s:Spec)=>void){return <div className="build-spec-fields">{(['material','condition','profile'] as const).map(k=><label key={k}>{pick(...({material:['Material / alloy','חומר / סגסוגת'],condition:['Condition / grade','מצב / דרגה'],profile:['Profile / section','פרופיל / חתך']} as Record<string,[string,string]>)[k])}<input required maxLength={120} value={value[k]} onChange={e=>set({...value,[k]:e.target.value})}/></label>)}<label>{pick('Stock form','צורת החומר')}<select value={value.shape} onChange={e=>set({...value,shape:e.target.value})}>{([['sheet','Sheet','לוח'],['bar','Bar','מוט'],['tube','Tube','צינור'],['filament','Filament','פילמנט'],['other','Other','אחר']] as const).map(([id,en,he])=><option key={id} value={id}>{pick(en,he)}</option>)}</select></label>{(['length_mm','width_mm','thickness_mm'] as const).map(k=><label key={k}>{pick(...({length_mm:['Length (mm)','אורך (מ״מ)'],width_mm:['Width / outside size (mm)','רוחב / מידה חיצונית (מ״מ)'],thickness_mm:['Thickness / wall / diameter (mm)','עובי / דופן / קוטר (מ״מ)']} as Record<string,[string,string]>)[k])}<input required type="number" min={0.001} max={1000000} step="any" value={value[k]||''} onChange={e=>set({...value,[k]:Number(e.target.value)})}/></label>)}</div>;}
 async function save(kind:'stock'|'required'){if(busy||!partId||(kind==='required'&&!plan))return;setBusy(true);setMessage('');try{const r=kind==='stock'?await supabase.rpc('save_robot_build_stock_spec',{p_part:partId,p_spec:spec,p_expected:stock?.revision??0,p_note:note,p_request:request}):await supabase.rpc('set_robot_build_material_spec',{p_material:plan?.id,p_required:required,p_expected:plan?.revision,p_note:note,p_request:request});if(r.error)throw r.error;setRequest(crypto.randomUUID());setMessage(pick('Specification saved.','המפרט נשמר.'));await saved();}catch(e){setMessage((e as {message?:string}).message??pick('Save not confirmed. Values retained.','השמירה לא אושרה. הערכים נשמרו.'));}finally{setBusy(false);}}
 return <details><summary>{pick('Material specification','מפרט החומר')} · {name}</summary>{failed?<p role="alert">{pick('Specification could not be loaded. Refresh manufacturing records before editing.','לא ניתן לטעון את המפרט. רעננו רשומות ייצור לפני עריכה.')}</p>:!loaded?<p role="status">{pick('Loading specification…','טוען מפרט…')}</p>:<><p>{pick('Use one stock item for one material, condition, profile and blank size. Different offcut sizes need separate inventory identities. Dimensions do not calculate cutting yield or replace the released drawing.','השתמשו בפריט מלאי אחד לחומר, מצב, פרופיל וגודל גלם אחידים. שאריות בגדלים שונים דורשות זיהוי מלאי נפרד. המידות אינן מחשבות תפוקת חיתוך ואינן מחליפות שרטוט מאושר.')}</p>{stock?<p>{stock.specification.material} · {stock.specification.condition} · {stock.specification.profile} · {stock.specification.length_mm} × {stock.specification.width_mm} × {stock.specification.thickness_mm} mm</p>:<p>{pick('Stock dimensions are not recorded. Unit/quantity checks alone do not prove suitability.','מידות חומר הגלם לא נרשמו. בדיקת יחידה וכמות לבדה אינה מוכיחה התאמה.')}</p>}{canStock&&!stock&&<form onChange={()=>setRequest(crypto.randomUUID())} onSubmit={e=>{e.preventDefault();void save('stock');}}><fieldset disabled={busy}><legend>{pick('Record measured stock specification','רישום מפרט חומר גלם שנמדד')}</legend>{fields(spec,setSpec)}<label>{pick('Supplier or measurement evidence','מקור ספק או ראיות מדידה')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button>{pick('Save stock specification','שמירת מפרט חומר הגלם')}</button></fieldset></form>}{stock&&plan&&canManage&&plan.consumed===0&&!(plan.reserved??0)&&<form onChange={()=>setRequest(crypto.randomUUID())} onSubmit={e=>{e.preventDefault();void save('required');}}><fieldset disabled={busy}><legend>{pick('Required blank from the released instructions','חומר גלם נדרש לפי ההוראות המאושרות')}</legend>{fields(required,setRequired)}<p>{pick('Material, condition, profile and thickness must match exactly. Length and width must fit in the recorded orientation. This records suitability; it does not grant engineering approval.','החומר, המצב, הפרופיל והעובי חייבים להתאים בדיוק. האורך והרוחב חייבים להתאים בכיוון הרשום. הרישום אינו מעניק אישור הנדסי.')}</p><label>{pick('Released drawing / requirement reference','הפניה לשרטוט / דרישה מאושרים')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button>{pick('Confirm compatible material requirement','אישור התאמת דרישת החומר')}</button></fieldset></form>}{plan?.required_spec&&<p>{pick('Recorded required blank','חומר גלם נדרש שנרשם')}: {plan?.required_spec.material} · {plan?.required_spec.length_mm} × {plan?.required_spec.width_mm} × {plan?.required_spec.thickness_mm} mm</p>}<p role="status">{message}</p></>}</details>;
}
