import {useEffect,useRef,useState} from 'react';
import {readBuildPages} from '../lib/robotBuildWorkspace';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
export default function BuildStockActions({lineId,inventoryId,canStock,canBuy}:{lineId:string;inventoryId:string;canStock:boolean;canBuy:boolean}){
 const {pick}=useLocalization();const [allocation,setAllocation]=useState({reserved:0,issued:0,revision:1}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[action,setAction]=useState(canStock?'reserve':'purchase'),[amount,setAmount]=useState('1'),[note,setNote]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID());
 const [existing,setExisting]=useState<{id:string;item_name:string;quantity:number;status:string}[]>([]),[selected,setSelected]=useState('');
 const [unitsPerPack,setUnitsPerPack]=useState('1');
 const generation=useRef(0);
 const [purchases,setPurchases]=useState<{purchase_id:string;quantity:number;units_per_pack:number}[]>([]);
 async function load(){const token=++generation.current;setLoaded(false);try{const [a,p,x]=await Promise.all([
  supabase.from('robot_build_allocations').select('reserved,issued,revision').eq('line_id',lineId).maybeSingle(),
  readBuildPages<{purchase_id:string;quantity:number;units_per_pack:number}>((a,z)=>supabase.from('robot_build_purchases').select('purchase_id,quantity,units_per_pack').eq('line_id',lineId).order('purchase_id').range(a,z)),
  canBuy?readBuildPages<{id:string;item_name:string;quantity:number;status:string}>((a,z)=>supabase.from('frc_purchase_requests').select('id,item_name,quantity,status').eq('part_id',inventoryId).is('source_purchase_id',null).in('status',['requested','approved','ordered']).order('id').range(a,z)):Promise.resolve([])]);
  if(a.error)throw a.error;if(token===generation.current){setAllocation(a.data??{reserved:0,issued:0,revision:1});setPurchases(p);setExisting(x);setLoaded(true);}
 }catch{if(token===generation.current)setMessage(pick('Stock allocations could not be checked. Refresh before changing stock.','לא ניתן לבדוק הקצאות מלאי. רעננו לפני שינוי מלאי.'));}}
 useEffect(()=>{setSelected('');void load();return()=>{generation.current++;};},[lineId,inventoryId,canBuy]);
 return <details><summary>{pick('Stock & purchasing','מלאי ורכש')}</summary><p>{pick('Reserved','מוקצה')}: {allocation.reserved} · {pick('Issued to workshop','נמסר לסדנה')}: {allocation.issued}</p>
 <p>{pick('Issue records a stock withdrawal, not installation or inspection. Return records reusable parts coming back into inventory.','מסירה רושמת הוצאה ממלאי, לא התקנה או בדיקת איכות. החזרה רושמת חלקים שמישים שחוזרים למלאי.')}</p>
 <button type="button" disabled={busy} onClick={()=>void load()}>{pick('Refresh allocation','רענון ההקצאה')}</button>
 {(canStock||canBuy)&&<form onSubmit={async e=>{e.preventDefault();if(!loaded||busy)return;setBusy(true);setMessage('');try{const r=action==='purchase'?await supabase.rpc('request_robot_build_pack_purchase',{p_line:lineId,p_packs:Number(amount),p_units_per_pack:Number(unitsPerPack),p_request:request}):await supabase.rpc('move_robot_build_stock',{p_line:lineId,p_action:action,p_amount:Number(amount),p_expected:allocation.revision,p_note:note,p_request:request});if(r.error)throw Error(r.error.message);await load();setRequest(crypto.randomUUID());setMessage(pick('Recorded successfully.','נרשם בהצלחה.'));}catch(e){setMessage(e instanceof Error?e.message:pick('Save not confirmed. Retry unchanged values or refresh.','השמירה לא אושרה. נסו שוב ללא שינוי או רעננו.'));}finally{setBusy(false);}}}><fieldset disabled={busy||!loaded}>
 <label>{pick('Action','פעולה')}<select value={action} onChange={e=>{setAction(e.target.value);setRequest(crypto.randomUUID());}}><option disabled={!canStock} value="reserve">{pick('Reserve available parts','הקצאת חלקים זמינים')}</option><option disabled={!canStock} value="release">{pick('Release reservation','שחרור הקצאה')}</option><option disabled={!canStock} value="issue">{pick('Issue reserved parts','מסירת חלקים שהוקצו')}</option><option disabled={!canStock} value="return">{pick('Return issued parts','החזרת חלקים שנמסרו')}</option><option disabled={!canBuy} value="purchase">{pick('Request purchase','בקשת רכש')}</option></select></label>
 <label>{action==='purchase'?pick('Number of packs (use 1 piece per pack for individual items)','מספר אריזות (בחרו יחידה אחת באריזה לפריטים בודדים)'):pick('Quantity for this action (pieces)','כמות לפעולה זו (יחידות)')}<input type="number" required min={1} max={100000} step={1} value={amount} onChange={e=>{setAmount(e.target.value);setRequest(crypto.randomUUID());}}/></label>
 {action==='purchase'&&<><label>{pick('Pieces per pack','יחידות באריזה')}<input required type="number" min={1} max={100000} step={1} value={unitsPerPack} onChange={e=>{setUnitsPerPack(e.target.value);setRequest(crypto.randomUUID());}}/></label><p>{amount} × {unitsPerPack} = <strong>{Number(amount)*Number(unitsPerPack)} {pick('pieces to request','יחידות לבקשה')}</strong>. {pick('Approval and receipt use pieces. Only the last pack may exceed uncovered demand; surplus stays in shared inventory.','אישור וקבלה נרשמים ביחידות. רק האריזה האחרונה יכולה לחרוג מהחוסר; העודף נשאר במלאי המשותף.')}</p></>}
 {action!=='purchase'&&<label>{pick('Reason / storage location','סיבה / מיקום אחסון')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);setRequest(crypto.randomUUID());}}/></label>}
 <button disabled={(action==='purchase'&&!canBuy)||(action!=='purchase'&&!canStock)}>{busy?pick('Saving…','שומר…'):pick('Record action','רישום הפעולה')}</button></fieldset></form>}
 {canBuy&&existing.filter(x=>!purchases.some(p=>p.purchase_id===x.id)).length>0&&<form onSubmit={async e=>{e.preventDefault();if(busy||!selected)return;setBusy(true);try{const r=await supabase.rpc('link_robot_build_purchase',{p_line:lineId,p_purchase:selected,p_request:request});if(r.error)throw Error(r.error.message);await load();setRequest(crypto.randomUUID());setSelected('');setMessage(pick('Existing purchase linked. No duplicate request created.','בקשת הרכש הקיימת קושרה. לא נוצרה בקשה כפולה.'));}catch(e){setMessage(e instanceof Error?e.message:pick('Link not confirmed.','הקישור לא אושר.'));}finally{setBusy(false);}}}><fieldset disabled={busy||!loaded}><legend>{pick('Already requested? Reuse the existing purchase','כבר ביקשתם? קשרו בקשת רכש קיימת')}</legend><label>{pick('Existing request for this component','בקשה קיימת לחלק זה')}<select required value={selected} onChange={e=>{setSelected(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose an existing request','בחירת בקשה קיימת')}</option>{existing.filter(x=>!purchases.some(p=>p.purchase_id===x.id)).map(x=><option key={x.id} value={x.id}>{x.item_name} · {x.quantity} · {x.status}</option>)}</select></label><button>{pick('Link existing request','קישור בקשה קיימת')}</button></fieldset></form>}
 {!!purchases.length&&<ul>{purchases.map(p=><li key={p.purchase_id}>{pick('Requested quantity','כמות שהתבקשה')}: {p.quantity} {pick('pieces','יחידות')}{p.units_per_pack>1?` (${p.quantity/p.units_per_pack} × ${p.units_per_pack})`:''} · <a href={`/tools?tab=purchasing&purchase=${p.purchase_id}`}>{pick('Open existing purchasing workspace','פתיחת סביבת הרכש הקיימת')}</a></li>)}</ul>}
 <p role="status">{message}</p></details>;
}
