import {useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
export default function BuildAdoptWip({job,canManage,saved}:{job:{id:string;revision:number;required_quantity:number;completed_quantity:number;initial_wip_quantity?:number|null;initial_wip_note?:string|null;initial_wip_observed_at?:string|null};canManage:boolean;saved:()=>Promise<void>}){
 const {pick}=useLocalization(),[quantity,setQuantity]=useState('1'),[observed,setObserved]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID());
 if(job.initial_wip_quantity!=null)return <aside><strong>{pick('Existing work recorded at setup','עבודה קיימת שנרשמה בהקמה')}: {job.initial_wip_quantity}</strong><p>{job.initial_wip_note}</p><p>{job.initial_wip_observed_at&&new Date(job.initial_wip_observed_at).toLocaleString(pick('en-GB','he-IL'))} · {pick('Historical baseline; physical inspection is still required. No historic stock use or student contribution was fabricated.','נקודת מוצא היסטורית; עדיין נדרשת בדיקה פיזית. לא נוצרו צריכת מלאי היסטורית או תרומת תלמיד פיקטיביות.')}</p></aside>;
 if(!canManage||job.revision!==1||job.completed_quantity!==0)return null;
 return <details><summary>{pick('Already partly made? Record existing work','כבר יוצר חלקית? רישום עבודה קיימת')}</summary><p>{pick('Use once when adopting pieces made before tracking began. Count completed pieces against this released revision and record unknown history. This creates no accepted stock, material expense or machine qualification.','השתמשו פעם אחת לקליטת חלקים שיוצרו לפני תחילת המעקב. ספרו חלקים שהושלמו מול הגרסה המשוחררת ותעדו היסטוריה חסרה. הפעולה אינה יוצרת מלאי מאושר, הוצאת חומר או הסמכת מכונה.')}</p><form onChange={()=>setRequest(crypto.randomUUID())} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const r=await supabase.rpc('adopt_robot_build_wip',{p_job:job.id,p_quantity:Number(quantity),p_note:note,p_observed:new Date(observed).toISOString(),p_request:request});if(r.error)throw r.error;await saved();}catch(e){setMessage((e as {message?:string}).message??pick('Save not confirmed.','השמירה לא אושרה.'));}finally{setBusy(false);}}}><fieldset disabled={busy}><label>{pick('Existing completed pieces awaiting inspection','חלקים קיימים שהושלמו וממתינים לבדיקה')}<input type="number" required min={1} max={job.required_quantity} step={1} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>{pick('Counted on (local date and time)','מועד הספירה (תאריך ושעה מקומיים)')}<input type="datetime-local" required value={observed} onChange={e=>setObserved(e.target.value)}/></label><label>{pick('Location, revision evidence and missing history','מיקום, ראיות לגרסה והיסטוריה חסרה')}<textarea required minLength={10} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button>{pick('Record initial work — inspection still required','רישום עבודה התחלתית — עדיין נדרשת בדיקה')}</button></fieldset><p role="status">{message}</p></form></details>;
}
