import {useEffect,useRef,useState} from 'react';
import BuildPendingFile from './BuildPendingFile';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useMemberAuth} from '../lib/memberAuth';
import {readBuildPages} from '../lib/robotBuildWorkspace';
type WorkFile={id:string;created_by:string;name:string;revision:string;source_version:string;status:string;sha256:string|null;units:string;shared_with_workers:boolean};
export default function BuildWorkFiles({taskId,canUpload=false}:{taskId:string;canUpload?:boolean}){
 const {pick}=useLocalization(),{profile}=useMemberAuth();
 const [files,setFiles]=useState<WorkFile[]>([]),[release,setRelease]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false);
 const [file,setFile]=useState<File|null>(null),[revision,setRevision]=useState(''),[source,setSource]=useState(''),[units,setUnits]=useState('mm'),[share,setShare]=useState(false),[request,setRequest]=useState(()=>crypto.randomUUID());
 const generation=useRef(0);
 async function load(){const token=++generation.current;const g=await supabase.from('project_review_gates').select('decision_type').eq('task_id',taskId).maybeSingle();if(token!==generation.current)return;if(g.error){setError(pick('Work files could not be loaded.','לא ניתן לטעון קובצי עבודה.'));return;}setRelease(g.data?.decision_type==='released_for_manufacturing');try{const rows=await readBuildPages<WorkFile>((a,z)=>supabase.from('robot_build_files').select('id,created_by,name,revision,source_version,status,sha256,units,shared_with_workers').eq('task_id',taskId).order('id').range(a,z));if(token===generation.current)setFiles(rows);}catch{if(token===generation.current)setError(pick('Work files could not be loaded.','לא ניתן לטעון קובצי עבודה.'));}}
 useEffect(()=>{void load();return()=>{generation.current++;};},[taskId]);
 async function upload(){if(!file||!profile||busy)return;setBusy(true);setError('');try{
  const format=file.name.split('.').pop()?.toLowerCase();if(!format||!['pdf','dxf','step','stl','png','jpg'].includes(format)||!file.size||file.size>20971520)throw Error(pick('Choose PDF, DXF, STEP, STL, PNG or JPG up to 20 MB.','בחרו PDF, DXF, STEP, STL, PNG או JPG עד 20 MB.'));
  const r=await supabase.rpc('prepare_robot_build_file',{p_task:taskId,p_name:file.name,p_revision:revision,p_source:source,p_format:format,p_units:units,p_share:share,p_request:request});if(r.error)throw r.error;
  const uploaded=await supabase.storage.from('robot-build-files').upload(`${profile.id}/${request}`,file,{upsert:false,contentType:'application/octet-stream'});
  if(uploaded.error&&String((uploaded.error as {statusCode?:string}).statusCode)!=='409')throw uploaded.error;
  const final=await supabase.functions.invoke('robot-build-files',{body:{action:'finalize',fileId:request}});if(final.error||final.data?.error)throw Error(final.data?.error||pick('Verification not confirmed. Retry the same file.','האימות לא אושר. נסו שוב עם אותו קובץ.'));
  setRequest(crypto.randomUUID());setFile(null);setOpen(false);await load();
 }catch(e){setError((e as {message?:string}).message??pick('Upload not confirmed. Your form is retained.','ההעלאה לא אושרה. הטופס נשמר.'));}finally{setBusy(false);}}
 if(!release&&!error)return null;
 return <section className="build-work-files"><h3>{pick('Drawings & work files','שרטוטים וקובצי עבודה')}</h3><p>{pick('Use the exact released revision. Uploading a file does not approve it.','השתמשו בגרסה המדויקת ששוחררה. העלאת קובץ אינה מאשרת אותו.')}</p>{error&&<p role="alert">{error} <button onClick={()=>void load()}>{pick('Retry','ניסיון חוזר')}</button></p>}
 {files.map(f=><article key={f.id}><strong>{f.name} · {f.revision}</strong><p>{f.source_version} · {f.units}</p>{f.status==='ready'?<><Link to={`/robot-build/file?id=${f.id}`} target="_blank">{pick('Open verified file','פתיחת קובץ מאומת')}</Link><details><summary>{pick('Evidence details for the release review','פרטי הראיה לביקורת השחרור')}</summary><p>{pick('Fixed source ID','מזהה מקור קבוע')}: <code>build-file:{f.id}</code></p><p>{pick('Review link','קישור לביקורת')}: https://g3-6740.com/robot-build/file?id={f.id}</p><p style={{overflowWrap:'anywhere'}}>SHA-256: {f.sha256}</p></details></>:canUpload&&f.created_by===profile?.id?<BuildPendingFile id={f.id} name={f.name} ownerId={f.created_by} saved={load}/>:<p>{pick('The uploader needs to finish this file.','על מעלה הקובץ להשלים את ההעלאה.')}</p>}</article>)}
 {canUpload&&<><button onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{pick('Add a revision file','הוספת קובץ גרסה')}</button>{open&&<form onChange={()=>setRequest(crypto.randomUUID())} onSubmit={e=>{e.preventDefault();void upload();}}><fieldset disabled={busy}><label>{pick('File · up to 20 MB','קובץ · עד 20 MB')}<input required type="file" accept=".pdf,.dxf,.step,.stl,.png,.jpg" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>{pick('Exact release revision','גרסת שחרור מדויקת')}<input required maxLength={120} value={revision} onChange={e=>setRevision(e.target.value)}/></label><label>{pick('Fixed CAD version or drawing source','גרסת CAD קבועה או מקור השרטוט')}<input required minLength={3} maxLength={240} value={source} onChange={e=>setSource(e.target.value)}/></label><label>{pick('File units','יחידות הקובץ')}<select value={units} onChange={e=>setUnits(e.target.value)}><option value="mm">mm</option><option value="in">in</option><option value="not_applicable">{pick('Not applicable','לא רלוונטי')}</option></select></label><label><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/>{pick('Allow assigned manufacturing workers to download after this file is included in an approved release.','לאפשר למבצעי הייצור שהוקצו להוריד לאחר הכללת הקובץ בשחרור מאושר.')}</label><button disabled={!file}>{busy?pick('Uploading & verifying…','מעלה ומאמת…'):pick('Upload and verify file','העלאה ואימות קובץ')}</button></fieldset></form>}</>}
 </section>;
}
