import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
type Material={id:string;part_id:string;unit:string;planned:number;consumed:number;revision:number};
type Stock={id:string;name:string;unit:string;quantity:number};
export default function BuildManufacturing({job,canManage,canStock,editable,done,saved}:{job:{id:string;revision:number};canManage:boolean;canStock:boolean;editable:boolean;done:boolean;saved:()=>Promise<void>}){
 const {pick}=useLocalization();const [materials,setMaterials]=useState<Material[]>([]),[stock,setStock]=useState<Stock[]>([]),[events,setEvents]=useState<{id:string;action:string;amount:number;note:string;created_at:string}[]>([]),[batch,setBatch]=useState<{id:string;quantity:number;note:string}|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [part,setPart]=useState(''),[planned,setPlanned]=useState('1'),[planNote,setPlanNote]=useState(''),[action,setAction]=useState('operation'),[material,setMaterial]=useState(''),[amount,setAmount]=useState('1'),[note,setNote]=useState(''),[output,setOutput]=useState(''),[batchNote,setBatchNote]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID());
 async function load(){setLoaded(false);try{const [m,s,e,b]=await Promise.all([supabase.from('robot_build_materials').select('*').eq('job_id',job.id),supabase.from('frc_parts_inventory').select('id,name,unit,quantity').eq('archived',false).order('name'),supabase.from('robot_build_work_events').select('id,action,amount,note,created_at').eq('job_id',job.id).order('created_at',{ascending:false}).limit(50),supabase.from('robot_build_batches').select('id,quantity,note').eq('job_id',job.id).maybeSingle()]);if(m.error||s.error||e.error||b.error)throw Error();setMaterials(m.data??[]);setStock(s.data??[]);setEvents(e.data??[]);setBatch(b.data);setLoaded(true);}catch{setMessage(pick('Manufacturing records could not be loaded. Retry.','לא ניתן לטעון רשומות ייצור. נסו שוב.'));}}
 const [open,setOpen]=useState(false);
 useEffect(()=>{if(open)void load();},[job.id,job.revision,open]);
 async function run(fn:()=>PromiseLike<{error:{message:string}|null}>){if(busy)return;setBusy(true);setMessage('');try{const r=await fn();if(r.error)throw Error(r.error.message);await load();setRequest(crypto.randomUUID());setMessage(pick('Recorded successfully.','נרשם בהצלחה.'));await saved();}catch(e){setMessage(e instanceof Error?e.message:pick('Save not confirmed; retry unchanged values.','השמירה לא אושרה; נסו שוב ללא שינוי.'));}finally{setBusy(false);}}
 const chosen=materials.find(m=>m.id===material),existing=materials.find(m=>m.part_id===part),moving=['consume','return_material'].includes(action);
 const actions:Record<string,[string,string]>={operation:['Operation completed','פעולה הושלמה'],scrap:['Scrap reported finished parts','פסילת חלקים שדווחו כמוכנים'],rework:['Record rework','רישום תיקון'],consume:['Consume material','צריכת חומר'],return_material:['Return unused material','החזרת חומר שלא נוצל']};
 return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>{pick('Materials, work log & accepted batch','חומרים, יומן עבודה ואצווה מאושרת')}</summary><p role="status">{message||(!loaded?pick('Loading…','טוען…'):'')}</p><button type="button" disabled={busy} onClick={()=>void load()}>{pick('Refresh manufacturing records','רענון רשומות הייצור')}</button>
 {loaded&&<><h4>{pick('Materials for this job','חומרים לעבודה זו')}</h4>{materials.length?<ul>{materials.map(m=><li key={m.id}>{stock.find(s=>s.id===m.part_id)?.name??m.part_id} · {pick('Planned','מתוכנן')}: {m.planned} {m.unit} · {pick('Consumed','נצרך')}: {m.consumed} {m.unit}</li>)}</ul>:<p>{pick('No material plan recorded.','טרם נרשמה תוכנית חומרים.')}</p>}
 {canManage&&!done&&<details><summary>{pick('Plan or revise material quantity','תכנון או עדכון כמות חומר')}</summary><p>{pick('Enter total material for the batch in the inventory unit. Planning does not withdraw or reserve stock. Include expected waste; record actual use separately.','הזינו כמות כוללת לאצווה ביחידת המלאי. התכנון אינו מוציא או מקצה מלאי. כללו פחת צפוי ורשמו צריכה בפועל בנפרד.')}</p><form onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('plan_robot_build_material',{p_job:job.id,p_part:part,p_quantity:Number(planned),p_expected:existing?.revision??0,p_note:planNote}));}}><fieldset disabled={busy}><label>{pick('Material','חומר')}<select required value={part} onChange={e=>{setPart(e.target.value);const m=materials.find(m=>m.part_id===e.target.value);setPlanned(String(m?.planned??1));}}><option value="">{pick('Choose inventory item','בחירת פריט מלאי')}</option>{stock.map(s=><option key={s.id} value={s.id}>{s.name} ({s.unit})</option>)}</select></label><label>{pick('Total planned quantity','כמות כוללת מתוכננת')}<input type="number" min="0.0001" step="0.0001" max={1000000} required value={planned} onChange={e=>setPlanned(e.target.value)}/></label><label>{pick('Plan / change reason','תוכנית / סיבת שינוי')}<textarea minLength={3} maxLength={2000} required value={planNote} onChange={e=>setPlanNote(e.target.value)}/></label><button>{pick('Save material plan','שמירת תוכנית חומרים')}</button></fieldset></form></details>}
 {editable&&!done&&<form onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('record_robot_build_work',{p_job:job.id,p_action:action,p_material:moving?material:null,p_amount:Number(amount),p_expected:moving?chosen?.revision:job.revision,p_note:note,p_request:request}));}}><fieldset disabled={busy}><legend>{pick('Record workshop activity','רישום פעילות בסדנה')}</legend><label>{pick('Activity','פעילות')}<select value={action} onChange={e=>{setAction(e.target.value);setRequest(crypto.randomUUID());}}>{Object.entries(actions).filter(([id])=>canStock||!['consume','return_material'].includes(id)).map(([id,label])=><option key={id} value={id}>{pick(...label)}</option>)}</select></label>
 {moving&&<label>{pick('Planned material','חומר מתוכנן')}<select required value={material} onChange={e=>{setMaterial(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose material','בחירת חומר')}</option>{materials.map(m=><option key={m.id} value={m.id}>{stock.find(s=>s.id===m.part_id)?.name} ({m.unit})</option>)}</select></label>}
 <label>{moving?pick('Quantity in the material unit','כמות ביחידת החומר'):pick('Number of pieces worked on','מספר חלקים שטופלו')}<input type="number" required min={moving?0.0001:1} step={moving?0.0001:1} max={1000000} value={amount} onChange={e=>{setAmount(e.target.value);setRequest(crypto.randomUUID());}}/></label><label>{pick('What was done, tool / location and result','מה בוצע, כלי / מיקום ותוצאה')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);setRequest(crypto.randomUUID());}}/></label><p>{pick('Operations and rework do not add accepted quantity. Scrap removes pieces from reported finished quantity. Material use includes failed work and is never automatically refunded.','פעולות ותיקונים אינם מוסיפים כמות מאושרת. פסילה מפחיתה מהכמות שדווחה כמוכנה. צריכת חומר כוללת עבודה שנכשלה ואינה מוחזרת אוטומטית.')}</p><button>{pick('Record activity','רישום פעילות')}</button></fieldset></form>}
 {batch?<p>{pick('Accepted batch recorded','אצווה מאושרת נרשמה')}: {batch.quantity} · {batch.note}</p>:done&&canManage&&canStock&&<form onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('receive_robot_build_batch',{p_job:job.id,p_part:output,p_note:batchNote,p_request:request}));}}><fieldset disabled={busy}><legend>{pick('Receive inspected output into inventory','קליטת תוצר שנבדק למלאי')}</legend><label>{pick('Finished component inventory item','פריט המלאי של התוצר')}<select required value={output} onChange={e=>{setOutput(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose confirmed finished part','בחרו חלק מוגמר מאומת')}</option>{stock.filter(s=>s.unit==='pcs').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>{pick('Batch identity & storage location','זיהוי אצווה ומיקום אחסון')}<textarea required minLength={3} maxLength={2000} value={batchNote} onChange={e=>{setBatchNote(e.target.value);setRequest(crypto.randomUUID());}}/></label><button>{pick('Receive accepted batch once','קליטת אצווה מאושרת פעם אחת')}</button></fieldset></form>}
 {!!events.length&&<details><summary>{pick('Recent workshop history','היסטוריית סדנה אחרונה')}</summary><ol>{events.map(e=><li key={e.id}>{new Date(e.created_at).toLocaleString(pick('en-GB','he-IL'))} · {pick(...actions[e.action])} · {e.amount}<p>{e.note}</p></li>)}</ol></details>}</>}
 </details>;
}
