import {useBuildStringDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
import {useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import BuildMaterialSpecs from './BuildMaterialSpecs';
type Material={id:string;part_id:string;unit:string;consumed:number;revision:number};
type Stock={id:string;name:string;unit:string};
export default function BuildRemnants({jobId,materials,stock,saved}:{jobId:string;materials:Material[];stock:Stock[];saved:()=>Promise<void>}){
 const initial=()=>({source:'',target:'',amount:'',note:'',request:crypto.randomUUID()});
 const draft=useBuildStringDraft(`remnant:${jobId}`,initial);const {source,target,amount,note,request}=draft.value;
 const setSource=(value:string)=>draft.change({source:value,request:crypto.randomUUID()});const setTarget=(value:string)=>draft.change({target:value,request:crypto.randomUUID()});const setAmount=(value:string)=>draft.change({amount:value,request:crypto.randomUUID()});const setNote=(value:string)=>draft.change({note:value,request:crypto.randomUUID()});const setRequest=(value:ReturnType<typeof crypto.randomUUID>)=>draft.change({request:value});

 const {pick}=useLocalization();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const m=materials.find(m=>m.id===source),item=stock.find(s=>s.id===target);
 return <details><summary>{pick('Return a measured usable offcut','החזרת שארית שימושית שנמדדה')}</summary><p>{pick('Weigh or measure the recovered material in the same inventory unit. Use a separate inventory item with its actual smaller dimensions. Scrap is not usable stock. This does not restore the original full-size blank.','שקלו או מדדו את החומר שהוחזר באותה יחידת מלאי. השתמשו בפריט נפרד בעל המידות הקטנות בפועל. פסולת אינה מלאי שימושי. פעולה זו אינה מחזירה את חומר הגלם המקורי בגודלו המלא.')}</p><label>{pick('Consumed material','חומר שנצרך')}<select value={source} onChange={e=>{setSource(e.target.value);setTarget('');setRequest(crypto.randomUUID());}}><option value="">{pick('Choose material','בחירת חומר')}</option>{materials.filter(m=>m.consumed>0).map(m=><option key={m.id} value={m.id}>{stock.find(s=>s.id===m.part_id)?.name} · {m.consumed} {m.unit}</option>)}</select></label>{m&&<><label>{pick('Remnant inventory item','פריט מלאי לשארית')}<select value={target} onChange={e=>{setTarget(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose separate stock item','בחירת פריט מלאי נפרד')}</option>{stock.filter(s=>s.id!==m.part_id&&s.unit===m.unit).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><p><Link to="/tools?tab=inventory">{pick('Create a distinct item in existing inventory if needed','יצירת פריט נפרד במלאי הקיים לפי הצורך')}</Link></p></>}{item&&m&&<><BuildMaterialSpecs key={item.id} stockItemId={item.id} name={item.name} canStock saved={async()=>{setTarget('');}}/><form data-build-form={draft.id} onChange={()=>setRequest(crypto.randomUUID())} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const r=await supabase.rpc('record_robot_build_remnant',{p_material:m.id,p_part:item.id,p_amount:Number(amount),p_expected:m.revision,p_note:note,p_request:request});if(r.error)throw r.error;setMessage(pick('Remnant received once; original blank was not refunded.','השארית נקלטה פעם אחת; חומר הגלם המקורי לא הוחזר.'));draft.saved(initial());await saved();}catch(e){setMessage((e as {message?:string}).message??pick('Save not confirmed; values retained.','השמירה לא אושרה; הערכים נשמרו.'));}finally{setBusy(false);}}}><fieldset disabled={busy}><BuildDraftNotice {...draft}/><label>{pick('Measured recovered quantity','כמות שנמדדה להחזרה')} ({m.unit})<input required type="number" min={0.0001} max={m.consumed} step={0.0001} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>{pick('Measurement, condition and storage location','מדידה, מצב ומיקום אחסון')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button>{pick('Receive measured remnant','קליטת שארית שנמדדה')}</button></fieldset></form></>}<p role="status">{message}</p></details>;
}
