import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
export default function BuildDemandReview({line,bom,revision,candidates,saved}:{line:string;bom:string;revision:number;candidates:{id:string;name:string;required_quantity:number}[];saved:()=>Promise<void>}){
 const {pick}=useLocalization();const [peers,setPeers]=useState<string[]|null>(null),[current,setCurrent]=useState(false),[decision,setDecision]=useState('independent'),[target,setTarget]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[open,setOpen]=useState(false);
 useEffect(()=>{if(!open)return;let active=true;void supabase.rpc('robot_build_reconciliation_context',{p_bom:bom,p_line:line}).then(({data,error})=>{if(!active)return;if(error){setMessage(pick('Could not check overlapping requirements. Refresh the project.','לא ניתן לבדוק דרישות חופפות. רעננו את הפרויקט.'));return;}const row=data?.find((x:{id:string})=>x.id===line);if(row){setPeers(row.peers);setCurrent(row.current);setDecision(row.decision??(row.peers.length?'additional':'independent'));}});return()=>{active=false;};},[line,bom,revision,open]);
 return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>{current?pick('Demand scope reviewed','היקף הדרישה נבדק'):pick('Review demand & revision overlaps','בדיקת היקף הדרישה וחפיפות בין גרסאות')}</summary>
 <p>{pick('An updated CAD import does not replace existing work. Confirm whether this is additional work or already covered. Manufacturing and stock history stay intact.','ייבוא CAD מעודכן אינו מחליף עבודה קיימת. אשרו אם זו עבודה נוספת או דרישה שכבר מכוסה. היסטוריית הייצור והמלאי נשמרת.')}</p>
 {peers&&<p>{pick('Potential overlaps','חפיפות אפשריות')}: {peers.length}. {peers.map(id=>candidates.find(c=>c.id===id)?.name??pick('Another source — ask its owner to share it','מקור נוסף — בקשו מבעליו לשתף אותו')).join(' · ')}</p>}
 <form onSubmit={async e=>{e.preventDefault();if(busy||!peers)return;setBusy(true);try{const r=await supabase.rpc('reconcile_robot_build_line',{p_line:line,p_expected:revision,p_decision:decision,p_target:decision==='covered'?target:null,p_peers:peers,p_note:note});if(r.error)throw Error(r.error.message);await saved();}catch(e){setMessage(e instanceof Error?e.message:pick('Review not saved.','הסקירה לא נשמרה.'));}finally{setBusy(false);}}}><fieldset disabled={busy||!peers}>
 <label>{pick('Demand decision','החלטה על הדרישה')}<select value={decision} onChange={e=>setDecision(e.target.value)}><option disabled={!!peers?.length} value="independent">{pick('Independent requirement','דרישה עצמאית')}</option><option value="additional">{pick('Additional quantity — retain existing work','כמות נוספת — שימור העבודה הקיימת')}</option><option value="covered">{pick('Already covered by another requirement','כבר מכוסה בדרישה אחרת')}</option></select></label>
 {decision==='covered'&&<label>{pick('Covering requirement','הדרישה המכסה')}<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">{pick('Select existing reviewed demand','בחרו דרישה קיימת שנבדקה')}</option>{candidates.filter(c=>c.id!==line&&c.required_quantity>0).map(c=><option key={c.id} value={c.id}>{c.name} · {c.required_quantity}</option>)}</select></label>}
 <label>{pick('Quantity and revision rationale','נימוק לכמות ולגרסה')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button>{pick('Confirm demand scope','אישור היקף הדרישה')}</button></fieldset></form><p role="status">{message}</p></details>;
}
