import {useBuildFormDraft,useBuildStringDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
import {useEffect,useState} from 'react';
import BuildLeaveDialog from './BuildLeaveDialog';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {readBuildPages} from '../lib/robotBuildWorkspace';
import {ReviewRequirements,emptyRequirement,type MilestoneRequirement} from './ReviewRequirements';
type Lot={id:string;task_id:string;quantity:number;status:string;revision:number};
type Stock={id:string;name:string;unit:string};
export default function BuildInspectionLots({job,workerId,projectId,canManage,canStock,done,saved}:{job:{id:string;part_revision:string};workerId?:string;projectId:string;canManage:boolean;canStock:boolean;done:boolean;saved:()=>Promise<void>}){
 const {pick}=useLocalization();
 const [lots,setLots]=useState<Lot[]>([]),[members,setMembers]=useState<{id:string;display_name:string;role:string}[]>([]),[stock,setStock]=useState<Stock[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [creating,setCreating]=useState(false);
 const createInitial=()=>({quantity:'1',reviewer:'',requirements:[emptyRequirement()],request:crypto.randomUUID()});
 const create=useBuildFormDraft(`inspection-create:${job.id}`,createInitial,(v):v is ReturnType<typeof createInitial>=>!!v&&typeof v==='object'&&['quantity','reviewer','request'].every(k=>typeof (v as Record<string,unknown>)[k]==='string')&&Array.isArray((v as {requirements:unknown}).requirements)&&(v as {requirements:unknown[]}).requirements.length<=30&&(v as {requirements:unknown[]}).requirements.every(r=>!!r&&typeof r==='object'&&['requirement','acceptance','method'].every(k=>typeof (r as Record<string,unknown>)[k]==='string')));
 const resultInitial=()=>({selected:'',expected:'0',splitQuantity:'1',action:canStock?'receive':'rework',note:'',part:'',request:crypto.randomUUID()});
 const resultDraft=useBuildStringDraft(`inspection-result:${job.id}`,resultInitial);
 const {quantity,reviewer,requirements}=create.value,{selected,splitQuantity,action,note,part,request}=resultDraft.value;
 const setQuantity=(quantity:string)=>create.change({quantity,request:crypto.randomUUID()}),setReviewer=(reviewer:string)=>create.change({reviewer,request:crypto.randomUUID()}),setRequirements=(requirements:MilestoneRequirement[])=>create.change({requirements,request:crypto.randomUUID()});
 const setSplitQuantity=(splitQuantity:string)=>resultDraft.change({splitQuantity,request:crypto.randomUUID()}),setAction=(action:string)=>resultDraft.change({action,request:crypto.randomUUID()}),setNote=(note:string)=>resultDraft.change({note,request:crypto.randomUUID()}),setPart=(part:string)=>resultDraft.change({part,request:crypto.randomUUID()});
 useEffect(()=>{if(create.restored)setCreating(true);},[create.restored]);
 async function load(){setLoading(true);setError('');try{const [l,m,s]=await Promise.all([
  readBuildPages<Lot>((a,z)=>supabase.from('robot_build_lots').select('id,task_id,quantity,status,revision').eq('job_id',job.id).order('id').range(a,z)),
  canManage?readBuildPages<{id:string;display_name:string;role:string}>((a,z)=>supabase.from('team_members').select('id,display_name,role').eq('active',true).order('id').range(a,z)):Promise.resolve([]),
  canStock?readBuildPages<Stock>((a,z)=>supabase.from('frc_parts_inventory').select('id,name,unit').eq('archived',false).eq('unit','pcs').order('id').range(a,z)):Promise.resolve([])
 ]);setLots(l);setMembers(m);setStock(s);setLoaded(true);}catch{setLoaded(false);setError(pick('Inspection lots could not be loaded. Retry before recording a result.','לא ניתן לטעון אצוות לבדיקה. נסו שוב לפני רישום תוצאה.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[job.id]);
 async function run(call:()=>PromiseLike<{error:{message:string}|null}>,confirmed:()=>void){if(busy)return;setBusy(true);setError('');try{const result=await call();if(result.error)throw result.error;confirmed();await load();await saved();}catch(e){setError((e as {message?:string}).message??pick('Save not confirmed. Retry unchanged values.','השמירה לא אושרה. נסו שוב ללא שינוי.'));}finally{setBusy(false);}}
 const labels:Record<string,[string,string]>={inspection:['Awaiting inspection','ממתין לבדיקה'],rework:['Needs rework','נדרש תיקון'],scrapped:['Scrapped','נפסל'],accepted:['Accepted batch recorded','נרשמה אצווה מאושרת'],held:['On hold','בהמתנה'],split:['Split into smaller lots','פוצלה לאצוות קטנות']};
 const [nextLot,setNextLot]=useState<Lot|null>(null);
 function chooseLot(l:Lot){if(l.id===selected)return;if(note.trim()||part||splitQuantity!=='1'){setNextLot(l);return;}selectLot(l);}
 function selectLot(l:Lot){resultDraft.saved({...resultInitial(),selected:l.id,expected:String(l.revision),action:['rework','held'].includes(l.status)?'inspection':canStock?'receive':'rework'});}
 const lot=lots.find(l=>l.id===selected);
 return <section className="build-inspection-lots">{nextLot&&<BuildLeaveDialog resolve={discard=>{if(discard)selectLot(nextLot);setNextLot(null);}}/>}<header className="build-job-summary"><div><h3>{pick('Inspection lots','אצוות לבדיקה')}</h3><p>{pick('Separate pieces with different outcomes. Only independently approved lots enter stock.','הפרידו חלקים עם תוצאות שונות. רק אצוות שאושרו בבדיקה בלתי תלויה נקלטות למלאי.')}</p></div>{canManage&&!done&&<button type="button" disabled={!loaded||busy} onClick={()=>setCreating(v=>!v)}>{pick('Create inspection lot','יצירת אצווה לבדיקה')}</button>}</header>
 {error&&<p role="alert">{error}</p>}{loading&&<p role="status">{pick("Loading inspection lots…","טוען אצוות לבדיקה…")}</p>}{!loaded&&!loading&&<button onClick={()=>void load()}>{pick('Retry lots','טעינה חוזרת של האצוות')}</button>}
 {loaded&&!lots.length&&<p>{pick('No partial lots yet. You may keep the existing whole-job inspection, or allocate reported pieces to separate inspection lots.','טרם נוצרו אצוות חלקיות. ניתן להמשיך בבדיקת העבודה כולה, או להקצות חלקים שדווחו לאצוות נפרדות.')}</p>}
 {!!lots.length&&<><dl className="build-lot-totals">{Object.entries(labels).filter(([status])=>status!=='split').map(([status,label])=><div key={status}><dt>{pick(...label)}</dt><dd>{lots.filter(l=>l.status===status).reduce((n,l)=>n+l.quantity,0)}</dd></div>)}</dl><p>{pick('Accepted is a historical receipt. Issuing or installing still checks that the release and inspection remain current.','אישור מציין קליטה היסטורית. ניפוק או התקנה עדיין בודקים שהשחרור והבדיקה בתוקף.')}</p><div className="build-queue-list">{lots.map(l=><button type="button" key={l.id} aria-pressed={l.id===selected} onClick={()=>chooseLot(l)}><strong>{l.quantity} · {pick('lot','אצווה')} {l.id.slice(0,8)}</strong><span>{pick(...labels[l.status])}</span></button>)}</div></>}
 {creating&&<form data-build-form={create.id} onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('prepare_robot_build_lot',{p_job:job.id,p_quantity:Number(quantity),p_reviewer:reviewer,p_requirements:requirements,p_request:create.value.request}),()=>{create.saved(createInitial());setCreating(false);});}}><fieldset disabled={busy}><BuildDraftNotice {...create}/><legend>{pick('Define this inspection lot','הגדרת האצווה לבדיקה')}</legend><label>{pick('Pieces in this lot','מספר חלקים באצווה')}<input required type="number" min={1} max={100000} step={1} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>{pick('Independent reviewer','בודק/ת בלתי תלוי/ה')}<select required value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">{pick('Choose reviewer','בחירת בודק/ת')}</option>{members.filter(m=>m.id!==workerId&&['mentor','admin'].includes(m.role)).map(m=><option key={m.id} value={m.id}>{m.display_name}</option>)}</select></label><ReviewRequirements items={requirements} onChange={r=>{setRequirements(r);}} disabled={busy}/><p>{pick('Use physical test criteria. The inspection must reference the released revision','השתמשו בתנאי בדיקה פיזיים. הבדיקה חייבת להתייחס לגרסה ששוחררה')}: {job.part_revision}</p><button>{pick('Prepare lot inspection','הכנת בדיקת האצווה')}</button></fieldset></form>}
 {lot&&<section key={lot.id}><h4>{pick('Selected lot','האצווה שנבחרה')}: {lot.quantity} · {lot.id.slice(0,8)}</h4><Link to={`/robot-build?project=${projectId}&view=work&queue=team&task=${lot.task_id}`}>{pick('Open this lot’s evidence & inspection','פתיחת הראיות ובדיקת האצווה')}</Link>{canManage&&!done&&!['accepted','scrapped','split'].includes(lot.status)&&<form data-build-form={resultDraft.id} onSubmit={e=>{e.preventDefault();void run(()=>action==='split'?supabase.rpc('split_robot_build_lot',{p_lot:lot.id,p_quantity:Number(splitQuantity),p_expected:Number(resultDraft.value.expected),p_note:note,p_request:request}):action==='receive'?supabase.rpc('receive_robot_build_lot',{p_lot:lot.id,p_part:part,p_note:note,p_request:request}):supabase.rpc('record_robot_build_lot',{p_lot:lot.id,p_action:action,p_expected:Number(resultDraft.value.expected),p_note:note,p_request:request}),()=>resultDraft.saved(resultInitial()));}}><fieldset disabled={busy}><BuildDraftNotice {...resultDraft}/><label>{pick('Next action','הפעולה הבאה')}<select value={action} onChange={e=>setAction(e.target.value)}>{lot.status==='inspection'&&<><option value="receive" disabled={!canStock}>{pick('Receive after independent approval','קליטה לאחר אישור בלתי תלוי')}</option><option value="rework">{pick('Mark for rework','סימון לתיקון')}</option></>}{['rework','held'].includes(lot.status)&&<option value="inspection">{pick('Return to inspection','החזרה לבדיקה')}</option>}{lot.status!=='held'&&<option value="hold">{pick('Hold for investigation','המתנה לבירור')}</option>}{lot.quantity>1&&<option value="split">{pick('Split into two smaller lots','פיצול לשתי אצוות קטנות')}</option>}<option value="scrap">{pick('Scrap these pieces','פסילת החלקים')}</option></select></label>{action==='split'&&<><label>{pick('Pieces in the first new lot','מספר החלקים באצווה החדשה הראשונה')}<input required type="number" min={1} max={lot.quantity-1} step={1} value={splitQuantity} onChange={e=>setSplitQuantity(e.target.value)}/></label><p>{pick('The remainder forms the second lot. Both need their own inspection; the original stays in history.','היתרה תהפוך לאצווה השנייה. כל אחת דורשת בדיקה משלה; המקור נשמר בהיסטוריה.')}</p></>}{action==='receive'&&<label>{pick('Finished component inventory item','פריט המלאי של התוצר')}<select required value={part} onChange={e=>setPart(e.target.value)}><option value="">{pick('Choose finished part','בחירת חלק מוגמר')}</option>{stock.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>{pick('Result, reason and storage location','תוצאה, סיבה ומיקום אחסון')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={action==='receive'&&!canStock}>{pick('Record lot result','רישום תוצאת האצווה')}</button></fieldset></form>}</section>}
 </section>;
}
