import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useMemberAuth} from '../lib/memberAuth';
import {readBuildPages} from '../lib/robotBuildWorkspace';
import {ReviewRequirements,emptyRequirement,type MilestoneRequirement} from './ReviewRequirements';
type Prepared={id:string;part_name:string;part_revision:string;quantity:number;release_task_id:string;work_task_id:string;job_id:string|null};
type RequirementLine={id:string;name:string;required_quantity:number;job_id:string|null;disposition:string};
export default function BuildPrepareWork({projectId,onChanged,onDirty,onSaved}:{projectId:string;onChanged:()=>Promise<void>;onDirty:()=>void;onSaved:()=>void}){
 const {pick}=useLocalization();const [open,setOpen]=useState(false),[items,setItems]=useState<Prepared[]>([]),[people,setPeople]=useState<{id:string;display_name:string;role:string}[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false);
 const {profile}=useMemberAuth();
 const draftKey=`g3-build-preparation-draft:${profile?.id}:${projectId}`;
 const [draftLoaded,setDraftLoaded]=useState(false);
 const [lines,setLines]=useState<RequirementLine[]>([]),[line,setLine]=useState('');
 const [name,setName]=useState(''),[revision,setRevision]=useState(''),[instructions,setInstructions]=useState(''),[quantity,setQuantity]=useState('1'),[owner,setOwner]=useState(''),[reviewer,setReviewer]=useState(''),[due,setDue]=useState(''),[requirements,setRequirements]=useState<MilestoneRequirement[]>([emptyRequirement()]),[request,setRequest]=useState(()=>crypto.randomUUID());
 useEffect(()=>{try{const d=JSON.parse(sessionStorage.getItem(draftKey)??'null');if(d&&['name','revision','instructions','quantity','owner','reviewer','due','request'].every(k=>typeof d[k]==='string')&&Array.isArray(d.requirements)&&d.requirements.length<=30&&d.requirements.every((r:unknown)=>r!==null&&typeof r==='object'&&['requirement','acceptance','method'].every(k=>typeof (r as Record<string,unknown>)[k]==='string'))){setLine(typeof d.line==='string'?d.line:'');setName(d.name);setRevision(d.revision);setInstructions(d.instructions);setQuantity(d.quantity);setOwner(d.owner);setReviewer(d.reviewer);setDue(d.due);setRequirements(d.requirements);setRequest(d.request);setOpen(true);onDirty();}}catch{}setDraftLoaded(true);},[draftKey]);
 useEffect(()=>{if(!draftLoaded)return;try{if(name||revision||instructions||owner||reviewer||due)sessionStorage.setItem(draftKey,JSON.stringify({line,name,revision,instructions,quantity,owner,reviewer,due,requirements,request}));else sessionStorage.removeItem(draftKey);}catch{setError(pick('Draft storage is unavailable. Keep this form open until saved.','אחסון הטיוטה אינו זמין. השאירו את הטופס פתוח עד השמירה.'));}},[draftLoaded,draftKey,line,name,revision,instructions,quantity,owner,reviewer,due,requirements,request]);
 async function load(){try{const [prepared,members]=await Promise.all([readBuildPages<Prepared>((a,z)=>supabase.from('robot_build_preparations').select('id,part_name,part_revision,quantity,release_task_id,work_task_id,job_id').eq('project_id',projectId).order('id').range(a,z)),readBuildPages<{id:string;display_name:string;role:string}>((a,z)=>supabase.from('team_members').select('id,display_name,role').eq('active',true).order('id').range(a,z))]);const boms=await readBuildPages<{id:string;shared_at:string|null}>((a,z)=>supabase.from('robot_build_boms').select('id,shared_at').eq('project_id',projectId).order('id').range(a,z));const available:RequirementLine[]=[];const shared=boms.filter(b=>b.shared_at).map(b=>b.id);for(let i=0;i<shared.length;i+=100)available.push(...await readBuildPages<RequirementLine>((a,z)=>supabase.from('robot_build_bom_lines').select('id,name,required_quantity,job_id,disposition').in('bom_id',shared.slice(i,i+100)).eq('disposition','make').order('id').range(a,z)));setLines(available.filter(l=>!l.job_id));setItems(prepared);setPeople(members);setLoaded(true);}catch{setError(pick('Work preparation is unavailable. Existing jobs remain available below.','הכנת העבודה אינה זמינה. העבודות הקיימות זמינות בהמשך.'));}}
 useEffect(()=>{void load();},[projectId]);
 async function run(fn:()=>PromiseLike<{error:{message:string}|null}>,done:()=>void){if(busy)return;setBusy(true);setError('');try{const r=await fn();if(r.error)throw r.error;done();await load();await onChanged();}catch(e){setError((e as {message?:string}).message??pick('Save was not confirmed. Your form is retained.','השמירה לא אושרה. הטופס נשמר.'));}finally{setBusy(false);}}
 return <section className="build-prepare"><h3>{pick('Prepare manufacturing work','הכנת עבודת ייצור')}</h3><p>{pick('Define the worker, reviewer and acceptance criteria here. The existing release and inspection checkpoints are created together; manufacturing still requires an approved revision.','הגדירו כאן מבצע, בודק ותנאי קבלה. נקודות הביקורת הקיימות לשחרור ולבדיקה נוצרות יחד; תחילת ייצור עדיין מחייבת גרסה מאושרת.')}</p>
 {error&&<p role="alert">{error}</p>}{!loaded?<button onClick={()=>void load()}>{pick('Retry preparation','ניסיון חוזר')}</button>:<>
 {items.map(p=><article className="build-prepared-row" key={p.id}><strong>{p.part_name} · {p.part_revision} · {p.quantity}</strong><div className="build-work-actions"><Link to={`/robot-build?project=${projectId}&view=work&task=${p.release_task_id}&queue=team`}>{pick('Open release review','פתיחת ביקורת השחרור')}</Link><Link to={`/robot-build?project=${projectId}&view=work&task=${p.work_task_id}&queue=team`}>{pick('Open manufacturing & inspection','פתיחת ייצור ובדיקה')}</Link>{!p.job_id&&<button disabled={busy} onClick={()=>void run(()=>supabase.rpc('start_robot_build_preparation',{p_preparation:p.id}),()=>{})}>{pick('Start after release approval','התחלה לאחר אישור השחרור')}</button>}</div></article>)}
 <button type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{pick(open?'Hide preparation form':'Prepare new work',open?'הסתרת טופס ההכנה':'הכנת עבודה חדשה')}</button>
 {open&&<form data-legacy-build-form="preparation" onChange={()=>setRequest(crypto.randomUUID())} onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('prepare_robot_build_work',{p_project:projectId,p_line:line||null,p_name:name,p_revision:revision,p_instructions:instructions,p_quantity:Number(quantity),p_owner:owner,p_reviewer:reviewer,p_requirements:requirements,p_due:due?new Date(due+'T12:00:00').toISOString():null,p_request:request}),()=>{onSaved();try{sessionStorage.removeItem(draftKey);}catch{}setOpen(false);setLine('');setName('');setRevision('');setInstructions('');setOwner('');setReviewer('');setDue('');setQuantity('1');setRequirements([emptyRequirement()]);setRequest(crypto.randomUUID());});}}><fieldset disabled={busy}>
 <label>{pick('Build requirement','דרישת הבנייה')}<select value={line} onChange={e=>{setLine(e.target.value);const chosen=lines.find(l=>l.id===e.target.value);if(chosen){setName(chosen.name);setQuantity(String(chosen.required_quantity));}}}><option value="">{pick('Independent task — no parts-list link','משימה עצמאית — ללא קישור לרשימת חלקים')}</option>{lines.map(l=><option key={l.id} value={l.id}>{l.name} · {l.required_quantity}</option>)}</select></label>
 <label>{pick('Part or batch name','שם חלק או אצווה')}<input required maxLength={180} value={name} onChange={e=>setName(e.target.value)}/></label><label>{pick('Exact revision to release','גרסה מדויקת לשחרור')}<input required maxLength={120} value={revision} onChange={e=>setRevision(e.target.value)}/></label><label>{pick('Quantity to make','כמות לייצור')}<input type="number" min={1} max={100000} step={1} required value={quantity} onChange={e=>setQuantity(e.target.value)}/></label>
 <label>{pick('Instructions for this revision','הוראות לגרסה זו')}<textarea required minLength={3} maxLength={8000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></label>
 <label>{pick('Worker','מבצע/ת')}<select required value={owner} onChange={e=>setOwner(e.target.value)}><option value="">{pick('Choose worker','בחירת מבצע/ת')}</option>{people.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>{pick('Independent reviewer','בודק/ת בלתי תלוי/ה')}<select required value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">{pick('Choose reviewer','בחירת בודק/ת')}</option>{people.filter(p=>['mentor','admin'].includes(p.role)&&p.id!==owner).map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label>
 <label>{pick('Target date (optional)','תאריך יעד (רשות)')}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><ReviewRequirements items={requirements} onChange={value=>{setRequirements(value);setRequest(crypto.randomUUID());}} disabled={busy}/>
 <p>{pick('Attach the exact drawing or design evidence in the release review. Creating this work does not approve the design or certify manufactured parts.','צרפו שרטוט או ראיות תכנון לגרסה המדויקת בביקורת השחרור. יצירת העבודה אינה מאשרת את התכנון או חלקים שיוצרו.')}</p><button>{pick('Create release & inspection workflow','יצירת תהליך שחרור ובדיקה')}</button></fieldset></form>}
 </>}
 </section>;
}
