import {useState} from 'react';import {supabase} from '../supabase';import {useLocalization} from '../lib/localization';
type Operation={id:number;title:string;completed:number};
export default function BuildOperations({job,canManage,editable,saved}:{job:{id:string;revision:number;required_quantity:number;completed_quantity:number;operations?:Operation[]};canManage:boolean;editable:boolean;saved:()=>Promise<void>}){
 const {pick}=useLocalization();const ops=job.operations??[];const [steps,setSteps]=useState(''),[step,setStep]=useState(String(ops.find(s=>s.completed<job.required_quantity)?.id??'')),[quantity,setQuantity]=useState('1'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID());
 async function run(fn:()=>PromiseLike<{error:{message:string}|null}>){if(busy)return;setBusy(true);try{const r=await fn();if(r.error)throw Error(r.error.message);await saved();}catch(e){setMessage(e instanceof Error?e.message:pick('Save not confirmed.','השמירה לא אושרה.'));}finally{setBusy(false);}}
 return <details><summary>{pick('Manufacturing operations','פעולות ייצור')}{ops.length?` · ${ops.filter(s=>s.completed===job.required_quantity).length}/${ops.length}`:''}</summary>
 {!!ops.length&&<p>{pick('Follow the operations in order. A later step cannot report more pieces than the preceding step.','בצעו את הפעולות לפי הסדר. לא ניתן לדווח בשלב מאוחר יותר על יותר יחידות מהשלב הקודם.')}</p>}{!!ops.length&&<ol>{ops.map(s=><li key={s.id}>{s.title} · {s.completed}/{job.required_quantity}</li>)}</ol>}
 {canManage&&job.completed_quantity===0&&ops.every(s=>s.completed===0)&&<form onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('set_robot_build_operations',{p_job:job.id,p_expected:job.revision,p_steps:steps.split('\n').map(s=>s.trim()).filter(Boolean)}));}}><fieldset disabled={busy}><legend>{pick('Set the process before starting work','הגדירו תהליך לפני תחילת העבודה')}</legend><label>{pick('Starting template','תבנית התחלתית')}<select defaultValue="" onChange={e=>{const templates:Record<string,string>={cut:pick('Prepare stock and fixture\nCut or machine to released drawing\nDeburr and clean','הכנת חומר וקיבוע\nחיתוך או עיבוד לפי שרטוט משוחרר\nהסרת גרדים וניקוי'),print:pick('Verify material and released print file\nPrint and record the result\nRemove supports and finish','אימות חומר וקובץ הדפסה משוחרר\nהדפסה ורישום התוצאה\nהסרת תמיכות וגימור'),assembly:pick('Check parts and hardware\nAssemble to released instructions\nCheck fastening and free movement','בדיקת חלקים ומחברים\nהרכבה לפי הוראות משוחררות\nבדיקת חיבורים ותנועה חופשית')};setSteps(templates[e.target.value]??'');}}><option value="">{pick('Custom process','תהליך מותאם')}</option><option value="cut">{pick('Cutting / machining','חיתוך / עיבוד')}</option><option value="print">{pick('3D printing','הדפסת תלת-ממד')}</option><option value="assembly">{pick('Bench assembly','הרכבה בשולחן עבודה')}</option></select></label><label>{pick('One operation per line — edit to match the released instructions','פעולה אחת בכל שורה — התאימו להוראות המשוחררות')}<textarea required value={steps} onChange={e=>setSteps(e.target.value)}/></label><p>{pick('These are process steps, not machine settings or approval. Follow workshop supervision and the released drawing. Final QC remains independent.','אלו שלבי תהליך, לא הגדרות מכונה או אישור עבודה. פעלו לפי הפיקוח בסדנה והשרטוט המשוחרר. בדיקת האיכות הסופית נשארת נפרדת.')}</p><button>{pick('Save process','שמירת תהליך')}</button></fieldset></form>}
 {editable&&ops.some(s=>s.completed<job.required_quantity)&&<form onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('record_robot_build_operation',{p_job:job.id,p_step:Number(step),p_quantity:Number(quantity),p_expected:job.revision,p_note:note,p_request:request}));}}><fieldset disabled={busy}><label>{pick('Completed operation','פעולה שבוצעה')}<select required value={step} onChange={e=>{setStep(e.target.value);setRequest(crypto.randomUUID());}}><option value="">{pick('Choose operation','בחירת פעולה')}</option>{ops.filter(s=>s.completed<job.required_quantity).map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>{pick('Additional pieces completed','יחידות נוספות שהושלמו')}<input type="number" required min={1} max={job.required_quantity} step={1} value={quantity} onChange={e=>{setQuantity(e.target.value);setRequest(crypto.randomUUID());}}/></label><label>{pick('Result and evidence note','תוצאה והערת ראיות')}<textarea required minLength={3} maxLength={1800} value={note} onChange={e=>{setNote(e.target.value);setRequest(crypto.randomUUID());}}/></label><button>{pick('Record operation','רישום הפעולה')}</button></fieldset></form>}
 <p role="status">{message}</p></details>;
}
