import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useBuildFormDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
import {readBuildPages} from '../lib/robotBuildWorkspace';
type Scope={id:string;name:string;description:string;revision:number};
type Task={id:string;title:string;status:string;archived:boolean};
type Mapping={subsystem_id:string;task_id:string};
type Readiness={gates:{task_id:string;decision_type:string}[];verified:(id:string)=>boolean;held:(id:string)=>boolean;jobs:{task_id:string;release_task_id:string}[]};
export default function BuildSubsystems({projectId,editable=false,readiness}:{projectId:string;editable?:boolean;readiness?:Readiness}){
 const {pick}=useLocalization();
 const [scopes,setScopes]=useState<Scope[]>([]),[tasks,setTasks]=useState<Task[]>([]),[maps,setMaps]=useState<Mapping[]>([]),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false);
 const initial=()=>({selected:'',name:'',description:'',chosen:[] as string[],expected:0,request:crypto.randomUUID(),newId:crypto.randomUUID()});
 const draft=useBuildFormDraft(`subsystems:${projectId}`,initial,(v):v is ReturnType<typeof initial>=>!!v&&typeof v==='object'&&['selected','name','description','request','newId'].every(k=>typeof (v as Record<string,unknown>)[k]==='string')&&Array.isArray((v as ReturnType<typeof initial>).chosen)&&(v as ReturnType<typeof initial>).chosen.every(x=>typeof x==='string')&&Number.isInteger((v as ReturnType<typeof initial>).expected));
 const {selected,name,description,chosen,expected,request,newId}=draft.value;
 const [search,setSearch]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[pendingSelection,setPendingSelection]=useState<string|null>(null);
 useEffect(()=>{let live=true;setLoading(true);void load(()=>live);return()=>{live=false;};},[projectId]);
 async function load(live=()=>true){try{
  const [s,t]=await Promise.all([
   readBuildPages<Scope>((a,z)=>supabase.from('robot_build_subsystems').select('id,name,description,revision').eq('project_id',projectId).order('id').range(a,z)),
   readBuildPages<Task>((a,z)=>supabase.from('project_tasks').select('id,title,status,archived').eq('project_id',projectId).order('id').range(a,z))]);
  const m:Mapping[]=[];for(let i=0;i<s.length;i+=100)m.push(...await readBuildPages<Mapping>((a,z)=>supabase.from('robot_build_subsystem_tasks').select('subsystem_id,task_id').in('subsystem_id',s.slice(i,i+100).map(x=>x.id)).order('subsystem_id').order('task_id').range(a,z)));
  if(live()){setScopes(s);setTasks(t);setMaps(m);setFailed(false);}return true;
 }catch{if(live())setFailed(true);return false;}finally{if(live())setLoading(false);}}
 function choose(id:string){const row=scopes.find(s=>s.id===id);draft.saved({...initial(),selected:id,name:row?.name??'',description:row?.description??'',chosen:maps.filter(m=>m.subsystem_id===id).map(m=>m.task_id),expected:row?.revision??0});setPendingSelection(null);setMessage('');}
 return <section><h3>{pick('Subsystem coverage','כיסוי לפי מערכת')}</h3>{loading?<p role="status">{pick('Loading…','טוען…')}</p>:<>
  {failed&&<p role="alert">{pick('Coverage could not be refreshed. Reload before editing.','לא ניתן לרענן את הכיסוי. טענו מחדש לפני עריכה.')} <button onClick={()=>void load()}>{pick('Retry','ניסיון חוזר')}</button></p>}
  {!failed&&!scopes.length&&<p>{pick('No subsystem scope is defined. Group existing tasks in Build details; unrecorded work is not assumed complete.','לא הוגדר תחום למערכות. קבצו משימות קיימות בפרטי הבנייה; עבודה שלא נרשמה אינה נחשבת מושלמת.')}</p>}
  {!failed&&scopes.map(s=>{const ids=new Set(maps.filter(m=>m.subsystem_id===s.id).map(m=>m.task_id));const relevant=tasks.filter(t=>ids.has(t.id)&&!t.archived);const releaseIds=new Set([...ids,...(readiness?.jobs.filter(j=>ids.has(j.task_id)).map(j=>j.release_task_id)??[])]);const releases=readiness?.gates.filter(g=>releaseIds.has(g.task_id)&&g.decision_type==='released_for_manufacturing')??[];const tests=readiness?.gates.filter(g=>ids.has(g.task_id)&&['verified_on_robot','competition_ready'].includes(g.decision_type))??[];return <article className="build-job" key={s.id}><strong>{s.name}</strong><p>{s.description}</p><p>{pick('Recorded work completed','עבודה רשומה שהושלמה')}: {relevant.filter(t=>t.status==='done').length} / {relevant.length}</p>{readiness&&<><p>{pick('Current releases','שחרורים עדכניים')}: {releases.filter(g=>readiness.verified(g.task_id)&&!readiness.held(g.task_id)).length} / {releases.length} · {pick('Current physical verification','אימות פיזי עדכני')}: {tests.filter(g=>readiness.verified(g.task_id)&&!readiness.held(g.task_id)).length} / {tests.length}</p>{!tests.length&&<p>{pick('Physical verification coverage is not configured.','לא הוגדר כיסוי של אימות פיזי.')}</p>}</>}</article>;})}
  {!failed&&<p>{pick('Active tasks without a subsystem','משימות פעילות ללא מערכת')}: {tasks.filter(t=>!t.archived&&!maps.some(m=>m.task_id===t.id)).length}. {pick('These counts cover accessible recorded work, not robot readiness certification. Shared tasks may appear in multiple subsystems and are not added together.','הספירה כוללת עבודה רשומה ונגישה ואינה אישור למוכנות הרובוט. משימות משותפות עשויות להופיע בכמה מערכות ואינן מחוברות לסכום כולל.')}</p>}
  {editable&&<form data-build-form={draft.id} onChange={()=>{draft.change({request:crypto.randomUUID()});setMessage('');}} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const r=await supabase.rpc('save_robot_build_subsystem',{p_project:projectId,p_subsystem:selected||newId,p_expected:expected,p_name:name,p_description:description,p_tasks:chosen,p_request:request});if(r.error)throw r.error;draft.saved({...draft.value,selected:selected||newId,expected:expected+1,request:crypto.randomUUID()});if(!await load())throw Error(pick('Saved, but refresh failed. Retry loading before further edits.','נשמר, אך הרענון נכשל. נסו לטעון לפני עריכה נוספת.'));setMessage(pick('Subsystem scope saved. Existing tasks and approvals were preserved.','תחום המערכת נשמר. המשימות והאישורים הקיימים נשמרו.'));}catch(e){setMessage((e as {message?:string}).message??pick('Save not confirmed.','השמירה לא אושרה.'));}finally{setBusy(false);}}}><BuildDraftNotice restored={draft.restored} storageError={draft.storageError}/>{pendingSelection!==null&&<div role="alert"><p>{pick('Discard unfinished subsystem changes before switching?','למחוק שינויים שלא נשמרו לפני מעבר למערכת אחרת?')}</p><button type="button" onClick={()=>setPendingSelection(null)}>{pick('Keep editing','המשך עריכה')}</button><button type="button" onClick={()=>choose(pendingSelection)}>{pick('Discard and switch','מחיקה ומעבר')}</button></div>}<fieldset disabled={busy||failed||pendingSelection!==null}><legend>{pick('Group existing work','קיבוץ עבודה קיימת')}</legend><label>{pick('Subsystem','מערכת')}<select value={selected} onChange={e=>{e.stopPropagation();if(draft.dirty)setPendingSelection(e.target.value);else choose(e.target.value);}}><option value="">{pick('New subsystem','מערכת חדשה')}</option>{scopes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>{pick('Name','שם')}<input required minLength={2} maxLength={100} value={name} onChange={e=>draft.change({name:e.target.value})}/></label><label>{pick('Scope and verification expectations','תחום העבודה וציפיות האימות')}<textarea required minLength={3} maxLength={2000} value={description} onChange={e=>draft.change({description:e.target.value})}/></label><label>{pick('Find existing tasks','חיפוש משימות קיימות')}<input type="search" value={search} onChange={e=>{e.stopPropagation();setSearch(e.target.value);}}/></label><div style={{maxHeight:280,overflowY:'auto'}}>{tasks.filter(t=>!t.archived&&t.title.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(t=><label key={t.id}><input type="checkbox" checked={chosen.includes(t.id)} onChange={e=>draft.change({chosen:e.target.checked?[...chosen,t.id]:chosen.filter(id=>id!==t.id)})}/>{t.title}</label>)}</div><p>{pick('Selected tasks','משימות שנבחרו')}: {chosen.length}</p><button>{pick('Save subsystem scope','שמירת תחום המערכת')}</button></fieldset><p role="status">{message}</p></form>}
  {!editable&&<Link to={`/robot-build?project=${projectId}&view=details`}>{pick('Review subsystem scope','בדיקת תחום המערכות')}</Link>}
 </>}</section>;
}
