import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useAccessControl} from '../lib/accessControl';
import {readBuildPages} from '../lib/robotBuildWorkspace';
import {useBuildStringDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
type Bom={id:string;name:string;revision:number;snapshot_id:string|null};
type Plan={id:string;name:string;revision:number};
type Ref={id:string;bom_id:string;bom_revision:number;plan_id:string;plan_revision:number;note:string};
type Check={bom_id:string;checked_at:string|null;error:string|null;reference_type:string|null;current_microversion:string|null;pinned_microversion:string|null};
export default function BuildSimulationReferences({projectId,editable}:{projectId:string;editable:boolean}){
 const {pick}=useLocalization(),access=useAccessControl(),allowed=access.can('view_field_twin');
 const initial=()=>({bom:'',plan:'',note:'',request:crypto.randomUUID()}),draft=useBuildStringDraft(`build-simulation:${projectId}`,initial);
 const [boms,setBoms]=useState<Bom[]>([]),[plans,setPlans]=useState<Plan[]>([]),[refs,setRefs]=useState<Ref[]>([]),[checks,setChecks]=useState<Check[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let live=true;if(!allowed){setLoading(false);return;}setLoading(true);setError('');void(async()=>{
  const b=await readBuildPages<Bom>((a,z)=>supabase.from('robot_build_boms').select('id,name,revision,snapshot_id').eq('project_id',projectId).order('id').range(a,z));
  const p=await readBuildPages<Plan>((a,z)=>supabase.from('engineering_plans').select('id,name,revision').order('id').range(a,z));
  const r=await readBuildPages<Ref>((a,z)=>supabase.from('robot_build_simulation_references').select('id,bom_id,bom_revision,plan_id,plan_revision,note').eq('project_id',projectId).order('created_at',{ascending:false}).order('id').range(a,z));
  const c:Check[]=[];for(let i=0;i<b.length;i+=100){const response=await supabase.from('robot_build_source_checks').select('bom_id,checked_at,error,reference_type,current_microversion,pinned_microversion').in('bom_id',b.slice(i,i+100).map(x=>x.id));if(response.error)throw response.error;c.push(...response.data);}
  if(live){setBoms(b.filter(x=>x.snapshot_id));setPlans(p);setRefs(r);setChecks(c);}
 })().catch(()=>{if(live)setError(pick('Simulation references could not be loaded.','לא ניתן לטעון ייחוסי סימולציה.'));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[projectId,allowed,reload]);
 if(!allowed)return null;
 return <section className="build-operation-learning"><h3>{pick('Simulation plans for this build','תוכניות סימולציה לבנייה זו')}</h3><p>{pick('Link an existing saved plan to the CAD parts list it was checked against. This records assumptions, not calibration or real-world validation. CAD changes never overwrite the plan.','קשרו תוכנית שמורה לרשימת חלקי CAD שמולה נבדקה. זה תיעוד הנחות, לא כיול או אימות בעולם האמיתי. שינויי CAD אינם מחליפים את התוכנית.')}</p>
 <Link to="/field-twin?activity=engineering">{pick('Open route planning','פתיחת תכנון מסלול')}</Link><button disabled={loading||busy} onClick={()=>setReload(n=>n+1)}>{pick('Refresh references','רענון ייחוסים')}</button>
 {loading?<p role="status">{pick('Loading…','טוען…')}</p>:error?<p role="alert">{error}</p>:<><ul>{refs.map(r=>{const b=boms.find(x=>x.id===r.bom_id),p=plans.find(x=>x.id===r.plan_id),c=checks.find(x=>x.bom_id===r.bom_id),changed=b?.revision!==r.bom_revision||!!(c?.current_microversion&&c.pinned_microversion&&c.current_microversion!==c.pinned_microversion);return <li key={r.id}><strong>{p?.name??pick('Saved plan','תוכנית שמורה')} · v{r.plan_revision}</strong><p>{b?.name??pick('CAD reference unavailable','ייחוס CAD אינו זמין')} · {pick('parts-list revision','גרסת רשימת חלקים')} {r.bom_revision}</p><p role="status">{changed?pick('Review required: CAD or parts-list context changed. Check dimensions, collisions and mechanism assumptions before using this plan.','נדרשת סקירה: ה-CAD או רשימת החלקים השתנו. בדקו מידות, התנגשויות והנחות מנגנונים לפני השימוש.'):!c?.checked_at||c.error?pick('CAD freshness is unconfirmed. Check the source in Parts before relying on this link.','עדכניות ה-CAD לא אושרה. בדקו את המקור בחלקים לפני הסתמכות על הקישור.'):pick('No difference reported at the last source check. Simulation assumptions still require engineering review.','לא דווח הבדל בבדיקת המקור האחרונה. הנחות הסימולציה עדיין דורשות סקירה הנדסית.')}{p&&p.revision!==r.plan_revision?' '+pick('A newer saved plan exists; this link preserves the earlier revision.','קיימת תוכנית שמורה חדשה יותר; הקישור משמר את הגרסה הקודמת.'):''}</p><p>{r.note}</p><Link to={`/field-twin?activity=engineering&plan=${r.plan_id}&revision=${r.plan_revision}`}>{pick('Open this plan revision','פתיחת גרסת תוכנית זו')}</Link></li>;})}</ul>{!refs.length&&<p>{pick('No simulation plan linked yet.','טרם קושרה תוכנית סימולציה.')}</p>}</>}
 {editable&&!error&&<details><summary>{pick('Link a saved plan','קישור תוכנית שמורה')}</summary><form data-build-form={draft.id} onSubmit={async e=>{e.preventDefault();const b=boms.find(b=>b.id===draft.value.bom),p=plans.find(p=>p.id===draft.value.plan);if(!b||!p||busy)return;setBusy(true);try{const result=await supabase.rpc('link_robot_build_simulation',{p_project:projectId,p_bom:b.id,p_expected:b.revision,p_plan:p.id,p_revision:p.revision,p_note:draft.value.note,p_request:draft.value.request});if(result.error)throw result.error;draft.saved(initial());setReload(n=>n+1);setMessage(pick('Reference saved. No simulation settings or physical evidence changed.','הייחוס נשמר. לא שונו הגדרות סימולציה או ראיות פיזיות.'));}catch(e){setMessage((e as {message?:string}).message??'Save failed');}finally{setBusy(false);}}}><fieldset disabled={busy||loading}><BuildDraftNotice {...draft}/><label>{pick('Imported CAD parts list','רשימת חלקי CAD מיובאת')}<select required value={draft.value.bom} onChange={e=>draft.change({bom:e.target.value,request:crypto.randomUUID()})}><option value="">{pick('Choose source','בחירת מקור')}</option>{boms.map(b=><option key={b.id} value={b.id}>{b.name} · v{b.revision}</option>)}</select></label><label>{pick('Saved simulation plan','תוכנית סימולציה שמורה')}<select required value={draft.value.plan} onChange={e=>draft.change({plan:e.target.value,request:crypto.randomUUID()})}><option value="">{pick('Choose plan','בחירת תוכנית')}</option>{plans.filter(p=>p.revision>0).map(p=><option key={p.id} value={p.id}>{p.name} · v{p.revision}</option>)}</select></label><label>{pick('Assumptions checked and known differences','הנחות שנבדקו והבדלים ידועים')}<textarea required minLength={3} maxLength={2000} value={draft.value.note} onChange={e=>draft.change({note:e.target.value,request:crypto.randomUUID()})}/></label><button>{pick('Save reference','שמירת ייחוס')}</button></fieldset></form></details>}<p role="status">{message}</p></section>;
}
