import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
export default function BuildStockActions({lineId,canStock,canBuy}:{lineId:string;canStock:boolean;canBuy:boolean}){
 const {pick}=useLocalization();const [allocation,setAllocation]=useState({reserved:0,issued:0,revision:1}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[action,setAction]=useState(canStock?'reserve':'purchase'),[amount,setAmount]=useState('1'),[note,setNote]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID());
 const [purchases,setPurchases]=useState<{purchase_id:string;quantity:number}[]>([]);
 async function load(){setLoaded(false);try{const [a,p]=await Promise.all([supabase.from('robot_build_allocations').select('reserved,issued,revision').eq('line_id',lineId).maybeSingle(),supabase.from('robot_build_purchases').select('purchase_id,quantity').eq('line_id',lineId)]);if(a.error||p.error)throw Error();setAllocation(a.data??{reserved:0,issued:0,revision:1});setPurchases(p.data??[]);setLoaded(true);}catch{setMessage(pick('Stock allocations could not be checked. Refresh before changing stock.','לא ניתן לבדוק הקצאות מלאי. רעננו לפני שינוי מלאי.'));}}
 useEffect(()=>{void load();},[lineId]);
 return <details><summary>{pick('Stock & purchasing','מלאי ורכש')}</summary><p>{pick('Reserved','מוקצה')}: {allocation.reserved} · {pick('Issued to workshop','נמסר לסדנה')}: {allocation.issued}</p>
 <p>{pick('Issue records a stock withdrawal, not installation or inspection. Return records reusable parts coming back into inventory.','מסירה רושמת הוצאה ממלאי, לא התקנה או בדיקת איכות. החזרה רושמת חלקים שמישים שחוזרים למלאי.')}</p>
 <button type="button" disabled={busy} onClick={()=>void load()}>{pick('Refresh allocation','רענון ההקצאה')}</button>
 {(canStock||canBuy)&&<form onSubmit={async e=>{e.preventDefault();if(!loaded||busy)return;setBusy(true);setMessage('');try{const r=action==='purchase'?await supabase.rpc('request_robot_build_purchase',{p_line:lineId,p_quantity:Number(amount),p_request:request}):await supabase.rpc('move_robot_build_stock',{p_line:lineId,p_action:action,p_amount:Number(amount),p_expected:allocation.revision,p_note:note,p_request:request});if(r.error)throw Error(r.error.message);await load();setRequest(crypto.randomUUID());setMessage(pick('Recorded successfully.','נרשם בהצלחה.'));}catch(e){setMessage(e instanceof Error?e.message:pick('Save not confirmed. Retry unchanged values or refresh.','השמירה לא אושרה. נסו שוב ללא שינוי או רעננו.'));}finally{setBusy(false);}}}><fieldset disabled={busy||!loaded}>
 <label>{pick('Action','פעולה')}<select value={action} onChange={e=>{setAction(e.target.value);setRequest(crypto.randomUUID());}}><option disabled={!canStock} value="reserve">{pick('Reserve available parts','הקצאת חלקים זמינים')}</option><option disabled={!canStock} value="release">{pick('Release reservation','שחרור הקצאה')}</option><option disabled={!canStock} value="issue">{pick('Issue reserved parts','מסירת חלקים שהוקצו')}</option><option disabled={!canStock} value="return">{pick('Return issued parts','החזרת חלקים שנמסרו')}</option><option disabled={!canBuy} value="purchase">{pick('Request purchase','בקשת רכש')}</option></select></label>
 <label>{pick('Quantity for this action','כמות לפעולה זו')}<input type="number" required min={1} max={100000} step={1} value={amount} onChange={e=>{setAmount(e.target.value);setRequest(crypto.randomUUID());}}/></label>
 {action!=='purchase'&&<label>{pick('Reason / storage location','סיבה / מיקום אחסון')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);setRequest(crypto.randomUUID());}}/></label>}
 <button disabled={(action==='purchase'&&!canBuy)||(action!=='purchase'&&!canStock)}>{busy?pick('Saving…','שומר…'):pick('Record action','רישום הפעולה')}</button></fieldset></form>}
 {!!purchases.length&&<ul>{purchases.map(p=><li key={p.purchase_id}>{pick('Requested quantity','כמות שהתבקשה')}: {p.quantity} · <a href={`/tools?tab=purchasing`}>{pick('Open existing purchasing workspace','פתיחת סביבת הרכש הקיימת')}</a></li>)}</ul>}
 <p role="status">{message}</p></details>;
}
