import {useEffect,useRef,useState} from 'react';import {supabase} from '../supabase';import {useLocalization} from '../lib/localization';
import {readBuildPages} from '../lib/robotBuildWorkspace';
import BuildKitRequirements from './BuildKitRequirements';
import BuildAdoptInstallation from './BuildAdoptInstallation';
import BuildExistingStock from './BuildExistingStock';
import BuildStockAssembly from './BuildStockAssembly';
import BuildMaintenanceLinks from './BuildMaintenanceLinks';
type Kit={id:string;task_id:string;name:string;configuration_id:string|null;installed_at:string|null;retired_at:string|null;retest_task_id:string|null;requirements_required:boolean;adoption_note?:string|null;stock_output_part_id?:string|null;stock_received_at?:string|null;stock_output_quantity?:number|null};
type Batch={id:string;job_id:string|null;part_id:string;quantity:number;note:string};
export default function BuildKits({projectId,tasks,canManage,canStock}:{projectId:string;tasks:{id:string;title:string;status:string}[];canManage:boolean;canStock:boolean}){
 const {pick}=useLocalization();const [kits,setKits]=useState<Kit[]>([]),[batches,setBatches]=useState<Batch[]>([]),[items,setItems]=useState<{kit_id:string;batch_id:string;quantity:number;revision:number;line_id:string|null}[]>([]),[configs,setConfigs]=useState<{id:string;name:string;revision:string}[]>([]),[eligible,setEligible]=useState<string[]>([]),[retestEligible,setRetestEligible]=useState<string[]>([]),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[message,setMessage]=useState('');
 const [requirements,setRequirements]=useState<{kit_id:string;line_id:string;quantity:number;identity_snapshot:{name:string;job_id:string|null;inventory_id:string|null;disposition:string}}[]>([]),[requirement,setRequirement]=useState('');
 const [task,setTask]=useState(''),[name,setName]=useState(''),[kit,setKit]=useState(''),[batch,setBatch]=useState(''),[action,setAction]=useState('issue'),[quantity,setQuantity]=useState('1'),[configuration,setConfiguration]=useState(''),[replacement,setReplacement]=useState(''),[retest,setRetest]=useState(''),[note,setNote]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID());
 const generation=useRef(0);
 async function load(){const token=++generation.current;setLoaded(false);try{
  const [k,g,c,b]=await Promise.all([
   readBuildPages<Kit>((a,z)=>supabase.from('robot_build_kits').select('*,project_tasks!inner(project_id)').eq('project_tasks.project_id',projectId).order('id').range(a,z)),
   readBuildPages<{task_id:string;decision_type:string}>((a,z)=>supabase.from('project_review_gates').select('task_id,decision_type,project_tasks!inner(project_id)').eq('project_tasks.project_id',projectId).eq('enabled',true).order('task_id').range(a,z)),
   readBuildPages<{id:string;name:string;revision:string}>((a,z)=>supabase.from('project_robot_configurations').select('id,name,revision').eq('project_id',projectId).eq('configuration_kind','as_installed').order('id').range(a,z)),
   readBuildPages<Batch>((a,z)=>supabase.from('robot_build_batches').select('id,job_id,part_id,quantity,note').eq('project_id',projectId).order('id').range(a,z))]);
  const [i,r]=await Promise.all([
   readBuildPages<{kit_id:string;batch_id:string;quantity:number;revision:number;line_id:string|null}>((a,z)=>supabase.from('robot_build_kit_items').select('*,robot_build_kits!inner(project_tasks!inner(project_id))').eq('robot_build_kits.project_tasks.project_id',projectId).order('kit_id').order('batch_id').range(a,z)),
   readBuildPages<{kit_id:string;line_id:string;quantity:number;identity_snapshot:{name:string;job_id:string|null;inventory_id:string|null;disposition:string}}>((a,z)=>supabase.from('robot_build_kit_requirements').select('*,robot_build_kits!inner(project_tasks!inner(project_id))').eq('robot_build_kits.project_tasks.project_id',projectId).order('kit_id').order('line_id').range(a,z))]);
  if(token!==generation.current)return;setRequirements(r);setKits(k);setBatches(b);setItems(i);setEligible(g.filter(g=>g.decision_type==='installed').map(g=>g.task_id));setRetestEligible(g.filter(g=>['verified_on_robot','competition_ready'].includes(g.decision_type)).map(g=>g.task_id));setConfigs(c);setLoaded(true);
 }catch{if(token===generation.current)setMessage(pick('Could not load assembly records. Retry.','לא ניתן לטעון רשומות הרכבה. נסו שוב.'));}}
 useEffect(()=>{setKit('');setBatch('');setRequirement('');void load();return()=>{generation.current++;};},[projectId]);
 async function run(fn:()=>PromiseLike<{error:{message:string}|null}>){if(busy)return;setBusy(true);setMessage('');try{const r=await fn();if(r.error)throw Error(r.error.message);await load();setRequest(crypto.randomUUID());setMessage(pick('Assembly record saved.','רשומת ההרכבה נשמרה.'));}catch(e){setMessage(e instanceof Error?e.message:pick('Save not confirmed. Retry unchanged values.','השמירה לא אושרה. נסו שוב ללא שינוי.'));}finally{setBusy(false);}}
 const selected=kits.find(k=>k.id===kit),item=items.find(i=>i.kit_id===kit&&i.batch_id===batch);const reset=()=>setRequest(crypto.randomUUID());
 return <details open><summary>{pick('Assembly kits & installation','ערכות הרכבה והתקנה')}</summary><p>{pick('Keep inspected batches together for an existing installation task. Installation is recorded against an approved physical configuration; it does not mean the robot has passed its final tests.','רכזו אצוות שנבדקו עבור משימת התקנה קיימת. ההתקנה נרשמת מול תצורה פיזית מאושרת; היא אינה מציינת שהרובוט עבר את הבדיקות הסופיות.')}</p><p role="status">{message||(!loaded?pick('Loading…','טוען…'):'')}</p><button type="button" disabled={busy} onClick={()=>void load()}>{pick('Refresh kits','רענון ערכות')}</button>
 {canManage&&canStock&&<BuildExistingStock tasks={tasks} saved={load}/>}
 {loaded&&<>{kits.map(k=><article className="build-job" key={k.id}><strong>{k.name}</strong><p>{k.stock_received_at?pick('Received into stock — components consumed','התקבל למלאי — הרכיבים נוצלו'):k.stock_output_part_id?pick('Preparing stock assembly','הכנת מכלול למלאי'):k.retired_at?pick('Replaced — historical installation','הוחלפה — התקנה היסטורית'):k.installed_at?pick('Installation recorded; verify current robot tests','ההתקנה נרשמה; בדקו את בדיקות הרובוט העדכניות'):pick('Preparing kit','הכנת הערכה')}</p>{k.requirements_required?<><h4>{pick('Required parts','חלקים נדרשים')}</h4>{requirements.filter(r=>r.kit_id===k.id).length?<ul>{requirements.filter(r=>r.kit_id===k.id).map(r=><li key={r.line_id}>{r.identity_snapshot.name} · {items.filter(i=>i.kit_id===k.id&&i.line_id===r.line_id).reduce((n,i)=>n+i.quantity,0)} / {r.quantity} {pick('issued','נמסרו')}</li>)}</ul>:<p>{pick('Plan the required parts before issuing stock.','הגדירו את החלקים הנדרשים לפני מסירת מלאי.')}</p>}{canManage&&!k.installed_at&&!k.retired_at&&<BuildKitRequirements projectId={projectId} kitId={k.id} requirements={requirements.filter(r=>r.kit_id===k.id)} saved={load}/>}</>:<p>{k.adoption_note?pick('Adopted existing installation — stock history is not reconstructed.','התקנה קיימת שנרשמה — היסטוריית מלאי אינה משוחזרת.'):pick('Historical kit — original recorded contents retained.','ערכה היסטורית — התכולה המקורית נשמרה.')}</p>}<ul>{items.filter(i=>i.kit_id===k.id&&i.quantity>0).map(i=><li key={i.batch_id}>{batches.find(b=>b.id===i.batch_id)?.note??i.batch_id} · {i.quantity}</li>)}</ul><a href={`/projects?project=${projectId}&task=${k.task_id}&review=1`}>{pick('Open installation task & evidence','פתיחת משימת התקנה וראיות')}</a>{k.retest_task_id&&<p><a href={`/projects?project=${projectId}&task=${k.retest_task_id}&review=1`}>{pick('Open required replacement verification','פתיחת בדיקת החלפה נדרשת')}</a></p>}</article>)}
 {canManage&&<><details><summary>{pick('Create kit for installation task','יצירת ערכה למשימת התקנה')}</summary><form onSubmit={e=>{e.preventDefault();void run(()=>supabase.rpc('create_robot_build_kit',{p_task:task,p_name:name,p_request:request}));}}><fieldset disabled={busy}><label>{pick('Installation task','משימת התקנה')}<select required value={task} onChange={e=>{setTask(e.target.value);reset();}}><option value="">{pick('Choose task with installation checkpoint','בחרו משימה עם נקודת ביקורת התקנה')}</option>{tasks.filter(t=>eligible.includes(t.id)&&t.status!=='done'&&!kits.some(k=>k.task_id===t.id)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>{pick('Kit name','שם הערכה')}<input required minLength={3} maxLength={180} value={name} onChange={e=>{setName(e.target.value);reset();}}/></label><button>{pick('Create kit','יצירת ערכה')}</button></fieldset></form></details>
 {!!kits.length&&<form onSubmit={e=>{e.preventDefault();void run(()=>action==='install'?supabase.rpc('install_robot_build_kit',{p_kit:kit,p_configuration:configuration,p_note:note,p_request:request}):action==='replace'?supabase.rpc('replace_robot_build_kit',{p_previous:kit,p_replacement:replacement,p_note:note,p_request:request,p_retest:retest}):supabase.rpc('move_robot_build_kit_requirement',{p_line:selected?.requirements_required?requirement:null,p_kit:kit,p_batch:batch,p_action:action,p_quantity:Number(quantity),p_expected:item?.revision??0,p_note:note,p_request:request}));}}><fieldset disabled={busy}><legend>{pick('Next assembly action','פעולת ההרכבה הבאה')}</legend><label>{pick('Kit','ערכה')}<select required value={kit} onChange={e=>{setKit(e.target.value);setRequirement('');setBatch('');reset();}}><option value="">{pick('Choose kit','בחירת ערכה')}</option>{kits.filter(k=>!k.retired_at).map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select></label><label>{pick('Action','פעולה')}<select value={action} onChange={e=>{setAction(e.target.value);reset();}}><option disabled={!canStock||!!selected?.installed_at} value="issue">{pick('Issue accepted batch into kit','מסירת אצווה מאושרת לערכה')}</option><option disabled={!canStock||!!selected?.installed_at} value="return">{pick('Return unused kit pieces','החזרת חלקים שלא נוצלו')}</option><option disabled={!!selected?.stock_output_part_id} value="install">{pick('Record approved installation','רישום התקנה מאושרת')}</option><option disabled={!selected?.installed_at} value="replace">{pick('Record replacement installation','רישום התקנה חלופית')}</option></select></label>
 {['issue','return'].includes(action)&&<>{selected?.requirements_required&&<label>{pick('Assembly requirement','דרישת הרכבה')}<select required value={requirement} onChange={e=>{setRequirement(e.target.value);setBatch('');reset();}}><option value="">{pick('Choose required part','בחרו חלק נדרש')}</option>{requirements.filter(r=>r.kit_id===kit).map(r=><option key={r.line_id} value={r.line_id}>{r.identity_snapshot.name} · {r.quantity}</option>)}</select></label>}<label>{pick('Accepted batch','אצווה מאושרת')}<select required value={batch} onChange={e=>{setBatch(e.target.value);reset();}}><option value="">{pick('Choose traceable batch','בחרו אצווה מזוהה')}</option>{batches.filter(b=>{if(action==='return')return items.some(i=>i.kit_id===kit&&i.batch_id===b.id&&i.quantity>0&&(!selected?.requirements_required||i.line_id===requirement));if(!selected?.requirements_required)return true;const r=requirements.find(r=>r.kit_id===kit&&r.line_id===requirement)?.identity_snapshot;return r&&(r.disposition==='make'?r.job_id===b.job_id:!b.job_id&&r.inventory_id===b.part_id);}).map(b=><option key={b.id} value={b.id}>{b.note} · {b.quantity}</option>)}</select></label><label>{pick('Pieces','יחידות')}<input type="number" min={1} max={100000} step={1} required value={quantity} onChange={e=>{setQuantity(e.target.value);reset();}}/></label></>}
 {action==='install'&&<label>{pick('Exact installed configuration','תצורת התקנה מדויקת')}<select required value={configuration} onChange={e=>{setConfiguration(e.target.value);reset();}}><option value="">{pick('Choose reviewed configuration','בחרו תצורה שנבדקה')}</option>{configs.map(c=><option key={c.id} value={c.id}>{c.name} · {c.revision}</option>)}</select></label>}
  {action==='replace'&&<><label>{pick('Required robot retest task','משימת בדיקה חוזרת נדרשת')}<select required value={retest} onChange={e=>{setRetest(e.target.value);reset();}}><option value="">{pick('Choose an open verification task','בחרו משימת אימות פתוחה')}</option>{tasks.filter(t=>t.status!=='done'&&retestEligible.includes(t.id)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><p>{pick('Removed parts are not returned to stock automatically. Keep them isolated until separately inspected. Record retests for the new configuration in the existing engineering workflow.','חלקים שהוסרו אינם חוזרים אוטומטית למלאי. שמרו אותם בנפרד עד בדיקה. רשמו בדיקות חוזרות לתצורה החדשה בתהליך ההנדסי הקיים.')}</p><label>{pick('Replacement installed kit','ערכה חלופית שהותקנה')}<select required value={replacement} onChange={e=>{setReplacement(e.target.value);reset();}}><option value="">{pick('Choose approved replacement','בחירת חלופה מאושרת')}</option>{kits.filter(k=>k.id!==kit&&k.installed_at&&!k.retired_at).map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select></label></>}
 <label>{pick('Location, disposition & verification note','מיקום, מצב והערת אימות')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);reset();}}/></label><button disabled={!kit||(['issue','return'].includes(action)&&(!canStock||!!selected?.installed_at))}>{pick('Record assembly action','רישום פעולת הרכבה')}</button></fieldset></form>}</>}
 {canManage&&canStock&&<BuildStockAssembly projectId={projectId} tasks={tasks} kits={kits} saved={load}/>}
 {canManage&&<BuildAdoptInstallation projectId={projectId} tasks={tasks} installTasks={eligible.filter(id=>!kits.some(k=>k.task_id===id))} retestTasks={retestEligible} configurations={configs} saved={load}/>}
 <BuildMaintenanceLinks projectId={projectId} kits={kits} tasks={tasks} canManage={canManage}/></> }</details>;
}
