import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useAccessControl} from '../lib/accessControl';
import {robotPurposes} from '../lib/robotRepositories';
import {readBuildPages} from '../lib/robotBuildWorkspace';
import {useBuildStringDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
type Reference={id:string;repository:string;commit_sha:string;note:string;created_at:string};
export default function BuildSoftwareReferences({projectId,editable}:{projectId:string;editable:boolean}){
 const {pick}=useLocalization(),access=useAccessControl(),allowed=access.can('use_private_robot_code');
 const initial=()=>({repository:'',commit:'',note:'',request:crypto.randomUUID()}),draft=useBuildStringDraft(`build-software:${projectId}`,initial);
 const [rows,setRows]=useState<Reference[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let live=true;if(!allowed){setRows([]);setLoading(false);return;}setLoading(true);setError('');void readBuildPages<Reference>((a,z)=>supabase.from('robot_build_software_references').select('id,repository,commit_sha,note,created_at').eq('project_id',projectId).order('created_at',{ascending:false}).order('id').range(a,z)).then(r=>{if(live)setRows(r);}).catch(()=>{if(live)setError(pick('Software references could not be loaded.','לא ניתן לטעון ייחוסי תוכנה.'));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[projectId,allowed,reload]);
 if(!allowed)return <p>{pick('Build software references require the separate private robot code permission.','ייחוסי תוכנה לבנייה דורשים הרשאה נפרדת לקוד רובוט פרטי.')}</p>;
 return <section className="build-operation-learning"><h3>{pick('Intended robot software','תוכנת הרובוט המיועדת')}</h3><p>{pick('Record the repository and exact commit intended for this build. This is not proof of deployment. Physical test configurations must record the actual deployed software and calibration separately.','רשמו את המאגר והקומיט המדויק המיועדים לבנייה זו. זה אינו אישור שהתוכנה הותקנה. בתצורת בדיקה פיזית יש לתעד בנפרד את התוכנה שהותקנה בפועל ואת הכיול.')}</p>
 {loading?<p role="status">{pick('Loading software references…','טוען ייחוסי תוכנה…')}</p>:error?<p role="alert">{error}<button onClick={()=>setReload(n=>n+1)}>{pick('Retry','ניסיון נוסף')}</button></p>:<><ol>{rows.map((r,i)=><li key={r.id}><strong>{i===0?pick('Latest recorded intent','הכוונה האחרונה שתועדה'):pick('Earlier reference','ייחוס קודם')}</strong><p dir="ltr">{r.repository} · <code>{r.commit_sha}</code></p><p>{r.note}</p><a href={`https://github.com/${r.repository}/tree/${r.commit_sha}`} target="_blank" rel="noreferrer">{pick('Open this exact code revision','פתיחת גרסת הקוד המדויקת')}</a></li>)}</ol>{!rows.length&&<p>{pick('No intended code revision recorded yet.','טרם תועדה גרסת קוד מיועדת.')}</p>}</>}
 {editable&&!error&&<details><summary>{pick('Record a code revision','תיעוד גרסת קוד')}</summary><form data-build-form={draft.id} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{
 const checked=await supabase.functions.invoke('github-repositories',{body:{action:'check-commit',repository:draft.value.repository,commit:draft.value.commit.trim()}});
 if(checked.error||checked.data?.error||checked.data?.revision!==draft.value.commit.trim().toLowerCase())throw Error(pick('This exact commit could not be read. Check the repository and full commit before saving.','לא ניתן לקרוא את הקומיט המדויק. בדקו את המאגר והקומיט המלא לפני שמירה.'));
 const r=await supabase.rpc('record_robot_build_software',{p_project:projectId,p_repository:draft.value.repository,p_commit:draft.value.commit,p_note:draft.value.note,p_request:draft.value.request});if(r.error)throw r.error;draft.saved(initial());setReload(n=>n+1);setMessage(pick('Intended revision recorded. No code was deployed or sent to AI.','הגרסה המיועדת תועדה. לא הותקן קוד ולא נשלח קוד לבינה מלאכותית.'));
 }catch(e){setMessage((e as {message?:string}).message??pick('Save not confirmed.','השמירה לא אושרה.'));}finally{setBusy(false);}}}><fieldset disabled={busy||loading}><BuildDraftNotice {...draft}/><label>{pick('Robot repository','מאגר הרובוט')}<select required value={draft.value.repository} onChange={e=>draft.change({repository:e.target.value,request:crypto.randomUUID()})}><option value="">{pick('Choose by purpose','בחירה לפי מטרה')}</option>{Object.entries(robotPurposes).map(([name,label])=><option key={name} value={'GlueGunAndGlitter/'+name}>{name} · {pick(...label)}</option>)}</select></label><label>{pick('Full commit SHA (40 characters)','SHA מלא של הקומיט (40 תווים)')}<input required dir="ltr" pattern="[a-fA-F0-9]{40}" maxLength={40} value={draft.value.commit} onChange={e=>draft.change({commit:e.target.value,request:crypto.randomUUID()})}/></label><label>{pick('Intended use / reason for changing revision','שימוש מיועד / סיבה לשינוי הגרסה')}<textarea required minLength={3} maxLength={2000} value={draft.value.note} onChange={e=>draft.change({note:e.target.value,request:crypto.randomUUID()})}/></label><button>{busy?pick('Checking code access…','בודק גישה לקוד…'):pick('Check commit & record intent','בדיקת קומיט ותיעוד הכוונה')}</button></fieldset></form></details>}<p role="status">{message}</p></section>;
}
