import {useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {readBuildPages} from '../lib/robotBuildWorkspace';
type Kit={id:string;name:string;installed_at:string|null;retired_at:string|null;configuration_id:string|null;retest_task_id:string|null};
type Impact={reserved:number;issued:number;job:{id:string;task_id:string;release_task_id:string;completed_quantity:number;required_quantity:number}|null;purchases:{purchase_id:string;quantity:number}[];kits:Kit[];accepted:number};
export default function BuildChangeImpact({lineId,jobId,projectId}:{lineId:string;jobId:string|null;projectId:string}){
 const {pick}=useLocalization(),[data,setData]=useState<Impact|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 async function load(){if(busy)return;setBusy(true);setError(false);try{
  const [allocation,purchases,job,batches,planned]=await Promise.all([
   supabase.from('robot_build_allocations').select('reserved,issued').eq('line_id',lineId).maybeSingle(),
   readBuildPages<{purchase_id:string;quantity:number}>((a,z)=>supabase.from('robot_build_purchases').select('purchase_id,quantity').eq('line_id',lineId).order('purchase_id').range(a,z)),
   jobId?supabase.from('robot_build_jobs').select('id,task_id,release_task_id,completed_quantity,required_quantity').eq('id',jobId).maybeSingle():Promise.resolve({data:null,error:null}),
   jobId?readBuildPages<{id:string;quantity:number}>((a,z)=>supabase.from('robot_build_batches').select('id,quantity').eq('job_id',jobId).order('id').range(a,z)):Promise.resolve([]),
   readBuildPages<{kit_id:string}>((a,z)=>supabase.from('robot_build_kit_requirements').select('kit_id').eq('line_id',lineId).order('kit_id').range(a,z))]);
  if(allocation.error||job.error)throw Error();
  const ids=new Set(planned.map(k=>k.kit_id));
  for(let i=0;i<batches.length;i+=100){const rows=await readBuildPages<{kit_id:string}>((a,z)=>supabase.from('robot_build_kit_items').select('kit_id,batch_id').in('batch_id',batches.slice(i,i+100).map(b=>b.id)).order('kit_id').order('batch_id').range(a,z));rows.forEach(r=>ids.add(r.kit_id));}
  const list=[...ids],kits:Kit[]=[];for(let i=0;i<list.length;i+=100)kits.push(...await readBuildPages<Kit>((a,z)=>supabase.from('robot_build_kits').select('id,name,installed_at,retired_at,configuration_id,retest_task_id').in('id',list.slice(i,i+100)).order('id').range(a,z)));
  setData({reserved:allocation.data?.reserved??0,issued:allocation.data?.issued??0,job:job.data,purchases,kits,accepted:batches.reduce((n,b)=>n+b.quantity,0)});
 }catch{setError(true);setData(null);}finally{setBusy(false);}}
 return <section><button type="button" disabled={busy} onClick={()=>void load()}>{busy?pick('Checking affected records…','בודק רשומות מושפעות…'):pick('Review affected work, purchases & installations','בדיקת עבודה, רכש והתקנות מושפעים')}</button>{error&&<p role="alert">{pick('Impact could not be loaded. Do not assume there is no affected work.','לא ניתן לטעון השפעות. אין להניח שאין עבודה מושפעת.')}</p>}{data&&<><p>{pick('This is the recorded impact for this requirement. A newer CAD revision does not cancel orders, withdraw a release or certify older parts as compatible. Decide with the responsible reviewer before changing work.','זוהי ההשפעה הרשומה עבור דרישה זו. גרסת CAD חדשה אינה מבטלת הזמנות, עוצרת שחרור או מאשרת תאימות של חלקים ישנים. החליטו עם הבודק האחראי לפני שינוי העבודה.')}</p><dl><dt>{pick('Reserved / issued pieces for this demand','יחידות מוקצות / שנמסרו לדרישה')}</dt><dd>{data.reserved} / {data.issued}</dd><dt>{pick('Recorded accepted manufacturing output (includes pieces subsequently issued)','תוצר ייצור מאושר שנרשם (כולל חלקים שנמסרו בהמשך)')}</dt><dd>{data.accepted}</dd></dl>{data.job&&<p>{pick('Reported manufacturing','ייצור שדווח')}: {data.job.completed_quantity} / {data.job.required_quantity} · <a href={`/robot-build?project=${projectId}&view=work&task=${data.job.task_id}&queue=team`}>{pick('Open work and release hold','פתיחת העבודה ועצירת השחרור')}</a></p>}<ul>{data.purchases.map(p=><li key={p.purchase_id}><a href={`/tools?tab=purchasing&purchase=${p.purchase_id}`}>{pick('Review linked purchase','בדיקת רכש מקושר')}</a> · {p.quantity} {pick('pieces originally linked; check actual order and receipt status','יחידות שקושרו במקור; בדקו מצב הזמנה וקבלה בפועל')}</li>)}</ul><ul>{data.kits.map(k=><li key={k.id}>{k.name} · {k.retired_at?pick('Retired / consumed','הוצא משימוש / נוצל'):k.installed_at?pick('Installed — review physical configuration and retest','מותקן — בדקו תצורה פיזית ובדיקה חוזרת'):pick('Assembly planned / in progress','הרכבה מתוכננת / בביצוע')} · <a href={`/robot-build?project=${projectId}&view=assembly`}>{pick('Open assembly records','פתיחת רשומות ההרכבה')}</a>{k.retest_task_id&&<> · <a href={`/robot-build?project=${projectId}&view=work&task=${k.retest_task_id}&queue=team`}>{pick('Open required retest','פתיחת בדיקה חוזרת נדרשת')}</a></>}</li>)}</ul><p>{pick('Only accessible linked records are included. Unlinked purchases, spare parts and physical changes need explicit reconciliation. These quantities must not be added together as available stock.','נכללות רק רשומות מקושרות ונגישות. רכש, חלפים ושינויים פיזיים שלא קושרו דורשים התאמה מפורשת. אין לחבר כמויות אלה כאילו היו מלאי זמין.')}</p></>}</section>;
}
