import {useState} from 'react';import {Link} from 'react-router-dom';
import {supabase} from '../supabase';import {useLocalization} from '../lib/localization';
export default function BuildAdoptInstallation({projectId,tasks,installTasks,retestTasks,configurations,saved}:{projectId:string;tasks:{id:string;title:string;status:string}[];installTasks:string[];retestTasks:string[];configurations:{id:string;name:string;revision:string}[];saved:()=>Promise<void>}){
 const {pick}=useLocalization();const [task,setTask]=useState(''),[configuration,setConfiguration]=useState(''),[retest,setRetest]=useState(''),[name,setName]=useState(''),[note,setNote]=useState(''),[request,setRequest]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const changed=()=>setRequest(crypto.randomUUID());
 return <details className="build-adopt"><summary>{pick('Already installed? Register existing hardware','כבר מותקן? רישום חומרה קיימת')}</summary>
 <p>{pick('Use an approved installation checkpoint for the exact physical configuration. No past purchases, stock movements or manufacturing results are created. A separate robot verification task remains required.','השתמשו בנקודת ביקורת התקנה מאושרת לתצורה הפיזית המדויקת. לא נוצרים רכש היסטורי, תנועות מלאי או תוצאות ייצור. עדיין נדרשת משימת אימות רובוט נפרדת.')}</p>
 <form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const r=await supabase.rpc('adopt_robot_build_installation',{p_task:task,p_configuration:configuration,p_retest:retest,p_name:name,p_note:note,p_request:request});if(r.error)throw r.error;setMessage(pick('Existing installation registered. No stock or finance entries were created.','ההתקנה הקיימת נרשמה. לא נוצרו רשומות מלאי או כספים.'));setNote('');setName('');changed();await saved();}catch(e){setMessage((e as {message:string}).message);}finally{setBusy(false);}}}><fieldset disabled={busy}>
 <label>{pick('Existing installation checkpoint','נקודת ביקורת התקנה קיימת')}<select required value={task} onChange={e=>{setTask(e.target.value);changed();}}><option value="">{pick('Choose approved installation task','בחירת משימת התקנה מאושרת')}</option>{tasks.filter(t=>installTasks.includes(t.id)).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label>
 <label>{pick('Exact installed configuration','תצורה מותקנת מדויקת')}<select required value={configuration} onChange={e=>{setConfiguration(e.target.value);changed();}}><option value="">{pick('Choose physical configuration','בחירת תצורה פיזית')}</option>{configurations.map(c=><option value={c.id} key={c.id}>{c.name} · {c.revision}</option>)}</select></label>
 <label>{pick('Required robot verification','אימות רובוט נדרש')}<select required value={retest} onChange={e=>{setRetest(e.target.value);changed();}}><option value="">{pick('Choose open verification task','בחירת משימת אימות פתוחה')}</option>{tasks.filter(t=>t.status!=='done'&&retestTasks.includes(t.id)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>
 <label>{pick('Installed assembly name','שם המכלול המותקן')}<input required minLength={3} maxLength={180} value={name} onChange={e=>{setName(e.target.value);changed();}}/></label>
 <label>{pick('Existing hardware, evidence and history gaps','החומרה הקיימת, הראיות והפערים בהיסטוריה')}<textarea required minLength={10} maxLength={2000} value={note} onChange={e=>{setNote(e.target.value);changed();}}/></label>
 <button>{pick('Register reviewed existing installation','רישום התקנה קיימת שנבדקה')}</button></fieldset></form><p role="status">{message}</p><Link to={`/projects?project=${projectId}`}>{pick('Prepare installation evidence or verification in project tasks','הכנת ראיות התקנה או אימות במשימות הפרויקט')}</Link>
 </details>;
}
