import {useMemo,useState} from 'react';
import {useLocalization} from '../lib/localization';
import {compareBuildRevisions,type RevisionPart} from '../lib/buildRevisionComparison';

export default function BuildRevisionComparison({boms,lines,onSelect}:{boms:{id:string;name:string;snapshot_id:string|null;created_at:string}[];lines:(RevisionPart&{bom_id:string})[];onSelect:(id:string)=>void}){
 const {pick}=useLocalization(),[before,setBefore]=useState(''),[after,setAfter]=useState(''),[all,setAll]=useState(false),[limit,setLimit]=useState(50);
 const imports=boms.filter(b=>b.snapshot_id);
 const changes=useMemo(()=>before&&after&&before!==after?compareBuildRevisions(lines.filter(l=>l.bom_id===before),lines.filter(l=>l.bom_id===after)):[],[before,after,lines]);
 if(imports.length<2)return null;
 const labels:Record<string,[string,string]>={added:['Added','נוסף'],removed:['Removed from candidate','הוסר מהגרסה המועמדת'],changed:['Changed','השתנה'],unchanged:['No detected change','לא זוהה שינוי'],ambiguous:['Identity needs review','נדרשת בדיקת זהות'],quantity:['Quantity','כמות'],name:['Name','שם'],microversion:['CAD revision','גרסת CAD'],status:['Metadata availability','זמינות פרטי חלק'],partNumber:['Part number','מספר חלק'],material:['Material','חומר'],vendor:['Vendor','ספק'],revision:['Part revision','גרסת חלק']};
 const visible=changes.filter(c=>all||c.kind!=='unchanged');
 return <section className="build-revision-comparison" aria-label={pick('Compare imported revisions','השוואת גרסאות שיובאו')}><h3>{pick('What changed in CAD?','מה השתנה ב־CAD?')}</h3>
 <p>{pick('Choose the previous and candidate imports. This comparison does not replace work, release stock or approve compatibility. A CAD revision change flags a review; it does not prove that the shape changed.','בחרו את הייבוא הקודם ואת הייבוא המועמד. ההשוואה אינה מחליפה עבודה, משחררת מלאי או מאשרת תאימות. שינוי בגרסת CAD דורש בדיקה ואינו מוכיח שהצורה השתנתה.')}</p>
 <div className="build-comparison-selectors">{(['before','after'] as const).map(side=><label key={side}>{side==='before'?pick('Previous import','ייבוא קודם'):pick('Candidate import','ייבוא מועמד')}<select value={side==='before'?before:after} onChange={e=>{(side==='before'?setBefore:setAfter)(e.target.value);setLimit(50);}}><option value="">{pick('Choose an import','בחירת ייבוא')}</option>{imports.map(b=><option key={b.id} value={b.id} disabled={b.id===(side==='before'?after:before)}>{b.name} · {new Date(b.created_at).toLocaleString(pick('en-GB','he-IL'))} · {b.id.slice(0,8)}</option>)}</select></label>)}</div>
 {!!changes.length&&<><p role="status">{pick('Changed or unmatched parts','חלקים שהשתנו או ללא התאמה')}: {changes.filter(c=>c.kind!=='unchanged').length} / {changes.length}</p><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>{pick('Include unchanged parts','הצגת חלקים ללא שינוי')}</label>
 <p>{pick('Open an affected part to review its existing job and demand decision. Use the release hold before continuing affected manufacturing. Missing identities are shown separately; parts are never matched by name.','פתחו חלק מושפע כדי לבדוק את העבודה הקיימת ואת החלטת הדרישה. עצרו את השחרור לפני המשך ייצור מושפע. זהויות חסרות מוצגות בנפרד; התאמה לעולם אינה נעשית לפי שם.')}</p>
 <ul className="build-change-list">{visible.slice(0,limit).map(c=><li key={[...c.before,...c.after].map(l=>l.id).join('/')}><strong>{pick(...labels[c.kind])}</strong><span>{c.fields.map(f=>pick(...labels[f])).join(' · ')}</span><div>{[...c.before,...c.after].map(l=><button type="button" key={l.id} onClick={()=>onSelect(l.id)}>{c.before.includes(l)?pick('Previous','קודם'):pick('Candidate','מועמד')}: {l.name} · {l.design_quantity}{l.job_id?pick(' · linked job',' · עבודה מקושרת'):''}</button>)}</div></li>)}</ul>{visible.length>limit&&<button type="button" onClick={()=>setLimit(n=>n+50)}>{pick('Show 50 more','הצגת 50 נוספים')}</button>}{!visible.length&&<p>{pick('No changes detected in the available imported fields. This is not a geometry or compatibility approval.','לא זוהו שינויים בשדות הזמינים בייבוא. אין בכך אישור לגאומטריה או לתאימות.')}</p>}</>}
 </section>;
}
