import {useEffect,useRef,useState} from 'react';
import {useLocalization} from '../lib/localization';
export default function CadDocumentBrowser({call,onAdded}:{call:(action:string,values?:Record<string,unknown>)=>Promise<any>;onAdded:(id:string)=>Promise<void>}){
 const lock=useRef(false),lastCheck=useRef(0),selectedDocument=useRef<any>(null);
 const {pick}=useLocalization(),[documents,setDocuments]=useState<any[]>([]),[elements,setElements]=useState<any[]>([]),[document,setDocument]=useState(''),[next,setNext]=useState<number|null>(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState('');
 async function run(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{lock.current=false;setBusy(false);}}
 async function load(){const data=await call('discover',{offset:next??0});setDocuments(old=>[...old,...data.items.filter((d:any)=>!old.some(item=>item.id===d.id))]);setNext(data.nextOffset);}
 async function refresh(){
  const fresh:any[]=[];let offset:number|null=0;
  // Read every catalogue page, with a bounded ceiling for unusually large accounts.
  for(let page=0;page<100&&offset!==null;page++){const data=await call('discover',{offset});fresh.push(...data.items);offset=data.nextOffset;}
  setDocuments(Array.from(new Map(fresh.map(d=>[d.id,d])).values()));setNext(offset);
  const selected=selectedDocument.current;if(selected)setElements((await call('elements',{documentId:selected.id,workspaceId:selected.workspaceId})).elements);
  lastCheck.current=Date.now();
 }
 useEffect(()=>{const check=()=>{if(globalThis.document.visibilityState==='visible'&&Date.now()-lastCheck.current>60000)void run(refresh);};void run(refresh);window.addEventListener('focus',check);globalThis.document.addEventListener('visibilitychange',check);const forced=()=>void run(refresh);window.addEventListener('g3-cad-refresh',forced);return()=>{window.removeEventListener('g3-cad-refresh',forced);window.removeEventListener('focus',check);globalThis.document.removeEventListener('visibilitychange',check);};},[]);
 return <section className="cad-panel cad-document-browser"><h2>{pick('Browse accessible Onshape documents','עיון במסמכי Onshape הזמינים')}</h2><button disabled={busy} onClick={()=>void run(refresh)}>{pick('Refresh from Onshape','רענון מ-Onshape')}</button><p role="status">{lastCheck.current?pick('Catalogue checked: ','הקטלוג נבדק: ')+new Date(lastCheck.current).toLocaleString():busy?pick('Checking Onshape…','בודק Onshape…'):pick('Onshape check failed — retry refresh.','הבדיקה נכשלה — נסו לרענן שוב.')}</p><p>{pick('New documents are discovered automatically when you open or return to CAD Mentor. Choose a document and a design tab to open its latest revision. Onshape is not modified.','מסמכים חדשים מתגלים אוטומטית בפתיחת מנטור CAD ובחזרה אליו. בחרו מסמך ולשונית תכנון לפתיחת הגרסה העדכנית. המקור ב-Onshape אינו משתנה.')}</p>{error&&<p role="alert">{error}</p>}<label>{pick('Filter loaded documents','סינון מסמכים שנטענו')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="cad-document-grid"><div>{documents.filter(d=>d.name.toLowerCase().includes(query.toLowerCase())).map(d=><button key={d.id} disabled={busy||!d.workspaceId} aria-pressed={document===d.id} onClick={()=>void run(async()=>{selectedDocument.current=d;setDocument(d.id);setElements([]);setElements((await call('elements',{documentId:d.id,workspaceId:d.workspaceId})).elements);})}>{d.name}</button>)}{next!==null&&<button disabled={busy} onClick={()=>void run(load)}>{pick('Load more documents','טעינת מסמכים נוספים')}</button>}</div><div>{elements.map(e=><button key={e.id} disabled={busy} onClick={()=>void run(async()=>{const data=await call('add-source',{url:e.url});await onAdded(data.source.id);})}>{e.name} · {e.type==='ASSEMBLY'?pick('Assembly','הרכבה'):pick('Part Studio','Part Studio')} →</button>)}{document&&!busy&&!elements.length&&<p>{pick('No supported design tabs in this document.','אין במסמך זה לשוניות תכנון נתמכות.')}</p>}</div></div>{busy&&<p role="status">{pick('Reading Onshape…','קורא מ-Onshape…')}</p>}</section>;
}
