import {useEffect,useState,useRef} from 'react';
import {useLocalization} from '../lib/localization';
import CadDesignViewer,{type CadGeometry} from './CadDesignViewer';
import AssistAnswer from './AssistAnswer';
type Call=(action:string,values?:Record<string,unknown>)=>Promise<any>;
type Snapshot={id:string;microversion:string;created_at:string;coverage:{kind:string;status:string}[]};
type Finding={id:string;title:string;description:string;status:string;resolution:string;revision:number;snapshot_id:string};
type Review={validation_note?:string;id:string;question:string;answer:string;snapshot_id:string;created_at:string;citations:{id:string;title:string;url:string;anchor:string}[]};
export default function CadReviewWorkspace({sourceId,call}:{sourceId:string;call:Call}){
 const {pick,language}=useLocalization();
 const [workspace,setWorkspace]=useState<{source:any;snapshots:Snapshot[];findings:Finding[];reviews:Review[]}|null>(null),[snapshotId,setSnapshotId]=useState(''),[geometry,setGeometry]=useState<CadGeometry|null>(null),[evidence,setEvidence]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('review'),[requirements,setRequirements]=useState(''),[question,setQuestion]=useState(''),[consent,setConsent]=useState(false),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[requestId,setRequestId]=useState(()=>crypto.randomUUID()),[findingId,setFindingId]=useState(()=>crypto.randomUUID());
 const refreshing=useRef(false),lastAutomaticCheck=useRef(0);const [checkedAt,setCheckedAt]=useState('');
 const selected=workspace?.snapshots.find(s=>s.id===snapshotId);
 async function run(label:string,work:()=>Promise<void>){setBusy(label);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('');}}
 async function load(){const data=await call('workspace',{sourceId});setWorkspace(data);setRequirements(data.source.requirements);return data;}
 async function inspect(id:string){setSnapshotId(id);setGeometry(null);setEvidence(null);setConsent(false);setRequestId(crypto.randomUUID());const data=await call('evidence',{sourceId,snapshotId:id});setEvidence(data);const asset=await call('geometry',{sourceId,snapshotId:id});const url=new URL(asset.url);if(url.origin!=='https://hnqwhuuxlqfyawqymaaz.supabase.co'||!url.pathname.startsWith('/storage/v1/object/sign/cad-design-assets/'))throw Error(pick('Invalid design asset destination.','כתובת קובץ התכנון אינה תקינה.'));const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw Error(pick('Geometry could not be loaded. Try opening the revision again.','לא ניתן לטעון את הגאומטריה. נסו לפתוח את הגרסה שוב.'));const model=await response.json();if(model.units!=='m'||!Array.isArray(model.meshes))throw Error(pick('Unsupported geometry response.','נתוני גאומטריה לא נתמכים.'));setGeometry(model);}
 useEffect(()=>{void run(pick('Loading design…','טוען תכנון…'),async()=>{const data=await load();try{const current=await call('snapshot',{sourceId});await load();await inspect(current.snapshot.id);setCheckedAt(new Date().toLocaleString());}catch(e){if(data.snapshots[0])await inspect(data.snapshots[0].id);throw e;}});},[sourceId]);
 useEffect(()=>{const check=()=>{if(document.visibilityState!=='visible'||busy||refreshing.current||question.trim()||requirements!==workspace?.source.requirements||tab!=='review')return;refreshing.current=true;void run(pick('Checking Onshape for changes…','בודק שינויים ב-Onshape…'),async()=>{const current=await call('snapshot',{sourceId});await load();if(current.snapshot.id!==snapshotId)await inspect(current.snapshot.id);setCheckedAt(new Date().toLocaleString());}).finally(()=>{refreshing.current=false;});};const automatic=()=>{if(Date.now()-lastAutomaticCheck.current<60000)return;lastAutomaticCheck.current=Date.now();check();};window.addEventListener('g3-cad-refresh',check);window.addEventListener('focus',automatic);document.addEventListener('visibilitychange',automatic);return()=>{window.removeEventListener('g3-cad-refresh',check);window.removeEventListener('focus',automatic);document.removeEventListener('visibilitychange',automatic);};},[busy,question,requirements,workspace,snapshotId,tab]);
 const labels:Record<string,[string,string]>={open:['Open','פתוח'],proposed_fix:['Fix proposed','הוצע תיקון'],awaiting_verification:['Awaiting verification','ממתין לאימות'],resolved:['Verified and resolved','אומת ונפתר'],accepted:['Accepted with reason','התקבל עם נימוק']};
 if(!workspace)return <section className="cad-panel"><p role="status">{busy}</p>{error&&<p role="alert">{error}</p>}</section>;
 return <section className="cad-workspace" aria-busy={!!busy}>
  <header className="cad-workspace-head"><div><span>{pick('REVIEW WORKSPACE','סביבת בדיקת תכנון')}</span><h2>{workspace.source.name}</h2><p>{pick('Inspect → Review → Improve in Onshape → Verify','בדיקה ← סקירה ← שיפור ב-Onshape ← אימות')}</p></div><button className="primary" disabled={!!busy} onClick={()=>void run(pick('Importing current revision…','מייבא גרסה נוכחית…'),async()=>{const data=await call('snapshot',{sourceId});await load();await inspect(data.snapshot.id);setCheckedAt(new Date().toLocaleString());})}>{workspace.snapshots.length?pick('Check for design changes','בדיקת שינויים בתכנון'):pick('Import current design','ייבוא התכנון הנוכחי')}</button></header>
  {(question.trim()||requirements!==workspace.source.requirements)&&<p>{pick('Automatic revision updates pause while you have an unsaved question or requirements. Use Check for design changes before reviewing when ready.','עדכוני גרסה אוטומטיים מושהים כל עוד יש שאלה או דרישות שלא נשמרו. בסיום השתמשו בבדיקת שינויים בתכנון לפני הסקירה.')}</p>}{checkedAt&&<p role="status">{pick('Onshape checked: ','Onshape נבדק: ')}{checkedAt}</p>}{busy&&<p role="status" className="cad-progress">{busy}</p>}{error&&<p role="alert" className="cad-error">{error}</p>}
  {!selected?<div className="cad-panel"><h3>{pick('Start with the actual design','מתחילים מהתכנון המקורי')}</h3><p>{pick('Import creates a read-only snapshot. It does not change your Onshape design.','הייבוא יוצר תמונת מצב לקריאה בלבד ואינו משנה את התכנון ב-Onshape.')}</p></div>:<>
   <div className="cad-revision-bar"><label>{pick('Design revision','גרסת תכנון')}<select disabled={!!busy} value={snapshotId} onChange={e=>void run(pick('Opening revision…','פותח גרסה…'),()=>inspect(e.target.value))}>{workspace.snapshots.map(s=><option key={s.id} value={s.id}>{new Date(s.created_at).toLocaleString(language==='he'?'he-IL':'en-GB')} · {s.microversion.slice(0,8)}</option>)}</select></label><a target="_blank" rel="noreferrer" href={`https://cad.onshape.com/documents/${workspace.source.document_id}/m/${selected.microversion}/e/${workspace.source.element_id}?configuration=${encodeURIComponent(workspace.source.configuration==='default'?'':workspace.source.configuration)}`}>{pick('Open this exact revision ↗','פתיחת הגרסה המדויקת ↗')}</a><a target="_blank" rel="noreferrer" href={`https://cad.onshape.com/documents/${workspace.source.document_id}/${workspace.source.reference_type}/${workspace.source.reference_id}/e/${workspace.source.element_id}`}>{pick('Edit in Onshape ↗','עריכה ב-Onshape ↗')}</a></div>
   {geometry&&<CadDesignViewer geometry={geometry}/>}
   <nav className="cad-tabs" aria-label={pick('Design workflow','תהליך בדיקת תכנון')}>{[['review','Review design','בדיקת תכנון'],['findings','Findings & verification','ממצאים ואימות'],['evidence','Imported evidence','נתונים שיובאו']].map(([id,en,he])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{pick(en,he)}{id==='findings'?` (${workspace.findings.filter(f=>!['resolved','accepted'].includes(f.status)).length})`:''}</button>)}</nav>
   {tab==='review'&&<div className="cad-review-grid"><section className="cad-panel"><h3>{pick('Design purpose & requirements','מטרת התכנון ודרישות')}</h3><p>{pick('Describe what this mechanism must do, available space, interfaces, loads, materials and manufacturing constraints. Only include values you know.','תארו את תפקיד המנגנון, המקום הזמין, הממשקים, העומסים, החומרים ומגבלות הייצור. כללו רק ערכים ידועים.')}</p><label>{pick('Requirements','דרישות')}<textarea rows={5} value={requirements} maxLength={6000} onChange={e=>setRequirements(e.target.value)}/></label><button disabled={!!busy||requirements===workspace.source.requirements} onClick={()=>void run(pick('Saving requirements…','שומר דרישות…'),async()=>{await call('requirements',{sourceId,requirements,revision:workspace.source.revision});await load();})}>{pick('Save requirements','שמירת דרישות')}</button></section>
    <section className="cad-panel"><h3>{pick('Ask G3 CAD Mentor','שאלה למנטור CAD')}</h3><p>{pick('Reviews use imported feature data and part/assembly structure from this revision. They do not simulate loads or prove physical fit.','הסקירה משתמשת בנתוני התכונות ובמבנה החלקים/הרכבה שיובאו מגרסה זו. היא אינה מדמה עומסים או מוכיחה התאמה פיזית.')}</p><label>{pick('What should we investigate?','מה לבדוק?')}<textarea rows={4} maxLength={4000} value={question} placeholder={pick('For example: review this bracket’s features and identify what we must verify before manufacturing.','לדוגמה: בדקו את תכונות התושבת ומה עלינו לאמת לפני ייצור.')} onChange={e=>{setQuestion(e.target.value);setRequestId(crypto.randomUUID());}}/></label><label className="cad-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{pick('Allow sending this revision’s selected CAD evidence, saved requirements and my question to Google Gemini for this review.','מאשר/ת לשלוח את נתוני ה-CAD שנבחרו מגרסה זו, הדרישות השמורות והשאלה שלי ל-Google Gemini לצורך הבדיקה.')}</span></label><button className="primary" disabled={!!busy||!consent||!question.trim()||requirements!==workspace.source.requirements} onClick={()=>void run(pick('Reviewing actual design evidence…','בודק את נתוני התכנון…'),async()=>{await call('review',{sourceId,snapshotId,question,requestId,cadConsent:'cad-gemini-v1',language});await load();setRequestId(crypto.randomUUID());})}>{pick('Review this revision','בדיקת גרסה זו')}</button>{requirements!==workspace.source.requirements&&<small>{pick('Save your requirements first.','שמרו קודם את הדרישות.')}</small>}</section>
    <section className="cad-panel cad-review-history"><h3>{pick('Saved reviews','סקירות שמורות')}</h3>{workspace.reviews.filter(r=>r.snapshot_id===snapshotId).map(review=><article key={review.id}><h4>{review.question}</h4><small>{new Date(review.created_at).toLocaleString()}</small>{review.validation_note&&<p role="alert" className="cad-error">{pick('Do not rely on this review: its evidence omitted a downstream feature. Use the newer corrected review.','אין להסתמך על סקירה זו: בנתונים חסרה תכונה מאוחרת. השתמשו בסקירה המתוקנת.')}</p>}{review.validation_note?<details><summary>{pick('Superseded test review — audit history','סקירת בדיקה שהוחלפה — היסטוריית ביקורת')}</summary><AssistAnswer text={review.answer}/></details>:<AssistAnswer text={review.answer}/>}<ul>{review.citations.map(c=><li key={c.id}><a target="_blank" rel="noreferrer" href={c.url}>[{c.id}] {c.title}</a> · <code>{c.anchor}</code></li>)}</ul><button disabled={!!review.validation_note} onClick={()=>{setTitle(review.question.slice(0,180));setDescription(review.answer.slice(0,6000));setTab('findings');}}>{pick('Track a finding from this review','מעקב אחר ממצא מסקירה זו')}</button></article>)}{!workspace.reviews.some(r=>r.snapshot_id===snapshotId)&&<p>{pick('No review saved for this revision yet.','עדיין אין סקירה שמורה לגרסה זו.')}</p>}</section></div>}
   {tab==='findings'&&<section className="cad-panel"><h3>{pick('Close the loop','סגירת מעגל')}</h3><p>{pick('Record a concern, make the change in Onshape, import the new revision and record how you verified the fix. Findings do not resolve automatically when geometry changes.','תעדו חשש, בצעו את השינוי ב-Onshape, יבאו את הגרסה החדשה ותעדו כיצד אימתתם את התיקון. שינוי בגאומטריה אינו סוגר ממצאים אוטומטית.')}</p><form onSubmit={e=>{e.preventDefault();void run(pick('Saving finding…','שומר ממצא…'),async()=>{await call('finding',{sourceId,snapshotId,title,description,findingRequestId:findingId});setTitle('');setDescription('');setFindingId(crypto.randomUUID());await load();});}}><label>{pick('Finding title','כותרת הממצא')}<input value={title} required maxLength={180} onChange={e=>setTitle(e.target.value)}/></label><label>{pick('Evidence, proposed change and acceptance test','ראיות, שינוי מוצע ובדיקת קבלה')}<textarea rows={4} value={description} maxLength={6000} onChange={e=>setDescription(e.target.value)}/></label><button disabled={!!busy||!title.trim()}>{pick('Add finding','הוספת ממצא')}</button></form>{workspace.findings.map(f=><FindingEditor key={`${f.id}/${f.revision}`} finding={f} labels={labels} busy={!!busy} save={(status,resolution)=>void run(pick('Saving verification…','שומר אימות…'),async()=>{await call('finding',{sourceId,snapshotId,findingId:f.id,status,resolution,revision:f.revision});await load();})}/>)}</section>}
   {tab==='evidence'&&<section className="cad-panel"><h3>{pick('What was actually imported','מה יובא בפועל')}</h3><p><code>{selected.microversion}</code></p><ul>{selected.coverage.map(c=><li key={c.kind}>{c.kind}: {c.status==='retrieved'?pick('Retrieved','יובא'):pick('Unavailable — not reviewed','לא זמין — לא נבדק')}</li>)}</ul>{evidence?.truncated&&<p>{pick('Evidence exceeds one review’s context limit. Some records were omitted; choose a smaller subsystem for a complete focused review.','הנתונים חורגים ממגבלת סקירה אחת. חלק מהרשומות הושמטו; בחרו תת־מערכת קטנה יותר לסקירה ממוקדת מלאה.')}</p>}{evidence?.citations.map((c:any)=><details key={c.id}><summary>[{c.id}] {c.title}</summary><pre>{JSON.stringify(c.data,null,2)}</pre></details>)}</section>}
  </>}
 </section>;
}
function FindingEditor({finding:f,labels,busy,save}:{finding:Finding;labels:Record<string,[string,string]>;busy:boolean;save:(status:string,resolution:string)=>void}){const {pick}=useLocalization(),[status,setStatus]=useState(f.status),[resolution,setResolution]=useState(f.resolution);return <article className="cad-finding"><h4>{f.title}</h4><p className="cad-answer">{f.description}</p><label>{pick('Status','מצב')}<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(labels).map(([id,words])=><option key={id} value={id}>{pick(...words)}</option>)}</select></label><label>{pick('Verification evidence or acceptance reason','ראיות לאימות או נימוק לקבלה')}<textarea rows={3} value={resolution} maxLength={6000} onChange={e=>setResolution(e.target.value)}/></label><button disabled={busy||(status===f.status&&resolution===f.resolution)||(['resolved','accepted'].includes(status)&&!resolution.trim())} onClick={()=>save(status,resolution)}>{pick('Save status & evidence','שמירת מצב וראיות')}</button></article>;}
