import {useEffect,useMemo,useRef,useState} from 'react';
import type {SeasonPackage} from '../lib/seasonPackage';
import {cameraCoverage,type CameraMount,type CameraSample,type VisibilityGeometry} from '../lib/cameraPlanning';
import {compareCoverageSets} from '../lib/cameraCad';
import PlanningField from './PlanningField';
import TwinNumberInput from './TwinNumberInput';
import {useLocalization} from '../lib/localization';
type Props={liveAnalysis:boolean;season:SeasonPackage;cameras:CameraMount[];maxCameras:number;geometry:VisibilityGeometry;pose:CameraSample;onPose:(pose:CameraSample)=>void};
type Cell={x:number;y:number;counts:number[]};
/** Bounded, explicit geometric survey. Does not classify a position as drivable. */
export default function CameraFieldExplorer({liveAnalysis,season,cameras,maxCameras,geometry,pose,onPose}:Props){
 const {pick}=useLocalization(),[cells,setCells]=useState<Cell[]>([]),[ids,setIds]=useState<string[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');const epoch=useRef(0);
 useEffect(()=>{epoch.current++;setCells([]);setIds([]);setBusy(false);return()=>{epoch.current++;};},[season,cameras,maxCameras,geometry]);
 const length=season.field.length,width=season.field.width,nx=12,ny=6,dx=length/nx,dy=width/ny;
 async function scan(){const token=++epoch.current;setBusy(true);setError('');setCells([]);try{
  const mounts=cameras.filter(c=>c.permitted!==false);if(!mounts.length)throw Error(pick('Enable at least one candidate mount.','יש לאפשר מיקום מצלמה אחד לפחות.'));
  const positions=Array.from({length:nx*ny},(_,i)=>({x:-length/2+(i%nx+.5)*dx,y:-width/2+(Math.floor(i/nx)+.5)*dy}));
  const poses=positions.flatMap(p=>Array.from({length:8},(_,i)=>({...p,heading:i*Math.PI/4})));
  const coverage:number[][][]=[];for(let c=0;c<mounts.length;c++){const values:number[][]=[];for(let i=0;i<poses.length;i++){if(token!==epoch.current)return;values.push(cameraCoverage(season,mounts[c],[poses[i]],[],geometry)[0].tagIds);if(i%8===0)setProgress(Math.round(100*(c*poses.length+i)/(mounts.length*poses.length)));if(i%4===0)await new Promise<void>(resolve=>{const channel=new MessageChannel();channel.port1.onmessage=()=>{channel.port1.close();channel.port2.close();resolve();};channel.port2.postMessage(null);});}coverage.push(values);}
  if(token!==epoch.current)return;const best=compareCoverageSets(mounts.map(c=>c.id),coverage,maxCameras,1)[0];const indices=best.ids.map(id=>mounts.findIndex(c=>c.id===id));setIds(best.ids);setCells(positions.map((p,j)=>({...p,counts:Array.from({length:8},(_,h)=>new Set(indices.flatMap(c=>coverage[c][j*8+h])).size)})));setProgress(100);
 }catch(e){if(token===epoch.current)setError(e instanceof Error?e.message:'Scan failed');}finally{if(token===epoch.current)setBusy(false);}}
 const visible=useMemo(()=>!liveAnalysis?[]:cameras.filter(c=>c.permitted!==false).map(c=>({id:c.id,tags:cameraCoverage(season,c,[pose],[],geometry)[0].tagIds})),[liveAnalysis,cameras,season,pose,geometry]);
 return <section className="ep-camera-explorer"><h3>{pick('Explore positions & blind zones','בדיקת מיקומים ואזורים ללא נראות')}</h3><p>{pick('Click the field to move the inspection robot; change heading to turn it. This does not edit your route. The camera view above follows this inspection pose.','לחצו במגרש להזזת רובוט הבדיקה; שנו כיוון כדי לסובב אותו. המסלול אינו משתנה. תצוגת המצלמה למעלה עוקבת אחר תנוחה זו.')}</p>
 <div className="ep-controls">{(['x','y','heading'] as const).map(k=><label key={k}>{k==='heading'?pick('Inspection heading (°)','כיוון בדיקה (°)'):k.toUpperCase()+' (m)'}<TwinNumberInput value={k==='heading'?pose.heading*180/Math.PI:pose[k]} min={k==='heading'?-180:k==='x'?-length/2:-width/2} max={k==='heading'?180:k==='x'?length/2:width/2} step={k==='heading'?5:.1} onCommit={v=>onPose({...pose,[k]:k==='heading'?v*Math.PI/180:v})}/></label>)}</div>
 <PlanningField season={season} active><svg className="ep-field" viewBox={`0 0 ${length} ${width}`} role="img" aria-label={pick('Camera blind-zone map; click to inspect','מפת אזורים ללא נראות; לחצו לבדיקה')} onClick={e=>{const m=e.currentTarget.getScreenCTM();if(!m)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());onPose({...pose,x:Math.max(-length/2,Math.min(length/2,p.x-length/2)),y:Math.max(-width/2,Math.min(width/2,width/2-p.y))});}}>
 {cells.map((c,i)=>{const blind=c.counts.filter(n=>n===0).length;return <rect key={i} x={c.x+length/2-dx/2} y={width/2-c.y-dy/2} width={dx} height={dy} fill={blind===8?'#ef4661':blind?'#f3b747':'#36c9a5'} fillOpacity=".45" stroke="#ffffff" strokeWidth=".015"><title>{`${c.x.toFixed(1)}, ${c.y.toFixed(1)}: ${blind}/8 headings without tags`}</title></rect>;})}
 {season.field.tags.map(t=><circle key={t.id} cx={t.x+length/2} cy={width/2-t.y} r=".07" fill="#56e6e1"/>)}
 <g pointerEvents="none" transform={`translate(${pose.x+length/2} ${width/2-pose.y}) rotate(${-pose.heading*180/Math.PI})`}><circle r=".2" fill="#fff" stroke="#94006f" strokeWidth=".05"/><path d="M 0 0 L .7 0 M .5 -.15 L .7 0 L .5 .15" fill="none" stroke="#fff" strokeWidth=".07"/></g></svg></PlanningField>
 <p>{!liveAnalysis&&pick('Live tag counts are paused during route playback; select an inspection pose to inspect them.','ספירת תגיות מושהית בזמן ניגון המסלול; בחרו תנוחת בדיקה לצפייה בהן.')}{visible.map(v=>`${v.id}: ${v.tags.length? v.tags.join(', '):pick('no visible tags','אין תגיות נראות')}`).join(' · ')}</p>
 <div className="ep-controls"><button disabled={busy} onClick={()=>void scan()}>{pick('Survey field · 8 headings per position','סריקת המגרש · 8 כיוונים לכל מיקום')}</button>{busy&&<button onClick={()=>{epoch.current++;setBusy(false);}}>{pick('Cancel','ביטול')}</button>}</div>{busy&&<progress max="100" value={progress} aria-label={pick('Field survey progress','התקדמות סריקה')}/>} {error&&<p role="alert">{error}</p>}
 {cells.length>0&&<><p><strong>{pick('Best tested candidate set','השילוב הטוב מבין המועמדים שנבדקו')}: {ids.join(' + ')}</strong> · {cells.reduce((n,c)=>n+c.counts.filter(v=>v===0).length,0)}/{cells.length*8} {pick('sampled poses without a visible tag','תנוחות מדוגמות ללא תגית נראית')}</p><p>{pick('Red: no tags at all 8 headings. Amber: at least one blind heading. Green: a tag at each tested heading. Cell colour describes its centre only; untested positions and angles are not guaranteed.','אדום: אין תגיות בכל 8 הכיוונים. כתום: לפחות כיוון אחד ללא נראות. ירוק: תגית בכל כיוון שנבדק. הצבע מתאר רק את מרכז התא; מיקומים וזוויות שלא נבדקו אינם מובטחים.')}</p><details><summary>{pick('Inspect blind poses','בדיקת תנוחות ללא נראות')}</summary><div className="ep-controls">{cells.flatMap((c,i)=>c.counts.map((n,h)=>n===0?<button key={`${i}-${h}`} onClick={()=>onPose({x:c.x,y:c.y,heading:h>4?(h-8)*Math.PI/4:h*Math.PI/4})}>{c.x.toFixed(1)}, {c.y.toFixed(1)} · {h*45}°</button>:null)).filter(Boolean).slice(0,48)}</div><small>{pick('First 48 blind poses shown; the map summarizes all samples.','מוצגות 48 התנוחות הראשונות; המפה מסכמת את כל הדגימות.')}</small></details></>}
 <p>{pick('Uses installed CAD occlusion and configured optics. The survey includes positions that may be inside obstacles; it is not a drivable-space or localization-accuracy certificate. It ranks your permitted mounts, not arbitrary mounting points.','משתמש בהסתרות CAD ובאופטיקה שהוגדרה. הסריקה כוללת גם מיקומים בתוך מכשולים; זו אינה הוכחת עבירות או דיוק מיקום. הדירוג הוא של המיקומים המותרים שהגדרתם בלבד.')}</p></section>;
}
