import {useRef,useState} from 'react';

type Pick=(en:string,he:string)=>string;
const wpilib='https://docs.wpilib.org/en/stable/docs/hardware/hardware-basics/can-wiring-basics.html';
const ctre='https://v5.docs.ctr-electronics.com/en/latest/ch08_BringUpCAN.html';
const kraken='https://docs.wcproducts.com/welcome/electronics/kraken-x60/kraken-x60-+-talonfx/overview-and-features/wiring-and-modularity';
const wiring='https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-1/intro-to-frc-robot-wiring.html';

/** A documented example, deliberately separate from the inspected robot's unknown harness. */
export default function CanWorkshop({pick}:{pick:Pick}){
 const dialog=useRef<HTMLDialogElement>(null),[step,setStep]=useState(0),[connector,setConnector]=useState('rio'),[imageFailed,setImageFailed]=useState(false);
 const titles=[pick('Trace the bus','מעקב אחר האפיק'),pick('Connect the hardware','חיבור הרכיבים'),pick('Inspect & diagnose','בדיקה ואבחון')];
 const link=(url:string,label:string)=><a href={url} target="_blank" rel="noreferrer">{label} ↗</a>;
 return <><button className="rl-can-launch" onClick={()=>dialog.current?.showModal()}>{pick('CAN wiring workshop','סדנת חיווט CAN')} ↗</button>
 <dialog ref={dialog} className="rl-can-dialog" aria-labelledby="can-title">
  <header><div><small>G3 / {pick('WORKSHOP','סדנה')}</small><h2 id="can-title">{pick('Make every connection count','כל חיבור קובע')}</h2></div><button onClick={()=>dialog.current?.close()}>{pick('Back to robot','חזרה לרובוט')} ×</button></header>
  <p className="rl-can-context">{pick('A practical roboRIO CAN-bus example. This is not Darwin’s or Limestone’s wiring map. Choose the hardware actually installed on your robot.','דוגמה מעשית לאפיק CAN של roboRIO. זו אינה מפת החיווט של Darwin או Limestone. בחרו את החומרה המותקנת בפועל ברובוט שלכם.')}</p>
  <nav aria-label={pick('Wiring lesson steps','שלבי שיעור החיווט')}>{titles.map((title,i)=><button key={i} aria-pressed={step===i} onClick={()=>setStep(i)}>{i+1}. {title}</button>)}</nav>
  <main className="rl-can-body">
  {step===0&&<><h3>{titles[0]}</h3><p>{pick('Follow each signal from end to end: yellow H connects to H; green L connects to L. CAN carries data, not motor power.','עקבו אחר כל אות מקצה לקצה: צהוב H מתחבר ל-H; ירוק L מתחבר ל-L. CAN מעביר נתונים, לא הספק למנוע.')}</p>
   <div className="rl-can-diagram" dir="ltr" role="img" aria-label={pick('Two continuous wires: CAN H and CAN L from roboRIO through devices to a terminated endpoint. 120 ohms at each end.','שני מוליכים רציפים: CAN H ו-CAN L מה-roboRIO דרך הרכיבים לקצה עם נגד סיום. 120 אוהם בכל קצה.')}>
    <div className="rl-can-nodes"><b>roboRIO<small>120 Ω</small></b><b>{pick('Device 1','רכיב 1')}</b><b>{pick('Device 2','רכיב 2')}</b><b>PDP / PDH<small>120 Ω · ON</small></b></div>
    <div className="rl-can-wire high">H ━━━━━━━━━ H ━━━━━━━━━ H ━━━━━━━━━ H</div><div className="rl-can-wire low">L ━━━━━━━━━ L ━━━━━━━━━ L ━━━━━━━━━ L</div>
   </div><p>{pick('Use a twisted pair in a continuous chain. The example places the distribution device at the far end with termination enabled. Intermediate devices must not add another termination. Other buses, including CANivore, need their own documented termination arrangement.','השתמשו בזוג שזור בשרשרת רציפה. בדוגמה רכיב חלוקת המתח בקצה המרוחק עם נגד סיום פעיל. רכיבי ביניים לא מוסיפים נגד סיום נוסף. אפיקים אחרים, כולל CANivore, דורשים סידור סיום לפי המדריך שלהם.')}</p>
   {link(wpilib,pick('WPILib: wiring and termination','WPILib: חיווט ונגדי סיום'))}
   <aside>{pick('Workshop task: label the two ends and every device on your own paper diagram before connecting cables. Mark which connector can be unplugged to service each mechanism.','משימת סדנה: סמנו על דף את שני הקצוות ואת כל הרכיבים לפני חיבור הכבלים. סמנו איזה מחבר ניתן לנתק לצורך תחזוקת כל מנגנון.')}</aside></>}
  {step===1&&<><h3>{titles[1]}</h3><p className="rl-can-safety">{pick('Disconnect the robot battery before changing connections.','נתקו את סוללת הרובוט לפני שינוי החיבורים.')}</p>
   <label>{pick('Which connector are you working on?','על איזה מחבר עובדים?')}<select value={connector} onChange={e=>setConnector(e.target.value)}><option value="rio">roboRIO / {pick('spring terminal','הדק קפיצי')}</option><option value="spark">SPARK MAX / {pick('CAN cable','כבל CAN')}</option><option value="kraken">Kraken X60 / {pick('ring terminal','נעל כבל טבעתית')}</option></select></label>
   {connector==='rio'&&<><ol><li>{pick('Identify the CAN H and L markings on the actual connector. Match yellow to H and green to L.','זהו סימוני CAN H ו-L על המחבר עצמו. התאימו צהוב ל-H וירוק ל-L.')}</li><li>{pick('Open the spring terminal using its actuator, insert the correctly stripped conductor fully, then release. Follow the illustrated device instructions for stripping and tools.','פתחו את ההדק הקפיצי באמצעות הלחצן שלו, הכניסו את המוליך החשוף באורך המתאים ושחררו. היעזרו בהוראות המאוירות לאורך הקילוף ולכלים.')}</li><li>{pick('Check that the clamp grips conductor, not insulation, with no exposed loose strands. Gently pull each wire separately.','בדקו שההדק אוחז במוליך ולא בבידוד, ללא גידים חופשיים חשופים. משכו בעדינות כל מוליך בנפרד.')}</li></ol>{link(wiring,pick('Open illustrated terminal instructions','פתיחת הוראות ההדקים המאוירות'))}</>}
   {connector==='spark'&&<><ol><li>{pick('Use the SPARK MAX CAN cable connections, not its encoder or motor connections.','השתמשו בחיבורי כבל CAN של SPARK MAX, לא בחיבורי המקודד או המנוע.')}</li><li>{pick('Join the preterminated CAN cables to continue the chain; fit the retention clips. Keep H and L consistent at each end.','חברו את כבלי ה-CAN המוכנים להמשך השרשרת והתקינו תפסי נעילה. שמרו על התאמת H ו-L בכל קצה.')}</li><li>{pick('Secure the harness so movement cannot pull on the connector. Check full seating before powering up.','קבעו את הצמה כך שתנועה לא תמשוך את המחבר. בדקו שהחיבור יושב במלואו לפני הפעלה.')}</li></ol>{link(wiring,pick('WPILib: SPARK MAX CAN connections','WPILib: חיבורי CAN של SPARK MAX'))}</>}
   {connector==='kraken'&&<>{!imageFailed&&<figure className="rl-can-photo"><img loading="lazy" onError={()=>setImageFailed(true)} src="https://782947646-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FG5VCf9egrd5oqXAIKxwT%2Fuploads%2F5iMKQv6NqHDgUZFHfEgO%2FKraken%20X60%20-%20Wiring%20%26%20Modularity.svg?alt=media&amp;token=852aacb1-345b-42d0-a35a-1ea07759fc7e" alt={pick('WCP illustration of Kraken X60 power and CAN ring-terminal connections','איור WCP לחיבורי מתח ו-CAN באמצעות נעלי כבל ב-Kraken X60')}/><figcaption>{pick('Manufacturer illustration · WCP · loaded from the source','איור היצרן · WCP · נטען מהמקור')}</figcaption></figure>}<p>{pick('Kraken X60 uses ring terminals. Its supplied CAN pair is 22 AWG with pre-crimped terminals. Keep the yellow H and green L leads on their marked terminals.','Kraken X60 משתמש בנעלי כבל טבעתיות. זוג ה-CAN המצורף הוא 22 AWG עם נעלי כבל לחוצות מראש. חברו את צהוב H וירוק L להדקים המסומנים.')}</p><div className="rl-can-spec"><strong>CAN · #4-40 × ¼″ · 0.6 N·m</strong><span>{pick('Kraken X60 CAN terminals only · IP8 / T8 driver','להדקי CAN של Kraken X60 בלבד · מברג IP8 / T8')}</span></div><p>{pick('Use the specified screws; longer screws can damage the controller. Support the cable near the terminal and allow movement without pulling the crimp. These values are not universal connector settings.','השתמשו בברגים המוגדרים; ברגים ארוכים יותר עלולים לפגוע בבקר. תמכו בכבל ליד ההדק ואפשרו תנועה בלי משיכת הלחיצה. הערכים אינם הגדרות כלליות לכל מחבר.')}</p>{link(kraken,pick('WCP: actual terminal illustrations and specifications','WCP: איורי ההדקים בפועל והמפרט'))}</>}
   <aside>{pick('Do not guess a crimp tool, strip length or terminal torque. Use the connector manufacturer’s specification. Start with a spare cable and inspect the practice crimp before working on the robot.','אל תנחשו כלי לחיצה, אורך קילוף או מומנט הידוק. השתמשו במפרט יצרן המחבר. התחילו מכבל רזרבי ובדקו את לחיצת התרגול לפני עבודה על הרובוט.')}</aside></>}
  {step===2&&<><h3>{titles[2]}</h3><div className="rl-can-checks">{[
   ['Battery disconnected; inspect H/L polarity and tug-test individual crimps.','סוללה מנותקת; בדקו התאמת H/L ומשכו בעדינות כל לחיצה בנפרד.'],
   ['Check cable strain relief throughout mechanism travel; keep wires away from sharp edges and moving parts.','בדקו הקלת מאמצים לאורך כל תנועת המנגנון; הרחיקו כבלים מקצוות חדים וחלקים נעים.'],
   ['With the system unpowered, measure resistance between H and L: about 60 Ω is expected for two 120 Ω terminators. About 120 Ω suggests one missing or disconnected terminator.','כשהמערכת ללא מתח, מדדו התנגדות בין H ל-L: כ-60 אוהם צפויים עבור שני נגדי 120 אוהם. כ-120 אוהם עשויים להצביע על נגד חסר או מנותק.'],
   ['A good resistance reading does not prove reliable communications. Reconnect power only after inspection, keep the robot disabled, and check device discovery and CAN errors.','התנגדות תקינה אינה הוכחה לתקשורת אמינה. חברו מתח רק לאחר בדיקה, השאירו את הרובוט במצב מושבת ובדקו גילוי רכיבים ושגיאות CAN.']
   ].map(([en,he],i)=><p key={i}><b>{i+1}</b>{pick(en,he)}</p>)}</div>{link(ctre,pick('CTRE: CAN bring-up and fault checks','CTRE: הפעלת CAN ובדיקת תקלות'))}<aside>{pick('Record the failing device, bus, connector, measured resistance and when the fault occurs. If all devices after one connection disappear, inspect that connection and the downstream cable first. Retest after the repair.','תעדו רכיב תקול, אפיק, מחבר, התנגדות ומועד התקלה. אם כל הרכיבים אחרי חיבור אחד נעלמים, התחילו בבדיקתו ובבדיקת הכבל שאחריו. בדקו שוב לאחר התיקון.')}</aside></>}
  </main><footer><span>{step+1} / 3</span><button disabled={step===0} onClick={()=>setStep(s=>s-1)}>{pick('Previous','הקודם')}</button>{step<2?<button onClick={()=>setStep(s=>s+1)}>{pick('Next step','השלב הבא')} →</button>:<button onClick={()=>dialog.current?.close()}>{pick('Return to the robot','חזרה לרובוט')}</button>}</footer>
 </dialog></>;
}
