import {useEffect,useState,type FormEvent} from 'react';
import {useNavigate} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useAccessControl} from '../lib/accessControl';
type Task={id:string;title:string;status:string;due_at:string|null;owner:string|null;assignee_id:string|null;project_id:string;subteam:string|null};
type Project={id:string;name:string;subteam:string|null};
export default function CompetitionChecklist({eventId,team}:{eventId:string;team:string|null}){
 const {pick}=useLocalization(),access=useAccessControl(),navigate=useNavigate();
 const [tasks,setTasks]=useState<Task[]>([]),[projects,setProjects]=useState<Project[]>([]),[choices,setChoices]=useState<Task[]>([]),[members,setMembers]=useState<{id:string;display_name:string}[]>([]);
 const [message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[mode,setMode]=useState(''),[selected,setSelected]=useState(''),[project,setProject]=useState(''),[title,setTitle]=useState(''),[owner,setOwner]=useState(''),[due,setDue]=useState('');
 const manage=access.can('manage_team_calendar',team);
 async function load(){setLoading(true);const r=await supabase.rpc('competition_checklist',{p_event:eventId});if(r.error){setMessage(pick('Checklist unavailable. Please refresh after setup.','רשימת ההכנות אינה זמינה. יש לרענן לאחר ההגדרה.'));}else{setTasks(r.data??[]);}setLoading(false);}
 useEffect(()=>{void load();},[eventId]);
 async function prepare(next:string){setMessage('');setBusy(true);try{const [p,t,m]=await Promise.all([supabase.from('team_projects').select('id,name,subteam').neq('status','archived'),supabase.from('project_tasks').select('id,title,status,due_at,assignee_id,project_id').eq('archived',false).order('title'),supabase.from('team_members').select('id,display_name').eq('active',true).order('display_name')]);if(p.error||t.error||m.error)throw p.error||t.error||m.error;const allowed=(p.data??[]).filter(x=>access.can('assign_team_work',x.subteam));setProjects(allowed);setChoices((t.data??[]).filter(x=>allowed.some(p=>p.id===x.project_id)) as Task[]);setMembers(m.data??[]);setMode(next==='new'&&!allowed.length?'no-projects':next==='link'&&!(t.data??[]).some(x=>allowed.some(p=>p.id===x.project_id)&&!tasks.some(link=>link.id===x.id))?'no-tasks':next);}catch{setMessage(pick('Could not load task options. Try again.','לא ניתן לטעון משימות. נסו שוב.'));}finally{setBusy(false);}}
 async function save(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const result=mode==='link'?await supabase.from('competition_checklist_tasks').insert({calendar_event_id:eventId,task_id:selected}):await supabase.rpc('create_competition_task',{p_event:eventId,p_project:project,p_title:title,p_owner:owner,p_due:new Date(due).toISOString()});if(result.error)throw result.error;setMode('');setTitle('');setSelected('');await load();window.dispatchEvent(new Event('g3-actions-changed'));}catch{setMessage(pick('Could not save. Check permissions and whether this task is already linked.','לא ניתן לשמור. בדקו הרשאות והאם המשימה כבר מקושרת.'));}finally{setBusy(false);}}
 async function unlink(id:string){setBusy(true);const r=await supabase.from('competition_checklist_tasks').delete().eq('calendar_event_id',eventId).eq('task_id',id).select('task_id');if(r.error||!r.data?.length)setMessage(pick('Could not remove the link.','לא ניתן להסיר את הקישור.'));else{await load();window.dispatchEvent(new Event('g3-actions-changed'));}setBusy(false);}
 const done=tasks.filter(t=>t.status==='done').length,overdue=tasks.filter(t=>t.status!=='done'&&t.due_at&&Date.parse(t.due_at)<Date.now()).length;
 return <section className="competition-checklist"><header><h3>{pick('Event preparation','הכנות לאירוע')}</h3>{!loading?<span>{pick(`${done}/${tasks.length} complete · ${overdue} overdue`,`${done}/${tasks.length} הושלמו · ${overdue} באיחור`)}</span>:null}</header>
 <p>{pick('Task progress only. Robot issues and stock risks are tracked separately.','התקדמות המשימות בלבד. תקלות רובוט וסיכוני מלאי מוצגים בנפרד.')}</p>
 {message?<p role="alert">{message}</p>:null}{loading?<p>{pick('Loading…','טוען…')}</p>:!tasks.length?<p>{pick('No visible preparation tasks linked yet.','טרם קושרו משימות הכנה גלויות.')}</p>:<ul>{tasks.map(t=><li key={t.id}><button type="button" onClick={()=>navigate(`/projects?project=${t.project_id}&task=${t.id}`)}><strong>{t.status==='done'?'✓ ':''}{t.title}</strong><small>{t.owner??pick('Unassigned','ללא אחראי')} · {t.due_at?new Date(t.due_at).toLocaleString():pick('No due date','ללא מועד')} · {pick(({todo:'To do',in_progress:'In progress',blocked:'Blocked',done:'Done'} as Record<string,string>)[t.status]??t.status,({todo:'לביצוע',in_progress:'בביצוע',blocked:'חסום',done:'הושלם'} as Record<string,string>)[t.status]??t.status)}</small></button>{manage&&access.can('assign_team_work',t.subteam)?<button type="button" disabled={busy} onClick={()=>void unlink(t.id)} aria-label={pick(`Unlink ${t.title}`,`הסרת קישור ${t.title}`)}>{pick('Unlink','הסרת קישור')}</button>:null}</li>)}</ul>}
 {manage&&!mode?<div className="checklist-actions"><button type="button" disabled={busy} onClick={()=>void prepare('link')}>{pick('Link existing task','קישור משימה קיימת')}</button><button type="button" disabled={busy} onClick={()=>void prepare('new')}>{pick('New preparation task','משימת הכנה חדשה')}</button></div>:null}
 {mode==='no-projects'||mode==='no-tasks'?<div role="status"><p>{mode==='no-projects'?pick('No projects are available for you to assign tasks. Open Projects, choose a team workspace and create a project, then return to this event.','אין פרויקטים זמינים להקצאת משימות. פתחו פרויקטים, בחרו סביבת צוות וצרו פרויקט, ואז חזרו לאירוע.'):pick('No available tasks to link. Create a preparation task first.','אין משימות זמינות לקישור. צרו תחילה משימת הכנה.')}</p><div className="checklist-actions"><button type="button" onClick={()=>navigate('/projects')}>{pick('Open Projects','פתיחת פרויקטים')}</button>{mode==='no-tasks'?<button type="button" disabled={busy} onClick={()=>void prepare('new')}>{pick('New preparation task','משימת הכנה חדשה')}</button>:null}<button type="button" onClick={()=>setMode('')}>{pick('Back','חזרה')}</button></div></div>:mode?<form onSubmit={save}>{mode==='link'?<label>{pick('Existing task','משימה קיימת')}<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{pick('Choose a task','בחירת משימה')}</option>{choices.filter(t=>!tasks.some(x=>x.id===t.id)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>:<><label>{pick('Project','פרויקט')}<select required value={project} onChange={e=>setProject(e.target.value)}><option value="">{pick('Choose a project','בחירת פרויקט')}</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{pick('Task title','כותרת משימה')}<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{pick('Owner','אחראי')}<select required value={owner} onChange={e=>setOwner(e.target.value)}><option value="">{pick('Choose an owner','בחירת אחראי')}</option>{members.map(m=><option key={m.id} value={m.id}>{m.display_name}</option>)}</select></label><label>{pick('Due date','מועד לביצוע')}<input required type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label></>}<div className="checklist-actions"><button disabled={busy}>{pick('Save','שמירה')}</button><button type="button" disabled={busy} onClick={()=>setMode('')}>{pick('Cancel','ביטול')}</button></div></form>:null}</section>;
}
