import {useEffect,useState} from "react";
import {useMemberAuth} from "../lib/memberAuth";
import {useAdminStatus} from "../lib/useAdminStatus";
import {useLocalization} from "../lib/localization";
import {supabase} from "../supabase";
type A={id:string;event_id:string;member_id:string;role:string;status:string;replacement_note:string|null;match_id:string|null};
type P={id:string;display_name:string};
type M={id:string;match_type:string|null;match_number:number|null;red_teams:number[]|null;blue_teams:number[]|null};
type R={id:string;assignment_id:string;requester_id:string;candidate_id:string;status:string;note:string|null};
const label=(m:M|undefined)=>m?`${["qual","qm"].includes(m.match_type?.toLowerCase()??"")?"QM":m.match_type?.toUpperCase()||"M"}${m.match_number??"?"}`:"Event";
function teamFor(a:A,m:M|undefined){if(!m)return null;const hit=/scout_(red|blue)_([123])/.exec(a.role);if(!hit)return null;return (hit[1]==="red"?m.red_teams:m.blue_teams)?.[Number(hit[2])-1]??null;}

export default function CompetitionAssignmentBanner(){
  const {profile}=useMemberAuth(),isAdmin=useAdminStatus(),{pick}=useLocalization();
  const [rows,setRows]=useState<A[]>([]),[people,setPeople]=useState<P[]>([]),[matches,setMatches]=useState<M[]>([]),[requests,setRequests]=useState<R[]>([]),[message,setMessage]=useState(""),[requesting,setRequesting]=useState<A|null>(null),[candidate,setCandidate]=useState(""),[reason,setReason]=useState("");
  const eventId=localStorage.getItem("g3_event_id");
  async function load(){if(!eventId)return;const [a,p,m,r]=await Promise.all([supabase.from("competition_assignments").select("id,event_id,member_id,role,status,replacement_note,match_id").eq("event_id",eventId),supabase.from("team_members").select("id,display_name").eq("active",true),supabase.from("matches").select("id,match_type,match_number,red_teams,blue_teams").eq("event_id",eventId),supabase.from("competition_replacement_requests").select("id,assignment_id,requester_id,candidate_id,status,note").eq("event_id",eventId).in("status",["pending","rejected"])]);setRows((a.data??[]) as A[]);setPeople((p.data??[]) as P[]);setMatches((m.data??[]) as M[]);if(!r.error)setRequests((r.data??[]) as R[]);}
  useEffect(()=>{void load();},[eventId]);
  async function patch(id:string,data:Record<string,unknown>){const {error}=await supabase.from("competition_assignments").update(data).eq("id",id);setMessage(error?.message??pick("Assignment updated.","השיבוץ עודכן."));if(!error)await load();}
  function availableFor(item:A){if(!item.match_id)return [];const busy=new Set(rows.filter(x=>x.match_id===item.match_id&&x.status!=="absent").map(x=>x.member_id));return people.filter(p=>p.id!==item.member_id&&!busy.has(p.id));}
  async function sendRequest(){if(!requesting||!profile||!candidate||!reason.trim())return;const {error}=await supabase.from("competition_replacement_requests").insert({assignment_id:requesting.id,event_id:requesting.event_id,match_id:requesting.match_id,requester_id:profile.id,candidate_id:candidate,note:reason.trim(),original_status:requesting.status});setMessage(error?.message??pick("Replacement request sent. The selected member can accept or reject it.","בקשת ההחלפה נשלחה. החבר/ה שנבחר/ה יכול/ה לאשר או לדחות."));if(!error){setRequesting(null);setCandidate("");setReason("");await load();}}
  async function respond(item:R,answer:"accepted"|"rejected"){const {error}=await supabase.rpc("respond_to_competition_replacement",{request_id:item.id,response:answer});setMessage(error?.message??pick(answer==="accepted"?"Replacement accepted. The match is now assigned to you.":"Replacement declined. The original member was notified.",answer==="accepted"?"ההחלפה אושרה. המשחק משויך אליך כעת.":"ההחלפה נדחתה. החבר/ה המקורי/ת קיבל/ה עדכון."));if(!error)await load();}
  const mine=rows.filter(x=>x.member_id===profile?.id),incoming=requests.filter(x=>x.candidate_id===profile?.id&&x.status==="pending"),rejected=requests.filter(x=>x.requester_id===profile?.id&&x.status==="rejected");
  if(!mine.length&&!incoming.length&&!rejected.length&&!isAdmin)return null;
  return <section className="competition-assignment-banner"><header><div><div className="hub-eyebrow">{pick("My competition role","התפקיד שלי בתחרות")}</div><h2>{mine.length?pick("Your match stations","עמדות המשחק שלך"):pick("Assignment control","בקרת שיבוצים")}</h2></div>{message?<small>{message}</small>:null}</header>
    {incoming.map(r=>{const assignment=rows.find(x=>x.id===r.assignment_id),match=matches.find(x=>x.id===assignment?.match_id),requester=people.find(x=>x.id===r.requester_id);return <article className="replacement-offer" key={r.id}><span><strong>{pick("Replacement requested","בקשת החלפה")}</strong> · {label(match)}<em>{requester?.display_name} · {r.note}</em></span><button onClick={()=>void respond(r,"accepted")}>{pick("Accept","אישור")}</button><button className="secondary" onClick={()=>void respond(r,"rejected")}>{pick("Decline","דחייה")}</button></article>})}
    {rejected.map(r=><article className="replacement-result" key={r.id}><span><strong>{pick("Replacement declined","בקשת ההחלפה נדחתה")}</strong><em>{people.find(x=>x.id===r.candidate_id)?.display_name} · {pick("You remain assigned. Choose another available member if needed.","השיבוץ נשאר אצלך. ניתן לבחור חבר/ה פנוי/ה אחר/ת במידת הצורך.")}</em></span><button onClick={()=>void supabase.from("competition_replacement_requests").update({status:"seen"}).eq("id",r.id).then(()=>load())}>{pick("Dismiss","סגירה")}</button></article>)}
    {mine.map(x=>{const match=matches.find(m=>m.id===x.match_id),team=teamFor(x,match);return <article key={x.id}><span><strong>{label(match)}</strong> · {x.role.replace(/_/g," ")}{team?<em>Team {team}</em>:x.match_id?<em>{pick("Awaiting match draw","ממתין להגרלת קבוצות")}</em>:null}</span><b>{x.status}</b>{x.status==="assigned"?<button onClick={()=>void patch(x.id,{status:"confirmed"})}>{pick("Confirm here","אישור כאן")}</button>:null}{["assigned","confirmed"].includes(x.status)?<button className="secondary" onClick={()=>{setRequesting(x);setCandidate("");setReason("");}}>{pick("Request replacement","בקשת מחליף/ה")}</button>:null}</article>})}
    {requesting?<div className="replacement-picker" role="dialog" aria-label={pick("Choose replacement","בחירת מחליף/ה")}><header><strong>{pick(`Choose an available member for ${label(matches.find(x=>x.id===requesting.match_id))}`,`בחירת חבר/ה פנוי/ה עבור ${label(matches.find(x=>x.id===requesting.match_id))}`)}</strong><button onClick={()=>setRequesting(null)}>×</button></header>{availableFor(requesting).length?<><label>{pick("Available members with no assignment in this match","חברים פנויים ללא שיבוץ במשחק זה")}<select value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">{pick("Choose member…","בחירת חבר/ה…")}</option>{availableFor(requesting).map(p=><option value={p.id} key={p.id}>{p.display_name}</option>)}</select></label><label>{pick("Reason or context","סיבה או הקשר")}<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2}/></label><button disabled={!candidate||!reason.trim()} onClick={()=>void sendRequest()}>{pick("Send replacement request","שליחת בקשת החלפה")}</button></>:<p>{pick("Everyone is already assigned in this match. Ask the assignment lead for help.","לכל החברים כבר יש שיבוץ במשחק זה. יש לפנות לאחראי/ת השיבוצים.")}</p>}</div>:null}
  </section>;
}
