import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {sourceLink} from '../lib/robotResearch';
type Row={source_url:string;title:string;document_id:string|null;current_sha:string|null;reviewed_sha:string|null;checked_at:string|null;state:'unmonitored'|'needs_review'|'changed'|'current'};
export default function CourseSourceReview({courseId,pick}:{courseId:string;pick:(en:string,he:string)=>string}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{let live=true;setRows([]);setError('');void supabase.rpc('training_source_impact',{p_course:courseId}).then(({data,error})=>{if(live){setError(error?pick('Source review is unavailable. Retry; do not assume sources are current.','בדיקת המקורות אינה זמינה. נסו שוב; אין להסיק שהמקורות עדכניים.'):'');setRows(data??[]);}});return()=>{live=false;};},[courseId,version]);
 async function approve(row:Row){setBusy(true);const {error}=await supabase.rpc('review_training_source',{p_course:courseId,p_url:row.source_url,p_document:row.document_id,p_sha:row.current_sha,p_note:notes[row.source_url]??''});setBusy(false);if(error)setError(error.message);else setVersion(v=>v+1);}
 return <details className="academy-source-review"><summary>{pick('Teaching sources & updates','מקורות הוראה ועדכונים')} · {rows.filter(r=>r.state==='changed'||r.state==='needs_review').length} {pick('to review','לבדיקה')}</summary><p>{pick('Review whether source changes affect this course. This records a teaching review; it does not rewrite lessons or alter student qualifications. External sources without an imported revision still require manual checking.','בדקו אם שינויי מקור משפיעים על הקורס. הבדיקה מתועדת ואינה משנה שיעורים או הסמכות. מקורות ללא גרסה מיובאת דורשים בדיקה ידנית.')}</p>{error&&<p role="alert">{error}</p>}<button onClick={()=>setVersion(v=>v+1)} disabled={busy}>{pick('Refresh source status','רענון מצב המקורות')}</button>{rows.map(r=><article key={r.source_url}><h4><a href={sourceLink(r.source_url)} target="_blank" rel="noreferrer">{r.title} ↗</a></h4><strong>{({unmonitored:pick('No tracked revision · check original','אין גרסה במעקב · בדקו מקור'),needs_review:pick('Teaching review needed','נדרשת בדיקת הוראה'),changed:pick('Source changed since teaching review','המקור השתנה מאז בדיקת ההוראה'),current:pick('Reviewed against current imported revision','נבדק מול הגרסה המיובאת הנוכחית')})[r.state]}</strong>{r.checked_at&&<small>{pick('Last checked','נבדק לאחרונה')}: {new Date(r.checked_at).toLocaleString()} · {r.current_sha?.slice(0,12)}</small>}{r.document_id&&r.state!=='current'&&<><label>{pick('What did you verify or update in the lesson?','מה אימתתם או עדכנתם בשיעור?')}<textarea maxLength={4000} value={notes[r.source_url]??''} onChange={e=>setNotes(n=>({...n,[r.source_url]:e.target.value}))}/></label><button disabled={busy||(notes[r.source_url]?.trim().length??0)<3} onClick={()=>void approve(r)}>{pick('Record teaching review','תיעוד בדיקת ההוראה')}</button></>}</article>)}</details>;
}
