import {LearningRobot,StudyArea} from '../lib/robotLearning';
type Pick=(en:string,he:string)=>string;
const wiring='https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-1/intro-to-frc-robot-wiring.html';
export default function ElectricalStudyGuide({area,robot,pick,onFind}:{area:StudyArea;robot:LearningRobot;pick:Pick;onFind:(term:string)=>void}){
 const power=area==='power',can=area==='can',network=area==='network';
 return <section className="rl-electrical-guide" aria-label={pick('Connection guide','מדריך חיבורים')}>
  <strong>{pick('Understand the connections','להבין את החיבורים')}</strong>
  <p>{pick('The 3D view shows named components and mounts. Cable routes, pin assignments and this robot’s complete wiring are not documented by this export.','תצוגת התלת־ממד מציגה רכיבים ותושבות מזוהים. נתיבי הכבלים, חיבורי הפינים והחיווט המלא של הרובוט אינם מתועדים בייצוא הזה.')}</p>
  <div className="rl-guide-badge">{pick('GENERAL FRC EXAMPLE · not this robot’s wiring diagram','דוגמת FRC כללית · לא תרשים החיווט של הרובוט הזה')}</div>
  {(power||area==='electrical')&&<><div className="rl-connection-chain"><span>{pick('Battery +','סוללה +')}</span><b>→</b><button onClick={()=>onFind('breaker')}>{pick('Main breaker','מפסק ראשי')}</button><b>→</b><button onClick={()=>onFind('pdp')}>{pick('Distribution +','חלוקת מתח +')}</button></div><p>{pick('Battery − returns directly to distribution −. Protected outputs supply the robot’s loads. Use the exact device manual for channel, fuse, wire and terminal requirements.','סוללה − מחוברת ישירות לחלוקת מתח −. יציאות מוגנות מזינות את צרכני הרובוט. פעלו לפי מדריך הרכיב המדויק לקביעת ערוץ, נתיך, מוליך והדקים.')}</p></>}
  {(can||area==='electrical')&&<><div className="rl-connection-chain"><span>roboRIO / CAN</span><b>↔</b><span>{pick('CAN devices','רכיבי CAN')}</span><b>↔</b><span>{pick('Bus endpoint','קצה האפיק')}</span></div><p>{pick('CAN carries control data, not motor power. Follow the device-specific bus wiring and termination instructions. CAD placement does not tell us the order of this robot’s CAN devices.','CAN מעביר נתוני בקרה ולא הספק למנוע. יש לפעול לפי הוראות החיווט והסיום של האפיק לרכיבים המדויקים. מיקום ב-CAD אינו מלמד על סדר רכיבי ה-CAN ברובוט.')}</p></>}
  {(network||area==='electrical')&&<><div className="rl-connection-chain"><button onClick={()=>onFind('robot radio')}>{pick('Radio','רדיו')}</button><b>↔</b><span>Ethernet</span><b>↔</b><span>{pick('Robot controller / network','בקר הרובוט / רשת')}</span></div><p>{pick('Ethernet is separate from CAN. Radio power and companion-computer connections depend on the actual hardware; no cable endpoints are inferred here.','Ethernet נפרד מ-CAN. הזנת הרדיו וחיבורי מחשב העזר תלויים בחומרה בפועל; לא מוסקים כאן קצוות כבלים.')}</p></>}
  <a href={wiring} target="_blank" rel="noreferrer">{pick('Open WPILib’s illustrated wiring instructions','פתיחת הוראות החיווט המאוירות של WPILib')} ↗</a>
  {robot==='limestone'&&<p>{pick('Team case study: 1678 describes a pivoting floor for electronics access and CAN failures at wire terminals. Compare access and strain relief, rather than copying a layout without testing it.','מקרה בוחן: 1678 מתארת רצפה מסתובבת לגישה לאלקטרוניקה וכשלי CAN בהדקי מוליכים. השוו נגישות והקלת מאמצים במקום להעתיק פריסה ללא בדיקה.')} <a href="https://www.chiefdelphi.com/t/1678-citrus-circuits-2026-cad-and-robot-code-release/521535/9" target="_blank" rel="noreferrer">{pick('Team evidence','מקור הקבוצה')} ↗</a></p>}
 </section>;
}
