import {parsePlanningDraft} from '../lib/planningDraft';
import {memo,useEffect,useMemo,useState} from 'react';
import {planningStorageKey,readPlanningWorkspace,writePlanningWorkspace} from '../lib/planningStorage';
import {useLocalization} from '../lib/localization';
import TwinNumberInput from './TwinNumberInput';
import {parseSeasonPackage,type SeasonPackage} from '../lib/seasonPackage';
import {planningReference} from '../lib/planningReference';
import {evaluateRoute,rankRoutes,type MotionProfile,type RoutePoint} from '../lib/autonomousPlanning';
import {rankCameraSets,type CameraMount} from '../lib/cameraPlanning';
import {routePoseAt} from '../lib/routePlayback';
import {generateRouteAlternatives} from '../lib/routeGeneration';
import type {Concept} from '../lib/conceptTwin';
import '../styles/engineeringPlanner.css';
const point=(x:number,y:number):RoutePoint=>({x,y,heading:0,action:'none',seconds:0,points:0,success:1});
const initialCameras:CameraMount[]=[0,Math.PI/2,Math.PI,-Math.PI/2].map((yaw,i)=>({id:`Mount ${i+1}`,x:Number((.25*Math.cos(yaw)).toFixed(4)),y:Number((.25*Math.sin(yaw)).toFixed(4)),z:.5,yaw,pitch:0,hfov:Math.PI/2,vfov:Math.PI/3,maxDistance:6,pixelsWide:1280,minTagPixels:16}));
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default memo(function EngineeringPlanner({concept,capacity}:{concept:Concept;capacity:number}){
 return <PlannerWorkspace key={`${planningStorageKey(concept)}:${capacity}`} concept={concept} capacity={capacity}/>;
});
function PlannerWorkspace({concept,capacity}:{concept:Concept;capacity:number}){
 const [restored]=useState(()=>{try{const value=readPlanningWorkspace(localStorage,`${planningStorageKey(concept)}:${capacity}`);if(value&&(value.draft.robot.length!==concept.length||value.draft.robot.width!==concept.width||value.draft.robot.speed!==concept.speed||value.draft.robot.turnRate!==concept.turn))throw Error('Profile mismatch');return {value,failed:false};}catch{return {value:null,failed:true};}});
 const {pick}=useLocalization(),[season,setSeason]=useState<SeasonPackage>(restored.value?.draft.season??planningReference),[route,setRoute]=useState<RoutePoint[]>(restored.value?.draft.route??[point(-6,2.7),point(-4,2.7)]),[selected,setSelected]=useState(0);
 const [acceleration,setAcceleration]=useState(restored.value?.draft.robot.acceleration??2),[clearance,setClearance]=useState(restored.value?.draft.robot.clearance??.1),[seconds,setSeconds]=useState(restored.value?.draft.season.autonomous.seconds??20),[error,setError]=useState('');
 const [cameras,setCameras]=useState(restored.value?.draft.cameras??initialCameras),[maxCameras,setMaxCameras]=useState(restored.value?.maxCameras??2),[saved,setSaved]=useState<{id:string;points:RoutePoint[]}[]>(restored.value?.candidates??[]);
 const [storageStatus,setStorageStatus]=useState<'saved'|'failed'|'blocked'>(restored.failed?'blocked':'saved');
 const [preload,setPreload]=useState(Math.min(capacity,restored.value?.draft.robot.inventory?.preload??0));
 const activeSeason=useMemo(()=>({...season,autonomous:{seconds,reviewed:false}}),[season,seconds]);
 const robot:MotionProfile={length:concept.length,width:concept.width,speed:concept.speed,turnRate:concept.turn,acceleration,clearance,measured:false,inventory:{capacity,preload}};
 useEffect(()=>{
  // Preserve a corrupt/newer stored draft for manual recovery instead of silently overwriting it.
  if(restored.failed)return;
  try{writePlanningWorkspace(localStorage,`${planningStorageKey(concept)}:${capacity}`,{schema:1,draft:{schema:1,status:'unverified-planning-draft',season:activeSeason,robot,route,cameras},candidates:saved,maxCameras});setStorageStatus('saved');}
  catch{setStorageStatus('failed');}
 },[activeSeason,concept.length,concept.width,concept.speed,concept.turn,acceleration,clearance,route,cameras,saved,maxCameras,restored.failed,capacity,preload]);
 const result=evaluateRoute(activeSeason,robot,route),ranked=rankRoutes(activeSeason,robot,saved);
 const [reorder,setReorder]=useState(false),[generated,setGenerated]=useState<ReturnType<typeof generateRouteAlternatives>|null>(null);
 useEffect(()=>setGenerated(null),[route,activeSeason,concept.length,concept.width,concept.speed,concept.turn,acceleration,clearance,capacity,preload]);
 const [playhead,setPlayhead]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{setPlaying(false);setPlayhead(0);},[route,activeSeason,concept.length,concept.width,concept.speed,concept.turn,acceleration,clearance,capacity,preload]);
 useEffect(()=>{if(!playing)return;let handle=0,last=performance.now();const tick=(now:number)=>{const delta=Math.min(.1,(now-last)/1000);last=now;if(document.hidden){setPlaying(false);return;}setPlayhead(t=>Math.min(result.seconds,t+delta));handle=requestAnimationFrame(tick);};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle);},[playing,result.seconds]);
 useEffect(()=>{if(playhead>=result.seconds)setPlaying(false);},[playhead,result.seconds]);
 const preview=result.errors.length?null:routePoseAt(activeSeason,robot,route,playhead);
 const sampleSpacing=Math.max(.5,route.reduce((sum,p,i)=>sum+(i?Math.hypot(p.x-route[i-1].x,p.y-route[i-1].y):0),0)/900);
 const samples=useMemo(()=>route.flatMap((p,i)=>{if(!i)return [p];const a=route[i-1],n=Math.max(1,Math.ceil(Math.hypot(p.x-a.x,p.y-a.y)/sampleSpacing));const delta=Math.atan2(Math.sin(p.heading-a.heading),Math.cos(p.heading-a.heading));return Array.from({length:n},(_,j)=>{const t=(j+1)/n;return {x:a.x+(p.x-a.x)*t,y:a.y+(p.y-a.y)*t,heading:a.heading+delta*t};});}),[route,sampleSpacing]);
 const coverage=useMemo(()=>rankCameraSets(activeSeason,cameras,samples,maxCameras),[activeSeason,cameras,samples,maxCameras]);
 const p=route[selected];
 const update=(patch:Partial<RoutePoint>)=>setRoute(r=>r.map((v,i)=>i===selected?{...v,...patch}:v));
 async function importSeason(file?:File){if(!file)return;try{if(file.size>300000)throw Error('Season package exceeds 300 KB');const next=parseSeasonPackage(JSON.parse(await file.text()));setSeason(next);setSeconds(next.autonomous.seconds);setRoute([point(-next.field.length/4,0),point(0,0)]);setSelected(1);setSaved([]);setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid package');}}
 async function importDraft(file?:File){if(!file)return;try{if(file.size>500000)throw Error('Planning draft exceeds 500 KB');const d=parsePlanningDraft(await file.text());if(d.robot.length!==concept.length||d.robot.width!==concept.width||d.robot.speed!==concept.speed||d.robot.turnRate!==concept.turn||(d.robot.inventory&&d.robot.inventory.capacity!==capacity))throw Error('Robot dimensions or motion limits differ. Match the simulator profile to the exported draft before importing.');setSeason(d.season);setSeconds(d.season.autonomous.seconds);setAcceleration(d.robot.acceleration);setClearance(d.robot.clearance);setPreload(d.robot.inventory?.preload??0);setRoute(d.route);setSelected(0);setCameras(d.cameras);setSaved([]);setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid draft');}}
 const input=(label:string,value:number,onCommit:(n:number)=>void,min:number,max:number,step=.1)=><label>{label}<TwinNumberInput value={Number(value.toFixed(5))} onCommit={onCommit} min={min} max={max} step={step}/></label>;
 return <details className="engineering-planner"><summary>{pick('Engineering planning · routes & camera coverage','תכנון הנדסי · מסלולים וכיסוי מצלמות')}</summary><div className="ep-body">
 <header><div><span className="intel-kicker">{pick('LOCAL PLANNING DRAFT','טיוטת תכנון מקומית')}</span><h2>{pick('Plan the route. Check what the cameras see.','תכננו מסלול. בדקו מה המצלמות רואות.')}</h2></div><button onClick={()=>download(`g3-plan-${season.season}.json`,{schema:1,status:'unverified-planning-draft',season:activeSeason,robot,route,cameras,assumptions:['Simplified stop-at-waypoint timing','Conservative circular robot clearance','Manual action durations, points and probability','Field proxy occlusion only; robot CAD not analyzed'],result})}>{pick('Export planning draft','ייצוא טיוטה')}</button></header>
 <p className="ep-notice">{pick('Planning estimates only. This does not drive the robot or change practice. Field obstacles are simplified; robot CAD, moving mechanisms, traction and camera calibration are not included. Points and action times are your assumptions, not validated game scoring.','אומדני תכנון בלבד. אין הפעלת רובוט או שינוי בתרגול. המכשולים מפושטים; CAD הרובוט, מנגנונים נעים, אחיזה וכיול מצלמה אינם נכללים. הניקוד וזמני הפעולות הם הנחות שלכם ולא ניקוד משחק מאומת.')}</p>
 <p role="status">{storageStatus==='saved'?pick('Draft and comparison routes saved on this browser for this robot profile. Export a copy before changing devices.','הטיוטה ומסלולי ההשוואה נשמרו בדפדפן זה לפרופיל הרובוט. ייצאו עותק לפני מעבר למכשיר אחר.'):storageStatus==='blocked'?pick('A saved workspace could not be read and has been preserved. Automatic saving is paused; export your current work.','סביבת עבודה שמורה לא ניתנת לקריאה ונשמרה ללא שינוי. שמירה אוטומטית מושהית; ייצאו את העבודה הנוכחית.'):pick('Browser storage is unavailable or full. Export your draft before leaving.','האחסון בדפדפן אינו זמין או מלא. ייצאו את הטיוטה לפני יציאה.')}</p>
 <div className="ep-controls"><label>{pick('Import saved planning draft','ייבוא טיוטת תכנון שמורה')}<input type="file" accept=".json,application/json" onChange={e=>{void importDraft(e.target.files?.[0]);e.target.value='';}}/></label><strong>{season.season} · {season.name}</strong><label>{pick('Import season configuration (JSON draft)','ייבוא תצורת עונה (טיוטת JSON)')}<input type="file" accept=".json,application/json" onChange={e=>{void importSeason(e.target.files?.[0]);e.target.value='';}}/></label>{input(pick('Auto duration assumption (s)','משך אוטונומי משוער (ש׳)'),seconds,setSeconds,1,120)}{input(pick('Acceleration assumption (m/s²)','תאוצה משוערת (מ׳/ש׳²)'),acceleration,setAcceleration,.1,10)}{input(pick('Clearance (m)','מרווח (מ׳)'),clearance,setClearance,0,1,.05)}</div>
 {error&&<p role="alert">{error}</p>}
 <div className="ep-controls">{input(pick('Planned preload (game pieces)','טעינה התחלתית מתוכננת'),preload,setPreload,0,capacity,1)}<span>{pick('Hopper capacity from simulator profile','קיבולת מיכל מפרופיל הסימולטור')}: {capacity} · {pick('Planned remaining at handoff','יתרה מתוכננת בהעברה לנהג')}: {result.remainingPieces}</span></div><p>{pick('Inventory assumes each planned intake succeeds. These are planning quantities, not current practice balls or verified season preload limits.','חישוב המלאי מניח שכל איסוף מתוכנן מצליח. אלו כמויות לתכנון ולא כדורי התרגול הנוכחיים או מגבלות טעינה מאומתות של העונה.')}</p>
 <div className="ep-grid"><div><p>{pick('Click the field to add a waypoint. Select a numbered point to edit. Coordinates use the existing centered field frame; +Y is up.','לחצו במגרש להוספת נקודה. בחרו נקודה ממוספרת לעריכה. מערכת הצירים במרכז המגרש; Y חיובי כלפי מעלה.')}</p>
 <svg className="ep-field" viewBox={`0 0 ${season.field.length} ${season.field.width}`} role="img" aria-label={pick('Route and field clearance diagram','תרשים מסלול ומרווחי מגרש')} onClick={e=>{if(route.length>=50)return;const svg=e.currentTarget,ctm=svg.getScreenCTM();if(!ctm)return;const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(ctm.inverse());setRoute(r=>[...r,point(pt.x-season.field.length/2,season.field.width/2-pt.y)]);setSelected(route.length);}}>
 <rect width={season.field.length} height={season.field.width} fill="#14283b"/>{season.field.obstacles.map(b=><rect key={b.id} x={b.min.x+season.field.length/2} y={season.field.width/2-b.max.y} width={b.max.x-b.min.x} height={b.max.y-b.min.y} fill="#657483"/>)}
 {season.field.tags.map(t=><circle key={t.id} cx={t.x+season.field.length/2} cy={season.field.width/2-t.y} r=".07" fill="#6ce5dd"/>)}
 <polyline points={route.map(v=>`${v.x+season.field.length/2},${season.field.width/2-v.y}`).join(' ')} fill="none" stroke="#ff91d2" strokeWidth=".06"/>
 {preview&&<g pointerEvents="none" transform={`translate(${preview.x+season.field.length/2} ${season.field.width/2-preview.y}) rotate(${-preview.heading*180/Math.PI})`}><rect x={-robot.length/2} y={-robot.width/2} width={robot.length} height={robot.width} fill="#4de4cc" fillOpacity=".55" stroke="white" strokeWidth=".04"/><path d={`M 0 0 L ${robot.length/2} 0 M ${robot.length/2-.15} -.12 L ${robot.length/2} 0 L ${robot.length/2-.15} .12`} fill="none" stroke="white" strokeWidth=".04"/></g>}
 {route.map((v,i)=><g key={i} onClick={e=>{e.stopPropagation();setSelected(i);}}><circle cx={v.x+season.field.length/2} cy={season.field.width/2-v.y} r={i===selected?.22:.15} fill={i===selected?'#fff':'#ff91d2'}/><text x={v.x+season.field.length/2+.25} y={season.field.width/2-v.y} fontSize=".3" fill="white">{i+1}</text></g>)}</svg>
 <div className="ep-metrics" aria-live="polite"><span><b>{result.seconds.toFixed(1)} s</b>{pick('Estimated duration','זמן משוער')}</span><span><b>{result.margin.toFixed(1)} s</b>{pick('Time margin','מרווח זמן')}</span><span><b>{result.expectedPoints.toFixed(1)}</b>{pick('Assumed expected points','תוחלת ניקוד לפי הנחות')}</span></div>
 <div className="ep-controls"><button disabled={!preview||!result.seconds} onClick={()=>{if(playhead>=result.seconds)setPlayhead(0);setPlaying(v=>!v);}}>{playing?pick('Pause route preview','השהיית תצוגת המסלול'):pick('Play route preview','הפעלת תצוגת המסלול')}</button><label>{pick('Route preview time','זמן תצוגת המסלול')}<input type="range" min="0" max={result.seconds} step=".05" value={Math.min(playhead,result.seconds)} disabled={!preview} onChange={e=>{setPlaying(false);setPlayhead(Number(e.target.value));}}/></label><span>{playhead.toFixed(1)} / {result.seconds.toFixed(1)} s</span></div>
 {result.errors.length>0&&<ul role="status">{result.errors.map(e=><li key={e}>{e}</li>)}</ul>}
 <p>{pick('Finish / driver takeover','סיום / העברה לנהג')}: X {result.finish.x.toFixed(2)}, Y {result.finish.y.toFixed(2)}, {(result.finish.heading*180/Math.PI).toFixed(0)}°</p>
 </div><section><h3>{pick('Waypoint and action','נקודה ופעולה')}</h3><label>{pick('Selected waypoint','נקודה נבחרת')}<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{route.map((_,i)=><option key={i} value={i}>{i+1}</option>)}</select></label><div className="ep-controls">{input('X (m)',p.x,n=>update({x:n}),-season.field.length/2,season.field.length/2)}{input('Y (m)',p.y,n=>update({y:n}),-season.field.width/2,season.field.width/2)}{input(pick('Heading (°)','כיוון (°)'),p.heading*180/Math.PI,n=>update({heading:n*Math.PI/180}),-180,180,1)}</div>
 <label>{pick('Action at arrival','פעולה בהגעה')}<select value={p.action} onChange={e=>update({action:e.target.value as RoutePoint['action'],seconds:0,points:0,quantity:0})}>{(['none','intake','shoot','wait'] as const).map((a,i)=><option key={a} value={a}>{pick(a,['ללא','איסוף','ירי','המתנה'][i])}</option>)}</select></label>
 {p.action!=='none'&&<div className="ep-controls">{input(pick('Action time (s)','זמן פעולה (ש׳)'),p.seconds,n=>update({seconds:n}),0,120)}{input(pick('Points assumption','ניקוד משוער'),p.points,n=>update({points:n}),0,1000,1)}{input(pick('Success probability assumption','הסתברות הצלחה משוערת'),p.success,n=>update({success:n}),0,1,.05)}</div>}
 {(p.action==='intake'||p.action==='shoot')&&input(pick('Game pieces in this action','כדורים בפעולה זו'),p.quantity??0,n=>update({quantity:n}),1,capacity,1)}
 <div className="ep-controls"><button onClick={()=>{if(route.length<50){setRoute(r=>[...r,point(p.x,p.y)]);setSelected(route.length);}}}>{pick('Add waypoint','הוספת נקודה')}</button><button disabled={route.length<=2} onClick={()=>{setRoute(r=>r.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));}}>{pick('Remove waypoint','הסרת נקודה')}</button><button disabled={saved.length>=20} onClick={()=>setSaved(s=>[...s,{id:`Route ${s.length+1}`,points:structuredClone(route)}])}>{pick('Save candidate for comparison','שמירת מועמד להשוואה')}</button></div>
 <h3>{pick('Compare saved candidates','השוואת מועמדים שמורים')}</h3><p>{pick('Ranks only the routes you saved, by assumed expected points, then time margin. Invalid routes are excluded. It does not search all possible routes.','מדרג רק מסלולים ששמרתם לפי תוחלת הניקוד המשוערת ואז מרווח הזמן. מסלולים לא תקינים אינם מדורגים. אין חיפוש בכל המסלולים האפשריים.')}</p>{ranked.map(r=><button key={r.id} onClick={()=>{setRoute(structuredClone(r.route));setSelected(0);}}>{r.id} · {r.result.expectedPoints.toFixed(1)} / {r.result.seconds.toFixed(1)} s</button>)}{saved.length>0&&!ranked.length&&<p>{pick('No saved candidate meets the configured constraints.','אין מועמד שמור שעומד באילוצים שהוגדרו.')}</p>}
 </section></div>
 <section><h3>{pick('Generate route alternatives','יצירת חלופות למסלול')}</h3><p>{pick('Find detours around the configured obstacle proxies while preserving your start, finish and actions. Up to 8 input waypoints and 200 orders. Points and action durations remain your assumptions; inventory, partner reservations and game legality are not validated yet.','איתור מעקפים סביב המכשולים המוגדרים תוך שמירת ההתחלה, הסיום והפעולות. עד 8 נקודות קלט ו-200 סדרים. הניקוד וזמני הפעולות נשארים הנחות שלכם; מלאי, מסלולי שותפים וחוקיות משחק עדיין אינם נבדקים.')}</p><label><input type="checkbox" checked={reorder} onChange={e=>{setReorder(e.target.checked);setGenerated(null);}}/>{pick('Allow reordering: these intermediate actions are independent','אפשר שינוי סדר: פעולות הביניים האלה עצמאיות')}</label><button disabled={route.length>8} onClick={()=>{try{setGenerated(generateRouteAlternatives(activeSeason,robot,route,reorder));setError('');}catch(e){setError(e instanceof Error?e.message:'Generation failed');}}}>{pick('Generate alternatives','יצירת חלופות')}</button>{route.length>8&&<p>{pick('Reduce the input to 8 waypoints before generating.','צמצמו את הקלט ל-8 נקודות לפני יצירה.')}</p>}{generated&&<div role="status"><p>{generated.evaluated} {pick('orders evaluated','סדרים נבדקו')} · {generated.feasible} {pick('fit the configured time and clearance limits','עומדים במגבלות הזמן והמרווח')} {generated.truncated&&pick('(bounded search; not all orders evaluated)','(חיפוש מוגבל; לא כל הסדרים נבדקו)')}</p>{generated.ranked.map(r=><button key={r.id} onClick={()=>{setRoute(structuredClone(r.route));setSelected(0);}}>{r.id} · {r.result.seconds.toFixed(1)} s · {pick('Load','טעינה')}</button>)}</div>}</section>
 <section><h3>{pick('Camera candidates · localization visibility','מועמדי מצלמות · נראות לתיקון מיקום')}</h3><p>{pick('Geometric visibility along the route at bounded spatial samples (normally 0.5 m). Cyan dots are tags. Edit mount positions and camera specifications. This does not predict localization accuracy or game-piece detection; robot-CAD occlusion is not connected yet.','נראות גאומטרית בדגימה מרחבית מוגבלת לאורך המסלול (בדרך כלל 0.5 מטר). נקודות טורקיז הן תגיות. ערכו מיקומים ומפרטי מצלמה. אין תחזית לדיוק מיקום או לזיהוי כדורים; חסימות CAD הרובוט עדיין אינן מחוברות.')}</p>
 <div className="ep-camera-grid">{cameras.map((c,i)=><details key={c.id}><summary>{pick(`Mount ${i+1}`,`מיקום ${i+1}`)}</summary><fieldset><legend>{pick(`Mount ${i+1}`,`מיקום ${i+1}`)}</legend>{(['x','y','z','yaw','pitch','hfov','vfov','maxDistance','pixelsWide','minTagPixels'] as const).map(k=>{const degrees=['yaw','pitch','hfov','vfov'].includes(k),scale=degrees?180/Math.PI:1;const min=k==='z'?0:['hfov','vfov'].includes(k)?1:degrees?-180:k==='maxDistance'?.1:['pixelsWide','minTagPixels'].includes(k)?1:-3;const max=['hfov','vfov'].includes(k)?179:degrees?180:k==='maxDistance'?50:k==='pixelsWide'?16000:k==='minTagPixels'?c.pixelsWide:3;return <div key={k}>{input(`${k}${degrees?' (°)':''}`,c[k]*scale,n=>setCameras(cs=>cs.map((v,j)=>j===i?{...v,[k]:n/scale,...(k==='pixelsWide'?{minTagPixels:Math.min(v.minTagPixels,n)}:{})}:v)),min,max,degrees||['pixelsWide','minTagPixels'].includes(k)?1:.05)}</div>;})}</fieldset></details>)}</div>
 <label>{pick('Maximum cameras to compare','מספר מצלמות מרבי להשוואה')}<select value={maxCameras} onChange={e=>setMaxCameras(Number(e.target.value))}>{[1,2,3].map(n=><option key={n}>{n}</option>)}</select></label><p aria-live="polite">{coverage[0].ids.join(' + ')} · {coverage[0].covered}/{coverage[0].total} {pick('poses with a visible tag','מיקומים עם תגית נראית')} · {coverage[0].multiTag} {pick('with at least two distinct tags','עם לפחות שתי תגיות שונות')}</p><small>{pick('Best among these candidates under these assumptions. Additional cameras are preferred only when they improve coverage.','הטוב מבין המועמדים וההנחות הללו. מצלמות נוספות מועדפות רק כשיש שיפור בכיסוי.')}</small></section>
 <section><h3>{pick('Robot code integration','שילוב בקוד הרובוט')}</h3><p>{pick('Not ready for robot deployment. Export contains a planning draft, not executable robot code. Repository, exact revision, drivetrain/path-following adapter, command bindings and build validation must be established before code generation is enabled.','לא מוכן לפריסה לרובוט. הייצוא הוא טיוטת תכנון ולא קוד רובוט. יש לקבוע מאגר, גרסה, מתאם הנעה ומעקב מסלול, פקודות ובדיקת בנייה לפני הפעלת יצירת קוד.')}</p></section>
 </div></details>;
}
