import {cameraRouteSamples,faceNext} from '../lib/cameraPose';
import {roundedRoute} from '../lib/routeSmoothing';
import {traversalChecks} from '../lib/routeTraversal';
import PlanningField from './PlanningField';
import {parsePlanningDraft} from '../lib/planningDraft';
import CameraCadAdvisor from './CameraCadAdvisor';
import PlanningCloud from './PlanningCloud';
import {supabase} from '../supabase';
import type {RobotModel} from '../lib/robotModel';
import type {PublishedRobot} from '../lib/publishedRobot';
import darwinProvenance from '../../public/twin/robots/6328-2026/provenance.json';
import {memo,useEffect,useMemo,useRef,useState} from 'react';
import {parsePlanningWorkspace,type PlanningWorkspace,planningStorageKey,readPlanningWorkspace,writePlanningWorkspace} from '../lib/planningStorage';
import {useLocalization} from '../lib/localization';
import TwinNumberInput from './TwinNumberInput';
import {parseSeasonPackage,type SeasonPackage} from '../lib/seasonPackage';
import {planningReference} from '../lib/planningReference';
import {evaluateRoute,rankRoutes,type PlanningPolicy,type Reservation,type MotionProfile,type RoutePoint} from '../lib/autonomousPlanning';
import {rankCameraSets,type CameraMount} from '../lib/cameraPlanning';
import {routePoseAt} from '../lib/routePlayback';
import {generateGoalRoutines,generateRouteAlternatives} from '../lib/routeGeneration';
import type {Concept} from '../lib/conceptTwin';
import '../styles/engineeringPlanner.css';
const point=(x:number,y:number):RoutePoint=>({x,y,heading:0,action:'none',seconds:0,points:0,success:1});
const initialCameras:CameraMount[]=[0,Math.PI/2,Math.PI,-Math.PI/2].map((yaw,i)=>({id:`Mount ${i+1}`,x:Number((.25*Math.cos(yaw)).toFixed(4)),y:Number((.25*Math.sin(yaw)).toFixed(4)),z:.5,yaw,pitch:0,hfov:Math.PI/2,vfov:Math.PI/3,maxDistance:6,pixelsWide:1280,minTagPixels:16}));
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
type PlannerProps={concept:Concept;capacity:number;robotId:PublishedRobot;custom?:RobotModel};
export default memo(function EngineeringPlanner(props:PlannerProps){
 const {pick}=useLocalization();const [assetKey,setAssetKey]=useState(''),[identityError,setIdentityError]=useState(false);
 useEffect(()=>{let active=true;setAssetKey('');setIdentityError(false);const bytes=props.custom?.data??new TextEncoder().encode(props.robotId==='darwin'?JSON.stringify(darwinProvenance.files):'053caf847815cb163632b8f858f5b261e589cb9abae3819b502c016fb57238b8');void crypto.subtle.digest('SHA-256',bytes).then(hash=>{if(active)setAssetKey((props.custom?'custom':props.robotId)+':'+Array.from(new Uint8Array(hash),v=>v.toString(16).padStart(2,'0')).join('')+':'+(props.custom?.scale??1)+':'+(props.custom?.rotation??0));}).catch(()=>{if(active)setIdentityError(true);});return()=>{active=false;};},[props.robotId,props.custom]);
 if(!assetKey)return <p role={identityError?'alert':'status'}>{identityError?pick('Robot identity could not be verified. Reload before opening saved plans.','לא ניתן לאמת את זהות הרובוט. טענו מחדש לפני פתיחת תוכניות שמורות.'):pick('Preparing robot planning workspace…','מכין סביבת תכנון לרובוט…')}</p>;
 return <PlannerWorkspace key={assetKey+planningStorageKey(props.concept)+props.capacity} {...props} assetKey={assetKey}/>;
});
function PlannerWorkspace({concept,capacity,robotId,custom,assetKey}:PlannerProps&{assetKey:string}){
 const [plannerOpen,setPlannerOpen]=useState(false),[focused,setFocused]=useState(false);
 const [mode,setMode]=useState<'route'|'cameras'|'coverage'>('route');
 const expandButton=useRef<HTMLButtonElement>(null),studioRoot=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{if(!focused||!studioRoot.current)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const blocked:{node:HTMLElement;inert:boolean}[]=[];let branch:HTMLElement=studioRoot.current;while(branch.parentElement){for(const sibling of Array.from(branch.parentElement.children)){if(sibling!==branch&&sibling instanceof HTMLElement){blocked.push({node:sibling,inert:sibling.inert});sibling.inert=true;}}branch=branch.parentElement;}const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setFocused(false);expandButton.current?.focus();}if(e.key==='Tab'){const nodes=Array.from(studioRoot.current!.querySelectorAll<HTMLElement>('button:not(:disabled),select,input:not(:disabled),summary,a[href]')).filter(n=>n.getClientRects().length>0);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',escape);return()=>{document.body.style.overflow=old;blocked.forEach(({node,inert})=>node.inert=inert);document.removeEventListener('keydown',escape);};},[focused]);
 const [restored]=useState(()=>{try{const value=readPlanningWorkspace(localStorage,`${planningStorageKey(concept)}:${capacity}:${assetKey}`);if(value&&(value.draft.robot.length!==concept.length||value.draft.robot.width!==concept.width||value.draft.robot.speed!==concept.speed||value.draft.robot.turnRate!==concept.turn))throw Error('Profile mismatch');return {value,failed:false};}catch{return {value:null,failed:true};}});
 const {pick}=useLocalization(),[season,setSeason]=useState<SeasonPackage>(restored.value?.draft.season??planningReference),[route,setRoute]=useState<RoutePoint[]>(restored.value?.draft.route??[point(-6,2.7)]),[selected,setSelected]=useState(0);
 const [beforeRound,setBeforeRound]=useState<RoutePoint[]|null>(null);
 const [placingStart,setPlacingStart]=useState(false),[showEditor,setShowEditor]=useState(false),[selectedCamera,setSelectedCamera]=useState(0);
 const [acceleration,setAcceleration]=useState(restored.value?.draft.robot.acceleration??2),[clearance,setClearance]=useState(restored.value?.draft.robot.clearance??.1),[seconds,setSeconds]=useState(restored.value?.draft.season.autonomous.seconds??20),[error,setError]=useState('');
 const [cameras,setCameras]=useState(restored.value?.draft.cameras??initialCameras),[maxCameras,setMaxCameras]=useState(restored.value?.maxCameras??2),[saved,setSaved]=useState<{id:string;points:RoutePoint[]}[]>(restored.value?.candidates??[]);
 const [storageStatus,setStorageStatus]=useState<'saved'|'failed'|'blocked'>(restored.failed?'blocked':'saved');
 const [preload,setPreload]=useState(Math.min(capacity,restored.value?.draft.robot.inventory?.preload??0));
 const [reserveSeconds,setReserveSeconds]=useState(restored.value?.draft.robot.constraints?.reserveSeconds??1),[reservations,setReservations]=useState<Reservation[]>(restored.value?.draft.robot.constraints?.reservations??[]);
 const [policy,setPolicy]=useState<{id:string;revision:number;policy:PlanningPolicy;sources:{url:string;page:number}[]}|null>(null),[policyStatus,setPolicyStatus]=useState('loading'),[policyRefresh,setPolicyRefresh]=useState(0);
 useEffect(()=>{let active=true;setPolicy(null);setPolicyStatus('loading');void supabase.rpc('current_frc_planning_policy',{p_season:season.season}).then(({data,error})=>{if(!active)return;if(error||!data){setPolicyStatus('unverified');return;}const p=data.policy;if(!p||![p.seconds,p.maxPreload,p.pointsPerPiece].every(Number.isInteger)||p.seconds<1||p.seconds>120||p.maxPreload<0||p.maxPreload>999||p.pointsPerPiece<0||p.pointsPerPiece>999){setPolicyStatus('unverified');return;}setPolicy(data);setPolicyStatus('current');});return()=>{active=false;};},[season.season,policyRefresh]);
 const activeSeason=useMemo(()=>({...season,autonomous:{seconds,reviewed:false}}),[season,seconds]);
 const robot:MotionProfile={length:concept.length,width:concept.width,height:concept.height,speed:concept.speed,turnRate:concept.turn,acceleration,clearance,measured:false,...(policy?{policy:policy.policy}:{}),inventory:{capacity,preload},constraints:{reserveSeconds,reservations}};
 useEffect(()=>{
  // Preserve a corrupt/newer stored draft for manual recovery instead of silently overwriting it.
  if(restored.failed)return;
  try{writePlanningWorkspace(localStorage,`${planningStorageKey(concept)}:${capacity}:${assetKey}`,{schema:1,draft:{schema:1,status:'unverified-planning-draft',assetKey,season:activeSeason,robot,route,cameras},candidates:saved,maxCameras});setStorageStatus('saved');}
  catch{setStorageStatus('failed');}
 },[activeSeason,concept.length,concept.width,concept.height,concept.speed,concept.turn,acceleration,clearance,route,cameras,saved,maxCameras,restored.failed,capacity,preload,reserveSeconds,reservations,policy]);
 const traversal=season.season===2026&&season.revision==='2026-planning-reference-v1'?traversalChecks(route,robot):[];
 const result=evaluateRoute(activeSeason,robot,route),ranked=rankRoutes(activeSeason,robot,saved);
 const [reorder,setReorder]=useState(false),[generated,setGenerated]=useState<ReturnType<typeof generateRouteAlternatives>|null>(null),[goalResults,setGoalResults]=useState<ReturnType<typeof generateGoalRoutines>|null>(null);
 useEffect(()=>{setGenerated(null);setGoalResults(null);},[route,activeSeason,concept.length,concept.width,concept.height,concept.speed,concept.turn,acceleration,clearance,capacity,preload,reserveSeconds,reservations]);
 const [playhead,setPlayhead]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{setPlaying(false);setPlayhead(0);},[route,activeSeason,concept.length,concept.width,concept.height,concept.speed,concept.turn,acceleration,clearance,capacity,preload,reserveSeconds,reservations]);
 useEffect(()=>{if(!playing)return;let handle=0,last=performance.now();const tick=(now:number)=>{const delta=Math.min(.1,(now-last)/1000);last=now;if(document.hidden){setPlaying(false);return;}setPlayhead(t=>Math.min(result.seconds,t+delta));handle=requestAnimationFrame(tick);};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle);},[playing,result.seconds]);
 useEffect(()=>{if(playhead>=result.seconds)setPlaying(false);},[playhead,result.seconds]);
 const preview=result.errors.length?{...route[0],done:false,phase:'start',waypoint:0}:routePoseAt(activeSeason,robot,route,playhead);
 const sampleSpacing=Math.max(.5,route.reduce((sum,p,i)=>sum+(i?Math.hypot(p.x-route[i-1].x,p.y-route[i-1].y):0),0)/900);
 const samples=useMemo(()=>cameraRouteSamples(route,sampleSpacing),[route,sampleSpacing]);
 const coverage=useMemo(()=>rankCameraSets(activeSeason,cameras,samples,maxCameras),[activeSeason,cameras,samples,maxCameras]);
 const p=route[selected];
 const update=(patch:Partial<RoutePoint>)=>setRoute(r=>r.map((v,i)=>i===selected?{...v,...patch}:v));
 async function importSeason(file?:File){if(!file)return;try{if(file.size>300000)throw Error('Season package exceeds 300 KB');const next=parseSeasonPackage(JSON.parse(await file.text()));setSeason(next);setSeconds(next.autonomous.seconds);setRoute([point(-next.field.length/4,0)]);setSelected(0);setSaved([]);setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid package');}}
 function loadWorkspace(workspace:PlanningWorkspace){const d=workspace.draft;if(d.assetKey&&d.assetKey!==assetKey)throw Error('This plan belongs to different CAD bytes, scale or orientation. Select its original robot model.');if(d.robot.length!==concept.length||d.robot.width!==concept.width||(d.robot.height!==undefined&&d.robot.height!==concept.height)||d.robot.speed!==concept.speed||d.robot.turnRate!==concept.turn||(d.robot.inventory&&d.robot.inventory.capacity!==capacity))throw Error('Robot profile differs. Match dimensions, motion limits and capacity before loading.');setSeason(d.season);setSeconds(d.season.autonomous.seconds);setAcceleration(d.robot.acceleration);setClearance(d.robot.clearance);setPreload(d.robot.inventory?.preload??0);setReserveSeconds(d.robot.constraints?.reserveSeconds??1);setReservations(d.robot.constraints?.reservations??[]);setRoute(d.route);setSelected(0);setCameras(d.cameras);setSaved(workspace.candidates);setMaxCameras(workspace.maxCameras);setError('');}
 async function importDraft(file?:File){if(!file)return;try{if(file.size>750000)throw Error('Workspace exceeds 750 KB');const text=await file.text(),value=JSON.parse(text);loadWorkspace(value.draft?parsePlanningWorkspace(text):{schema:1,draft:parsePlanningDraft(text),candidates:[],maxCameras:2});}catch(e){setError(e instanceof Error?e.message:'Invalid draft');}}
 const workspace:PlanningWorkspace={schema:1,draft:{schema:1,status:'unverified-planning-draft',assetKey,season:activeSeason,robot,route,cameras},candidates:saved,maxCameras};
 const input=(label:string,value:number,onCommit:(n:number)=>void,min:number,max:number,step=.1)=><label>{label}<TwinNumberInput value={Number(value.toFixed(5))} onCommit={onCommit} min={min} max={max} step={step}/></label>;
 const playbackControls=(<div className="ep-controls ep-playback"><button disabled={!!result.errors.length||!result.seconds} onClick={()=>{if(playhead>=result.seconds)setPlayhead(0);setPlaying(v=>!v);}}>{playing?pick('Pause route preview','השהיית תצוגת המסלול'):pick('Play route preview','הפעלת תצוגת המסלול')}</button><label>{pick('Route preview time','זמן תצוגת המסלול')}<input type="range" min="0" max={result.seconds} step=".05" value={Math.min(playhead,result.seconds)} disabled={!preview} onChange={e=>{setPlaying(false);setPlayhead(Number(e.target.value));}}/></label><span>{playhead.toFixed(1)} / {result.seconds.toFixed(1)} s</span></div>);
 return <details ref={studioRoot} className={`engineering-planner ep-studio ep-mode-${mode}${focused?' ep-focused':''}${showEditor?' ep-editor-open':''}`} onToggle={e=>{const open=e.currentTarget.open;setPlannerOpen(open);if(!open)setFocused(false);}}><summary>{pick('Engineering planning · routes & camera coverage','תכנון הנדסי · מסלולים וכיסוי מצלמות')}</summary><div className="ep-body">
 <header><div><span className="intel-kicker">{pick('FIELD → ROUTE → REVIEW','מגרש ← מסלול ← בדיקה')}</span><h2>{pick('Field & Robot Studio','סטודיו מגרש ורובוט')}</h2><span className="ep-profile">{season.season} · {season.name} / {custom?pick('Custom robot','רובוט מותאם'):robotId==='darwin'?'6328 Darwin':'KitBot'}</span></div><div className="ep-controls"><button ref={expandButton} onClick={()=>{setFocused(v=>!v);setShowEditor(false);}}>{focused?pick('Exit planning full screen','יציאה ממסך תכנון מלא'):pick('Expand field','הגדלת המגרש')}</button><button onClick={()=>download(`g3-plan-${season.season}.json`,{schema:1,status:'unverified-planning-draft',assetKey,season:activeSeason,robot,route,cameras,assumptions:['Continuous polyline timing; shoot/wait stops; intake during incoming travel','Swept oriented robot footprint; bounded envelope expansion','Manual action durations, points and probability','Route clearance uses simplified solids; camera CAD analysis is separate'],result})}>{pick('Export planning draft','ייצוא טיוטה')}</button></div></header>
 <nav className="ep-mode-nav" aria-label={pick('Studio mode','מצב סטודיו')}>{(['route','cameras','coverage'] as const).map((v,i)=><button key={v} aria-pressed={mode===v} onClick={()=>{setMode(v);setShowEditor(false);}}>{pick(['Plan route','Place cameras','Review coverage'][i],['תכנון מסלול','מיקום מצלמות','בדיקת כיסוי'][i])}</button>)}<span role="status">{storageStatus==='saved'?pick('Saved on this browser','נשמר בדפדפן זה'):pick('Export to preserve your work','ייצאו לשמירת העבודה')}</span>{focused&&<button className="ep-inspector-toggle" aria-expanded={showEditor} onClick={()=>setShowEditor(v=>!v)}>{showEditor?pick('Hide settings','הסתרת הגדרות'):pick('Show settings','הצגת הגדרות')}</button>}</nav>
 <div className="ep-route-pane" hidden={mode!=='route'}>
 <div className="ep-route-toolbar"><button disabled={route.length<3||route.length>20} onClick={()=>{try{const next=roundedRoute(route);setBeforeRound(structuredClone(route));setRoute(next);setSelected(0);setError('');}catch(e){setError(e instanceof Error?e.message:'Smoothing failed');}}}>{pick('Round drive-through corners','עיגול פינות נסיעה')}</button>{beforeRound&&<button onClick={()=>{setRoute(beforeRound);setBeforeRound(null);setSelected(0);}}>{pick('Undo rounding','ביטול עיגול')}</button>}<button aria-pressed={placingStart} onClick={()=>{setPlacingStart(v=>!v);setSelected(0);}}>{pick('Place robot start','מיקום התחלת הרובוט')}</button><button onClick={()=>{setRoute([{...route[0],action:'none',seconds:0,points:0,quantity:0}]);setSelected(0);setPlaying(false);setPlacingStart(false);}}>{pick('Reset route','איפוס מסלול')}</button><span>{placingStart?pick('Click the field to move the robot start.','לחצו במגרש להזזת נקודת ההתחלה.'):route.length===1?pick('Position the robot, then click the field to add your first route point.','מקמו את הרובוט ואז לחצו במגרש להוספת נקודת המסלול הראשונה.'):pick('Click to add a point; select any numbered point to edit or delete it.','לחצו להוספת נקודה; בחרו נקודה ממוספרת לעריכה או מחיקה.')}</span></div><div className="ep-grid"><div className="ep-route-stage"><p>{pick('Click the field to add a waypoint. Select a numbered point to edit. Coordinates use the existing centered field frame; +Y is up.','לחצו במגרש להוספת נקודה. בחרו נקודה ממוספרת לעריכה. מערכת הצירים במרכז המגרש; Y חיובי כלפי מעלה.')}</p>
 <PlanningField season={season} active={plannerOpen}><svg className="ep-field" viewBox={`0 0 ${season.field.length} ${season.field.width}`} role="img" aria-label={pick('Route and field clearance diagram','תרשים מסלול ומרווחי מגרש')} onClick={e=>{if(route.length>=50&&!placingStart)return;const svg=e.currentTarget,ctm=svg.getScreenCTM();if(!ctm)return;const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(ctm.inverse());const next=point(pt.x-season.field.length/2,season.field.width/2-pt.y);if(placingStart){setRoute(r=>[{...r[0],x:next.x,y:next.y},...r.slice(1)]);setSelected(0);setPlacingStart(false);}else{setRoute(r=>[...r,next]);setSelected(route.length);}}}>
 {season.field.tags.map(t=><circle key={t.id} cx={t.x+season.field.length/2} cy={season.field.width/2-t.y} r=".07" fill="#6ce5dd"/>)}
 {traversal.map(t=>{const a=route[Math.max(0,t.leg-1)],b=route[t.leg];return <line key={t.leg+t.kind} pointerEvents="none" x1={a.x+season.field.length/2} y1={season.field.width/2-a.y} x2={b.x+season.field.length/2} y2={season.field.width/2-b.y} stroke={t.kind==='bump'?'#f9cf66':'#ff657e'} strokeWidth=".22" opacity=".65"/>;})}
 <polyline points={route.map(v=>`${v.x+season.field.length/2},${season.field.width/2-v.y}`).join(' ')} fill="none" stroke="#ff91d2" strokeWidth=".06"/>
 {preview&&<g pointerEvents="none" transform={`translate(${preview.x+season.field.length/2} ${season.field.width/2-preview.y}) rotate(${-preview.heading*180/Math.PI})`}><rect x={-robot.length/2} y={-robot.width/2} width={robot.length} height={robot.width} fill="#4de4cc" fillOpacity=".55" stroke="white" strokeWidth=".04"/><path d={`M 0 0 L ${robot.length/2} 0 M ${robot.length/2-.15} -.12 L ${robot.length/2} 0 L ${robot.length/2-.15} .12`} fill="none" stroke="white" strokeWidth=".04"/></g>}
 {route.map((v,i)=><g key={i} onClick={e=>{e.stopPropagation();setSelected(i);if(focused)setShowEditor(true);}}><circle cx={v.x+season.field.length/2} cy={season.field.width/2-v.y} r={i===selected?.22:.15} fill={i===selected?'#fff':'#ff91d2'}/><text x={v.x+season.field.length/2+.25} y={season.field.width/2-v.y} fontSize=".3" fill="white">{i===0?pick('Start','התחלה'):i}</text></g>)}</svg></PlanningField>
 <div className="ep-assumptions">{pick('Simulation estimate · configured robot','הערכת סימולציה · רובוט מוגדר')}: {robot.length.toFixed(2)} × {robot.width.toFixed(2)} × {concept.height.toFixed(2)} m · {pick('speed / acceleration are unmeasured assumptions','מהירות ותאוצה הן הנחות שלא נמדדו')}</div>
 {traversal.length>0&&<details className="ep-route-warnings"><summary>{pick('Field traversal review','בדיקת מעברים במגרש')} · {traversal.length}</summary>{traversal.map(t=><button key={t.leg+t.kind} onClick={()=>{setSelected(t.leg);setShowEditor(true);}}>{pick('Point','נקודה')} {t.leg} · {pick(t.message,t.kind==='height'?'גובה הרובוט והמרווח גדולים מפתח המעבר (0.565 מ׳).':t.kind==='post'?'תומך המעבר: הזיזו את המסלול למרכז הפתח.':'רמפה עבירה: הזמן אינו כולל הפסדי טיפוס ואחיזה שנמדדו.')}</button>)}<small>{pick('Red: adjust the route or robot dimensions before hardware testing. Gold: traversable ramp, uncalibrated timing.','אדום: תקנו מסלול או מידות לפני בדיקת חומרה. זהב: רמפה עבירה, זמן לא מכויל.')}</small></details>}
 <div className="ep-metrics" aria-live="polite"><span><b>{result.seconds.toFixed(1)} s</b>{pick('Estimated duration','זמן משוער')}</span><span><b>{result.margin.toFixed(1)} s</b>{pick('Time margin','מרווח זמן')}</span><span><b>{result.expectedPoints.toFixed(1)}</b>{policy?pick('Expected points · reviewed value','תוחלת ניקוד · ערך שנבדק'):pick('Assumed expected points','תוחלת ניקוד לפי הנחות')}</span></div>
 {playbackControls}
 {result.warnings.length>0&&<details className="ep-route-warnings"><summary>{pick('Clearance checks to review · preview is available','בדיקות מרווח לעיון · ניתן להפעיל תצוגה')} ({result.warnings.length})</summary><ul>{result.warnings.map(w=><li key={w}>{w}</li>)}</ul><p>{pick('Approximate boxes are not the drivable CAD surface. Bumps are traversable; this preview does not certify climbing, trench height or real robot clearance.','תיבות משוערות אינן משטח ה-CAD. ניתן לחצות רמפות; התצוגה אינה מאמתת טיפוס, גובה מעבר או מרווח רובוט אמיתי.')}</p></details>}{result.errors.length>0&&<ul role="status">{result.errors.map(e=><li key={e}>{e}</li>)}</ul>}
 <p>{pick('Finish / driver takeover','סיום / העברה לנהג')}: X {result.finish.x.toFixed(2)}, Y {result.finish.y.toFixed(2)}, {(result.finish.heading*180/Math.PI).toFixed(0)}°</p>
 </div><section><h3>{pick('Waypoint and action','נקודה ופעולה')}</h3><label>{pick('Selected waypoint','נקודה נבחרת')}<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{route.map((_,i)=><option key={i} value={i}>{i===0?pick('Robot start','התחלת הרובוט'):i}</option>)}</select></label><div className="ep-controls">{input('X (m)',p.x,n=>update({x:n}),-season.field.length/2,season.field.length/2)}{input('Y (m)',p.y,n=>update({y:n}),-season.field.width/2,season.field.width/2)}{input(pick('Heading (°)','כיוון (°)'),p.heading*180/Math.PI,n=>update({heading:n*Math.PI/180}),-180,180,1)}</div>
 <label>{pick('Waypoint behavior','התנהגות בנקודה')}<select value={p.action} onChange={e=>update({action:e.target.value as RoutePoint['action'],seconds:0,points:0,quantity:0})}>{(['none','intake','shoot','wait'] as const).map((a,i)=><option key={a} value={a}>{pick(['Drive through','Intake while approaching','Stop and shoot','Stop and wait'][i],['מעבר רציף','איסוף תוך התקרבות','עצירה וירי','עצירה והמתנה'][i])}</option>)}</select></label>
 {p.action!=='none'&&<div className="ep-controls">{input(p.action==='intake'?pick('Minimum collection travel time (s)','זמן נסיעה מינימלי לאיסוף (ש׳)'):pick('Stopped time (s)','זמן עצירה (ש׳)'),p.seconds,n=>update({seconds:n}),0,120)}{!policy&&input(pick('Points assumption','ניקוד משוער'),p.points,n=>update({points:n}),0,1000,1)}{input(pick('Success probability assumption','הסתברות הצלחה משוערת'),p.success,n=>update({success:n}),0,1,.05)}</div>}
 {(p.action==='intake'||p.action==='shoot')&&input(pick('Game pieces in this action','כדורים בפעולה זו'),p.quantity??0,n=>update({quantity:n}),1,capacity,1)}
 <p className="ep-notice">{pick('Robot heading is independent of travel direction. Cameras and clearance use these headings. Set turns explicitly; a curved path alone does not turn a swerve robot.','כיוון הרובוט נפרד מכיוון התנועה. המצלמות והמרווחים משתמשים בכיוון זה. הגדירו סיבובים במפורש; מסלול עקום לבדו אינו מסובב רובוט סוורב.')}</p><div className="ep-controls"><button onClick={()=>update({heading:faceNext(route,selected)})}>{pick('Face next route point','פנייה לנקודה הבאה')}</button><button onClick={()=>update({heading:Math.atan2(-p.y,-p.x)})}>{pick('Face field center','פנייה למרכז המגרש')}</button><button onClick={()=>setRoute(r=>r.map((v,i)=>({...v,heading:faceNext(r,i)})))}>{pick('Set headings along route','הגדרת כיוונים לאורך המסלול')}</button></div><div className="ep-controls"><button onClick={()=>{if(route.length<50){setRoute(r=>[...r,point(p.x,p.y)]);setSelected(route.length);}}}>{pick('Add waypoint','הוספת נקודה')}</button><button disabled={selected===0} onClick={()=>{setRoute(r=>r.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));}}>{pick('Remove waypoint','הסרת נקודה')}</button><button disabled={route.length<2||saved.length>=20} onClick={()=>setSaved(s=>[...s,{id:`Route ${s.length+1}`,points:structuredClone(route)}])}>{pick('Save candidate for comparison','שמירת מועמד להשוואה')}</button></div>
 <details><summary>{pick('Compare saved candidates','השוואת מועמדים שמורים')}</summary><p>{pick('Ranks only the routes you saved, by assumed expected points, then time margin. Invalid routes are excluded. It does not search all possible routes.','מדרג רק מסלולים ששמרתם לפי תוחלת הניקוד המשוערת ואז מרווח הזמן. מסלולים לא תקינים אינם מדורגים. אין חיפוש בכל המסלולים האפשריים.')}</p>{ranked.map(r=><button key={r.id} onClick={()=>{setRoute(structuredClone(r.route));setSelected(0);}}>{r.id} · {r.result.expectedPoints.toFixed(1)} / {r.result.seconds.toFixed(1)} s</button>)}{saved.length>0&&!ranked.length&&<p>{pick('No saved candidate meets the configured constraints.','אין מועמד שמור שעומד באילוצים שהוגדרו.')}</p>}
 </details><button className="ep-primary" onClick={()=>setMode('cameras')}>{pick('Next: camera placement','הבא: מיקום מצלמות')}</button></section></div></div>
 <details className="ep-workspace-tools"><summary>{pick('Workspace tools · rules, saved plans and alternatives','כלי עבודה · חוקים, תוכניות שמורות וחלופות')}</summary>
 <details className="ep-settings"><summary>{pick('Rules, motion limits & imports','חוקים, מגבלות תנועה וייבוא')}</summary> <p className="ep-notice">{pick('Planning estimates only. This does not drive the robot or change practice. Route obstacles are simplified; use the CAD advisor for camera occlusion. Traction and camera calibration require measurements. Action times and success rates are your assumptions. When available, the current reviewed policy supplies scoring values and numeric limits.','אומדני תכנון בלבד. אין הפעלת רובוט או שינוי בתרגול. מכשולי המסלול מפושטים; השתמשו ביועץ CAD לחסימות מצלמה. אחיזה וכיול מצלמה דורשים מדידות. זמני הפעולות ושיעורי ההצלחה הם הנחות שלכם. כשקיימת מדיניות עדכנית שנבדקה, היא מספקת ערכי ניקוד ומגבלות מספריות.')}</p>
 <p role="status">{storageStatus==='saved'?pick('Draft and comparison routes saved on this browser for this robot profile. Export a copy before changing devices.','הטיוטה ומסלולי ההשוואה נשמרו בדפדפן זה לפרופיל הרובוט. ייצאו עותק לפני מעבר למכשיר אחר.'):storageStatus==='blocked'?pick('A saved workspace could not be read and has been preserved. Automatic saving is paused; export your current work.','סביבת עבודה שמורה לא ניתנת לקריאה ונשמרה ללא שינוי. שמירה אוטומטית מושהית; ייצאו את העבודה הנוכחית.'):pick('Browser storage is unavailable or full. Export your draft before leaving.','האחסון בדפדפן אינו זמין או מלא. ייצאו את הטיוטה לפני יציאה.')}</p>
 <div className="ep-controls"><label>{pick('Import saved planning draft','ייבוא טיוטת תכנון שמורה')}<input type="file" accept=".json,application/json" onChange={e=>{void importDraft(e.target.files?.[0]);e.target.value='';}}/></label><strong>{season.season} · {season.name}</strong><label>{pick('Import season configuration (JSON draft)','ייבוא תצורת עונה (טיוטת JSON)')}<input type="file" accept=".json,application/json" onChange={e=>{void importSeason(e.target.files?.[0]);e.target.value='';}}/></label>{input(pick('Auto duration assumption (s)','משך אוטונומי משוער (ש׳)'),seconds,setSeconds,1,120)}{input(pick('Acceleration assumption (m/s²)','תאוצה משוערת (מ׳/ש׳²)'),acceleration,setAcceleration,.1,10)}{input(pick('Clearance (m)','מרווח (מ׳)'),clearance,setClearance,0,1,.05)}</div>
 <section className="ep-notice"><strong>{policy?pick('Official numeric policy','מדיניות מספרית רשמית'):pick('Official policy not verified','מדיניות רשמית לא אומתה')}</strong>{policy?<><p>v{policy.revision} · {policy.policy.seconds}s · {pick('Maximum preload','טעינה מרבית')}: {policy.policy.maxPreload} · {pick('Points per scored piece','נקודות לכדור שנקלע')}: {policy.policy.pointsPerPiece}</p>{policy.sources.map((s,i)=><a key={i} href={s.url.split('#')[0]+'#page='+s.page} target="_blank" rel="noreferrer">{pick('Source page','עמוד מקור')} {s.page} ↗ </a>)}<button onClick={()=>setSeconds(policy.policy.seconds)}>{pick('Use official duration','שימוש במשך הרשמי')}</button><p>{pick('Expected points use scored-piece quantity × official value × your success estimate. Shot feasibility, starting position and complete game legality still require review.','תוחלת הניקוד היא כמות כדורים × ערך רשמי × אומדן הצלחה. היתכנות ירי, מיקום התחלה וחוקיות מלאה דורשים בדיקה.')}</p></>:<p>{policyStatus==='loading'?pick('Checking current reviewed source…','בודק מקור עדכני שנבדק…'):pick('No current policy could be verified. Results use draft assumptions and are not official match predictions.','לא אומתה מדיניות נוכחית. התוצאות מבוססות על הנחות טיוטה ואינן תחזית רשמית למשחק.')}</p>}<button onClick={()=>setPolicyRefresh(v=>v+1)}>{pick('Refresh official policy','רענון מדיניות רשמית')}</button></section>
 {error&&<p role="alert">{error}</p>}
 <details><summary>{pick('Time reserve and partner areas','מרווח זמן ושטחים לשותפים')}</summary>{input(pick('Time to keep in reserve (s)','זמן לשמירה כמרווח (ש׳)'),reserveSeconds,setReserveSeconds,0,seconds,.5)}<p>{pick('Reserved rectangles are partner agreements, not live robot tracking. Route evaluation checks their time windows conservatively. Generated goal routes detour around the entire reserved area.','מלבנים שמורים הם הסכמות עם שותפים, לא מעקב חי. בדיקת מסלול בוחנת חלונות זמן באופן שמרני. מסלולים שנוצרים עוקפים את כל השטח השמור.')}</p>{reservations.map((r,i)=><fieldset key={r.id}><legend>{r.id}</legend><div className="ep-controls">{(['x','y','width','height','from','to'] as const).map(k=>input(pick(({x:'Center X (m)',y:'Center Y (m)',width:'Width (m)',height:'Depth (m)',from:'From second',to:'Until second'})[k],({x:'מרכז X (מ׳)',y:'מרכז Y (מ׳)',width:'רוחב (מ׳)',height:'עומק (מ׳)',from:'משנייה',to:'עד שנייה'})[k]),r[k],n=>setReservations(v=>v.map((x,j)=>j===i?{...x,[k]:n}:x)),k==='x'?-season.field.length/2:k==='y'?-season.field.width/2:k==='width'||k==='height'?.1:k==='to'?r.from+.1:0,k==='from'?r.to-.1:k==='to'?120:k==='x'?season.field.length/2:k==='y'?season.field.width/2:20,.1))}<button onClick={()=>setReservations(v=>v.filter((_,j)=>j!==i))}>{pick('Remove area','הסרת שטח')}</button></div></fieldset>)}<button disabled={reservations.length>=12} onClick={()=>setReservations(v=>[...v,{id:`Partner ${crypto.randomUUID().slice(0,6)}`,x:0,y:0,width:1,height:1,from:0,to:seconds}])}>{pick('Add partner area','הוספת שטח לשותף')}</button></details>
 <div className="ep-controls">{input(pick('Planned preload (game pieces)','טעינה התחלתית מתוכננת'),preload,setPreload,0,capacity,1)}<span>{pick('Hopper capacity from simulator profile','קיבולת מיכל מפרופיל הסימולטור')}: {capacity} · {pick('Planned remaining at handoff','יתרה מתוכננת בהעברה לנהג')}: {result.remainingPieces}</span></div><p>{pick('Inventory assumes each planned intake succeeds. These quantities are separate from practice balls. Any current official preload limit is checked above.','חישוב המלאי מניח שכל איסוף מתוכנן מצליח. כמויות אלו נפרדות מכדורי התרגול. מגבלת טעינה רשמית עדכנית, אם קיימת, נבדקת למעלה.')}</p>
</details>
 <details><summary>{pick('Generate route alternatives','יצירת חלופות למסלול')}</summary><p>{pick('Find detours around the configured obstacle proxies while preserving your start, finish and actions. Up to 8 input waypoints and 200 orders. Action durations remain assumptions; current reviewed scoring values take precedence over manual points. Inventory and partner reservations are checked; complete game legality still requires review.','איתור מעקפים סביב המכשולים המוגדרים תוך שמירת ההתחלה, הסיום והפעולות. עד 8 נקודות קלט ו-200 סדרים. זמני הפעולות נשארים הנחות שלכם; ערכי ניקוד עדכניים שנבדקו גוברים על ניקוד ידני. מלאי ושטחי שותפים נבדקים; חוקיות משחק מלאה עדיין דורשת בדיקה.')}</p><label><input type="checkbox" checked={reorder} onChange={e=>{setReorder(e.target.checked);setGenerated(null);}}/>{pick('Allow reordering: these intermediate actions are independent','אפשר שינוי סדר: פעולות הביניים האלה עצמאיות')}</label><button disabled={route.length<2||route.length>8} onClick={()=>{try{setGenerated(generateRouteAlternatives(activeSeason,robot,route,reorder));setError('');}catch(e){setError(e instanceof Error?e.message:'Generation failed');}}}>{pick('Generate alternatives','יצירת חלופות')}</button>{route.length>8&&<p>{pick('Reduce the input to 8 waypoints before generating.','צמצמו את הקלט ל-8 נקודות לפני יצירה.')}</p>}{generated&&<div role="status"><p>{generated.evaluated} {pick('orders evaluated','סדרים נבדקו')} · {generated.feasible} {pick('fit the configured time and clearance limits','עומדים במגבלות הזמן והמרווח')} {generated.truncated&&pick('(bounded search; not all orders evaluated)','(חיפוש מוגבל; לא כל הסדרים נבדקו)')}</p>{generated.ranked.map(r=><button key={r.id} onClick={()=>{setRoute(structuredClone(r.route));setSelected(0);}}>{r.id} · {r.result.seconds.toFixed(1)} s · {pick('Load','טעינה')}</button>)}</div>}</details>
 <PlanningCloud workspace={workspace} onLoad={loadWorkspace}/><button onClick={()=>download('g3-planning-workspace.json',workspace)}>{pick('Export complete workspace','ייצוא סביבת עבודה מלאה')}</button>
 <details><summary>{pick('Recommend which goals to attempt','המלצה אילו יעדים לנסות')}</summary><p>{pick('Intermediate waypoints are optional goals, each available once. Keep the first point as your start and the last as the driver handoff. This searches goal subsets and orders, preserves inventory and time reserve, and ranks assumed expected points, waypoint tag visibility, then time margin. Confirm action assumptions and validate the selected route with CAD analysis.','נקודות הביניים הן יעדים אפשריים, כל אחד זמין פעם אחת. הראשונה היא ההתחלה והאחרונה היא ההעברה לנהג. החיפוש בוחר יעדים וסדר, שומר מלאי ומרווח זמן, ומדרג תוחלת ניקוד משוערת, נראות תגיות בנקודות ומרווח זמן. אמתו הנחות ובדקו את המסלול שנבחר בניתוח CAD.')}</p><button disabled={route.length>8} onClick={()=>{try{setGoalResults(generateGoalRoutines(activeSeason,robot,route,cameras.filter(c=>coverage[0].ids.includes(c.id))));setError('');}catch(e){setError(e instanceof Error?e.message:'Generation failed');}}}>{pick('Recommend goal routines','המלצה על רצפי יעדים')}</button>{goalResults&&<div role="status"><p>{goalResults.evaluated} {pick('candidates evaluated','מועמדים נבדקו')} · {goalResults.feasible} {pick('feasible within these assumptions','אפשריים לפי ההנחות')} {goalResults.truncated&&pick('· bounded search','· חיפוש מוגבל')}</p>{goalResults.ranked.map(r=><button key={r.id} onClick={()=>{setRoute(structuredClone(r.route));setSelected(0);}}>{r.id} · {r.result.expectedPoints.toFixed(1)} {pick('expected points','נקודות צפויות')} · {r.result.seconds.toFixed(1)} s · {Math.round((r.cameraCoverage??0)*100)}% {pick('waypoint tag coverage · Load','כיסוי תגיות בנקודות · טעינה')}</button>)}</div>}</details>
 </details><div className="ep-camera-pane" hidden={mode==='route'}>{playbackControls}<CameraCadAdvisor studioMode={mode} active={plannerOpen&&mode!=='route'} previewPose={preview} season={activeSeason} robotId={robotId} custom={custom} cameras={cameras} samples={samples} maxCameras={maxCameras} selectedCamera={selectedCamera} onSelectCamera={setSelectedCamera} onPlace={(id,position)=>setCameras(cs=>cs.map(c=>c.id===id?{...c,...position}:c))}> <section className="ep-camera-setup"><h3>{pick('Camera positions','מיקומי מצלמות')}</h3><details className="ep-camera-help"><summary>{pick('How to measure a mount','כיצד מודדים מיקום מצלמה')}</summary><p>{pick('Each candidate is a possible lens position on this robot. Measure from the robot planning origin on the floor: X forward (+), Y left (+), Z upward (+), in metres. Yaw 0° faces forward; +90° faces left. Positive pitch looks upward. Verify the red X, green Y and blue Z axes against your CAD before using measurements.','כל מועמד הוא מיקום אפשרי של מרכז העדשה. מודדים מראשית הרובוט על הרצפה: X קדימה, Y שמאלה, Z למעלה, במטרים. כיוון 0° קדימה ו-90° שמאלה; הטיה חיובית למעלה. ודאו שצירי X האדום, Y הירוק ו-Z הכחול תואמים ל-CAD לפני מדידה.')}</p></details>
 <div className="ep-camera-grid">{cameras.map((c,i)=><details key={c.id} onToggle={e=>{if(e.currentTarget.open)setSelectedCamera(i);}}><summary>{pick(`Mount ${i+1}`,`מיקום ${i+1}`)}</summary><fieldset><legend>{pick(`Mount ${i+1}`,`מיקום ${i+1}`)}</legend><label><input type="checkbox" checked={c.permitted!==false} onChange={e=>setCameras(cs=>cs.map((v,j)=>j===i?{...v,permitted:e.target.checked}:v))}/>{pick('Permitted mounting location','מיקום התקנה מותר')}</label><label>{pick('Camera optics profile','פרופיל אופטיקה')}<select value={c.model??'custom'} onChange={e=>setCameras(cs=>cs.map((v,j)=>j!==i?v:e.target.value==='limelight4-stock'?{...v,model:'limelight4-stock',hfov:82*Math.PI/180,vfov:56.2*Math.PI/180,pixelsWide:1280}:{...v,model:'custom'}))}><option value="custom">{pick('Custom / measured settings','הגדרות מותאמות / מדודות')}</option><option value="limelight4-stock">Limelight 4 · stock lens · 1280 px</option></select></label><small>{pick('Lens or pipeline crop changed? Enter measured FOV and processing width below. Range and tag-size thresholds remain assumptions.','העדשה או חיתוך התמונה השתנו? הזינו זוויות ראייה ורוחב עיבוד מדודים. טווח וסף גודל תגית נשארים הנחות.')}</small>{(['x','y','z','yaw','pitch','hfov','vfov','maxDistance','pixelsWide','minTagPixels'] as const).map(k=>{const degrees=['yaw','pitch','hfov','vfov'].includes(k),scale=degrees?180/Math.PI:1;const min=k==='z'?0:['hfov','vfov'].includes(k)?1:degrees?-180:k==='maxDistance'?.1:['pixelsWide','minTagPixels'].includes(k)?1:-3;const max=['hfov','vfov'].includes(k)?179:degrees?180:k==='maxDistance'?50:k==='pixelsWide'?16000:k==='minTagPixels'?c.pixelsWide:3;return <div key={k}>{input(pick(({x:'Forward / back X (m)',y:'Left / right Y (m)',z:'Lens height above floor (m)',yaw:'Facing direction (°)',pitch:'Tilt up / down (°)',hfov:'Horizontal field of view (°)',vfov:'Vertical field of view (°)',maxDistance:'Assumed usable range (m)',pixelsWide:'Processing image width (pixels)',minTagPixels:'Minimum visible tag size (pixels)'})[k],({x:'קדימה / אחורה X (מ׳)',y:'שמאלה / ימינה Y (מ׳)',z:'גובה העדשה מעל הרצפה (מ׳)',yaw:'כיוון (°)',pitch:'הטיה למעלה / למטה (°)',hfov:'זווית ראייה אופקית (°)',vfov:'זווית ראייה אנכית (°)',maxDistance:'טווח שימושי משוער (מ׳)',pixelsWide:'רוחב תמונת העיבוד (פיקסלים)',minTagPixels:'גודל תגית מינימלי (פיקסלים)'})[k]),c[k]*scale,n=>setCameras(cs=>cs.map((v,j)=>j===i?{...v,[k]:n/scale,...(['hfov','vfov','pixelsWide'].includes(k)?{model:'custom'}:{}),...(k==='pixelsWide'?{minTagPixels:Math.min(v.minTagPixels,n)}:{})}:v)),min,max,degrees||['pixelsWide','minTagPixels'].includes(k)?1:.05)}</div>;})}</fieldset></details>)}</div>
 <label>{pick('Maximum cameras you can install','מספר מצלמות מרבי להתקנה')}<select value={maxCameras} onChange={e=>setMaxCameras(Number(e.target.value))}>{[1,2,3].map(n=><option key={n}>{n}</option>)}</select></label><h4>{pick('Quick estimate · approximate boxes only','אומדן מהיר · תיבות משוערות בלבד')}</h4><p aria-live="polite">{coverage[0].ids.join(' + ')} · {coverage[0].covered}/{coverage[0].total} {pick('sampled robot positions see at least one AprilTag','מיקומי רובוט שנדגמו רואים לפחות תגית אחת')} · {coverage[0].multiTag} {pick('with at least two distinct tags','עם לפחות שתי תגיות שונות')}</p><small>{pick('Best among these candidates under these assumptions. Additional cameras are preferred only when they improve coverage.','הטוב מבין המועמדים וההנחות הללו. מצלמות נוספות מועדפות רק כשיש שיפור בכיסוי.')}</small></section>
</CameraCadAdvisor></div>
 <section className="ep-code-status"><h3>{pick('Robot code · setup required','קוד לרובוט · נדרשת הגדרה')}</h3><p>{pick('Code generation has not been implemented yet. The Export button saves your plan only. To produce compatible robot code, we still need the team software repository, path-following library and intake/shoot commands; then the generator must be implemented and build-tested. There is no generated-code download hidden elsewhere.','יצירת קוד עדיין לא מומשה. כפתור הייצוא שומר תוכנית בלבד. ליצירת קוד תואם נדרשים מאגר התוכנה של הקבוצה, ספריית מעקב מסלול ופקודות איסוף וירי, ולאחר מכן מימוש המחולל ובדיקת בנייה. אין הורדת קוד במקום אחר.')}</p></section>
 </div></details>;
}
