import {useEffect,useState} from 'react';
import {EngineeringCoverage} from './EngineeringCoverage';
import {notifyProjectChange,useProjectRefresh} from '../lib/projectRefresh';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
type RecordRow={id:string;title:string;kind:string;current_revision:number};
type Revision={revision:number;content:Record<string,unknown>;reason:string;created_at:string};
type Person={id:string;display_name:string};
type EngineeringLink={source_id:string;target_id:string;relation:string;dimensions:string[];resolved_at:string|null;resolution:string|null};
export function EngineeringRecords({projectId,canManage,people,tasks}:{projectId:string;canManage:boolean;people:Person[];tasks:{id:string;title:string}[]}){
 const {pick}=useLocalization();const [records,setRecords]=useState<RecordRow[]>([]),[history,setHistory]=useState<Revision[]>([]),[selected,setSelected]=useState<RecordRow|null>(null);
 const [editing,setEditing]=useState(false),[kind,setKind]=useState('requirement'),[title,setTitle]=useState(''),[content,setContent]=useState<Record<string,unknown>>({method:'test',critical:true}),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await supabase.from('project_engineering_records').select('id,title,kind,current_revision').eq('project_id',projectId).order('created_at');if(r.error)setMessage(pick('Engineering records are unavailable.','הרשומות ההנדסיות אינן זמינות.'));else setRecords(r.data??[]);}
 useEffect(()=>{void load();},[projectId]);useProjectRefresh(load);
 async function open(r:RecordRow){setEditing(false);setSelected(r);setHistory([]);const result=await supabase.from('project_engineering_revisions').select('revision,content,reason,created_at').eq('record_id',r.id).order('revision',{ascending:false});if(result.error){setMessage(result.error.message);return;}setHistory(result.data??[]);}
 const labels:Record<string,[string,string]>={description:['Description','תיאור'],owner_id:['Accountable owner','אחראי/ת'],allocation:['Subsystem / allocation','תת־מערכת / שיוך'],acceptance:['Measurable acceptance','תנאי קבלה מדיד'],unit:['Canonical unit','יחידה קנונית'],conditions:['Conditions / tolerance','תנאים / סבילות'],provider:['Provider subteam','צוות מספק'],consumer:['Consumer subteam','צוות מקבל'],contract:['Technical agreement and exact reference','הסכם טכני וייחוס מדויק'],alternatives:['Alternatives considered','חלופות שנבחנו'],rationale:['Decision rationale','נימוק ההחלטה']};
 const [target,setTarget]=useState(''),[relation,setRelation]=useState('depends_on'),[taskId,setTaskId]=useState(''),[linkReason,setLinkReason]=useState(''),[dimension,setDimension]=useState('all');
 const [related,setRelated]=useState<RecordRow[]>([]),[search,setSearch]=useState(''),[links,setLinks]=useState<EngineeringLink[]>([]),[resolution,setResolution]=useState('');
 useEffect(()=>{if(!selected){setLinks([]);return;}let active=true;void supabase.from('project_engineering_links').select('source_id,target_id,relation,dimensions,resolved_at,resolution').or(`source_id.eq.${selected.id},target_id.eq.${selected.id}`).then(r=>{if(active){if(r.error)setMessage(r.error.message);else setLinks(r.data??[]);}});return()=>{active=false;};},[selected]);
 async function findRelated(){try{setBusy(true);const r=await supabase.from('project_engineering_records').select('id,title,kind,current_revision').ilike('title',`%${search.replace(/[%_]/g,'')}%`).order('title').limit(50);if(r.error)throw r.error;setRelated(r.data??[]);}catch{setMessage(pick('Could not load related records. Try again.','לא ניתן לטעון רשומות מקושרות. נסו שוב.'));}finally{setBusy(false);}}
 async function resolve(link:EngineeringLink){if(busy)return;try{setBusy(true);const r=await supabase.rpc('resolve_engineering_conflict',{p_source:link.source_id,p_target:link.target_id,p_reason:resolution});if(r.error)throw r.error;setLinks(v=>v.map(x=>x===link?{...x,resolved_at:new Date().toISOString(),resolution}:x));setResolution('');await load();setSelected(null);setMessage(pick('Resolution recorded. Existing approvals are not renewed automatically.','הפתרון תועד. אישורים קיימים אינם מתחדשים אוטומטית.'));notifyProjectChange();}catch(e){setMessage(e instanceof Error?e.message:pick('Resolution could not be saved. Refresh and try again.','לא ניתן לשמור את הפתרון. רעננו ונסו שוב.'));}finally{setBusy(false);}}
 const fields=['description',...(kind==='requirement'?['allocation','acceptance','unit','conditions']:kind==='interface'?['provider','consumer','contract']:['alternatives','rationale'])];
 function change(key:string,value:unknown){setContent(c=>({...c,[key]:value}));}
 return <details className="review-evidence-editor"><summary>{pick('Engineering requirements & agreements','דרישות והסכמים הנדסיים')} · {records.length}</summary>
 <p>{pick('Versioned engineering records. Approval remains in the task checkpoint.','רשומות הנדסיות עם היסטוריית גרסאות. האישור נשאר בנקודת הביקורת של המשימה.')}</p>
 {message?<p role="status">{message}</p>:null}
 <EngineeringCoverage projectId={projectId} records={records}/>
 <div className="review-buttons">{records.map(r=><button type="button" className="hub-button secondary" key={r.id} onClick={()=>void open(r)}>{r.title} · v{r.current_revision}</button>)}</div>
 {canManage&&!editing?<button type="button" className="hub-button" onClick={()=>{setSelected(null);setHistory([]);setKind('requirement');setTitle('');setContent({method:'test',critical:true});setReason('');setEditing(true);}}>{pick('Add engineering record','הוספת רשומה הנדסית')}</button>:null}
 {selected&&!editing?<section><h4>{selected.title}</h4>{history.map(h=><details key={h.revision} open={h.revision===selected.current_revision}><summary>v{h.revision} · {new Date(h.created_at).toLocaleDateString()}</summary><p>{h.reason}</p><dl>{Object.entries(h.content).map(([k,v])=><div key={k}><dt>{labels[k]?pick(...labels[k]):k}</dt><dd>{k==='owner_id'?people.find(p=>p.id===v)?.display_name??String(v):String(v)}</dd></div>)}</dl></details>)}{canManage&&history.length?<button type="button" className="hub-button secondary" onClick={()=>{setKind(selected.kind);setTitle(selected.title);setContent(history[0].content);setReason('');setEditing(true);}}>{pick('Create next revision','יצירת הגרסה הבאה')}</button>:null}</section>:null}
 {editing?<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);const result=await supabase.rpc('save_project_engineering_record',{p_project:projectId,p_record:selected?.id??null,p_expected_revision:selected?.current_revision??0,p_kind:kind,p_title:title,p_content:content,p_reason:reason});setBusy(false);if(result.error){setMessage(result.error.message);return;}setEditing(false);setSelected(null);notifyProjectChange();setMessage(pick('Revision saved.','הגרסה נשמרה.'));await load();}}>
 <fieldset disabled={busy} className="review-evidence-editor"><legend>{pick('Engineering record','רשומה הנדסית')}</legend>
 <label>{pick('Type','סוג')}<select disabled={!!selected} value={kind} onChange={e=>{setKind(e.target.value);setContent({method:'test',critical:true});}}><option value="requirement">{pick('Requirement','דרישה')}</option><option value="interface">{pick('Interface agreement','הסכם ממשק')}</option><option value="decision">{pick('Engineering decision','החלטה הנדסית')}</option></select></label>
 <label>{pick('Title','כותרת')}<input required minLength={3} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label>
 <label>{pick('Accountable owner','אחראי/ת')}<select required value={String(content.owner_id??'')} onChange={e=>change('owner_id',e.target.value)}><option value="">{pick('Choose person','בחירת אדם')}</option>{people.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label>
 {fields.map(key=><label key={key}>{pick(...labels[key])}<textarea required={!['unit','conditions'].includes(key)} maxLength={2000} rows={2} value={String(content[key]??'')} onChange={e=>change(key,e.target.value)}/></label>)}
 {kind==='requirement'?<><label>{pick('Verification method','שיטת אימות')}<select value={String(content.method??'test')} onChange={e=>change('method',e.target.value)}><option value="test">{pick('Test','בדיקה')}</option><option value="inspection">{pick('Inspection','ביקורת')}</option><option value="analysis">{pick('Analysis','ניתוח')}</option><option value="demonstration">{pick('Demonstration','הדגמה')}</option></select></label><label>{pick('Release critical','קריטית לשחרור')}<select value={String(content.critical??true)} onChange={e=>change('critical',e.target.value==='true')}><option value="true">{pick('Yes','כן')}</option><option value="false">{pick('No','לא')}</option></select></label></>:null}
  <label>{pick('What changed?','מה השתנה?')}<select value={String(content.change_dimension??'all')} onChange={e=>change('change_dimension',e.target.value)}>{[['all','All / uncertain','הכול / לא ודאי'],['geometry','Geometry','גאומטריה'],['mass_material','Mass / material','מסה / חומר'],['interface','Interface','ממשק'],['electrical','Electrical','חשמל'],['software','Software','תוכנה'],['vision','Vision','ראייה'],['rule','Rule','חוק'],['manufacturing','Manufacturing','ייצור'],['documentation','Documentation only','תיעוד בלבד']].map(([v,en,he])=><option key={v} value={v}>{pick(en,he)}</option>)}</select></label><label>{pick('Reason for this revision','סיבה לגרסה זו')}<textarea required minLength={3} maxLength={2000} rows={2} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 <div className="review-buttons"><button type="button" className="hub-button secondary" onClick={()=>setEditing(false)}>{pick('Cancel','ביטול')}</button><button className="hub-button">{busy?pick('Saving…','שומר…'):pick('Save revision','שמירת גרסה')}</button></div>
 </fieldset></form>:null}
 {selected&&!editing?<details><summary>{pick('Link requirements and checkpoint','קישור דרישות ונקודת ביקורת')}</summary>
 {links.length?<section aria-label={pick('Engineering links','קישורים הנדסיים')}>{links.map(link=><article className="review-evidence-item" key={`${link.source_id}-${link.target_id}-${link.relation}`}><strong>{({parent:pick('Parent requirement','דרישת אב'),depends_on:pick('Engineering dependency','תלות הנדסית'),conflicts_with:pick('Requirement conflict','סתירה בין דרישות')} as Record<string,string>)[link.relation]}</strong><p>{[...records,...related].find(r=>r.id===(link.source_id===selected.id?link.target_id:link.source_id))?.title??pick('Related record in another project','רשומה קשורה בפרויקט אחר')}</p><small>{link.dimensions.join(' · ')}</small>{link.relation==='conflicts_with'?link.resolved_at?<p>{pick('Resolved','נפתרה')}: {link.resolution}</p>:canManage?<form onSubmit={e=>{e.preventDefault();void resolve(link);}}><label>{pick('How was this conflict resolved?','כיצד נפתרה הסתירה?')}<textarea required minLength={3} maxLength={2000} value={resolution} onChange={e=>setResolution(e.target.value)}/></label><button className="hub-button" disabled={busy}>{pick('Record resolution','תיעוד פתרון')}</button></form>:<p>{pick('Unresolved conflict','סתירה שלא נפתרה')}</p>:null}</article>)}</section>:null}
 {canManage?<><form onSubmit={e=>{e.preventDefault();void findRelated();}}><label>{pick('Find records across accessible projects','חיפוש רשומות בפרויקטים נגישים')}<input type="search" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="hub-button secondary" disabled={busy}>{pick('Find related records','חיפוש רשומות קשורות')}</button></form>
 <form onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await supabase.rpc('link_project_engineering_record',{p_source:selected.id,p_target:target,p_relation:relation,p_dimensions:[dimension]});setBusy(false);setMessage(r.error?.message??pick('Engineering link saved.','הקישור ההנדסי נשמר.'));if(!r.error){setSelected({...selected});notifyProjectChange();}}}>
 <label>{pick('Related record','רשומה מקושרת')}<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">{pick('Choose record','בחירת רשומה')}</option>{[...new Map([...records,...related].map(r=>[r.id,r])).values()].filter(r=>r.id!==selected.id).map(r=><option value={r.id} key={r.id}>{r.title} · v{r.current_revision}</option>)}</select></label>
  <label>{pick('Relevant change category','קטגוריית שינוי רלוונטית')}<select value={dimension} onChange={e=>setDimension(e.target.value)}>{[['all','Any change','כל שינוי'],['geometry','Geometry','גאומטריה'],['mass_material','Mass / material','מסה / חומר'],['interface','Interface','ממשק'],['electrical','Electrical','חשמל'],['software','Software','תוכנה'],['vision','Vision','ראייה'],['rule','Rule','חוק'],['manufacturing','Manufacturing','ייצור']].map(([v,en,he])=><option value={v} key={v}>{pick(en,he)}</option>)}</select></label>
 <label>{pick('Relationship','קשר')}<select value={relation} onChange={e=>setRelation(e.target.value)}><option value="depends_on">{pick('Depends on','תלויה ב־')}</option><option value="parent">{pick('Parent requirement','דרישת אב')}</option><option value="conflicts_with">{pick('Conflicts with','סתירה עם')}</option></select></label><button className="hub-button" disabled={busy}>{pick('Save link','שמירת קישור')}</button></form>
 <form onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await supabase.rpc('bind_engineering_review',{p_task:taskId,p_record:selected.id,p_reason:linkReason});setBusy(false);setMessage(r.error?.message??pick('Checkpoint linked. A new submission is required.','נקודת הביקורת קושרה. נדרשת הגשה חדשה.'));if(!r.error)notifyProjectChange();}}>
 <p>{pick('Linking requires a configured task checkpoint and resets its current approval.','הקישור דורש נקודת ביקורת מוגדרת במשימה ומאפס את האישור הנוכחי שלה.')}</p>
 <label>{pick('Checkpoint task','משימת נקודת ביקורת')}<select required value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">{pick('Choose task','בחירת משימה')}</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>
 <label>{pick('Reason','סיבה')}<input required minLength={3} maxLength={2000} value={linkReason} onChange={e=>setLinkReason(e.target.value)}/></label><button className="hub-button" disabled={busy}>{pick('Link checkpoint','קישור נקודת ביקורת')}</button></form>
 </>:null}</details>:null}
 </details>;
}
