import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useMemberAuth } from "../lib/memberAuth";
import { useLocalization } from "../lib/localization";
import { supabase } from "../supabase";

type Action = { id:string; title:string; details:string|null; action_type:string; due_at:string|null; priority:string; created_at:string; destination?:string|null };
type State = { action_id:string; status:string; snoozed_until:string|null };

export default function HomeActionInbox({mode="home"}:{mode?:"home"|"work"}) {
  const {profile}=useMemberAuth(),{pick}=useLocalization(),navigate=useNavigate();
  const [actions,setActions]=useState<Action[]>([]),[states,setStates]=useState<State[]>([]),[message,setMessage]=useState(""),[showAll,setShowAll]=useState(false),[loading,setLoading]=useState(true);
  async function load(){if(!profile)return;setLoading(true);const actionResult=await supabase.from("team_actions").select("id,title,details,action_type,due_at,priority,created_at,destination").order("due_at",{ascending:true,nullsFirst:false}).limit(100);let actionData:Action[]=(actionResult.data??[]) as Action[];if(actionResult.error?.message.includes("destination")){const fallback=await supabase.from("team_actions").select("id,title,details,action_type,due_at,priority,created_at").order("due_at",{ascending:true,nullsFirst:false}).limit(100);actionData=(fallback.data??[]) as Action[];}const stateResult=await supabase.from("team_action_states").select("action_id,status,snoozed_until").eq("member_id",profile.id);setActions(actionData);setStates((stateResult.data??[]) as State[]);setLoading(false);}
  useEffect(()=>{void load();},[profile?.id]);
  const available=useMemo(()=>{const now=Date.now();return actions.filter(action=>{const state=states.find(item=>item.action_id===action.id);if(state?.status==="completed")return false;if(state?.status==="snoozed"&&state.snoozed_until&&new Date(state.snoozed_until).getTime()>now)return false;const due=action.due_at?new Date(action.due_at).getTime():null;if(action.action_type==="meeting"&&due&&due<now-12*3600000)return false;if(mode==="work")return true;return !due||due<=now+7*86400000||["high","urgent"].includes(action.priority);});},[actions,states,mode]);
  const visible=showAll?available:available.slice(0,mode==="home"?4:6);
  async function updateState(action:Action,status:string,snoozed_until?:string){if(!profile)return;const now=new Date().toISOString();const {error}=await supabase.from("team_action_states").upsert({action_id:action.id,member_id:profile.id,status,snoozed_until:snoozed_until??null,acknowledged_at:status==="acknowledged"?now:null,completed_at:status==="completed"?now:null,updated_at:now},{onConflict:"action_id,member_id"});setMessage(error?.message??pick("Responsibility updated.","המשימה עודכנה."));if(!error)await load();}
  return <section className={`hub-card home-action-inbox responsibility-inbox responsibility-${mode}`} aria-labelledby={`${mode}-responsibility-title`}><header><div><div className="hub-eyebrow">{pick(mode==="home"?"Your priorities":"Personal command",mode==="home"?"סדר העדיפויות שלך":"מרכז אישי")}</div><h2 id={`${mode}-responsibility-title`}>{pick(mode==="home"?"What needs you":"My responsibilities",mode==="home"?"מה דורש אותך":"האחריות שלי")}</h2></div><span aria-label={pick(`${available.length} active responsibilities`,`${available.length} משימות פעילות`)}>{loading?"—":available.length}</span></header>{message?<small className="action-message" role="status">{message}</small>:null}{loading?<div className="work-skeleton"/>:visible.length?visible.map(action=>{const state=states.find(item=>item.action_id===action.id);return <article className={`priority-${action.priority}`} key={action.id}><button className="responsibility-open" onClick={()=>navigate(action.destination||"/work")}><span>{action.action_type.replace("_"," ")}</span><strong>{action.title}</strong><small>{action.details}{action.due_at?` · ${new Date(action.due_at).toLocaleDateString()}`:""}</small></button><div>{!state||state.status==="new"?<button onClick={()=>void updateState(action,"acknowledged")}>{pick("Acknowledge","אישור קבלה")}</button>:null}<button onClick={()=>void updateState(action,"completed")}>{pick("Complete","השלמה")}</button><button className="secondary" onClick={()=>void updateState(action,"snoozed",new Date(Date.now()+24*3600000).toISOString())}>{pick("Tomorrow","מחר")}</button></div></article>}):<p>{pick(mode==="home"?"Nothing needs your attention in the next seven days.":"You have no active responsibilities.",mode==="home"?"אין פעולות הדורשות את תשומת לבכם בשבעת הימים הקרובים.":"אין לכם אחריות פעילה כרגע.")}</p>}{available.length>(mode==="home"?4:6)?<button className="work-disclosure-link" onClick={()=>setShowAll(value=>!value)}>{showAll?pick("Show priorities only","הצגת עדיפויות בלבד"):pick(`View all ${available.length}`,`הצגת כל ${available.length}`)} <span>{showAll?"↑":"↓"}</span></button>:null}<footer>{pick(mode==="home"?"Home stays focused on the next seven days. Open Work for the complete list.":"Project, training, calendar, competition and robot responsibilities stay synchronized with their source.",mode==="home"?"מסך הבית מתמקד בשבעת הימים הקרובים. הרשימה המלאה נמצאת בעבודה.":"פרויקטים, הכשרות, יומן, תחרות ואחריות לרובוט מסונכרנים עם המקור שלהם.")}</footer></section>;
}
