import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {replenishmentQuantity} from '../lib/operationsPlanning';
type Part={id:string;name:string;unit:string;quantity:number;minimum_quantity:number;stock_alert_enabled?:boolean;target_quantity?:number|null};
export default function InventoryReplenishment({parts,onRequest}:{parts:Part[];onRequest:(id:string,quantity:number)=>void}){
 const {pick}=useLocalization(),[incoming,setIncoming]=useState<{part_id:string;status:string;quantity:number}[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{setLoading(true);void supabase.from('readiness_purchase_counts').select('part_id,status,quantity').then(r=>{setLoading(false);setError(r.error?pick('Incoming quantities unavailable. Refresh before planning a request.','כמויות הרכש אינן זמינות. רעננו לפני תכנון בקשה.'):'');if(!r.error)setIncoming(r.data??[]);});},[parts]);
 const monitored=parts.filter(p=>p.stock_alert_enabled&&p.quantity<=p.minimum_quantity);
 if(!monitored.length)return null;
 return <section className="hub-card replenishment-panel"><h2>{pick('Replenishment planning','תכנון השלמת מלאי')}</h2><p>{pick('Suggested quantities use your target minus stock, approved and ordered quantities. Pending requests are shown separately. Review each draft before submitting.','ההצעה מחושבת לפי היעד פחות מלאי וכמויות שאושרו או הוזמנו. בקשות ממתינות מוצגות בנפרד. בדקו כל טיוטה לפני השליחה.')}</p>{loading?<p>{pick("Loading incoming quantities…","טוען כמויות רכש…")}</p>:error?<p role="alert">{error}</p>:monitored.map(p=>{const count=(status:string)=>Number(incoming.find(r=>r.part_id===p.id&&r.status===status)?.quantity??0);const target=p.target_quantity;const quantity=target==null?null:replenishmentQuantity(Number(p.quantity),Number(target),count('approved'),count('ordered'));return <article key={p.id}><div><strong>{p.name}</strong><small>{pick('On hand','במלאי')}: {p.quantity} {p.unit} · {pick('Target','יעד')}: {target??'—'}</small><small>{pick('Approved / ordered / pending','אושר / הוזמן / ממתין')}: {count('approved')} / {count('ordered')} / {count('requested')} {p.unit}</small></div>{quantity===null?<span>{pick('Set a target in Stock monitoring','הגדירו יעד במעקב מלאי')}</span>:quantity>0?<button className="hub-button" onClick={()=>onRequest(p.id,quantity)}>{pick(`Draft request · ${quantity} ${p.unit}`,`טיוטת בקשה · ${quantity} ${p.unit}`)}</button>:<span>{pick('Target covered by stock and approved orders','היעד מכוסה במלאי וברכש שאושר')}</span>}</article>;})}</section>;
}
