import {useEffect,useState,type FormEvent} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
export type InventoryCategory={id:string;scope:string;name:string;active:boolean};
export function useInventoryCategories(){
 const [rows,setRows]=useState<InventoryCategory[]>([]),[error,setError]=useState('');
 async function reload(){const r=await supabase.from('inventory_categories').select('id,scope,name,active').order('name');setError(r.error?.message??'');if(!r.error)setRows(r.data??[]);}
 useEffect(()=>{void reload();},[]);return {rows,error,reload};
}
export default function InventoryCategories({rows,scope,error,onSaved,onClose}:{rows:InventoryCategory[];scope:string;error:string;onSaved:()=>void;onClose:()=>void}){
 const {pick}=useLocalization(),[id,setId]=useState(''),[name,setName]=useState(''),[active,setActive]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(e:FormEvent){e.preventDefault();setBusy(true);const r=await supabase.rpc('save_inventory_category',{p_id:id||null,p_scope:scope,p_name:name.trim(),p_active:active});setBusy(false);if(r.error){setMessage(pick('Could not save. Use a unique category name and check administrator access.','לא ניתן לשמור. השתמשו בשם ייחודי ובדקו הרשאת מנהל.'));return;}setId('');setName('');setActive(true);setMessage(pick('Category saved.','הקטגוריה נשמרה.'));onSaved();}
 return <section className="hub-card category-manager" aria-label={pick('Manage categories','ניהול קטגוריות')}><header><h2>{pick(scope==='parts'?'Part categories':'Equipment categories',scope==='parts'?'קטגוריות חלקים':'קטגוריות ציוד')}</h2><button type="button" onClick={onClose}>{pick('Close','סגירה')}</button></header><p>{pick('Rename updates existing items. Disable removes a category from new-item choices while preserving existing records.','שינוי שם מעדכן פריטים קיימים. השבתה מסירה קטגוריה מאפשרויות לפריטים חדשים ושומרת רשומות קיימות.')}</p>{error?<p role="alert">{pick('Category setup is unavailable. Apply the category SQL and refresh.','הגדרת הקטגוריות אינה זמינה. הפעילו את קובץ הקטגוריות ורעננו.')}</p>:<><label>{pick('Edit an existing category, or add a new one','עריכת קטגוריה קיימת או הוספת חדשה')}<select value={id} onChange={e=>{const row=rows.find(r=>r.id===e.target.value);setId(row?.id??'');setName(row?.name??'');setActive(row?.active??true);setMessage('');}}><option value="">{pick('+ New category','+ קטגוריה חדשה')}</option>{rows.filter(r=>r.scope===scope).map(r=><option key={r.id} value={r.id}>{r.name}{r.active?'':pick(' (disabled)',' (מושבתת)')}</option>)}</select></label><form className="operations-planning-form" onSubmit={save}><label>{pick('Category name','שם הקטגוריה')}<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>{pick('Available for new items','זמינה לפריטים חדשים')}</label><button disabled={busy} className="hub-button">{pick('Save category','שמירת קטגוריה')}</button></form></>}{message?<p role="status">{message}</p>:null}</section>;
}
