import {FormEvent,useEffect,useRef,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import AccessibleDialog from './AccessibleDialog';
import {CheckItem,checkSummary,DiscoveredDocument,invokeSourceCheck,KnowledgeSeason,SourceCheck,SourceWatch} from '../lib/knowledgeSources';
import '../styles/knowledgeSources.css';

export default function KnowledgeSourceCenter({season,admin,onSeasonAdded,onEvidenceChanged}:{season:number;admin:boolean;onSeasonAdded:(season:KnowledgeSeason)=>void;onEvidenceChanged:()=>void}){
 const {pick,language}=useLocalization();
 const [watches,setWatches]=useState<SourceWatch[]>([]),[run,setRun]=useState<SourceCheck|null>(null),[items,setItems]=useState<CheckItem[]>([]),[documents,setDocuments]=useState<DiscoveredDocument[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[running,setRunning]=useState(false),[configure,setConfigure]=useState(false),[saving,setSaving]=useState(false),[formError,setFormError]=useState('');
 const [page,setPage]=useState(0),[total,setTotal]=useState(0);const generation=useRef(0),busy=useRef(false),cancelled=useRef(false);
 const date=(value:string)=>new Date(value).toLocaleString(language==='he'?'he-IL':'en-GB',{dateStyle:'medium',timeStyle:'short'});
 const itemTitle=(item:CheckItem)=>item.kind==='listing'&&item.title==='Season materials'?pick('Season materials','חומרי העונה'):item.kind==='listing'&&item.title==='Playing field'?pick('Playing field','מגרש המשחק'):item.title;
 function itemNote(item:CheckItem){
  if(!item.note)return pick('Waiting to be checked','ממתין לבדיקה');
  if(language!=='he')return item.note;
  if(item.note.startsWith('Source fingerprint checked.'))return 'גרסת המקור נבדקה. תוכן המסמך עדיין לא אונדקס או נסקר.';
  if(item.note.startsWith('Publisher confirms'))return 'האתר המפרסם אישר שהמסמך לא השתנה. קובץ ה-PDF לא הורד שוב.';
  if(item.note.includes('format is linked only'))return 'הפורמט מוצג כקישור בלבד. פתחו את המקור באתר המפרסם.';
  if(item.note.startsWith('No ')&&item.note.includes('document links'))return `לא נמצאו כאן קישורי מסמכים לעונת ${season}. ייתכן שהפרסום טרם הושלם או שמבנה העמוד השתנה.`;
  if(item.note.includes('season-specific document links found'))return `${item.note.match(/^\d+/)?.[0]??''} קישורי מסמכים של העונה אותרו. המסמכים נשארים באתר המפרסם.`;
  if(item.note.includes('128 MB'))return 'מכסת ההורדה לבדיקה זו נוצלה. יתר המקורות לא הורדו.';
  if(item.note.includes('document check limit'))return 'מכסת המסמכים לבדיקה זו נוצלה. חלק מהקישורים טרם נבדקו.';
  if(item.note.includes('download limit'))return 'המסמך חורג ממגבלת ההורדה. ניתן לפתוח אותו באתר המקור.';
  if(item.note.includes('returned HTTP'))return `המקור אינו זמין כרגע (HTTP ${item.note.match(/HTTP (\d+)/)?.[1]??''}). נסו שוב מאוחר יותר.`;
  if(item.note.includes('instead of a PDF'))return 'במקום PDF התקבל עמוד אינטרנט. פתחו את המקור ונסו שוב מאוחר יותר.';
  return item.note;
 }
 async function refresh(target:number,epoch:number,documentPage=page){
  const [w,d,r]=await Promise.all([
   supabase.from('frc_knowledge_watches').select('*').eq('season',target).eq('enabled',true).order('title'),
   supabase.from('frc_knowledge_documents').select('*',{count:'exact'}).eq('season',target).order('changed_at',{ascending:false}).order('id').range(documentPage*6,documentPage*6+5),
   admin?supabase.from('frc_knowledge_checks').select('*').eq('season',target).order('started_at',{ascending:false}).limit(1):Promise.resolve({data:[],error:null}),
  ]);
  if(w.error||d.error||r.error)throw new Error(pick('Source management is unavailable. Existing evidence remains available.','ניהול המקורות אינו זמין. המקורות הקיימים עדיין זמינים.'));
  const latest=(r.data?.[0]??null) as SourceCheck|null;let rows:CheckItem[]=[];
  if(latest){const result=await supabase.from('frc_knowledge_check_items').select('*').eq('check_id',latest.id).order('kind',{ascending:false}).order('title').range(0,199);if(result.error)throw result.error;rows=(result.data??[]) as CheckItem[];}
  if(epoch===generation.current){setWatches(w.data??[]);setDocuments(d.data??[]);setTotal(d.count??0);setRun(latest);setItems(rows);}
  return latest;
 }
 useEffect(()=>{const epoch=++generation.current;cancelled.current=true;busy.current=false;setRunning(false);setLoading(true);setError('');setRun(null);setItems([]);setDocuments([]);setWatches([]);setPage(0);
  void refresh(season,epoch,0).catch(e=>{if(epoch===generation.current)setError(e.message);}).finally(()=>{if(epoch===generation.current)setLoading(false);});return()=>{generation.current++;cancelled.current=true;};
 },[season,admin]);
 async function loadPage(next:number){setLoading(true);setError('');const epoch=generation.current;try{await refresh(season,epoch,next);if(epoch===generation.current)setPage(next);}catch(e){if(epoch===generation.current)setError(e instanceof Error?e.message:'Could not load sources');}finally{if(epoch===generation.current)setLoading(false);}}
 async function checkNow(retry=false){
  if(busy.current)return;busy.current=true;cancelled.current=false;setRunning(true);setError('');const epoch=generation.current;
  try{
   const result=await invokeSourceCheck(retry?'retry':'start',retry&&run?{checkId:run.id}:{season});if(!result.checkId)throw new Error('Check did not return an identifier.');
   let current=await refresh(season,epoch);
   while(current?.status==='running'&&!cancelled.current&&epoch===generation.current){
    const step=await invokeSourceCheck('advance',{checkId:result.checkId});current=await refresh(season,epoch);
    if(step.status==='busy'){setError(pick('This check is already processing in another request. Refresh its progress, or resume after a minute.','הבדיקה כבר מתבצעת בבקשה אחרת. רעננו את ההתקדמות או המשיכו בעוד דקה.'));break;}
   }
   if(epoch===generation.current)onEvidenceChanged();
  }catch(e){if(epoch===generation.current)setError(e instanceof Error?e.message:pick('Could not continue. Resume to try again.','לא ניתן להמשיך. נסו לחדש את הבדיקה.'));}
  finally{if(epoch===generation.current){busy.current=false;setRunning(false);}}
 }
 async function cancel(){if(!run)return;cancelled.current=true;const epoch=generation.current;const {error:failure}=await supabase.rpc('cancel_frc_source_check',{p_check:run.id});if(failure){setError(pick('Could not stop the check. Refresh to see its status.','לא ניתן לעצור את הבדיקה. רעננו את המצב.'));return;}await refresh(season,epoch);}
 async function configureSeason(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),year=Number(form.get('year')),name=String(form.get('name')??'').trim();setSaving(true);setFormError('');try{const {error:failure}=await supabase.rpc('configure_frc_season',{p_season:year,p_name:name});if(failure)throw failure;setConfigure(false);onSeasonAdded({season:year,name});}catch{setFormError(pick('Season could not be saved. Check your access and try again.','לא ניתן לשמור את העונה. בדקו הרשאות ונסו שוב.'));}finally{setSaving(false);}}
 const summary=checkSummary(items);const statusLabel=run?.status==='running'?pick(running?'Checking sources':'Check ready to resume',running?'בודק מקורות':'הבדיקה מוכנה להמשך'):run?.status==='attention'?pick('Check finished · items need attention','הבדיקה הסתיימה · יש פריטים לבדיקה'):run?.status==='cancelled'?pick('Check stopped','הבדיקה נעצרה'):pick('Check finished','הבדיקה הסתיימה');
 const label=(status:string)=>({new:pick('New','חדש'),updated:pick('Changed','השתנה'),unchanged:pick('Unchanged','ללא שינוי'),checked:pick('Page checked','העמוד נבדק'),failed:pick('Could not check','הבדיקה נכשלה'),skipped:pick('Needs attention','דורש בדיקה'),pending:pick('Waiting','ממתין')}[status]??status);
 return <section className="knowledge-source-center" aria-labelledby="source-center-heading">
  <header className="source-center-header"><div><span className="source-eyebrow">{pick('OFFICIAL SOURCES','מקורות רשמיים')} · {season}</span><h2 id="source-center-heading">{pick('Keep your season up to date','המקורות של העונה, מעודכנים')}</h2><p>{pick('Discover new documents and check for revisions. Your reviewed evidence stays separate.','איתור מסמכים חדשים ובדיקת גרסאות. המקורות שנבדקו נשמרים בנפרד.')}</p></div>{admin&&<button className="source-secondary" onClick={()=>{setFormError('');setConfigure(true);}} disabled={running}>{pick('Set up a season','הגדרת עונה')}</button>}</header>
  {error&&<div className="source-message source-warning" role="alert">{error}<button onClick={()=>void loadPage(page)} disabled={running}>{pick('Refresh status','רענון מצב')}</button></div>}
  <div className="source-check-layout"><div className="source-scope"><h3>{pick('What will be checked','מה ייבדק')}</h3>{loading&&!watches.length?<p role="status">{pick('Loading publication pages…','טוען עמודי פרסום…')}</p>:watches.length?<ul>{watches.map(w=><li key={w.id}><span aria-hidden="true">↗</span><a href={w.url} target="_blank" rel="noreferrer">{w.title==='Season materials'?pick('FIRST season materials','חומרי העונה של FIRST'):w.title==='Playing field'?pick('FIRST playing field','מגרש המשחק של FIRST'):w.title}</a></li>)}</ul>:<p>{pick('No publication pages configured for this season. An administrator can set it up.','לא הוגדרו עמודי פרסום לעונה זו. מנהל יכול להגדיר אותם.')}</p>}<p className="source-muted">{pick('Season-specific PDFs hosted by FIRST and earlier discoveries. Other season files are linked only; Q&A, CAD models and videos are not imported.','קובצי PDF של העונה באתר FIRST ומסמכים שאותרו בעבר. קובצי עונה אחרים מוצגים כקישורים בלבד; שאלות ותשובות, מודלי CAD וסרטונים אינם מיובאים.')}</p></div>
   <div className="source-action"><span className="source-mode">{pick('ON DEMAND · NO AUTOMATIC POLLING','לפי בקשה · ללא בדיקות אוטומטיות')}</span><p>{pick('Use this at kickoff or whenever an official update is published.','השתמשו בבדיקה בהזנקה או כשמתפרסם עדכון רשמי.')}</p>{admin?<button className="source-primary" disabled={loading||running||!watches.length} onClick={()=>void checkNow()}>{running?pick('Checking…','בודק…'):run?.status==='running'?pick('Resume check','המשך בדיקה'):pick('Check now','בדיקה עכשיו')}</button>:<p className="source-muted">{pick('An administrator can check for updates.','מנהל יכול לבדוק אם יש עדכונים.')}</p>}<small>{pick('One shared check per season. Leaving this page saves progress; return to resume remaining items.','בדיקה משותפת אחת לעונה. ביציאה מהעמוד ההתקדמות נשמרת; ניתן לחזור ולהמשיך.')}</small></div></div>
  {admin&&run&&<div className="source-run" aria-busy={running}><div className="source-run-heading"><div><h3 role="status">{statusLabel}</h3><span>{date(run.started_at)}</span></div>{run.status==='running'&&<button className="source-secondary" onClick={()=>void cancel()}>{pick('Stop check','עצירת בדיקה')}</button>}{run.status!=='running'&&items.some(i=>i.status==='failed')&&<button className="source-secondary" disabled={running} onClick={()=>void checkNow(true)}>{pick('Retry failed items','ניסיון חוזר לפריטים שנכשלו')}</button>}</div><progress aria-label={pick('Check progress','התקדמות הבדיקה')} value={summary.done} max={Math.max(1,summary.total)}/><p className="source-muted">{summary.done} / {summary.total} {pick('items processed','פריטים עובדו')}</p><div className="source-result-counts">{[['New','חדשים',summary.new],['Changed','השתנו',summary.updated],['Unchanged','ללא שינוי',summary.unchanged],['Need attention','דורשים בדיקה',summary.attention]].map(([en,he,count])=><div key={String(en)}><strong>{count}</strong><span>{pick(String(en),String(he))}</span></div>)}</div><details className="source-run-details"><summary>{pick('View check results','הצגת תוצאות הבדיקה')}</summary><ul>{items.map(item=><li key={item.id}><div><a href={item.url} target="_blank" rel="noreferrer">{itemTitle(item)}</a><p>{itemNote(item)}</p></div><span className={`source-badge source-${item.status}`}>{label(item.status)}</span></li>)}</ul></details></div>}
  <div className="source-documents-heading"><h3>{pick('Discovered documents','מסמכים שאותרו')} <span>{total}</span></h3><p>{pick('Original documents open on FIRST. Discovery is not full-text indexing or verification.','המסמכים המקוריים נפתחים באתר FIRST. איתור אינו אינדוקס תוכן מלא או אימות.')}</p></div>
  {documents.length?<><div className="source-document-grid">{documents.map(doc=><article key={doc.id}><span className="source-badge">{pick('Source checked · not reviewed','המקור נבדק · ללא סקירת תוכן')}</span><h4><a href={doc.url} target="_blank" rel="noreferrer">{doc.title} <span aria-hidden="true">↗</span></a></h4><p>{pick('Last checked','בדיקה אחרונה')}: {date(doc.checked_at)}</p><details><summary>{pick('Version details','פרטי גרסה')}</summary><code dir="ltr">{doc.sha256}</code><p>{(doc.bytes/1024/1024).toFixed(1)} MB · {pick('Change detected','שינוי אותר')}: {date(doc.changed_at)}</p></details></article>)}</div>{total>6&&<nav className="source-pagination" aria-label={pick('Document pages','עמודי מסמכים')}><button disabled={!page||loading} onClick={()=>void loadPage(page-1)}>{pick('Previous','הקודם')}</button><span>{page+1} / {Math.ceil(total/6)}</span><button disabled={(page+1)*6>=total||loading} onClick={()=>void loadPage(page+1)}>{pick('Next','הבא')}</button></nav>}</>:<div className="source-empty"><strong>{pick('No documents discovered yet','טרם אותרו מסמכים')}</strong><p>{admin?pick('Run a check to find available documents. Future-season material may not be published yet.','הריצו בדיקה לאיתור מסמכים זמינים. ייתכן שחומרי עונה עתידית טרם פורסמו.'):pick('An administrator can check for available documents. Future-season material may not be published yet.','מנהל יכול לבדוק אילו מסמכים זמינים. ייתכן שחומרי עונה עתידית טרם פורסמו.')}</p></div>}
  {configure&&<AccessibleDialog title={pick('Set up a season','הגדרת עונה')} onClose={()=>!saving&&setConfigure(false)}><form className="source-season-form" onSubmit={configureSeason}><span className="source-eyebrow">{pick('KNOWLEDGE SETTINGS','הגדרות ידע')}</span><h2>{pick('Set up a season','הגדרת עונה')}</h2><p>{pick('Add a season or update its name. Official publication pages are connected automatically; only links explicitly belonging to that year are collected.','הוסיפו עונה או עדכנו את שמה. עמודי הפרסום הרשמיים מחוברים אוטומטית; רק קישורים השייכים במפורש לשנה ייאספו.')}</p><label>{pick('Year','שנה')}<input autoFocus name="year" type="number" min="1992" max="2100" required defaultValue={season} /></label><label>{pick('Season name','שם העונה')}<input name="name" required maxLength={100} placeholder={pick('Use “Awaiting kickoff” if the game is not announced','אפשר להזין ״ממתינים להזנקה״ לפני הכרזת המשחק')} /></label>{formError&&<p role="alert">{formError}</p>}<footer><button type="button" onClick={()=>setConfigure(false)} disabled={saving}>{pick('Cancel','ביטול')}</button><button className="source-primary" disabled={saving}>{saving?pick('Saving…','שומר…'):pick('Save season','שמירת עונה')}</button></footer></form></AccessibleDialog>}
 </section>;
}
