import {useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {parsePlanningWorkspace,type PlanningWorkspace} from '../lib/planningStorage';
type Plan={id:string;name:string;revision:number;shared:boolean;owner_id:string};
export default function PlanningCloud({workspace,onLoad}:{workspace:PlanningWorkspace;onLoad:(workspace:PlanningWorkspace)=>void}){
 const {pick}=useLocalization(),[plans,setPlans]=useState<Plan[]>([]),[selected,setSelected]=useState<Plan|null>(null),[name,setName]=useState(''),[shared,setShared]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[versions,setVersions]=useState<number[]>([]);
 async function list(){setBusy(true);try{const {data,error}=await supabase.from('engineering_plans').select('id,name,revision,shared,owner_id').order('updated_at',{ascending:false}).limit(100);if(error)throw error;setPlans(data??[]);setStatus(pick('Up to 100 most recent accessible plans.','עד 100 תוכניות נגישות אחרונות.'));}catch{setStatus(pick('Cloud plans are unavailable. Your local draft remains saved.','תוכניות הענן אינן זמינות. הטיוטה המקומית נשמרת.'));}finally{setBusy(false);}}
 async function load(p:Plan,revision=p.revision){setBusy(true);try{const {data,error}=await supabase.from('engineering_plan_versions').select('workspace').eq('plan_id',p.id).eq('revision',revision).single();if(error)throw error;const parsed=parsePlanningWorkspace(JSON.stringify(data.workspace));onLoad(parsed);setSelected(p);setName(p.name);setShared(p.shared);setVersions(Array.from({length:p.revision},(_,i)=>p.revision-i));setStatus(pick(`Loaded revision ${revision}; a save creates a new revision.`,`נטענה גרסה ${revision}; שמירה יוצרת גרסה חדשה.`));}catch(e){setStatus(e instanceof Error?e.message:pick('Could not load this plan.','לא ניתן לטעון תוכנית זו.'));}finally{setBusy(false);}}
 async function save(copy:boolean){setBusy(true);try{const draft=parsePlanningWorkspace(JSON.stringify(workspace));const {data,error}=await supabase.rpc('save_engineering_plan',{p_id:copy?null:selected?.id??null,p_name:name.trim(),p_workspace:draft,p_expected:copy?0:selected?.revision??0,p_shared:shared});if(error)throw error;setSelected({id:data.id,revision:data.revision,name:name.trim(),shared,owner_id:''});setVersions(Array.from({length:data.revision},(_,i)=>data.revision-i));setStatus(pick(`Saved revision ${data.revision}. Shared plans can be copied by teammates; only the owner can update them.`,`נשמרה גרסה ${data.revision}. חברי קבוצה יכולים להעתיק תוכניות משותפות; רק הבעלים יכולים לעדכן.`));}catch(e){if((e as {code?:string})?.code==='40001'){setStatus(pick('This plan changed on another device. Browse saved plans and reload it, or save your work as a copy.','התוכנית השתנתה במכשיר אחר. עיינו בתוכניות וטענו מחדש, או שמרו את העבודה כעותק.'));return;}setStatus(e instanceof Error?e.message:pick('Save failed. If another person owns this plan, use Save a copy.','השמירה נכשלה. אם התוכנית בבעלות אדם אחר, השתמשו בשמירת עותק.'));}finally{setBusy(false);}}
 return <details><summary>{pick('Save, share and restore plans','שמירה, שיתוף ושחזור תוכניות')}</summary><p>{pick('Local autosave stays on this browser. Save to your account to open the complete workspace on another device. Sharing grants team members read/copy access, not edit access.','שמירה מקומית נשארת בדפדפן זה. שמרו בחשבון לפתיחת סביבת העבודה במכשיר אחר. שיתוף מאפשר לחברי הקבוצה לקרוא ולהעתיק, ללא עריכה.')}</p><div className="ep-controls"><label>{pick('Plan name','שם התוכנית')}<input maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label><input type="checkbox" checked={shared} onChange={e=>setShared(e.target.checked)}/>{pick('Share with the team','שיתוף עם הקבוצה')}</label><button disabled={busy||!name.trim()} onClick={()=>void save(false)}>{pick('Save revision','שמירת גרסה')}</button><button disabled={busy||!name.trim()} onClick={()=>void save(true)}>{pick('Save a copy','שמירת עותק')}</button><button disabled={busy} onClick={()=>void list()}>{pick('Browse saved plans','עיון בתוכניות שמורות')}</button></div>{status&&<p role="status">{status}</p>}{plans.map(p=><button key={p.id} disabled={busy} onClick={()=>void load(p)}>{p.name} · v{p.revision}{p.shared?' · '+pick('Shared','משותף'):''}</button>)}{selected&&versions.length>1&&<label>{pick('Restore an earlier revision','שחזור גרסה קודמת')}<select value="" disabled={busy} onChange={e=>void load(selected,Number(e.target.value))}><option value="" disabled>{pick('Select a revision','בחירת גרסה')}</option>{versions.map(v=><option key={v} value={v}>v{v}</option>)}</select></label>}</details>;
}
