import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useMemberAuth} from '../lib/memberAuth';
import {useAccessControl} from '../lib/accessControl';
import CanWorkshop from './CanWorkshop';
import './teamLearning.css';
import {academyText,academyFeedback} from '../lib/academyLanguage';
type Pair=[string,string];
type Pack={course_id:string;revision:string;content:{key:string;title:Pair;goal:Pair;steps:Pair[];mistakes:Pair[];sources:[string,string][];practical:Pair[];rubrics:Pair[][];quizId:string;practicalIds:string[];sourceChecked:string}};
type Assessment={id:string;title:string;instructions:string;assessment_type:string;questions:{id:string;prompt:string;options:string[]}[];max_attempts:number;passing_score:number|null};
type Submission={id:string;assessment_id:string;member_id:string;status:string;score:number|null;feedback:string|null;response:string;resource_url:string|null;attempt_number:number;answers:Record<string,string>};
type Draft={step:number;answers:Record<string,string>;responses:string[];urls:string[]};
const empty=():Draft=>({step:0,answers:{},responses:['',''],urls:['','']});
export const localLessonText=academyText;
export default function PracticalLearning({onCourse,onLab,initialCourse,initialStep,reviewSubmission,hideCourseList=false,previewOnly=false}:{initialStep?:number;reviewSubmission?:string;hideCourseList?:boolean;previewOnly?:boolean;onCourse:(id:string)=>void;onLab:(id:string)=>void;initialCourse?:string}){
 const {pick}=useLocalization(),{profile}=useMemberAuth(),access=useAccessControl(),canReview=access.can('validate_training');
 const [packs,setPacks]=useState<Pack[]>([]),[selected,setSelected]=useState(''),[assessments,setAssessments]=useState<Assessment[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[enrollment,setEnrollment]=useState<{id:string;status:string}|null>(null),[draft,setDraft]=useState<Draft>(empty),[reviewDraft,setReviewDraft]=useState<Record<string,{checks:boolean[];feedback:string}>>({}),[people,setPeople]=useState<Record<string,string>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const generation=useRef(0),saving=useRef(false);
 const pack=packs.find(p=>p.course_id===selected),c=pack?.content;
 useEffect(()=>{let live=true;void supabase.from('training_lesson_packs').select('*').order('course_id').then(({data,error})=>{if(!live)return;if(error)setError(error.message);else{setPacks(data??[]);setSelected(data?.find(x=>x.course_id===initialCourse)?.course_id??data?.[0]?.course_id??'');}setLoading(false);});return()=>{live=false;};},[]);
 useEffect(()=>{if(initialCourse&&packs.some(p=>p.course_id===initialCourse))setSelected(initialCourse);},[initialCourse,packs]);
 async function load(id:string,restore=false){
  const token=++generation.current;setLoading(true);setError('');
  const [a,s,e,d,p]=await Promise.all([supabase.from('training_assessments').select('id,title,instructions,assessment_type,questions,max_attempts,passing_score').eq('course_id',id).eq('active',true).order('sort_order'),supabase.from('training_assessment_submissions').select('*').in('assessment_id',[packs.find(p=>p.course_id===id)!.content.quizId,...packs.find(p=>p.course_id===id)!.content.practicalIds]).order('created_at',{ascending:false}),supabase.from('training_enrollments').select('id,status').eq('course_id',id).eq('member_id',profile?.id??'').maybeSingle(),supabase.from('training_lesson_drafts').select('draft').eq('course_id',id).eq('member_id',profile?.id??'').maybeSingle(),canReview?supabase.from('team_members').select('id,display_name').eq('active',true):Promise.resolve({data:[],error:null})]);
  if(token!==generation.current)return;
  const failed=[a,s,e,d,p].find(r=>r.error);if(failed?.error)setError(failed.error.message);else{setAssessments(a.data??[]);setSubmissions((s.data??[]).filter(x=>(a.data??[]).some(v=>v.id===x.assessment_id)));setEnrollment(e.data);setPeople(Object.fromEntries((p.data??[]).map(x=>[x.id,x.display_name])));if(restore){const restored=d.data?.draft as Partial<Draft>|undefined;setDraft({...empty(),...restored,...(initialStep===undefined?{}:{step:initialStep})});setDirty(false);}}
  setLoading(false);
 }
 useEffect(()=>{if(selected&&profile?.id)void load(selected,true);},[selected,profile?.id,initialStep,reviewSubmission]);
 function patch(value:Partial<Draft>){setDraft(d=>({...d,...value}));setDirty(!previewOnly);setNotice('');}
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 async function saveDraft(){if(previewOnly||!profile||saving.current)return false;saving.current=true;setBusy(true);const r=await supabase.from('training_lesson_drafts').upsert({member_id:profile.id,course_id:selected,draft,updated_at:new Date().toISOString()});saving.current=false;setBusy(false);if(r.error){setError(r.error.message);return false;}else{setDirty(false);setNotice(pick('Progress saved. You can return on another device.','ההתקדמות נשמרה. ניתן לחזור ממכשיר אחר.'));return true;}}
 async function submit(a:Assessment,index?:number){if(!enrollment||previewOnly||saving.current)return;saving.current=true;setBusy(true);setError('');const r=await supabase.rpc('submit_learning_pack',{target_assessment:a.id,target_enrollment:enrollment.id,submitted_answers:index===undefined?draft.answers:{},submitted_response:index===undefined?'':draft.responses[index],submitted_resource_url:index===undefined?null:draft.urls[index]||null});saving.current=false;setBusy(false);if(r.error)setError(r.error.message);else{setNotice(pick('Submitted. Your result or reviewer feedback appears below.','נשלח. תוצאה או משוב יופיעו בהמשך.'));await load(selected);}}
 async function review(s:Submission,approve:boolean,criteria:number){const r=reviewDraft[s.id]??{checks:Array(criteria).fill(false),feedback:''};if(saving.current)return;saving.current=true;setBusy(true);const result=await supabase.rpc('review_learning_practical',{target_submission:s.id,approved:approve,checked_criteria:r.checks,review_feedback:r.feedback});saving.current=false;setBusy(false);if(result.error)setError(result.error.message);else{setNotice(pick('Review saved. The learner can see your feedback.','הבדיקה נשמרה. התלמיד יכול לראות את המשוב.'));await load(selected);}}
 const my=(id:string)=>submissions.filter(s=>s.assessment_id===id&&s.member_id===profile?.id);
 const result=(id:string)=>{const rows=my(id),last=rows[0];return last?<div className="tl-result"><b>{last.status==='reviewed'?pick('Reviewed','נבדק'):last.status==='changes_requested'?pick('Revise and demonstrate again','תקנו והדגימו שוב'):pick('Awaiting review','ממתין לבדיקה')}{last.score!==null?` · ${last.score}/10`:''}</b>{last.feedback&&<p>{academyFeedback(last.feedback,pick)}</p>}{last.score!==null&&last.score<8&&<p>{pick('Revisit the illustrated source, explain each choice to a peer, then retry. Your practical demonstrations still require review.','חזרו למקור המאויר, הסבירו כל בחירה לחבר ואז נסו שוב. ההדגמות המעשיות עדיין דורשות בדיקה.')}</p>}<small>{pick('Attempts used','ניסיונות שנוצלו')}: {rows.length}</small></div>:null;};
 const labels=[pick('Learn','ללמוד'),pick('Check understanding','בדיקת הבנה'),pick('Demonstrate','הדגמה'),pick('Review & improve','בדיקה ושיפור')];
 return <section className="tl-workbench"><header className="tl-heading"><div><small>G3 / {pick('PRACTICAL SKILLS','מיומנויות מעשיות')}</small><h2>{pick('Learn it. Build it. Prove it.','ללמוד. לבנות. להוכיח.')}</h2><p>{pick('Six guided modules. Saved progress. Real demonstrations reviewed by a responsible person.','שש יחידות מודרכות. התקדמות נשמרת. הדגמות אמיתיות נבדקות בידי אחראי.')}</p></div><Link to="/growth?view=robot-tests">{pick('Open shared robot tests','פתיחת בדיקות רובוט משותפות')} ↗</Link></header>
 {error&&<p role="alert" className="tl-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="tl-split" style={hideCourseList?{gridTemplateColumns:"minmax(0,1fr)"}:undefined}>{!hideCourseList&&<aside className="tl-history">{packs.map((p,i)=><button key={p.course_id} aria-pressed={selected===p.course_id} onClick={()=>{if(dirty&&!confirm(pick('Leave without saving your draft?','לעזוב בלי לשמור טיוטה?')))return;setSelected(p.course_id);setNotice('');}}><small>0{i+1}</small><strong>{pick(...p.content.title)}</strong></button>)}{!loading&&!packs.length&&<p>{pick('The lesson pack has not been published yet.','חבילת השיעורים טרם פורסמה.')}</p>}</aside>}
 <article className="tl-panel" aria-busy={loading}>{loading?<p role="status">{pick('Loading saved learning…','טוען למידה שמורה…')}</p>:c&&<><div className="tl-heading"><div><h3>{pick(...c.title)}</h3><p>{pick(...c.goal)}</p></div><button className="secondary" disabled={previewOnly||busy||!dirty} onClick={()=>void saveDraft()}>{pick(dirty?'Save progress':'Progress saved',dirty?'שמירת התקדמות':'ההתקדמות נשמרה')}</button></div>
 <nav className="tl-steps" aria-label={pick('Learning flow','תהליך למידה')}>{labels.map((label,i)=><button key={i} aria-current={draft.step===i?'step':undefined} onClick={()=>patch({step:i})}>{i+1}<span>{label}</span></button>)}</nav>
 {!enrollment&&<aside className="tl-callout">{pick('You can explore now. Ask your instructor to assign this course before submitting assessments.','ניתן לעיין עכשיו. בקשו מהמדריך להקצות את הקורס לפני הגשת מטלות.')}<button className="secondary" onClick={()=>onCourse(selected)}>{pick('Course & assignment','קורס והקצאה')}</button></aside>}
 {enrollment?.status==='qualified'&&<p className="tl-result">{pick('Course completed: required quiz and practical reviews passed. This does not authorize unsupervised work beyond team policy.','הקורס הושלם: מבחן ובדיקות מעשיות עברו. אין בכך אישור לעבודה ללא פיקוח בניגוד למדיניות הקבוצה.')}</p>}
 {draft.step===0&&<><div className="tl-visual" role="img" aria-label={pick('Learning sequence: inspect the reference, demonstrate on the real assembly, record evidence, obtain review','רצף למידה: עיון בדוגמה, הדגמה בהרכבה אמיתית, תיעוד ראיות ובדיקה')}><span>01<br/>{pick('Reference','דוגמה')}</span><b>→</b><span>02<br/>{pick('Real assembly','הרכבה אמיתית')}</span><b>→</b><span>03<br/>{pick('Evidence','ראיות')}</span><b>→</b><span>04<br/>{pick('Review','בדיקה')}</span></div><ol className="tl-lesson">{c.steps.map((s,i)=><li key={i}>{pick(...s)}</li>)}</ol>
 <div className="tl-actions"><button onClick={async()=>{if(!dirty||await saveDraft())onLab(selected);}}>{pick('Inspect reference robots in 3D','בדיקת רובוטי דוגמה בתלת־ממד')}</button>{c.key==='can'&&<CanWorkshop pick={pick}/>}</div><p>{pick('Reference CAD illustrates parts and assemblies; it does not verify your installed wiring or physical performance.','CAD לדוגמה מציג חלקים והרכבות; הוא אינו מאמת חיווט מותקן או ביצועים פיזיים שלכם.')}</p>{['power','can','inspection'].includes(c.key)&&<figure className="tl-source-image"><a href="https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-1/intro-to-frc-robot-wiring.html" target="_blank" rel="noreferrer"><img loading="lazy" src={'https://docs.wpilib.org/en/stable/_images/'+(c.key==='can'?'can-bus-ends.jpg':'layout-kitbot.jpg')} alt={pick(c.key==='can'?'WPILib: roboRIO and PDH CAN terminals':'WPILib: Kitbot control-board layout',c.key==='can'?'WPILib: הדקי CAN של roboRIO ו-PDH':'WPILib: לוח בקרה של Kitbot')}/></a><figcaption>{pick('WPILib published Kitbot example, not your installed robot. Open the source for full detail.','דוגמת Kitbot שפורסמה ב-WPILib, לא הרובוט המותקן שלכם. פתחו מקור לפירוט מלא.')}</figcaption></figure>}<h4>{pick('Illustrated source material','מקורות מאוירים')}</h4>{c.sources.map(([label,url])=><p key={url}><a href={url} target="_blank" rel="noreferrer">{pick(label,`מקור ${c.sources.findIndex(s=>s[1]===url)+1} · ${new URL(url).hostname}`)} ↗</a></p>)}<small>{pick('Content revision','גרסת תוכן')}: {pack?.revision}. {pick('Living source documents: verify instructions for the installed hardware before assembly.','מקורות מתעדכנים: אמתו הוראות לחומרה המותקנת לפני הרכבה.')}</small><aside className="tl-callout"><h4>{pick('Common mistakes to catch','טעויות שכדאי לזהות')}</h4>{c.mistakes.map((m,i)=><p key={i}>{pick(...m)}</p>)}</aside></>}
 {draft.step===1&&(()=>{const a=assessments.find(a=>a.id===c.quizId);return a?<><p>{pick('Ten questions · pass 8/10 · answers are graded on the server.','עשר שאלות · מעבר 8/10 · התשובות נבדקות בשרת.')}</p>{a.questions.map((q,i)=><fieldset className="tl-question" key={q.id}><legend>{i+1}. {localLessonText(q.prompt,pick)}</legend>{q.options.map((option,j)=><label className="tl-check" key={j}><input type="radio" name={q.id} checked={draft.answers[q.id]===option} onChange={()=>patch({answers:{...draft.answers,[q.id]:option}})}/><span>{localLessonText(option,pick)}</span></label>)}</fieldset>)}{result(a.id)}<button disabled={busy||!enrollment||previewOnly||my(a.id).length>=a.max_attempts||a.questions.some(q=>!draft.answers[q.id])} onClick={()=>void submit(a)}>{pick('Submit knowledge check','הגשת בדיקת ידע')}</button><p>{my(a.id).length>=a.max_attempts?pick('No attempts remain. Ask your instructor to review your progress.','לא נותרו ניסיונות. בקשו מהמדריך לבדוק התקדמות.'):pick('You can save progress before submitting.','ניתן לשמור התקדמות לפני הגשה.')}</p></>:<p>{pick('Quiz unavailable. Contact the course owner.','המבחן לא זמין. פנו לאחראי הקורס.')}</p>;})()}
 {draft.step===2&&c.practicalIds.map((id,i)=>{const a=assessments.find(a=>a.id===id);if(!a)return null;const rows=my(id),locked=rows.some(r=>r.status==='submitted')||rows.length>=a.max_attempts;return <section className="tl-practical" key={id}><h4>{i+1}. {pick(...c.practical[i])}</h4><ul>{c.rubrics[i].map((r,j)=><li key={j}>{pick(...r)}</li>)}</ul><label>{pick('What you did, measured and observed','מה עשיתם, מדדתם וראיתם')}<textarea minLength={20} maxLength={16000} value={draft.responses[i]??''} onChange={e=>patch({responses:draft.responses.map((v,j)=>j===i?e.target.value:v)})}/></label><label>{pick('Evidence link: shared robot test, sketch or team media (optional)','קישור ראיה: בדיקת רובוט משותפת, שרטוט או מדיה קבוצתית (אופציונלי)')}<input type="url" value={draft.urls[i]??''} onChange={e=>patch({urls:draft.urls.map((v,j)=>j===i?e.target.value:v)})}/></label>{result(id)}<button disabled={busy||!enrollment||previewOnly||locked||(draft.responses[i]?.trim().length??0)<20} onClick={()=>void submit(a,i)}>{pick('Submit demonstration for review','שליחת הדגמה לבדיקה')}</button>{locked&&<p>{pick('Awaiting review or attempt limit reached. Review your feedback before continuing.','ממתין לבדיקה או הגעה למגבלת ניסיונות. עיינו במשוב לפני המשך.')}</p>}</section>;})}
 {draft.step===3&&<><h4>{pick('Feedback and next action','משוב ופעולה הבאה')}</h4>{[c.quizId,...c.practicalIds].map(id=><section key={id}><b>{localLessonText(assessments.find(a=>a.id===id)?.title??'',pick)}</b>{result(id)??<p>{pick('Not submitted yet.','טרם הוגש.')}</p>}</section>)}{canReview&&!previewOnly&&<><h4>{pick('Practical review queue','תור בדיקות מעשיות')}</h4>{submissions.filter(s=>s.status==='submitted'&&c.practicalIds.includes(s.assessment_id)&&(!reviewSubmission||s.id===reviewSubmission)).map(s=>{const index=c.practicalIds.indexOf(s.assessment_id),rubric=c.rubrics[index],r=reviewDraft[s.id]??{checks:rubric.map(()=>false),feedback:''};return <section className="tl-practical" key={s.id}><h4>{people[s.member_id]??s.member_id} · {pick(...c.practical[index])}</h4><p>{s.response}</p>{s.resource_url&&/^https?:\/\//.test(s.resource_url)&&<a href={s.resource_url} target="_blank" rel="noreferrer">{pick('Open evidence','פתיחת ראיה')} ↗</a>}<p>{pick('Verify each criterion from the demonstration. Self-review is not allowed.','אמתו כל קריטריון מההדגמה. אין לאשר בדיקה עצמית.')}</p>{rubric.map((criterion,j)=><label key={j} className="tl-check"><input type="checkbox" checked={r.checks[j]} onChange={e=>setReviewDraft(old=>({...old,[s.id]:{...r,checks:r.checks.map((v,k)=>j===k?e.target.checked:v)}}))}/><span>{pick(...criterion)}</span></label>)}<label>{pick('Specific feedback / what to improve','משוב מוגדר / מה לשפר')}<textarea maxLength={4000} value={r.feedback} onChange={e=>setReviewDraft(old=>({...old,[s.id]:{...r,feedback:e.target.value}}))}/></label><div className="tl-actions"><button disabled={busy||s.member_id===profile?.id||!r.checks.every(Boolean)||r.feedback.trim().length<3} onClick={()=>void review(s,true,rubric.length)}>{pick('Approve demonstration','אישור הדגמה')}</button><button className="secondary" disabled={busy||s.member_id===profile?.id||r.feedback.trim().length<3} onClick={()=>void review(s,false,rubric.length)}>{pick('Request correction & retest','בקשת תיקון ובדיקה חוזרת')}</button></div></section>;})}{!submissions.some(s=>s.status==='submitted'&&c.practicalIds.includes(s.assessment_id))&&<p>{pick('No practical demonstrations awaiting review in this module.','אין הדגמות שממתינות לבדיקה ביחידה זו.')}</p>}</>}</>}
 <footer className="tl-actions"><button className="secondary" disabled={draft.step===0} onClick={()=>patch({step:draft.step-1})}>{pick('Previous','הקודם')}</button>{draft.step<3&&<button onClick={()=>patch({step:draft.step+1})}>{labels[draft.step+1]} →</button>}<small>{dirty?pick('Unsaved progress','התקדמות לא נשמרה'):''}</small></footer></>}</article></div></section>;
}
