import {useMemberAuth} from '../lib/memberAuth';
import {useEffect,useState} from 'react';
import {useLocalization} from '../lib/localization';
import {type PracticeRun} from '../lib/twinPractice';
import {PROGRESS_KEY,readAttempts,recordAttempt,comparableAttempts,type Attempt,type Exercise} from '../lib/practiceProgress';
import '../styles/practiceProgress.css';
export default function PracticeProgress({run,exercise,settings}:{run:PracticeRun|null;exercise:Exercise;settings:string}){
 const {profile}=useMemberAuth();const storageKey=PROGRESS_KEY+':'+(profile?.id??'local-preview');
 const {pick}=useLocalization(),[history,setHistory]=useState<Attempt[]>([]),[reflection,setReflection]=useState(''),[nextTest,setNextTest]=useState(''),[status,setStatus]=useState(''),[blocked,setBlocked]=useState(false);
 useEffect(()=>{try{setHistory(readAttempts({getItem:()=>localStorage.getItem(storageKey)}));}catch(e){setBlocked(true);setStatus((e instanceof Error?e.message+': ':'')+pick('Saved practice history could not be read. It has been preserved. Export this attempt before leaving.','לא ניתן לקרוא היסטוריה שמורה. היא נשמרה ללא שינוי. ייצאו את הניסיון לפני יציאה.'));}},[storageKey]);
 useEffect(()=>{setReflection('');setNextTest('');},[run?.id]);
 const result=run?.result;const attemptExercise:Exercise=run?JSON.parse(run.settings).exercise??exercise:exercise;const matches=comparableAttempts(history,exercise,settings,result?.input??run?.input??'Keyboard / touch');const baseline=matches[0],latest=matches[matches.length-1];const value=(a:Attempt)=>exercise==='collection'?(a.result.collected??0):a.result.scored;const metric=exercise==='collection'?pick('collected','נאספו'):pick('scored','קליעות');
 function attempt():Attempt|null{return run?.result?{id:run.id,createdAt:run.createdAt,exercise:attemptExercise,result:run.result,reflection,nextTest}:null;}
 function save(){const a=attempt();if(!a)return;try{const next=recordAttempt(history,a);readAttempts({getItem:()=>JSON.stringify(next)});localStorage.setItem(storageKey,JSON.stringify(next));setHistory(next);setStatus(pick('Attempt saved on this browser.','הניסיון נשמר בדפדפן זה.'));}catch{setStatus(pick('Storage unavailable or full. Export the attempt instead.','האחסון אינו זמין או מלא. ייצאו את הניסיון.'));}}
 function exportAttempt(){const a=attempt();if(!a)return;const blob=new Blob([JSON.stringify({schema:1,kind:'simulated-practice-evidence',attempt:a},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='g3-practice-evidence.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="practice-progress"><header><div><h3>{pick('Review → improve → retest','בדיקה ← שיפור ← ניסיון חוזר')}</h3><p>{pick('Simulated practice. History is local to this browser, not a team leaderboard. Compare complete attempts with the same exercise, robot settings and controls.','תרגול מדומה. ההיסטוריה מקומית לדפדפן, לא דירוג קבוצתי. ההשוואה היא בין ניסיונות מלאים עם אותו תרגיל, הגדרות ובקרים.')}</p></div><strong>{matches.length} {pick('comparable attempts','ניסיונות להשוואה')}</strong></header>
 {baseline&&latest&&<div className="practice-comparison"><span>{pick('First completed attempt','ניסיון מלא ראשון')}<b>{value(baseline)} {metric}</b></span><span>{pick('Latest completed attempt','ניסיון מלא אחרון')}<b>{value(latest)} {metric}</b></span><span>{pick('Change from baseline','שינוי מהבסיס')}<b>{value(latest)-value(baseline)>=0?'+':''}{value(latest)-value(baseline)}</b></span></div>}
 {result&&<><div className="practice-reflection"><label>{pick('What should improve?','מה צריך לשפר?')}<textarea maxLength={1500} value={reflection} onChange={e=>setReflection(e.target.value)} placeholder={pick('Example: lost sight of the intake near the hub','לדוגמה: איבדתי קשר עין עם האיסוף ליד המבנה')}/></label><label>{pick('What will you change and retest?','מה תשנו ותבדקו שוב?')}<textarea maxLength={1500} value={nextTest} onChange={e=>setNextTest(e.target.value)} placeholder={pick('One change; repeat the same exercise','שינוי אחד; חזרו על אותו תרגיל')}/></label></div><div className="intel-button-row"><button disabled={blocked} onClick={save}>{pick('Save attempt & review','שמירת ניסיון ובדיקה')}</button><button onClick={exportAttempt}>{pick('Export evidence for mentor','ייצוא ראיות למנטור')}</button><a href="/work">{pick('Open existing team tasks','פתיחת משימות הקבוצה')}</a><a href="/growth">{pick('Open Skills Academy','פתיחת אקדמיית המיומנויות')}</a></div><small>{pick('Export includes settings, results and your review. Attach it to the relevant task; this does not automatically create a task or approve a result.','הייצוא כולל הגדרות, תוצאות ובדיקה. צרפו למשימה המתאימה; אין יצירה אוטומטית של משימה או אישור תוצאה.')}</small></>}
 {status&&<p role="status">{status}</p>}{blocked&&<button onClick={()=>{try{const raw=localStorage.getItem(storageKey);if(raw)localStorage.setItem(storageKey+':recovery:'+Date.now(),raw);localStorage.setItem(storageKey,'[]');setHistory([]);setBlocked(false);setStatus(pick('Previous bytes archived on this browser; a new history is ready.','הנתונים הקודמים הועברו לארכיון בדפדפן; היסטוריה חדשה מוכנה.'));}catch{setStatus(pick('Archive failed. Original data remains unchanged.','שמירה בארכיון נכשלה. הנתונים המקוריים לא שונו.'));}}}>{pick('Archive unreadable history and start fresh','שמירת היסטוריה בלתי קריאה בארכיון והתחלה חדשה')}</button>}
 {matches.length>0&&<details><summary>{pick('Attempt history','היסטוריית ניסיונות')}</summary><div className="practice-history"><table><thead><tr>{[pick('Date','תאריך'),pick('Collected','נאספו'),pick('Scored','קליעות'),pick('Accuracy','דיוק'),pick('Review & next test','בדיקה וניסיון הבא')].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{matches.slice(-10).reverse().map(a=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString()}</td><td>{a.result.collected??'—'}</td><td>{a.result.scored}</td><td>{a.result.accuracy===null?'—':Math.round(a.result.accuracy*100)+'%'}</td><td><details><summary>{pick('Read review','קריאת בדיקה')}</summary><p>{a.reflection||'—'}</p><p>{a.nextTest||'—'}</p></details></td></tr>)}</tbody></table></div></details>}
 </section>;
}
