import {useEffect,useState,type FormEvent} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useMemberAuth} from '../lib/memberAuth';
import {notifyProjectChange,useProjectRefresh} from '../lib/projectRefresh';
export type ReviewSubmission={id:string;revision:string;evidence_url:string;notes:string;criteria:string;submitted_by:string;submitted_by_name?:string|null;decided_by_name?:string|null;submitted_at:string;status:string;decided_by:string|null;decided_at:string|null;decision_note:string|null};
export type ReviewGate={task_id:string;project_id:string;title:string;due_at:string|null;reviewer_id:string;reviewer:string|null;criteria:string;submission:ReviewSubmission|null;history:ReviewSubmission[];audit:{id:number;action:string;actor_id:string;actor_name?:string|null;note:string;created_at:string}[]};
export function reviewLabel(status:string|undefined,pick:(en:string,he:string)=>string){
 return status==='approved'?pick('Approved','אושר'):status==='overridden'?pick('Released by admin override','שוחרר בחריגת מנהל'):status==='pending'?pick('Awaiting mentor review','ממתין לבדיקת מנטור'):status==='changes_requested'?pick('Changes requested','נדרשים שינויים'):pick('Not submitted','טרם הוגש');
}
function safeEvidence(url:string){try{return new URL(url).protocol==='https:'?url:undefined;}catch{return undefined;}}
export default function ProjectTaskReview({task,gate,canManage,autoOpen=false,onChanged}:{task:{id:string;status:string;archived?:boolean;assignee_id:string|null;created_by:string|null};gate?:ReviewGate;canManage:boolean;autoOpen?:boolean;onChanged:()=>Promise<void>}){
 const {pick}=useLocalization(),{profile}=useMemberAuth();
 const [open,setOpen]=useState(autoOpen),[full,setFull]=useState<ReviewGate|null>(null),[mode,setMode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [reviewers,setReviewers]=useState<{id:string;display_name:string}[]>([]),[reviewer,setReviewer]=useState(''),[criteria,setCriteria]=useState(''),[reason,setReason]=useState('');
 const [revision,setRevision]=useState(''),[url,setUrl]=useState(''),[notes,setNotes]=useState(''),[decisionNote,setDecisionNote]=useState('');
 const current=full??gate,submission=current?.submission;
 async function details(){if(!gate)return;const r=await supabase.rpc('project_review_context',{p_task:task.id});if(r.error)setMessage(r.error.message);else setFull(r.data?.[0]??null);}
 useEffect(()=>{setFull(null);if(open&&gate)void details();},[open,gate?.submission?.id,gate?.submission?.status,gate?.criteria,gate?.reviewer_id]);
 useProjectRefresh(()=>{if(open)return details();});
 useEffect(()=>{if(autoOpen)setOpen(true);},[autoOpen]);
 if(!gate&&!canManage)return null;
 const author=!!profile&&(task.assignee_id===profile.id||task.created_by===profile.id||canManage);
 const canSubmit=author&&!task.archived&&current?.reviewer_id!==profile?.id;
 const canDecide=submission?.status==='pending'&&current?.reviewer_id===profile?.id&&submission?.submitted_by!==profile?.id;
 const approved=submission?.status==='approved'||submission?.status==='overridden';
 async function configure(){setBusy(true);const r=await supabase.from('team_members').select('id,display_name').eq('active',true).in('role',['mentor','admin']).order('display_name');setBusy(false);if(r.error){setMessage(r.error.message);return;}setReviewers(r.data??[]);setReviewer(current?.reviewer_id??'');setCriteria(current?.criteria??'');setReason('');setMode('configure');setMessage('');}
 async function perform(name:string,args:Record<string,unknown>){if(busy)return;setBusy(true);setMessage('');try{const r=await supabase.rpc(name,args);if(r.error)throw r.error;setMode('');setDecisionNote('');await onChanged();setFull(null);notifyProjectChange();setMessage(pick('Review checkpoint updated.','נקודת הביקורת עודכנה.'));}catch(e){setMessage((e as {message?:string})?.message??pick('Could not save the review.','לא ניתן לשמור את הביקורת.'));}finally{setBusy(false);}}
 function saveConfig(e:FormEvent){e.preventDefault();void perform('configure_project_review',{p_task:task.id,p_reviewer:reviewer,p_criteria:criteria,p_reason:reason});}
 function submit(e:FormEvent){e.preventDefault();void perform('submit_project_review',{p_task:task.id,p_revision:revision,p_url:url,p_notes:notes});}
 return <section className="task-review-shell">{gate?<div className="review-task-action"><div><strong>{reviewLabel(submission?.status,pick)}</strong><small>{pick("Work is complete only after mentor approval.","המשימה תושלם לאחר אישור המנטור.")}</small></div>{canSubmit?<button className="hub-button" disabled={busy} onClick={()=>{setOpen(true);setMode("submit");setRevision("");setUrl("");setNotes("");}}>{submission?pick("Send revised work","שליחת גרסה מתוקנת"):pick("Send for approval","שליחה לאישור")}</button>:null}</div>:null}<details className="task-review" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary><span>{pick('Review details & settings','פרטי ביקורת והגדרות')}</span><span className={`review-state ${approved?'is-approved':''}`}>{gate?reviewLabel(submission?.status,pick):pick('Optional','רשות')}</span></summary><div className="task-review-body">
 {!gate?<p>{pick('Enable review only for a milestone that needs formal release. Link dependent tasks through Prerequisites before work starts.','הפעילו ביקורת רק לאבן דרך הדורשת אישור רשמי. קשרו משימות תלויות דרך משימות מקדימות לפני תחילת העבודה.')}</p>:<><div className="review-owner"><strong>{pick('Reviewer','מנטור בודק')}: {current?.reviewer??pick('Unavailable','לא זמין')}</strong>{gate.due_at?<small>{pick('Milestone due','מועד אבן הדרך')}: {new Date(gate.due_at).toLocaleDateString()}</small>:null}</div><h4>{pick('Acceptance criteria','תנאי קבלה')}</h4><p className="review-copy">{current?.criteria}</p>{submission?<div className="review-submission"><strong>{pick('Revision','גרסה')}: {submission.revision}</strong><small>{new Date(submission.submitted_at).toLocaleString()}</small><a href={safeEvidence(submission.evidence_url)} target="_blank" rel="noopener noreferrer">{pick('Open drawing / design / code','פתיחת שרטוט / תכנון / קוד')} ↗</a>{submission.notes?<p className="review-copy">{submission.notes}</p>:null}{submission.decision_note?<p className="review-decision"><strong>{reviewLabel(submission.status,pick)}</strong><br/>{submission.decision_note}</p>:null}</div>:null}
 <p className="review-hint">{pick('Approval releases this submitted revision and completes the checkpoint. A new revision requires review again. Dependent tasks use their Prerequisites links.','האישור משחרר את הגרסה שהוגשה ומשלים את נקודת הביקורת. גרסה חדשה דורשת ביקורת מחדש. משימות תלויות משתמשות בקישורי המשימות המקדימות.')}</p></>}
 {message?<p role="status" className="review-message">{message}</p>:null}
 {gate&&author&&current?.reviewer_id===profile?.id?<small>{pick('Choose another mentor before submitting your own work.','בחרו מנטור אחר לפני הגשת עבודה שלכם.')}</small>:null}{mode==='configure'?<form className="operations-planning-form" onSubmit={saveConfig}><label>{pick('Assigned mentor','מנטור בודק')}<select required value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">{pick('Select a mentor','בחירת מנטור')}</option>{reviewers.map(m=><option key={m.id} value={m.id}>{m.display_name}</option>)}</select></label><label>{pick('Acceptance criteria','תנאי קבלה')}<textarea required minLength={3} maxLength={4000} rows={3} value={criteria} onChange={e=>setCriteria(e.target.value)}/></label>{gate?<label>{pick('Reason for the change','סיבת השינוי')}<textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>:null}{gate?<small>{pick('Changing criteria invalidates the current release and requires a fresh submission. Reviewer changes are recorded in history.','שינוי תנאי הקבלה מבטל את השחרור הנוכחי ודורש הגשה חדשה. שינוי מנטור נרשם בהיסטוריה.')}</small>:null}<footer><button type="button" onClick={()=>setMode('')}>{pick('Cancel','ביטול')}</button><button className="hub-button" disabled={busy}>{pick('Save checkpoint','שמירת נקודת הביקורת')}</button></footer></form>:mode==='submit'?<form className="operations-planning-form" onSubmit={submit}><label>{pick('Revision identifier','מזהה גרסה')}<input required maxLength={120} placeholder="CAD Rev B / prototype v2" value={revision} onChange={e=>setRevision(e.target.value)}/></label><label>{pick('Work to review — link to this revision','העבודה לבדיקה — קישור לגרסה זו')}<input required type="url" pattern="https://.*" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>{pick('Changes and supporting test evidence','שינויים וראיות מבדיקות')}<textarea maxLength={5000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><small>{pick('Use a fixed revision link. Submitting replaces the current release and blocks further dependent progress until approved. Existing work is not undone.','השתמשו בקישור לגרסה קבועה. ההגשה מחליפה את השחרור הנוכחי וחוסמת התקדמות תלויה עד לאישור. עבודה קיימת אינה מבוטלת.')}</small><footer><button type="button" onClick={()=>setMode('')}>{pick('Cancel','ביטול')}</button><button className="hub-button" disabled={busy}>{pick('Send for approval','שליחה לאישור')}</button></footer></form>:<div className="review-buttons">{canManage&&!task.archived?<button disabled={busy} onClick={()=>void configure()}>{gate?pick('Reviewer / criteria settings','הגדרות מנטור ותנאי קבלה'):pick('Enable mentor review','הפעלת ביקורת מנטור')}</button>:null}</div>}
 {canDecide&&!task.archived?<div className="review-decision-form"><label>{pick('Review findings and decision reason','ממצאי הביקורת וסיבת ההחלטה')}<textarea rows={3} value={decisionNote} onChange={e=>setDecisionNote(e.target.value)} maxLength={5000}/></label><div className="review-buttons"><button className="hub-button" disabled={busy||decisionNote.trim().length<3} onClick={()=>void perform('decide_project_review',{p_task:task.id,p_submission:submission!.id,p_decision:'changes_requested',p_note:decisionNote})}>{pick('Request changes','בקשת שינויים')}</button><button className="review-approve" disabled={busy||decisionNote.trim().length<3} onClick={()=>void perform('decide_project_review',{p_task:task.id,p_submission:submission!.id,p_decision:'approved',p_note:decisionNote})}>{pick('Approve revision & release','אישור גרסה ושחרור')}</button></div></div>:null}
 {profile?.role==='admin'&&submission&&!approved&&!task.archived?<details className="review-override"><summary>{pick('Emergency administrator override','חריגת מנהל למקרה חירום')}</summary><p>{pick('This bypasses mentor approval for this revision. Your identity and reason remain in the audit history.','פעולה זו עוקפת אישור מנטור לגרסה זו. זהותכם והסיבה נשמרות בהיסטוריית הביקורת.')}</p><label>{pick('Override justification','נימוק החריגה')}<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={5000}/></label><button disabled={busy||reason.trim().length<3} onClick={()=>void perform('decide_project_review',{p_task:task.id,p_submission:submission.id,p_decision:'overridden',p_note:reason})}>{pick('Record override & release','רישום חריגה ושחרור')}</button></details>:null}
 {profile?.role==='admin'&&gate&&!current?.history?.length&&!submission?<details className="review-override"><summary>{pick('Withdraw unused checkpoint','ביטול נקודת ביקורת שלא הוגשה')}</summary><label>{pick('Reason','סיבה')}<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<3} onClick={()=>void perform('withdraw_unused_project_review',{p_task:task.id,p_reason:reason})}>{pick('Withdraw checkpoint','ביטול נקודת הביקורת')}</button></details>:null}
 {current?.history?.length?<details className="review-history"><summary>{pick('Revision and decision history','היסטוריית גרסאות והחלטות')}</summary>{current.history.map(s=><article key={s.id}><strong>{s.revision} · {s.status==='pending'&&s.id!==current.submission?.id?pick('Superseded submission','הגשה שהוחלפה'):reviewLabel(s.status,pick)}</strong><small>{new Date(s.submitted_at).toLocaleString()}</small><a href={safeEvidence(s.evidence_url)} target="_blank" rel="noopener noreferrer">{pick('Submitted evidence','ראיות שהוגשו')}</a><p>{s.decision_note??s.notes}</p><small>{pick('Submitted by','הוגש על ידי')}: {s.submitted_by_name??pick("Former member","חבר שאינו זמין")}{s.decided_by?' · '+pick('Decision by','החלטה על ידי')+': '+(s.decided_by_name??pick('Former member','חבר שאינו זמין')):''}</small>{s.decided_at?<small>{new Date(s.decided_at).toLocaleString()}</small>:null}</article>)}</details>:null}
 {current?.audit?.length?<details className="review-history"><summary>{pick('Checkpoint change log','יומן שינויי נקודת הביקורת')}</summary>{current.audit.map(a=><article key={a.id}><strong>{a.action.replaceAll('_',' ')}</strong><p className="review-copy">{a.note}</p><small>{new Date(a.created_at).toLocaleString()} · {a.actor_name??pick("Former member","חבר שאינו זמין")}</small></article>)}</details>:null}
 </div></details></section>;
}
