import {useBuildStringDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {notifyProjectChange,useProjectRefresh} from '../lib/projectRefresh';
export type RobotConfiguration={id:string;name:string;revision:string;configuration_kind:string;details:string;identity_snapshot?:{asset?:{serial?:string}}};
export function useProjectConfigurations(projectId:string){const[items,setItems]=useState<RobotConfiguration[]>([]);async function load(){const r=await supabase.from('project_robot_configurations').select('id,name,revision,configuration_kind,details,identity_snapshot').eq('project_id',projectId).order('created_at',{ascending:false});if(!r.error)setItems(r.data??[]);}useEffect(()=>{void load();},[projectId]);useProjectRefresh(load);return items;}
export default function ProjectConfigurations({projectId}:{projectId:string}){
 const {pick}=useLocalization();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const configurations=useProjectConfigurations(projectId);
 const [assets,setAssets]=useState<{id:string;serial:string;name:string}[]>([]);
 const initial=()=>({name:'',revision:'',kind:'as_built',details:'',asset:'',parent:'',software:'',calibration:''});
 const assetInitial=()=>({serial:'',assetName:'',assetKind:'prototype'});
 const draft=useBuildStringDraft(`configuration:${projectId}`,initial),assetDraft=useBuildStringDraft(`physical-asset:${projectId}`,assetInitial);
 const {name,revision,kind,details,asset,parent,software,calibration}=draft.value;const {serial,assetName,assetKind}=assetDraft.value;
 async function loadAssets(){const r=await supabase.from('project_physical_assets').select('id,serial,name').eq('project_id',projectId).order('serial');if(r.error)setMessage(pick('Asset registry could not be loaded.','לא ניתן לטעון את מרשם הנכסים.'));else setAssets(r.data??[]);}
 useEffect(()=>{void loadAssets();},[projectId]);
 return <details className="review-evidence-editor"><summary>{pick('Register robot / prototype configuration','רישום תצורת רובוט / אב־טיפוס')}</summary><p>{pick('Save the exact parts and software revisions tested. Saved records are retained; create a new revision when the configuration changes.','שמרו את גרסאות החלקים והתוכנה שנבדקו. רשומות נשמרות; צרו גרסה חדשה כאשר התצורה משתנה.')}</p>
 <details><summary>{pick('Register a physical asset first','רישום נכס פיזי תחילה')}</summary><form data-build-form={assetDraft.id} className="review-evidence-item" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const r=await supabase.rpc('register_project_asset',{p_project:projectId,p_serial:serial,p_name:assetName,p_kind:assetKind});if(r.error)throw new Error(r.error.message);await loadAssets();draft.change({asset:r.data});assetDraft.saved(assetInitial());setMessage(pick('Asset registered and selected.','הנכס נרשם ונבחר.'));}catch(e){setMessage(e instanceof Error?e.message:pick('Could not register asset.','לא ניתן לרשום את הנכס.'));}finally{setBusy(false);}}}>
 <BuildDraftNotice {...assetDraft}/><label>{pick('Unique physical serial / tag','מספר סידורי / תג פיזי ייחודי')}<input required minLength={3} maxLength={120} value={serial} onChange={e=>assetDraft.change({serial:e.target.value})}/></label><label>{pick('Asset name','שם הנכס')}<input required minLength={3} maxLength={160} value={assetName} onChange={e=>assetDraft.change({assetName:e.target.value})}/></label><label>{pick('Asset type','סוג נכס')}<select value={assetKind} onChange={e=>assetDraft.change({assetKind:e.target.value})}>{[['robot','Robot','רובוט'],['prototype','Prototype','אב־טיפוס'],['component','Component','רכיב'],['instrument','Instrument','מכשיר מדידה']].map(([v,en,he])=><option value={v} key={v}>{pick(en,he)}</option>)}</select></label><button className="hub-button" disabled={busy}>{pick('Register asset','רישום נכס')}</button></form></details>
 <form data-build-form={draft.id} className="review-evidence-item" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{const r=await supabase.rpc('create_tracked_configuration',{p_project:projectId,p_name:name,p_revision:revision,p_kind:kind,p_details:details,p_asset:kind==='designed'?null:asset,p_parent:parent||null,p_software:software,p_calibration:calibration});if(r.error)throw new Error(r.error.message);setMessage(pick('Configuration registered. It is now available for test findings.','התצורה נשמרה וזמינה לרישום ממצאי בדיקות.'));draft.saved(initial());notifyProjectChange();}catch(e){setMessage(e instanceof Error?e.message:pick('Could not save configuration.','לא ניתן לשמור תצורה.'));}finally{setBusy(false);}}}>
 <BuildDraftNotice {...draft}/><label>{pick('Robot / prototype name','שם הרובוט / אב־הטיפוס')}<input required minLength={3} maxLength={120} value={name} onChange={e=>draft.change({name:e.target.value})}/></label>
 <label>{pick('Configuration revision','גרסת התצורה')}<input required maxLength={120} value={revision} onChange={e=>draft.change({revision:e.target.value})}/></label>
 <label>{pick('State','מצב')}<select value={kind} onChange={e=>draft.change({kind:e.target.value})}><option value="as_built">{pick('As built','כפי שנבנה')}</option><option value="as_installed">{pick('As installed','כפי שהותקן')}</option><option value="designed">{pick('Designed (not a physical test configuration)','מתוכנן (לא תצורה לבדיקה פיזית)')}</option></select></label>
 <label>{pick('Parts, software versions and configuration details','חלקים, גרסאות תוכנה ופרטי התצורה')}<textarea required minLength={3} maxLength={4000} rows={4} value={details} onChange={e=>draft.change({details:e.target.value})}/></label>
 <label>{pick('Parent design / built configuration','תצורת תכנון / בנייה קודמת')}<select required={kind!=='designed'} value={parent} onChange={e=>draft.change({parent:e.target.value})}><option value="">{pick('Choose configuration','בחירת תצורה')}</option>{configurations.filter(c=>kind!=='as_installed'||c.configuration_kind==='as_built').map(c=><option key={c.id} value={c.id}>{c.name} · {c.revision} · {c.configuration_kind}</option>)}</select></label>
 {kind!=='designed'?<><p>{pick('Create the designed configuration first, then link each built or installed revision to its parent.','צרו תחילה תצורת תכנון, ולאחר מכן קשרו כל גרסה שנבנתה או הותקנה לתצורה הקודמת.')}</p><label>{pick('Exact physical asset','הנכס הפיזי המדויק')}<select required value={asset} onChange={e=>draft.change({asset:e.target.value})}><option value="">{pick('Choose registered asset','בחירת נכס רשום')}</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name} · {a.serial}</option>)}</select></label><label>{pick('Exact software reference, or why not applicable','ייחוס תוכנה מדויק, או הסבר מדוע אינו רלוונטי')}<input required minLength={3} maxLength={500} value={software} onChange={e=>draft.change({software:e.target.value})}/></label><label>{pick('Calibration reference, or why not applicable','ייחוס כיול, או הסבר מדוע אינו רלוונטי')}<input required minLength={3} maxLength={500} value={calibration} onChange={e=>draft.change({calibration:e.target.value})}/></label></>:null}
 <button className="hub-button" disabled={busy}>{pick('Save configuration revision','שמירת גרסת תצורה')}</button><p role="status">{message}</p></form></details>;
}
