import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {useMemberAuth} from '../lib/memberAuth';
import BuildStockActions from './BuildStockActions';
type Bom={id:string;name:string;snapshot_id:string;owner_id:string;revision:number;shared_at:string|null;created_at:string};
type Line={id:string;bom_id:string;name:string;design_quantity:number;required_quantity:number;disposition:string;inventory_id:string|null;job_id:string|null;review_note:string;revision:number};
type Stock={id:string;name:string;quantity:number;unit:string};
export default function ProjectBom({projectId,canManage,canStock,canBuy,jobs,onChanged}:{projectId:string;canManage:boolean;canStock:boolean;canBuy:boolean;jobs:{id:string;part_name:string;required_quantity:number}[];onChanged:()=>Promise<void>}){
 const {pick}=useLocalization(),{profile}=useMemberAuth();
 const [boms,setBoms]=useState<Bom[]>([]),[lines,setLines]=useState<Line[]>([]),[stock,setStock]=useState<Stock[]>([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);try{const b=await supabase.from('robot_build_boms').select('*').eq('project_id',projectId).order('created_at',{ascending:false});if(b.error)throw Error();
  const l=b.data?.length?await supabase.from('robot_build_bom_lines').select('*').in('bom_id',b.data.map(b=>b.id)):{data:[],error:null};
  const s=await supabase.from('frc_parts_inventory').select('id,name,quantity,unit').eq('archived',false).eq('unit','pcs').order('name');if(l.error||s.error)throw Error();setBoms(b.data??[]);setLines(l.data??[]);setStock(s.data??[]);setMessage('');
 }catch{setMessage(pick('Parts review could not be loaded.','לא ניתן לטעון את סקירת החלקים.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[projectId]);
 return <section aria-label={pick('Project parts review','סקירת חלקי הפרויקט')}><h3>{pick('Parts to make, buy or reuse','חלקים לייצור, לרכש או לשימוש חוזר')}</h3><p role="status">{loading?pick('Loading parts…','טוען חלקים…'):message}</p>
 {!loading&&!boms.length&&!message&&<p>{pick('Import an assembly draft from CAD Mentor → Assembly parts. Existing tasks can be used independently.','יבאו טיוטת הרכבה ממנטור CAD ← חלקי ההרכבה. ניתן להשתמש במשימות הקיימות בנפרד.')} <a href="/engineering/cad">{pick('Open CAD Mentor','פתיחת מנטור CAD')}</a></p>}
 {message&&<button onClick={()=>void load()}>{pick('Retry','ניסיון חוזר')}</button>}
 {boms.map(b=><details key={b.id}><summary>{b.name} · {b.shared_at?pick('Shared project list','רשימה משותפת בפרויקט'):pick('Private draft','טיוטה פרטית')} · {new Date(b.created_at).toLocaleDateString(pick("en-GB","he-IL"),{day:"numeric",month:"short",year:"numeric"})}</summary>
  <p>{pick('Each import remains a separate revision. Lists are not added together automatically; review overlapping assemblies and purchased subassemblies before creating work.','כל ייבוא נשמר כגרסה נפרדת. הרשימות אינן מחוברות אוטומטית; בדקו הרכבות חופפות ומכלולים קנויים לפני יצירת עבודה.')}</p>
  {!b.shared_at&&b.owner_id===profile?.id&&<div><p>{pick('Sharing exposes this parts list, source identifiers and review notes to members who can view this project. It does not share CAD geometry or AI reviews.','השיתוף חושף את רשימת החלקים, מזהי המקור והערות הסקירה לחברים שיכולים לצפות בפרויקט. הוא אינו משתף גאומטריה או סקירות AI.')}</p><button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await supabase.rpc('share_robot_build_bom',{p_bom:b.id,p_expected:b.revision});if(r.error)throw Error(r.error.message);await load();}catch(e){setMessage(e instanceof Error?e.message:pick('Sharing failed.','השיתוף נכשל.'));}finally{setBusy(false);}}}>{pick('Share this parts list with project members','שיתוף רשימת החלקים עם חברי הפרויקט')}</button></div>}
  {lines.filter(l=>l.bom_id===b.id).map(l=><LineEditor key={`${l.id}/${l.revision}`} line={l} stock={stock} jobs={jobs} editable={canManage} canStock={canStock} canBuy={canBuy} shared={!!b.shared_at} saved={async()=>{await load();await onChanged();}}/>)}
 </details>)}</section>;
}
function LineEditor({line:l,stock,jobs,editable,canStock,canBuy,shared,saved}:{line:Line;stock:Stock[];jobs:{id:string;part_name:string;required_quantity:number}[];editable:boolean;canStock:boolean;canBuy:boolean;shared:boolean;saved:()=>Promise<void>}){
 const {pick}=useLocalization();const [disposition,setDisposition]=useState(l.disposition),[qty,setQty]=useState(String(l.required_quantity)),[inventory,setInventory]=useState(l.inventory_id??''),[note,setNote]=useState(l.review_note),[job,setJob]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const labels:Record<string,[string,string]>={review:['Needs review','דרושה סקירה'],make:['Make','ייצור'],buy:['Buy','רכש'],reuse:['Reuse','שימוש חוזר'],exclude:['Exclude','לא נדרש']};
 const item=stock.find(s=>s.id===l.inventory_id);
 return <article className="build-job"><div className="build-job-summary"><strong>{l.name}</strong><span>{pick(...labels[l.disposition])} · {l.required_quantity}</span></div><small>{pick('Imported quantity','כמות שיובאה')}: {l.design_quantity}</small>
 {item&&<p>{item.name} · {pick('Physical stock','מלאי פיזי')}: {item.quantity} {item.unit} · {pick('Availability must account for other reservations.','יש להתחשב בהקצאות אחרות לפני קביעת זמינות.')}</p>}
 {editable&&!l.job_id&&<details><summary>{pick('Review quantity & sourcing','בדיקת כמות ומקור')}</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await supabase.rpc('review_robot_build_line',{p_line:l.id,p_expected:l.revision,p_disposition:disposition,p_quantity:Number(qty),p_inventory:inventory||null,p_note:note});if(r.error)throw Error(r.error.message);await saved();}catch(e){setMessage(e instanceof Error?e.message:pick('Save not confirmed.','השמירה לא אושרה.'));}finally{setBusy(false);}}}><fieldset disabled={busy}>
 <label>{pick('Source','מקור')}<select required value={disposition} onChange={e=>{setDisposition(e.target.value);if(e.target.value==='exclude')setQty('0');}}>{Object.entries(labels).map(([id,label])=><option key={id} disabled={id==='review'} value={id}>{pick(...label)}</option>)}</select></label>
 <label>{pick('Required quantity','כמות נדרשת')}<input type="number" min={0} max={100000} step={1} required value={qty} onChange={e=>setQty(e.target.value)}/></label>
 <label>{pick('Confirmed inventory match','התאמה מאושרת למלאי')}<select value={inventory} onChange={e=>setInventory(e.target.value)}><option value="">{pick('Not matched','ללא התאמה')}</option>{stock.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
 <label>{pick('Decision / quantity explanation','הסבר להחלטה ולכמות')}<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button>{pick('Save review','שמירת הסקירה')}</button></fieldset></form></details>}
 {editable&&shared&&l.disposition==='make'&&!l.job_id&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await supabase.rpc('link_robot_build_line',{p_line:l.id,p_expected:l.revision,p_job:job});if(r.error)throw Error(r.error.message);await saved();}catch(e){setMessage(e instanceof Error?e.message:pick('Link not confirmed.','הקישור לא אושר.'));}finally{setBusy(false);}}}><label>{pick('Manufacturing job with matching quantity','עבודת ייצור בכמות תואמת')}<select required value={job} onChange={e=>setJob(e.target.value)}><option value="">{pick('Choose reviewed job','בחירת עבודה שנבדקה')}</option>{jobs.filter(j=>j.required_quantity===l.required_quantity).map(j=><option key={j.id} value={j.id}>{j.part_name}</option>)}</select></label><button disabled={busy||!job}>{pick('Link manufacturing job','קישור עבודת הייצור')}</button></form>}
 {shared&&['buy','reuse'].includes(l.disposition)&&l.inventory_id&&<BuildStockActions lineId={l.id} canStock={editable&&canStock} canBuy={editable&&canBuy&&l.disposition==='buy'}/>}
 {l.job_id&&<p>{pick('Linked to manufacturing. This reviewed line is retained unchanged.','מקושר לייצור. השורה שנבדקה נשמרת ללא שינוי.')}</p>}<p role="status">{message}</p></article>;
}
