import {useEffect,useRef,useState,type FormEvent} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';

export default function PurchaseQuantityApproval({request,onClose,onSaved}:{request:{id:string;item_name:string;quantity:number};onClose:()=>void;onSaved:()=>Promise<void>}){
 const {pick}=useLocalization(),dialog=useRef<HTMLDialogElement>(null);
 const [quantity,setQuantity]=useState(String(request.quantity)),[remainder,setRemainder]=useState('deferred'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const amount=Number(quantity),reduced=amount<request.quantity;
 useEffect(()=>{dialog.current?.showModal();},[]);
 async function save(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await supabase.rpc('approve_purchase_quantity',{p_purchase:request.id,p_quantity:amount,p_remainder:remainder,p_note:note.trim()});if(r.error)throw r.error;window.dispatchEvent(new Event('g3-actions-changed'));await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <dialog ref={dialog} className="quantity-approval-dialog" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><form onSubmit={save}><header><small>{pick('PURCHASE APPROVAL','אישור רכש')}</small><h2>{request.item_name}</h2><p>{pick('Originally requested','כמות מבוקשת מקורית')}: <strong>{request.quantity}</strong></p></header><label>{pick('Quantity approved now','כמות מאושרת כעת')}<input autoFocus required type="number" min="0.01" max={request.quantity} step="0.01" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label>{reduced?<><div className="purchase-remainder-summary">{pick('Remaining quantity','כמות שנותרה')}: <strong>{request.quantity-amount}</strong></div><label>{pick('Handle remaining quantity','טיפול בכמות שנותרה')}<select value={remainder} onChange={e=>setRemainder(e.target.value)}><option value="deferred">{pick('Defer for a future request','דחייה לבקשה עתידית')}</option><option value="declined">{pick('Decline the remainder','אי אישור היתרה')}</option></select></label><p>{pick('Deferred quantity is not approved spending. It can be requested later and requires a new decision.','כמות שנדחתה אינה הוצאה מאושרת. ניתן לבקש אותה בעתיד והיא דורשת החלטה חדשה.')}</p></>:null}<label>{pick(reduced?'Reason for reduction (required)':'Decision note (optional)',reduced?'סיבה להפחתה (חובה)':'הערת החלטה (רשות)')}<textarea required={reduced} minLength={reduced?3:undefined} maxLength={2000} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label>{error?<p role="alert">{error}</p>:null}<footer><button type="button" className="button-secondary" disabled={busy} onClick={onClose}>{pick('Cancel','ביטול')}</button><button className="hub-button" disabled={busy||!Number.isFinite(amount)||amount<=0||amount>request.quantity||(reduced&&note.trim().length<3)}>{busy?pick('Saving…','שומר…'):pick(`Approve ${amount}`,`אישור ${amount}`)}</button></footer></form></dialog>;
}
