import {useState,type FormEvent} from 'react';
import {useNavigate} from 'react-router-dom';
import {useAdminStatus} from '../lib/useAdminStatus';
import {useLocalization} from '../lib/localization';
import {supabase} from '../supabase';
import type {ReadinessData} from '../lib/readiness';
export default function PurchaseApprovalAging({data,error}:{data:ReadinessData['approval_aging'];error:boolean}){
 const admin=useAdminStatus(),{pick}=useLocalization(),navigate=useNavigate();const [draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 if(!admin)return null;
 async function save(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);try{const value=Number(draft||data?.threshold_hours);if(!Number.isInteger(value)||value<1||value>8760)throw Error();const r=await supabase.from('purchase_approval_settings').update({threshold_hours:value}).eq('id',true).select('threshold_hours').single();if(r.error)throw r.error;setDraft('');setMessage(pick('Threshold saved. Refreshing requests…','הסף נשמר. מרענן בקשות…'));window.dispatchEvent(new Event('g3-actions-changed'));}catch{setMessage(pick('Could not save the threshold. Try again.','לא ניתן לשמור את הסף. נסו שוב.'));}finally{setBusy(false);}}
 return <section className="hub-card home-team-risks"><header><h2>{pick('Purchasing approvals','אישורי רכש')}</h2></header>{error||!data?<p role="status">{pick('Approval aging is unavailable. Open Purchasing for current requests.','נתוני המתנה לאישורים אינם זמינים. פתחו רכש לצפייה בבקשות.')}</p>:<><p>{pick(`${data.requests.length} requests waiting at least ${data.threshold_hours} hours`,`${data.requests.length} בקשות ממתינות לפחות ${data.threshold_hours} שעות`)}</p>{data.requests.length?<details className="readiness-stock-group"><summary>{pick('Review aged requests','בדיקת בקשות ממתינות')}</summary>{data.requests.map(r=><article className="readiness-risk" key={r.id}><h3>{r.item_name}</h3><p>{pick(`Waiting ${r.waiting_hours} hours`,`ממתינה ${r.waiting_hours} שעות`)} · {new Date(r.created_at).toLocaleDateString()}</p><button onClick={()=>navigate(`/tools?tab=purchasing&purchase=${r.id}`)}>{pick('Review request','בדיקת בקשה')}</button></article>)}</details>:null}<details className="calendar-competition-link"><summary>{pick('Approval aging settings','הגדרות זמן המתנה לאישור')}</summary><form onSubmit={save} className="competition-checklist"><label>{pick('Flag after this many hours','סימון לאחר מספר שעות')}<input required type="number" min="1" max="8760" step="1" value={draft||data.threshold_hours} onChange={e=>setDraft(e.target.value)}/></label><button disabled={busy}>{pick('Save threshold','שמירת סף')}</button></form></details><small className="readiness-coverage">{pick('Up to 100 oldest requests awaiting an administrator decision. No additional notifications.','עד 100 הבקשות הוותיקות ביותר הממתינות להחלטת מנהל. ללא התראות נוספות.')}</small></>}{message?<p role="status">{message}</p>:null}</section>;
}
