import {FormEvent,useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {allocateOldest,cents,money,outstanding,recipientBalance,recipientExpenses,type Expense,type Income} from '../lib/finance';

export default function RecipientRepayment({expenses,members,income,funds,initialRecipient='',initialExpense,onClose,onSaved}:{expenses:Expense[];members:Record<string,string>;income:Income[];funds:number;initialRecipient?:string;initialExpense?:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const {pick}=useLocalization(),[recipient,setRecipient]=useState(initialRecipient),[amount,setAmount]=useState(initialExpense?String(outstanding(expenses.find(e=>e.id===initialExpense)!)/100):''),[selected,setSelected]=useState<string[]>(initialExpense?[initialExpense]:[]),[mode,setMode]=useState<'oldest'|'selected'>(initialExpense?'selected':'oldest'),[date,setDate]=useState(new Date().toLocaleDateString('en-CA')),[method,setMethod]=useState('Bank transfer'),[source,setSource]=useState('Team funds'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);
 const form=useRef<HTMLFormElement>(null),lock=useRef(false),request=useRef(crypto.randomUUID()),sent=useRef<string|null>(null);
 const eligible=recipientExpenses(expenses,recipient),balance=recipientBalance(expenses,recipient),payment=cents(amount||0),covered=mode==='oldest'?eligible:eligible.filter(e=>selected.includes(e.id)),allocations=allocateOldest(covered,Number.isFinite(payment)?payment:0),allocated=allocations.reduce((sum,a)=>sum+cents(a.amount),0);
 const validation=!recipient?pick('Choose who is receiving this repayment.','בחרו למי מבוצע ההחזר.'):!amount||!Number.isFinite(payment)||payment<=0?pick('Enter the amount paid.','הזינו את הסכום ששולם.'):payment>balance?pick('Amount exceeds this person’s total outstanding balance.','הסכום גדול מסך החוב לאדם זה.'):payment>funds?pick('Not enough recorded team funds. Record missing income before repayment.','אין מספיק כספים רשומים. רשמו הכנסות חסרות לפני ההחזר.'):allocated!==payment?pick('Select enough outstanding expenses to cover this repayment.','בחרו הוצאות פתוחות שיכסו את ההחזר.'):'';
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';form.current?.querySelector<HTMLSelectElement>('select')?.focus();const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!lock.current){e.preventDefault();onClose();}if(e.key==='Tab'){const els=Array.from(form.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')??[]);const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handle);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handle);previous?.focus();};},[onClose]);
 async function save(e:FormEvent){e.preventDefault();if(lock.current||validation||!confirmed)return;lock.current=true;setBusy(true);setError('');const body={p_recipient:recipient,p_amount:payment/100,p_allocations:allocations,p_date:date,p_method:method,p_source:source.trim(),p_note:note.trim()||null,p_expected_balance:balance/100,p_expected_funds:funds/100};const signature=JSON.stringify(body);if(sent.current&&sent.current!==signature)request.current=crypto.randomUUID();sent.current=signature;
 try{const {error}=await supabase.rpc('record_recipient_repayment',{...body,p_request:request.current});if(error)throw error;onClose();await onSaved();}catch(e){setError((e as {message?:string}).message??pick('Repayment could not be confirmed. Retry the same payment to avoid duplicates.','לא ניתן לאשר את ההחזר. נסו שוב עם אותם הפרטים למניעת כפילות.'));}finally{lock.current=false;setBusy(false);}}
 return createPortal(<div className="fp-overlay" dir={pick("ltr","rtl")}><form ref={form} className="fp-dialog" role="dialog" aria-modal="true" aria-labelledby="repayment-title" onSubmit={save}><header className="fp-dialog-header"><div><span className="fp-eyebrow">{pick('TEAM FINANCE','כספי הקבוצה')}</span><h2 id="repayment-title">{pick('Record a repayment','רישום החזר')}</h2><p>{pick('Choose the recipient and the expenses this payment covers.','בחרו את מקבל/ת ההחזר ואת ההוצאות שהתשלום מכסה.')}</p></div><button type="button" className="fp-close" aria-label={pick('Close repayment','סגירת ההחזר')} disabled={busy} onClick={onClose}>×</button></header>
 <div className="fp-dialog-body"><fieldset disabled={busy} className="fp-repayment-fields"><div className="fp-form-grid"><label className="fp-wide">{pick('Pay to','למי מחזירים')}<select value={recipient} required onChange={e=>{setRecipient(e.target.value);setAmount('');setSelected([]);setMode('oldest');setConfirmed(false);setError('');}}><option value="">{pick('Select a person','בחירת אדם')}</option>{Object.entries(members).map(([id,name])=><option key={id} value={id}>{name} — {money(recipientBalance(expenses,id)/100)} {pick('owed','יתרה')}</option>)}</select></label><label>{pick('Amount paid (ILS)','סכום ששולם (ש״ח)')}<input inputMode="decimal" type="number" required min="0.01" step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setConfirmed(false);}}/></label><label>{pick('Payment date','תאריך התשלום')}<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>{pick('Payment method','אמצעי תשלום')}<select value={method} onChange={e=>setMethod(e.target.value)}>{[['Bank transfer','העברה בנקאית'],['Cash','מזומן'],['Bit / PayBox','ביט / פייבוקס'],['Other','אחר']].map(([en,he])=><option value={en} key={en}>{pick(en,he)}</option>)}</select></label><label>{pick('Funding source / event','מקור הכסף / אירוע')}<input required list="fp-fund-sources" value={source} onChange={e=>setSource(e.target.value)}/><datalist id="fp-fund-sources"><option value="Team funds"/>{income.filter(i=>i.currency==='ILS').map(i=><option key={i.id} value={`${i.source_name??i.source_type} · ${i.received_on}`}/>)}</datalist></label></div>
 <section className="fp-allocation"><h3>{pick('Expenses covered','הוצאות מכוסות')}</h3><div className="fp-segment"><button type="button" aria-pressed={mode==='oldest'} onClick={()=>{setMode('oldest');setConfirmed(false);}}>{pick('Oldest first','הישנות תחילה')}</button><button type="button" aria-pressed={mode==='selected'} onClick={()=>{setMode('selected');setConfirmed(false);}}>{pick('Choose expenses','בחירת הוצאות')}</button></div><p>{pick('Payments are applied oldest-first within your selection. Partial repayment is supported.','ההחזר מחולק מהישן לחדש בתוך הבחירה. ניתן להחזיר חלק מהסכום.')}</p>{eligible.length?<div className="fp-allocation-list">{eligible.map(e=>{const paid=cents(allocations.find(a=>a.expense_id===e.id)?.amount??0);return <label className="fp-allocation-row" key={e.id}>{mode==='selected'?<input type="checkbox" checked={selected.includes(e.id)} onChange={event=>{setSelected(ids=>event.target.checked?[...ids,e.id]:ids.filter(id=>id!==e.id));setConfirmed(false);}}/>:null}<span><strong dir="auto">{e.description}</strong><small>{e.expense_date} · {pick('Expense balance','יתרת הוצאה')}: <bdi>{money(outstanding(e)/100)}</bdi></small></span><span className="fp-allocation-money"><bdi>{money(paid/100)}</bdi><small>{pick('Applied now','משולם כעת')}</small></span></label>;})}</div>:<div className="fp-empty">{recipient?pick('No outstanding ILS expenses for this person. Record their personal expense first.','אין הוצאות פתוחות בש״ח לאדם זה. תחילה רשמו את ההוצאה האישית.'):pick('Select a recipient to see their expenses.','בחרו אדם להצגת הוצאותיו.')}</div>}</section>
 <label>{pick('Reference / note','אסמכתא / הערה')}<textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder={pick('Transfer reference, receipt or explanation','מספר העברה, קבלה או הסבר')}/></label></fieldset>
 <aside className="fp-payment-summary" aria-live="polite"><span className="fp-eyebrow">{pick('BALANCE PREVIEW','תצוגת יתרות')}</span><h3 dir="auto">{members[recipient]??pick('Select recipient','בחירת מקבל/ת')}</h3><dl><div><dt>{pick('Total owed to this person','סך החוב לאדם זה')}</dt><dd><bdi>{money(balance/100)}</bdi></dd></div><div><dt>{pick('This repayment','ההחזר הנוכחי')}</dt><dd><bdi>{money((Number.isFinite(payment)?payment:0)/100)}</bdi></dd></div><div className="fp-balance-after"><dt>{pick('Still owed to this person','יישאר להחזיר לאדם זה')}</dt><dd><bdi>{money((balance-(Number.isFinite(payment)?payment:0))/100)}</bdi></dd></div><div><dt>{pick('Team funds now','כספי הקבוצה כעת')}</dt><dd><bdi>{money(funds/100)}</bdi></dd></div><div><dt>{pick('Team funds after repayment','כספי הקבוצה אחרי ההחזר')}</dt><dd><bdi>{money((funds-(Number.isFinite(payment)?payment:0))/100)}</bdi></dd></div></dl><p>{pick('The personal balance includes all outstanding ILS expenses, not only the expenses selected here.','היתרה האישית כוללת את כל ההוצאות הפתוחות בש״ח, לא רק את ההוצאות שנבחרו כאן.')}</p><p>{pick('Funds are pooled. The source name identifies where the money came from.','הכספים מנוהלים במאגר משותף. שם המקור מתעד מהיכן הגיע הכסף.')}</p></aside></div>
 <footer className="fp-dialog-footer">{error?<p className="fp-error" role="alert">{error}</p>:validation&&amount?<p className="fp-error" role="status">{validation}</p>:null}<label className="fp-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/><span>{pick('I confirm this money has been paid to the selected person.','אני מאשר/ת שהכסף שולם לאדם שנבחר.')}<small>{pick('This records the payment; it does not transfer money.','הרישום אינו מבצע העברת כסף.')}</small></span></label><div className="fp-footer-actions"><button type="button" className="fp-button" disabled={busy} onClick={onClose}>{pick('Cancel','ביטול')}</button><button className="fp-button primary" disabled={busy||!!validation||!confirmed}>{busy?pick('Saving…','שומר…'):pick('Record repayment','רישום החזר')}</button></div></footer></form></div>,document.body);
}
