import {readSoftwareContext} from '../lib/softwareWorkingContext';
import {Link} from 'react-router-dom';
import {useMemberAuth} from '../lib/memberAuth';
import {readWorkspaceDescriptor} from '../lib/logWorkspace';
import {useState} from 'react';
import {useLocalization} from '../lib/localization';
import {supabase} from '../supabase';
import {repositoryAutoJava} from '../lib/repositoryAutoExport';
import type {AutoPlan} from '../lib/autonomousExport';
import '../styles/repositoryAutoExport.css';
export default function RepositoryAutoExport({plan}:{plan:AutoPlan}){
 const {pick}=useLocalization(),[commit,setCommit]=useState(''),[checked,setChecked]=useState(''),[busy,setBusy]=useState(false),[frame,setFrame]=useState({x:'',y:'',yaw:''}),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState('');
 const {profile}=useMemberAuth();const working=profile?readSoftwareContext(profile.id):null;const context=profile?readWorkspaceDescriptor(profile.id):null;
 const unsupported=plan.route.some(p=>p.action==='intake'||p.action==='shoot');
 async function verify(){setBusy(true);setMessage('');setChecked('');try{const r=await supabase.functions.invoke('github-repositories',{body:{action:'check-commit',repository:'GlueGunAndGlitter/OFFSEASON_2026',commit:commit.toLowerCase()}});if(r.error||r.data?.error||r.data?.revision!==commit.toLowerCase())throw Error();setChecked(commit.toLowerCase());setMessage(pick('Commit accessible. Generated code still requires a build and review against this revision.','הקומיט נגיש. עדיין נדרשים בנייה וביקורת מול גרסה זו.'));}catch{setMessage(pick('Could not verify commit/access.','לא ניתן לאמת קומיט או הרשאה.'));}finally{setBusy(false);}}
 function download(){try{if(!checked||checked!==commit.toLowerCase())throw Error();const java=repositoryAutoJava(plan,checked,{x:Number(frame.x),y:Number(frame.y),yaw:Number(frame.yaw)*Math.PI/180,reviewed});const url=URL.createObjectURL(new Blob([java],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='G3GeneratedPlan.java';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(pick('Review candidate downloaded. It has not been built or deployed by the app.','מועמד לביקורת הורד. הוא לא נבנה ולא הותקן על ידי האפליקציה.'));}catch{setMessage(pick('Export blocked. Check route, frame and code revision.','הייצוא חסום. בדקו מסלול, מערכת צירים וגרסת קוד.'));}}
 return <section className="repo-auto-export"><h3>{pick('OFFSEASON_2026 · drivetrain integration','OFFSEASON_2026 · שילוב הנעה')}</h3><p>{pick('A repository-specific command for drive and wait routes. Uses the existing Swerve API, stops on cancellation and requires explicit controller limits in robot code.','פקודה ייעודית למאגר עבור מסלולי נסיעה והמתנה. משתמשת ב-Swerve הקיים, עוצרת בביטול ודורשת מגבלות בקרה מפורשות בקוד הרובוט.')}</p>
 <p>{pick('The simulator model is a separate selection; it does not identify this repository’s physical robot.','מודל הסימולציה נבחר בנפרד; הוא אינו מזהה את הרובוט הפיזי של מאגר זה.')}</p>{working&&working.repository!=='GlueGunAndGlitter/OFFSEASON_2026'&&<p role="alert">{pick('Your working repository has no export adapter here. This panel explicitly targets OFFSEASON_2026; choose its exact commit below to use it.','למאגר העבודה שלכם אין כאן מתאם ייצוא. לוח זה מיועד במפורש ל-OFFSEASON_2026; בחרו את הקומיט המדויק שלו לשימוש.')}</p>}
 {unsupported&&<p role="alert">{pick('This route includes intake or shooting. Export is blocked until those mechanism contracts are implemented; no action will be silently removed.','המסלול כולל איסוף או ירי. הייצוא חסום עד למימוש חוזי המנגנונים; שום פעולה לא תוסר בשקט.')}</p>}
 {working?.repository==='GlueGunAndGlitter/OFFSEASON_2026'&&<button onClick={()=>{setCommit(working.revision);setChecked('');}}>{pick('Use pinned working revision','שימוש בגרסת העבודה המקובעת')} · {working.revision.slice(0,8)}</button>}
 {context?.repository==='GlueGunAndGlitter/OFFSEASON_2026'&&/^[a-f0-9]{40}$/i.test(context.commit)&&<p><button onClick={()=>{setCommit(context.commit);setChecked('');}}>{pick('Use the revision selected in log inspection','שימוש בגרסה שנבחרה בבדיקת הלוג')}</button><small>{pick('This selects a planning target; it does not prove the logged deployment.','זו בחירת יעד לתכנון, לא הוכחה לגרסה שהותקנה.')}</small></p>}
 <label>{pick('Exact target commit','קומיט יעד מדויק')}<input dir="ltr" maxLength={40} disabled={busy} value={commit} onChange={e=>{setCommit(e.target.value);setChecked('');}}/></label><button disabled={busy||!/^[a-f0-9]{40}$/i.test(commit)} onClick={()=>void verify()}>{pick('Verify access & commit','אימות גישה וקומיט')}</button>
 <details><summary>{pick('Software lead: coordinate mapping','מוביל תוכנה: התאמת צירים')}</summary><p>{pick('Rigid transform: rotate Studio X/Y, then add the offsets below. Headings receive the same rotation. Alliance is already applied in Studio. Verify against known field points and the robot odometry; do not apply a second alliance flip.','התמרה קשיחה: סיבוב צירי X/Y של הסטודיו ואז הוספת ההיסטים. הכיוון מקבל אותו סיבוב. הברית כבר מוחלת בסטודיו. אמתו מול נקודות מוכרות ואודומטריית הרובוט; אין לבצע היפוך ברית נוסף.')}</p>{(['x','y','yaw'] as const).map((key,i)=><label key={key}>{pick(['Origin X (m)','Origin Y (m)','Rotation (degrees)'][i],['ראשית X (מטר)','ראשית Y (מטר)','סיבוב (מעלות)'][i])}<input type="number" step="any" value={frame[key]} onChange={e=>{setFrame(old=>({...old,[key]:e.target.value}));setReviewed(false);}}/></label>)}<label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>{pick('I verified this mapping against the robot coordinate convention.','אימתתי את ההתאמה מול מערכת הצירים של הרובוט.')}</label></details>
 <button disabled={unsupported||busy||!checked||!reviewed||Object.values(frame).some(v=>v.trim()===''||!Number.isFinite(Number(v)))} onClick={download}>{pick('Download command for code review','הורדת פקודה לביקורת קוד')}</button><p>{pick('Place under frc/robot/commands in a review branch. Call create(existingSwerve, approvedLimits) from the autonomous selection only after build and review. This is a bounded feedback candidate, not a calibrated trajectory controller.','יש למקם תחת frc/robot/commands בענף ביקורת. יש לקרוא ל-create עם Swerve קיים ומגבלות מאושרות מבחירת האוטונומי רק אחרי בנייה וביקורת. זהו מועמד בקרת משוב מוגבל, לא בקר מסלול מכויל.')}</p><p role="status">{message}</p><ol><li>{pick('Review the downloaded command and approved limits in your IDE.','סקרו את הפקודה שהורדה ואת המגבלות המאושרות בסביבת הפיתוח.')}</li><li>{pick('Run the project build and tests. App-triggered builds are deferred; GitHub remains read-only.','הריצו בנייה ובדיקות בפרויקט. בנייה מתוך האפליקציה נדחתה; GitHub נשאר לקריאה בלבד.')}</li><li>{pick('Record the actual robot or simulation test, then inspect its log.','תעדו בדיקת רובוט או סימולציה שבוצעה בפועל, ואז בדקו את הלוג.')}</li></ol><Link to="/engineering?view=tests">{pick('Tests & results','בדיקות ותוצאות')}</Link> · <Link to="/engineering?view=logs">{pick('Logs & diagnosis','לוגים ואבחון')}</Link></section>;
}
