import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useLocalization} from '../lib/localization';
import {useMemberAuth} from '../lib/memberAuth';
import {assistDraftKey} from '../lib/assistDecision';
export default function ReviewedSoftwareTask({message}:{message:string}){
 const {pick}=useLocalization(),{profile}=useMemberAuth(),navigate=useNavigate();
 const [title,setTitle]=useState(''),[summary,setSummary]=useState(''),[criterion,setCriterion]=useState(''),[reviewed,setReviewed]=useState(false),[error,setError]=useState('');
 return <details className="log-assist-draft"><summary>{pick('Assign a reviewed follow-up','הקצאת המשך טיפול לאחר סקירה')}</summary><p>{pick('Write a summary safe for the project team and a measurable acceptance criterion. Private code and the AI answer are not copied. The original conversation remains restricted to its owner.','כתבו סיכום מתאים לשיתוף בצוות ותנאי קבלה מדיד. הקוד הפרטי ותשובת הבינה אינם מועתקים. השיחה המקורית נשארת מוגבלת לבעליה.')}</p><label>{pick('Task title','כותרת משימה')}<input maxLength={150} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{pick('Reviewed problem and next action','בעיה שנבדקה ופעולה הבאה')}<textarea maxLength={2000} value={summary} onChange={e=>{setSummary(e.target.value);setReviewed(false);}}/></label><label>{pick('How will we verify the fix?','כיצד נאמת את התיקון?')}<textarea maxLength={1000} value={criterion} onChange={e=>{setCriterion(e.target.value);setReviewed(false);}}/></label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>{pick('I reviewed this text for sharing with the project team.','בדקתי שהטקסט מתאים לשיתוף עם צוות הפרויקט.')}</label><button disabled={!profile||!reviewed||title.trim().length<3||summary.trim().length<3||criterion.trim().length<3||!/^[0-9a-f-]{36}$/i.test(message)} onClick={()=>{try{if(!profile)return;const key=assistDraftKey(profile.id);if(sessionStorage.getItem(key))throw Error();sessionStorage.setItem(key,JSON.stringify({version:1,member:profile.id,message,request:crypto.randomUUID(),title:title.trim(),reviewedSummary:summary.trim(),criterion:criterion.trim()}));navigate('/projects?assistantDraft=1&subteam=software');}catch{setError(pick('Finish the existing task draft in Projects before preparing another.','השלימו את טיוטת המשימה הקיימת בפרויקטים לפני הכנת טיוטה נוספת.'));}}}>{pick('Choose project & owner','בחירת פרויקט ואחראי')}</button>{error&&<p role="alert">{error}</p>}</details>;
}
