import {PhysicalMeasurementEditor,emptyMeasurement,type PhysicalMeasurement} from './PhysicalMeasurement';
import {useProjectConfigurations} from './ProjectConfigurations';
import {useState} from 'react';
import {useLocalization} from '../lib/localization';
import type {EvidenceItem} from './ReviewEvidence';
export type Requirement={id:string;requirement:string;acceptance:string;method:string};
export type RequirementResult={result:string;evidence:number;note:string;configuration:string;expires_at:string|null;measurement?:Omit<PhysicalMeasurement,"value"|"samples">&{value:number;samples:number}};
export function ReviewResults({projectId,submission,canReview,canWaive,busy,onSave}:{projectId:string;submission:{id:string;requirements?:Requirement[];requirement_results?:Record<string,RequirementResult>;evidence_items?:EvidenceItem[]};canReview:boolean;canWaive:boolean;busy:boolean;onSave:(args:Record<string,unknown>)=>Promise<boolean>}){
 const {pick}=useLocalization();const configurations=useProjectConfigurations(projectId);
 const [editing,setEditing]=useState<string|null>(null),[result,setResult]=useState('passed'),[evidence,setEvidence]=useState(''),[note,setNote]=useState(''),[configuration,setConfiguration]=useState(''),[expiry,setExpiry]=useState('');
 const [measurement,setMeasurement]=useState(emptyMeasurement);
 if(!submission.requirements?.length)return null;
 return <section className="review-evidence-editor"><h4>{pick('Requirement results','תוצאות הדרישות')}</h4>
 {submission.requirements.map(r=>{const saved=submission.requirement_results?.[r.id];const expired=saved?.result==='waived'&&!!saved.expires_at&&Date.parse(saved.expires_at)<=Date.now();return <article className="review-evidence-item" key={r.id}>
 <strong>{r.requirement}</strong><p className="review-copy">{r.acceptance}</p><small>{r.method==='test'?pick('Test','בדיקה'):r.method==='inspection'?pick('Inspection','ביקורת'):r.method==='analysis'?pick('Analysis','ניתוח'):pick('Demonstration','הדגמה')}</small>
 <strong>{expired?pick('Waiver expired','תוקף החריגה פג'):saved?.result==='passed'?pick('Passed','עבר'):saved?.result==='failed'?pick('Failed','נכשל'):saved?.result==='waived'?pick('Waived — not passed','חריגה מאושרת — לא עבר'):pick('Not assessed','טרם נבדק')}</strong>
 {saved?<><p>{saved.note}</p>{saved.measurement?<p>{saved.measurement.value} {saved.measurement.unit} · n={saved.measurement.samples} · {saved.measurement.instrument}<br/>{saved.measurement.asset} · {saved.measurement.conditions}<br/>{saved.measurement.calibration}</p>:null}{saved.configuration?<small>{pick('Tested configuration','תצורה שנבדקה')}: {saved.configuration}</small>:null}{saved.expires_at?<small>{pick('Expires','בתוקף עד')}: {new Date(saved.expires_at).toLocaleString()}</small>:null}</>:null}
 {editing===r.id?<form onSubmit={async e=>{e.preventDefault();const ok=await onSave({p_submission:submission.id,p_requirement:r.id,p_result:result,p_evidence:Number(evidence),p_note:note,p_configuration_id:configuration||null,p_expires_at:result==='waived'?new Date(expiry).toISOString():null,p_measurement:['test','demonstration'].includes(r.method)?{...measurement,value:Number(measurement.value),samples:Number(measurement.samples)}:null});if(ok)setEditing(null);}}>
 <label>{pick('Result','תוצאה')}<select value={result} onChange={e=>setResult(e.target.value)}>{canReview?<><option value="passed">{pick('Passed','עבר')}</option><option value="failed">{pick('Failed','נכשל')}</option></>:null}{canWaive?<option value="waived">{pick('Waive with expiry','אישור חריגה עם תפוגה')}</option>:null}</select></label>
 <label>{pick('Submitted evidence','ראיות שהוגשו')}<select required value={evidence} onChange={e=>setEvidence(e.target.value)}><option value="">{pick('Select evidence','בחירת ראיה')}</option>{submission.evidence_items?.map((x,i)=><option value={i} key={i}>{x.title} · {x.revision}</option>)}</select></label>
 {['test','demonstration'].includes(r.method)?<label>{pick('Exact prototype / robot configuration tested','התצורה המדויקת של האב־טיפוס / הרובוט שנבדקה')}<select required value={configuration} onChange={e=>{setConfiguration(e.target.value);const serial=configurations.find(c=>c.id===e.target.value)?.identity_snapshot?.asset?.serial;if(serial)setMeasurement(m=>({...m,asset:serial}));}}><option value="">{pick('Select saved physical configuration','בחירת תצורה פיזית שמורה')}</option>{configurations.filter(c=>c.configuration_kind!=='designed').map(c=><option value={c.id} key={c.id}>{c.name} · {c.revision}</option>)}</select></label>:null}
 {['test','demonstration'].includes(r.method)?<PhysicalMeasurementEditor value={measurement} onChange={setMeasurement}/>:null}
 <label>{pick('Findings and measurements','ממצאים ומדידות')}<textarea required minLength={3} maxLength={2000} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label>
 {result==='waived'?<label>{pick('Waiver expiry (up to 30 days)','תפוגת החריגה (עד 30 יום)')}<input required type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label>:null}
 <div className="review-buttons"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>{pick('Cancel','ביטול')}</button><button className="hub-button" disabled={busy}>{pick('Save finding','שמירת ממצא')}</button></div>
 </form>:(canReview||canWaive)?<button type="button" className="hub-button secondary" disabled={busy} onClick={()=>{setEditing(r.id);setResult(canReview?'passed':'waived');setEvidence(saved?String(saved.evidence):'');setNote(saved?.note??'');setConfiguration('');setExpiry('');setMeasurement(saved?.measurement?{...saved.measurement,value:String(saved.measurement.value),samples:String(saved.measurement.samples)}:emptyMeasurement());}}>{pick('Record finding','רישום ממצא')}</button>:null}
 </article>;})}</section>;
}
