import {useEffect,useState} from 'react';import {supabase} from '../supabase';import {useLocalization} from '../lib/localization';
export const reviewStages=[['concept_approved','Concept approval','אישור רעיון'],['prototype_validated','Prototype validation','אימות אב־טיפוס'],['design_review_passed','Design review','סקר תכן'],['released_for_manufacturing','Manufacturing release','שחרור לייצור'],['qc_accepted','Quality acceptance','קבלת איכות'],['cleared_for_installation','Installation clearance','אישור להתקנה'],['installed','Installation record','תיעוד התקנה'],['verified_on_robot','Robot verification','אימות על הרובוט'],['competition_ready','Competition readiness','מוכנות לתחרות']];
export function ReviewStage({taskId,canManage,onChanged}:{taskId:string;canManage:boolean;onChanged:()=>Promise<void>}){
 const {pick}=useLocalization();const [stage,setStage]=useState(''),[saved,setSaved]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;void supabase.from('project_review_gates').select('decision_type').eq('task_id',taskId).single().then(r=>{if(!active)return;if(r.error){setMessage(pick('Stage configuration is unavailable.','הגדרות השלב אינן זמינות.'));return;}setSaved(r.data.decision_type);setStage(r.data.decision_type==='legacy_review'?'':r.data.decision_type);});return()=>{active=false;};},[taskId]);
 const label=reviewStages.find(s=>s[0]===saved);
 return <section className="review-evidence-editor"><h4>{pick('Engineering decision','החלטה הנדסית')}</h4><p>{label?pick(label[1],label[2]):pick('Select a decision stage before sending new work for review.','יש לבחור שלב החלטה לפני שליחת עבודה חדשה לביקורת.')}</p><small>{pick('Approval applies only to this stage and revision. It does not approve later stages.','האישור חל רק על השלב והגרסה האלה. הוא אינו מאשר שלבים מאוחרים יותר.')}</small>
 {message?<p role="status">{message}</p>:null}{canManage?<details><summary>{pick('Configure decision stage','הגדרת שלב החלטה')}</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await supabase.rpc('configure_project_review_stage',{p_task:taskId,p_stage:stage,p_reason:reason});setBusy(false);if(r.error){setMessage(r.error.message);return;}setSaved(stage);setReason('');setMessage(pick('Stage saved. Submit a new revision for approval.','השלב נשמר. יש להגיש גרסה חדשה לאישור.'));await onChanged();}}>
 <label>{pick('Stage','שלב')}<select required value={stage} onChange={e=>setStage(e.target.value)}><option value="">{pick('Choose stage','בחירת שלב')}</option>{reviewStages.map(([v,en,he])=><option key={v} value={v}>{pick(en,he)}</option>)}</select></label><label>{pick('Reason — changing stage resets current approval','סיבה — שינוי שלב מאפס אישור נוכחי')}<textarea required minLength={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="hub-button" disabled={busy}>{pick('Save decision stage','שמירת שלב החלטה')}</button></form></details>:null}</section>;
}
