import {useEffect,useState,type ReactNode} from 'react';
import {useSearchParams} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {readAllEvidence} from '../lib/knowledgeSources';
import {filterParams,researchFilters,ResearchFilters,ResearchRobot,ResearchTopic,RobotSearch,sourceLink,toggleSelection,topicMatches} from '../lib/robotResearch';
import RobotResearchAdmin from './RobotResearchAdmin';
import CollectedSourceResults from './CollectedSourceResults';
import type {CollectedSourceSearch} from '../lib/collectedSources';
import '../styles/robotResearch.css';

export default function RobotResearch({admin,sourceSearch,initialView,teamResults}:{admin:boolean;sourceSearch?:CollectedSourceSearch;initialView?:'sources'|'robots';teamResults?:ReactNode}){
 const [resultView,setResultView]=useState<'sources'|'robots'>(initialView??(sourceSearch?'sources':'robots'));
 const {pick}=useLocalization();const [params,setParams]=useSearchParams();const filters=researchFilters(params);
 const [topics,setTopics]=useState<ResearchTopic[]>([]),[topicQuery,setTopicQuery]=useState(''),[result,setResult]=useState<RobotSearch|null>(null);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[compare,setCompare]=useState<ResearchRobot[]>([]);
 const [filtersOpen,setFiltersOpen]=useState(()=>window.matchMedia('(min-width: 901px)').matches);
 const [notice,setNotice]=useState('');const [queryDraft,setQueryDraft]=useState(filters.query);
 const patch=(value:Partial<ResearchFilters>)=>setParams(filterParams(params,value));
 const filterKey=JSON.stringify(filters);
 useEffect(()=>{setQueryDraft(filters.query);},[filters.query]);
 useEffect(()=>{
  let current=true;setLoading(true);setError('');
  const timer=setTimeout(async()=>{try{
   const [available,response]=await Promise.all([readAllEvidence<ResearchTopic>('frc_research_topics'),supabase.rpc('search_frc_robots',{p_topics:filters.topics,p_mode:filters.mode,p_seasons:filters.seasons,p_query:filters.query,p_exclude:filters.exclude,p_page:filters.page})]);
   if(response.error)throw response.error;
   if(current){setTopics(available);setResult(response.data as RobotSearch);}
  }catch{if(current){setResult(null);setError(pick('Robot research is unavailable. Existing evidence and the knowledge library remain available. Retry, or ask an administrator to check that the research migration is installed.','מחקר הרובוטים אינו זמין. המקורות וספריית הידע הקיימים עדיין זמינים. נסו שוב או פנו למנהל לבדיקת התקנת העדכון.'));}}
  finally{if(current)setLoading(false);}},150);
  return()=>{current=false;clearTimeout(timer);};
 // The serialized filters deliberately include every search field.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[filterKey,refresh]);
 const activeTopics=topics.filter(t=>t.active),label=(t:ResearchTopic)=>pick(t.name,t.name_he||t.name);
 const name=(id:string)=>{const t=topics.find(x=>x.id===id);return t?label(t):id;};
 function choose(id:string){patch({topics:toggleSelection(filters.topics,id),exclude:filters.exclude.filter(x=>x!==id)});}
 function compareRobot(robot:ResearchRobot){if(compare.some(r=>r.id===robot.id)){setCompare(compare.filter(r=>r.id!==robot.id));return;}if(compare.length===3){setNotice(pick('Compare up to three configurations. Remove one to add another.','ניתן להשוות עד שלוש תצורות. הסירו אחת כדי להוסיף אחרת.'));return;}setNotice('');setCompare([...compare,robot]);}
 const yearOptions=[...new Set([...Array.from({length:Math.max(1,new Date().getFullYear()-2016)},(_,i)=>2017+i),...(result?.coverage.map(c=>c.season)??[]),...filters.seasons])].sort((a,b)=>b-a);
 return <section className="robot-research" aria-labelledby="robot-research-title">
  <header className="research-intro"><div><small>{pick('DESIGN RESEARCH','מחקר תכן')}</small><h2 id="robot-research-title">{resultView==='sources'?pick('Search engineering knowledge','חיפוש ידע הנדסי'):pick('Learn from real robots','ללמוד מרובוטים אמיתיים')}</h2><p>{sourceSearch?pick('Search collected sources and reviewed robot configurations with the same filters.','חפשו במקורות שנאספו ובתצורות רובוט שנבדקו באמצעות אותם מסננים.'):pick('Choose mechanisms, find documented robot configurations and compare the evidence.','בחרו מנגנונים, מצאו תצורות רובוט מתועדות והשוו את המקורות.')}</p></div><span className="research-badge">{pick('Deterministic search · No AI required','חיפוש דטרמיניסטי · ללא צורך בבינה מלאכותית')}</span></header>
  <div className="research-layout"><aside className="research-filters" aria-label={pick('Robot filters','מסנני רובוטים')}>
   <div className="research-filter-heading"><h3>{pick('Find a design','מציאת תכן')}</h3><button type="button" onClick={()=>{setQueryDraft('');setTopicQuery('');patch({topics:[],exclude:[],seasons:[],query:'',mode:'all',teams:[],source:''});}}>{pick('Reset','איפוס')}</button></div>
   <form onSubmit={e=>{e.preventDefault();patch({query:queryDraft});}} className="research-keywords"><label>{pick('Team, robot or keywords','קבוצה, רובוט או מילות מפתח')}<input maxLength={200} value={queryDraft} onChange={e=>setQueryDraft(e.target.value)} placeholder={pick('Team number, name, design…','מספר קבוצה, שם, תכן…')}/></label><button type="submit">{pick('Search','חיפוש')}</button></form>
   <details className="research-advanced-filters" open={filtersOpen} onToggle={e=>setFiltersOpen(e.currentTarget.open)}><summary>{pick('Topics, seasons & source filters','מסנני נושאים, עונות ומקורות')}</summary>
   {sourceSearch&&resultView==='sources'&&<fieldset><legend>{pick('Source filters','מסנני מקורות')}</legend><label>{pick('Source type','סוג מקור')}<select value={filters.source??''} onChange={e=>patch({source:e.target.value})}><option value="">{pick('All sources','כל המקורות')}</option><option value="official">{pick('Official documentation','תיעוד רשמי')}</option><option value="team">{pick('Teams & community','קבוצות וקהילה')}</option><option value="other">{pick('Other references','מקורות אחרים')}</option></select></label><label>{pick('Associated teams (comma separated)','קבוצות משויכות (מופרדות בפסיק)')}<input key={(filters.teams??[]).join(',')} defaultValue={(filters.teams??[]).join(',')} placeholder="254, 6328, 6740" onBlur={e=>patch({teams:[...new Set(e.target.value.split(/[ ,]+/).map(Number).filter(n=>Number.isInteger(n)&&n>0&&n<100000))].slice(0,50)})}/></label><small>{pick('An association does not prove that a team used a mechanism.','שיוך לקבוצה אינו מוכיח שהקבוצה השתמשה במנגנון.')}</small></fieldset>}
   <fieldset><legend>{pick('Mechanisms & topics','מנגנונים ונושאים')}</legend><label className="research-topic-search">{pick('Find an option','חיפוש אפשרות')}<input value={topicQuery} onChange={e=>setTopicQuery(e.target.value)} placeholder={pick('Elevator, turret, PID…','מעלית, צריח, PID…')}/></label>
   <div className="research-topic-list">{(['mechanism','subject'] as const).map(kind=><div key={kind}><h4>{kind==='mechanism'?pick('Robot mechanisms','מנגנוני רובוט'):pick('Engineering subjects','נושאים הנדסיים')}</h4>{activeTopics.filter(t=>t.kind===kind&&topicMatches(t,topicQuery)).map(t=><label className="research-check" key={t.id}><input type="checkbox" checked={filters.topics.includes(t.id)} onChange={()=>choose(t.id)}/><span>{label(t)}</span></label>)}</div>)}{!activeTopics.some(t=>topicMatches(t,topicQuery))&&<p>{pick('No matching topic. Try another name.','לא נמצא נושא תואם. נסו שם אחר.')}</p>}</div>
   </fieldset>
   <fieldset><legend>{pick('Match selected topics','התאמה לנושאים שנבחרו')}</legend><div className="research-match">{(['all','any'] as const).map(mode=><label key={mode}><input type="radio" name="research-match" checked={filters.mode===mode} onChange={()=>patch({mode})}/>{mode==='all'?pick('All selected','כל הנבחרים'):pick('Any selected','אחד מהנבחרים')}</label>)}</div></fieldset>
   <details><summary>{pick('Seasons','עונות')} · {filters.seasons.length||pick('All','כולן')}</summary><p>{pick('Leave every year unchecked to search all seasons.','ללא בחירת שנה, החיפוש יכלול את כל העונות.')}</p><div className="research-years">{yearOptions.map(year=><label className="research-check" key={year}><input type="checkbox" checked={filters.seasons.includes(year)} onChange={()=>patch({seasons:toggleSelection(filters.seasons,year)})}/>{year}</label>)}</div></details>
   <details><summary>{pick('Documented absence','היעדר מתועד')}</summary><p>{pick('Require evidence that a mechanism was absent. Unknown does not count as absent.','נדרשת אסמכתא לכך שהמנגנון לא היה קיים. מידע חסר אינו הוכחה להיעדר.')}</p>{activeTopics.filter(t=>t.kind==='mechanism').map(t=><label className="research-check" key={t.id}><input type="checkbox" checked={filters.exclude.includes(t.id)} onChange={()=>patch({exclude:toggleSelection(filters.exclude,t.id),topics:filters.topics.filter(x=>x!==t.id)})}/>{label(t)}</label>)}</details>
   </details>
  </aside>
  <div className="research-results" aria-busy={loading}>
   <div className="research-chips">{filters.topics.map(id=><button key={id} onClick={()=>patch({topics:filters.topics.filter(x=>x!==id)})} aria-label={`${pick('Remove','הסרת')} ${name(id)}`}>{name(id)} ×</button>)}{filters.exclude.map(id=><button key={'no'+id} onClick={()=>patch({exclude:filters.exclude.filter(x=>x!==id)})}>{pick('Absent','ללא')}: {name(id)} ×</button>)}{filters.seasons.map(year=><button key={year} onClick={()=>patch({seasons:filters.seasons.filter(x=>x!==year)})}>{year} ×</button>)}{filters.query&&<button onClick={()=>patch({query:''})}>{filters.query} ×</button>}</div>
   {sourceSearch&&!initialView&&<nav className="research-result-views" aria-label={pick('Result type','סוג תוצאות')}><button aria-pressed={resultView==='sources'} onClick={()=>setResultView('sources')}>{pick('Source passages','קטעי מקור')}</button><button aria-pressed={resultView==='robots'} onClick={()=>setResultView('robots')}>{pick('Reviewed robot configurations','תצורות רובוט שנבדקו')}{!loading&&!error&&result?` · ${result.total}`:''}</button></nav>}
   {teamResults}
   {sourceSearch&&resultView==='sources'&&<CollectedSourceResults key={JSON.stringify([filters,refresh])} filters={filters} search={sourceSearch}/>}
   {resultView==='robots'&&(loading?<p role="status">{pick('Searching reviewed records…','מחפש ברשומות שנבדקו…')}</p>:error?<div role="alert" className="research-empty"><p>{error}</p><button onClick={()=>setRefresh(n=>n+1)}>{pick('Retry','ניסיון נוסף')}</button></div>:result&&<>
    <div className="research-result-heading"><h3>{result.total} {result.total===1?pick('robot configuration','תצורת רובוט'):pick('robot configurations','תצורות רובוט')}</h3><button onClick={async()=>{try{await navigator.clipboard.writeText(window.location.href);setNotice(pick('Search link copied. Recipients need evidence access.','קישור החיפוש הועתק. לנמענים נדרשת הרשאה למקורות.'));}catch{setNotice(pick('Copy this page address to share your filters.','העתיקו את כתובת העמוד כדי לשתף את המסננים.'));}}}>{pick('Copy search link','העתקת קישור לחיפוש')}</button></div>
    <p className="research-coverage">{pick('Coverage','כיסוי')}: {result.coverage.map(c=>`${c.season}: ${c.configurations}`).join(' · ')||pick('No reviewed robot records yet','אין עדיין רשומות רובוט שנבדקו')}. {pick('Counts describe this catalogue, not every robot that competed.','המספרים מתארים את הקטלוג הזה, ולא את כל הרובוטים שהתחרו.')}</p>
    {!result.rows.length&&<div className="research-empty"><h3>{pick('No reviewed robot configurations match','אין תצורות רובוט שנבדקו התואמות לחיפוש')}</h3><p>{pick('No matching configuration has been established by the reviewed evidence in this catalogue. This does not mean the mechanism was never used.','לא נקבעה תצורה תואמת במקורות שנבדקו בקטלוג זה. אין פירוש הדבר שמעולם לא השתמשו במנגנון.')}</p>{sourceSearch&&<button onClick={()=>setResultView('sources')}>{pick('Search collected source passages','חיפוש בקטעי המקורות שנאספו')}</button>}</div>}
    <div className="research-cards">{result.rows.map(robot=><article className="research-card" key={robot.id}><div className="research-card-top"><span>{robot.season} · {pick('Team','קבוצה')} {robot.team}</span><label className="research-check"><input type="checkbox" checked={compare.some(r=>r.id===robot.id)} onChange={()=>compareRobot(robot)}/>{pick('Compare','השוואה')}</label></div><h3>{robot.name}</h3><p className="research-configuration">{robot.configuration}</p><div className="research-fact-tags">{[...new Set(robot.facts.map(f=>f.topic_id))].map(id=>{const facts=robot.facts.filter(f=>f.topic_id===id);return <span key={id} className={filters.topics.includes(id)?'selected':''}>{facts.some(f=>f.present)?'':pick('Absent: ','ללא: ')}{name(id)}</span>;})}</div><details><summary>{pick('Read supporting evidence','קריאת המקורות התומכים')} · {robot.facts.length}</summary>{robot.facts.map(f=><div className="research-citation" key={f.id}><strong>{pick(f.topic_name,f.topic_name_he||f.topic_name)} · {f.present?pick('Documented','מתועד'):pick('Documented absence','היעדר מתועד')}</strong><p>{f.body}</p><a href={sourceLink(f.url)} target="_blank" rel="noreferrer">{f.source_title} ↗</a><small>{f.locator} · {f.source_revision}</small></div>)}</details></article>)}</div>
    {result.total>12&&<nav className="research-pagination" aria-label={pick('Search pages','עמודי חיפוש')}><button disabled={!filters.page} onClick={()=>patch({page:filters.page-1})}>{pick('Previous','הקודם')}</button><span>{filters.page+1} / {Math.ceil(result.total/12)}</span><button disabled={(filters.page+1)*12>=result.total} onClick={()=>patch({page:filters.page+1})}>{pick('Next','הבא')}</button></nav>}
   </>)}
   <p role="status">{notice}</p>{compare.length>0&&<a className="research-compare-jump" href="#research-comparison">{pick("Compare selected configurations","השוואת התצורות שנבחרו")} · {compare.length} ↓</a>}
   {compare.length>0&&<section id="research-comparison" className="research-comparison"><div className="research-result-heading"><h3>{pick('Compare documented designs','השוואת תכן מתועד')}</h3><button onClick={()=>setCompare([])}>{pick('Clear comparison','ניקוי השוואה')}</button></div><p>{pick('Up to three configurations. Unknown means not established by the reviewed evidence.','עד שלוש תצורות. לא ידוע פירושו שהמידע לא נקבע במקורות שנבדקו.')}</p><div className="research-table-scroll" tabIndex={0} role="region" aria-label={pick('Robot comparison table','טבלת השוואת רובוטים')}><table><thead><tr><th>{pick('Topic','נושא')}</th>{compare.map(r=><th key={r.id}>{r.team} · {r.season}<br/>{r.name}<br/><button onClick={()=>compareRobot(r)}>{pick('Remove','הסרה')}</button></th>)}</tr></thead><tbody>{[...new Set(compare.flatMap(r=>r.facts.map(f=>f.topic_id)))].map(id=><tr key={id}><th>{name(id)}</th>{compare.map(r=><td key={r.id}>{r.facts.filter(f=>f.topic_id===id).map(f=><p key={f.id}><a href={sourceLink(f.url)} target="_blank" rel="noreferrer">{f.present?pick('Present','קיים'):pick('Absent','לא קיים')} ↗</a><br/>{f.body}</p>)}{!r.facts.some(f=>f.topic_id===id)&&pick('Unknown','לא ידוע')}</td>)}</tr>)}</tbody></table></div></section>}
  </div></div>
  {admin&&<RobotResearchAdmin topics={topics} onChanged={()=>{setRefresh(n=>n+1);setCompare([]);}}/>}
 </section>;
}
