import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {ResearchTopic,sourceLink} from '../lib/robotResearch';
type Candidate={id:string;topic_id:string;claim_id:string;claim_revision:number;revision:number;status:string;robot_id:string|null;present:boolean;note:string};
type ReviewRow=Candidate&{title:string;body:string;locator:string;url:string;season:number;topic_name:string;topic_name_he:string;current:boolean};
type Config={id:string;team:number;season:number;name:string;configuration:string};
export default function RobotResearchAdmin({topics,onChanged}:{topics:ResearchTopic[];onChanged:()=>void}){
 const {pick}=useLocalization();const [open,setOpen]=useState(false),[edit,setEdit]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[rows,setRows]=useState<ReviewRow[]>([]),[configs,setConfigs]=useState<Config[]>([]),[page,setPage]=useState(0),[total,setTotal]=useState(0),[refresh,setRefresh]=useState(0),[queue,setQueue]=useState('proposed');
 const selected=topics.find(t=>t.id===edit);
 useEffect(()=>{if(!open)return;let active=true;supabase.rpc('frc_research_review_queue',{p_page:page,p_status:queue}).then(({data,error})=>{if(!active)return;if(error){setMessage(pick('Review queue unavailable. Retry after checking the database update.','תור הבדיקה אינו זמין. נסו שוב לאחר בדיקת עדכון מסד הנתונים.'));return;}setRows(data.rows);setConfigs(data.configurations);setTotal(data.total);});return()=>{active=false;};},[open,page,queue,refresh]);
 async function action(name:string,args:Record<string,unknown>,success:string){setBusy(true);setMessage('');try{const {error}=await supabase.rpc(name,args);if(error)throw error;setMessage(success);setRefresh(n=>n+1);onChanged();}catch(e){setMessage(e instanceof Error?e.message:(e as {message?:string})?.message??pick('Unable to save. Try again.','לא ניתן לשמור. נסו שוב.'));}finally{setBusy(false);}}
 return <details className="research-admin" onToggle={e=>setOpen(e.currentTarget.open)}><summary>{pick('Manage research · Admin only','ניהול מחקר · למנהלים בלבד')}</summary>
 <p>{pick('Topics create search options immediately. Text matches enter this queue as proposals; a reviewer must establish the robot configuration and check the cited evidence.','נושאים חדשים מופיעים מיד במסננים. התאמות טקסט נכנסות לתור כהצעות; בודק צריך לזהות את תצורת הרובוט ולבדוק את האסמכתא.')}</p>
 {open&&<><div className="research-admin-grid"><form key={edit||'new-topic'} onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action('save_frc_research_topic',{p_id:selected?.id??null,p_expected:selected?.revision??0,p_name:d.get('name'),p_name_he:d.get('name_he'),p_kind:d.get('kind'),p_synonyms:String(d.get('synonyms')).split(',').map(s=>s.trim()).filter(Boolean),p_description:d.get('description'),p_active:d.get('active')==='on'},pick('Topic saved. Existing indexed summaries were scanned for candidate matches.','הנושא נשמר. התקצירים באינדקס נסרקו למציאת התאמות מוצעות.'));}}>
 <h3>{pick('Topics & synonyms','נושאים ומילים נרדפות')}</h3><label>{pick('Edit topic','עריכת נושא')}<select value={edit} onChange={e=>setEdit(e.target.value)}><option value="">{pick('Add a topic','הוספת נושא')}</option>{topics.map(t=><option key={t.id} value={t.id}>{pick(t.name,t.name_he||t.name)}</option>)}</select></label>
 <label>{pick('English name','שם באנגלית')}<input name="name" required minLength={2} maxLength={80} defaultValue={selected?.name}/></label><label>{pick('Hebrew name','שם בעברית')}<input name="name_he" maxLength={80} defaultValue={selected?.name_he}/></label>
 <label>{pick('Topic type','סוג נושא')}<select name="kind" defaultValue={selected?.kind??'mechanism'}>{(['mechanism','subject'] as const).filter(k=>!selected||selected.kind===k).map(k=><option key={k} value={k}>{k==='mechanism'?pick('Robot mechanism','מנגנון רובוט'):pick('Engineering subject','נושא הנדסי')}</option>)}</select></label>
 <label>{pick('Synonyms, separated by commas','מילים נרדפות, מופרדות בפסיקים')}<input name="synonyms" maxLength={3200} defaultValue={selected?.synonyms.join(', ')} placeholder="elevators, lift, מעלית"/></label><label>{pick('Definition','הגדרה')}<textarea name="description" maxLength={1000} defaultValue={selected?.description}/></label><label className="research-check"><input name="active" type="checkbox" defaultChecked={selected?.active??true}/>{pick('Active in search','פעיל בחיפוש')}</label><button disabled={busy}>{pick('Save topic & scan','שמירת נושא וסריקה')}</button></form>
 <form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action('save_frc_robot_configuration',{p_team:Number(d.get('team')),p_season:Number(d.get('season')),p_name:d.get('name'),p_configuration:d.get('configuration')},pick('Configuration registered. Associate reviewed evidence below.','התצורה נוספה. שייכו אליה מקורות שנבדקו בהמשך.'));}}><h3>{pick('Register a robot configuration','הוספת תצורת רובוט')}</h3><p>{pick('Use a separate configuration for a rebuild or a documented mechanism change.','השתמשו בתצורה נפרדת לבנייה מחדש או לשינוי מתועד במנגנונים.')}</p><label>{pick('Team number','מספר קבוצה')}<input name="team" type="number" required min={1} max={99999}/></label><label>{pick('Season','עונה')}<input name="season" type="number" required min={1992} max={2100} defaultValue={new Date().getFullYear()}/></label><label>{pick('Robot name','שם הרובוט')}<input name="name" required maxLength={120}/></label><label>{pick('Configuration / release date','תצורה / תאריך פרסום')}<input name="configuration" required minLength={3} maxLength={160} placeholder={pick('Worlds configuration · April 2025','תצורת אליפות העולם · אפריל 2025')}/></label><button disabled={busy}>{pick('Register configuration','הוספת תצורה')}</button></form></div>
 <details><summary>{pick('Add a reviewed source reference','הוספת מקור שנבדק')}</summary><p>{pick('Record a short factual summary after reading a team or technical source. This does not download or extract the document. Topic matches will enter the review queue.','תעדו תקציר עובדתי קצר לאחר קריאת מקור קבוצתי או טכני. פעולה זו אינה מורידה או מחלצת את המסמך. התאמות לנושאים ייכנסו לתור הבדיקה.')}</p><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action('add_frc_robot_reference',{p_season:Number(d.get('season')),p_url:d.get('url'),p_source_title:d.get('source_title'),p_title:d.get('title'),p_body:d.get('body'),p_locator:d.get('locator'),p_note:d.get('note')},pick('Reference added. Review its proposed topic associations below.','המקור נוסף. בדקו את השיוכים המוצעים לנושאים בהמשך.'));}}><label>{pick('Season','עונה')}<input name="season" type="number" required min={1992} max={2100}/></label><label>{pick('Original source URL','קישור למקור המקורי')}<input name="url" type="url" required pattern="https://.*" maxLength={2000}/></label><label>{pick('Source title','כותרת המקור')}<input name="source_title" required minLength={3} maxLength={180}/></label><label>{pick('Reference title','כותרת הרשומה')}<input name="title" required minLength={3} maxLength={180}/></label><label>{pick('Factual summary','תקציר עובדתי')}<textarea name="body" required minLength={3} maxLength={1500}/></label><label>{pick('Page, section or timestamp','עמוד, סעיף או חותמת זמן')}<input name="locator" required maxLength={200}/></label><label>{pick('Review note','הערת בדיקה')}<input name="note" required minLength={3} maxLength={1000}/></label><button disabled={busy}>{pick('Save reviewed reference','שמירת מקור שנבדק')}</button></form></details>
 <div className="research-result-heading"><h3>{pick('Evidence review queue','תור בדיקת מקורות')} · {total}</h3><button disabled={busy} onClick={()=>void action('scan_frc_topic_candidates',{p_topic:null,p_claim:null},pick('Scan complete. Existing decisions were preserved.','הסריקה הושלמה. החלטות קיימות נשמרו.'))}>{pick('Scan indexed references','סריקת מקורות באינדקס')}</button></div>
 <label>{pick('Review status','מצב בדיקה')}<select value={queue} onChange={e=>{setQueue(e.target.value);setPage(0);}}><option value="proposed">{pick('Awaiting review','ממתין לבדיקה')}</option><option value="confirmed">{pick('Confirmed','אושר')}</option><option value="rejected">{pick('Rejected','נדחה')}</option></select></label>
 {!rows.length&&<p>{pick('No items in this queue. Scanning checks indexed reference summaries, not unprocessed PDFs or the internet.','אין פריטים בתור זה. הסריקה בודקת תקצירים באינדקס, ולא קובצי PDF שלא עובדו או את האינטרנט.')}</p>}
 {rows.map(row=><form className="research-review" key={row.id+row.revision} onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void action('review_frc_topic_evidence',{p_id:row.id,p_expected:row.revision,p_robot:d.get('robot')||null,p_present:d.get('present')==='yes',p_status:d.get('status'),p_note:d.get('note')},pick('Review saved. Search now uses the updated decision.','הבדיקה נשמרה. החיפוש משתמש כעת בהחלטה המעודכנת.'));}}><h4>{pick(row.topic_name,row.topic_name_he||row.topic_name)} · {row.season}</h4><strong>{row.title}</strong><p>{row.body}</p><a href={sourceLink(row.url)} target="_blank" rel="noreferrer">{pick('Inspect original source','בדיקת המקור המקורי')} ↗</a><p>{row.locator}</p>{!row.current&&<p role="alert">{pick('This evidence revision is no longer current. It cannot be confirmed.','גרסת המקור הזו כבר אינה עדכנית. לא ניתן לאשר אותה.')}</p>}<label>{pick('Documented robot configuration','תצורת הרובוט המתועדת')}<select name="robot" defaultValue={row.robot_id??''}><option value="">{pick('No robot — subject reference only','ללא רובוט — מקור בנושא בלבד')}</option>{configs.filter(c=>c.season===row.season).map(c=><option value={c.id} key={c.id}>{c.team} · {c.name} · {c.configuration}</option>)}</select></label><label>{pick('What does the evidence establish?','מה נקבע במקור?')}<select name="present" defaultValue={row.present?'yes':'no'}><option value="yes">{pick('Present / covers this subject','קיים / עוסק בנושא')}</option><option value="no">{pick('Explicitly absent','אינו קיים במפורש')}</option></select></label><label>{pick('Decision','החלטה')}<select name="status" defaultValue={row.status==='rejected'?'rejected':'confirmed'}><option value="confirmed" disabled={!row.current}>{pick('Confirm after checking source','אישור לאחר בדיקת המקור')}</option><option value="rejected">{pick('Reject association','דחיית השיוך')}</option></select></label><label>{pick('Review reason','נימוק לבדיקה')}<input name="note" required minLength={3} maxLength={1000} defaultValue={row.note}/></label><button disabled={busy}>{pick('Save review','שמירת בדיקה')}</button></form>)}
 <nav className="research-pagination"><button disabled={page===0||busy} onClick={()=>setPage(n=>n-1)}>{pick('Previous','הקודם')}</button><span>{page+1} / {Math.max(1,Math.ceil(total/10))}</span><button disabled={(page+1)*10>=total||busy} onClick={()=>setPage(n=>n+1)}>{pick('Next','הבא')}</button></nav><p role="status">{message}</p></>}
 </details>;
}
