import {useEffect,useRef,useState} from 'react';
import {useLocalization} from '../lib/localization';
import {numericLogSummary,type LogChannel,type RobotLog} from '../lib/robotLog';
import {compareLogChannels,logIdentity} from '../lib/robotLogAnalysis';
export default function RobotLogComparison({current,channel}:{current:RobotLog;channel:LogChannel}){
 const {pick}=useLocalization(),worker=useRef<Worker|null>(null),request=useRef(0);
 const [baseline,setBaseline]=useState<RobotLog|null>(null),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{request.current++;worker.current?.terminate();},[]);
 async function open(file:File){const id=++request.current;worker.current?.terminate();setBaseline(null);setError('');setName(file.name);if(file.size>32*1024*1024){setError(pick('Maximum file size: 32 MB.','גודל קובץ מרבי: 32 MB.'));return;}setBusy(true);try{const buffer=await file.arrayBuffer();if(id!==request.current)return;const task=new Worker(new URL('../lib/robotLog.worker.ts',import.meta.url),{type:'module'});worker.current=task;task.onmessage=e=>{if(id!==request.current)return;setBusy(false);task.terminate();if(e.data.error)setError(String(e.data.error));else setBaseline(e.data.log);};task.onerror=()=>{if(id!==request.current)return;setBusy(false);task.terminate();setError(pick('Could not read comparison log.','לא ניתן לקרוא לוג להשוואה.'));};task.postMessage(buffer,[buffer]);}catch{if(id===request.current){setBusy(false);setError(pick('Could not open file.','לא ניתן לפתוח קובץ.'));}}}
 const matches=baseline?.channels.filter(c=>c.name===channel.name)??[],other=matches.length===1?matches[0]:null;
 const comparison=other?compareLogChannels(channel,other):null,a=numericLogSummary(channel),b=other?numericLogSummary(other):null;
 const originalIdentity=logIdentity(current),baselineIdentity=baseline?logIdentity(baseline):null;
 return <details><summary>{pick('Compare this signal with another run','השוואת אות זה לריצה אחרת')}</summary><p>{pick('Both files stay local. This compares full-log sample statistics, not aligned events or proof of improvement. Robot setup, battery and conditions must still be checked.','שני הקבצים נשארים מקומיים. ההשוואה היא של סטטיסטיקת דגימות מכל הלוג, לא של אירועים מיושרים ולא הוכחה לשיפור. עדיין יש לבדוק תצורת רובוט, סוללה ותנאים.')}</p><input type="file" accept=".wpilog" aria-label={pick('Comparison WPILOG','WPILOG להשוואה')} onChange={e=>{const file=e.target.files?.[0];if(file)void open(file);e.target.value='';}}/>{busy&&<p role="status">{pick('Reading comparison…','קורא השוואה…')}</p>}{error&&<p role="alert">{error}</p>}
 {baseline&&<><p dir="auto">{name}</p>{!baseline.complete&&<p role="alert">{pick('Comparison log is partial.','לוג ההשוואה חלקי.')}</p>}{!other?<p>{pick('No unique matching signal in this log.','אין אות תואם יחיד בלוג זה.')}</p>:<>{!comparison?.compatible&&<p role="alert">{pick('Compatibility is not established: ','התאימות לא הוכחה: ')}{comparison?.reasons.map(r=>({UNITS_UNKNOWN:pick('units not recorded','יחידות לא תועדו'),UNIT_MISMATCH:pick('different units','יחידות שונות'),TYPE_MISMATCH:pick('different types','סוגים שונים'),SIGNAL_MISMATCH:pick('different signals','אותות שונים')})[r]).join(', ')}</p>}
 <p>{originalIdentity.commit&&baselineIdentity?.commit&&originalIdentity.commit===baselineIdentity.commit?pick('Recorded commit matches; deployment and configuration are not independently verified.','הקומיט המתועד תואם; הפריסה והתצורה לא אומתו באופן עצמאי.'):pick('Code revisions differ or are not recorded.','גרסאות הקוד שונות או לא מתועדות.')}</p>
 {a&&b?<table><thead><tr><th>{pick('Statistic','נתון')}</th><th>{pick('Current log','לוג נוכחי')}</th><th>{pick('Comparison','השוואה')}</th></tr></thead><tbody>{(['count','min','max','mean'] as const).map((key,i)=><tr key={key}><td>{pick(['Samples','Minimum','Maximum','Sample mean'][i],['דגימות','מינימום','מקסימום','ממוצע דגימות'][i])}</td><td>{a[key].toPrecision(6)}</td><td>{b[key].toPrecision(6)}</td></tr>)}</tbody></table>:<p>{pick('Numeric summary is unavailable for this channel type.','סיכום מספרי אינו זמין לסוג ערוץ זה.')}</p>}</>}</>}
 </details>;
}
