import {useEffect,useRef,useState} from 'react';
import {useLocalization} from '../lib/localization';
import {numericLogSummary,type RobotLog} from '../lib/robotLog';
import {boundedLogEvidence,logIdentity,logModes,standardModeChannels} from '../lib/robotLogAnalysis';
import {robotPurposes} from '../lib/robotRepositories';
import {supabase} from '../supabase';
import RobotLogComparison from './RobotLogComparison';
import {useMemberAuth} from '../lib/memberAuth';
import {logTrialDraftKey,parseLogTrialDraft} from '../lib/robotLogTrialDraft';
import '../styles/robotLog.css';

export default function RobotLogInspector(){
 const {pick}=useLocalization(),worker=useRef<Worker|null>(null),ticket=useRef(0);
 const {profile}=useMemberAuth();
 const [evidenceKind,setEvidenceKind]=useState<''|'physical'|'simulated'>('');
 const [component,setComponent]=useState(0);
 const [log,setLog]=useState<RobotLog|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(''),[hash,setHash]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(-1);
 const [repository,setRepository]=useState(''),[commit,setCommit]=useState(''),[checked,setChecked]=useState(''),[checking,setChecking]=useState(false),[modeIds,setModeIds]=useState([-1,-1,-1]),[windowStart,setWindowStart]=useState(''),[windowEnd,setWindowEnd]=useState('');
 useEffect(()=>()=>{ticket.current++;worker.current?.terminate();},[]);
 async function open(file:File){
  const request=++ticket.current;worker.current?.terminate();setLog(null);setSelected(-1);setHash('');setError('');setName(file.name);setBusy(true);setRepository('');setCommit('');setChecked('');setChecking(false);setModeIds([-1,-1,-1]);setWindowStart('');setWindowEnd('');setEvidenceKind('');setComponent(0);
  if(file.size>32*1024*1024){setError(pick('Choose a WPILOG file up to 32 MB.','בחרו קובץ WPILOG עד 32 MB.'));setBusy(false);return;}
  try{
   const buffer=await file.arrayBuffer();if(request!==ticket.current)return;
   const digest=await crypto.subtle.digest('SHA-256',buffer);if(request!==ticket.current)return;
   setHash(Array.from(new Uint8Array(digest),n=>n.toString(16).padStart(2,'0')).join(''));
   const task=new Worker(new URL('../lib/robotLog.worker.ts',import.meta.url),{type:'module'});worker.current=task;
   task.onmessage=e=>{if(request!==ticket.current)return;setBusy(false);task.terminate();if(e.data.error)setError(pick('This file could not be read: ','לא ניתן לקרוא את הקובץ: ')+e.data.error);else {setLog(e.data.log);setModeIds(standardModeChannels(e.data.log));}};
   task.onerror=()=>{if(request!==ticket.current)return;setBusy(false);task.terminate();setError(pick('Log reader failed. Try a smaller file.','קריאת הלוג נכשלה. נסו קובץ קטן יותר.'));};
   task.postMessage(buffer,[buffer]);
  }catch{if(request===ticket.current){setBusy(false);setError(pick('Could not open this file.','לא ניתן לפתוח את הקובץ.'));}}
 }
 const channel=log?.channels.find(c=>c.generation===selected);
 const plotted=channel?.components?{...channel,samples:channel.samples.map(s=>({...s,value:Array.isArray(s.value)?s.value[component]??'Unavailable':'Unavailable'}))}:channel;
 const stats=plotted?numericLogSummary(plotted):null;
 const identity=log?logIdentity(log):null;
 const modes=log&&modeIds[0]>=0&&modeIds[1]>=0?logModes(log,log.channels[modeIds[0]],log.channels[modeIds[1]],log.channels[modeIds[2]]):[];
 async function checkCommit(){const request=ticket.current;setChecking(true);setChecked('');setError('');try{const r=await supabase.functions.invoke('github-repositories',{body:{action:'check-commit',repository,commit:commit.trim().toLowerCase()}});if(request!==ticket.current)return;if(r.error||r.data?.error||r.data?.revision!==commit.trim().toLowerCase())throw Error();setChecked(repository+'@'+commit.trim().toLowerCase());}catch{if(request===ticket.current)setError(pick('Commit could not be verified. Check access and the full SHA.','לא ניתן לאמת את הקומיט. בדקו הרשאות ו-SHA מלא.'));}finally{if(request===ticket.current)setChecking(false);}}
 function downloadEvidence(){if(!log||!channel)return;try{const start=windowStart===''?log.start:Number(windowStart),end=windowEnd===''?log.end:Number(windowEnd);const evidence=boundedLogEvidence(log,channel,start,end);const report={schema:1,file:{name,sha256:hash},identity,association:{repository,commit,commitExists:checked===repository+'@'+commit.trim().toLowerCase(),deploymentVerified:false},evidence};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='g3-log-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError(pick('Choose a valid, smaller time window for the evidence export.','בחרו חלון זמן תקין וקטן יותר לייצוא ראיות.'));}}
 function prepareTrial(){if(!profile||!log||!evidenceKind)return;try{const key=logTrialDraftKey(profile.id);if(sessionStorage.getItem(key)){setError(pick('A log test draft already exists. Open robot test records to review it first.','כבר קיימת טיוטת בדיקה מלוג. פתחו רשומות בדיקת רובוט כדי לסקור אותה תחילה.'));return;}const start=windowStart===''?log.start:Number(windowStart),end=windowEnd===''?log.end:Number(windowEnd);if(start<log.start||end>log.end)throw Error();const draft=parseLogTrialDraft({schema:1,fileSha256:hash,start,end,repository,commit:commit.trim().toLowerCase(),kind:evidenceKind,partial:!log.complete});sessionStorage.setItem(key,JSON.stringify(draft));location.assign('/growth?view=robot-tests&logDraft=1');}catch{setError(pick('Could not prepare draft. Check the time window and commit, or export evidence instead.','לא ניתן להכין טיוטה. בדקו חלון זמן וקומיט, או ייצאו ראיות במקום זאת.'));}}
 const visible=log?.channels.filter(c=>c.name.toLowerCase().includes(query.toLowerCase()))??[];
 const points=plotted?.samples.filter(s=>typeof s.value==='number'&&Number.isFinite(s.value))??[];
 const plot=stats&&points.length&&log?points.filter((_,i)=>i%Math.max(1,Math.ceil(points.length/1000))===0).map(s=>`${10+780*(s.time-log.start)/Math.max(.001,log.end-log.start)},${150-140*((s.value as number)-stats.min)/Math.max(.000001,stats.max-stats.min)}`).join(' '):'';
 return <section className="robot-log" aria-label={pick('Robot log inspection','בדיקת לוג רובוט')}>
  <header><div><h2>{pick('Inspect a robot log','בדיקת לוג רובוט')}</h2><p>{pick('Open → inspect channels → identify the code revision.','פתיחה ← בדיקת ערוצים ← זיהוי גרסת הקוד')}</p></div><label className="hub-button">{pick('Open WPILOG','פתיחת WPILOG')}<input aria-label={pick('Choose WPILOG file','בחירת קובץ WPILOG')} type="file" accept=".wpilog" onChange={e=>{const file=e.target.files?.[0];if(file)void open(file);e.target.value='';}}/></label></header>
  <p>{pick('Local inspection: this file stays on this device. Nothing is uploaded, saved to team history or sent to AI.','בדיקה מקומית: הקובץ נשאר במכשיר. דבר אינו מועלה, נשמר בהיסטוריית הצוות או נשלח לבינה מלאכותית.')}</p>
  {busy&&<p role="status">{pick('Reading log…','קורא לוג…')} <button onClick={()=>{ticket.current++;worker.current?.terminate();setBusy(false);setName('');setHash('');}}>{pick('Cancel','ביטול')}</button></p>}
  {error&&<p role="alert">{error}</p>}
  {log&&<><h3 dir="auto">{name}</h3><p>{log.records.toLocaleString()} {pick('records','רשומות')} · {log.channels.length} {pick('channels','ערוצים')} · {(log.end-log.start).toFixed(2)} {pick('seconds','שניות')}</p>
   <p><strong>{pick('Code revision: not verified','גרסת קוד: לא אומתה')}</strong> — {pick('A filename or project label does not prove which code was running.','שם קובץ או תווית פרויקט אינם מוכיחים איזה קוד פעל.')}</p>
   <details><summary>{pick('Associate code & inspect operating modes','קישור קוד ובדיקת מצבי פעולה')}</summary>
    <p dir="auto">{pick('Recorded project','פרויקט שתועד')}: {identity?.project??pick('Not recorded','לא תועד')} · {pick('Recorded commit','קומיט שתועד')}: {identity?.commit??pick('Not recorded','לא תועד')}</p>
    <p>{identity?.dirty===true?pick('Log reports uncommitted source changes.','הלוג מדווח על שינויי מקור שלא נשמרו בקומיט.'):identity?.dirty===false?pick('Log reports a clean source tree; this is metadata, not independent deployment proof.','הלוג מדווח על עץ מקור נקי; אלו מטא־נתונים ולא הוכחה עצמאית לפריסה.'):pick('Source modification status is unknown.','מצב שינויי המקור אינו ידוע.')}</p>
    {identity?.conflicts&&<p role="alert">{pick('Conflicting source metadata. Resolve before associating results.','מטא־נתוני מקור סותרים. יש לברר לפני קישור תוצאות.')}</p>}
    <details><summary>{pick('All recorded metadata channels','כל ערוצי המטא־נתונים שתועדו')}</summary>{log.channels.filter(c=>/^\/(RealMetadata|Metadata)\//.test(c.name)).map(c=><p key={c.generation} dir="auto"><code>{c.name}</code>: {JSON.stringify(c.samples[c.samples.length-1]?.value??null).slice(0,1000)}</p>)}</details>
    <label>{pick('Repository to compare','מאגר להשוואה')}<select disabled={checking} value={repository} onChange={e=>{setRepository(e.target.value);setChecked('');}}><option value="">{pick('Choose repository','בחירת מאגר')}</option>{Object.keys(robotPurposes).map(r=><option key={r} value={'GlueGunAndGlitter/'+r}>{r}</option>)}</select></label>
    <label>{pick('Full commit SHA','SHA מלא של קומיט')}<input disabled={checking} dir="ltr" value={commit} maxLength={40} onChange={e=>{setCommit(e.target.value);setChecked('');}}/></label><button disabled={checking||!repository||!/^[a-f0-9]{40}$/i.test(commit.trim())} onClick={()=>void checkCommit()}>{checking?pick('Checking…','בודק…'):pick('Check repository commit','בדיקת קומיט במאגר')}</button>
    {checked&&<p role="status">{pick('Commit exists and is accessible. This does not prove it produced this log.','הקומיט קיים ונגיש. אין בכך הוכחה שהוא יצר את הלוג.')}</p>}
    {identity?.commit&&commit.trim()&&identity.commit!==commit.trim().toLowerCase()&&<p role="alert">{pick('Selected commit differs from the recorded log commit.','הקומיט שנבחר שונה מהקומיט שתועד בלוג.')}</p>}
    {(['Enabled','Autonomous','Test'] as const).map((label,index)=><label key={label}>{pick(label+' channel',['ערוץ הפעלה','ערוץ אוטונומי','ערוץ בדיקה'][index])}<select value={modeIds[index]} onChange={e=>setModeIds(old=>old.map((n,i)=>i===index?Number(e.target.value):n))}><option value={-1}>{pick('Not mapped','לא מופה')}</option>{log.channels.filter(c=>c.type==='boolean'&&!modeIds.some((n,i)=>i!==index&&n===c.generation)).map(c=><option key={c.generation} value={c.generation}>{c.name}</option>)}</select></label>)}
    {modes.length>0&&<table><thead><tr><th>{pick('Mode','מצב')}</th><th>{pick('Start / end (log seconds)','התחלה / סוף (שניות לוג)')}</th></tr></thead><tbody>{modes.slice(0,100).map((m,i)=><tr key={i}><td>{pick(m.mode,({disabled:'מושבת',autonomous:'אוטונומי',teleop:'נהיגה',test:'בדיקה',unknown:'לא ידוע'})[m.mode])}</td><td>{m.start.toFixed(3)}–{m.end.toFixed(3)}</td></tr>)}</tbody></table>}
    {modes.length>100&&<p>{pick('First 100 intervals shown.','מוצגים 100 המקטעים הראשונים.')}</p>}
   </details>
   {!log.complete&&<p role="alert">{pick('Partial log. Do not treat this as a complete run.','לוג חלקי. אין להתייחס אליו כריצה מלאה.')} <code>{log.warnings.join(', ')}</code></p>}
   <p>{log.channels.filter(c=>c.unsupported).length} {pick('channels have unsupported structured data; they are listed but not decoded.','ערוצים מכילים נתונים מובנים שאינם נתמכים; הם מוצגים ברשימה אך אינם מפוענחים.')}</p>
   <label>{pick('Find a signal','חיפוש אות')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>
   <div className="robot-log-columns"><div className="robot-log-signals" role="group" aria-label={pick('Channels','ערוצים')}>{visible.map(c=><button key={c.generation} aria-pressed={selected===c.generation} onClick={()=>{setSelected(c.generation);setComponent(0);}}><span dir="ltr">{c.name}</span><small>{c.type} · {c.records}</small></button>)}{!visible.length&&<p>{pick('No matching signals.','לא נמצאו אותות מתאימים.')}</p>}</div>
   <div>{channel?<><h3 dir="ltr">{channel.name}</h3>{channel.components&&<label>{pick("Component","רכיב")}<select value={component} onChange={e=>setComponent(Number(e.target.value))}>{channel.components.map((label,i)=><option key={i} value={i}>{label}</option>)}</select></label>}<p>{pick('Time is seconds in the log clock, not date/time. Units are not inferred.','הזמן הוא בשניות לפי שעון הלוג, לא תאריך ושעה. יחידות אינן מוסקות אוטומטית.')}</p>{stats&&<p dir="ltr">Min {stats.min.toPrecision(5)} · Max {stats.max.toPrecision(5)} · {pick('Sample mean','ממוצע דגימות')} {stats.mean.toPrecision(5)}</p>}{plot&&<><svg viewBox="0 0 800 170" role="img" aria-label={pick('Numeric signal overview, sampled to at most 1000 points','סקירת אות מספרי, עד 1000 נקודות')}><polyline fill="none" stroke="currentColor" strokeWidth="2" points={plot}/></svg><small>{pick('Sampled overview; brief peaks may be omitted. Statistics use all decoded finite samples.','סקירה מדוגמת; שיאים קצרים עלולים לא להופיע. הסטטיסטיקה משתמשת בכל הדגימות המספריות התקינות.')}</small></>}
   <details><summary>{pick('Latest 20 samples','20 הדגימות האחרונות')}</summary><table><thead><tr><th>{pick('Time (s)','זמן (שניות)')}</th><th>{pick('Value','ערך')}</th></tr></thead><tbody>{channel.samples.slice(-20).map((s,i)=><tr key={i}><td>{s.time.toFixed(6)}</td><td dir="auto">{JSON.stringify(s.value).slice(0,500)}</td></tr>)}</tbody></table></details><details><summary>{pick('Source metadata','מטא־נתונים מהמקור')}</summary><pre>{channel.metadata||pick('Not provided','לא סופק')}</pre></details></>:<p>{pick('Select a signal to inspect it.','בחרו אות לבדיקה.')}</p>}</div></div>
   <details><summary>{pick('File identity','זהות הקובץ')}</summary><code className="robot-log-hash">SHA-256: {hash}</code></details>
   {channel&&<RobotLogComparison key={hash} current={log} channel={channel}/>}
   {profile&&<details><summary>{pick('Prepare an existing robot-test workflow','הכנת תהליך בדיקת רובוט קיים')}</summary><p>{pick('Only file identity, time window and your code association are carried into a draft. You must enter the setup, criterion and observed outcome. Saving there shares that record with the team; raw log samples are not copied.','רק זהות הקובץ, חלון הזמן וקישור הקוד שהזנתם יועברו לטיוטה. יש להזין תצורה, קריטריון ותוצאה שנצפתה. שמירה שם משתפת את הרשומה עם הצוות; דגימות הלוג הגולמיות אינן מועתקות.')}</p><label>{pick('Where was this log recorded?','היכן הוקלט הלוג?')}<select value={evidenceKind} onChange={e=>setEvidenceKind(e.target.value as typeof evidenceKind)}><option value="">{pick('Choose explicitly','בחרו במפורש')}</option><option value="physical">{pick('Physical robot','רובוט פיזי')}</option><option value="simulated">{pick('Simulation','סימולציה')}</option></select></label><button disabled={!evidenceKind} onClick={prepareTrial}>{pick('Open test draft for review','פתיחת טיוטת בדיקה לסקירה')}</button></details>}
   {channel&&<details><summary>{pick('Export selected evidence','ייצוא ראיות נבחרות')}</summary><p>{pick('Exports the selected signal, time window and source identity. Nothing is sent to AI or saved as a passed test.','מייצא את האות הנבחר, חלון הזמן וזהות המקור. דבר אינו נשלח לבינה מלאכותית או נשמר כבדיקה שעברה.')}</p><label>{pick('Start (log seconds)','התחלה (שניות לוג)')}<input type="number" step="any" placeholder={String(log.start)} value={windowStart} onChange={e=>setWindowStart(e.target.value)}/></label><label>{pick('End (log seconds)','סוף (שניות לוג)')}<input type="number" step="any" placeholder={String(log.end)} value={windowEnd} onChange={e=>setWindowEnd(e.target.value)}/></label><button onClick={downloadEvidence}>{pick('Download evidence JSON','הורדת JSON ראיות')}</button><a href="/growth?view=robot-tests">{pick('Open existing robot test records','פתיחת רשומות בדיקת רובוט קיימות')}</a></details>}
  </>}
 </section>;
}
