import {useEffect, useRef, useState} from 'react';
import * as THREE from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {loadDarwin} from '../lib/publishedRobot';
import '../styles/robotLearningLab.css';

type Pick=(en:string,he:string)=>string;
type Part={id:number;name:string};
type Commands={select:(id:number)=>void;focus:()=>void;isolate:()=>void;reset:()=>void;explode:(value:number)=>void};
const source='https://github.com/Mechanical-Advantage/RobotCode2026Public/tree/a6239fd90e8de72a7c1870c3c189820fcef6552d/ascope_assets/Robot_Darwin';

/** A separate inspection scene: never mutates the driving/VR scene or robot settings. */
export default function RobotLearningLab({pick}:{pick:Pick}){
 const host=useRef<HTMLDivElement>(null),shell=useRef<HTMLElement>(null),commands=useRef<Commands>();
 const [started,setStarted]=useState(false),[attempt,setAttempt]=useState(0),[parts,setParts]=useState<Part[]>([]),[selected,setSelected]=useState<Part>(),[query,setQuery]=useState(''),[error,setError]=useState(false),[loading,setLoading]=useState(false),[spread,setSpread]=useState(0),[isolated,setIsolated]=useState(false),[expanded,setExpanded]=useState(false),[lesson,setLesson]=useState(0),[note,setNote]=useState('');
 useEffect(()=>{if(!started||!host.current)return;
  const target=host.current,abort=new AbortController();let environment:THREE.WebGLRenderTarget|undefined;let renderer:THREE.WebGLRenderer|undefined,controls:OrbitControls|undefined,observer:ResizeObserver|undefined,root:THREE.Group|undefined,disposed=false;
  const scene=new THREE.Scene();scene.background=new THREE.Color('#edf0f5');
  const camera=new THREE.PerspectiveCamera(42,1,.0005,100);camera.up.set(0,0,1);
  const meshes:THREE.Mesh[]=[],originals=new Map<THREE.Mesh,THREE.Vector3>(),directions=new Map<THREE.Mesh,THREE.Vector3>();let active:THREE.Mesh|undefined,outline:THREE.BoxHelper|undefined;
  const render=()=>{if(!disposed)renderer?.render(scene,camera);};
  const fit=(object:THREE.Object3D)=>{const box=new THREE.Box3().setFromObject(object),center=box.getCenter(new THREE.Vector3()),radius=Math.max(box.getSize(new THREE.Vector3()).length()/2,.004);controls!.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(1.2,-1.7,1.1).normalize().multiplyScalar(radius/Math.sin(Math.atan(Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*Math.min(1,camera.aspect)))*1.2));controls!.update();render();};
  const clearOutline=()=>{if(outline){scene.remove(outline);outline.geometry.dispose();(outline.material as THREE.Material).dispose();outline=undefined;}};
  const highlight=()=>{clearOutline();if(active){outline=new THREE.BoxHelper(active,0xc00083);scene.add(outline);}render();};
  const select=(id:number)=>{active=meshes[id];if(active){if(meshes.some(m=>!m.visible))meshes.forEach(m=>m.visible=m===active);setSelected({id,name:active.name||`Part ${id+1}`});highlight();}};
  let down={x:0,y:0};
  const onDown=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};};
  const onUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5||e.button!==0)return;const rect=target.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObjects(meshes.filter(m=>m.visible),false)[0];if(hit)select(meshes.indexOf(hit.object as THREE.Mesh));};
  const disposeRoot=(object:THREE.Object3D)=>{const materials=new Set<THREE.Material>(),geometries=new Set<THREE.BufferGeometry>(),textures=new Set<THREE.Texture>();object.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);Object.values(m).forEach(v=>{if(v instanceof THREE.Texture)textures.add(v);});}}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());};
  setLoading(true);setError(false);setParts([]);setSelected(undefined);setSpread(0);setIsolated(false);
  try{renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.setAttribute('aria-label','Interactive robot CAD; use the parts list for keyboard selection');target.appendChild(renderer.domElement);const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();environment=pmrem.fromScene(room);scene.environment=environment.texture;room.dispose();pmrem.dispose();
   scene.add(new THREE.HemisphereLight(0xffffff,0x727889,2.7));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(2,-3,5);scene.add(light);
   controls=new OrbitControls(camera,renderer.domElement);controls.minDistance=.006;controls.maxDistance=12;controls.addEventListener('change',render);
   observer=new ResizeObserver(()=>{const {width,height}=target.getBoundingClientRect();if(width&&height){renderer!.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();render();}});observer.observe(target);
   renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onUp);
   void loadDarwin(abort.signal).then(result=>{if(disposed){disposeRoot(result.group);return;}root=result.group;scene.add(root);root.updateMatrixWorld(true);root.traverse(o=>{if(o instanceof THREE.Mesh){meshes.push(o);originals.set(o,o.position.clone());}});
    const center=new THREE.Box3().setFromObject(root).getCenter(new THREE.Vector3());meshes.forEach(m=>{const world=new THREE.Box3().setFromObject(m).getCenter(new THREE.Vector3());const direction=world.sub(center);if(direction.lengthSq()<1e-8)direction.set(0,0,1);direction.normalize().multiplyScalar(.55);const a=m.parent!.worldToLocal(new THREE.Vector3()),b=m.parent!.worldToLocal(direction.clone());directions.set(m,b.sub(a));});
    commands.current={select,focus:()=>{if(active)fit(active);},isolate:()=>{if(active){meshes.forEach(m=>m.visible=m===active);fit(active);setIsolated(true);}},reset:()=>{meshes.forEach(m=>{m.visible=true;m.position.copy(originals.get(m)!);});setSpread(0);setIsolated(false);highlight();fit(root!);},explode:value=>{meshes.forEach(m=>m.position.copy(originals.get(m)!).addScaledVector(directions.get(m)!,value));root!.updateMatrixWorld(true);highlight();}};
    setParts(meshes.map((m,id)=>({id,name:m.name||`Part ${id+1}`})));setLoading(false);fit(root);
   }).catch(()=>{if(!disposed){setLoading(false);setError(true);}});
  }catch{setLoading(false);setError(true);}
  return()=>{disposed=true;abort.abort();commands.current=undefined;observer?.disconnect();controls?.dispose();clearOutline();if(root)disposeRoot(root);renderer?.domElement.removeEventListener('pointerdown',onDown);renderer?.domElement.removeEventListener('pointerup',onUp);environment?.dispose();renderer?.dispose();renderer?.domElement.remove();};
 },[started,attempt]);
 useEffect(()=>{if(!expanded)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setExpanded(false);};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',close);};},[expanded]);
 const lessons=[
  {title:pick('Trace the intake','חקירת האיסוף'),search:'Intake',prompt:pick('Select an intake side plate. Follow the roller supports and locate a fastener. Which parts would you remove to replace a roller? Record what the CAD shows and what still needs a drawing or physical inspection.','בחרו לוח צד של האיסוף. עקבו אחרי תמיכות הגליל ומצאו מחבר. אילו חלקים צריך להסיר כדי להחליף גליל? תעדו מה רואים במודל ומה דורש שרטוט או בדיקה פיזית.')},
  {title:pick('Inspect the launcher','חקירת השיגור'),search:'Hood',prompt:pick('Find the hood plates and carbon tubes. Isolate a part and inspect its mounting holes. Explain how access to the fasteners could affect repair time. The exploded view is a visual separation, not an assembly sequence.','מצאו את לוחות הכוונת וצינורות הקרבון. בודדו חלק ובדקו את חורי ההרכבה. הסבירו כיצד הגישה למחברים משפיעה על זמן התיקון. תצוגת הפירוק היא הפרדה חזותית ולא סדר הרכבה.')},
  {title:pick('Compare design decisions','השוואת החלטות תכנון'),search:'Hopper',prompt:pick('Compare Darwin with the linked 2910 designs. Choose one intake or service-access tradeoff. Cite the team source, describe the change you would try on G3, and define a repeatable test before recommending it.','השוו את Darwin לתכנוני 2910 המקושרים. בחרו פשרה אחת באיסוף או בגישה לתחזוקה. ציינו מקור, תארו שינוי שתרצו לבדוק ב-G3 והגדירו ניסוי חוזר לפני המלצה.')}
 ];
 const filtered=parts.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));
 const download=()=>{const text=`G3 Robot study — 6328 Darwin 2026\nSource: ${source}\nActivity: ${lessons[lesson].title}\nSelected part: ${selected?.name??'None'}\n\n${note}\n\nLearning notes only; not engineering approval.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='g3-robot-study.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section ref={shell} className={`robot-learning-lab${expanded?' is-expanded':''}`} aria-label={pick('Robot learning lab','מעבדת למידה מרובוטים')}>
  <header className="rl-header"><div><span>G3 / {pick('ENGINEERING LAB','מעבדת הנדסה')}</span><h2>{pick('Learn from the real assembly','ללמוד מהמכלול האמיתי')}</h2><p>{pick('Inspect a part. Understand a decision. Propose a test.','חקרו חלק. הבינו החלטה. הציעו ניסוי.')}</p></div><button onClick={()=>setExpanded(!expanded)}>{expanded?pick('Close full screen','סגירת מסך מלא'):pick('Expand workspace','הרחבת סביבת העבודה')}</button></header>
  <div className="rl-layout"><div className="rl-workspace"><div className="rl-toolbar"><strong>6328 · Darwin · 2026</strong><button disabled={!selected} onClick={()=>commands.current?.focus()}>{pick('Zoom to part','התמקדות בחלק')}</button><button disabled={!selected} onClick={()=>commands.current?.isolate()}>{pick('Isolate part','בידוד חלק')}</button><button disabled={!parts.length} onClick={()=>commands.current?.reset()}>{pick('Show whole robot','הצגת הרובוט המלא')}</button></div>
   <div className="rl-viewer" ref={host}>{!started?<div className="rl-overlay"><strong>{pick('Real published CAD, down to individual fasteners','מודל שפורסם על ידי הקבוצה, עד למחברים הבודדים')}</strong><p>{pick('Load the detailed model when you are ready (about 37 MB).','טענו את המודל המפורט כשתהיו מוכנים (כ-37 MB).')}</p><button onClick={()=>setStarted(true)}>{pick('Open Darwin in 3D','פתיחת Darwin בתלת־ממד')}</button></div>:null}{loading?<div className="rl-overlay" role="status">{pick('Loading and verifying the CAD…','טוען ומאמת את המודל…')}</div>:null}{error?<div className="rl-overlay" role="alert"><p>{pick('The 3D model could not load. Check your connection and WebGL support.','לא ניתן לטעון את המודל. בדקו את החיבור ואת התמיכה ב-WebGL.')}</p><button onClick={()=>setAttempt(v=>v+1)}>{pick('Retry','ניסיון נוסף')}</button></div>:null}</div>
   <div className="rl-view-controls"><label>{pick('Separate parts','הפרדת חלקים')}<input aria-label={pick('Visual separation','הפרדה חזותית')} type="range" min="0" max="1" step=".02" value={spread} disabled={!parts.length} onChange={e=>{const v=Number(e.target.value);setSpread(v);commands.current?.explode(v);}}/></label><span>{pick('Drag to orbit · Scroll / pinch to zoom','גרירה לסיבוב · גלילה / צביטה להתקרבות')}{isolated?pick(' · Part isolated',' · חלק מבודד'):''}</span></div>
  </div><aside className="rl-inspector"><h3>{pick('Find a part','מציאת חלק')}</h3><label className="rl-search">{pick('Name in the published CAD','שם במודל המקורי')}<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={pick('Intake, hood, nut…','Intake, hood, nut…')}/></label><small aria-live="polite">{filtered.length} / {parts.length} {pick('mesh parts','חלקי מודל')}</small><div className="rl-parts">{filtered.slice(0,100).map(p=><button key={p.id} aria-pressed={selected?.id===p.id} onClick={()=>commands.current?.select(p.id)}>{p.name}<small>#{p.id+1}</small></button>)}{filtered.length>100?<p>{pick('Refine the search to see more parts.','צמצמו את החיפוש כדי לראות חלקים נוספים.')}</p>:null}</div><p className="rl-selected">{selected?.name??pick('Click the robot or choose a part from the list.','לחצו על הרובוט או בחרו חלק מהרשימה.')}</p><a href={source} target="_blank" rel="noreferrer">{pick('Original CAD & revision','המודל המקורי וגרסתו')} ↗</a><small>{pick('MIT · Mechanical Advantage. Mesh detail is limited to the published export; hidden wiring, tolerances and loads are not validated.','MIT · Mechanical Advantage. רמת הפירוט מוגבלת לייצוא שפורסם; חיווט נסתר, סבולות ועומסים אינם מאומתים.')}</small></aside></div>
  <div className="rl-learning"><section><h3>{pick('Guided exploration','חקירה מודרכת')}</h3><div className="rl-lesson-tabs">{lessons.map((l,i)=><button key={i} aria-pressed={lesson===i} onClick={()=>{setLesson(i);setQuery(l.search);}}>{i+1}. {l.title}</button>)}</div><p>{lessons[lesson].prompt}</p><label>{pick('Your observations — kept only while this workspace is open','התצפיות שלכם — נשמרות רק כל עוד הסביבה פתוחה')}<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={pick('What did you observe? What would you test?','מה ראיתם? מה הייתם בודקים?')}/></label><button disabled={!note.trim()} onClick={download}>{pick('Download study notes','הורדת סיכום הלמידה')}</button><small>{pick('Attach these notes to an existing Academy assignment. This exercise does not award qualification.','צרפו את הסיכום למטלה קיימת באקדמיה. התרגיל אינו מעניק הסמכה.')}</small></section><section><h3>{pick('Compare with another team','השוואה לקבוצה נוספת')}</h3><p>{pick('2910 published two different 2026 robots and explains the redesign. Open the original assemblies to compare intake robustness and service access. These models are not yet imported into this viewer.','2910 פרסמה שני רובוטים שונים ל-2026 והסבר לתכנון המחודש. פתחו את המכלולים המקוריים להשוואת עמידות האיסוף והגישה לתחזוקה. המודלים האלה טרם יובאו לצופה זה.')}</p><a href="https://2910.onshape.com/documents/28894ad47d9c63a665e2a36b/w/078272beb4618ea6cffc78e0/e/aea9a72f86f273a5a9484208" target="_blank" rel="noreferrer">2910 · Blitz ↗</a><a href="https://2910.onshape.com/documents/dfb391aac173a4555d00a5b5/w/3dc64f602735252892b0e47b/e/6c654da4eb6b1710fb0900bd" target="_blank" rel="noreferrer">2910 · Re•Blitz ↗</a><a href="https://www.chiefdelphi.com/t/2910-cad-and-tech-binder-release-2026/521705" target="_blank" rel="noreferrer">{pick('Team explanations & technical binders','הסברי הקבוצה ותיקי ההנדסה')} ↗</a></section></div>
 </section>;
}
