import LogSignalChart from './LogSignalChart';
import {validWindow,windowChannel} from '../lib/logWorkspace';
import {logModes,standardModeChannels} from '../lib/robotLogAnalysis';
import {useEffect,useRef,useState} from 'react';
import {useLocalization} from '../lib/localization';
import {numericLogSummary,type LogChannel,type RobotLog} from '../lib/robotLog';
import {compareLogChannels,logIdentity} from '../lib/robotLogAnalysis';
export default function RobotLogComparison({current,channel,start,end,component=0}:{current:RobotLog;channel:LogChannel;start:number;end:number;component?:number}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[cursor,setCursor]=useState(0);
 const {pick}=useLocalization(),worker=useRef<Worker|null>(null),request=useRef(0);
 const [baseline,setBaseline]=useState<RobotLog|null>(null),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{request.current++;worker.current?.terminate();},[]);
 async function open(file:File){const id=++request.current;worker.current?.terminate();setBaseline(null);setFrom('');setTo('');setError('');setName(file.name);if(file.size>32*1024*1024){setError(pick('Maximum file size: 32 MB.','גודל קובץ מרבי: 32 MB.'));return;}setBusy(true);try{const buffer=await file.arrayBuffer();if(id!==request.current)return;const task=new Worker(new URL('../lib/robotLog.worker.ts',import.meta.url),{type:'module'});worker.current=task;task.onmessage=e=>{if(id!==request.current)return;setBusy(false);task.terminate();if(e.data.error)setError(String(e.data.error));else setBaseline(e.data.log);};task.onerror=()=>{if(id!==request.current)return;setBusy(false);task.terminate();setError(pick('Could not read comparison log.','לא ניתן לקרוא לוג להשוואה.'));};task.postMessage(buffer,[buffer]);}catch{if(id===request.current){setBusy(false);setError(pick('Could not open file.','לא ניתן לפתוח קובץ.'));}}}
 const matches=baseline?.channels.filter(c=>c.name===channel.name)??[],other=matches.length===1?matches[0]:null;
 const bStart=from===''?(baseline?.start??0):Number(from),bEnd=to===''?(baseline?.end??1):Number(to),valid=!!baseline&&validWindow(baseline,bStart,bEnd);
 const ids=baseline?standardModeChannels(baseline):[],find=(i:number)=>baseline?.channels.find(c=>c.generation===ids[i]);
 const modes=baseline&&find(0)&&find(1)?logModes(baseline,find(0)!,find(1)!,find(2)):[];
 const componentsMatch=JSON.stringify(channel.components??[])===JSON.stringify(other?.components??[]);
 const currentChannel=windowChannel(channel,start,end,component),otherChannel=other&&valid&&componentsMatch?windowChannel(other,bStart,bEnd,component):null;
 const comparison=other?compareLogChannels(channel,other):null,a=numericLogSummary(currentChannel),b=otherChannel?numericLogSummary(otherChannel):null;
 const relative=(c:LogChannel,origin:number)=>({...c,samples:c.samples.map(s=>({...s,time:s.time-origin}))});
 const duration=Math.max(end-start,bEnd-bStart);

 const originalIdentity=logIdentity(current),baselineIdentity=baseline?logIdentity(baseline):null;
 return <details><summary>{pick('Compare this signal with another run','השוואת אות זה לריצה אחרת')}</summary><p>{pick('Both files stay local. Select comparable intervals. Plots align their starts at zero; this is not proof of improvement. Robot setup, battery and conditions must still be checked.','שני הקבצים נשארים מקומיים. בחרו מקטעים מתאימים. הגרפים מיושרים לתחילת המקטע, ולא מהווים הוכחה לשיפור. עדיין יש לבדוק תצורת רובוט, סוללה ותנאים.')}</p><input type="file" accept=".wpilog" aria-label={pick('Comparison WPILOG','WPILOG להשוואה')} onChange={e=>{const file=e.target.files?.[0];if(file)void open(file);e.target.value='';}}/>{busy&&<p role="status">{pick('Reading comparison…','קורא השוואה…')}</p>}{error&&<p role="alert">{error}</p>}
 {baseline&&<><div className="log-mode-timeline"><button onClick={()=>{setFrom('');setTo('');}}>{pick('Whole comparison run','כל ריצת ההשוואה')}</button>{modes.map((m,i)=><button key={i} onClick={()=>{setFrom(String(m.start));setTo(String(m.end));setCursor(0);}}>{pick(m.mode,({disabled:'מושבת',autonomous:'אוטונומי',teleop:'נהיגה',test:'בדיקה',unknown:'לא ידוע'})[m.mode])} · {m.start.toFixed(2)}–{m.end.toFixed(2)}</button>)}</div><div className="log-window"><label>{pick('Comparison start (s)','תחילת השוואה (שניות)')}<input type="number" step="any" value={from} placeholder={String(baseline.start)} onChange={e=>setFrom(e.target.value)}/></label><label>{pick('Comparison end (s)','סוף השוואה (שניות)')}<input type="number" step="any" value={to} placeholder={String(baseline.end)} onChange={e=>setTo(e.target.value)}/></label></div>{!valid&&<p role="alert">{pick('Invalid comparison interval','חלון השוואה אינו תקין')}</p>}<p>{pick('Interval durations','משכי המקטעים')}: {(end-start).toFixed(2)} / {(bEnd-bStart).toFixed(2)} s</p>{otherChannel&&<><label>{pick('Elapsed time from interval start','זמן מתחילת המקטע')}<input type="range" min="0" max={duration} step="any" value={cursor} onChange={e=>setCursor(Number(e.target.value))}/></label><LogSignalChart channel={relative(currentChannel,start)} start={0} end={duration} cursor={cursor} onCursor={setCursor} label={pick('Current run','ריצה נוכחית')}/><LogSignalChart channel={relative(otherChannel,bStart)} start={0} end={duration} cursor={cursor} onCursor={setCursor} label={pick('Comparison run','ריצת השוואה')}/></>}<p dir="auto">{name}</p>{!baseline.complete&&<p role="alert">{pick('Comparison log is partial.','לוג ההשוואה חלקי.')}</p>}{!other?<p>{pick('No unique matching signal in this log.','אין אות תואם יחיד בלוג זה.')}</p>:<>{!componentsMatch&&<p role="alert">{pick('Structured components differ. Numeric comparison is unavailable.','הרכיבים המובנים שונים. השוואה מספרית אינה זמינה.')}</p>}{!comparison?.compatible&&<p role="alert">{pick('Compatibility is not established: ','התאימות לא הוכחה: ')}{comparison?.reasons.map(r=>({UNITS_UNKNOWN:pick('units not recorded','יחידות לא תועדו'),UNIT_MISMATCH:pick('different units','יחידות שונות'),TYPE_MISMATCH:pick('different types','סוגים שונים'),SIGNAL_MISMATCH:pick('different signals','אותות שונים')})[r]).join(', ')}</p>}
 <p>{originalIdentity.commit&&baselineIdentity?.commit&&originalIdentity.commit===baselineIdentity.commit?pick('Recorded commit matches; deployment and configuration are not independently verified.','הקומיט המתועד תואם; הפריסה והתצורה לא אומתו באופן עצמאי.'):pick('Code revisions differ or are not recorded.','גרסאות הקוד שונות או לא מתועדות.')}</p>
 {a&&b?<table><thead><tr><th>{pick('Statistic','נתון')}</th><th>{pick('Current log','לוג נוכחי')}</th><th>{pick('Comparison','השוואה')}</th></tr></thead><tbody>{(['count','min','max','mean'] as const).map((key,i)=><tr key={key}><td>{pick(['Samples','Minimum','Maximum','Sample mean'][i],['דגימות','מינימום','מקסימום','ממוצע דגימות'][i])}</td><td>{a[key].toPrecision(6)}</td><td>{b[key].toPrecision(6)}</td></tr>)}</tbody></table>:<p>{pick('Numeric summary is unavailable for this channel type.','סיכום מספרי אינו זמין לסוג ערוץ זה.')}</p>}</>}</>}
 </details>;
}
