import {useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import {comparisonIssues,parseTrialCsv,protocolHelp,protocols,summarizeTrials,validateTrials,type TestRun,type TestSetup,type Trial} from '../lib/robotTests';
import './teamLearning.css';
const blankSetup=():TestSetup=>({robot:'',mechanism:'',codeRevision:null,batteryId:null,batteryVolts:null,conditions:'',procedure:'',criterion:'',units:'seconds/counts/volts'});
const trial=():Trial=>({seconds:0,attempted:1,successful:0,faults:0,passed:false,note:''});
type Task={id:string;project_id:string;title:string;status:string};
export default function RobotTestWorkbench(){
 const {pick}=useLocalization(),[params,setParams]=useSearchParams();
 const [runs,setRuns]=useState<TestRun[]>([]),[tasks,setTasks]=useState<Task[]>([]),[links,setLinks]=useState<{run_id:string;task_id:string}[]>([]);
 const [selected,setSelected]=useState(params.get('run')??''),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[more,setMore]=useState(false);
 const [title,setTitle]=useState(''),[protocol,setProtocol]=useState<TestRun['protocol']>('intake'),[kind,setKind]=useState<TestRun['evidence_kind']>('physical'),[setup,setSetup]=useState(blankSetup),[trials,setTrials]=useState<Trial[]>([trial()]),[baseline,setBaseline]=useState<string|null>(null),[correction,setCorrection]=useState<string|null>(null),[change,setChange]=useState(''),[task,setTask]=useState(''),[csv,setCsv]=useState<Trial[]|null>(null),[compare,setCompare]=useState<TestRun|null>(null);
 const [plans,setPlans]=useState<{id:string;title:string;procedure:string;success_criteria:string}[]>([]),[planId,setPlanId]=useState('');
 const request=useRef(false);
 const setupLabels:Record<string,[string,string]>={robot:['Robot / configuration','רובוט / תצורה'],mechanism:['Mechanism / settings','מנגנון / הגדרות'],codeRevision:['Code revision','גרסת קוד'],batteryId:['Battery ID','מזהה סוללה'],batteryVolts:['Battery voltage (V)','מתח סוללה (וולט)'],conditions:['Conditions','תנאים'],procedure:['Procedure','נוהל'],criterion:['Pass criterion','קריטריון מעבר'],units:['Units','יחידות']};
 useEffect(()=>{const id=params.get('run');if(!id)return;setSelected(id);if(!runs.some(r=>r.id===id)){let live=true;void supabase.from('robot_trial_sessions').select('*').eq('id',id).maybeSingle().then(({data,error})=>{if(!live)return;if(error)setError(error.message);else if(data)setRuns(old=>old.some(r=>r.id===id)?old:[data as TestRun,...old]);});return()=>{live=false;};}},[params.get('run')]);
 useEffect(()=>{if(!editing)return;const guard=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[editing]);
 async function load(append=false){
  setError('');let query=supabase.from('robot_trial_sessions').select('*').order('created_at',{ascending:false}).order('id',{ascending:false}).limit(50);
  if(append&&runs.length){const last=runs[runs.length-1];query=query.or(`created_at.lt.${last.created_at},and(created_at.eq.${last.created_at},id.lt.${last.id})`);}
  const result=await query;if(result.error){setError(result.error.message);return;}
  const data=result.data as TestRun[];setRuns(old=>append?[...old,...data]:data);setMore(data.length===50);
  const [t,l]=await Promise.all([supabase.from('project_tasks').select('id,project_id,title,status').eq('archived',false).order('updated_at',{ascending:false}).limit(200),supabase.from('robot_test_task_links').select('run_id,task_id').in('run_id',data.map(r=>r.id))]);
  if(t.error||l.error)setError((t.error??l.error)!.message);else{setTasks(t.data??[]);setLinks(old=>append?[...old,...l.data??[]]:l.data??[]);}
  if(!append&&params.get('run')&&!data.some(r=>r.id===params.get('run'))){const r=await supabase.from('robot_trial_sessions').select('*').eq('id',params.get('run')).maybeSingle();if(r.error)setError(r.error.message);else if(r.data)setRuns(old=>[r.data as TestRun,...old]);else setError(pick('This test is unavailable.','בדיקה זו אינה זמינה.'));}
 }
 useEffect(()=>{void load();void supabase.from('robot_test_plans').select('id,title,procedure,success_criteria').eq('active',true).order('title').limit(200).then(({data,error})=>{if(error)setError(error.message);else setPlans(data??[]);});},[]);
 const active=runs.find(r=>r.id===selected);
 useEffect(()=>{setCompare(null);if(active?.baseline_id){const existing=runs.find(r=>r.id===active.baseline_id);if(existing)setCompare(existing);else{let live=true;void supabase.from('robot_trial_sessions').select('*').eq('id',active.baseline_id).single().then(({data,error})=>{if(live){if(error)setError(error.message);else setCompare(data as TestRun);}});return()=>{live=false;};}}},[active?.id,runs]);
 function start(source?:TestRun,isCorrection=false){setTitle(source?`${source.title} · ${pick(isCorrection?'correction':'retest',isCorrection?'תיקון רישום':'בדיקה חוזרת')}`:'');setProtocol(source?.protocol??'intake');setKind(source?.evidence_kind??'physical');setSetup(source?{...source.setup}:blankSetup());setTrials(isCorrection&&source?source.trials.map(r=>({...r})):[trial()]);setBaseline(isCorrection?source?.baseline_id??null:source?.id??null);setCorrection(isCorrection?source?.id??null:null);setPlanId(source?.test_plan_id??'');setChange('');setTask(source?.repair_task_id??links.find(l=>l.run_id===source?.id)?.task_id??'');setCsv(null);setError('');setNotice('');setEditing(true);}
 async function save(){
  if(request.current)return;
  const invalid=validateTrials(trials);if(invalid){setError(invalid);return;}
  request.current=true;setBusy(true);setError('');
  const result=await supabase.from('robot_trial_sessions').insert({title:title.trim(),test_plan_id:planId||null,protocol,evidence_kind:kind,setup,trials,baseline_id:baseline,correction_of:correction,change_note:change.trim(),repair_task_id:task||null}).select('*').single();
  request.current=false;setBusy(false);if(result.error){setError(result.error.message);return;}
  setEditing(false);setSelected(result.data.id);setParams({view:'robot-tests',run:result.data.id});setNotice(pick('Saved to shared team history. This record cannot be overwritten.','נשמר בהיסטוריית הקבוצה. לא ניתן לדרוס רשומה זו.'));await load();
 }
 async function linkTask(){if(!active||!task||busy)return;setBusy(true);const r=await supabase.from('robot_test_task_links').insert({run_id:active.id,task_id:task});setBusy(false);if(r.error)setError(r.error.message);else{setLinks(l=>[...l,{run_id:active.id,task_id:task}]);setTask('');}}
 const taskPicker=<label>{pick('Existing repair task','משימת תיקון קיימת')}<select value={task} onChange={e=>setTask(e.target.value)}><option value="">{pick('No task selected','לא נבחרה משימה')}</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title} · {t.status}</option>)}</select><small>{pick('Latest 200 active tasks. Create/manage tasks in Work, then return and refresh.','200 המשימות הפעילות האחרונות. צרו/נהלו משימות בעבודה וחזרו לרענון.')} <Link to="/work">{pick('Open Work','פתיחת עבודה')}</Link></small></label>;
 const stats=(r:TestRun)=>{const s=summarizeTrials(r.trials);return <div className="tl-metrics"><div><b>{s.n}</b><span>{pick('trials','ניסיונות')}</span></div><div><b>{s.passed}/{s.n}</b><span>{pick('passed','עברו')}</span></div><div><b>{s.successRate?.toFixed(1)}%</b><span>{s.successful}/{s.attempted} {pick('successful','הצלחות')}</span></div><div><b>{s.mean?.toFixed(2)} s</b><span>{pick('mean duration','זמן ממוצע')} · SD {s.sd?.toFixed(2)??'—'}</span></div><div><b>{s.perMinute?.toFixed(1)}</b><span>{pick('successes / minute','הצלחות / דקה')}</span></div><div><b>{s.faults}</b><span>{pick('faults','תקלות')} · {s.min}–{s.max} s</span></div></div>;};
 return <section className="tl-workbench"><header className="tl-heading"><div><small>G3 / {pick('MEASURE → IMPROVE → RETEST','מדידה ← שיפור ← בדיקה חוזרת')}</small><h2>{pick('Robot test records','רשומות בדיקת רובוט')}</h2><p>{pick('Record actual trials. Preserve the setup. Show whether a change helped.','תעדו ניסיונות אמיתיים. שמרו תצורה. בדקו אם שינוי עזר.')}</p></div>{!editing&&<button onClick={()=>start()}>{pick('New test','בדיקה חדשה')} +</button>}</header>
 {error&&<p className="tl-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {editing?<form onSubmit={e=>{e.preventDefault();void save();}} className="tl-panel">
 <div className="tl-heading"><h3>{pick('1 · Define the setup','1 · הגדרת תצורה')}</h3><button type="button" className="secondary" onClick={()=>{if(confirm(pick('Discard this unsaved test?','לבטל בדיקה שלא נשמרה?')))setEditing(false);}}>{pick('Cancel','ביטול')}</button></div>
 <p>{pick('Save only after checking all trials. Saving preserves the setup and results together; corrections become separate linked records.','שמרו לאחר בדיקת כל הניסיונות. תצורה ותוצאות נשמרות יחד; תיקונים יישמרו ברשומה מקושרת נפרדת.')}</p>
 <label>{pick('Existing reliability test plan (optional)','תוכנית בדיקת אמינות קיימת (אופציונלי)')}<select value={planId} onChange={e=>{setPlanId(e.target.value);const p=plans.find(p=>p.id===e.target.value);if(p)setSetup(s=>({...s,procedure:p.procedure,criterion:p.success_criteria}));}}><option value="">{pick('Define a standalone measured test','הגדרת בדיקה מדידה עצמאית')}</option>{plans.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><small>{pick('The selected procedure is copied into this immutable setup; later plan edits do not rewrite the test.','הנוהל מועתק לתצורה השמורה; עריכות עתידיות בתוכנית אינן משנות את הבדיקה.')}</small></label><div className="tl-form-grid"><label>{pick('Test name','שם בדיקה')}<input required minLength={3} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{pick('Protocol','נוהל')}<select disabled={!!baseline} value={protocol} onChange={e=>setProtocol(e.target.value as TestRun['protocol'])}>{Object.entries(protocols).map(([k,v])=><option key={k} value={k}>{pick(v[0],v[1])}</option>)}</select></label><label>{pick('Evidence type','סוג ראיה')}<select disabled={!!baseline} value={kind} onChange={e=>setKind(e.target.value as TestRun['evidence_kind'])}><option value="physical">{pick('Physical robot','רובוט פיזי')}</option><option value="simulated">{pick('Simulation only','סימולציה בלבד')}</option></select></label>
 {(['robot','mechanism','codeRevision','batteryId'] as const).map((k,i)=><label key={k}>{pick(['Robot / configuration ID','Mechanism / settings','Code revision (optional)','Battery ID (optional)'][i],['מזהה רובוט / תצורה','מנגנון / הגדרות','גרסת קוד (אופציונלי)','מזהה סוללה (אופציונלי)'][i])}<input required={i<2} maxLength={200} value={setup[k]??''} onChange={e=>setSetup(s=>({...s,[k]:e.target.value||null}))}/></label>)}
 <label>{pick('Battery before test (V, optional)','סוללה לפני בדיקה (וולט, אופציונלי)')}<input type="number" step="0.01" min="0" max="16" value={setup.batteryVolts??''} onChange={e=>setSetup(s=>({...s,batteryVolts:e.target.value===''?null:Number(e.target.value)}))}/></label>
 {(['conditions','procedure','criterion'] as const).map((k,i)=><label className="tl-wide" key={k}>{pick(['Conditions: surface, distance, pieces, temperature if relevant','Repeatable procedure and settings','Pass definition agreed before testing'][i],['תנאים: משטח, מרחק, חלקים, טמפרטורה אם רלוונטי','נוהל חוזר והגדרות','הגדרת מעבר שסוכמה לפני הבדיקה'][i])}<textarea required maxLength={2000} value={setup[k]} onChange={e=>setSetup(s=>({...s,[k]:e.target.value}))}/></label>)}
 </div><p className="tl-callout">{pick(protocolHelp[protocol][0],protocolHelp[protocol][1])}</p>
 <h3>{pick('2 · Record every trial','2 · תיעוד כל ניסיון')}</h3><p>{pick('Counts are whole numbers; durations are seconds. Pass/fail uses your stated criterion, not an automatic safety approval. Include failed trials.','הספירות הן מספרים שלמים והזמנים בשניות. מעבר/כישלון לפי הקריטריון שהגדרתם, ולא אישור בטיחות אוטומטי. כללו ניסיונות שנכשלו.')}</p>
 <div className="tl-trials">{trials.map((r,i)=><fieldset key={i}><legend>{pick('Trial','ניסיון')} {i+1}</legend><div className="tl-form-grid">{(['seconds','attempted','successful','faults'] as const).map((k,j)=><label key={k}>{pick(['Seconds','Attempted','Successful','Faults / jams'][j],['שניות','ניסיונות','הצלחות','תקלות / תקיעות'][j])}<input required type="number" min={j<2?j===0?0.001:1:0} max="100000" step={j===0?'any':1} value={r[k]} onChange={e=>setTrials(old=>old.map((v,n)=>n===i?{...v,[k]:Number(e.target.value)}:v))}/></label>)}<label>{pick('Outcome','תוצאה')}<select value={String(r.passed)} onChange={e=>setTrials(old=>old.map((v,n)=>n===i?{...v,passed:e.target.value==='true'}:v))}><option value="false">{pick('Failed criterion','לא עמד בקריטריון')}</option><option value="true">{pick('Passed criterion','עמד בקריטריון')}</option></select></label><label>{pick('Observation','תצפית')}<input maxLength={2000} value={r.note} onChange={e=>setTrials(old=>old.map((v,n)=>n===i?{...v,note:e.target.value}:v))}/></label></div><button type="button" className="secondary" disabled={trials.length===1} onClick={()=>setTrials(old=>old.filter((_,n)=>n!==i))}>{pick('Remove unsaved trial','הסרת ניסיון שלא נשמר')}</button></fieldset>)}</div>
 <div className="tl-actions"><button type="button" disabled={trials.length>=200} onClick={()=>setTrials(old=>[...old,trial()])}>+ {pick('Add trial','הוספת ניסיון')}</button><label className="tl-file">{pick('Import CSV','ייבוא CSV')}<input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{setCsv(parseTrialCsv(await f.text()));setError('');}catch(err){setCsv(null);setError(String(err));}e.target.value='';}}/></label></div><details><summary>{pick('CSV format','מבנה CSV')}</summary><pre dir="ltr">seconds,attempted,successful,faults,passed,note{'\n'}12.5,5,4,1,false,"jam on piece 3"</pre></details>
 {csv&&<aside className="tl-callout"><b>{csv.length} {pick('validated rows ready to append','שורות תקינות מוכנות להוספה')}</b><p>{pick('Import does not save to the database. Review the appended trials before saving.','ייבוא אינו שומר למסד הנתונים. בדקו ניסיונות לפני שמירה.')}</p><button type="button" disabled={csv.length+(trials.length===1&&trials[0].seconds===0?0:trials.length)>200} onClick={()=>{setTrials(old=>old.length===1&&old[0].seconds===0?csv:[...old,...csv]);setCsv(null);}}>{pick('Apply import','החלת ייבוא')}</button><button type="button" className="secondary" onClick={()=>setCsv(null)}>{pick('Discard import','ביטול ייבוא')}</button></aside>}
 <h3>{pick('3 · Link the change and save','3 · קישור שינוי ושמירה')}</h3>{(baseline||correction)&&<p>{pick('Linked original','רשומה מקורית מקושרת')}: {baseline??correction}</p>}<label>{pick('What changed? / correction reason','מה השתנה? / סיבת תיקון')}<textarea required={!!baseline||!!correction} minLength={baseline||correction?5:0} maxLength={4000} value={change} onChange={e=>setChange(e.target.value)}/></label>{taskPicker}<button disabled={busy}>{busy?pick('Saving…','שומר…'):pick('Save shared test record','שמירת רשומת בדיקה משותפת')}</button>
 </form>:<div className="tl-split"><aside className="tl-history"><button className="secondary" onClick={()=>void load()}>{pick('Refresh history','רענון היסטוריה')}</button>{runs.length===0&&!error&&<p>{pick('No shared tests yet. Start with five repeatable trials of one mechanism.','אין עדיין בדיקות משותפות. התחילו מחמישה ניסיונות חוזרים למנגנון אחד.')}</p>}{runs.map(r=><button key={r.id} aria-pressed={selected===r.id} onClick={()=>{setSelected(r.id);setTask('');setParams({view:'robot-tests',run:r.id});}}><strong>{r.title}</strong><small>{pick(protocols[r.protocol][0],protocols[r.protocol][1])} · {r.evidence_kind==='physical'?pick('Physical','פיזי'):pick('Simulated','מדומה')} · {new Date(r.created_at).toLocaleDateString()}</small></button>)}{more&&<button onClick={()=>void load(true)}>{pick('Load older tests','טעינת בדיקות ישנות')}</button>}</aside>
 <article className="tl-panel">{active?<><div className="tl-heading"><div><small>{active.evidence_kind==='physical'?pick('PHYSICAL OBSERVATIONS','תצפיות פיזיות'):pick('SIMULATION — NOT PHYSICAL VALIDATION','סימולציה — לא אימות פיזי')}</small><h3>{active.title}</h3></div><button onClick={()=>start(active)}>{pick('Retest this setup','בדיקה חוזרת לתצורה')}</button></div>{stats(active)}<p>{pick('Descriptive results only. Small samples and changed conditions limit conclusions; completing a task does not validate a repair.','תוצאות תיאוריות בלבד. מדגם קטן ותנאים שהשתנו מגבילים מסקנות; סגירת משימה אינה מאמתת תיקון.')}</p>
 {active.test_plan_id&&<p><Link to={`/robot-reliability?plan=${active.test_plan_id}`}>{pick('Open original reliability plan','פתיחת תוכנית האמינות המקורית')} ↗</Link></p>}<details open><summary>{pick('Preserved setup','תצורה שמורה')}</summary><dl className="tl-setup">{Object.entries(active.setup).map(([k,v])=><div key={k}><dt>{setupLabels[k]?pick(...setupLabels[k]):k}</dt><dd>{v??pick('Unknown','לא ידוע')}</dd></div>)}</dl></details>
 {active.change_note&&<p><b>{pick('Change / correction','שינוי / תיקון')}: </b>{active.change_note}</p>}{active.correction_of&&<p>{pick('Corrects record','מתקן רשומה')}: <button className="secondary" onClick={()=>{setSelected(active.correction_of!);setParams({view:'robot-tests',run:active.correction_of!});void load();}}>{active.correction_of}</button></p>}
 {compare&&<section><h3>{pick('Compared with baseline','השוואה לבסיס')}: {compare.title}</h3>{stats(compare)}<p>{pick('After − before','אחרי פחות לפני')}: {((summarizeTrials(active.trials).successRate??0)-(summarizeTrials(compare.trials).successRate??0)).toFixed(1)} {pick('percentage points success','נקודות אחוז הצלחה')} · {((summarizeTrials(active.trials).mean??0)-(summarizeTrials(compare.trials).mean??0)).toFixed(2)} s {pick('mean duration','זמן ממוצע')}. {pick('Observed difference, not proof that the change caused it.','הבדל שנצפה, לא הוכחה שהשינוי גרם לו.')}</p>{comparisonIssues(active,compare).length>0?<p className="tl-callout">{pick('Not an equivalent-condition comparison. Review these differences/unknowns:','זו אינה השוואה בתנאים שווים. בדקו הבדלים/חוסרים אלה:')} {comparisonIssues(active,compare).join(', ')}</p>:<p>{pick('Protocol and recorded conditions match. Review the changed factor before interpreting the difference.','הנוהל והתנאים המתועדים תואמים. בדקו את הגורם ששונה לפני פירוש ההבדל.')}</p>}<p>{pick('Battery / code before → after','סוללה / קוד לפני ← אחרי')}: {compare.setup.batteryId??'?'} / {compare.setup.batteryVolts??'?'} V / {compare.setup.codeRevision??'?'} → {active.setup.batteryId??'?'} / {active.setup.batteryVolts??'?'} V / {active.setup.codeRevision??'?'}</p></section>}
 <details><summary>{pick('All recorded trials','כל הניסיונות המתועדים')} ({active.trials.length})</summary><div className="tl-table-scroll"><table><thead><tr>{['#','s',pick('Attempted','ניסיונות'),pick('Success','הצלחה'),pick('Faults','תקלות'),pick('Passed','עבר'),pick('Note','הערה')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{active.trials.map((r,i)=><tr key={i}><td>{i+1}</td><td>{r.seconds}</td><td>{r.attempted}</td><td>{r.successful}</td><td>{r.faults}</td><td>{r.passed?'✓':'✕'}</td><td>{r.note}</td></tr>)}</tbody></table></div></details>
 <h3>{pick('Repair → retest','תיקון ← בדיקה חוזרת')}</h3>{[...new Set([active.repair_task_id,...links.filter(l=>l.run_id===active.id).map(l=>l.task_id)].filter(Boolean))].map(id=>{const t=tasks.find(t=>t.id===id);return <p key={id}><Link to={`/projects?task=${id}${t?`&project=${t.project_id}`:''}`}>{t?.title??id} ↗</Link> · {t?.status??pick('Open task for status','פתחו משימה להצגת מצב')}</p>;})}{taskPicker}<button disabled={!task||busy} onClick={()=>void linkTask()}>{pick('Link task to this record','קישור משימה לרשומה')}</button><div className="tl-actions"><button className="secondary" onClick={()=>start(active,true)}>{pick('Append a correction','הוספת תיקון רישום')}</button><button className="secondary" onClick={()=>void navigator.clipboard.writeText(`${location.origin}/growth?view=robot-tests&run=${active.id}`).then(()=>setNotice(pick('Evidence link copied.','קישור ראיה הועתק.'))).catch(()=>setError(pick('Could not copy. Copy the URL from the address bar.','לא ניתן להעתיק. העתיקו את הכתובת משורת הכתובת.')))}>{pick('Copy evidence link','העתקת קישור ראיה')}</button></div></>:<p>{pick('Choose a test to inspect its setup, trials and repair history.','בחרו בדיקה להצגת תצורה, ניסיונות והיסטוריית תיקונים.')}</p>}</article></div>}
 </section>;
}
