import {readSoftwareContext} from '../lib/softwareWorkingContext';
import {useNavigate} from 'react-router-dom';
import LogSignalChart from './LogSignalChart';
import {readWorkspace,readWorkspaceDescriptor,retainWorkspace,validWindow,windowChannel,signalSummary,type SignalChoice} from '../lib/logWorkspace';
import {useEffect,useRef,useState} from 'react';
import {useLocalization} from '../lib/localization';
import {numericLogSummary,type RobotLog} from '../lib/robotLog';
import {boundedLogEvidence,logIdentity,logModes,standardModeChannels} from '../lib/robotLogAnalysis';
import {robotPurposes} from '../lib/robotRepositories';
import {supabase} from '../supabase';
import RobotLogComparison from './RobotLogComparison';
import {useMemberAuth} from '../lib/memberAuth';
import {logTrialDraftKey,parseLogTrialDraft} from '../lib/robotLogTrialDraft';
import '../styles/robotLog.css';
import {logAssistDraft,logAssistKey} from '../lib/robotLogAssist';

export default function RobotLogInspector(){const {profile}=useMemberAuth();return <LogInspector key={profile?.id??'signed-out'}/>;}
function LogInspector(){
 const {pick}=useLocalization(),worker=useRef<Worker|null>(null),ticket=useRef(0);
 const {profile}=useMemberAuth(),navigate=useNavigate();
 const [related,setRelated]=useState<SignalChoice[]>([]),[cursor,setCursor]=useState(0),[restored,setRestored]=useState(false);
 useEffect(()=>{if(!profile)return;const saved=readWorkspace(profile.id);if(saved){setLog(saved.log);setName(saved.name);setHash(saved.hash);setRepository(saved.repository);setCommit(saved.commit);setSelected(saved.selected);setComponent(saved.component);setModeIds(saved.modeIds);setWindowStart(saved.windowStart);setWindowEnd(saved.windowEnd);setRelated(saved.related);}setRestored(true);},[profile?.id]);
 const [evidenceKind,setEvidenceKind]=useState<''|'physical'|'simulated'>('');
 const [component,setComponent]=useState(0),[group,setGroup]=useState('');
 const [log,setLog]=useState<RobotLog|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState(''),[hash,setHash]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(-1);
 const [repository,setRepository]=useState(''),[commit,setCommit]=useState(''),[checked,setChecked]=useState(''),[checking,setChecking]=useState(false),[modeIds,setModeIds]=useState([-1,-1,-1]),[windowStart,setWindowStart]=useState(''),[windowEnd,setWindowEnd]=useState('');
 useEffect(()=>()=>{ticket.current++;worker.current?.terminate();},[]);
 async function open(file:File){
  const request=++ticket.current;worker.current?.terminate();setLog(null);setSelected(-1);setHash('');setError('');setName(file.name);setBusy(true);setRepository('');setCommit('');setChecked('');setChecking(false);setModeIds([-1,-1,-1]);setWindowStart('');setWindowEnd('');setEvidenceKind('');setComponent(0);setRelated([]);setGroup('');
  if(file.size>32*1024*1024){setError(pick('Choose a WPILOG file up to 32 MB.','בחרו קובץ WPILOG עד 32 MB.'));setBusy(false);return;}
  try{
   const buffer=await file.arrayBuffer();if(request!==ticket.current)return;
   const digest=await crypto.subtle.digest('SHA-256',buffer);if(request!==ticket.current)return;
   const fileHash=Array.from(new Uint8Array(digest),n=>n.toString(16).padStart(2,'0')).join('');setHash(fileHash);
   const task=new Worker(new URL('../lib/robotLog.worker.ts',import.meta.url),{type:'module'});worker.current=task;
   task.onmessage=e=>{if(request!==ticket.current)return;setBusy(false);task.terminate();if(e.data.error)setError(pick('This file could not be read: ','לא ניתן לקרוא את הקובץ: ')+e.data.error);else {setLog(e.data.log);setModeIds(standardModeChannels(e.data.log));const saved=profile?readWorkspaceDescriptor(profile.id):null;if(saved?.hash===fileHash){setSelected(saved.selected);setComponent(saved.component);setRepository(saved.repository);setCommit(saved.commit);setWindowStart(saved.windowStart);setWindowEnd(saved.windowEnd);setRelated(saved.related);setModeIds(saved.modeIds);}else if(saved){setError(pick('Different file: previous selections were not applied.','קובץ שונה: הבחירות הקודמות לא הוחלו.'));}}};
   task.onerror=()=>{if(request!==ticket.current)return;setBusy(false);task.terminate();setError(pick('Log reader failed. Try a smaller file.','קריאת הלוג נכשלה. נסו קובץ קטן יותר.'));};
   task.postMessage(buffer,[buffer]);
  }catch{if(request===ticket.current){setBusy(false);setError(pick('Could not open this file.','לא ניתן לפתוח את הקובץ.'));}}
 }
 const channel=log?.channels.find(c=>c.generation===selected);
 const start=windowStart===''?(log?.start??0):Number(windowStart),end=windowEnd===''?(log?.end??1):Number(windowEnd),windowValid=!!log&&validWindow(log,start,end);
 const plotted=channel&&windowValid?windowChannel(channel,start,end,component):null;
 useEffect(()=>{setCursor(start);},[start,end]);
 useEffect(()=>{if(profile&&log&&restored)retainWorkspace(profile.id,{log,name,hash,repository,commit,selected,component,modeIds,windowStart,windowEnd,related});},[profile?.id,log,name,hash,repository,commit,selected,component,modeIds,windowStart,windowEnd,related,restored]);
 const working=profile?readSoftwareContext(profile.id):null;
 const identity=log?logIdentity(log):null;
 const modes=log&&modeIds[0]>=0&&modeIds[1]>=0?logModes(log,log.channels.find(c=>c.generation===modeIds[0])!,log.channels.find(c=>c.generation===modeIds[1])!,log.channels.find(c=>c.generation===modeIds[2])):[];
 async function checkCommit(){const request=ticket.current;setChecking(true);setChecked('');setError('');try{const r=await supabase.functions.invoke('github-repositories',{body:{action:'check-commit',repository,commit:commit.trim().toLowerCase()}});if(request!==ticket.current)return;if(r.error||r.data?.error||r.data?.revision!==commit.trim().toLowerCase())throw Error();setChecked(repository+'@'+commit.trim().toLowerCase());}catch{if(request===ticket.current)setError(pick('Commit could not be verified. Check access and the full SHA.','לא ניתן לאמת את הקומיט. בדקו הרשאות ו-SHA מלא.'));}finally{if(request===ticket.current)setChecking(false);}}
 function downloadEvidence(){if(!log||!channel)return;try{const start=windowStart===''?log.start:Number(windowStart),end=windowEnd===''?log.end:Number(windowEnd);const evidenceChannel=channel.components?windowChannel(channel,log.start,log.end,component):channel;const evidenceLog={...log,channels:log.channels.map(c=>c===channel?evidenceChannel:c)};const evidence=boundedLogEvidence(evidenceLog,evidenceChannel,start,end);const report={schema:1,file:{name,sha256:hash},identity,association:{repository,commit,commitExists:checked===repository+'@'+commit.trim().toLowerCase(),deploymentVerified:false},evidence};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='g3-log-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError(pick('Choose a valid, smaller time window for the evidence export.','בחרו חלון זמן תקין וקטן יותר לייצוא ראיות.'));}}
 function prepareTrial(){if(!profile||!log||!evidenceKind)return;try{const key=logTrialDraftKey(profile.id);if(sessionStorage.getItem(key)){setError(pick('A log test draft already exists. Open robot test records to review it first.','כבר קיימת טיוטת בדיקה מלוג. פתחו רשומות בדיקת רובוט כדי לסקור אותה תחילה.'));return;}const start=windowStart===''?log.start:Number(windowStart),end=windowEnd===''?log.end:Number(windowEnd);if(start<log.start||end>log.end)throw Error();const draft=parseLogTrialDraft({schema:1,fileSha256:hash,start,end,repository,commit:commit.trim().toLowerCase(),kind:evidenceKind,partial:!log.complete,signals:[...(channel?[signalSummary(channel,start,end,component)]:[]),...related.filter(r=>r.generation!==selected||r.component!==component).map(r=>{const c=log.channels.find(c=>c.generation===r.generation);return c?signalSummary(c,start,end,r.component):null;}).filter(Boolean)]});sessionStorage.setItem(key,JSON.stringify(draft));navigate('/engineering?view=tests&logDraft=1');}catch{setError(pick('Could not prepare draft. Check the time window and commit, or export evidence instead.','לא ניתן להכין טיוטה. בדקו חלון זמן וקומיט, או ייצאו ראיות במקום זאת.'));}}
 const visible=log?.channels.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())&&(!group||c.name.split('/').filter(Boolean)[0]===group))??[];
 function prepareAssist(){if(!profile||!log||!channel)return;try{const key=logAssistKey(profile.id);if(sessionStorage.getItem(key))throw Error('DRAFT_EXISTS');const evidenceChannel=channel.components?windowChannel(channel,log.start,log.end,component):channel;const evidenceLog={...log,channels:log.channels.map(c=>c===channel?evidenceChannel:c)};const prompt=logAssistDraft(evidenceLog,evidenceChannel,hash,windowStart===''?log.start:Number(windowStart),windowEnd===''?log.end:Number(windowEnd),repository,commit.trim());sessionStorage.setItem(key,JSON.stringify({schema:1,prompt}));navigate('/assistant?logDraft=1'+(checked&&repository&&commit?'&robotRepository='+encodeURIComponent(repository)+'&robotRevision='+encodeURIComponent(commit.trim()):''));}catch{setError(pick('Could not prepare AI draft. Choose a numeric signal and smaller window, or finish the existing log draft in G3 Assist.','לא ניתן להכין טיוטה. בחרו אות מספרי וחלון קטן יותר, או השלימו את הטיוטה הקיימת ב-G3 Assist.'));}}
 return <section className="robot-log" aria-label={pick('Robot log inspection','בדיקת לוג רובוט')}>
  <header><div><h2>{pick('Inspect a robot log','בדיקת לוג רובוט')}</h2><p>{pick('Open a run → choose a period → inspect signals → follow up.','פתיחת ריצה ← בחירת מקטע ← בדיקת אותות ← המשך טיפול')}</p></div><label className="hub-button">{pick('Open WPILOG','פתיחת WPILOG')}<input aria-label={pick('Choose WPILOG file','בחירת קובץ WPILOG')} type="file" accept=".wpilog" onChange={e=>{const file=e.target.files?.[0];if(file)void open(file);e.target.value='';}}/></label></header>
  <p>{pick('Local inspection: this file stays on this device. Nothing is uploaded, saved to team history or sent to AI.','בדיקה מקומית: הקובץ נשאר במכשיר. דבר אינו מועלה, נשמר בהיסטוריית הצוות או נשלח לבינה מלאכותית.')}</p>
  {busy&&<p role="status">{pick('Reading log…','קורא לוג…')} <button onClick={()=>{ticket.current++;worker.current?.terminate();setBusy(false);setName('');setHash('');}}>{pick('Cancel','ביטול')}</button></p>}
  {error&&<p role="alert">{error}</p>}
  {!log&&!busy&&<div className="log-empty"><h3>{pick('What happened during the run?','מה קרה במהלך הריצה?')}</h3><p>{pick('Open a WPILOG file (up to 32 MB). Operating modes and signals appear here. No repository selection is required.','פתחו קובץ WPILOG עד 32 MB. מצבי הפעולה והאותות יוצגו כאן. אין חובה לבחור מאגר.')}</p>{profile&&readWorkspaceDescriptor(profile.id)&&<p>{pick('Reopen the previous file to restore your selections. Its fingerprint must match.','פתחו שוב את הקובץ הקודם לשחזור הבחירות. טביעת האצבע חייבת להתאים.')}</p>}</div>}
  {log&&<><h3 dir="auto">{name}</h3><p>{log.records.toLocaleString()} {pick('records','רשומות')} · {log.channels.length} {pick('channels','ערוצים')} · {(log.end-log.start).toFixed(2)} {pick('seconds','שניות')}</p>
   <p><strong>{pick('Code revision: not verified','גרסת קוד: לא אומתה')}</strong> — {pick('A filename or project label does not prove which code was running.','שם קובץ או תווית פרויקט אינם מוכיחים איזה קוד פעל.')}</p>
   <details><summary>{pick('Code identity & comparison revision','זהות קוד וגרסה להשוואה')}</summary>
    <p dir="auto">{pick('Recorded project','פרויקט שתועד')}: {identity?.project??pick('Not recorded','לא תועד')} · {pick('Recorded commit','קומיט שתועד')}: {identity?.commit??pick('Not recorded','לא תועד')}</p>
    <p>{identity?.dirty===true?pick('Log reports uncommitted source changes.','הלוג מדווח על שינויי מקור שלא נשמרו בקומיט.'):identity?.dirty===false?pick('Log reports a clean source tree; this is metadata, not independent deployment proof.','הלוג מדווח על עץ מקור נקי; אלו מטא־נתונים ולא הוכחה עצמאית לפריסה.'):pick('Source modification status is unknown.','מצב שינויי המקור אינו ידוע.')}</p>
    {identity?.conflicts&&<p role="alert">{pick('Conflicting source metadata. Resolve before associating results.','מטא־נתוני מקור סותרים. יש לברר לפני קישור תוצאות.')}</p>}
    <details><summary>{pick('All recorded metadata channels','כל ערוצי המטא־נתונים שתועדו')}</summary>{log.channels.filter(c=>/^\/(RealMetadata|Metadata)\//.test(c.name)).map(c=><p key={c.generation} dir="auto"><code>{c.name}</code>: {JSON.stringify(c.samples[c.samples.length-1]?.value??null).slice(0,1000)}</p>)}</details>
    {working&&<button onClick={()=>{setRepository(working.repository);setCommit(working.revision);setChecked('');}}>{pick('Compare with pinned working revision','השוואה לגרסת העבודה המקובעת')} · {working.revision.slice(0,8)}</button>}
    <label>{pick('Repository to compare','מאגר להשוואה')}<select disabled={checking} value={repository} onChange={e=>{setRepository(e.target.value);setChecked('');}}><option value="">{pick('Choose repository','בחירת מאגר')}</option>{Object.keys(robotPurposes).map(r=><option key={r} value={'GlueGunAndGlitter/'+r}>{r}</option>)}</select></label>
    <label>{pick('Full commit SHA','SHA מלא של קומיט')}<input disabled={checking} dir="ltr" value={commit} maxLength={40} onChange={e=>{setCommit(e.target.value);setChecked('');}}/></label><button disabled={checking||!repository||!/^[a-f0-9]{40}$/i.test(commit.trim())} onClick={()=>void checkCommit()}>{checking?pick('Checking…','בודק…'):pick('Check repository commit','בדיקת קומיט במאגר')}</button>
    {checked&&<p role="status">{pick('Commit exists and is accessible. This does not prove it produced this log.','הקומיט קיים ונגיש. אין בכך הוכחה שהוא יצר את הלוג.')}</p>}
    {identity?.commit&&commit.trim()&&identity.commit!==commit.trim().toLowerCase()&&<p role="alert">{pick('Selected commit differs from the recorded log commit.','הקומיט שנבחר שונה מהקומיט שתועד בלוג.')}</p>}
   </details>
   {!log.complete&&<p role="alert">{pick('Partial log. Do not treat this as a complete run.','לוג חלקי. אין להתייחס אליו כריצה מלאה.')} <code>{log.warnings.join(', ')}</code></p>}
   <p>{log.channels.filter(c=>c.unsupported).length} {pick('channels have unsupported structured data; they are listed but not decoded.','ערוצים מכילים נתונים מובנים שאינם נתמכים; הם מוצגים ברשימה אך אינם מפוענחים.')}</p>
<section className="log-overview"><h3>{pick('1 · Choose the analysis interval','1 · בחירת חלון הניתוח')}</h3><p>{pick('Modes are recorded robot states, not controls for operating the robot.','המצבים הם תיעוד של הרובוט, לא פקדים להפעלתו.')}</p><div className="log-mode-timeline"><button onClick={()=>{setWindowStart('');setWindowEnd('');}}>{pick('Whole run','כל הריצה')}</button>{modes.map((m,i)=><button key={i} aria-pressed={start===m.start&&end===m.end} onClick={()=>{setWindowStart(String(m.start));setWindowEnd(String(m.end));}}>{pick(m.mode,({disabled:'מושבת',autonomous:'אוטונומי',teleop:'נהיגה',test:'בדיקה',unknown:'לא ידוע'})[m.mode])}<small>{m.start.toFixed(2)}–{m.end.toFixed(2)} s</small></button>)}</div>{!modes.length&&<p>{pick('Operating modes unavailable. Map recorded DriverStation signals below; no mode is assumed.','מצבי פעולה אינם זמינים. מפו אותות DriverStation למטה; לא מניחים מצב אוטומטית.')}</p>}<div className="log-window"><label>{pick('Start (log seconds)','התחלה (שניות לוג)')}<input type="number" step="any" value={windowStart} placeholder={String(log.start)} onChange={e=>setWindowStart(e.target.value)}/></label><label>{pick('End (log seconds)','סוף (שניות לוג)')}<input type="number" step="any" value={windowEnd} placeholder={String(log.end)} onChange={e=>setWindowEnd(e.target.value)}/></label></div>{!windowValid?<p role="alert">{pick('Choose an interval inside this log, with end after start.','בחרו חלון בתוך הלוג עם סוף לאחר ההתחלה.')}</p>:<p role="status">{pick('All charts, statistics and evidence use','כל הגרפים, הנתונים והראיות משתמשים בחלון')} <b>{start.toFixed(3)}–{end.toFixed(3)} s</b></p>}<details><summary>{pick('Advanced · operating-mode signal mapping','מתקדם · מיפוי אותות מצבי פעולה')}</summary>    {(['Enabled','Autonomous','Test'] as const).map((label,index)=><label key={label}>{pick(label+' channel',['ערוץ הפעלה','ערוץ אוטונומי','ערוץ בדיקה'][index])}<select value={modeIds[index]} onChange={e=>setModeIds(old=>old.map((n,i)=>i===index?Number(e.target.value):n))}><option value={-1}>{pick('Not mapped','לא מופה')}</option>{log.channels.filter(c=>c.type==='boolean'&&!modeIds.some((n,i)=>i!==index&&n===c.generation)).map(c=><option key={c.generation} value={c.generation}>{c.name}</option>)}</select></label>)}
</details></section>
   <h3>{pick('2 · Inspect related signals','2 · בדיקת אותות קשורים')}</h3><label>{pick('Signal group (from logged path)','קבוצת אותות (לפי נתיב הלוג)')}<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">{pick('All groups','כל הקבוצות')}</option>{[...new Set(log.channels.map(c=>c.name.split('/').filter(Boolean)[0]))].sort().map(g=><option key={g} value={g}>{g}</option>)}</select></label><label>{pick('Find a signal','חיפוש אות')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>
   <div className="robot-log-columns"><div className="robot-log-signals" role="group" aria-label={pick('Channels','ערוצים')}>{visible.map(c=><button key={c.generation} aria-pressed={selected===c.generation} onClick={()=>{setSelected(c.generation);setComponent(0);}}><span dir="ltr">{c.name}</span><small>{c.type} · {c.records}</small></button>)}{!visible.length&&<p>{pick('No matching signals.','לא נמצאו אותות מתאימים.')}</p>}</div>
   <div>{channel?<><h3 dir="ltr">{channel.name}</h3>{channel.components&&<label>{pick("Component","רכיב")}<select value={component} onChange={e=>setComponent(Number(e.target.value))}>{channel.components.map((label,i)=><option key={i} value={i}>{label}</option>)}</select></label>}{plotted&&<LogSignalChart channel={plotted} start={start} end={end} cursor={cursor} onCursor={setCursor} label={channel.name+(channel.components?' · '+channel.components[component]:'')}/>}<button disabled={!plotted||related.length>=3||related.some(r=>r.generation===selected&&r.component===component)} onClick={()=>setRelated(v=>[...v,{generation:selected,component}])}>{pick('Pin signal for comparison (up to 3)','הצמדת אות להשוואה (עד 3)')}</button>
   <details><summary>{pick('Latest 20 samples','20 הדגימות האחרונות')}</summary><table><thead><tr><th>{pick('Time (s)','זמן (שניות)')}</th><th>{pick('Value','ערך')}</th></tr></thead><tbody>{(plotted?.samples??[]).slice(-20).map((s,i)=><tr key={i}><td>{s.time.toFixed(6)}</td><td dir="auto">{JSON.stringify(s.value).slice(0,500)}</td></tr>)}</tbody></table></details><details><summary>{pick('Source metadata','מטא־נתונים מהמקור')}</summary><pre>{channel.metadata||pick('Not provided','לא סופק')}</pre></details></>:<p>{pick('Select a signal to inspect it.','בחרו אות לבדיקה.')}</p>}</div></div>
   {windowValid&&<><label>{pick('Shared cursor (log seconds)','סמן משותף (שניות לוג)')}<input type="range" min={start} max={end} step="any" value={cursor} onChange={e=>setCursor(Number(e.target.value))}/><output>{cursor.toFixed(3)} s</output></label><small>{pick('Charts are sampled; statistics use every finite sample in the interval. Each trace has its own vertical scale.','הגרפים מדוגמים; הסטטיסטיקה כוללת כל דגימה תקינה בחלון. לכל אות סולם אנכי נפרד.')}</small>{related.map((r,i)=>{const c=log.channels.find(c=>c.generation===r.generation);return c?<div key={i}><button onClick={()=>setRelated(v=>v.filter((_,n)=>n!==i))}>{pick('Unpin','ביטול הצמדה')} · {c.name}</button><LogSignalChart channel={windowChannel(c,start,end,r.component)} start={start} end={end} cursor={cursor} onCursor={setCursor} label={c.name+(c.components?' · '+c.components[r.component]:'')}/></div>:null;})}</>}
   <details><summary>{pick('File identity','זהות הקובץ')}</summary><code className="robot-log-hash">SHA-256: {hash}</code></details>
   {channel&&windowValid&&<RobotLogComparison key={hash} current={log} channel={channel} start={start} end={end} component={component}/>}
   {channel&&profile&&<aside><h3>{pick('Review with G3 Assist','סקירה באמצעות G3 Assist')}</h3><p>{pick('Prepare up to 20 numeric samples with signal, time window and source identity. Review the draft before sending it to Gemini through G3 Assist. The full log stays local. Select matching robot code in Assist if you need code-specific diagnosis.','הכינו עד 20 דגימות מספריות עם שם אות, חלון זמן וזהות מקור. בדקו את הטיוטה לפני שליחתה ל-Gemini דרך G3 Assist. הלוג המלא נשאר מקומי. בחרו קוד תואם ב-Assist לצורך אבחון מבוסס קוד.')}</p><button disabled={!windowValid||!plotted?.samples.some(s=>typeof s.value==='number'||typeof s.value==='boolean')} onClick={prepareAssist}>{pick('Prepare analysis draft','הכנת טיוטת ניתוח')}</button></aside>}
   {profile&&<details><summary>{pick('Record a test result','תיעוד תוצאת בדיקה')}</summary><p>{pick('File identity, time window, selected signal statistics and your code association are carried into a draft. You must enter the setup, criterion and observed outcome. Saving there shares that record with the team; raw log samples are not copied.','זהות הקובץ, חלון הזמן, נתוני האותות וקישור הקוד יועברו לטיוטה. יש להזין תצורה, קריטריון ותוצאה שנצפתה. שמירה שם משתפת את הרשומה עם הצוות; דגימות הלוג הגולמיות אינן מועתקות.')}</p><label>{pick('Where was this log recorded?','היכן הוקלט הלוג?')}<select value={evidenceKind} onChange={e=>setEvidenceKind(e.target.value as typeof evidenceKind)}><option value="">{pick('Choose explicitly','בחרו במפורש')}</option><option value="physical">{pick('Physical robot','רובוט פיזי')}</option><option value="simulated">{pick('Simulation','סימולציה')}</option></select></label><button disabled={!evidenceKind||!windowValid} onClick={prepareTrial}>{pick('Open test draft for review','פתיחת טיוטת בדיקה לסקירה')}</button></details>}
   {channel&&<details><summary>{pick('Export selected evidence','ייצוא ראיות נבחרות')}</summary><p>{pick('Exports the selected signal, time window and source identity. Nothing is sent to AI or saved as a passed test.','מייצא את האות הנבחר, חלון הזמן וזהות המקור. דבר אינו נשלח לבינה מלאכותית או נשמר כבדיקה שעברה.')}</p><button disabled={!windowValid} onClick={downloadEvidence}>{pick('Download evidence JSON','הורדת JSON ראיות')}</button><a href="/engineering?view=tests">{pick('Open existing robot test records','פתיחת רשומות בדיקת רובוט קיימות')}</a></details>}
  </>}
 </section>;
}
