import {useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
import '../styles/softwareMentor.css';
export type SoftwareSelection={repository:string;revision:string;base?:string;paths:string[];mode:'explain'|'diagnose'|'review'};
export default function SoftwareMentorContext({value,onChange,locked}:{value:SoftwareSelection|null;onChange:(v:SoftwareSelection|null)=>void;locked:boolean}){
 const {pick}=useLocalization();
 const [open,setOpen]=useState(false),[repos,setRepos]=useState<{owner:string;name:string;defaultBranch:string;private?:boolean}[]>([]),[repository,setRepository]=useState(''),[ref,setRef]=useState('main'),[baseRef,setBaseRef]=useState(''),[mode,setMode]=useState<SoftwareSelection['mode']>('explain');
 const [prepared,setPrepared]=useState<{revision:string;paths:string[];base?:string}|null>(null),[paths,setPaths]=useState<string[]>([]),[filter,setFilter]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function catalogue(){setOpen(true);setBusy(true);setError('');try{const {data,error}=await supabase.functions.invoke('github-repositories');if(error||data?.error)throw Error(pick('Repository catalogue unavailable. Try again.','קטלוג המאגרים אינו זמין. נסו שוב.'));setRepos((data.repositories??[]).filter((r:any)=>!r.private&&['GlueGunAndGlitter','GlueGunGlitter'].includes(r.owner)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function prepare(){setBusy(true);setError('');setPrepared(null);setPaths([]);try{
  const result=await supabase.functions.invoke('frc-assistant',{body:{action:'prepare-software',repository,ref}});
  if(result.error||result.data?.error)throw Error(result.data?.error??pick('Could not read this revision. Check the branch and access.','לא ניתן לקרוא גרסה זו. בדקו ענף והרשאות.'));
  let base:string|undefined;
  if(mode==='review'){const r=await supabase.functions.invoke('frc-assistant',{body:{action:'prepare-software',repository,ref:baseRef}});if(r.error||r.data?.error)throw Error(pick('Could not read the base revision.','לא ניתן לקרוא את גרסת הבסיס.'));base=r.data.revision;if(base===result.data.revision)throw Error(pick('Choose two different revisions.','בחרו שתי גרסאות שונות.'));}
  setPrepared({...result.data,base});
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="software-mentor" aria-label={pick('Software Mentor code context','הקשר קוד למנטור תוכנה')}>
  <header><div><strong>{pick('1. Attach robot code · optional','1. צירוף קוד רובוט · לא חובה')}</strong><p>{pick('Software Mentor uses these files in G3 Assist. Choosing files does not run AI; type your question below and press Send.','מנטור התוכנה משתמש בקבצים אלה ב-G3 Assist. בחירת קבצים אינה מפעילה AI; כתבו שאלה למטה ולחצו שליחה.')}</p></div>{!value&&<button type="button" disabled={locked||busy} onClick={()=>open?setOpen(false):void catalogue()}>{open?pick('Close picker','סגירת הבחירה'):pick('Choose robot code','בחירת קוד רובוט')}</button>}</header>
  {value?<><p><b dir="ltr">{value.repository}</b> · {value.mode==='explain'?pick('Understand code','הבנת קוד'):value.mode==='review'?pick('Review a change','ביקורת שינוי'):pick('Investigate a problem','חקירת תקלה')}</p><details><summary>{pick(`Code ready · files: ${value.paths.length} · revision details`,`הקוד מוכן · ${value.paths.length} קבצים · פרטי גרסה`)}</summary><code dir="ltr">{value.revision}</code>{value.base&&<p>{pick('Compare with','השוואה מול')} <code dir="ltr">{value.base}</code></p>}<p>{pick('Files in scope','קבצים בתחום הבדיקה')}: {value.paths.length}. {pick('The rest of the repository has not been reviewed.','יתר המאגר לא נבדק.')}</p><details><summary>{pick('Included files','קבצים כלולים')}</summary><ul>{value.paths.map(p=><li key={p} dir="ltr">{p}</li>)}</ul></details><p>{pick('This conversation stays pinned to this commit. Start a new conversation to use newer code. Historical repositories are not the current robot.','השיחה מקושרת לקומיט זה. לשימוש בקוד חדש פתחו שיחה חדשה. מאגרים היסטוריים אינם הרובוט הנוכחי.')}</p></details>{!locked&&<button type="button" onClick={()=>onChange(null)}>{pick('Remove code context','הסרת הקשר קוד')}</button>}</>:open&&<>
  <p>{pick('Public team repositories only. No AI charge for selecting files. Private access and the new offseason repository are not configured yet.','מאגרים ציבוריים של הקבוצה בלבד. בחירת קבצים אינה מחויבת ב-AI. גישה פרטית ומאגר קדם העונה החדש טרם הוגדרו.')}</p>
  <div className="software-mentor-grid"><label>{pick('Repository','מאגר')}<select disabled={busy} value={repository} onChange={e=>{setRepository(e.target.value);setRef(repos.find(r=>`${r.owner}/${r.name}`===e.target.value)?.defaultBranch??'main');setPrepared(null);}}><option value="">{pick('Choose a repository','בחרו מאגר')}</option>{repos.map(r=><option key={`${r.owner}/${r.name}`} value={`${r.owner}/${r.name}`}>{r.owner}/{r.name}</option>)}</select></label>
  <label>{pick('Purpose','מטרה')}<select disabled={busy} value={mode} onChange={e=>{setMode(e.target.value as SoftwareSelection['mode']);setPrepared(null);}}><option value="explain">{pick('Understand code','הבנת קוד')}</option><option value="diagnose">{pick('Investigate a problem','חקירת תקלה')}</option><option value="review">{pick('Review a change','ביקורת שינוי')}</option></select></label>
  <label>{pick('Target branch, tag or commit','ענף, תג או קומיט יעד')}<input dir="ltr" disabled={busy} maxLength={120} value={ref} onChange={e=>{setRef(e.target.value);setPrepared(null);}}/></label>{mode==='review'&&<label>{pick('Base branch, tag or commit','ענף, תג או קומיט בסיס')}<input dir="ltr" disabled={busy} maxLength={120} value={baseRef} onChange={e=>{setBaseRef(e.target.value);setPrepared(null);}}/></label>}</div>
  <button type="button" disabled={busy||!repository||!ref.trim()||(mode==='review'&&!baseRef.trim())} onClick={()=>void prepare()}>{busy?pick('Reading…','קורא…'):pick('Read revision & choose files','קריאת גרסה ובחירת קבצים')}</button>
  {prepared&&<div className="software-mentor-files"><p>{pick('Pinned commit','קומיט מקובע')}: <code dir="ltr">{prepared.revision}</code></p><label>{pick('Find a file or subsystem','חיפוש קובץ או תת־מערכת')}<input value={filter} onChange={e=>setFilter(e.target.value)}/></label><p>{pick('Select up to 6 files. Small source files only; include relevant commands, subsystem and constants. This is a selected-file review, not whole-repository analysis.','בחרו עד 6 קבצי מקור קטנים, כולל פקודות, תת־מערכת וקבועים רלוונטיים. הביקורת היא על הקבצים שנבחרו ולא על כל המאגר.')}</p><div className="software-mentor-file-list">{prepared.paths.filter(p=>p.toLowerCase().includes(filter.toLowerCase())).map(p=><label key={p}><input type="checkbox" checked={paths.includes(p)} disabled={!paths.includes(p)&&paths.length>=6} onChange={e=>setPaths(old=>e.target.checked?[...old,p]:old.filter(v=>v!==p))}/><span dir="ltr">{p}</span></label>)}</div><button type="button" disabled={!paths.length||locked} onClick={()=>{onChange({repository,revision:prepared.revision,base:prepared.base,paths,mode});setOpen(false);}}>{pick(`Attach files (${paths.length}) & write question`,`שימוש ב-${paths.length} קבצים בשיחה`)}</button></div>}
  </>}
  {error&&<p role="alert">{error}</p>}
 </section>;
}
