import {useState} from 'react';
import {useLocalization} from '../lib/localization';
import {useMemberAuth} from '../lib/memberAuth';
import {supabase} from '../supabase';
import {readSoftwareContext,saveSoftwareContext} from '../lib/softwareWorkingContext';
export default function SoftwareContextBar({repositories,onChange}:{repositories:{owner:string;name:string}[];onChange:()=>void}){
 const {profile}=useMemberAuth(),{pick}=useLocalization();const saved=profile?readSoftwareContext(profile.id):null;
 const [repository,setRepository]=useState(saved?.repository??''),[ref,setRef]=useState(saved?.revision??'main'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <details className="software-context"><summary>{pick('Working code revision','גרסת קוד לעבודה')}: {saved?`${saved.repository} · ${saved.revision.slice(0,8)}`:pick('Not selected · optional for logs','לא נבחרה · אופציונלי ללוגים')}</summary><p>{pick('This pins code for planning and review. It does not identify what ran on the robot. Recorded log identity stays separate.','זו גרסת קוד לתכנון וביקורת. היא אינה מזהה מה פעל ברובוט. זהות הקוד שתועדה בלוג נשארת נפרדת.')}</p><div className="log-window"><label>{pick('Repository','מאגר')}<select value={repository} onChange={e=>setRepository(e.target.value)} disabled={busy}><option value="">{pick('Choose accessible repository','בחירת מאגר נגיש')}</option>{repositories.map(r=><option key={r.owner+'/'+r.name} value={r.owner+'/'+r.name}>{r.name}</option>)}</select></label><label>{pick('Branch, tag or exact SHA','ענף, תג או SHA מדויק')}<input value={ref} onChange={e=>setRef(e.target.value)} disabled={busy}/></label><button disabled={busy||!repository||!ref.trim()} onClick={async()=>{if(!profile)return;setBusy(true);setError('');try{const r=await supabase.functions.invoke('frc-assistant',{body:{action:'prepare-software',repository,ref:ref.trim()}});if(r.error||r.data?.error||!/^[a-f0-9]{40}$/.test(r.data?.revision??''))throw Error();saveSoftwareContext(profile.id,{repository,revision:r.data.revision});onChange();}catch{setError(pick('Cannot pin this revision. Check private-code permission and the branch name.','לא ניתן לקבע גרסה זו. בדקו הרשאת קוד פרטי ושם ענף.'));}finally{setBusy(false);}}}>{pick('Pin revision','קיבוע גרסה')}</button><button disabled={busy||!saved} onClick={()=>{if(profile){try{saveSoftwareContext(profile.id,null);setError('');onChange();}catch{setError(pick('Browser storage is unavailable.','אחסון הדפדפן אינו זמין.'));}}}}>{pick('Clear','ניקוי')}</button></div>{error&&<p role="alert">{error}</p>}</details>;
}
