import {useBuildFormDraft} from '../lib/buildFormDraft';
import BuildDraftNotice from './BuildDraftNotice';
import {useEffect,useState} from 'react';
import {supabase} from '../supabase';
import {useLocalization} from '../lib/localization';
export default function StageReviewers({taskId,primary,initial,onSaved}:{taskId:string;primary:string;initial?:string[];onSaved:()=>Promise<void>}){
 const{pick}=useLocalization();const[people,setPeople]=useState<{id:string;display_name:string}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const defaults=()=>({ids:initial?.length?initial:[primary],note:'',mode:'parallel',disciplines:[] as string[]});const draft=useBuildFormDraft(`reviewers:${taskId}`,defaults,(v):v is ReturnType<typeof defaults>=>!!v&&typeof v==='object'&&typeof (v as ReturnType<typeof defaults>).mode==='string'&&typeof (v as ReturnType<typeof defaults>).note==='string'&&['ids','disciplines'].every(k=>Array.isArray((v as Record<string,unknown>)[k])&&((v as Record<string,string[]>)[k]).every(x=>typeof x==='string')));
 const {ids,note,mode,disciplines}=draft.value;const setIds=(ids:string[])=>draft.change({ids}),setNote=(note:string)=>draft.change({note}),setMode=(mode:string)=>draft.change({mode});const setDisciplines=(value:string[]|((v:string[])=>string[]))=>draft.change({disciplines:typeof value==='function'?value(draft.value.disciplines):value});
 useEffect(()=>{void supabase.from('project_review_gates').select('review_mode,reviewer_disciplines').eq('task_id',taskId).single().then(r=>{if(r.error)setError(pick('Review policy could not be loaded.','לא ניתן לטעון את מדיניות הביקורת.'));else {draft.initialize({...defaults(),mode:r.data.review_mode,disciplines:r.data.reviewer_disciplines??[]});}});},[taskId]);
 useEffect(()=>{void supabase.from('team_members').select('id,display_name').eq('active',true).in('role',['mentor','admin']).then(r=>{if(!r.error)setPeople(r.data??[]);});},[]);
 return <details className="review-evidence-editor"><summary>{pick('Required stage reviewers','בודקים נדרשים לשלב')}</summary><p>{pick('Every listed reviewer must approve. The first reviewer records requirement findings. Saving a changed reviewer list requires a fresh submission.','כל הבודקים ברשימה חייבים לאשר. הבודק הראשון רושם ממצאים לדרישות. שינוי רשימת הבודקים דורש הגשה חדשה.')}</p><form data-build-form={draft.id} className="review-evidence-item" onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await supabase.rpc('configure_engineering_reviewers',{p_task:taskId,p_reviewers:ids,p_mode:mode,p_disciplines:ids.map((_,i)=>disciplines[i]??''),p_reason:note});setBusy(false);setError(r.error?.message??pick('Reviewers saved. Submit the work again.','הבודקים נשמרו. יש להגיש את העבודה שוב.'));if(!r.error){draft.saved({...draft.value,note:''});await onSaved();}}}>
 <BuildDraftNotice {...draft}/><label>{pick('Review order','סדר הביקורת')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value='parallel'>{pick('Parallel — everyone must approve','במקביל — נדרש אישור כולם')}</option><option value='sequential'>{pick('Sequential — in the order below','ברצף — לפי הסדר להלן')}</option></select></label>{ids.map((id,i)=><label key={i}>{pick('Reviewer','בודק')} {i+1}<select required value={id} onChange={e=>setIds(ids.map((x,j)=>i===j?e.target.value:x))}><option value="">{pick('Choose reviewer','בחירת בודק')}</option>{people.map(p=><option value={p.id} key={p.id}>{p.display_name}</option>)}</select><span>{pick('Accountable discipline','תחום אחריות')}</span><input required minLength={2} maxLength={100} value={disciplines[i]??''} placeholder={pick('CAD, mechanical, electrical…','CAD, מכניקה, חשמל…')} onChange={e=>setDisciplines(v=>ids.map((_,j)=>j===i?e.target.value:v[j]??''))}/>{i>0?<button type="button" onClick={()=>{setIds(ids.filter((_,j)=>j!==i));setDisciplines(disciplines.filter((_,j)=>j!==i));}}>{pick('Remove','הסרה')}</button>:null}</label>)}
 {ids.length<5?<button type="button" className="hub-button secondary" onClick={()=>setIds([...ids,''])}>{pick('Add reviewer','הוספת בודק')}</button>:null}
 <label>{pick('Reason for reviewer configuration','סיבה להגדרת הבודקים')}<textarea required minLength={3} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="hub-button" disabled={busy}>{pick('Save required reviewers','שמירת בודקים נדרשים')}</button><p role="status">{error}</p></form></details>;
}
