import {notifyProjectChange} from "../lib/projectRefresh";
import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useLocalization} from '../lib/localization';
import {supabase} from '../supabase';
export type TaskDependency={task_id:string;prerequisite_id:string;task_status:string;title:string|null;status:string|null;unavailable:boolean;owner:string|null;subteam:string|null;due_at:string|null;href:string|null;waiting:boolean};
export type DependencyCandidate={id:string;title:string;project_id:string;archived?:boolean};
export default function TaskDependencies({taskId,edges,candidates,projects,canManage,loaded,onChanged}:{taskId:string;edges:TaskDependency[];candidates:DependencyCandidate[];projects:{id:string;name:string;subteam:string|null;status:string}[];canManage:boolean;loaded:boolean;onChanged:()=>Promise<void>}){
 const {pick}=useLocalization(),navigate=useNavigate();const[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const own=edges.filter(e=>e.task_id===taskId),waiting=own.filter(e=>e.waiting);
 async function change(remove?:string){if(busy)return;setBusy(true);setMessage('');try{const r=remove?await supabase.from('project_task_dependencies').delete().eq('task_id',taskId).eq('prerequisite_id',remove).select('task_id'):await supabase.from('project_task_dependencies').insert({task_id:taskId,prerequisite_id:selected}).select('task_id');if(r.error||!r.data?.length)throw r.error??Error();setSelected('');await onChanged();notifyProjectChange();}catch{setMessage(pick('Could not save. Check permissions, duplicate links or a circular dependency.','לא ניתן לשמור. בדקו הרשאות, קישור כפול או תלות מעגלית.'));}finally{setBusy(false);}}
 return <details className={`task-dependencies ${loaded&&own.length&&!waiting.length?"dependencies-ready":""}`}><summary>{!loaded?pick('Dependencies unavailable','תלויות אינן זמינות'):waiting.length?pick(`Waiting on ${waiting.length} prerequisite${waiting.length===1?'':'s'}`,`ממתין ל־${waiting.length} משימות מקדימות`):own.length?pick('All prerequisites complete','כל המשימות המקדימות הושלמו'):pick('No prerequisites linked','לא קושרו משימות מקדימות')}</summary>
 {loaded?<><p>{waiting.length?pick('Waiting for the unfinished prerequisites below.','ממתין להשלמת המשימות המקדימות שלהלן.'):own.length?own[0].task_status==='done'?pick('This task and all its prerequisites are complete.','משימה זו וכל המשימות המקדימות שלה הושלמו.'):pick('Ready to proceed — all prerequisites complete. This task still needs its own completion.','אפשר להתקדם — כל המשימות המקדימות הושלמו. יש להשלים את המשימה הזו בנפרד.'):pick('Link a task that must be completed before this work proceeds.','קשרו משימה שיש להשלים לפני התקדמות בעבודה זו.')}</p>{own.map(e=><div className="dependency-row" key={e.prerequisite_id}><div><strong>{e.title??pick('Restricted prerequisite','משימה מקדימה מוגבלת לצפייה')}</strong><span className={`dependency-status ${e.waiting?"is-waiting":"is-complete"}`}>{e.unavailable?pick('Unavailable or archived — review the link','אינה זמינה או בארכיון — בדקו את הקישור'):e.waiting?pick('Waiting','ממתין'):pick('✓ Completed','✓ הושלם')}</span><small>{e.subteam??''} · {e.owner??pick('Unassigned','ללא אחראי')}</small>{e.due_at?<small>{pick('Due','מועד')}: {new Date(e.due_at).toLocaleString()}{e.waiting&&Date.parse(e.due_at)<Date.now()?pick(' · Overdue',' · באיחור'):''}</small>:null}{e.task_status==='done'&&e.waiting?<small>{pick('This task is complete, but a prerequisite needs review.','המשימה הושלמה, אך משימה מקדימה דורשת בדיקה.')}</small>:null}</div>{e.href?<button type="button" onClick={()=>navigate(e.href!)}>{pick('Open','פתיחה')}</button>:null}{canManage?<button type="button" disabled={busy} onClick={()=>void change(e.prerequisite_id)}>{pick('Unlink','הסרת קישור')}</button>:null}</div>)}
 {canManage?<div className="dependency-editor"><label>{pick('Add a prerequisite from any visible team','הוספת משימה מקדימה מצוות גלוי')}<select value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}><option value="">{pick('Choose a task','בחירת משימה')}</option>{candidates.filter(t=>t.id!==taskId&&!t.archived&&!own.some(e=>e.prerequisite_id===t.id)&&projects.some(p=>p.id===t.project_id&&p.status!=='archived')).map(t=>{const p=projects.find(p=>p.id===t.project_id);return <option key={t.id} value={t.id}>{p?.subteam} · {p?.name} · {t.title}</option>})}</select></label><button type="button" disabled={!selected||busy} onClick={()=>void change()}>{pick('Save dependency','שמירת תלות')}</button></div>:null}</>:null}{message?<p role="alert">{message}</p>:null}</details>;
}
