import {axisValue,centeredProfile,freshProfile,padButton,padProblem,type Pad,type PadProfile} from '../lib/twinGamepad';
import type {useTwinGamepad} from '../lib/useTwinGamepad';
export default function TwinGamepadSettings({controller,locked}:{controller:ReturnType<typeof useTwinGamepad>;locked:boolean}){
 const {pads,pad,profile:p,choose,update,notice,setNotice}=controller;
 const change=(next:PadProfile)=>update({...next,verified:false});
 const live=pad?[axisValue(pad,p.forward,p.deadband),axisValue(pad,p.strafe,p.deadband),axisValue(pad,p.turn,p.deadband)]:[0,0,0];
 const buttonName=(i:number,device:Pad|null)=>device?.mapping==='standard'?({0:'A / Cross',1:'B / Circle',2:'X / Square',3:'Y / Triangle',4:'LB / L1',5:'RB / R1',6:'LT / L2',7:'RT / R2',8:'View / Select',9:'Menu / Start',10:'Left stick press',11:'Right stick press'} as Record<number,string>)[i]??`Button ${i}`:`Button ${i}`;
 return <div className="twin-gamepad"><h2>Controller setup</h2><p>Default: left stick drives relative to the robot’s front; right stick turns. Camera rotation does not change the controls.</p><label>Controller<select disabled={locked||!pads.length} value={pad?.index??''} onChange={e=>{const found=pads.find(p=>p.index===Number(e.target.value));if(found)choose(found);}}><option value="" disabled>{pads.length?'Select a controller':'Connect a controller and press any button'}</option>{pads.map(p=><option key={p.index} value={p.index}>Controller {p.index+1} · {p.id}</option>)}</select></label><p className="intel-muted">{pad?`${pad.mapping==='standard'?'Standard Xbox / PlayStation layout':'Non-standard layout — verify your assignments'} · ${pad.axes.length} axes · ${pad.buttons.length} buttons`:'No controller detected. Click this page, then press a controller button.'}</p>
 <div className="twin-pad-live" aria-label="Live controller directions">{[['Forward / reverse',live[0],'Reverse','Forward'],['Strafe',live[1],'Left','Right'],['Rotation',live[2],'Counter-clockwise','Clockwise']].map(([label,value,neg,pos])=><div key={String(label)}><span>{label}</span><meter min={-1} max={1} value={Number(value)} aria-label={String(label)}/><strong>{Number(value)===0?'Centered':`${Number(value)<0?neg:pos} ${Math.round(Math.abs(Number(value))*100)}%`}</strong></div>)}</div><p className="intel-muted">Move the sticks while driving is disabled: forward should read Forward; right on the rotation stick should read Clockwise.</p>
 <fieldset disabled={locked||!pad}><label>Driving frame<select value={p.frame} onChange={e=>change({...p,frame:e.target.value as PadProfile['frame']})}><option value="robot">Robot-relative (recommended)</option><option value="field">Field-relative (+X forward, −Y right)</option></select></label><p className="intel-muted">{p.frame==='robot'?'Forward always follows the front intake, even after turning.':'Forward always points toward field +X, regardless of robot heading. This is not camera-relative.'}</p>
 <details><summary>Axes, direction & sensitivity</summary><div className="twin-pad-raw" aria-label="Raw controller axes">{pad?.axes.map((v,i)=><span key={i}>Axis {i}: {v.toFixed(2)}</span>)}</div><div className="twin-pad-bindings">{([['forward','Forward / reverse'],['strafe','Strafe right / left'],['turn','Clockwise / counter-clockwise']] as const).map(([name,label])=><div key={name}><label>{label}<select value={p[name].axis} onChange={e=>change({...p,[name]:{...p[name],axis:Number(e.target.value),center:0}})}>{name==='strafe'&&<option value={-1}>Not assigned (no strafe)</option>}{Array.from({length:Math.min(64,pad?.axes.length??4)},(_,i)=><option key={i} value={i}>Axis {i}{pad?.mapping==='standard'?[' · Left stick horizontal',' · Left stick vertical',' · Right stick horizontal',' · Right stick vertical'][i]??'':''}</option>)}</select></label><label className="intel-toggle"><input type="checkbox" checked={p[name].invert} onChange={e=>change({...p,[name]:{...p[name],invert:e.target.checked}})}/>Reverse direction</label></div>)}</div>
 {([['deadband','Dead zone',.05,.35,.01],['curve','Response curve (1 = linear)',1,3,.1],['driveScale','Maximum drive power',.2,1,.05],['turnScale','Maximum turning power',.2,1,.05]] as const).map(([key,label,min,max,step])=><label key={key}>{label}: {p[key].toFixed(2)}<input type="range" min={min} max={max} step={step} value={p[key]} onChange={e=>change({...p,[key]:Number(e.target.value)})}/></label>)}<div className="intel-button-row"><button type="button" onClick={()=>{if(!pad)return;try{change(centeredProfile(pad,p));setNotice('Neutral centers captured. Recheck the live directions.');}catch(e){setNotice((e as Error).message);}}}>Calibrate released sticks</button><button type="button" onClick={()=>change(freshProfile())}>Restore Xbox defaults</button></div><p className="intel-muted">Release the sticks before calibration. Increase the dead zone only if the centered sticks still drift.</p></details>
 <details><summary>Controller buttons</summary>{([['intakeButton','Toggle intake'],['shootButton','Shoot while held'],['stopButton','Disable driving']] as const).map(([key,label])=><label key={key}>{label}<select value={p[key]} onChange={e=>change({...p,[key]:Number(e.target.value)})}><option value={-1}>Not assigned</option>{Array.from({length:Math.min(64,pad?.buttons.length??16)},(_,i)=><option value={i} key={i}>{buttonName(i,pad)}</option>)}</select></label>)}<p>Pressed buttons: {pad?.buttons.map((b,i)=>b.pressed?buttonName(i,pad):null).filter(Boolean).join(", ")||"None"}</p><p>Xbox defaults: A toggles intake · hold RT to shoot · B disables driving. Start driving still requires the on-screen button.</p></details>
 {pad&&pad.mapping!=='standard'&&<label className="intel-toggle"><input type="checkbox" checked={p.verified} onChange={e=>update({...p,verified:e.target.checked})}/>I checked forward, strafe, rotation and button assignments for this controller.</label>}</fieldset>
 <p className="twin-pad-actions">Intake: {pad&&padButton(pad,p.intakeButton)?'pressed':'released'} · Shoot: {pad&&padButton(pad,p.shootButton)?'pressed':'released'} · Stop: {pad&&padButton(pad,p.stopButton)?'pressed':'released'}</p><p role="status">{padProblem(pad,p)||notice||(locked?'Controller active; setup is locked.':'Ready. Release sticks and buttons, then press Start driving.')}</p>{locked&&<p>Disable driving and stop recording before changing controller settings.</p>}</div>;
}
