import {useEffect,useState} from "react";
import {supabase} from "../supabase";
import {useMemberAuth} from "../lib/memberAuth";
import {useLocalization} from "../lib/localization";
import "../styles/dialog.css";
export type SessionAudit={id:string;status:string;ends_at:string;opened_by?:string|null;closed_by?:string|null;opened_at?:string|null;closed_at?:string|null;opened_automatically?:boolean;closed_automatically?:boolean};
export default function WorkshopSessionControls({meeting,onUpdated}:{meeting:SessionAudit;onUpdated:()=>void}){
 const {profile}=useMemberAuth(),{pick}=useLocalization(),[names,setNames]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{let active=true;const ids=[meeting.opened_by,meeting.closed_by].filter(Boolean) as string[];if(ids.length)void supabase.from("team_members").select("id,display_name").in("id",ids).then(({data})=>{if(active)setNames(Object.fromEntries((data??[]).map(m=>[m.id,m.display_name])));});return()=>{active=false};},[meeting.opened_by,meeting.closed_by]);
 const label=(id:string|null|undefined,automatic:boolean|undefined)=>id?(names[id]??pick("Recorded member","חבר/ה מתועד/ת")):automatic?pick("System · scheduled","מערכת · מתוזמן"):pick("Not recorded (historical)","לא תועד (היסטורי)");
 async function manage(action:"close"|"extend"){if(busy)return;if(action==="close"&&!confirm(pick("Close this workshop session? Everyone must check out first.","לסגור מפגש זה? כולם חייבים לדווח יציאה תחילה.")))return;setBusy(true);const result=await supabase.rpc("manage_workshop_session",{p_meeting_id:meeting.id,p_action:action});setMessage(result.error?.message??pick(action==="close"?"Workshop closed.":"Workshop extended by one hour.",action==="close"?"המפגש נסגר.":"המפגש הוארך בשעה."));setBusy(false);if(!result.error)onUpdated();}
 return <div className="workshop-session-controls"><small>{pick("Opened by","נפתח על ידי")}: {meeting.status==="scheduled"?pick("Scheduled to open one hour before start","ייפתח שעה לפני ההתחלה"):label(meeting.opened_by,meeting.opened_automatically)}</small>{meeting.status==="closed"&&<small>{pick("Closed by","נסגר על ידי")}: {label(meeting.closed_by,meeting.closed_automatically)}</small>}{meeting.status==="open"&&<small>{pick("Open until","פתוח עד")}: {new Date(meeting.ends_at).toLocaleString("en-IL",{timeZone:"Asia/Jerusalem",hour:"2-digit",minute:"2-digit"})}</small>}{meeting.status==="open"&&profile&&["admin","mentor","team_leader"].includes(profile.role)&&<div><button className="button-secondary" disabled={busy} onClick={()=>void manage("extend")}>{pick("Extend 1 hour","הארכה בשעה")}</button><button className="button-secondary" disabled={busy} onClick={()=>void manage("close")}>{pick("Close workshop","סגירת סדנה")}</button></div>}{message&&<p role="status">{message}</p>}</div>;
}
