import {useState} from 'react';
import '../src/styles/connectedKnowledgeReview.css';

// Review-only workflow. Never imported by production routes; no provider or database client.
export default function ConnectedKnowledgeReview(){
 const [step,setStep]=useState('search'),[query,setQuery]=useState('Elevator oscillates while holding a load'),[role,setRole]=useState('mentor'),[selected,setSelected]=useState(true),[notes,setNotes]=useState(''),[saved,setSaved]=useState(false);
 const allowed=role==='mentor'||role==='admin';
 const steps=[['search','Find evidence'],['ask','Ask G3 Assist'],['test','Plan a test'],['save','Save learning']];
 return <main className="connected-review">
  <aside className="connected-review-notice">INTERACTIVE DESIGN REVIEW · Sample content only · No AI calls or database writes</aside>
  <header><div><p className="hub-eyebrow">G3 6740 · ENGINEERING KNOWLEDGE</p><h1>From evidence to a better robot.</h1><p>Find a useful reference. Work through the problem. Keep what the team learns.</p></div><label>Preview role<select value={role} onChange={e=>setRole(e.target.value)}><option value="mentor">Mentor</option><option value="admin">Admin</option><option value="team_leader">Team leader</option><option value="member">Student</option></select></label></header>
  <nav aria-label="Knowledge workflow">{steps.map(([id,label],i)=><button key={id} aria-current={step===id?'step':undefined} onClick={()=>setStep(id)}><small>0{i+1}</small>{label}</button>)}</nav>
  <div className="connected-review-layout"><section>
   {step==='search'?<><h2>What are you working on?</h2><form onSubmit={e=>{e.preventDefault();setSaved(false);}}><label>Question or keywords<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="connected-review-filters"><label>Season<select><option>All indexed seasons</option><option>2026</option></select></label><label>Topic<select><option>PID & controls</option><option>Elevator</option></select></label><button type="submit">Search</button></div></form><p className="connected-review-muted">Example result layout · Production search will use the shared retrieval service.</p><article><p className="hub-eyebrow">SOURCE PASSAGE · EXAMPLE</p><h3>Control-system diagnosis reference</h3><p>This sample card demonstrates the source title, relevant excerpt, version and citation location. It is not engineering evidence.</p><dl><dt>Why it matched</dt><dd>Elevator, oscillation and feedback control</dd><dt>Review status</dt><dd>Source passage — not a verified robot configuration</dd></dl><label className="connected-review-check"><input type="checkbox" checked={selected} onChange={e=>setSelected(e.target.checked)}/> Use this reference as context</label></article><button className="primary" disabled={!allowed} onClick={()=>setStep('ask')}>Ask G3 Assist with selected context →</button></>:null}
   {step==='ask'?<><p className="hub-eyebrow">G3 ASSIST · SAMPLE ANSWER STRUCTURE</p><h2>{query||'Your engineering question'}</h2>{allowed?<><div className="connected-review-chips"><span>Robot: not supplied</span><span>Season: not supplied</span><span>{selected?'1 example reference selected':'No reference selected'}</span></div><article><h3>Recommended next action</h3><p>A real answer will identify the next useful diagnostic step and explain what observation it would confirm or rule out.</p><h3>What is known / what is missing</h3><p>The symptom comes from your question. Measurements, controller settings and the physical configuration have not been supplied.</p><h3>Evidence and alternatives</h3><p>Each factual claim will link to authorized source passages. Hypotheses and suggested designs remain explicitly labelled.</p></article><button className="primary" onClick={()=>setStep('test')}>Build a test plan →</button></>:<p role="status">Paid AI is not enabled for this role. Search remains available. An administrator can change the role permission.</p>}</>:null}
   {step==='test'?<><p className="hub-eyebrow">PROPOSED TEST · NOT VALIDATED</p><h2>Define how you will check the idea.</h2><article><h3>Test plan contents</h3><ol><li>Question the test should resolve</li><li>Setup and supervision requirements</li><li>Measurements, units and recording method</li><li>Expected observations and stop conditions</li></ol><p>These fields will be populated from the reviewed proposal and team input. A generated plan is not proof that a mechanism is safe.</p></article><label>Observed outcome<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Record what was actually measured. Leave blank until the test is performed." rows={5}/></label><button className="primary" onClick={()=>setStep('save')}>Prepare a team-library draft →</button></>:null}
   {step==='save'?<><p className="hub-eyebrow">TEAM LIBRARY · DRAFT</p><h2>Keep the reasoning and the evidence.</h2><article><dl><dt>Question</dt><dd>{query||'Not supplied'}</dd><dt>Evidence</dt><dd>{selected?'Example selection retained':'None selected'}</dd><dt>Test outcome</dt><dd>{notes||'Not measured — no outcome claimed'}</dd><dt>Review</dt><dd>Awaiting authorized review</dd></dl></article><p>Saving does not mark the answer verified. Later edits require review of the new revision.</p><button className="primary" onClick={()=>setSaved(true)}>Save preview draft</button>{saved?<p role="status">Preview draft prepared. Nothing was written to the team library.</p>:null}</>:null}
  </section><aside><p className="hub-eyebrow">WORKSPACE CONTEXT</p><h2>Evidence stays visible.</h2><dl><dt>Access</dt><dd>{allowed?'Paid AI permitted by preview role':'Search only — paid AI disabled'}</dd><dt>Source coverage</dt><dd>Coverage will reflect indexed material, not every robot that competed.</dd><dt>Trust</dt><dd>Source passages, reviewed facts and AI proposals remain distinct.</dd><dt>Spending</dt><dd>Production paid steps require permission and a budget reservation.</dd></dl><a href="/?article=example">Open the implemented article-review workflow →</a></aside></div>
 </main>;
}
