"""Deterministic, idempotent Academy seed. Keys stay in backend SQL, never web assets.
Run from the repository root with Python 3. Content revision is immutable once used.
"""
import json
from pathlib import Path

def pair(en, he): return [en, he]
WIRING='https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-1/intro-to-frc-robot-wiring.html'
CAN='https://docs.wpilib.org/en/stable/docs/hardware/hardware-basics/can-wiring-basics.html'
BATTERY='https://docs.wpilib.org/en/stable/docs/hardware/hardware-basics/robot-battery.html'
BEST='https://docs.wpilib.org/en/stable/docs/hardware/hardware-basics/wiring-best-practices.html'
REV='https://www.revrobotics.com/content/docs/FRC-Robot-Basics-Guide.pdf'
CTRE='https://v5.docs.ctr-electronics.com/en/latest/ch08_BringUpCAN.html'

# Each question contains a bilingual prompt, correct answer and two plausible distractors.
packs=[dict(key='power',domain='electrical',title=pair('Power & component identification','הספק וזיהוי רכיבים'),
 goal=pair('Trace power on an unpowered robot and identify what each device does.','עקבו אחר ההספק ברובוט מנותק וזהו את תפקידו של כל רכיב.'),
 sources=[['WPILib · illustrated robot wiring',WIRING],['WPILib · battery basics',BATTERY]],
 steps=[pair('Disconnect the battery. Identify battery connector, main breaker, distribution device, controller and motor before touching wiring.','נתקו סוללה. זהו מחבר סוללה, מפסק ראשי, רכיב חלוקה, בקר ומנוע לפני מגע בחיווט.'),pair('Follow the installed power path using device labels and the manufacturer diagram. Record unknown devices rather than guessing.','עקבו אחר מסלול ההספק לפי סימוני הרכיבים ותרשים היצרן. תעדו רכיבים לא מזוהים בלי לנחש.'),pair('Separate motor power, control/data and sensor connections in your sketch. Record the actual breaker and wire specifications for one branch.','הפרידו בשרטוט בין הספק למנוע, בקרה/נתונים וחיבורי חיישנים. תעדו מפרט מפסק וחוט בפועל בענף אחד.'),pair('Compare the sketch against the physical robot with a reviewer. Powered checks require a supervised test plan and clear moving parts.','השוו את השרטוט לרובוט עם בודק. בדיקות עם מתח דורשות תוכנית מפוקחת והרחקה מחלקים נעים.')],
 mistakes=[pair('A controller status LED does not prove the battery can supply load.','נורית בקר אינה מוכיחה שהסוללה מסוגלת לספק זרם בעומס.'),pair('Do not infer an installed wire gauge or breaker rating from a CAD model.','אין להסיק עובי חוט או דירוג מפסק מותקן ממודל CAD.')],
 practical=[pair('Map one power branch','מיפוי ענף הספק אחד'),pair('Inspect the battery installation','בדיקת התקנת הסוללה')],
 rubrics=[[pair('Battery disconnected before inspection','סוללה נותקה לפני הבדיקה'),pair('Every device in the chosen branch identified on a labeled sketch','כל רכיב בענף מזוהה בשרטוט מסומן'),pair('Actual wire and protection ratings recorded with their source','מפרטי החוט וההגנה בפועל תועדו עם מקור'),pair('Reviewer compares sketch to the installed robot','בודק משווה את השרטוט לרובוט המותקן')],[pair('Battery identity and visible condition recorded','זהות הסוללה ומצבה החזותי תועדו'),pair('Connector seating, retention and cable protection inspected unpowered','נבדקו חיבור, קיבוע והגנת כבלים ללא מתח'),pair('Mounting and access to disconnect demonstrated','הודגמו קיבוע וגישה לניתוק'),pair('Defects recorded; responsible reviewer decides readiness','תועדו ליקויים; בודק אחראי מחליט על מוכנות')]],
 questions=[
 ['Before changing power wiring?','לפני שינוי חיווט הספק?','Disconnect the battery','לנתק סוללה','Only disable software','רק להשבית תוכנה','Only stop the wheels','רק לעצור גלגלים'],
 ['What does CAN carry?','מה CAN מעביר?','Control data','נתוני בקרה','Motor supply current','זרם הספק למנוע','Compressed air','אוויר דחוס'],
 ['An unknown connector should be…','מחבר לא מזוהה צריך…','Identified from its device documentation','להיות מזוהה לפי תיעוד הרכיב','Connected by matching shape alone','להתחבר לפי צורה בלבד','Tested by swapping power wires','להיבדק בהחלפת חוטי מתח'],
 ['Where do you verify branch protection?','איפה מאמתים הגנת ענף?','Actual hardware labels and applicable documentation','סימוני החומרה והתיעוד המתאים','A photograph of another robot','תצלום רובוט אחר','Wire color only','צבע החוט בלבד'],
 ['A good no-load voltage proves…','מתח תקין ללא עומס מוכיח…','Only the voltage under that measured condition','רק את המתח בתנאי המדידה','Full battery capacity','קיבולת סוללה מלאה','All power connectors are sound','שכל מחברי ההספק תקינים'],
 ['A loose battery needs…','סוללה רופפת דורשת…','Secure mounting before operation','קיבוע לפני הפעלה','Higher driving speed','מהירות נסיעה גבוהה יותר','A software offset','היסט בתוכנה'],
 ['Which evidence identifies the tested battery?','איזו ראיה מזהה את הסוללה שנבדקה?','Recorded battery ID','מזהה סוללה מתועד','Robot paint color','צבע הרובוט','Team ranking','דירוג הקבוצה'],
 ['A power path sketch should include…','שרטוט מסלול הספק צריך לכלול…','Source, protection and load','מקור, הגנה ועומס','Only the motor','רק את המנוע','Only CAN devices','רק רכיבי CAN'],
 ['Damage on a power cable means…','נזק בכבל הספק מחייב…','Stop and obtain inspection/repair before use','לעצור ולבצע בדיקה/תיקון לפני שימוש','Cover it in the photograph','להסתיר בתצלום','Increase the breaker rating','להגדיל דירוג מפסק'],
 ['Who confirms physical readiness?','מי מאשר מוכנות פיזית?','A responsible reviewer using the inspection evidence','בודק אחראי על סמך ראיות הבדיקה','A quiz score alone','ציון מבחן בלבד','The CAD viewer','מציג ה-CAD']]),
dict(key='can',domain='electrical',title=pair('CAN & sensors','CAN וחיישנים'),goal=pair('Trace a bus, inspect real connectors and reproduce a fault safely.','עקבו אחר אפיק, בדקו מחברים אמיתיים ושחזרו תקלה בבטחה.'),sources=[['WPILib · CAN wiring',CAN],['CTRE · CAN bring-up',CTRE]],
steps=[pair('Draw your installed bus, including each device, bus identity and the two endpoints. Label H and L at every connector.','שרטטו את האפיק המותקן, הרכיבים, זהות האפיק ושני קצותיו. סמנו H ו-L בכל מחבר.'),pair('Open the CAN wiring workshop in the robot lab for connector-specific illustrations. Inspect full seating, crimps and strain relief with power disconnected.','פתחו את סדנת CAN במעבדת הרובוטים לאיורי מחברים. בדקו ישיבה מלאה, לחיצות והקלת מאמצים ללא מתח.'),pair('For the documented two-terminator bus, measure H–L resistance unpowered. Around 60 Ω is consistent with two 120 Ω terminations; it is not proof of error-free communication.','באפיק המתועד עם שני נגדי סיום, מדדו התנגדות H–L ללא מתח. כ-60 אוהם מתאימים לשני נגדי 120 אוהם; אין בכך הוכחה לתקשורת ללא שגיאות.'),pair('With supervised power and the robot disabled, record discovered devices and error observations. Repeat the same observation after repair.','עם מתח בפיקוח ורובוט מושבת, תעדו רכיבים שזוהו ושגיאות. חזרו על אותה בדיקה לאחר התיקון.')],
mistakes=[pair('A missing device can be wiring, configuration or power; do not replace hardware before isolating the cause.','רכיב חסר עשוי לנבוע מחיווט, הגדרה או הספק; בידדו סיבה לפני החלפת חומרה.'),pair('Sensor connectors are not interchangeable just because they fit. Check voltage and pinout.','מחברי חיישנים אינם חלופיים רק מפני שהם מתאימים מכנית. בדקו מתח ומיפוי פינים.')],
practical=[pair('Trace and inspect one CAN bus','מעקב ובדיקת אפיק CAN'),pair('Reproduce and retest a connector fault','שחזור ובדיקה חוזרת של תקלת מחבר')],
rubrics=[[pair('Bus identity, devices and endpoints labeled','זהות אפיק, רכיבים וקצוות סומנו'),pair('H/L and termination arrangement verified against documentation','H/L וסידור נגדי סיום אומתו מול תיעוד'),pair('Connector-specific inspection recorded unpowered','בדיקת המחבר תועדה ללא מתח'),pair('Resistance value and meter condition recorded without claiming full validation','תועדו התנגדות ותנאי מדידה בלי לטעון לאימות מלא')],[pair('Use a supervised spare harness; never inject a short on the robot','משתמשים בצמה רזרבית בפיקוח; אין ליצור קצר ברובוט'),pair('Fault symptom and affected devices recorded','תועדו תסמין ורכיבים מושפעים'),pair('One repair/change recorded','תועד תיקון/שינוי אחד'),pair('Repeated equivalent tests linked to the repair task','בדיקות חוזרות זהות קושרו למשימת התיקון')]],questions=[
['Yellow CAN wire connects to…','חוט CAN צהוב מתחבר ל…','H','H','L','L','Battery positive','פלוס סוללה'],['Resistance is measured…','התנגדות נמדדת…','With power disconnected','ללא מתח','While enabled','במצב מופעל','With the motor spinning','כשהמנוע מסתובב'],['Two 120 Ω endpoints in parallel give about…','שני נגדי 120 אוהם במקביל נותנים כ…','60 Ω','60 אוהם','240 Ω','240 אוהם','0 Ω','0 אוהם'],['About 120 Ω may indicate…','כ-120 אוהם עשויים להעיד על…','One disconnected or missing termination','נגד סיום חסר או מנותק','Guaranteed good communication','תקשורת תקינה בוודאות','A full battery','סוללה מלאה'],['A correct resistance reading proves…','התנגדות תקינה מוכיחה…','Only part of the electrical checks','רק חלק מהבדיקות החשמליות','All devices have correct IDs','שלכל הרכיבים מזהים נכונים','No intermittent faults exist','שאין תקלות לסירוגין'],['All devices after one connector disappear. Inspect…','כל הרכיבים אחרי מחבר נעלמים. בדקו…','That connector and downstream wiring','את המחבר והחיווט שאחריו','The robot paint','את צבע הרובוט','Only the first wheel','רק את הגלגל הראשון'],['Strain relief should…','הקלת מאמצים צריכה…','Keep cable load off the terminal','למנוע עומס כבל על ההדק','Pull the conductor tight','למתוח את המוליך','Replace termination','להחליף נגד סיום'],['Sensor pinout comes from…','מיפוי פיני חיישן מגיע מ…','The exact device documentation','תיעוד הרכיב המדויק','Its color alone','צבעו בלבד','Another sensor that fits','חיישן אחר שמתאים'],['A fair repair retest uses…','בדיקה חוזרת הוגנת משתמשת ב…','The same fault observation procedure','אותו נוהל תצפית לתקלה','An unrelated mechanism','מנגנון לא קשור','Only one successful screenshot','צילום מוצלח אחד בלבד'],['Where should extra termination be added?','איפה מוסיפים נגד סיום נוסף?','Only where the bus documentation requires it','רק היכן שתיעוד האפיק מחייב','At every device','בכל רכיב','At every cable joint','בכל חיבור כבל']]),
dict(key='inspection',domain='electrical',title=pair('Wiring & mounting inspection','בדיקת חיווט וקיבוע'),goal=pair('Find failures before vibration and motion expose them.','זהו כשלים לפני שרעידות ותנועה חושפות אותם.'),sources=[['WPILib · wiring best practices',BEST],['WPILib · illustrated connections',WIRING]],
steps=[pair('Create an inspection path from the battery through one mechanism. Use the actual installed hardware and connector instructions.','צרו מסלול בדיקה מהסוללה דרך מנגנון אחד. השתמשו בחומרה המותקנת ובהוראות המחבר.'),pair('With power disconnected, inspect seating, conductor capture, exposed strands, abrasion and retention.','ללא מתח, בדקו ישיבה, אחיזת מוליך, גידים חשופים, שחיקה ונעילה.'),pair('Move the mechanism only as safely permitted, checking the entire cable travel for tension, pinch points and service access.','הזיזו מנגנון רק באופן מותר ובטוח, ובדקו לאורך התנועה מתח בכבל, נקודות צביטה וגישה לתחזוקה.'),pair('Assign each defect an owner in Work. Photograph or sketch the location and repeat the inspection after repair.','הקצו לכל ליקוי אחראי בעבודה. צלמו או שרטטו מיקום וחזרו על הבדיקה לאחר תיקון.')],mistakes=[pair('A cable tie can hold a cable while the terminal still has a poor connection. Inspect both.','אזיקון יכול להחזיק כבל כשההדק מחובר גרוע. בדקו את שניהם.'),pair('Inspection is not a powered stress test. Agree a supervised procedure separately.','בדיקה חזותית אינה בדיקת עומס עם מתח. קבעו נוהל מפוקח בנפרד.')],
practical=[pair('Inspect a complete mechanism harness','בדיקת צמת מנגנון מלאה'),pair('Close a defect with repair evidence','סגירת ליקוי עם ראיות תיקון')],rubrics=[[pair('All connectors listed with exact device identity','כל המחברים רשומים עם זהות רכיב מדויקת'),pair('Seating and retention checked unpowered','ישיבה ונעילה נבדקו ללא מתח'),pair('Full safe mechanism travel checked for pinch/strain','כל טווח התנועה הבטוח נבדק לצביטה/מאמץ'),pair('Findings include location and evidence','הממצאים כוללים מיקום וראיות')],[pair('Original defect and owner recorded','ליקוי מקורי ואחראי תועדו'),pair('Repair method matches connector instructions','שיטת התיקון תואמת להוראות המחבר'),pair('Same inspection repeated after repair','אותה בדיקה חזרה לאחר תיקון'),pair('Reviewer signs off or requests a specific correction','בודק מאשר או מבקש תיקון מוגדר')]],questions=[
['A terminal should grip…','הדק צריך לאחוז…','The correctly prepared conductor','במוליך שהוכן כראוי','Only the insulation','רק בבידוד','A cable tie','באזיקון'],['Loose exposed strands can…','גידים חשופים משוחררים עלולים…','Cause unintended electrical contact','ליצור מגע חשמלי לא רצוי','Improve strain relief','לשפר הקלת מאמצים','Increase accuracy','להגדיל דיוק'],['Check cable travel…','בודקים מסלול כבל…','Across the safe mechanism range','בכל טווח המנגנון הבטוח','Only at rest','רק במנוחה','Only in CAD','רק ב-CAD'],['A defect record needs…','רישום ליקוי צריך…','Location, symptom and owner','מיקום, תסמין ואחראי','Only “broken”','רק ״שבור״','Only a team number','רק מספר קבוצה'],['A sharp edge near wiring needs…','קצה חד ליד חיווט דורש…','Protection or rerouting before operation','הגנה או שינוי מסלול לפני הפעלה','Higher voltage','מתח גבוה יותר','More software logging only','רק יותר רישום תוכנה'],['A tug check is performed…','בדיקת משיכה נעשית…','Gently, unpowered, per connector instructions','בעדינות, ללא מתח ולפי הוראות המחבר','By pulling the whole robot','במשיכת כל הרובוט','While driving','תוך נסיעה'],['Service access matters because…','גישה לתחזוקה חשובה כי…','Parts must be inspected and replaced','צריך לבדוק ולהחליף רכיבים','It changes the game score','היא משנה ניקוד משחק','It removes the need for labels','היא מבטלת צורך בסימון'],['After repair…','לאחר תיקון…','Repeat the relevant inspection','חוזרים על הבדיקה המתאימה','Erase the original defect','מוחקים את הליקוי המקורי','Skip reviewer feedback','מדלגים על משוב'],['Connector torque should be…','מומנט מחבר צריך להיות…','Taken from its exact specification','לפי המפרט המדויק','As high as possible','גבוה ככל האפשר','The same for all connectors','זהה לכל המחברים'],['A mounting check includes…','בדיקת קיבוע כוללת…','Retention and interference through motion','אחיזה והפרעות בזמן תנועה','Only appearance','רק מראה','Only wireless signal','רק אות אלחוטי']]),
dict(key='fastening',domain='mechanical',title=pair('Mechanical fastening','חיבורים מכניים'),goal=pair('Build and inspect a documented joint instead of guessing tightness.','בנו ובדקו חיבור מתועד במקום לנחש הידוק.'),sources=[['REV · FRC Robot Basics, mechanical assembly examples',REV]],steps=[pair('Select a documented joint on a reference CAD assembly. Identify its parts, fastener, mating surfaces and access.','בחרו חיבור מתועד בהרכבת CAD לדוגמה. זהו חלקים, מחבר, משטחי מגע וגישה.'),pair('For your practice joint, record fastener size, material, engagement and locking method from its drawing/specification. Missing specifications need review.','בחיבור התרגול תעדו גודל מחבר, חומר, עומק הברגה ושיטת נעילה מהשרטוט/מפרט. מפרט חסר דורש בדיקה.'),pair('Assemble an unpowered sample with the specified tool. Never substitute an arbitrary torque value.','הרכיבו דוגמה ללא מתח עם הכלי המוגדר. אין להחליף מפרט בערך מומנט שרירותי.'),pair('Check alignment, access and interference. Record a repeatable inspection method and have the reviewer inspect the joint.','בדקו יישור, גישה והפרעות. תעדו שיטת בדיקה חוזרת ובקשו בדיקת החיבור.')],mistakes=[pair('CAD geometry does not prove joint strength or preload.','גאומטריית CAD אינה מוכיחה חוזק או עומס הידוק.'),pair('A witness mark helps detect movement; it does not prove correct torque.','סימן ביקורת מסייע לזהות תזוזה; הוא אינו מוכיח מומנט תקין.')],practical=[pair('Assemble a documented practice joint','הרכבת חיבור תרגול מתועד'),pair('Inspect and improve service access','בדיקה ושיפור גישה לתחזוקה')],rubrics=[[pair('Drawing and fastener identity attached','צורפו שרטוט וזהות המחבר'),pair('Tool and specified tightening method recorded','תועדו כלי ושיטת הידוק מוגדרת'),pair('Alignment and seating verified','אומתו יישור וישיבה'),pair('Reviewer checks assembled sample','בודק בודק דוגמה מורכבת')],[pair('Original access problem demonstrated','הודגמה בעיית הגישה המקורית'),pair('Proposed change preserves required clearances','שינוי מוצע שומר על מרווחים נדרשים'),pair('Disassembly/reassembly demonstrated on sample','הודגמו פירוק והרכבה בדוגמה'),pair('Unknown structural effects escalated for engineering review','השפעות מבניות לא ידועות הועברו לבדיקה הנדסית')]],questions=[
['Tightening torque is chosen from…','מומנט הידוק נבחר לפי…','The applicable joint specification','מפרט החיבור המתאים','Appearance','מראה','Maximum tool setting','עוצמת כלי מרבית'],['CAD alone proves joint strength?','CAD לבדו מוכיח חוזק חיבור?','No; loads/materials/assembly matter','לא; עומסים, חומרים והרכבה חשובים','Yes, if it renders','כן, אם מוצג','Yes, if colored','כן, אם צבעוני'],['A witness mark indicates…','סימן ביקורת מצביע על…','Relative movement since marking','תזוזה יחסית מאז הסימון','Exact preload','עומס הידוק מדויק','Guaranteed fatigue life','אורך חיי עייפות מובטח'],['Before copying a fastener…','לפני העתקת מחבר…','Verify size, material and joint requirements','מאמתים גודל, חומר ודרישות חיבור','Choose any shiny one','בוחרים כל מחבר מבריק','Remove washers at random','מסירים דסקיות אקראית'],['Poor tool access can cause…','גישה גרועה לכלי עלולה לגרום…','Difficult inspection and repair','קושי בבדיקה ותיקון','Guaranteed higher strength','חוזק גבוה מובטח','More scoring points','יותר ניקוד'],['Misaligned parts should be…','חלקים לא מיושרים צריכים…','Investigated before forcing assembly','להיבדק לפני הרכבה בכוח','Forced together','להתחבר בכוח','Hidden behind panels','להסתתר מאחורי פנלים'],['Thread engagement is…','עומק חיבור הברגה הוא…','A joint property to check against its design','מאפיין חיבור שיש לבדוק מול התכנון','Always irrelevant','תמיד חסר חשיבות','The battery voltage','מתח הסוללה'],['An unspecified locking method needs…','שיטת נעילה לא מוגדרת דורשת…','Engineering review and documentation','בדיקה הנדסית ותיעוד','Any available glue','כל דבק זמין','No inspection','ללא בדיקה'],['Useful evidence includes…','ראיות מועילות כוללות…','Specification and inspected assembly','מפרט והרכבה שנבדקה','Only an unrelated CAD screenshot','רק צילום CAD לא קשור','Only a quiz result','רק תוצאת מבחן'],['A modified structural joint…','חיבור מבני ששונה…','Needs review of the changed requirements','דורש בדיקת הדרישות שהשתנו','Is approved automatically','מאושר אוטומטית','Needs no records','לא דורש תיעוד']]),
dict(key='transmission',domain='mechanical',title=pair('Shafts, bearings & transmission','צירים, מיסבים ותמסורת'),goal=pair('Trace motion and inspect alignment, support and retention.','עקבו אחר תנועה ובדקו יישור, תמיכה וקיבוע.'),sources=[['REV · FRC Robot Basics, bearings and chain examples',REV]],steps=[pair('In a reference assembly, follow motor → transmission → shaft → driven part. Identify which parts rotate together.','בהרכבת דוגמה עקבו ממנוע לתמסורת, ציר וחלק מונע. זהו אילו חלקים מסתובבים יחד.'),pair('Record bearing supports, shaft retention and sprocket/pulley alignment on a drawing. Do not infer hidden retainers from an external view.','תעדו תמיכות מיסב, קיבוע ציר ויישור גלגלי שרשרת/רצועה בשרטוט. אין להסיק קיבוע נסתר ממבט חיצוני.'),pair('On an unpowered practice assembly, inspect free motion, unwanted axial movement and interference using the design specification.','בהרכבת תרגול ללא מתח בדקו תנועה חופשית, תנועה צירית לא רצויה והפרעות לפי המפרט.'),pair('Record the before/after condition of one adjustment. Powered tests require guarding, supervision and a defined procedure.','תעדו מצב לפני ואחרי כוונון אחד. בדיקות עם מתח דורשות מיגון, פיקוח ונוהל מוגדר.')],mistakes=[pair('Tightening a transmission until it binds is not a substitute for the correct tension procedure.','הידוק תמסורת עד שנתקעת אינו תחליף לנוהל מתיחה נכון.'),pair('A shaft looking straight in CAD does not establish real alignment under load.','ציר שנראה ישר ב-CAD אינו מוכיח יישור בפועל תחת עומס.')],practical=[pair('Map a transmission and its supports','מיפוי תמסורת ותמיכות'),pair('Inspect an unpowered assembly','בדיקת הרכבה ללא מתח')],rubrics=[[pair('Input/output and rotating groups identified','זוהו קלט/פלט וקבוצות מסתובבות'),pair('Bearing and retention locations labeled','סומנו מיסבים וקיבועים'),pair('Ratio calculated from actual tooth counts','יחס חושב ממספרי שיניים בפועל'),pair('Unknown parts explicitly marked','חלקים לא ידועים סומנו במפורש')],[pair('Power isolated and stored energy handled by procedure','מתח נותק ואנרגיה אגורה טופלה לפי נוהל'),pair('Alignment and retention checked against drawing','יישור וקיבוע נבדקו מול שרטוט'),pair('Motion/interference observations recorded','תועדו תצפיות תנועה/הפרעה'),pair('Reviewer checks findings before powered test','בודק בוחן ממצאים לפני בדיקה עם מתח')]],questions=[
['A bearing primarily…','מיסב בעיקר…','Supports a moving shaft with controlled motion','תומך בציר נע עם תנועה מבוקרת','Stores battery power','אוגר הספק סוללה','Sends CAN messages','שולח הודעות CAN'],['Shaft retention prevents…','קיבוע ציר מונע…','Unwanted axial displacement','תזוזה צירית לא רצויה','All electrical faults','כל תקלה חשמלית','All gear wear forever','כל שחיקת גלגלי שיניים לתמיד'],['Sprockets should be checked for…','גלגלי שרשרת נבדקים ל…','Alignment and specified tension','יישור ומתיחה מוגדרת','Matching paint only','צבע זהה בלבד','Battery charge','טעינת סוללה'],['A 12-tooth driver and 36-tooth driven sprocket ideally give…','מניע 12 שיניים ומונע 36 שיניים נותנים אידאלית…','One third output speed','שליש מהירות ביציאה','Triple output speed','פי שלושה מהירות ביציאה','Unchanged speed','מהירות זהה'],['A binding assembly should…','הרכבה שנתקעת צריכה…','Be inspected before powered operation','להיבדק לפני הפעלה עם מתח','Use more motor power immediately','לקבל יותר הספק מיד','Be ignored','להיות מוזנחת'],['Hidden shaft retainers are…','קיבועי ציר נסתרים הם…','Unknown until inspected or documented','לא ידועים עד בדיקה או תיעוד','Always present','תמיד קיימים','Unnecessary','מיותרים'],['Before hand inspection…','לפני בדיקה ידנית…','Isolate power and address stored energy','מנתקים מתח ומטפלים באנרגיה אגורה','Enable the robot','מפעילים רובוט','Spin at full speed','מסובבים במהירות מרבית'],['Transmission tension comes from…','מתיחת תמסורת נקבעת לפי…','Its design/manufacturer procedure','נוהל התכנון/היצרן','Maximum possible tension','מתיחה מרבית אפשרית','Color of the belt','צבע הרצועה'],['A ratio calculation needs…','חישוב יחס דורש…','Actual driver and driven tooth counts','מספרי שיניים במניע ובמונע','Only robot mass','רק מסת רובוט','Only battery ID','רק מזהה סוללה'],['Useful before/after evidence holds…','ראיות לפני/אחרי מועילות שומרות…','Test conditions comparable','על תנאי בדיקה דומים','No record of the original','על היעדר רישום מקורי','Different procedures every time','על נהלים שונים בכל פעם']]),
dict(key='mechanism-tests',domain='drive_pit',title=pair('Intake & shooter testing','בדיקות איסוף וירי'),goal=pair('Measure repeated pickups and shots with a clear success definition.','מדדו איסופים ויריות חוזרים עם הגדרת הצלחה ברורה.'),sources=[['WPILib · wiring best practices and baseline checks',BEST],['REV · FRC Robot Basics, mechanism examples',REV]],steps=[pair('Choose a supervised test area and a success criterion before running. Record robot configuration, battery, game pieces, distance and procedure.','בחרו אזור בדיקה מפוקח וקריטריון הצלחה מראש. תעדו תצורה, סוללה, חלקי משחק, מרחק ונוהל.'),pair('For intake tests, count presented pieces, collected pieces and jams. Keep approach and piece placement repeatable.','בבדיקות איסוף ספרו חלקים שהוצגו, נאספו ותקיעות. שמרו על גישה ומיקום חלקים חוזרים.'),pair('For shooting, record attempted and successful shots plus elapsed time. Accuracy and throughput answer different questions.','בירי תעדו ניסיונות ופגיעות מוצלחות וזמן. דיוק וקצב עונים על שאלות שונות.'),pair('Save every trial, including failures. Change one factor, link the baseline and repair task, then retest with equivalent conditions.','שמרו כל ניסיון, כולל כישלונות. שנו גורם אחד, קשרו בסיס ומשימת תיקון וחזרו על בדיקה בתנאים דומים.')],mistakes=[pair('One successful shot is not a reliability estimate. Show the sample count and spread.','ירייה מוצלחת אחת אינה אומדן אמינות. הציגו מספר ניסיונות ופיזור.'),pair('A simulated result is not measured robot performance.','תוצאה מדומה אינה ביצוע שנמדד ברובוט.')],practical=[pair('Record repeated intake trials','תיעוד ניסיונות איסוף חוזרים'),pair('Compare repeated shooting trials','השוואת ניסיונות ירי חוזרים')],rubrics=[[pair('Supervisor, test area and pass definition agreed before testing','סוכמו פיקוח, אזור וקריטריון מעבר לפני בדיקה'),pair('Setup and procedure recorded','תועדו תצורה ונוהל'),pair('At least five trials include duration, counts and jams','לפחות חמישה ניסיונות כוללים זמן, ספירות ותקיעות'),pair('Shared test record linked as evidence','רשומת בדיקה משותפת קושרה כראיה')],[pair('Distance, target, game pieces and battery conditions recorded','מרחק, מטרה, חלקי משחק ותנאי סוללה תועדו'),pair('At least five baseline and five retest trials','לפחות חמישה ניסיונות בסיס וחמישה חוזרים'),pair('One change and any confounding conditions disclosed','תועד שינוי אחד וכל תנאי מפריע'),pair('Comparison reports counts, variability and limits without claiming causation','השוואה מציגה ספירות, שונות ומגבלות בלי לטעון לסיבתיות')]],questions=[
['Define success…','מגדירים הצלחה…','Before collecting results','לפני איסוף תוצאות','After seeing the best run','אחרי הניסיון הטוב ביותר','Only when publishing','רק בפרסום'],['Record a jam…','מתעדים תקיעה…','As a fault, including the failed trial','כתקלה, כולל הניסיון שנכשל','By deleting the trial','במחיקת הניסיון','Only if it happens ten times','רק אם קרתה עשר פעמים'],['Accuracy is…','דיוק הוא…','Successful shots divided by attempted shots','פגיעות מוצלחות חלקי ניסיונות ירי','Shots divided by battery voltage','יריות חלקי מתח סוללה','Always equal to throughput','תמיד שווה לקצב'],['Throughput uses…','קצב משתמש ב…','Successful pieces and elapsed time','חלקים מוצלחים וזמן שחלף','Only a photo','רק בתצלום','Only robot color','רק בצבע רובוט'],['A fair comparison should…','השוואה הוגנת צריכה…','Keep procedure and conditions equivalent','לשמור על נוהל ותנאים דומים','Change every variable','לשנות כל משתנה','Omit failures','להשמיט כישלונות'],['An unknown battery voltage is…','מתח סוללה לא ידוע הוא…','Recorded as unknown','נרשם כלא ידוע','Assumed perfect','מונח כמושלם','Written as zero','נכתב כאפס'],['One successful trial establishes…','ניסיון מוצלח אחד קובע…','That single observed outcome','את התוצאה הבודדת שנצפתה','Guaranteed match reliability','אמינות משחק מובטחת','A championship result','תוצאת אליפות'],['Simulation and physical trials should…','ניסיונות סימולציה ופיזיים צריכים…','Remain clearly distinguished','להישאר מובחנים בבירור','Be pooled as identical evidence','להתאחד כראיות זהות','Have their labels removed','להיות ללא תוויות'],['A changed setup is saved…','תצורה ששונתה נשמרת…','As a new snapshot linked to baseline','כתמונת מצב חדשה המקושרת לבסיס','By overwriting the old run','בדריסת ניסיון ישן','Without a change note','ללא הערת שינוי'],['A repair is validated by…','תיקון מאומת באמצעות…','Equivalent retests and responsible review','בדיקות חוזרות דומות ובדיקה אחראית','Closing a task alone','סגירת משימה בלבד','Passing a quiz alone','מעבר מבחן בלבד']])]

def uid(i,slot): return f'67402026-1002-4000-8000-{i:06d}{slot:06d}'
def sql(v): return "'"+str(v).replace("'","''")+"'"
def bilingual(p): return '\n---HE---\n'.join(p)
lines=['-- Generated by backend/content/build_practical_pack.py. No learner auto-enrollment.', 'begin;']
for i,p in enumerate(packs,1):
 course=uid(i,1)
 title=bilingual(p['title']); goal=bilingual(p['goal'])
 lines.append(f"insert into public.training_courses(id,title,description,domain,required,active,sort_order) values('{course}',{sql(title)},{sql(goal)},{sql(p['domain'])},true,true,{500+i}) on conflict(id) do nothing;")
 # No extra module-evidence gate: both practical assessments require explicit human review.
 content={k:v for k,v in p.items() if k!='questions'}
 content['quizId']=uid(i,2);content['practicalIds']=[uid(i,3),uid(i,4)]
 content['sourceChecked']='2026-10-02';content['sourcePolicy']='Linked living documentation; confirm the installed hardware and current instructions before practical work.'
 lines.append(f"insert into public.training_lesson_packs(course_id,revision,content) values('{course}','2026-10-02.v1',{sql(json.dumps(content,ensure_ascii=False))}::jsonb) on conflict(course_id) do nothing;")
 questions=[];keys={}
 for j,q in enumerate(p['questions']):
  choices=[bilingual(q[2:4]),bilingual(q[4:6]),bilingual(q[6:8])]
  correct=choices[0];shift=(i+j)%3;choices=choices[shift:]+choices[:shift]
  key=f'q{j+1}';keys[key]=[correct]
  questions.append(dict(id=key,prompt=bilingual(q[:2]),kind='single_choice',options=choices,points=1))
 assert len(questions)==10
 instructions=bilingual(pair('Answer all ten questions. Review the lesson after feedback; practical qualification also requires both demonstrations to be approved.','ענו על עשר השאלות. חזרו לשיעור לאחר משוב; הסמכה מעשית דורשת גם אישור לשתי ההדגמות.'))
 lines.append(f"insert into public.training_assessments(id,course_id,title,instructions,assessment_type,questions,required,graded,max_score,passing_score,max_attempts,target_type,sort_order) values('{uid(i,2)}','{course}',{sql(bilingual(pair('Knowledge check','בדיקת ידע')))},{sql(instructions)},'quiz',{sql(json.dumps(questions,ensure_ascii=False))}::jsonb,true,true,10,8,5,'all',10) on conflict(id) do nothing;")
 lines.append(f"insert into public.training_assessment_answer_keys(assessment_id,answers) values('{uid(i,2)}',{sql(json.dumps(keys,ensure_ascii=False))}::jsonb) on conflict(assessment_id) do nothing;")
 for a in range(2):
  instruction=bilingual(['\n'.join([p['practical'][a][lang],*['• '+r[lang] for r in p['rubrics'][a]],pair('Submit observations and an evidence link. A responsible reviewer must verify every criterion; a self-check is not certification.','הגישו תצפיות וקישור לראיה. בודק אחראי חייב לאמת כל קריטריון; בדיקה עצמית אינה הסמכה.')[lang]]) for lang in range(2)])
  lines.append(f"insert into public.training_assessments(id,course_id,title,instructions,assessment_type,questions,required,graded,max_attempts,target_type,sort_order) values('{uid(i,a+3)}','{course}',{sql(bilingual(p['practical'][a]))},{sql(instruction)},'practical','[]',true,false,10,'all',{20+a*10}) on conflict(id) do nothing;")
lines.append('commit;')
Path('backend/supabase/practical_learning_pack_20261002.sql').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print('Generated six courses, 60 questions, 12 practical assessments; no enrollment mutations.')
