-- G3 absence approvals and auditable meeting-roster attendance.
begin;
create table if not exists public.absence_requests(id uuid primary key default gen_random_uuid(),member_id uuid not null references public.team_members(id) on delete cascade default auth.uid(),calendar_event_id uuid not null references public.team_calendar_events(id) on delete cascade,reason text not null check(length(trim(reason))>=3),status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled')),reviewer_note text,reviewed_by uuid references public.team_members(id) on delete set null,reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(member_id,calendar_event_id));
create table if not exists public.absence_request_history(id uuid primary key default gen_random_uuid(),request_id uuid not null references public.absence_requests(id) on delete cascade,status text not null,note text,actor_id uuid references public.team_members(id) on delete set null,created_at timestamptz not null default now());
alter table public.absence_requests enable row level security;alter table public.absence_request_history enable row level security;
drop policy if exists "members view applicable absences" on public.absence_requests;create policy "members view applicable absences" on public.absence_requests for select to authenticated using(member_id=auth.uid() or public.current_team_role() in ('admin','mentor'));
drop policy if exists "members request own absence" on public.absence_requests;create policy "members request own absence" on public.absence_requests for insert to authenticated with check(member_id=auth.uid() and status='pending');
drop policy if exists "members view applicable absence history" on public.absence_request_history;create policy "members view applicable absence history" on public.absence_request_history for select to authenticated using(exists(select 1 from public.absence_requests r where r.id=request_id and (r.member_id=auth.uid() or public.current_team_role() in ('admin','mentor'))));
create or replace function public.notify_absence_reviewers() returns trigger language plpgsql security definer set search_path=public as $$declare reviewer record;event_title text;member_name text;begin select title into event_title from public.team_calendar_events where id=new.calendar_event_id;select display_name into member_name from public.team_members where id=new.member_id;insert into public.absence_request_history(request_id,status,note,actor_id) values(new.id,'pending',new.reason,new.member_id);for reviewer in select id from public.team_members where active and role in ('admin','mentor') loop insert into public.team_actions(title,details,action_type,target_type,target_value,priority,source_table,source_id,destination,created_by) values('Absence request: '||coalesce(member_name,'Team member'),coalesce(event_title,'Calendar event')||' · '||new.reason,'announcement','member',reviewer.id::text,'normal','absence_review_'||reviewer.id,new.id,'/attendance?view=absences&request='||new.id,new.member_id) on conflict(source_table,source_id) where source_table is not null and source_id is not null do update set details=excluded.details,cancelled=false;end loop;return new;end$$;
drop trigger if exists absence_request_notify_reviewers on public.absence_requests;create trigger absence_request_notify_reviewers after insert on public.absence_requests for each row execute function public.notify_absence_reviewers();
create or replace function public.review_absence_request(p_request_id uuid,p_status text,p_note text) returns public.absence_requests language plpgsql security definer set search_path=public as $$declare request public.absence_requests;event_title text;begin if public.current_team_role() not in ('admin','mentor') then raise exception 'Not authorized to review absence requests';end if;if p_status not in ('approved','rejected') or length(trim(coalesce(p_note,'')))<3 then raise exception 'A decision and written response are required';end if;update public.absence_requests set status=p_status,reviewer_note=trim(p_note),reviewed_by=auth.uid(),reviewed_at=now(),updated_at=now() where id=p_request_id and status='pending' returning * into request;if not found then raise exception 'Pending absence request not found';end if;insert into public.absence_request_history(request_id,status,note,actor_id) values(request.id,p_status,trim(p_note),auth.uid());update public.team_actions set cancelled=true where source_id=request.id and source_table like 'absence_review_%';select title into event_title from public.team_calendar_events where id=request.calendar_event_id;perform public.sync_team_action('absence_request_status',request.id,'Absence request '||p_status||': '||coalesce(event_title,'Calendar event'),trim(p_note),'announcement','member',request.member_id::text,null,case when p_status='rejected' then 'high' else 'normal' end,'/attendance?view=absences&request='||request.id,auth.uid(),false);return request;end$$;
grant execute on function public.review_absence_request(uuid,text,text) to authenticated;
create or replace function public.save_meeting_attendance_roster(p_meeting_id uuid,p_present_members uuid[],p_note text) returns integer language plpgsql security definer set search_path=public as $$declare meeting public.team_meetings;target_member uuid;record_id uuid;old_record record;count_saved integer:=0;begin if not public.has_permission('correct_attendance') and public.current_team_role()<>'mentor' then raise exception 'Not authorized to record attendance';end if;if length(trim(coalesce(p_note,'')))<3 then raise exception 'A roster audit note is required';end if;select * into meeting from public.team_meetings where id=p_meeting_id;if not found then raise exception 'Meeting not found';end if;for old_record in select attendance.* from public.attendance_records attendance where attendance.meeting_id=p_meeting_id and attendance.check_in_method='admin' and not(attendance.member_id=any(coalesce(p_present_members,'{}'::uuid[]))) loop insert into public.attendance_audit_log(attendance_id,actor_id,action,reason,previous_values) values(old_record.id,auth.uid(),'roster_absent',trim(p_note),to_jsonb(old_record));delete from public.attendance_records where id=old_record.id;end loop;foreach target_member in array coalesce(p_present_members,'{}'::uuid[]) loop insert into public.attendance_records(meeting_id,member_id,checked_in_at,checked_out_at,check_in_method,check_out_method,corrected_by,correction_reason) values(meeting.id,target_member,meeting.starts_at,meeting.ends_at,'admin','admin',auth.uid(),trim(p_note)) on conflict(meeting_id,member_id) do update set checked_in_at=excluded.checked_in_at,checked_out_at=excluded.checked_out_at,check_in_method='admin',check_out_method='admin',corrected_by=auth.uid(),correction_reason=excluded.correction_reason,updated_at=now() returning id into record_id;insert into public.attendance_audit_log(attendance_id,actor_id,action,reason,new_values) values(record_id,auth.uid(),'roster_present',trim(p_note),jsonb_build_object('meeting_id',meeting.id,'member_id',target_member));count_saved:=count_saved+1;end loop;return count_saved;end$$;
grant execute on function public.save_meeting_attendance_roster(uuid,uuid[],text) to authenticated;
drop policy if exists "leaders read attendance" on public.attendance_records;create policy "leaders read attendance" on public.attendance_records for select to authenticated using(public.has_permission('view_team_reports'));
drop policy if exists "leaders read attendance audit" on public.attendance_audit_log;create policy "leaders read attendance audit" on public.attendance_audit_log for select to authenticated using(public.has_permission('view_team_reports'));
commit;
