-- G3 6740 Robot Issue Tracking. Run once in the Supabase SQL editor.
begin;
create table if not exists public.robot_issues (
  id uuid primary key default gen_random_uuid(), issue_number bigint generated by default as identity unique,
  title text not null check (char_length(trim(title)) between 3 and 160), description text not null check (char_length(trim(description)) between 3 and 5000),
  subsystem text not null check (subsystem in ('drivetrain','mechanical','electrical','software','controls','vision','pneumatics','battery','bumpers','inspection','other')),
  severity text not null default 'medium' check (severity in ('low','medium','high','critical')),
  status text not null default 'reported' check (status in ('reported','triaged','in_progress','blocked','verification','resolved')),
  discovered_context text not null default 'workshop' check (discovered_context in ('workshop','testing','inspection','match','pit','other')),
  reporter_id uuid not null references public.team_members(id) on delete restrict default auth.uid(), owner_id uuid references public.team_members(id) on delete set null,
  project_id uuid references public.team_projects(id) on delete set null, resolution text check (resolution is null or char_length(resolution) <= 5000),
  resolved_at timestamptz, resolved_by uuid references public.team_members(id) on delete set null, archived boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.robot_issue_updates (
  id uuid primary key default gen_random_uuid(), issue_id uuid not null references public.robot_issues(id) on delete cascade,
  author_id uuid not null references public.team_members(id) on delete restrict default auth.uid(), body text not null check (char_length(trim(body)) between 1 and 3000),
  update_type text not null default 'comment' check (update_type in ('comment','diagnosis','work_log','verification')), created_at timestamptz not null default now()
);
create table if not exists public.robot_issue_attachments (
  id uuid primary key default gen_random_uuid(), issue_id uuid not null references public.robot_issues(id) on delete cascade,
  uploaded_by uuid not null references public.team_members(id) on delete restrict default auth.uid(), storage_path text not null unique,
  file_name text not null, mime_type text, created_at timestamptz not null default now()
);
create index if not exists robot_issues_active_idx on public.robot_issues(archived,status,severity,updated_at desc);
create index if not exists robot_issues_owner_idx on public.robot_issues(owner_id,status);
create index if not exists robot_issue_updates_issue_idx on public.robot_issue_updates(issue_id,created_at);
create index if not exists robot_issue_attachments_issue_idx on public.robot_issue_attachments(issue_id,created_at);
alter table public.robot_issues enable row level security; alter table public.robot_issue_updates enable row level security; alter table public.robot_issue_attachments enable row level security;
drop policy if exists "members view robot issues" on public.robot_issues;
create policy "members view robot issues" on public.robot_issues for select to authenticated using (public.current_team_role() is not null and (not archived or public.is_admin()));
drop policy if exists "members report robot issues" on public.robot_issues;
create policy "members report robot issues" on public.robot_issues for insert to authenticated with check (reporter_id=auth.uid() and public.current_team_role() is not null);
drop policy if exists "team manages robot issues" on public.robot_issues;
create policy "team manages robot issues" on public.robot_issues for update to authenticated using (public.current_team_role() is not null) with check (public.current_team_role() is not null);
drop policy if exists "admins delete robot issues" on public.robot_issues;
create policy "admins delete robot issues" on public.robot_issues for delete to authenticated using (public.is_admin());
drop policy if exists "members view issue updates" on public.robot_issue_updates;
create policy "members view issue updates" on public.robot_issue_updates for select to authenticated using (public.current_team_role() is not null);
drop policy if exists "members add issue updates" on public.robot_issue_updates;
create policy "members add issue updates" on public.robot_issue_updates for insert to authenticated with check (author_id=auth.uid() and public.current_team_role() is not null);
drop policy if exists "authors or admins delete issue updates" on public.robot_issue_updates;
create policy "authors or admins delete issue updates" on public.robot_issue_updates for delete to authenticated using (author_id=auth.uid() or public.is_admin());
drop policy if exists "members view issue attachments" on public.robot_issue_attachments;
create policy "members view issue attachments" on public.robot_issue_attachments for select to authenticated using (public.current_team_role() is not null);
drop policy if exists "members add issue attachments" on public.robot_issue_attachments;
create policy "members add issue attachments" on public.robot_issue_attachments for insert to authenticated with check (uploaded_by=auth.uid() and public.current_team_role() is not null);
drop policy if exists "uploaders or admins delete attachments" on public.robot_issue_attachments;
create policy "uploaders or admins delete attachments" on public.robot_issue_attachments for delete to authenticated using (uploaded_by=auth.uid() or public.is_admin());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('robot-issues','robot-issues',false,10485760,array['image/jpeg','image/png','image/webp','text/plain','application/pdf'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "members read robot issue files" on storage.objects;
create policy "members read robot issue files" on storage.objects for select to authenticated using (bucket_id='robot-issues' and public.current_team_role() is not null);
drop policy if exists "members upload robot issue files" on storage.objects;
create policy "members upload robot issue files" on storage.objects for insert to authenticated with check (bucket_id='robot-issues' and public.current_team_role() is not null);
drop policy if exists "owners or admins delete robot issue files" on storage.objects;
create policy "owners or admins delete robot issue files" on storage.objects for delete to authenticated using (bucket_id='robot-issues' and (owner_id=auth.uid()::text or public.is_admin()));
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='robot_issues') then alter publication supabase_realtime add table public.robot_issues; end if; end $$;
commit;
