begin;
alter table public.competition_assignments drop constraint if exists competition_assignments_status_check;alter table public.competition_assignments add constraint competition_assignments_status_check check(status in ('assigned','confirmed','completed','absent','replacement_requested'));alter table public.competition_assignments add column if not exists replacement_note text;
create table if not exists public.frc_skills(id uuid primary key default gen_random_uuid(),name text not null,domain text not null check(domain in ('mechanical','electrical','software','cad','strategy','drive_pit','business','safety')),description text,requires_validation boolean not null default true,active boolean not null default true,created_at timestamptz not null default now(),unique(name,domain));
create table if not exists public.member_skill_progress(member_id uuid not null references public.team_members(id) on delete cascade,skill_id uuid not null references public.frc_skills(id) on delete cascade,level text not null default 'learning' check(level in ('learning','practicing','qualified','mentor')),evidence text,validated_by uuid references public.team_members(id) on delete set null,validated_at timestamptz,updated_at timestamptz not null default now(),primary key(member_id,skill_id));
create table if not exists public.season_milestones(id uuid primary key default gen_random_uuid(),title text not null,workstream text not null,status text not null default 'planned' check(status in ('planned','in_progress','at_risk','blocked','completed')),due_at date,owner_id uuid references public.team_members(id) on delete set null,depends_on uuid references public.season_milestones(id) on delete set null,details text,created_by uuid references public.team_members(id) on delete set null default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.engineering_decisions(id uuid primary key default gen_random_uuid(),title text not null,problem text not null,decision text not null,rationale text not null,alternatives text,workstream text not null,status text not null default 'approved' check(status in ('proposed','approved','superseded')),decided_by uuid references public.team_members(id) on delete set null,created_by uuid not null references public.team_members(id) on delete restrict default auth.uid(),created_at timestamptz not null default now());
insert into public.frc_skills(name,domain,description) values ('Hand and power tool safety','safety','Safely select, inspect and operate common workshop tools'),('CAD fundamentals','cad','Create constrained parts and assemblies for FRC mechanisms'),('Mechanical assembly','mechanical','Build and verify robust FRC mechanisms'),('Robot wiring and CAN','electrical','Wire, label and diagnose FRC control systems'),('WPILib robot programming','software','Build, deploy and test command-based robot code'),('Match scouting','strategy','Collect accurate match data and observations'),('Drive team operations','drive_pit','Operate safely and communicate under match pressure') on conflict(name,domain) do nothing;
do $$declare t text;begin foreach t in array array['frc_skills','member_skill_progress','season_milestones','engineering_decisions'] loop execute format('alter table public.%I enable row level security',t);execute format('drop policy if exists "members view %1$s" on public.%1$I',t);execute format('create policy "members view %1$s" on public.%1$I for select to authenticated using(public.current_team_role() is not null)',t);execute format('drop policy if exists "members create %1$s" on public.%1$I',t);execute format('create policy "members create %1$s" on public.%1$I for insert to authenticated with check(public.current_team_role() is not null)',t);execute format('drop policy if exists "members update %1$s" on public.%1$I',t);execute format('create policy "members update %1$s" on public.%1$I for update to authenticated using(public.current_team_role() is not null) with check(public.current_team_role() is not null)',t);execute format('drop policy if exists "admins delete %1$s" on public.%1$I',t);execute format('create policy "admins delete %1$s" on public.%1$I for delete to authenticated using(public.is_admin())',t);end loop;end$$;
commit;
