name: CI

on:
  pull_request:
    branches: [ "dev", "main" ]
  push:
    branches: [ "dev", "main" ]

jobs:
   dashboard_web:
    name: Dashboard (Web) - Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/dashboard_web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
